### ISSUE TITLE
yarn start takes very long

### ISSUE THREAD

**Issue by leontepe** [desktop/desktop#10009]
### Describe the bug

When running `yarn start` on my local machine in my cloned directory of GH Desktop (after running `yarn` and `yarn build:dev`), the startup time is veeery long. It takes like ~2min to start up.

### Version & OS

GH Desktop 5d956d550f
macOS High Sierra 10.13.6

### Steps to reproduce the behavior

1. Clone repo on macOS
2. Run `yarn`
3. Run `yarn build:dev`
4. Run `yarn start`

### Expected behavior

It takes less than ~15s to start up. That's the speed it had on my Windows machine.

### Actual behavior

It takes way longer, roughly ~2min.

### Logs
Terminal log:
```
yarn run v1.21.1
$ cross-env NODE_ENV=development ts-node -P script/tsconfig.json script/start.ts
Server running at http://localhost:3000
ℹ ｢atl｣: Using typescript@3.4.3 from typescript
ℹ ｢atl｣: Using tsconfig.json from /Users/leontepe/projects/desktop/tsconfig.json
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Time: 21728ms
webpack built e906fe8a62d863e54879 in 42020ms
info: [ui] [AppStore] loading 0 repositories from store
debug: [ui] Unable to locate IntelliJ installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate SlickEdit installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate CodeRunner installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate Typora installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate WebStorm installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate Brackets installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate TextMate installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate RubyMine installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate PhpStorm installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate BBEdit installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate VSCodium installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate Visual Studio Code (Insiders) installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate MacVim installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate Rider installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate Android Studio installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate GoLand installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate SlickEdit installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
info: [ui] Opt in reported.
debug: [ui] Unable to locate SlickEdit installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
debug: [ui] Unable to locate SlickEdit installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
info: [ui] [Welcome] no sign in step found. ignoring...
info: [ui] [Welcome] no sign in step found. ignoring...
info: [ui] launching: 2.5.3-beta1 (Mac OS 10.13.6)
info: [ui] execPath: '/Users/leontepe/projects/desktop/dist/GitHub Desktop-dev-darwin-x64/GitHub Desktop-dev.app/Contents/Frameworks/GitHub Desktop-dev Helper (Renderer).app/Contents/MacOS/GitHub Desktop-dev Helper (Renderer)'
info: [ui] [Welcome] no sign in step found. ignoring...
info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 0.267s)
info: [ui] [Welcome] no sign in step found. ignoring...
✨  Done in 58.23s.
Leons-MBP:desktop leontepe$ yarn start
yarn run v1.21.1
$ cross-env NODE_ENV=development ts-node -P script/tsconfig.json script/start.ts
Server running at http://localhost:3000
ℹ ｢atl｣: Using typescript@3.4.3 from typescript
ℹ ｢atl｣: Using tsconfig.json from /Users/leontepe/projects/desktop/tsconfig.json
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Time: 23615ms
webpack built e906fe8a62d863e54879 in 45737ms
info: [ui] [AppStore] loading 0 repositories from store
debug: [ui] Unable to locate GoLand installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate IntelliJ installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate SlickEdit installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate CodeRunner installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate Typora installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate WebStorm installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate Brackets installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate TextMate installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate RubyMine installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate PhpStorm installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate BBEdit installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate VSCodium installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate Visual Studio Code (Insiders) installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate MacVim installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate Rider installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate Android Studio installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate SlickEdit installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
debug: [ui] Unable to locate SlickEdit installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
debug: [ui] Unable to locate SlickEdit installation
Error: Couldn't find the app
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
info: [ui] [Welcome] no sign in step found. ignoring...
info: [ui] [Welcome] no sign in step found. ignoring...
info: [ui] launching: 2.5.3-beta1 (Mac OS 10.13.6)
info: [ui] execPath: '/Users/leontepe/projects/desktop/dist/GitHub Desktop-dev-darwin-x64/GitHub Desktop-dev.app/Contents/Frameworks/GitHub Desktop-dev Helper (Renderer).app/Contents/MacOS/GitHub Desktop-dev Helper (Renderer)'
info: [ui] [Welcome] no sign in step found. ignoring...
```

### Additional context

The icon in the task bar is already showing quite early, but no window / UI.

**Comment by niik** [comment]
Hi @leontepe, I'm sorry to hear that it takes so long for you to launch the development app. I'm afraid I don't have any tips or tricks for you except to say that I believe all of us developers on the team are on macOS Catalina now.

The build performance differs greatly between machines, the build times on my MacBook Pro are close to the ones you reported seeing on Windows whereas the build times in my Windows VM are closer to the numbers you report seeing on macOS. Without knowing more about your machine performance it's hard to speculate about whether it's expected or not.

Unfortunately we're not able to offer much support related to building the application but I'd start by making sure you're running node 10+ (there's a known performance regression in Node.js versions 8.9.10 - 9.11.1) and if that doesn't help I'd follow the performance tips and tricks for webpack (https://webpack.js.org/guides/build-performance/). Seems like a good chunk of your build time is taken up by the typescript loader as well which is to be expected but it might be worth looking into if there are any performance tricks to play around with there as well.

I hope you're able to speed up your build time. Given that this issue doesn't affect regular users of the Desktop app I'm going to close it.
