### ISSUE TITLE
Can't open VS Code using shortcut.

### ISSUE THREAD

**Issue by devduttabain** [desktop/desktop#10079]
```
Error: spawn C:\WINDOWS\system32\cmd.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

Version: 2.5.3
OS: Windows 10.0.18362
```
Can't open VS Code using shortcut. **`Ctrl + Shift + A`**. showing this error.

**Comment by steveward** [comment]
@devduttabain it looks like you may be running into the same issue as #10042. See my reply in https://github.com/desktop/desktop/issues/10042#issuecomment-648955982 for more information about how to resolve this. Let me know if that doesn't get things working.
