### ISSUE TITLE
Need to reinstall GitHub Desktop every time I use it

### ISSUE THREAD

**Issue by markgbeckett** [desktop/desktop#10137]
### Each time I start GitHub Desktop on my Windows 10 PC, I need to reinstall it

I have two laptops, both Windows 10 and with similar setups. One has installed GitHub Desktop client without any issues. The other appears to install it without issue (completes installation, starts client) but once I close it, I can't find the binary again (Windows Search doesn't find the client, plus GitHub installation folder has some files, but no executable) and need to reinstall it.

### Proposed solution

If someone can spot what I am doing wrong, this will then be in the knowledge-base for others.

Thanks in advance!

**Comment by niik** [comment]
Hi @markgbeckett, thanks for opening this. I'm sorry to hear you're having problems with your GitHub Desktop installation. To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

%LocalAppData%\GitHubDesktop\SquirrelSetup.log

If no log file is being generated there you should be able to find one in the SquirrelTemp directory:

%LocalAppData%\SquirrelTemp\SquirrelSetup.log

Please upload that as an attachment.

The GitHub Desktop installer is supposed to create a start menu entry and a shortcut on your Desktop. It sounds like something is preventing that from happening.

**Comment by markgbeckett** [comment]
Hi, Thanks for getting back to me. I've attached the the two SquirrelSetup.log files, as requested. I see a couple of errors, though nothing immediately stands out as obvious to my untrained eye. Thanks again

[GitHubDesktop-SquirrelSetup.log](https://github.com/desktop/desktop/files/4880868/GitHubDesktop-SquirrelSetup.log)

[SquirrelSetup.log](https://github.com/desktop/desktop/files/4880865/SquirrelSetup.log)

**Comment by tierninho** [comment]
@markgbeckett It looks like a failed installation. Was this an upgrade or fresh installation? 

Logs:
```
2020-07-06 20:19:28> CheckForUpdateImpl: Reading RELEASES file from C:\Users\markg_000\AppData\Local\SquirrelTemp
2020-07-06 20:19:31> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2020-07-06 20:19:56> ApplyReleasesImpl: Writing files to app directory: C:\Users\markg_000\AppData\Local\GitHubDesktop\app-2.5.2
2020-07-06 20:20:06> LogHost: Rigging execution stub for GitHubDesktop_ExecutionStub.exe to C:\Users\markg_000\AppData\Local\GitHubDesktop\GitHubDesktop.exe
2020-07-06 20:21:29> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\markg_000\AppData\Local\GitHubDesktop\app-2.5.2\GitHubDesktop.exe]
2020-07-06 20:22:05> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\markg_000\AppData\Local\GitHubDesktop\app-2.5.2\GitHubDesktop.exe: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClass11_0.<InvokeProcessAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2020-07-06 20:22:11> ApplyReleasesImpl: Starting fixPinnedExecutables
2020-07-06 20:22:12> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2020-07-06 20:22:12> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2020-07-06 20:22:12> ApplyReleasesImpl: Fixing up tray icons
2020-07-06 20:22:12> ApplyReleasesImpl: cleanDeadVersions: for version 2.5.2
2020-07-06 20:22:12> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.5.2
```

I'd suggest a clean install:
Close GitHub Desktop
Delete the `%AppData%\GitHub Desktop\` directory
Delete the `%LocalAppData%\GitHubDesktop\` directory
Reinstall GitHub Desktop from desktop.github.com

It could also be related to anti-virus software (McAfee!!) and permissions to the directory as there was a similar problem in Atom https://github.com/atom/atom/issues/10383

**Comment by markgbeckett** [comment]
Thanks. While following the clean-install advice, I found a copy of the GitHubDesktop.exe executable in %LocalAppData%\GitHubDesktop\. This seems to be usable, so I manually added it to the Windows Start menu and now all seems in order. Thanks for your help.
