### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by 1900011604** [desktop/desktop#10412]
This is an old problem. I deleted all the SSH keys and use HTTPS to push. I can push on Git Bash and VS Code but not on Github Desktop. It will show:
```
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
```

The log file says this:
```
2020-08-20T09:54:12.136Z - info: [ui] [AppStore] loading 2 repositories from store
2020-08-20T09:54:12.137Z - info: [ui] [AppStore] found account: 1900011604 (1900011604)
2020-08-20T09:54:12.441Z - warn: [ui] Error refreshing account '1900011604'
Error: Cannot update an account which doesn't have a token: 1900011604
    at Object.n [as fatalError] (C:\Users\19000\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\external "path":1:1)
    at o (C:\Users\19000\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\accounts-store.ts:215:7)
    at l.tryUpdateAccount (C:\Users\19000\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\accounts-store.ts:135:6)
    at C:\Users\19000\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\accounts-store.ts:117:5
    at Array.map (<anonymous>)
    at l.refresh (C:\Users\19000\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\accounts-store.ts:114:21)
    at Xe.loadInitialState (C:\Users\19000\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\app-store.ts:1857:4)
2020-08-20T09:54:12.779Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2020-08-20T09:54:13.137Z - info: [ui] launching: 2.5.3 (Windows 10.0.18362)
2020-08-20T09:54:13.137Z - info: [ui] execPath: 'C:\Users\19000\AppData\Local\GitHubDesktop\app-2.5.3\GitHubDesktop.exe'
2020-08-20T09:54:16.654Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Python-Codes - 1900011604 (empty token)
2020-08-20T09:54:19.541Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 2.803s)
```
And I logout and login via Edge for several times but nothing changes. Deleting the Desktop entries from the Credentials Manager cannot fix the issue,

**Comment by 1900011604** [comment]
```
2020-08-20T10:06:08.665Z - info: [ui] [AppStore] adding account 1900011604 (1900011604) to store
2020-08-20T10:06:09.202Z - warn: [ui] fetchCommit: returned an error '1900011604/Python-Codes@fbc705d6cecc73d843f320f40cd2ab6d15633c81'
Error: No commit found for SHA: fbc705d6cecc73d843f320f40cd2ab6d15633c81
    at Object.t.parsedResponse (C:\Users\19000\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\http.ts:175:4)
    at x.fetchCommit (C:\Users\19000\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\api.ts:591:14)
    at c.findUserWithAPI (C:\Users\19000\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\github-user-store.ts:265:23)
    at c._loadAndCacheUser (C:\Users\19000\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\github-user-store.ts:239:17)
2020-08-20T10:06:11.861Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Python-Codes - 1900011604 (has token)
2020-08-20T10:06:14.770Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 2.835s)
```
**It can also bring this "No commit found for SHA" bug**

**Comment by 1900011604** [comment]
```
2020-08-20T10:11:05.079Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Python-Codes - 1900011604 (has token)
2020-08-20T10:11:07.969Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 2.819s)
```
I have tried one last time and it seems to be OK but the push also failed, leaving me an **Authentication failed**

**Comment by steveward** [comment]
Thanks for the report @1900011604. Here's what I'd like for you to try:

1. Close GitHub Desktop
2. Open File Explorer to the `%AppData%\GitHub` directory
3. Delete all the files in that folder.
4. Launch GitHub Desktop and try logging in again from the menu > `Options`

**Comment by 1900011604** [comment]
Do you mean ```C:\Users\(User_name)\AppData\Local\GitHubDesktop```? That doesn't work

**Comment by steveward** [comment]
@1900011604 that's the correct directory. Normally logging in again fixes these token errors. Would you mind uploading the most recent log file so I could take a closer look?

**Comment by 1900011604** [comment]
```
2020-08-20T15:38:12.800Z - info: [ui] [SignInStore] initializing OAuth flow
2020-08-20T15:38:12.801Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=45f60a68-7c9e-444e-a7d4-cd6caaddc5f2
2020-08-20T15:38:57.586Z - info: [ui] [SignInStore] initializing OAuth flow
2020-08-20T15:38:57.586Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=0849603a-c08d-4e61-b7b4-f11467ae8dc7
2020-08-20T15:40:16.120Z - error: [ui] fetchMetadata: unable to load metadata from 'https://api.github.com/meta' as a fallback
TypeError: Failed to fetch
2020-08-20T15:40:16.821Z - info: [ui] [SignInStore] initializing OAuth flow
2020-08-20T15:40:16.821Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=1df91121-7828-453e-b63f-fe8bc073559e
2020-08-20T15:41:59.275Z - info: [ui] [AppStore] adding account 1900011604 (1900011604) to store
2020-08-20T15:42:04.558Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Python-Codes - 1900011604 (has token)
2020-08-20T15:42:07.529Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 2.885s)
```

**Comment by steveward** [comment]
It looks like you have a valid token:

`2020-08-20T15:42:04.558Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Python-Codes - 1900011604 (has token)`

Can you confirm the remote URL is using HTTPS (`Repository` > `Repository Settings` > `Remote`)?

**Comment by 1900011604** [comment]
Yes, I have confirmed before.
![2020-08-20 235802](https://user-images.githubusercontent.com/65082432/90795777-0e44f100-e341-11ea-9514-e8a4da9af757.png)

**Comment by tierninho** [comment]
@1900011604 Thanks for the update. Was the issue resolved? I see you reopened it and wanted to confirm all is ok now.

**Comment by steveward** [comment]
@1900011604 unfortunately modifying the Autorun registry entries breaks GitHub Desktop. We'd like to provide a more robust solution that would prevent this error from occurring in the future, but I don't have a timeline for when that may happen. I'm going to close this issue out but let us know if you are still having any problems.

**Comment by arunohwar** [comment]
I am facing exactly the same issue as reported on this page.  I am also using HTTPS authentication.
Following are the last 5 log lines - 
2022-03-14T19:25:36.517Z - info: [ui] [Dispatcher] requesting authenticated user
2022-03-14T19:25:37.933Z - info: [ui] [SignInStore] account resolved
2022-03-14T19:25:37.934Z - info: [ui] [AppStore] adding account arunohwar (arun) to store
2022-03-14T19:25:39.419Z - info: [ui] Subscribed 'arunohwar' to Alive channel
2022-03-14T19:26:08.235Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: spring-boot-labs - arunohwar (has token)
2022-03-14T19:26:10.692Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 2.034s)
