### ISSUE TITLE
Errors appears when the repository name contains ".wiki"

### ISSUE THREAD

**Issue by sdudnic** [desktop/desktop#10414]
### Describe the bug

My repository folder name is "moldova.wiki". Because of this I can commit, but often when I try to push it does not allow me, saying that ".wiki" is not allowed. So I need to open the command line and do "git push", and that work without problems, from the command line. 
The bug appears often, but not always. Sometimes I am able to push from the GUI...

### Version & OS

Desktop Version 2.5.3
Windows 10.

### Steps to reproduce the behavior

Create a repository in a folder named "something.wiki" and try to commint and then push.
If the push is OK, retry several times. 

### Expected behavior

the Push should work as expected, without error
### Actual behavior

The push opens a GUI proposing to rename the repository containing folder

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs
```
2020-07-17T00:12:15.466Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Object.t.parsedResponse (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\http.ts:175:4)
    at x.fetchPushControl (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\api.ts:853:14)
    at Xe.refreshBranchProtectionState (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\app-store.ts:896:29)
    at C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\app-store.ts:4181:9
    at Xe.withPushPullFetch (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\app-store.ts:3766:7)
    at Xe.performFetch (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\app-store.ts:4143:5)
    at Xe.refreshIndicatorForRepository (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\app-store.ts:2880:7)
    at Xe.refreshAllSidebarIndicators (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\app-store.ts:2833:7)
2020-07-17T00:12:15.803Z - info: [ui] Background fetch for 3 repositories took 3.075sec
2020-07-17T00:27:13.782Z - warn: [ui] fetchRepository: 'myuser/moldova.wiki' returned a 404
2020-07-17T00:27:13.782Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: moldova.wiki - myuser(has token)
2020-07-17T00:27:15.204Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.322s)
2020-07-17T00:27:15.455Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Object.t.parsedResponse (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\http.ts:175:4)
    at x.fetchPushControl (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\api.ts:853:14)
    at Xe.refreshBranchProtectionState (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\app-store.ts:896:29)
    at C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\app-store.ts:4181:9
    at Xe.withPushPullFetch (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\app-store.ts:3766:7)
    at Xe.performFetch (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\app-store.ts:4143:5)
    at Xe.refreshIndicatorForRepository (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\app-store.ts:2880:7)
    at Xe.refreshAllSidebarIndicators (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\stores\app-store.ts:2833:7)
2020-07-17T00:27:15.901Z - info: [ui] Background fetch for 3 repositories took 3.176sec
2020-07-17T00:42:13.994Z - warn: [ui] fetchRepository: 'myuser/moldova.wiki' returned a 404
2020-07-17T00:42:13.995Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: moldova.wiki - myuser(has token)
2020-07-17T00:42:15.379Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.303s)
2020-07-17T00:42:15.651Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Object.t.parsedResponse (C:\Users\myuser\AppData\Local\GitHubDesktop\app-2.5.3\webpack:\app\src\lib\http.ts:175:4)
```

**Comment by tierninho** [comment]
@sdudnic Thanks for the report. In short, you cannot end a repository with the name `wiki`, so in order for it to work, please rename the repository.

You should have got an error like so:
![Screen Shot 2020-08-20 at 1 39 26 PM](https://user-images.githubusercontent.com/14828183/90836310-bed3d600-e2ea-11ea-9ee2-c3b5d222b7c9.png)

**Comment by sdudnic** [comment]
> @sdudnic Thanks for the report. In short, you cannot end a repository with the name `wiki`, so in order for it to work, please rename the repository.
> 
> You should have got an error like so:
> ![Screen Shot 2020-08-20 at 1 39 26 PM](https://user-images.githubusercontent.com/14828183/90836310-bed3d600-e2ea-11ea-9ee2-c3b5d222b7c9.png)

Please read carefully all the text before closing the issue.

**Comment by sdudnic** [comment]
I said that is possible to push but the git command. Just "git push", and it works.
And also, sometimes is possible to push via the GUI, I have this folder for long time. I will not rename it. The denial to have no ".wiki" folder is stupid, and also, as I said, works from time to time via GUI, and also always work via the command line.

**Comment by sdudnic** [comment]
@tierninho please read carrefully the issue, and then, or explain this "from time to time working" behavior, or explain why the ".wiki" shouldn't be allowed, and also why it always work via the command line, and if you have no answers on all this, please reopen my issue.

**Comment by tierninho** [comment]
So we have an open bug for pushing to wiki pages that are cloned in Desktop: https://github.com/desktop/desktop/issues/3839 which is probably what is blocking you. Please follow along there.

In general, a repository cannot be named "something.wiki", but you still can have a wiki page based off of a repository. More info about wikis is here: https://docs.github.com/en/github/building-a-strong-community/about-wikis

**Comment by sdudnic** [comment]
> So we have an open bug for pushing to wiki pages that are cloned in Desktop: #3839 which is probably what is blocking you. Please follow along there.
> 
> In general, a repository cannot be named "something.wiki", but you still can have a wiki page based off of a repository. More info about wikis is here: https://docs.github.com/en/github/building-a-strong-community/about-wikis

your documentation explains the following: 
![image](https://user-images.githubusercontent.com/35489219/90840614-bca96000-e35a-11ea-8c79-e3af6f50aef9.png)

and then you have 
![image](https://user-images.githubusercontent.com/35489219/90840712-0003ce80-e35b-11ea-86f3-e53d99b9bfea.png)

and then 
![image](https://user-images.githubusercontent.com/35489219/90840759-2aee2280-e35b-11ea-8251-7685b2fd5060.png)

**Comment by sdudnic** [comment]
this is really shitty, anyway, it creates a .wiki folder, so there is any possibility to push from the GUI, only from the command line... please fix the bug!

**Comment by hani77979** [comment]
Dd
