### ISSUE TITLE
Desktop can not figure out the uploaded PDFs

### ISSUE THREAD

**Issue by LotusOrient** [desktop/desktop#10626]
### Describe the bug

I uploaded some pdfs to the local folder however it can not feel the changes from the Desktop, so I can not push.

### Version & OS

2.5.5 with WIndows 10 Iot Enterprise

### Steps to reproduce the behavior

1. Go to the localder and paste some PDFs in the folder.
2. There is no reaction on the interface of the Github Destop.

### Expected behavior

It should displayed the new added PDFs in the change list.

### Actual behavior

No reaction on the change list.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

```
2020-09-23T01:07:20.540Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 6.698s)
2020-09-23T01:07:29.705Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 8.296s)
2020-09-23T01:07:30.458Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 21379.903s)
2020-09-23T01:07:35.015Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ZATECH-FINTECH-DOCS - LotusOrient (has token)
2020-09-23T01:07:36.279Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ZATECH-FINTECH-DOCS - LotusOrient (has token)
2020-09-23T01:07:37.544Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.379s)
2020-09-23T01:07:37.544Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/za-guanping/ZATECH-FINTECH-DOCS.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-09-23T01:07:38.802Z - info: [ui] Background fetch for 9 repositories took 21390.245sec
2020-09-23T01:07:39.907Z - info: [ui] Background fetch for 9 repositories took 26.062sec
2020-09-23T01:17:51.546Z - warn: [ui] fetchRepository: an error occurred for 'za-guanping/ZATECH-FINTECH-DOCS'
TypeError: Failed to fetch
2020-09-23T01:17:51.807Z - warn: [ui] fetchRepository: an error occurred for 'za-guanping/ZATECH-FINTECH-DOCS'
TypeError: Failed to fetch
2020-09-23T01:17:51.811Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ZATECH-FINTECH-DOCS - LotusOrient (has token)
2020-09-23T01:17:54.231Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.300s)
2020-09-23T01:17:54.231Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/za-guanping/ZATECH-FINTECH-DOCS.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-09-23T01:17:56.385Z - warn: [ui] fetchRepository: an error occurred for 'za-guanping/docs'
TypeError: Failed to fetch
2020-09-23T01:17:56.656Z - warn: [ui] fetchRepository: an error occurred for 'za-guanping/docs'
TypeError: Failed to fetch
2020-09-23T01:17:56.657Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: docs - LotusOrient (has token)
2020-09-23T01:17:59.062Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.286s)
2020-09-23T01:17:59.062Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/za-guanping/docs.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-09-23T01:18:00.344Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
TypeError: Failed to fetch
2020-09-23T01:18:02.546Z - warn: [ui] fetchRepository: an error occurred for 'LotusOrient/ZAdocs'
TypeError: Failed to fetch
2020-09-23T01:18:02.801Z - warn: [ui] fetchRepository: an error occurred for 'lotusorient/ZAdocs'
TypeError: Failed to fetch
2020-09-23T01:18:02.801Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ZAdocs - LotusOrient (has token)
2020-09-23T01:18:05.116Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.216s)
2020-09-23T01:18:05.116Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/LotusOrient/ZAdocs.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-09-23T01:18:06.405Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
TypeError: Failed to fetch
2020-09-23T01:18:07.380Z - info: [ui] Background fetch for 9 repositories took 18.255sec
2020-09-23T01:26:36.168Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.469s)
2020-09-23T01:26:45.865Z - info: [ui] [Timing] Action 'create commit' for 'GitbookV1.5.1' took 1.797s
2020-09-23T01:27:00.620Z - info: [ui] Executing push: git -c credential.helper= push origin DocV1.5.1:DocV1.5.1 --progress (took 7.234s)
2020-09-23T01:27:02.412Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.780s)
2020-09-23T01:27:37.573Z - info: [ui] Executing pull: git -c credential.helper= -c rebase.backend=merge pull --progress origin (took 2.896s)
2020-09-23T01:29:13.683Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.667s)
2020-09-23T01:29:20.687Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.180s)
2020-09-23T01:30:54.091Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.545s)
2020-09-23T01:32:23.216Z - info: [ui] [AppStore] loading 9 repositories from store
2020-09-23T01:32:23.218Z - info: [ui] [AppStore] found account: LotusOrient (嘉璐莲)
2020-09-23T01:32:23.844Z - warn: [ui] Error refreshing account 'LotusOrient'
Error: Cannot update an account which doesn't have a token: LotusOrient
    at Z (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\fatal-error.ts:3:9)
    at C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\accounts-store.ts:214:12
    at Object.tryUpdateAccount (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\accounts-store.ts:134:20)
    at C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\accounts-store.ts:114:37
    at Array.map (<anonymous>)
    at Object.refresh (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\accounts-store.ts:114:21)
    at Object.loadInitialState (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:1825:24)
2020-09-23T01:32:24.836Z - info: [ui] launching: 2.5.5 (Windows 10.0.18362)
2020-09-23T01:32:24.836Z - info: [ui] execPath: 'C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\GitHubDesktop.exe'
2020-09-23T01:33:09.663Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.205s)
2020-09-23T01:34:12.615Z - info: [ui] [AppStore] loading 9 repositories from store
2020-09-23T01:34:12.616Z - info: [ui] [AppStore] found account: LotusOrient (嘉璐莲)
2020-09-23T01:34:13.081Z - warn: [ui] Error refreshing account 'LotusOrient'
Error: Cannot update an account which doesn't have a token: LotusOrient
    at Z (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\fatal-error.ts:3:9)
    at C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\accounts-store.ts:214:12
    at Object.tryUpdateAccount (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\accounts-store.ts:134:20)
    at C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\accounts-store.ts:114:37
    at Array.map (<anonymous>)
    at Object.refresh (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\accounts-store.ts:114:21)
    at Object.loadInitialState (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:1825:24)
2020-09-23T01:34:13.587Z - info: [ui] launching: 2.5.5 (Windows 10.0.18362)
2020-09-23T01:34:13.587Z - info: [ui] execPath: 'C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\GitHubDesktop.exe'
2020-09-23T01:34:48.192Z - info: [ui] calling captureCommandOutput(where git)
2020-09-23T01:36:14.913Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.341s)
2020-09-23T01:36:17.726Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.290s)
2020-09-23T01:36:20.742Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.615s)
2020-09-23T01:36:23.743Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.445s)
2020-09-23T01:36:27.758Z - warn: [ui] fetchRepository: 'za-guanping/ZATECH-FINTECH-DOCS' returned a 404
2020-09-23T01:36:27.841Z - warn: [ui] fetchRepository: 'za-guanping/ZATECH-FINTECH-DOCS' returned a 404
2020-09-23T01:36:27.842Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ZATECH-FINTECH-DOCS - LotusOrient (empty token)
2020-09-23T01:36:30.438Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.479s)
2020-09-23T01:36:30.439Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/za-guanping/ZATECH-FINTECH-DOCS.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-09-23T01:36:31.790Z - warn: [ui] fetchRepository: 'za-guanping/docs' returned a 404
2020-09-23T01:36:31.870Z - warn: [ui] fetchRepository: 'za-guanping/docs' returned a 404
2020-09-23T01:36:31.872Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: docs - LotusOrient (empty token)
2020-09-23T01:36:34.390Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.404s)
2020-09-23T01:36:34.390Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/za-guanping/docs.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-09-23T01:36:34.825Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Ue (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\http.ts:170:11)
    at at.fetchPushControl (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\api.ts:804:7)
    at Object.refreshBranchProtectionState (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:899:41)
    at C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:4142:18
    at Object.withPushPullFetch (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:3733:5)
    at Object.performFetch (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:4107:5)
    at Object.refreshIndicatorForRepository (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:2847:48)
    at Object.refreshAllSidebarIndicators (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:2802:24)
    at C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\ui\app.tsx:220:29
2020-09-23T01:36:36.233Z - warn: [ui] fetchRepository: 'LotusOrient/ZAdocs' returned a 404
2020-09-23T01:36:36.577Z - warn: [ui] fetchRepository: 'lotusorient/ZAdocs' returned a 404
2020-09-23T01:36:36.578Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ZAdocs - LotusOrient (empty token)
2020-09-23T01:36:39.066Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.379s)
2020-09-23T01:36:39.066Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/LotusOrient/ZAdocs.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-09-23T01:36:39.506Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Ue (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\http.ts:170:11)
    at at.fetchPushControl (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\api.ts:804:7)
    at Object.refreshBranchProtectionState (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:899:41)
    at C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:4142:18
    at Object.withPushPullFetch (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:3733:5)
    at Object.performFetch (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:4107:5)
    at Object.refreshIndicatorForRepository (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:2847:48)
    at Object.refreshAllSidebarIndicators (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:2802:24)
    at C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\ui\app.tsx:220:29
2020-09-23T01:36:40.334Z - info: [ui] Background fetch for 9 repositories took 27.203sec
2020-09-23T01:36:49.250Z - info: [ui] [Timing] Action 'create commit' for 'GitbookV1.5.1' took 1.988s
2020-09-23T01:37:00.721Z - info: [ui] Executing push: git -c credential.helper= push origin DocV1.5.1:DocV1.5.1 --progress (took 2.467s)
2020-09-23T01:51:41.634Z - warn: [ui] fetchRepository: 'za-guanping/ZATECH-FINTECH-DOCS' returned a 404
2020-09-23T01:51:41.721Z - warn: [ui] fetchRepository: 'za-guanping/ZATECH-FINTECH-DOCS' returned a 404
2020-09-23T01:51:41.721Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ZATECH-FINTECH-DOCS - LotusOrient (empty token)
2020-09-23T01:51:45.251Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 3.426s)
2020-09-23T01:51:45.256Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/za-guanping/ZATECH-FINTECH-DOCS.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-09-23T01:51:46.532Z - warn: [ui] fetchRepository: 'za-guanping/docs' returned a 404
2020-09-23T01:51:46.611Z - warn: [ui] fetchRepository: 'za-guanping/docs' returned a 404
2020-09-23T01:51:46.612Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: docs - LotusOrient (empty token)
2020-09-23T01:51:49.165Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.452s)
2020-09-23T01:51:49.165Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/za-guanping/docs.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-09-23T01:51:49.599Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Ue (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\http.ts:170:11)
    at at.fetchPushControl (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\api.ts:804:7)
    at Object.refreshBranchProtectionState (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:899:41)
    at C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:4142:18
    at Object.withPushPullFetch (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:3733:5)
    at Object.performFetch (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:4107:5)
    at Object.refreshIndicatorForRepository (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:2847:48)
    at Object.refreshAllSidebarIndicators (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:2802:24)
2020-09-23T01:51:50.782Z - warn: [ui] fetchRepository: 'LotusOrient/ZAdocs' returned a 404
2020-09-23T01:51:51.128Z - warn: [ui] fetchRepository: 'lotusorient/ZAdocs' returned a 404
2020-09-23T01:51:51.129Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ZAdocs - LotusOrient (empty token)
2020-09-23T01:51:53.642Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.405s)
2020-09-23T01:51:53.647Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/LotusOrient/ZAdocs.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-09-23T01:51:54.087Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Ue (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\http.ts:170:11)
    at at.fetchPushControl (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\api.ts:804:7)
    at Object.refreshBranchProtectionState (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:899:41)
    at C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:4142:18
    at Object.withPushPullFetch (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:3733:5)
    at Object.performFetch (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:4107:5)
    at Object.refreshIndicatorForRepository (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:2847:48)
    at Object.refreshAllSidebarIndicators (C:\Users\za-guanping\Documents\GitHubDesktop_v2.1.0.0\app-2.5.5\webpack:\app\src\lib\stores\app-store.ts:2802:24)
2020-09-23T01:51:54.861Z - info: [ui] Background fetch for 9 repositories took 14.518sec
```

**Comment by tierninho** [comment]
@LotusOrient Thanks for the issue. Desktop should show the pdf file in the Changes list, but not render it as the current application only has support for image-based formats. We are tracking support for rendering here: https://github.com/desktop/desktop/issues/5009

Please add your logs so we can triage further and maybe add a screenshot -- see the Help menu in Desktop. Thanks!

**Comment by tierninho** [comment]
I see from your logs that there are some issues authenticating. Were you able to get past this and push/pull successfully, in general? However, this should have no bearing on the pdf issue.

Does the pdf issue happen for every repo and every time?

**Comment by LotusOrient** [comment]
> I see from your logs that there are some issues authenticating. Were you able to get past this and push/pull successfully, in general? However, this should have no bearing on the pdf issue.
> Does the pdf issue happen for every repo and every time?

Hi, thank you. I finally found that my colleague has set to ignore the PDFs. So I use git command to force push the PDFs to solve this  problem.
