### ISSUE TITLE
The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

### ISSUE THREAD

**Issue by TokenTip** [desktop/desktop#11023]
### Describe the bug

I belong to an organization and I have a private repository that I share with another team member. Both have admin previlages to this repository. But neither is able to fetch after initial cloning.

If I try to clone using Git Desktop version 2.4.1 Linux. On Pop-OS 20.04 LTS. 

I get the error - Sorry, I cant find any repository matching https://github.com/Tiptoken/Purdue.git

Next I tried command line cloning. That worked but asked for my git login and password. The cloning was complete. I then went back to desktop and added the repository to it. But when I fetch origin I get the  message. 
The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

when I try command line fetch after it asks for my Tokentip login and password it fails with this message
fatal: couldn't find remote ref master

### Version & OS

https://github.com/Tiptoken/Purdue.git

### Steps to reproduce the behavior

I belong to an organization and I have a private repository that I share with another team member. Both have admin previlages to this repository. But neither is able to fetch after initial cloning.

If I try to clone using Git Desktop version 2.4.1 Linux. On Pop-OS 20.04 LTS. 

I get the error - Sorry, I cant find any repository matching https://github.com/Tiptoken/Purdue.git

Next I tried command line cloning. That worked but asked for my git login and password. The cloning was complete. I then went back to desktop and added the repository to it. But when I fetch origin I get the  message. 
The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

when I try command line fetch after it asks for my Tokentip login and password it fails with this message
fatal: couldn't find remote ref master

### Expected behavior

As I have access to the repository, I am the one that created the repository. And I gave myself Admin rights on that private repository. I should have access to clone and fetch. 

### Actual behavior

Not able to fetch or clone through desktop or command line. 

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

2020-11-13T00:45:51.969Z - warn: [ui] fetchRepository: 'Tiptoken/Purdue' returned a 404
2020-11-13T00:45:52.077Z - warn: [ui] fetchRepository: 'Tiptoken/Purdue' returned a 404
2020-11-13T00:45:58.422Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Purdue - TokenTip (has token)
2020-11-13T00:45:58.791Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/Tiptoken/Purdue.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)

### Additional context
.

**Comment by TokenTip** [comment]
I did the same action on my Mac and it worked without issues. The command I do not see on my Mac in the log is:
git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin exited with an unexpected code: 128.

This particular command runs only on my Linux Git desktop.

**Comment by steveward** [comment]
Thanks for the report @TokenTip. Can you try logging out and then logging back into your GitHub account in GitHub Desktop to see if that gets things working?

**Comment by TokenTip** [comment]
@steveward - Thanks for taking time to review my issue. 

Here is an update 
Tried this this morning. Upgraded to newest version 2.5.7 on Linux still not working. Works on mac and windows. Works from command line.

at Object.withPushPullFetch (/home/xxxxxxx/webpack:/app/src/lib/stores/app-store.ts:3835:5)
    at Object.performFetch (/home/xxxxxxx/webpack:/app/src/lib/stores/app-store.ts:4209:5)
2020-11-17T13:16:24.864Z - warn: [ui] fetchRepository: 'Tiptoken/Purdue' returned a 404
2020-11-17T13:16:24.865Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Purdue - TokenTip (has token)
2020-11-17T13:16:25.347Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/Tiptoken/Purdue.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2020-11-17T13:16:25.475Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at ze (/home/xxxxxxx/webpack:/app/src/lib/http.ts:170:11)
    at ot.fetchPushControl (/home/xxxxxxx/webpack:/app/src/lib/api.ts:910:7)
    at Object.refreshBranchProtectionState (/home/xxxxxxx/webpack:/app/src/lib/stores/app-store.ts:938:41)
    at /home/xxxxxxx/webpack:/app/src/lib/stores/app-store.ts:4244:18
    at Object.withPushPullFetch (/home/xxxxxxx/webpack:/app/src/lib/stores/app-store.ts:3835:5)
    at Object.performFetch (/home/xxxxxxx/webpack:/app/src/lib/stores/app-store.ts:4209:5)
2020-11-17T13:16:25.507Z - warn: [ui] Unable to fetch issues for Tiptoken/Purdue
Error: Need a GitHubRepository that's been inserted into the database
    at Bu (/home/xxxxxxx/webpack:/app/src/lib/stores/issues-store.ts:229:11)
    at iS.constructor.getLatestUpdatedAt (/home/xxxxxxx/webpack:/app/src/lib/stores/issues-store.ts:47:5)
    at iS.constructor.refreshIssues (/home/xxxxxxx/webpack:/app/src/lib/stores/issues-store.ts:71:38)
    at Object._refreshIssues (/home/xxxxxxx/webpack:/app/src/lib/stores/app-store.ts:1651:30)
    at /home/xxxxxxx/webpack:/app/src/lib/stores/app-store.ts:4266:18
    at Object.withPushPullFetch (/home/xxxxxxx/webpack:/app/src/lib/stores/app-store.ts:3835:5)
    at Object.performFetch (/home/xxxxxxx/webpack:/app/src/lib/stores/app-store.ts:4209:5)

**Comment by steveward** [comment]
@TokenTip this looks like a specific issue with the Linux fork. Since this an organization repository it could be OAuth app restrictions causing these auth failures. I'd recommend taking a look at https://github.com/shiftkey/desktop/issues/281. At this time we can't provide support for the Linux fork in this repository, so I am going to close this out.

**Comment by TokenTip** [comment]
https://github.com/shiftkey/desktop/issues/72#issuecomment-656537145
@steveward  - I did what was described in this link and everything works fine now. Thanks for linking with the other issue above... 

This is a copy from the link above... 
https://github.com/settings/applications

Click on "The GitHub Desktop Development App"

Scroll down to "Organization access"

You can grant or revoke access to organizations individually.

**Comment by steveward** [comment]
I'm glad to hear that got things working!
