### ISSUE TITLE
Removing a Repository Locally that was deleted from Github.com

### ISSUE THREAD

**Issue by OAKO-UCONN** [desktop/desktop#11186]
### Describe the bug

When trying to delete a local repository that was deleted on github.com Github Desktop freezes.

### Version & OS

Version 2.6.0 Windows 10

### Steps to reproduce the behavior

1. Create a test repository
2. Delete that repository on github.com only.
3. Now delete it locally using Github Desktop and move to recycle bin.

### Expected behavior

Removes the local directory and application continues working.

### Actual behavior

Github desktop just froze. Have to manually restart it.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs
`2020-12-06T01:26:52.976Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 39 repositories took 15.2s of which 60672.6s paused, total 60687.7s
2020-12-06T01:26:57.476Z - info: [ui] [BranchPruner] Last prune took place in 2 minutes - skipping
2020-12-06T01:26:59.468Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.329s)
2020-12-06T01:27:10.630Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: 12-MySQL_HW_Employee_Tracker - OAKO-UCONN (has token)
2020-12-06T01:27:11.638Z - warn: [ui] fetchRepository: 'OAKO-UCONN/tDNReactPortfolio' returned a 404
2020-12-06T01:27:12.807Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at We (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchProtectedBranches (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\api.ts:936:7)
    at Object.updateBranchProtectionsFromAPI (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\app-store.ts:3493:11)
2020-12-06T01:27:12.827Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.218s)
2020-12-06T01:27:12.828Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.196s)
2020-12-06T01:27:12.828Z - info: [ui] Executing getRemotes: git remote -v (took 1.180s)
2020-12-06T01:27:12.828Z - info: [ui] Executing getRemotes: git remote -v (took 1.265s)
2020-12-06T01:27:14.009Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.013s)
2020-12-06T01:27:14.011Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/OAKO-UCONN/tDNReactPortfolio.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2020-12-06T01:27:14.703Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at We (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchPushControl (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\api.ts:910:7)
    at Object.refreshBranchProtectionState (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\app-store.ts:940:41)
    at C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\app-store.ts:4249:18
    at Object.withPushPullFetch (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\app-store.ts:3840:5)
    at Object.performFetch (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\app-store.ts:4214:5)
    at Rc.performAndScheduleFetch (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2020-12-06T01:27:16.322Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 2.727s)
2020-12-06T01:27:22.965Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: 17-NoSQL-MongoDB_HW_Fitness-Tracker-MongoDB-Atlas-Heroku - OAKO-UCONN (has token)
2020-12-06T01:27:23.192Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2020-12-06T01:27:23.225Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at We (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchProtectedBranches (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\api.ts:936:7)
    at Object.updateBranchProtectionsFromAPI (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\app-store.ts:3493:11)
2020-12-06T01:27:23.228Z - warn: [ui] fetchRepository: 'OAKO-UCONN/tDNReactPortfolio' returned a 404
2020-12-06T01:27:24.488Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: 18-PWA_HW_Progressive-Web-Apps-Budget-Online-and-Offline-Mongo-Atlas-Heroku - OAKO-UCONN (has token)
2020-12-06T01:27:27.246Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Dine_Now - OAKO-UCONN (has token)
2020-12-06T01:27:31.940Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: 21_HW_Google_Books_Search - OAKO-UCONN (has token)
2020-12-06T01:27:40.632Z - info: [ui] [AppStore] loading 39 repositories from store
2020-12-06T01:27:40.634Z - info: [ui] [AppStore] found account: OAKO-UCONN (Omar K.)
2020-12-06T01:27:42.259Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at We (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchProtectedBranches (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\api.ts:936:7)
    at Object.updateBranchProtectionsFromAPI (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\stores\app-store.ts:3493:11)
2020-12-06T01:27:42.280Z - warn: [ui] fetchRepository: 'OAKO-UCONN/tDNReactPortfolio' returned a 404
2020-12-06T01:27:42.390Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2020-12-06T01:27:42.451Z - info: [ui] launching: 2.6.0 (Windows 10.0.18363)
2020-12-06T01:27:42.451Z - info: [ui] execPath: 'C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\GitHubDesktop.exe'
2020-12-06T01:27:43.829Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.397s)
2020-12-06T01:27:55.880Z - error: [ui] `git rev-list --left-right --count fb91750c19af8b25758e6662419b1a3f52bff9a4...fb91750c19af8b25758e6662419b1a3f52bff9a4 --` exited with an unexpected code: 128.
stderr:
fatal: Invalid symmetric difference expression fb91750c19af8b25758e6662419b1a3f52bff9a4...fb91750c19af8b25758e6662419b1a3f52bff9a4

2020-12-06T01:27:56.017Z - info: [main] Error report submitted
2020-12-06T01:28:06.745Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2020-12-06T01:28:06.746Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at We (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchProtectedBranches (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\api.ts:936:7)
    at Object.updateBranchProtectionsFromAPI (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\stores\app-store.ts:3493:11)
2020-12-06T01:28:06.747Z - warn: [ui] fetchRepository: 'OAKO-UCONN/tDNReactPortfolio' returned a 404
2020-12-06T01:28:43.911Z - info: [ui] [AppStore] loading 39 repositories from store
2020-12-06T01:28:43.913Z - info: [ui] [AppStore] found account: OAKO-UCONN (Omar K.)
2020-12-06T01:28:46.048Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at We (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchProtectedBranches (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\api.ts:936:7)
    at Object.updateBranchProtectionsFromAPI (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\stores\app-store.ts:3493:11)
2020-12-06T01:28:46.090Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 2.134s)
2020-12-06T01:28:46.091Z - info: [ui] Executing getRemotes: git remote -v (took 2.147s)
2020-12-06T01:28:46.091Z - info: [ui] Executing getRemotes: git remote -v (took 2.161s)
2020-12-06T01:28:46.253Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2020-12-06T01:28:46.273Z - warn: [ui] fetchRepository: 'OAKO-UCONN/tDNReactPortfolio' returned a 404
2020-12-06T01:28:46.320Z - info: [ui] launching: 2.6.0 (Windows 10.0.18363)
2020-12-06T01:28:46.321Z - info: [ui] execPath: 'C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\GitHubDesktop.exe'
2020-12-06T01:29:16.994Z - info: [ui] [AppStore] loading 39 repositories from store
2020-12-06T01:29:16.997Z - info: [ui] [AppStore] found account: OAKO-UCONN (Omar K.)
2020-12-06T01:29:17.473Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2020-12-06T01:29:17.890Z - info: [ui] launching: 2.6.0 (Windows 10.0.18363)
2020-12-06T01:29:17.891Z - info: [ui] execPath: 'C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\GitHubDesktop.exe'
2020-12-06T01:29:19.202Z - warn: [ui] fetchRepository: 'OAKO-UCONN/tDNReactPortfolio' returned a 404
2020-12-06T01:29:20.107Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at We (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchProtectedBranches (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\api.ts:936:7)
    at Object.updateBranchProtectionsFromAPI (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\stores\app-store.ts:3493:11)
2020-12-06T01:29:20.210Z - info: [ui] Executing getCommitDiff: git log fb91750c19af8b25758e6662419b1a3f52bff9a4 -m -1 --first-parent --patch-with-raw -z --no-color -- src/App.js (took 1.060s)
2020-12-06T01:33:43.688Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 7.286s)
`

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by OAKO-UCONN** [comment]
2020-12-06T01:26:52.976Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 39 repositories took 15.2s of which 60672.6s paused, total 60687.7s
2020-12-06T01:26:57.476Z - info: [ui] [BranchPruner] Last prune took place in 2 minutes - skipping
2020-12-06T01:26:59.468Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.329s)
2020-12-06T01:27:10.630Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: 12-MySQL_HW_Employee_Tracker - OAKO-UCONN (has token)
2020-12-06T01:27:11.638Z - warn: [ui] fetchRepository: 'OAKO-UCONN/tDNReactPortfolio' returned a 404
2020-12-06T01:27:12.807Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at We (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchProtectedBranches (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\api.ts:936:7)
    at Object.updateBranchProtectionsFromAPI (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\app-store.ts:3493:11)
2020-12-06T01:27:12.827Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.218s)
2020-12-06T01:27:12.828Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.196s)
2020-12-06T01:27:12.828Z - info: [ui] Executing getRemotes: git remote -v (took 1.180s)
2020-12-06T01:27:12.828Z - info: [ui] Executing getRemotes: git remote -v (took 1.265s)
2020-12-06T01:27:14.009Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.013s)
2020-12-06T01:27:14.011Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/OAKO-UCONN/tDNReactPortfolio.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2020-12-06T01:27:14.703Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at We (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchPushControl (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\api.ts:910:7)
    at Object.refreshBranchProtectionState (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\app-store.ts:940:41)
    at C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\app-store.ts:4249:18
    at Object.withPushPullFetch (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\app-store.ts:3840:5)
    at Object.performFetch (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\app-store.ts:4214:5)
    at Rc.performAndScheduleFetch (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2020-12-06T01:27:16.322Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 2.727s)
2020-12-06T01:27:22.965Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: 17-NoSQL-MongoDB_HW_Fitness-Tracker-MongoDB-Atlas-Heroku - OAKO-UCONN (has token)
2020-12-06T01:27:23.192Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2020-12-06T01:27:23.225Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at We (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchProtectedBranches (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\api.ts:936:7)
    at Object.updateBranchProtectionsFromAPI (C:\Program Files (x86)\Google\Chrome\Application\86.0.4240.198\webpack:\app\src\lib\stores\app-store.ts:3493:11)
2020-12-06T01:27:23.228Z - warn: [ui] fetchRepository: 'OAKO-UCONN/tDNReactPortfolio' returned a 404
2020-12-06T01:27:24.488Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: 18-PWA_HW_Progressive-Web-Apps-Budget-Online-and-Offline-Mongo-Atlas-Heroku - OAKO-UCONN (has token)
2020-12-06T01:27:27.246Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Dine_Now - OAKO-UCONN (has token)
2020-12-06T01:27:31.940Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: 21_HW_Google_Books_Search - OAKO-UCONN (has token)
2020-12-06T01:27:40.632Z - info: [ui] [AppStore] loading 39 repositories from store
2020-12-06T01:27:40.634Z - info: [ui] [AppStore] found account: OAKO-UCONN (Omar K.)
2020-12-06T01:27:42.259Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at We (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchProtectedBranches (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\api.ts:936:7)
    at Object.updateBranchProtectionsFromAPI (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\stores\app-store.ts:3493:11)
2020-12-06T01:27:42.280Z - warn: [ui] fetchRepository: 'OAKO-UCONN/tDNReactPortfolio' returned a 404
2020-12-06T01:27:42.390Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2020-12-06T01:27:42.451Z - info: [ui] launching: 2.6.0 (Windows 10.0.18363)
2020-12-06T01:27:42.451Z - info: [ui] execPath: 'C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\GitHubDesktop.exe'
2020-12-06T01:27:43.829Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.397s)
2020-12-06T01:27:55.880Z - error: [ui] `git rev-list --left-right --count fb91750c19af8b25758e6662419b1a3f52bff9a4...fb91750c19af8b25758e6662419b1a3f52bff9a4 --` exited with an unexpected code: 128.
stderr:
fatal: Invalid symmetric difference expression fb91750c19af8b25758e6662419b1a3f52bff9a4...fb91750c19af8b25758e6662419b1a3f52bff9a4

2020-12-06T01:27:56.017Z - info: [main] Error report submitted
2020-12-06T01:28:06.745Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2020-12-06T01:28:06.746Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at We (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchProtectedBranches (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\api.ts:936:7)
    at Object.updateBranchProtectionsFromAPI (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\stores\app-store.ts:3493:11)
2020-12-06T01:28:06.747Z - warn: [ui] fetchRepository: 'OAKO-UCONN/tDNReactPortfolio' returned a 404
2020-12-06T01:28:43.911Z - info: [ui] [AppStore] loading 39 repositories from store
2020-12-06T01:28:43.913Z - info: [ui] [AppStore] found account: OAKO-UCONN (Omar K.)
2020-12-06T01:28:46.048Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at We (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchProtectedBranches (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\api.ts:936:7)
    at Object.updateBranchProtectionsFromAPI (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\stores\app-store.ts:3493:11)
2020-12-06T01:28:46.090Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 2.134s)
2020-12-06T01:28:46.091Z - info: [ui] Executing getRemotes: git remote -v (took 2.147s)
2020-12-06T01:28:46.091Z - info: [ui] Executing getRemotes: git remote -v (took 2.161s)
2020-12-06T01:28:46.253Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2020-12-06T01:28:46.273Z - warn: [ui] fetchRepository: 'OAKO-UCONN/tDNReactPortfolio' returned a 404
2020-12-06T01:28:46.320Z - info: [ui] launching: 2.6.0 (Windows 10.0.18363)
2020-12-06T01:28:46.321Z - info: [ui] execPath: 'C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\GitHubDesktop.exe'
2020-12-06T01:29:16.994Z - info: [ui] [AppStore] loading 39 repositories from store
2020-12-06T01:29:16.997Z - info: [ui] [AppStore] found account: OAKO-UCONN (Omar K.)
2020-12-06T01:29:17.473Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2020-12-06T01:29:17.890Z - info: [ui] launching: 2.6.0 (Windows 10.0.18363)
2020-12-06T01:29:17.891Z - info: [ui] execPath: 'C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\GitHubDesktop.exe'
2020-12-06T01:29:19.202Z - warn: [ui] fetchRepository: 'OAKO-UCONN/tDNReactPortfolio' returned a 404
2020-12-06T01:29:20.107Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at We (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\http.ts:170:11)
    at lt.fetchProtectedBranches (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\api.ts:936:7)
    at Object.updateBranchProtectionsFromAPI (C:\Users\node-reactor\AppData\Local\GitHubDesktop\app-2.6.0\webpack:\app\src\lib\stores\app-store.ts:3493:11)
2020-12-06T01:29:20.210Z - info: [ui] Executing getCommitDiff: git log fb91750c19af8b25758e6662419b1a3f52bff9a4 -m -1 --first-parent --patch-with-raw -z --no-color -- src/App.js (took 1.060s)
2020-12-06T01:33:43.688Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 7.286s)
2020-12-06T01:34:06.789Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.695s)
2020-12-06T01:34:51.918Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 38 repositories took 25.5s of which 201.8s paused, total 227.3s

**Comment by steveward** [comment]
Thanks for the report @OAKO-UCONN. I just tested this out and was unable to reproduce the same behavior in a Windows VM. Based on the log file it looks like refreshing the repository list took an unusual amount of time:

```
2020-12-06T01:34:51.918Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 38 repositories took 25.5s of which 201.8s paused, total 227.3s
```

Are you able to consistently reproduce this behavior? If you wouldn't mind testing this again that would be helpful.
