### ISSUE TITLE
EFAULT error on MacOS

### ISSUE THREAD

**Issue by avaer** [desktop/desktop#11258]
### Describe the bug

I've seen this about 5 times over the last few weeks. I get this hard crash error on attempting commit:

```Error: read EFAULT
    at Pipe.onStreamRead (internal/stream_base_commons.js:200:27)

Version: 2.6.1
OS: Mac OS 10.16.0```

### Version & OS

Version: 2.6.1
OS: Mac OS 10.16.0

### Steps to reproduce the behavior

1. Open some repo
2. Checkmark an edited file on the left hand side
3. Click commit button below files list
4. See crash

### Expected behavior

Creates a file commit.

### Actual behavior

Crash dialog.

### Logs

[2020-12-19.desktop.production.log](https://github.com/desktop/desktop/files/5719894/2020-12-19.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @avaer. Would you mind uploading the log file as an attachment? It looks like it didn't make it through.

**Comment by avaer** [comment]
[2020-12-19.desktop.production.log](https://github.com/desktop/desktop/files/5751536/2020-12-19.desktop.production.log)

**Comment by niik** [comment]
Hey @avaer, sorry to hear you're having problems with crashes! I'm trying to find some commonality around these errors so I'm wondering if you're running Big Sur on the new Apple arm processor (M1) or on a previous generation mac?

**Comment by avaer** [comment]
Big Sur M1.

**Comment by steveward** [comment]
We've had two other reports of this issue. I'm going to keep this one open for tracking and drop any new incoming reports here.

From: https://github.com/desktop/desktop/issues/11325

>It happened several times but I'm not really able to provide steps to reproduce the behavior. 

From https://github.com/desktop/desktop/issues/11068:

>Does this crash happen immediately after launch? Are you able to view a repository that's not handled by Dropbox?
>
>It originally happened because I delete a repo out from under Github (GitHub desktop was closed) I opened it and it was asked to 'locate' the repo which it couldn't find, so I pointed it to the Dropbox repo I have, which was 'smart synced'. (not the best name)


We're working to try and reproduce this but have thus far been unsuccessful.

**Comment by Androz2091** [comment]
I'm still getting the error, sometimes. Here are my logs:
```
2021-01-23T01:46:34.217Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 67.534s)
2021-01-23T01:46:34.232Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/Androz2091/node-ecole-directe.git/': Failed to connect to github.com port 443: Operation timed out

2021-01-23T01:46:35.226Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
TypeError: Failed to fetch
2021-01-23T01:46:42.865Z - warn: [ui] getFetchPollInterval: failed for androz2091/node-ecole-directe
TypeError: Failed to fetch
2021-01-23T04:02:01.560Z - info: [ui] [BranchPruner] Last prune took place in 16 hours - skipping
2021-01-23T04:59:59.857Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 75.388s)
2021-01-23T04:59:59.875Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/Androz2091/node-ecole-directe.git/': Failed to connect to github.com port 443: Operation timed out

2021-01-23T05:01:15.249Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
TypeError: Failed to fetch
2021-01-23T05:02:30.991Z - warn: [ui] getFetchPollInterval: failed for androz2091/node-ecole-directe
TypeError: Failed to fetch
2021-01-23T08:10:40.410Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.081s)
2021-01-23T08:10:40.670Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: DefinitelyTyped - Androz2091 (has token)
2021-01-23T08:10:43.903Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 3.170s)
2021-01-23T08:10:46.780Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/node-ecole-directe' took 0.845s
2021-01-23T08:19:29.071Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.106s)
2021-01-23T08:19:30.388Z - info: [ui] No submodules found. Skipping "git submodule status"
2021-01-23T08:19:33.935Z - info: [ui] No submodules found. Skipping "git submodule status"
2021-01-23T08:27:40.423Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: discord.js - Androz2091 (has token)
2021-01-23T08:27:42.098Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.638s)
2021-01-23T08:27:45.889Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 71 repositories took 33.3s of which 995.2s paused, total 1028.6s
2021-01-23T08:27:52.894Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/node-ecole-directe' took 0.702s
2021-01-23T08:28:06.424Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/node-ecole-directe' took 0.834s
2021-01-23T08:28:06.774Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: node-ecole-directe - Androz2091 (has token)
2021-01-23T08:28:11.777Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 4.906s)
2021-01-23T08:30:22.807Z - info: [ui] [BranchPruner] No branches to prune.
2021-01-23T08:30:24.490Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: discord-giveaways - Androz2091 (has token)
2021-01-23T08:30:25.651Z - info: [ui] Executing pull: git -c credential.helper= -c protocol.version=2 -c rebase.backend=merge pull --progress origin (took 1.046s)
2021-01-23T08:30:32.326Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 72 repositories took 25.5s of which 126.4s paused, total 151.9s
2021-01-23T08:30:32.406Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: discord-giveaways - Androz2091 (has token)
2021-01-23T08:30:32.520Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress Nico105/develop -b develop --` exited with an unexpected code: 128.
stderr:
fatal: A branch named 'develop' already exists.

(The error was parsed as 26: A branch with that name already exists.)
2021-01-23T08:30:32.865Z - info: [ui] [Timing] Action 'checkout branch from list' for 'androz2091/discord-giveaways' took 0.444s
2021-01-23T08:30:35.497Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: discord-giveaways - Androz2091 (has token)
2021-01-23T08:30:35.592Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress Nico105/develop -b develop --` exited with an unexpected code: 128.
stderr:
fatal: A branch named 'develop' already exists.

(The error was parsed as 26: A branch with that name already exists.)
2021-01-23T08:30:35.911Z - info: [ui] [Timing] Action 'checkout branch from list' for 'androz2091/discord-giveaways' took 0.403s
2021-01-23T08:45:32.559Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: DefinitelyTyped - Androz2091 (has token)
2021-01-23T08:45:33.735Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.101s)
2021-01-23T08:45:35.310Z - info: [ui] [BranchPruner] Last prune took place in 11 hours - skipping
2021-01-23T08:45:48.608Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/node-ecole-directe' took 0.964s
2021-01-23T08:45:49.140Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: node-ecole-directe - Androz2091 (has token)
2021-01-23T08:45:53.481Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 4.271s)
2021-01-23T08:46:24.610Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 72 repositories took 24.6s of which 45.6s paused, total 70.2s
2021-01-23T08:46:24.747Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: node-ecole-directe - Androz2091 (has token)
2021-01-23T08:46:24.844Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/node-ecole-directe' took 0.928s
2021-01-23T08:46:29.412Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 4.559s)
2021-01-23T08:50:44.222Z - info: [ui] Stats reported.
2021-01-23T08:56:58.788Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-01-23T09:03:19.300Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.541s)
2021-01-23T09:03:21.514Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/discord-giveaways' took 0.858s
2021-01-23T09:03:34.292Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 71 repositories took 24.6s of which 0.0s paused, total 24.6s
2021-01-23T09:03:37.365Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/discord-giveaways' took 0.797s
2021-01-23T09:04:39.090Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/discord-giveaways' took 0.841s
2021-01-23T09:09:53.961Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/discord-giveaways' took 0.604s
2021-01-23T09:15:22.282Z - info: [ui] [AppStore] adding repository at /Users/simon/Documents/GitHub/test-serialize-js to store
2021-01-23T13:05:19.627Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: DefinitelyTyped - Androz2091 (has token)
2021-01-23T13:05:22.075Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.394s)
2021-01-23T13:14:36.442Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: discord-giveaways - Androz2091 (has token)
2021-01-23T13:14:37.717Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.212s)
2021-01-23T13:14:38.137Z - info: [ui] [BranchPruner] No branches to prune.
2021-01-23T14:10:10.919Z - info: [ui] [BranchPruner] Pruning 0 branches that have been merged into the default branch, master (a7fdc22cd7ba824fcef06a766a8d7885bb870475), from 'pronote-api
2021-01-23T14:10:11.562Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.006s)
2021-01-23T14:10:12.678Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.680s)
2021-01-23T14:10:12.781Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune upstream (took 1.158s)
2021-01-23T14:10:28.892Z - info: [ui] [Timing] Action 'checkout branch from list' for 'androz2091/pronote-api' took 0.000s
2021-01-23T14:10:31.462Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pronote-api - Androz2091 (has token)
2021-01-23T14:10:31.591Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress master --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	src/auth.js
Please commit your changes or stash them before you switch branches.
Aborting

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
2021-01-23T14:10:32.443Z - info: [ui] [Timing] Action 'stash and checkout' for 'androz2091/pronote-api' took 0.979s
2021-01-23T14:10:40.489Z - info: [ui] No submodules found. Skipping "git submodule status"
2021-01-23T14:11:18.868Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.126s)
2021-01-23T14:11:20.100Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 73 repositories took 36.8s of which 3927.1s paused, total 3963.9s
2021-01-23T14:12:59.716Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: DefinitelyTyped - Androz2091 (has token)
2021-01-23T14:13:00.820Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.052s)
2021-01-23T14:13:31.940Z - info: [ui] [Timing] Action 'create branch' for 'androz2091/pronote-api' took 0.139s
2021-01-23T14:13:34.791Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pronote-api - Androz2091 (has token)
2021-01-23T14:13:35.349Z - info: [ui] [Timing] Action 'stash and checkout' for 'androz2091/pronote-api' took 0.541s
2021-01-23T14:13:43.703Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 72 repositories took 24.9s of which 21.4s paused, total 46.3s
2021-01-23T14:13:50.933Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/pronote-api' took 1.395s
2021-01-23T14:13:51.223Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pronote-api - Androz2091 (has token)
2021-01-23T14:13:55.956Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin fix-atrium --set-upstream --progress (took 4.614s)
2021-01-23T14:44:02.828Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.170s)
2021-01-23T14:53:55.605Z - info: [ui] [BranchPruner] No branches to prune.
2021-01-23T14:53:55.826Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.192s)
2021-01-23T14:54:01.667Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: discord-giveaways - Androz2091 (has token)
2021-01-23T14:54:08.088Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.940s)
2021-01-23T14:54:38.623Z - info: [ui] [Timing] Action 'create commit' for 'pronote-notifications/pronote-notifications-api' took 1.153s
2021-01-23T14:55:00.865Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.130s)
2021-01-23T14:55:06.506Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 72 repositories took 38.6s of which 38.0s paused, total 76.6s
2021-01-23T14:55:09.314Z - info: [ui] [Timing] Action 'create commit' for 'pronote-notifications/pronote-notifications-api' took 1.261s
2021-01-23T14:55:13.616Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pronote-notifications-api - Androz2091 (has token)
2021-01-23T14:55:19.225Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 5.207s)
2021-01-23T14:55:20.388Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.031s)
2021-01-23T14:55:59.747Z - info: [ui] [Timing] Action 'create commit' for 'pronote-notifications/pronote-notifications-api' took 1.691s
2021-01-23T14:55:59.820Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pronote-notifications-api - Androz2091 (has token)
2021-01-23T14:56:05.417Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 5.519s)
2021-01-23T15:00:59.964Z - info: [ui] [Timing] Action 'create commit' for 'pronote-notifications/pronote-notifications-api' took 1.288s
2021-01-23T15:00:59.983Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pronote-notifications-api - Androz2091 (has token)
2021-01-23T15:02:07.558Z - warn: [ui] failed fetching open PRs for repository pronote-notifications/pronote-notifications-api
TypeError: Failed to fetch
2021-01-23T15:02:07.566Z - error: [ui] Error refreshing pull requests for 'pronote-notifications/pronote-notifications-api'
TypeError: Failed to fetch
2021-01-23T15:02:16.041Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 75.995s)
2021-01-23T15:02:16.088Z - error: [ui] `git -c credential.helper= -c protocol.version=2 push origin main:main --progress` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/pronote-notifications/pronote-notifications-api.git/': Failed to connect to github.com port 443: Operation timed out

2021-01-23T15:02:41.899Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 4.208s)
2021-01-23T15:02:58.045Z - info: [ui] [Timing] Action 'create commit' for 'pronote-notifications/pronote-notifications-api' took 1.087s
2021-01-23T15:02:58.377Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pronote-notifications-api - Androz2091 (has token)
2021-01-23T15:03:05.360Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 6.894s)
2021-01-23T15:03:06.845Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.176s)
2021-01-23T15:06:37.205Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pronote-notifications-api - Androz2091 (has token)
2021-01-23T15:06:37.322Z - info: [ui] [Timing] Action 'create commit' for 'pronote-notifications/pronote-notifications-api' took 1.124s
2021-01-23T15:06:43.562Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 6.234s)
2021-01-23T15:06:45.435Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.739s)
2021-01-23T15:39:15.092Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.499s)
2021-01-23T16:13:39.519Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.242s)
2021-01-23T16:22:07.024Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.109s)
2021-01-23T16:22:09.370Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: DefinitelyTyped - Androz2091 (has token)
2021-01-23T16:22:12.583Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 3.121s)
2021-01-23T16:23:05.728Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pronote-api - Androz2091 (has token)
2021-01-23T16:23:07.471Z - info: [ui] [BranchPruner] No branches to prune.
2021-01-23T16:23:07.570Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.769s)
2021-01-23T16:23:08.222Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.210s)
2021-01-23T16:23:09.217Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune upstream (took 1.609s)
2021-01-23T16:35:30.583Z - warn: [ui] getFetchPollInterval: failed for androz2091/atlanta-emojis-mod
TypeError: Failed to fetch
2021-01-23T17:40:53.486Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: discord-giveaways - Androz2091 (has token)
2021-01-23T17:40:54.549Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.011s)
2021-01-23T17:40:59.199Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.942s)
2021-01-23T17:41:16.373Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: discord.js - Androz2091 (has token)
2021-01-23T17:41:16.703Z - info: [ui] [AppStore] adding repository at /Users/simon/Documents/GitHub/cloudflare-page-rules to store
2021-01-23T17:41:18.239Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.817s)
2021-01-23T18:03:14.558Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 74 repositories took 42.8s of which 6025.9s paused, total 6068.7s
2021-01-23T18:03:36.494Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.275s)
2021-01-23T18:03:36.815Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: DefinitelyTyped - Androz2091 (has token)
2021-01-23T18:03:38.105Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.237s)
2021-01-23T18:05:01.359Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: eris - Androz2091 (has token)
2021-01-23T18:05:15.590Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 74 repositories took 28.9s of which 80.9s paused, total 109.9s
2021-01-23T18:05:50.019Z - info: [ui] [Timing] Action 'create commit' for 'cloudflare-page-rules' took 0.998s
2021-01-23T18:05:59.499Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main --set-upstream --progress (took 5.211s)
2021-01-23T18:06:00.704Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.138s)
2021-01-23T18:06:45.449Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/cloudflare-page-rules' took 0.778s
2021-01-23T18:06:45.801Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: cloudflare-page-rules - Androz2091 (has token)
2021-01-23T18:06:50.227Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 4.343s)
2021-01-23T18:10:38.183Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.219s)
2021-01-23T18:10:41.420Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-01-23T18:10:57.558Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/atlanta-emojis-mod' took 0.912s
2021-01-23T18:10:57.874Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: atlanta-emojis-mod - Androz2091 (has token)
2021-01-23T18:11:02.910Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 4.951s)
2021-01-23T18:12:28.358Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/atlanta-emojis-mod' took 1.448s
2021-01-23T18:12:28.456Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: atlanta-emojis-mod - Androz2091 (has token)
2021-01-23T18:12:32.907Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 4.374s)
2021-01-23T18:13:22.348Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/atlanta-emojis-mod' took 0.975s
2021-01-23T18:13:22.579Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: atlanta-emojis-mod - Androz2091 (has token)
2021-01-23T18:13:27.002Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 4.343s)
2021-01-23T18:13:28.248Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.009s)
2021-01-23T18:13:57.456Z - info: [ui] [Timing] Action 'create commit' for 'androz2091/atlanta-emojis-mod' took 0.922s
2021-01-23T18:13:57.713Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: atlanta-emojis-mod - Androz2091 (has token)
2021-01-23T18:14:02.847Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 5.048s)
2021-01-23T18:17:48.691Z - info: [ui] [BranchPruner] Last prune took place in 2 hours - skipping
2021-01-23T18:28:26.393Z - info: [ui] [BranchPruner] Last prune took place in 20 hours - skipping
2021-01-23T18:28:30.255Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: discord-giveaways - Androz2091 (has token)
2021-01-23T18:28:35.186Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.563s)
2021-01-23T18:28:38.858Z - error: [main] Error: read EFAULT
    at Pipe.onStreamRead (internal/stream_base_commons.js:200:27)
2021-01-23T18:28:39.450Z - info: [main] Error report submitted
2021-01-23T18:29:20.120Z - info: [ui] [AppStore] loading 74 repositories from store
2021-01-23T18:29:20.122Z - info: [ui] [AppStore] found account: Androz2091 (Androz)
2021-01-23T18:29:23.141Z - info: [ui] [BranchPruner] Last prune took place in 20 hours - skipping
2021-01-23T18:29:23.804Z - info: [ui] launching: 2.6.2 (Mac OS 10.16.0)
2021-01-23T18:29:23.805Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
```
Note: I'm also using a Mac Mini m1


Edit: I'm getting the error ~1 time per day (I'm using GH Desktop several hours per day)

**Comment by arda-zeytin** [comment]
Hi, 

I am getting this same error on my Macbook Air M1 Big Sur. 1-2 times per day when switching from Unity Editor to Github desktop window.

Error: read EFAULT
    at Pipe.onStreamRead (internal/stream_base_commons.js:200:27)

Version: 2.6.2
OS: Mac OS 10.16.0

<img width="636" alt="Screen Shot 2021-02-06 at 16 45 53" src="https://user-images.githubusercontent.com/74360464/107119825-1666fd80-689b-11eb-9c23-0815783658c2.png">

**Comment by exevil** [comment]
Same error as above, M1 MBA, Big Sur 11.2.1.

**Comment by Androz2091** [comment]
Just wanted to remind that I'm still getting this error 2-3 times a day :wink:

**Comment by smoreface** [comment]
Just started getting these errors in the past couple weeks, M1 Macbook Air, Big Sur 11.2.3 (20D91)

**Comment by felixgeissler** [comment]
I'm also facing this issue recently with version 2.8.3, M1 MacBook Pro, Bir Sur 11.2.3

**Comment by ChALkeR** [comment]
:wave: Updating to macOS 11.4.0 or above should fix this.

**Comment by Androz2091** [comment]
Yes, I am no longer getting the error... 🤔

**Comment by sergiou87** [comment]
Using arm64 builds (the app auto updates from x64 to arm64 builds if it detects M1 devices) should make these crashes muuuuuch less frequent 😄
