### ISSUE TITLE
Cannot launch github desktop since update to 2.6.1 on 14th Dec 2020

### ISSUE THREAD

**Issue by artipathare** [desktop/desktop#11271]
### Describe the bug

I cannot launch github desktop and it gives the below error in the logs:
Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\xxxx\AppData\Local\GitHubDesktop\app-2.6.1\chrome_100_percent.pak' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()<---

    at AutoUpdater.emitError (electron/js2c/browser_init.js:17:1391)
    at electron/js2c/browser_init.js:17:1134
    at ChildProcess.<anonymous> (electron/js2c/browser_init.js:21:732)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
2020-12-21T19:33:43.706Z - info: [main] Error report submitted
2020-12-21T19:36:32.938Z - info: [main] Error report submitted
2020-12-21T19:38:25.900Z - info: [main] Error report submitted

### Version & OS

Windows 10
Desktop version 2.6.1

### Steps to reproduce the behavior

1. Go to Github desktop from Windows Start
2. Click on GitHub Desktop
3. No UI erros on launch.
4. See error above.

**Comment by niik** [comment]
Hi @artipathare sorry to hear you're having problems running GitHub Desktop. It looks like some application on your machine is preventing GitHub Desktop from applying the latest update to your machine.

```
Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\xxxx\AppData\Local\GitHubDesktop\app-2.6.1\chrome_100_percent.pak' because it is being used by another process.
```
Have you tried rebooting your machine since this error started happening? If you have and that still didn't cut it I'm afraid I have to recommend a complete reset of the application by following these steps

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let us know how that goes!

**Comment by artipathare** [comment]
Hi Markus,

I had tried rebooting, but it did not fix the issue. What fixed it was
re-installing the new version from the website.

I did not follow the steps though as I did this before I got your email.
So, just uninstalled the old version and installed the new version without
deleting the directories.
Could you please confirm that nothing else needs to be done now as
everything seems to be working fine?

Thanks,
Arti

**Comment by steveward** [comment]
@artipathare if everything is working well then you shouldn't need to take any additional steps. Let us know if you run into any other problems.
