### ISSUE TITLE
deleted repository shows up in github-desktop

### ISSUE THREAD

**Issue by tovade** [desktop/desktop#11284]
### Describe the bug

I have this issue i deleted the repository 3 days ago and it says it still exist

### Version & OS

Github desktop Version 2.6.1
windows 10

### Steps to reproduce the behavior

1. delete a repository
2. go to github desktop and fetch

### Expected behavior

I would be able to create a new repo with the same files

### Actual behavior

Gives an notification wich blocks me of making a new repo named "add this repository instead"

### Screenshots

![image](https://user-images.githubusercontent.com/66245404/103136150-2ac1b300-46be-11eb-86ed-f0784753d797.png)

![image](https://user-images.githubusercontent.com/66245404/103136157-3b722900-46be-11eb-9739-7ab1fb7f997a.png)

### Logs

remote: Repository not found.
fatal: repository 'https://github.com/tovade/AndoiBot.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2020-12-25T13:27:17.382Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Ge (C:\Users\tovade\AppData\Local\GitHubDesktop\app-2.6.1\webpack:\app\src\lib\http.ts:170:11)
    at ht.fetchPushControl (C:\Users\tovade\AppData\Local\GitHubDesktop\app-2.6.1\webpack:\app\src\lib\api.ts:926:7)
    at Object.refreshBranchProtectionState (C:\Users\tovade\AppData\Local\GitHubDesktop\app-2.6.1\webpack:\app\src\lib\stores\app-store.ts:928:39)
    at C:\Users\tovade\AppData\Local\GitHubDesktop\app-2.6.1\webpack:\app\src\lib\stores\app-store.ts:4085:18
    at Object.withPushPullFetch (C:\Users\tovade\AppData\Local\GitHubDesktop\app-2.6.1\webpack:\app\src\lib\stores\app-store.ts:3682:5)
    at Object.performFetch (C:\Users\tovade\AppData\Local\GitHubDesktop\app-2.6.1\webpack:\app\src\lib\stores\app-store.ts:4050:5)
2020-12-25T13:27:18.680Z - warn: [ui] fetchAll: 'repos/tovade/AndoiBot/issues?state=open' returned a 404
2020-12-25T13:27:26.811Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: AndoiBot - tovade (has token)
2020-12-25T13:27:28.681Z - info: [ui] Executing pull: git -c credential.helper= -c protocol.version=2 -c rebase.backend=merge pull --progress origin (took 1.590s)
2020-12-25T13:27:28.912Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Ge (C:\Users\tovade\AppData\Local\GitHubDesktop\app-2.6.1\webpack:\app\src\lib\http.ts:170:11)
    at ht.fetchPushControl (C:\Users\tovade\AppData\Local\GitHubDesktop\app-2.6.1\webpack:\app\src\lib\api.ts:926:7)
    at Object.refreshBranchProtectionState (C:\Users\tovade\AppData\Local\GitHubDesktop\app-2.6.1\webpack:\app\src\lib\stores\app-store.ts:928:39)
    at C:\Users\tovade\AppData\Local\GitHubDesktop\app-2.6.1\webpack:\app\src\lib\stores\app-store.ts:3801:45
    at Object.withPushPullFetch (C:\Users\tovade\AppData\Local\GitHubDesktop\app-2.6.1\webpack:\app\src\lib\stores\app-store.ts:3682:5)
2020-12-25T13:27:37.419Z - info: [main] opening in browser: https://github.com/tovade/AndoiBot/issues/new/choose

**Comment by tovade** [comment]
this is annoying me alot

**Comment by steveward** [comment]
@tovade thanks for the report. Just to confirm -- you deleted the repository on GitHub and are now trying to recreate it in GitHub Desktop with the same files? Are you wanting to publish the repository to GitHub again?

It's likely that the remote URL for the repository is still set if you did not modify the local repository. You can check this by going to `Repository` > `Repository Settings` > `Remote`.

**Comment by tovade** [comment]
im making a new repo yes

**Comment by steveward** [comment]
@tovade can you give some more details about what you are wanting to do? It's difficult to provide you with the correct steps without more information. Deleting a repository on GitHub does not delete the repository in GitHub Desktop. If you need to delete a repository in GitHub Desktop you can right-click on it and select `Remove`. You can then create a new repository and add your files to it.
