### ISSUE TITLE
Cannot commit, npm cannot find module npx-cli.js'

### ISSUE THREAD

**Issue by cl0vrfi3ld** [desktop/desktop#11428]
### Describe the bug

When I try to commit changes, I get an error that states
```
Commit failed - exit code 1 received, with output: '/c/Users/mjlev/AppData/Roaming/npm/npx: line 5: cygpath: command not found
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'C:\GitHubDesktop\app-2.6.2\resources\app\git\node_modules\npm\bin\npx-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### Version & OS

Version 2.6.2 | Win 10 19042.746

### Steps to reproduce the behavior

1. Make a change in a repo
2. Select changes
3. Click: commit to `branch`

### Expected behavior

My changes get committed as normal

### Actual behavior

Error modal pops up with error mentioned in first question

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

``` 2021-01-20T04:56:31.140Z - info: [ui] Executing pull: git -c credential.helper= -c protocol.version=2 -c rebase.backend=merge pull --progress origin (took 2.718s)
2021-01-20T05:28:59.546Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.448s)
2021-01-20T05:38:48.884Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 33 repositories took 5.8s of which 0.0s paused, total 5.8s
2021-01-20T05:40:18.159Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
stderr:
/c/Users/GitHubDesktop/AppData/Roaming/npm/npx: line 5: cygpath: command not found
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'C:\Users\GitHubDesktop\AppData\Local\GitHubDesktop\app-2.6.2\resources\app\git\node_modules\npm\bin\npx-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

2021-01-20T05:40:18.160Z - info: [ui] [Timing] Action 'create commit' for 'REPO' took 1.011s
```

**Comment by steveward** [comment]
Thanks for the report @1MaddieX. GitHub Desktop ships with an internal version of Git which we use for all actions inside the app. As such the environment within which your commit hooks execute will likely not exactly match that of your normal environment.

You can take a look at  https://github.com/desktop/desktop/issues/9351 and see if the workaround in https://github.com/desktop/desktop/issues/9351#issuecomment-604425781 is applicable to your situation. One user also had success by changing the husky command from `"pre-commit": "lint-staged"` to`"pre-commit": "npx lint-staged"`.

[This comment](https://github.com/desktop/desktop/issues/10326#issuecomment-751263702) and [this comment](https://github.com/desktop/desktop/issues/10999#issuecomment-749106311) also have some potential workarounds for this issue. 

I hope that is helpful!

**Comment by toadeelali** [comment]
> npx lint-staged

npx lint-staged fixed the issue for me. Thanks!

**Comment by 23leliana32** [comment]
Oh i joined to do that for ya xD
