### ISSUE TITLE
Trying to contribute - error ../node_modules/keytar: Command failed. Exit code: 1 

### ISSUE THREAD

**Issue by maifeeulasad** [desktop/desktop#11423]
I was trying to clone GitHub desktop and build and run it, Then I encountered this error : 
```
error /home/maifee/Desktop/desktop/node_modules/keytar: Command failed.
Exit code: 1
```

Complete log : 
```
 maifee@maifee-ubuntu  ~/Desktop/desktop  development  yarn install
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning file-loader@2.0.0: Invalid bin field for "file-loader".
warning sha.js@2.4.9: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[4/6] ⠈ electron-chromedriver
[2/6] ⠈ keytar
[-/6] ⠈ waiting...
[5/6] ⠈ electron
error /home/maifee/Desktop/desktop/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/maifee/Desktop/desktop/node_modules/keytar
Output:
prebuild-install WARN install No prebuilt binaries found (target=14.15.4 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.15.4 | linux | x64
gyp info find Python using Python version 3.7.5 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v14.15.4/node-v14.15.4-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.15.4/node-v14.15.4-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.15.4/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.15.4/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/maifee/Desktop/desktop/node_modules/keytar/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/maifee/.cache/node-gyp/14.15.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/maifee/.cache/node-gyp/14.15.4',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/maifee/.cache/node-gyp/14.15.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/maifee/Desktop/desktop/node_modules/keytar',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-62-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/maifee/Desktop/desktop/node_modules/keytar

```

To reproduce : 
```
git clone https://github.com/desktop/desktop.git
cd desktop
yarn install
```

OS : 
```
Ubuntu 18.04.5 LTS
```

**Comment by sergiou87** [comment]
Hi @maifeeulasad ! 👋 

Did you install the additional dependencies mentioned in https://github.com/desktop/desktop/blob/development/docs/contributing/setup-linux.md#ubuntu-1404-and-later ?
```
$ sudo apt install libsecret-1-dev libgconf-2-4
```

`libsecret` is needed to get `keytar` working. Please, give that a try and let me know if it worked! 🤞

**Comment by maifeeulasad** [comment]
@sergiou87 that worked, thanks. Thanks a lot.
