### ISSUE TITLE
Unhandled exception: System.UnauthorizedAccessException: Access to the path

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#11482]
### Describe the bug

Installation is not ending successfully 

### Version & OS
Win 7 Enterprise SP1

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
Last setup available from https://desktop.github.com/ version 2.6.2.0  96,0 MB (100.726.392 bytes)

### Steps to reproduce the behavior
Run setup GitHubDesktopSetup.exe

### Expected behavior
the installation end inspected.

### Logs
2021-01-29 15:07:53> Program: Starting Squirrel Updater: --createShortcut GitHubDesktop.exe -l StartMenu,Desktop
2021-01-29 15:07:53> ApplyReleasesImpl: About to create shortcuts for GitHubDesktop.exe, rootAppDir C:\Users\tiziano.tremonti\AppData\Local\GitHubDesktop
2021-01-29 15:07:53> Unhandled exception: System.UnauthorizedAccessException: Access to the path 'C:\Users\tiziano.tremonti\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Squirrel.UpdateManager.ApplyReleasesImpl.getLinkTarget(ShortcutLocation location, String title, String applicationName, Boolean createDirectoryIfNecessary)
   at Squirrel.UpdateManager.ApplyReleasesImpl.linkTargetForVersionInfo(ShortcutLocation location, IPackage package, FileVersionInfo versionInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.CreateShortcutsForExecutable(String exeName, ShortcutLocation locations, Boolean updateOnly, String programArguments, String icon)
   at Squirrel.Update.Program.Shortcut(String exeName, String shortcutArgs, String processStartArgs, String icon)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

Thanks For support me !

**Comment by steveward** [comment]
Sorry to hear you're having trouble installing GitHub Desktop @tt-se. I was recently able to install GitHub Desktop on Windows 7 Professional SP1 without issue, so this may be a specific problem with your environment. Are you running any antivirus/security software on this machine that could be preventing the installation from completing?
