### ISSUE TITLE
Cannot log in my GitHub account on GitHub Desktop

### ISSUE THREAD

**Issue by YumiiK** [desktop/desktop#11506]
### Describe the bug

I cannot log in to my GitHub account on GitHub Desktop.

### Version & OS

Version 2.6.2 on Windows 10

### Steps to reproduce the behavior

1. Click on 'File'
2. Click on 'Options'
3. Click on  'Sign in' next to 'GitHub.com'
4. Click on  'Continue with browser'
5. Click on  'Open GitHubDesktop.exe'
6. See error

### Expected behavior

Be able to log in.

### Actual behavior

Pop up error info.

### Screenshots

![image](https://user-images.githubusercontent.com/38561046/106459134-5fe6cf80-64cc-11eb-8e6c-a91ff13fe816.png)

### Logs

2021-02-01T12:26:55.778Z - info: [main] Received possible protocol arguments: 4
2021-02-01T12:26:55.778Z - info: [main] Processing protocol url
2021-02-01T12:26:55.793Z - info: [ui] [Dispatcher] requesting authenticated user
2021-02-01T12:26:55.860Z - info: [main] Received possible protocol arguments: 3
2021-02-01T12:26:55.863Z - info: [main] Processing protocol url
2021-02-01T12:26:57.086Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
Error: Hello there, wayfaring stranger. If you’re reading this then you probably didn’t see our blog post a couple of years back announcing that this API would go away: http://git.io/17AROg Fear not, you should be able to get what you need from the shiny new Events API instead.
    at Ge (C:\Users\47017\AppData\Local\GitHubDesktop\app-2.6.2\webpack:\app\src\lib\http.ts:170:11)
    at ht.fetchAccount (C:\Users\47017\AppData\Local\GitHubDesktop\app-2.6.2\webpack:\app\src\lib\api.ts:650:7)
    at ft (C:\Users\47017\AppData\Local\GitHubDesktop\app-2.6.2\webpack:\app\src\lib\api.ts:1229:11)
    at Object.dispatchURLAction (C:\Users\47017\AppData\Local\GitHubDesktop\app-2.6.2\webpack:\app\src\ui\dispatcher\dispatcher.ts:1657:17)
2021-02-01T12:26:57.088Z - warn: [ui] fetchUser: failed with endpoint https://api.github.com
Error: Hello there, wayfaring stranger. If you’re reading this then you probably didn’t see our blog post a couple of years back announcing that this API would go away: http://git.io/17AROg Fear not, you should be able to get what you need from the shiny new Events API instead.
    at Ge (C:\Users\47017\AppData\Local\GitHubDesktop\app-2.6.2\webpack:\app\src\lib\http.ts:170:11)
    at ht.fetchAccount (C:\Users\47017\AppData\Local\GitHubDesktop\app-2.6.2\webpack:\app\src\lib\api.ts:650:7)
    at ft (C:\Users\47017\AppData\Local\GitHubDesktop\app-2.6.2\webpack:\app\src\lib\api.ts:1229:11)
    at Object.dispatchURLAction (C:\Users\47017\AppData\Local\GitHubDesktop\app-2.6.2\webpack:\app\src\ui\dispatcher\dispatcher.ts:1657:17)
2021-02-01T12:26:57.089Z - info: [ui] [SignInStore] error with OAuth flow
Error: Hello there, wayfaring stranger. If you’re reading this then you probably didn’t see our blog post a couple of years back announcing that this API would go away: http://git.io/17AROg Fear not, you should be able to get what you need from the shiny new Events API instead.
    at Ge (C:\Users\47017\AppData\Local\GitHubDesktop\app-2.6.2\webpack:\app\src\lib\http.ts:170:11)
    at ht.fetchAccount (C:\Users\47017\AppData\Local\GitHubDesktop\app-2.6.2\webpack:\app\src\lib\api.ts:650:7)
    at ft (C:\Users\47017\AppData\Local\GitHubDesktop\app-2.6.2\webpack:\app\src\lib\api.ts:1229:11)
    at Object.dispatchURLAction (C:\Users\47017\AppData\Local\GitHubDesktop\app-2.6.2\webpack:\app\src\ui\dispatcher\dispatcher.ts:1657:17)

**Comment by steveward** [comment]
Thanks for the report @YumiiK. Are you behind a firewall or proxy server that could be interfering with your connection to GitHub? It'd be helpful if you could run two commands from PowerShell to diagnose this issue:

`ping -n 10 api.github.com`
`tracert api.github.com`

Let me know the output of those commands.

**Comment by YumiiK** [comment]
Yes, I'm using a proxy. When I turned it down and tried, it still failed to log in. And I found the output of the second command is the same whether I turned on the proxy or not.

The output of `ping -n 10 api.github.com`:

> 正在 Ping api.github.com [192.30.255.116] 具有 32 字节的数据:
> 来自 192.30.255.116 的回复: 字节=32 时间=295ms TTL=48
> 来自 192.30.255.116 的回复: 字节=32 时间=289ms TTL=48
> 来自 192.30.255.116 的回复: 字节=32 时间=297ms TTL=48
> 请求超时。
> 来自 192.30.255.116 的回复: 字节=32 时间=291ms TTL=48
> 来自 192.30.255.116 的回复: 字节=32 时间=294ms TTL=48
> 请求超时。
> 请求超时。
> 来自 192.30.255.116 的回复: 字节=32 时间=287ms TTL=48
> 来自 192.30.255.116 的回复: 字节=32 时间=288ms TTL=48
> 
> 192.30.255.116 的 Ping 统计信息:
>     数据包: 已发送 = 10，已接收 = 7，丢失 = 3 (30% 丢失)，
> 往返行程的估计时间(以毫秒为单位):
>     最短 = 287ms，最长 = 297ms，平均 = 291ms

The output of `tracert api.github.com`:

> 通过最多 30 个跃点跟踪
> 到 api.github.com [192.30.255.116] 的路由:
> 
>   1    10 ms     6 ms     4 ms  phicomm.me [192.168.2.1]
>   2     7 ms    13 ms    13 ms  Broadcom.Home [192.168.1.1]
>   3     8 ms    18 ms     8 ms  100.64.0.1
>   4    14 ms    14 ms    14 ms  111.175.201.13
>   5    15 ms     *        *     111.175.209.49
>   6    32 ms    38 ms    27 ms  202.97.67.57
>   7    27 ms    29 ms    27 ms  202.97.94.134
>   8    29 ms    27 ms     *     202.97.12.1
>   9   240 ms   250 ms   242 ms  202.97.13.26
>  10   243 ms   250 ms     *     118.85.205.246
>  11   308 ms   298 ms   291 ms  ae1.cs1.ams17.nl.eth.zayo.com [64.125.29.78]
>  12     *        *        *     请求超时。
>  13     *        *        *     请求超时。
>  14     *        *        *     请求超时。
>  15     *        *        *     请求超时。
>  16     *        *        *     请求超时。
>  17   294 ms   283 ms   291 ms  ae2.cs1.sea1.us.eth.zayo.com [64.125.29.26]
>  18     *        *      282 ms  ae1.mcs1.sea1.us.eth.zayo.com [64.125.28.133]
>  19   533 ms   320 ms   297 ms  64.125.188.97.IPYX-243981-001-ZYO.zip.zayo.com [64.125.188.97]
>  20     *        *        *     请求超时。
>  21     *        *        *     请求超时。
>  22     *        *        *     请求超时。
>  23   295 ms     *      289 ms  lb-192-30-255-116-sea.github.com [192.30.255.116]

**Comment by steveward** [comment]
@YumiiK unfortunately it looks like you may be hitting an issue most often caused by firewall restrictions. Are you able to try using a VPN to see if that succeeds?

**Comment by YumiiK** [comment]
@steveward Thanks for your help. I just solved this problem by reinstalling GitHub Desktop.
I uninstalled it by Windows ControlPanel and deleted all user config files manually, then reinstalled it. (Only uninstalling by ControlPanel did not work out.)

**Comment by soyadokio** [comment]
> @steveward Thanks for your help. I just solved this problem by reinstalling GitHub Desktop. I uninstalled it by Windows ControlPanel and deleted all user config files manually, then reinstalled it. (Only uninstalling by ControlPanel did not work out.)

Hi @YumiiK Could you please list the user config files deleted manually?
