### ISSUE TITLE
Cannot login my github accound on github desktop

### ISSUE THREAD

**Issue by nonusx** [desktop/desktop#11512]
### Describe the bug

Shortcut pointer of my computer is bat.

So the application on my computer cannot open the browser.

**But** your software requires me to use browser to verify.

It won't open.

I don’t want to change the computer or reinstall the OS.

![image](https://user-images.githubusercontent.com/60562136/106558909-8efa5100-655f-11eb-9fbf-59c5466b7632.png)

![image](https://user-images.githubusercontent.com/60562136/106558932-9ae61300-655f-11eb-8935-64633c2e50a6.png)

Just like this infinite loop.

### Version & OS

OS: Windows 10

Github desktop version: 2.6.1

Browser version: Chrome-Dev 89.0.4385.0

![image](https://user-images.githubusercontent.com/60562136/106558874-7f7b0800-655f-11eb-9cd9-f3f650ff4a7b.png)

### Steps to reproduce the behavior

1. Open the Github-Desktop
2. Click on File | Options
3. Select "Sign in github.com": 
![image](https://user-images.githubusercontent.com/60562136/106559335-38d9dd80-6560-11eb-9ba9-9286f3e7a618.png)
4. Select "Continue with browser"
5. See error

### Expected behavior

I do not have a "Expected behavior"

I just hope it(github desktop) can try username and password to login, Instead of just try "browser".

### Actual behavior

Infinited loop for login.

### Screenshots

![image](https://user-images.githubusercontent.com/60562136/106559796-ef3dc280-6560-11eb-96f8-921c04e727bc.png)

### Logs

```log
2021-02-02T05:46:35.126Z - info: [main] Received possible protocol arguments: 2
2021-02-02T05:46:35.128Z - error: [main] Malformed launch arguments received: C:\Users\86136\AppData\Local\GitHubDesktop\app-2.6.1\GitHubDesktop.exe,--allow-file-access-from-files
2021-02-02T05:46:35.128Z - info: [main] Received possible protocol arguments: 2
2021-02-02T05:46:35.128Z - error: [main] Malformed launch arguments received: C:\Users\86136\AppData\Local\GitHubDesktop\app-2.6.1\GitHubDesktop.exe,--allow-file-access-from-files
2021-02-02T05:46:43.205Z - info: [ui] [AppStore] loading 0 repositories from store
2021-02-02T05:46:45.917Z - info: [ui] launching: 2.6.1 (Windows 10.0.17763)
2021-02-02T05:46:45.917Z - info: [ui] execPath: 'C:\Users\86136\AppData\Local\GitHubDesktop\app-2.6.1\GitHubDesktop.exe'
2021-02-02T05:46:49.539Z - info: [ui] Stats reported.
2021-02-02T05:46:50.304Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 5.587s)
2021-02-02T05:47:06.655Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: ����һ���������� ---> System.Net.WebException: ���������Ѿ��ر�: ����ʱ�������� ---> System.IO.IOException: �޷��Ӵ��������ж�ȡ����: Զ������ǿ�ȹر���һ�����е����ӡ��� ---> System.Net.Sockets.SocketException: Զ������ǿ�ȹر���һ�����е����ӡ�
   �� System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   �� System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   �� System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   �� System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   �� System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   �� System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.FileDownloader.<>c__DisplayClass2_2.<<DownloadFile>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.FileDownloader.<DownloadFile>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Update.Program.<Update>d__5.MoveNext()
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   �� System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   �� System.Threading.Tasks.Task.Wait()
   �� Squirrel.Update.Program.executeCommandLine(String[] args)
   �� Squirrel.Update.Program.main(String[] args)
   �� Squirrel.Update.Program.Main(String[] args)
---> (�ڲ��쳣 #0) System.Net.WebException: ���������Ѿ��ر�: ����ʱ�������� ---> System.IO.IOException: �޷��Ӵ��������ж�ȡ����: Զ������ǿ�ȹر���һ�����е����ӡ��� ---> System.Net.Sockets.SocketException: Զ������ǿ�ȹر���һ�����е����ӡ�
   �� System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   �� System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   �� System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   �� System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   �� System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   �� System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.FileDownloader.<>c__DisplayClass2_2.<<DownloadFile>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.FileDownloader.<DownloadFile>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Update.Program.<Update>d__5.MoveNext()<---


    at AutoUpdater.emitError (electron/js2c/browser_init.js:17:1391)
    at electron/js2c/browser_init.js:17:1134
    at ChildProcess.<anonymous> (electron/js2c/browser_init.js:21:732)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
2021-02-02T05:47:33.003Z - info: [ui] calling captureCommandOutput(where git)
2021-02-02T05:47:38.693Z - info: [ui] [SignInStore] initializing OAuth flow
2021-02-02T05:47:38.693Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=91785632-dd1f-4ad3-9e98-a6485ad2f7e5
2021-02-02T05:47:38.733Z - error: [main] Call to openExternal failed: 'Error: Failed to open'
2021-02-02T05:51:49.155Z - error: [main] Failed opening issue creation page
Error: Failed to open
2021-02-02T05:52:07.007Z - info: [ui] [SignInStore] initializing OAuth flow
2021-02-02T05:52:07.007Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=5716405e-b57e-457e-99cf-728ae5d9daf6
2021-02-02T05:52:07.011Z - error: [main] Call to openExternal failed: 'Error: Failed to open'
2021-02-02T06:04:30.838Z - info: [ui] [SignInStore] initializing OAuth flow
2021-02-02T06:04:30.843Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=82fce33f-8421-4f04-8cab-ed001bf6e561
2021-02-02T06:04:30.849Z - error: [main] Call to openExternal failed: 'Error: Failed to open'
2021-02-02T06:14:10.277Z - info: [ui] [SignInStore] initializing OAuth flow
2021-02-02T06:14:10.282Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=ebc3366e-2f22-4b5c-85a4-e48640eb58c8
2021-02-02T06:14:10.285Z - error: [main] Call to openExternal failed: 'Error: Failed to open'
```

### Additional context

Shortcut of my computer is bad. I don't want to change the computer or reinstall the new OS. I also don't want to fix the shortcut.

I just hope it can try username and password to login the accound.

I have used this computer to log in to other github accounts, so it seems that I can only log in to my account using a browser...

What should I do?

**Comment by Rexogamer** [comment]
When you say "the shortcut is bad", what exactly do you mean? And what's preventing the fix?

As far as I'm aware the ability to log in using your username and password via the app was removed due to API changes, so OAuth is the only option.

**Comment by nonusx** [comment]
There are "the shortcut" of windows

**Comment by steveward** [comment]
@368573607 it's no longer possible to authenticate via username and password in GitHub Desktop. Could you try changing your default browser on Windows to see if that allows you to authenticate?

**Comment by nonusx** [comment]
Thank you.

I decided not to use desktop
