### ISSUE TITLE
Unable to authenticate during clone attempt (EDIT: tried to clone subdirectory)

### ISSUE THREAD

**Issue by thorstenlang** [desktop/desktop#11536]
### Describe the bug
Authentication failure when attempting to clone repository: https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester

**EDIT:
I've been trying to clone a subdirectory, which is why it didn't work!!**

### Version & OS

GitHub Desktop version 2.6.2  
OS: Windows 10 Pro 20H2
VPN deactivated (https://github.com/desktop/desktop/issues/11506#issuecomment-770907254)

### Steps to reproduce the behavior

1. File> Clone repository
2. Paste URL
3. press "Clone"
4. See error: Authentication failed to associate with https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester. Please enter your username and password and try again.
5. fill in username and password 
6. fail again
7. rinse and repeat :-)

### Expected behavior

I expected to be able to clone the repository

### Actual behavior

A clear and concise description of what actually happened.

![github desktop authentication error](https://user-images.githubusercontent.com/25455227/107026058-1fc06f00-67a2-11eb-87b4-11daf80da8d4.png)

Add screenshots to help explain your problem, if applicable.

### Logs

2021-02-05T10:09:41.199Z - error: [ui] Error checking for updates
Error: GitHub Desktop was not able to contact the update server. Ensure you have internet connectivity and try again.
    at file:///C:/Users/t_lan/AppData/Local/GitHubDesktop/app-2.6.2/resources/app/renderer.js:45:170457
    at onAutoUpdaterError (file:///C:/Users/t_lan/AppData/Local/GitHubDesktop/app-2.6.2/resources/app/renderer.js:45:170738)
    at CallbacksRegistry.apply (electron/js2c/renderer_init.js:131:792)
    at electron/js2c/renderer_init.js:83:5068
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:83:4308)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
2021-02-05T10:09:57.617Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.196s)
2021-02-05T10:10:00.191Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.142s)
2021-02-05T10:10:00.916Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 12.1s of which 0.0s paused, total 12.1s
2021-02-05T10:11:39.321Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.538s)
2021-02-05T10:12:25.291Z - info: [ui] calling captureCommandOutput(where git)
2021-02-05T10:12:28.864Z - info: [ui] [AppStore] removing account thorstenlang (thorstenlang) from store
2021-02-05T10:12:54.574Z - info: [ui] [SignInStore] initializing OAuth flow
2021-02-05T10:12:54.575Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=0583cfec-df6e-4185-8602-73d8ef59ceaa
2021-02-05T10:13:08.267Z - info: [main] Received possible protocol arguments: 4
2021-02-05T10:13:08.268Z - info: [main] Processing protocol url
2021-02-05T10:13:08.274Z - info: [ui] [Dispatcher] requesting authenticated user
2021-02-05T10:13:08.444Z - info: [main] Received possible protocol arguments: 3
2021-02-05T10:13:08.445Z - info: [main] Processing protocol url
2021-02-05T10:13:08.955Z - info: [ui] [SignInStore] account resolved
2021-02-05T10:13:08.955Z - info: [ui] [AppStore] adding account thorstenlang (thorstenlang) to store
2021-02-05T10:13:28.927Z - info: [main] Received possible protocol arguments: 4
2021-02-05T10:13:28.927Z - info: [main] Processing protocol url
2021-02-05T10:13:28.951Z - info: [ui] [Dispatcher] requesting authenticated user
2021-02-05T10:13:28.965Z - warn: [ui] requestAuthenticatedUser was not called with valid OAuth state. This is likely due to a browser reloading the callback URL. Contact GitHub Support if you believe this is an error
2021-02-05T10:13:29.171Z - info: [main] Received possible protocol arguments: 3
2021-02-05T10:13:29.172Z - info: [main] Processing protocol url
2021-02-05T10:25:32.496Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.596s)
2021-02-05T10:25:34.506Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 7 repositories took 4.9s of which 0.0s paused, total 4.9s
2021-02-05T10:26:14.381Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d' and 'thorstenlang'
2021-02-05T10:26:14.991Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester D:\Documents\GitHub\ifcbimtester` exited with an unexpected code: 128.
stderr:
Cloning into 'D:\Documents\GitHub\ifcbimtester'...
fatal: repository 'https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-05T10:27:20.912Z - info: [ui] storing generic credentials for 'github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d' and 'thorstenlang'
2021-02-05T10:27:20.916Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d' and 'thorstenlang'
2021-02-05T10:27:21.495Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester D:\Documents\GitHub\ifcbimtester` exited with an unexpected code: 128.
stderr:
Cloning into 'D:\Documents\GitHub\ifcbimtester'...
fatal: repository 'https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-05T10:34:17.635Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d' and 'thorstenlang'
2021-02-05T10:34:18.234Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester D:\Documents\GitHub\ifcbimtester` exited with an unexpected code: 128.
stderr:
Cloning into 'D:\Documents\GitHub\ifcbimtester'...
fatal: repository 'https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-05T10:34:33.316Z - info: [ui] [AppStore] removing account thorstenlang (thorstenlang) from store
2021-02-05T10:34:43.291Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d' and 'thorstenlang'
2021-02-05T10:34:44.109Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester D:\Documents\GitHub\ifcbimtester` exited with an unexpected code: 128.
stderr:
Cloning into 'D:\Documents\GitHub\ifcbimtester'...
fatal: repository 'https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-05T10:35:08.678Z - info: [ui] storing generic credentials for 'github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d' and 'thorstenlang'
2021-02-05T10:35:08.698Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d' and 'thorstenlang'
2021-02-05T10:35:09.360Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester D:\Documents\GitHub\ifcbimtester` exited with an unexpected code: 128.
stderr:
Cloning into 'D:\Documents\GitHub\ifcbimtester'...
fatal: repository 'https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-05T10:37:48.930Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d' and 'thorstenlang'
2021-02-05T10:37:49.861Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester D:\Documents\GitHub\ifcbimtester` exited with an unexpected code: 128.
stderr:
Cloning into 'D:\Documents\GitHub\ifcbimtester'...
fatal: repository 'https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-05T10:40:51.805Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.036s)
2021-02-05T10:40:54.582Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.453s)
2021-02-05T10:41:00.788Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.025s)
2021-02-05T10:41:00.852Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 10.7s of which 0.0s paused, total 10.7s
2021-02-05T11:02:27.615Z - info: [ui] [AppStore] loading 8 repositories from store
2021-02-05T11:02:27.766Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-02-05T11:02:28.045Z - info: [ui] launching: 2.6.2 (Windows 10.0.19042)
2021-02-05T11:02:28.046Z - info: [ui] execPath: 'C:\Users\t_lan\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe'
2021-02-05T11:02:48.828Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d' and 'thorstenlang'
2021-02-05T11:02:49.461Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester D:\Documents\GitHub\ifcbimtester` exited with an unexpected code: 128.
stderr:
Cloning into 'D:\Documents\GitHub\ifcbimtester'...
fatal: repository 'https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-05T11:03:16.217Z - info: [ui] calling captureCommandOutput(where git)
2021-02-05T11:03:32.031Z - info: [ui] [AppStore] loading 8 repositories from store
2021-02-05T11:03:32.166Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-02-05T11:03:32.277Z - info: [ui] launching: 2.6.2 (Windows 10.0.19042)
2021-02-05T11:03:32.278Z - info: [ui] execPath: 'C:\Users\t_lan\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe'
2021-02-05T11:03:45.027Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d' and 'thorstenlang'
2021-02-05T11:03:45.657Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester D:\Documents\GitHub\ifcbimtester` exited with an unexpected code: 128.
stderr:
Cloning into 'D:\Documents\GitHub\ifcbimtester'...
fatal: repository 'https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-05T11:04:02.890Z - info: [ui] storing generic credentials for 'github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d' and 'thorstenlang'
2021-02-05T11:04:02.901Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d' and 'thorstenlang'
2021-02-05T11:04:03.509Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester D:\Documents\GitHub\ifcbimtester` exited with an unexpected code: 128.
stderr:
Cloning into 'D:\Documents\GitHub\ifcbimtester'...
fatal: repository 'https://github.com/IfcOpenShell/IfcOpenShell/tree/5f8e77c29281ffd778ee530051fbe45b68eae19d/src/ifcbimtester/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-05T11:06:23.799Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 2.4s of which 0.0s paused, total 2.4s

**Comment by steveward** [comment]
@thorstenlang it looks like your repository's remote URL is incorrect. Go to the file menu in GitHub Desktop and select `Repository` > `Repository Settings` > `Remote`. You will want the URL to be this:

https://github.com/IfcOpenShell/IfcOpenShell

Let me know if you run into any other issues.
