### ISSUE TITLE
I couldnt Log in to My account using GIT HUB desktop

### ISSUE THREAD

**Issue by INMANN1** [desktop/desktop#11805]
### Describe the bug

My https://github.com/AtradiusGroup is working
while i try to login with same Username  in GIT DESKTOP APP i fails to Login

### Version & OS

version: 2.6.6

### Steps to reproduce the behavior

1. Go to 'FILE'
2. Click on '.CLONE Repository'
3. Scroll down to 'URL'
4. 
![image](https://user-images.githubusercontent.com/71826116/111262082-970edb80-8649-11eb-9832-58ee70a32a35.png)

prompting for Username

Username: INMANN1
pwd as  https://github.com/AtradiusGroup

### Expected behavior

it should log into the GIT desktop

### Actual behavior

it is not accepting my user credentials

### Screenshots

![image](https://user-images.githubusercontent.com/71826116/111262217-e3f2b200-8649-11eb-8b2a-91cc3681b07f.png)

### Logs

Cloning into 'C:\GIT_Clone1\RK-BBT-OSB-AssessCustomer'...
remote: The `AtradiusGroup' organization has enabled or enforced SAML SSO. To access
remote: this repository, you must re-authorize the OAuth Application `GitHub Desktop`.
fatal: unable to access 'https://github.com/AtradiusGroup/RK-BBT-OSB-AssessCustomer.git/': The requested URL returned error: 403

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2021-03-16T05:40:34.258Z - info: [ui] storing generic credentials for 'github.com' and 'manideepthi.annapareddy@atradius.com'
2021-03-16T05:40:34.284Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/AtradiusGroup/RK-BBT-OSB-AssessCustomer.git - INMANN1 (has token)
2021-03-16T05:40:40.821Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=main clone --recursive --progress -- https://github.com/AtradiusGroup/RK-BBT-OSB-AssessCustomer.git C:\GIT_Clone1\RK-BBT-OSB-AssessCustomer (took 5.168s)
2021-03-16T05:40:40.828Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=main clone --recursive --progress -- https://github.com/AtradiusGroup/RK-BBT-OSB-AssessCustomer.git C:\GIT_Clone1\RK-BBT-OSB-AssessCustomer` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\GIT_Clone1\RK-BBT-OSB-AssessCustomer'...
remote: The `AtradiusGroup' organization has enabled or enforced SAML SSO. To access
remote: this repository, you must re-authorize the OAuth Application `GitHub Desktop`.
fatal: unable to access 'https://github.com/AtradiusGroup/RK-BBT-OSB-AssessCustomer.git/': The requested URL returned error: 403

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2021-03-16T05:51:45.143Z - error: [ui] Failed to look up repository clone info for 'https://github.com/AtradiusGroup/RK-BBT-OSB-AssessCustomer.git'
Error: Resource protected by organization SAML enforcement. You must grant your OAuth token access to this organization.
    at qe (C:\Users\mannapar\AppData\Local\GitHubDesktop\app-2.6.6\webpack:\app\src\lib\http.ts:170:11)
    at pt.fetchRepositoryCloneInfo (C:\Users\mannapar\AppData\Local\GitHubDesktop\app-2.6.6\webpack:\app\src\lib\api.ts:635:11)
    at Object.clone [as onSubmit] (C:\Users\mannapar\AppData\Local\GitHubDesktop\app-2.6.6\webpack:\app\src\ui\clone-repository\clone-repository.tsx:628:11)
2021-03-16T05:51:45.144Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/AtradiusGroup/RK-BBT-OSB-AssessCustomer.git - INMANN1 (has token)
2021-03-16T05:51:52.292Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=main clone --recursive --progress -- https://github.com/AtradiusGroup/RK-BBT-OSB-AssessCustomer.git C:\GIT_Clone1\RK-BBT-OSB-AssessCustomer (took 5.559s)
2021-03-16T05:51:52.300Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=main clone --recursive --progress -- https://github.com/AtradiusGroup/RK-BBT-OSB-AssessCustomer.git C:\GIT_Clone1\RK-BBT-OSB-AssessCustomer` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\GIT_Clone1\RK-BBT-OSB-AssessCustomer'...
remote: The `AtradiusGroup' organization has enabled or enforced SAML SSO. To access
remote: this repository, you must re-authorize the OAuth Application `GitHub Desktop`.
fatal: unable to access 'https://github.com/AtradiusGroup/RK-BBT-OSB-AssessCustomer.git/': The requested URL returned error: 403

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2021-03-16T05:52:05.743Z - info: [ui] storing generic credentials for 'github.com' and 'INMANN1'
2021-03-16T05:52:05.761Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/AtradiusGroup/RK-BBT-OSB-AssessCustomer.git - INMANN1 (has token)
2021-03-16T05:52:12.413Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=main clone --recursive --progress -- https://github.com/AtradiusGroup/RK-BBT-OSB-AssessCustomer.git C:\GIT_Clone1\RK-BBT-OSB-AssessCustomer (took 5.270s)
2021-03-16T05:52:12.421Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=main clone --recursive --progress -- https://github.com/AtradiusGroup/RK-BBT-OSB-AssessCustomer.git C:\GIT_Clone1\RK-BBT-OSB-AssessCustomer` exited with an unexpected code: 128.

**Comment by steveward** [comment]
@INMANN1 thanks for the report. It looks like you need to approve GitHub Desktop for use in your organization:

`remote: The AtradiusGroup' organization has enabled or enforced SAML SSO. To access remote: this repository, you must re-authorize the OAuth Application GitHub Desktop`.`

See [this help guide](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/approving-oauth-apps-for-your-organization) for how to do that. You can also follow [this guide](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/requesting-organization-approval-for-oauth-apps) if you need to request approval. I hope that helps! Let me know if run into any issues.
