### ISSUE TITLE
Error message on 'Check for updates'

### ISSUE THREAD

**Issue by niajthat** [desktop/desktop#11999]
I have GitHub Desktop version 2.5.0 installed on Windows Server 2012 R2.

When I go to Help -> About GitHub Desktop, I see red text warning me of old version.

When I click in 'Check for updates', I get this error message - "The application is missing a dependency it needs to check and install updates. This is very, very bad."

Following shows up in logs:
2021-04-14T15:35:19.365Z - error: [ui] Error checking for updates
Error: The application is missing a dependency it needs to check and install updates. This is very, very bad.
    at Object.t.parseError (file:///C:/Users/username/AppData/Local/GitHubDesktop/app-2.5.0/resources/app/renderer.js:29:126947)
    at onAutoUpdaterError (file:///C:/Users/username/AppData/Local/GitHubDesktop/app-2.5.0/resources/app/renderer.js:12:106800)
    at CallbacksRegistry.apply (electron/js2c/renderer_init.js:1804:29)
    at electron/js2c/renderer_init.js:1603:21
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:1593:7)
    at EventEmitter.emit (events.js:203:13)
    at Object.onMessage (electron/js2c/renderer_init.js:2399:16)

**Comment by steveward** [comment]
@niajthat thanks for the report. Did you install GitHub Desktop via the standard installation method?

I would recommend trying a fresh download from http://desktop.github.com to see if it installs successfully.

**Comment by steveward** [comment]
Also, please note that Windows Server 2012 is not an officially supported operating system, but it should work since it is based on Windows 8.
