### ISSUE TITLE
Gets stuck on "fetch: Hang on..." when other repos are from a different username / private

### ISSUE THREAD

**Issue by ninmonkey** [desktop/desktop#12014]
### Describe the bug

The app hangs on "fetch: Hang on..." when other repos are from a different username / private. I searched issues and didn't see one that matched

![image](https://user-images.githubusercontent.com/3892031/115118183-aeeabf80-9f67-11eb-87fa-abcfc1611371.png)

### Steps to reproduce the behavior

Setup: 

- Two github logins exist, `Ben` and `ninmonkey`
- `ninmonkey` has been using  `git desktop` without problems /w github
- a repo `Ben` owns was cloned using `Ben`'s credentials on the cli ( external of the app )
- `github desktop` is still logged in as `ninmonkey`
- `add local repo` was used on `Ben`'s cloned repo

### Expected behavior

- `ninmonkey` should be able to open `github desktop` on a repo `ninmonkey` owns

### Actual behavior

- app hangs, preventing any `push or pull`
- It's trying to use `ninmonkey` creds on `Bob`'s private repo, and failing
- Then it hangs there, so `ninmonkey` can't use `ninmonkey`'s repo when `ninmonkey` is logged in

### Version & OS

| Name | Version|
|- | - |
| Github desktop | Version 2.7.2 |
| Windows 10 / Pro | 2004 19041.928 |

### Logs

<details><summary>

full log (Click to Expand)
</summary>
log

```log
2021-04-17T15:02:25.733Z - info: [ui] [AppStore] loading 70 repositories from store
2021-04-17T15:02:25.734Z - info: [ui] [AppStore] found account: ninmonkey (Jake Bolton)
2021-04-17T15:02:26.037Z - info: [ui] launching: 2.7.2 (Windows 10.0.19041)
2021-04-17T15:02:26.038Z - info: [ui] execPath: 'C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\GitHubDesktop.exe'
2021-04-17T15:02:26.659Z - info: [ui] Stats reported.
2021-04-17T15:04:10.027Z - warn: [ui] fetchRepository: '<Ben>/<PrivateRepo1>' returned a 404
2021-04-17T15:04:10.132Z - warn: [ui] fetchRepository: '<Ben>/<PrivateRepo1>' returned a 404
2021-04-17T15:04:10.133Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: <PrivateRepo1> - ninmonkey (has token)
2021-04-17T15:04:10.933Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/<Ben>/<PrivateRepo1>.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-04-17T15:04:11.455Z - warn: [ui] fetchRepository: '<Ben>/<PrivateRepo1>' returned a 404
2021-04-17T15:04:11.558Z - warn: [ui] fetchRepository: '<Ben>/<PrivateRepo1>' returned a 404
2021-04-17T15:04:11.559Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: <PrivateRepo1> (has token)
2021-04-17T15:04:12.105Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/<Ben>/<PrivateRepo2>.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-04-17T15:04:12.429Z - warn: [ui] fetchRepository: '<Ben>/<PrivateRepo2>' returned a 404
2021-04-17T15:04:12.529Z - warn: [ui] fetchRepository: '<Ben>/<PrivateRepo2>' returned a 404
2021-04-17T15:04:12.530Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: <PrivateRepo2> - ninmonkey (has token)
2021-04-17T15:04:13.041Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/<Ben>/<PrivateRepo2>.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-04-17T15:04:16.002Z - warn: [ui] fetchRepository: '<Ben>/<PrivateRepo3>' returned a 404
2021-04-17T15:04:16.110Z - warn: [ui] fetchRepository: '<Ben>/<PrivateRepo3>' returned a 404
2021-04-17T15:04:16.111Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: <PrivateRepo3> - ninmonkey (has token)
2021-04-17T15:04:16.643Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/<Ben>/<PrivateRepo3>.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-04-17T15:04:20.485Z - warn: [ui] fetchRepository: 'ninmonkey/powershellDocs_compare.ps1' returned a 404
2021-04-17T15:04:20.568Z - warn: [ui] fetchRepository: 'ninmonkey/powershellDocs_compare.ps1' returned a 404
2021-04-17T15:04:20.569Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: powershellDocs_compare.ps1 - ninmonkey (has token)
2021-04-17T15:09:11.332Z - info: [ui] [Timing] Action 'create commit' for 'ninmonkey/Ninmonkey.Cheat-Sheets' took 0.794s
2021-04-17T15:12:11.221Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at Ke (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\http.ts:170:11)
    at gt.fetchProtectedBranches (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\api.ts:977:7)
    at Object.updateBranchProtectionsFromAPI (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:3359:11)
2021-04-17T15:12:11.223Z - warn: [ui] fetchRepository: '<Ben>/<PrivateRepo4>' returned a 404
2021-04-17T15:12:11.223Z - warn: [ui] fetchMentionables: 'repos/<Ben>/<PrivateRepo4>/mentionables/users' returned a 404
2021-04-17T15:12:11.223Z - warn: [ui] fetchAll: 'repos/<Ben>/<PrivateRepo4>/issues?state=open' returned a 404
2021-04-17T15:12:11.225Z - warn: [ui] fetchAll: 'repos/<Ben>/<PrivateRepo4>/pulls?state=open' returned a 404
2021-04-17T15:12:11.346Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/<Ben>/<PrivateRepo4>.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-04-17T15:12:11.568Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Ke (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\http.ts:170:11)
    at gt.fetchPushControl (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\api.ts:951:7)
    at Object.refreshBranchProtectionState (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:955:39)
    at C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:4170:32
    at Object.withPushPullFetch (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:3773:5)
    at Object.performFetch (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:4126:5)
    at Ro.performAndScheduleFetch (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2021-04-17T15:12:14.094Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: <PrivateRepo5> - ninmonkey (has token)
2021-04-17T15:12:14.641Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/<Ben>/<PrivateRepo5>.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-04-17T15:12:14.813Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Ke (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\http.ts:170:11)
    at gt.fetchPushControl (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\api.ts:951:7)
    at Object.refreshBranchProtectionState (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:955:39)
    at C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:4170:32
    at Object.withPushPullFetch (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:3773:5)
    at Object.performFetch (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:4126:5)
2021-04-17T15:12:15.199Z - warn: [ui] fetchAll: 'repos/<Ben>/<PrivateRepo>/issues?state=open' returned a 404
2021-04-17T15:12:21.130Z - info: [ui] calling captureCommandOutput(where git)
2021-04-17T15:13:00.075Z - info: [ui] calling captureCommandOutput(where git)
2021-04-17T15:13:00.188Z - info: [ui] launching Windows Terminal at path: "C:\Users\<username>\AppData\Local\Microsoft\WindowsApps\wt.exe"
2021-04-17T15:18:32.855Z - warn: [ui] fetchAll: 'repos/<Ben>/<PrivateRepo>/pulls?state=open' returned a 404
2021-04-17T15:20:06.006Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
```
</details>

### Additional context

Important section of the log 
```log
2021-04-17T15:02:25.733Z - info: [ui] [AppStore] loading 70 repositories from store
2021-04-17T15:02:25.734Z - info: [ui] [AppStore] found account: ninmonkey (Jake Bolton)
2021-04-17T15:02:26.037Z - info: [ui] launching: 2.7.2 (Windows 10.0.19041)
2021-04-17T15:02:26.038Z - info: [ui] execPath: 'C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\GitHubDesktop.exe'
2021-04-17T15:02:26.659Z - info: [ui] Stats reported.
2021-04-17T15:04:10.027Z - warn: [ui] fetchRepository: '<Ben>/<PrivateRepo1>' returned a 404
2021-04-17T15:04:10.132Z - warn: [ui] fetchRepository: '<Ben>/<PrivateRepo1>' returned a 404
2021-04-17T15:04:10.133Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: <PrivateRepo1> - ninmonkey (has token)
2021-04-17T15:04:10.933Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/<Ben>/<PrivateRepo1>.git/' not found

fatal: repository 'https://github.com/<Ben>/<PrivateRepo4>.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-04-17T15:12:11.568Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Ke (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\http.ts:170:11)
    at gt.fetchPushControl (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\api.ts:951:7)
    at Object.refreshBranchProtectionState (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:955:39)
    at C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:4170:32
    at Object.withPushPullFetch (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:3773:5)
    at Object.performFetch (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:4126:5)
    at Ro.performAndScheduleFetch (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2021-04-17T15:12:14.094Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: <PrivateRepo5> - ninmonkey (has token)
2021-04-17T15:12:14.641Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/<Ben>/<PrivateRepo5>.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-04-17T15:12:14.813Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Ke (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\http.ts:170:11)
    at gt.fetchPushControl (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\api.ts:951:7)
    at Object.refreshBranchProtectionState (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:955:39)
    at C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:4170:32
    at Object.withPushPullFetch (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:3773:5)
    at Object.performFetch (C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.7.2\webpack:\app\src\lib\stores\app-store.ts:4126:5)
2021-04-17T15:12:15.199Z - warn: [ui] fetchAll: 'repos/<Ben>/<PrivateRepo>/issues?state=open' returned a 404
2021-04-17T15:12:21.130Z - info: [ui] calling captureCommandOutput(where git)
2021-04-17T15:13:00.075Z - info: [ui] calling captureCommandOutput(where git)
2021-04-17T15:13:00.188Z - info: [ui] launching Windows Terminal at path: "C:\Users\<username>\AppData\Local\Microsoft\WindowsApps\wt.exe"
2021-04-17T15:18:32.855Z - warn: [ui] fetchAll: 'repos/<Ben>/<PrivateRepo>/pulls?state=open' returned a 404
2021-04-17T15:20:06.006Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
```
```

**Comment by joriswitteman** [comment]
Just implement #3707 (multiple account support) already.

's been four years!
