### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by tspeidel-ey** [desktop/desktop#12163]
### Installation fails with an error
My GitHub desktop was working fine. Then, one day, double-clicking the executable did not launch the application. I decided to re-install and even after manually purging the folder, I am unable to install it. I'm not sure where to start troubleshooting. I also tried the msi version to no avail.

### Version & OS
GitHub Desktop version I'm trying to install: 2.8.1
MS Windows OS Version:                10.0.18363 N/A Build 18363

### Screenshots
![image](https://user-images.githubusercontent.com/66435255/117364631-6134e900-ae7b-11eb-9dfa-e4b112a249ed.png)

### Logs
Output of `SquirrelSetup.log`

`
2021-05-06 14:38:36> Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC

2021-05-06 14:38:36> Program: Starting install, writing to C:\Users\tspeidel\AppData\Local\SquirrelTemp

2021-05-06 14:38:36> Program: About to install to: C:\Users\tspeidel\AppData\Local\gitkraken
2021-05-06 14:38:36> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\tspeidel\AppData\Local\gitkraken\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2021-05-06 14:38:36> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\tspeidel\AppData\Local\gitkraken\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2021-05-06 14:38:36> CheckForUpdateImpl: Reading RELEASES file from C:\Users\tspeidel\AppData\Local\SquirrelTemp
2021-05-06 14:38:36> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2021-05-06 14:38:36> ApplyReleasesImpl: Writing files to app directory: C:\Users\tspeidel\AppData\Local\gitkraken\app-7.5.5
2021-05-06 14:38:40> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\tspeidel\AppData\Local\gitkraken\app-7.5.5\gitkraken.exe]
2021-05-06 14:38:45> ApplyReleasesImpl: Starting fixPinnedExecutables
`

**Comment by steveward** [comment]
@tspeidel-suncor thanks for the issue. Unfortunately it looks like the log you shared is only showing sections related to GitKraken, and not GitHub Desktop. Could you see if there is an installation log in`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`? It may also be worth checking `%LocalAppData%\SquirrelTemp\SquirrelSetup.log` to see if anything related to GitHub Desktop has been added there.

Are you running any antivirus/security software on this machine that could be blocking the installation from completing?

**Comment by tspeidel-ey** [comment]
Thanks for letting me know. It appears I included the wrong log (after giving up, I tried installing a different GUI). 
I now believe that the AV is preventing the installation

In particular, the corporate AV (McAfee) is preventing `test.exe` during installation. This was not the case in past installations (I suppose because something changed either on the AV side or GitHub Desktop). I have contacted my IT department, but perhaps this is something the GitHub Desktop team should be aware.

NETWORK\myusername ran C:\Users\myusername\AppData\Local\SquirrelTemp\Update.exe, which tried to access the file C:\Users\myusername\AppData\Local\GitHubDesktop\app-2.8.2-beta1\resources\app\git\usr\bin\test.exe, violating the rule "C2C23RD FEB", and was blocked. For information about how to respond to this event, see KB85494

Unless you know of a workaround, this can be closed.

**Comment by steveward** [comment]
Thanks for the update @tspeidel-suncor. We've seen this happen after we push out updates to the embedded Git that ships with GitHub Desktop. McAfee often incorrectly flags binaries as malicious. Is it possible your IT department can whitelist the file or installation directory? Whitelisting `C:\Users\<Your_user>\AppData\Local\GitHubDesktop` would be the best option.

I'll close this out but let me know if I can assist with any questions you or your IT department has.
