### ISSUE TITLE
Github unable to fetch authenticated users on Vm ware 

### ISSUE THREAD

**Issue by X058729** [desktop/desktop#12169]
#Github unable to fetch authenticated users on my VMwares.

Please find the logs

2021-05-07T06:36:35.395Z - info: [ui] [AppStore] loading 0 repositories from store
2021-05-07T06:36:36.988Z - info: [ui] launching: 2.8.1 (Windows 10.0.18363)
2021-05-07T06:36:36.988Z - info: [ui] execPath: 'C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-07T06:36:39.113Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2021-05-07T06:36:45.762Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 9.498s)
2021-05-07T06:36:57.091Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T06:36:57.093Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=2bf4b284-1d92-4a37-9414-f6ce289f803b
2021-05-07T06:37:07.771Z - info: [main] Received possible protocol arguments: 4
2021-05-07T06:37:07.771Z - info: [main] Processing protocol url
2021-05-07T06:37:07.811Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T06:37:08.540Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T06:37:10.430Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T07:55:08.421Z - info: [ui] [AppStore] loading 0 repositories from store
2021-05-07T07:55:10.104Z - info: [ui] launching: 2.8.1 (Windows 10.0.18363)
2021-05-07T07:55:10.105Z - info: [ui] execPath: 'C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-07T07:55:11.917Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2021-05-07T07:55:16.825Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 7.390s)
2021-05-07T07:55:21.957Z - info: [ui] calling captureCommandOutput(where git)
2021-05-07T07:55:54.767Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T07:55:54.775Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=bec0367a-43ca-41c4-b34a-190515c3736d
2021-05-07T07:56:05.973Z - info: [main] Received possible protocol arguments: 4
2021-05-07T07:56:05.974Z - info: [main] Processing protocol url
2021-05-07T07:56:06.087Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T07:56:06.975Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T07:56:09.019Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T07:56:15.314Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T07:56:15.400Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=40b403cc-6967-49fc-bff8-7e5a1f0b4a16
2021-05-07T07:58:46.183Z - info: [ui] [AppStore] loading 0 repositories from store
2021-05-07T07:58:46.823Z - info: [ui] launching: 2.8.1 (Windows 10.0.18363)
2021-05-07T07:58:46.823Z - info: [ui] execPath: 'C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-07T07:58:49.327Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.698s)
2021-05-07T07:58:49.421Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2021-05-07T07:58:55.963Z - info: [ui] calling captureCommandOutput(where git)
2021-05-07T07:59:01.822Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T07:59:01.823Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=c4877d10-8917-4cfb-9ab7-86ea242010a2
2021-05-07T07:59:10.311Z - info: [main] Received possible protocol arguments: 4
2021-05-07T07:59:10.311Z - info: [main] Processing protocol url
2021-05-07T07:59:10.335Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T07:59:11.119Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T07:59:13.096Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:01:06.702Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:01:06.837Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=43105d41-ac3c-4581-812a-12c4558b2dd9
2021-05-07T08:01:38.683Z - info: [main] Received possible protocol arguments: 2
2021-05-07T08:01:38.683Z - error: [main] Malformed launch arguments received: C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe,--allow-file-access-from-files
2021-05-07T08:01:40.425Z - info: [ui] [AppStore] loading 0 repositories from store
2021-05-07T08:01:41.071Z - info: [ui] launching: 2.8.1 (Windows 10.0.18363)
2021-05-07T08:01:41.072Z - info: [ui] execPath: 'C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-07T08:01:43.840Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.918s)
2021-05-07T08:01:43.887Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2021-05-07T08:01:47.344Z - info: [ui] calling captureCommandOutput(where git)
2021-05-07T08:01:47.866Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:01:47.871Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=23315cf9-17d6-4551-8330-341928c34a66
2021-05-07T08:02:29.461Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:02:29.461Z - info: [main] Processing protocol url
2021-05-07T08:02:29.524Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:02:30.304Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:02:32.264Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:02:46.906Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:02:46.909Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=5aa4041c-fb81-4bbf-82ce-501180cb0463
2021-05-07T08:03:20.589Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:03:20.589Z - info: [main] Processing protocol url
2021-05-07T08:03:20.637Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:03:21.403Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:03:21.408Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:05:11.037Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:05:11.074Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=c1d712cc-35c8-4a6b-8df7-d7d87f11ecea
2021-05-07T08:05:59.874Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:05:59.874Z - info: [main] Processing protocol url
2021-05-07T08:05:59.908Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:06:00.688Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:06:00.689Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:15:14.465Z - info: [ui] [AppStore] loading 0 repositories from store
2021-05-07T08:15:15.004Z - info: [ui] launching: 2.8.1 (Windows 10.0.18363)
2021-05-07T08:15:15.004Z - info: [ui] execPath: 'C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-07T08:15:17.160Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.270s)
2021-05-07T08:15:18.082Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2021-05-07T08:15:20.847Z - info: [ui] calling captureCommandOutput(where git)
2021-05-07T08:15:23.458Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:15:23.459Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=4532a754-18c9-48eb-9ada-4762f3ef7037
2021-05-07T08:15:28.672Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:15:28.672Z - info: [main] Processing protocol url
2021-05-07T08:15:28.682Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:15:29.413Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:15:31.210Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:21:20.495Z - info: [ui] [AppStore] loading 0 repositories from store
2021-05-07T08:21:21.164Z - info: [ui] launching: 2.8.1 (Windows 10.0.18363)
2021-05-07T08:21:21.164Z - info: [ui] execPath: 'C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-07T08:21:22.882Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2021-05-07T08:21:26.186Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 5.305s)
2021-05-07T08:21:34.318Z - info: [ui] Executing getConfigValueInPath: git config -z --global user.name (took 1.174s)
2021-05-07T08:21:35.494Z - info: [ui] calling captureCommandOutput(where git)
2021-05-07T08:21:37.605Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:21:37.607Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=730d8087-e0bb-4250-b72d-e9565fd0a710
2021-05-07T08:22:04.079Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:22:04.079Z - info: [main] Processing protocol url
2021-05-07T08:22:04.157Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:22:04.976Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:22:06.793Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:22:21.727Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:22:21.727Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=71ef1bc8-b7ca-4ae8-8719-c3ebc767a3e0
2021-05-07T08:22:25.794Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:22:25.794Z - info: [main] Processing protocol url
2021-05-07T08:22:25.811Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:22:26.169Z - info: [main] Received possible protocol arguments: 3
2021-05-07T08:22:26.582Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:22:26.583Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:22:28.339Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:22:28.342Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=62599274-a3d9-49bd-a11e-a1dad4f59d2e
2021-05-07T08:22:32.188Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:22:32.188Z - info: [main] Processing protocol url
2021-05-07T08:22:32.202Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:22:32.945Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:22:32.946Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:25:51.527Z - info: [main] Received possible protocol arguments: 2
2021-05-07T08:25:51.530Z - error: [main] Malformed launch arguments received: C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe,--squirrel-firstrun
2021-05-07T08:25:54.437Z - info: [ui] [AppStore] loading 0 repositories from store
2021-05-07T08:25:55.280Z - info: [ui] launching: 2.8.1 (Windows 10.0.18363)
2021-05-07T08:25:55.280Z - info: [ui] execPath: 'C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-07T08:25:56.483Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2021-05-07T08:25:57.938Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 3.160s)
2021-05-07T08:26:04.280Z - info: [ui] calling captureCommandOutput(where git)
2021-05-07T08:26:05.546Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:26:05.547Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=ba4dc635-32d8-44f3-817d-15463fe848fa
2021-05-07T08:26:14.511Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:26:14.511Z - info: [main] Processing protocol url
2021-05-07T08:26:14.591Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:26:15.516Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:26:17.034Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:26:40.171Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:26:40.175Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=b8825e98-d731-4113-95d4-b8fdc7cf370f
2021-05-07T08:26:44.450Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:26:44.450Z - info: [main] Processing protocol url
2021-05-07T08:26:44.459Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:26:45.213Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:26:45.214Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:36:22.758Z - info: [ui] [AppStore] loading 0 repositories from store
2021-05-07T08:36:23.314Z - info: [ui] launching: 2.8.1 (Windows 10.0.18363)
2021-05-07T08:36:23.315Z - info: [ui] execPath: 'C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-07T08:36:25.408Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.296s)
2021-05-07T08:36:26.286Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2021-05-07T08:38:32.870Z - info: [ui] calling captureCommandOutput(where git)
2021-05-07T08:38:33.598Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:38:33.600Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=001dca3f-44cb-45b9-a799-e8af3d9a81cb
2021-05-07T08:38:41.758Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:38:41.758Z - info: [main] Processing protocol url
2021-05-07T08:38:41.805Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:38:42.602Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:38:44.320Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:39:47.578Z - info: [ui] [AppStore] loading 0 repositories from store
2021-05-07T08:39:48.192Z - info: [ui] launching: 2.8.1 (Windows 10.0.18363)
2021-05-07T08:39:48.194Z - info: [ui] execPath: 'C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-07T08:39:50.281Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.261s)
2021-05-07T08:39:50.941Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2021-05-07T08:39:54.490Z - info: [ui] calling captureCommandOutput(where git)
2021-05-07T08:39:55.202Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:39:55.213Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=884f1368-21ee-485d-8764-b70fc5525b56
2021-05-07T08:40:10.999Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:40:10.999Z - info: [main] Processing protocol url
2021-05-07T08:40:11.076Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:40:11.850Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:40:13.754Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:40:50.376Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:40:50.379Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=e6f724b2-31e3-4de5-9594-341ce62d2f27
2021-05-07T08:40:53.470Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:40:53.471Z - info: [main] Processing protocol url
2021-05-07T08:40:53.481Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:40:54.245Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:40:54.246Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:50:23.555Z - info: [ui] [AppStore] loading 0 repositories from store
2021-05-07T08:50:24.165Z - info: [ui] launching: 2.8.1 (Windows 10.0.18363)
2021-05-07T08:50:24.166Z - info: [ui] execPath: 'C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-07T08:50:26.407Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.441s)
2021-05-07T08:50:27.235Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2021-05-07T08:50:29.840Z - info: [ui] calling captureCommandOutput(where git)
2021-05-07T08:50:31.398Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:50:31.399Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=61e35926-74b9-49ba-b2db-7f365a67494f
2021-05-07T08:52:15.821Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:52:15.833Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=f27a8434-788d-4705-8632-9c94d8ad2f46
2021-05-07T08:52:28.526Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:52:28.526Z - info: [main] Processing protocol url
2021-05-07T08:52:28.556Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:52:29.430Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:52:31.115Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T08:52:44.821Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T08:52:44.831Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=81c91f3c-3396-4ac2-80ce-04296b206395
2021-05-07T08:52:48.399Z - info: [main] Received possible protocol arguments: 4
2021-05-07T08:52:48.400Z - info: [main] Processing protocol url
2021-05-07T08:52:48.411Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T08:52:49.158Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T08:52:49.158Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T09:04:31.277Z - info: [ui] [AppStore] loading 0 repositories from store
2021-05-07T09:04:33.089Z - info: [ui] launching: 2.8.1 (Windows 10.0.18363)
2021-05-07T09:04:33.105Z - info: [ui] execPath: 'C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-07T09:04:34.980Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2021-05-07T09:04:37.762Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 5.917s)
2021-05-07T09:04:43.699Z - info: [ui] calling captureCommandOutput(where git)
2021-05-07T09:04:44.808Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T09:04:44.810Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=58caefb0-2452-4adf-8a06-009e7087d3e2
2021-05-07T09:04:55.998Z - info: [main] Received possible protocol arguments: 4
2021-05-07T09:04:55.998Z - info: [main] Processing protocol url
2021-05-07T09:04:56.033Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T09:04:56.802Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T09:04:58.410Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T09:05:23.036Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T09:05:23.051Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=b5b8ce09-1e0b-4569-9764-e7f88f387307
2021-05-07T09:05:28.424Z - info: [main] Received possible protocol arguments: 4
2021-05-07T09:05:28.424Z - info: [main] Processing protocol url
2021-05-07T09:05:28.449Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T09:05:29.161Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T09:05:29.161Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T09:08:41.058Z - info: [ui] [AppStore] loading 0 repositories from store
2021-05-07T09:08:44.231Z - info: [ui] launching: 2.8.1 (Windows 10.0.18363)
2021-05-07T09:08:44.231Z - info: [ui] execPath: 'C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-07T09:08:44.268Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.831s)
2021-05-07T09:08:45.482Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2021-05-07T09:08:48.263Z - info: [ui] calling captureCommandOutput(where git)
2021-05-07T09:08:50.718Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T09:08:50.720Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=e2699813-e632-4a37-846b-0ccf250fd077
2021-05-07T09:08:54.695Z - info: [main] Received possible protocol arguments: 4
2021-05-07T09:08:54.695Z - info: [main] Processing protocol url
2021-05-07T09:08:54.711Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T09:08:55.482Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T09:08:57.330Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T09:09:01.113Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T09:09:01.114Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=2423cb91-997c-480c-a5e1-c21d3a0ad4b8
2021-05-07T09:09:43.566Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T09:09:43.567Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=04ddcd9c-2c6d-4d58-8102-9b3fc430b713
2021-05-07T09:10:05.256Z - info: [main] Received possible protocol arguments: 4
2021-05-07T09:10:05.257Z - info: [main] Processing protocol url
2021-05-07T09:10:05.280Z - info: [ui] [Dispatcher] requesting authenticated user
2021-05-07T09:10:06.025Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2021-05-07T09:10:06.025Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\XY58729\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1694:32)
2021-05-07T09:11:40.436Z - info: [ui] [SignInStore] initializing OAuth flow
2021-05-07T09:11:40.448Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=b97e1d40-05fe-43ed-b93a-a0744d98df64

**Comment by steveward** [comment]
Thanks for the report @XY58729. Can you share a few more details about your setup? I'm assuming you are running Windows in a VM using VMWare, but I wanted to clarify.

Are you behind a firewall or proxy that could be blocking GitHub Desktop?

**Comment by X058729** [comment]
Yes, its windows 10 on the vm and yes there should be a proxy for the org.

**Comment by steveward** [comment]
Thanks for the update. Is there anyone in your organization you can reach out to get more information about your specific network setup? Does GitHub Desktop work outside of your virtual machine on the same network?
