### ISSUE TITLE
Sometimes GitHub Desktop does not recognize that there is no merge needed

### ISSUE THREAD

**Issue by spsquared** [desktop/desktop#12250]
### Describe the bug

Sometimes after switching branches and resolving merges (and also actively trying to restore whatever changes it overwrote with much older versions), it thinks there still are conflicts to be resolved, leading to me getting stuck in a branch and unable to commit. There is a green check mark meaning there are no conflicts, and it says NO.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Expected behavior

The green check mark should let me change branches because there are no conflicts

### Actual behavior

It thinks there is a conflict.

### Screenshots

![image](https://user-images.githubusercontent.com/67865358/118988000-c80fd300-b94e-11eb-861c-957de53ac97a.png)
![image](https://user-images.githubusercontent.com/67865358/118988062-d65def00-b94e-11eb-9b28-f148f02f21ae.png)

### Logs

```
2021-05-20T12:26:19.720Z - info: [ui] [AppStore] loading 6 repositories from store
2021-05-20T12:26:19.721Z - info: [ui] [AppStore] found account: definitely-nobody-is-here (Radioactive64)
2021-05-20T12:26:20.185Z - info: [ui] launching: 2.8.1 (Windows 10.0.19042)
2021-05-20T12:26:20.186Z - info: [ui] execPath: 'C:\Users\jacki\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-20T12:26:20.438Z - info: [ui] Stats reported.
2021-05-20T12:26:25.351Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ev3rt-hrp2-sdk - definitely-nobody-is-here (has token)
2021-05-20T12:26:40.277Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.000s
2021-05-20T12:26:41.922Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T12:26:42.167Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress the-aniket-branch --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	README.md
	app.js
	client/index.html
	client/js/game.js
	client/js/index.js
	server/game.js
Please commit your changes or stash them before you switch branches.
Aborting

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
2021-05-20T12:26:43.531Z - info: [ui] [popStashEntry] a stash was popped successfully but exit code 1 reported.
2021-05-20T12:26:46.150Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.458s)
2021-05-20T12:26:47.083Z - info: [ui] [Timing] Action 'stash and checkout' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 5.161s
2021-05-20T12:26:49.984Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.761s)
2021-05-20T12:26:51.734Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 7.0s of which 0.0s paused, total 7.0s
2021-05-20T12:26:58.869Z - error: [ui] `git merge master` exited with an unexpected code: 128.
stderr:
error: Merging is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

(The error was parsed as 38: There are unresolved conflicts in the working directory.)
2021-05-20T12:27:03.579Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.000s
2021-05-20T12:27:05.176Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T12:27:05.326Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress master --` exited with an unexpected code: 1.
stdout:
README.md: needs merge
app.js: needs merge
client/index.html: needs merge
client/js/game.js: needs merge
client/js/index.js: needs merge
server/game.js: needs merge

stderr:
error: you need to resolve your current index first

2021-05-20T12:27:06.059Z - info: [ui] [Timing] Action 'stash and checkout' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.883s
2021-05-20T12:27:12.233Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T12:27:12.377Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress master --` exited with an unexpected code: 1.
stdout:
README.md: needs merge
app.js: needs merge
client/index.html: needs merge
client/js/game.js: needs merge
client/js/index.js: needs merge
server/game.js: needs merge

stderr:
error: you need to resolve your current index first

2021-05-20T12:27:13.108Z - info: [ui] [Timing] Action 'stash and checkout' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.874s
2021-05-20T12:30:26.910Z - info: [ui] No submodules found. Skipping "git submodule status"
2021-05-20T12:30:29.845Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T12:30:30.779Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.934s
2021-05-20T12:32:04.685Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T12:32:05.394Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.709s
2021-05-20T12:32:15.522Z - error: [ui] `git merge master` exited with an unexpected code: 128.
stderr:
error: Merging is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

(The error was parsed as 38: There are unresolved conflicts in the working directory.)
2021-05-20T12:32:29.367Z - info: [ui] [Timing] Action 'create commit' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.008s
2021-05-20T12:32:34.196Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T12:32:36.486Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin the-aniket-branch:the-aniket-branch --progress (took 2.221s)
2021-05-20T12:32:40.234Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T12:32:41.554Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 1.320s
2021-05-20T12:34:37.237Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T12:34:37.826Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.590s
2021-05-20T12:36:12.262Z - info: [ui] No submodules found. Skipping "git submodule status"
2021-05-20T13:15:32.756Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 3.5s of which 0.0s paused, total 3.5s
2021-05-20T13:15:36.384Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.000s
2021-05-20T13:15:39.161Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T13:15:40.753Z - info: [ui] [Timing] Action 'stash and checkout' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 1.592s
2021-05-20T13:15:42.318Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T13:15:43.434Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 1.115s
2021-05-20T13:15:45.980Z - info: [ui] [AppStore. _popStashEntry] popped stash with commit id 308d0ed4b959297fc45520f1d34745c7017e4427
2021-05-20T13:15:47.268Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.000s
2021-05-20T13:15:49.367Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T13:15:49.531Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress master --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	app.js
	client/index.html
	client/js/menu.js
Please commit your changes or stash them before you switch branches.
Aborting

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
2021-05-20T13:15:50.417Z - info: [ui] [popStashEntry] a stash was popped successfully but exit code 1 reported.
2021-05-20T13:15:51.912Z - info: [ui] [Timing] Action 'stash and checkout' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 2.544s
2021-05-20T13:16:42.336Z - info: [ui] No submodules found. Skipping "git submodule status"
2021-05-20T13:16:44.213Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.128s)
2021-05-20T13:16:44.232Z - info: [ui] Executing getPartialBlobContents: git show HEAD:app.js (took 1.054s)
2021-05-20T13:27:17.074Z - info: [ui] [AppStore] loading 6 repositories from store
2021-05-20T13:27:17.075Z - info: [ui] [AppStore] found account: definitely-nobody-is-here (Radioactive64)
2021-05-20T13:27:17.392Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-05-20T13:27:17.576Z - info: [ui] launching: 2.8.1 (Windows 10.0.19042)
2021-05-20T13:27:17.576Z - info: [ui] execPath: 'C:\Users\jacki\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-20T13:29:51.262Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.010s)
2021-05-20T13:29:51.774Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 2.8s of which 0.0s paused, total 2.8s
2021-05-20T13:29:56.554Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.000s
2021-05-20T13:29:58.165Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T13:29:58.322Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress the-aniket-branch --` exited with an unexpected code: 1.
stdout:
app.js: needs merge

stderr:
error: you need to resolve your current index first

2021-05-20T13:29:59.011Z - info: [ui] [Timing] Action 'stash and checkout' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.843s
2021-05-20T13:30:04.391Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T13:30:04.509Z - info: [ui] [createDesktopStashEntry] a stash was created successfully but exit code 1 reported. stderr: 
2021-05-20T13:30:04.627Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress the-aniket-branch --` exited with an unexpected code: 1.
stdout:
app.js: needs merge

stderr:
error: you need to resolve your current index first

2021-05-20T13:30:05.251Z - info: [ui] [Timing] Action 'stash and checkout' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.858s
2021-05-20T13:30:20.096Z - info: [ui] [AppStore] loading 6 repositories from store
2021-05-20T13:30:20.097Z - info: [ui] [AppStore] found account: definitely-nobody-is-here (Radioactive64)
2021-05-20T13:30:20.297Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-05-20T13:30:20.498Z - info: [ui] launching: 2.8.1 (Windows 10.0.19042)
2021-05-20T13:30:20.500Z - info: [ui] execPath: 'C:\Users\jacki\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-20T13:30:27.497Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.000s
2021-05-20T13:30:29.448Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T13:30:29.549Z - info: [ui] [createDesktopStashEntry] a stash was created successfully but exit code 1 reported. stderr: 
2021-05-20T13:30:29.699Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress the-aniket-branch --` exited with an unexpected code: 1.
stdout:
app.js: needs merge

stderr:
error: you need to resolve your current index first

2021-05-20T13:30:30.308Z - info: [ui] [Timing] Action 'stash and checkout' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.858s
2021-05-20T13:30:36.059Z - info: [ui] [AppStore] loading 6 repositories from store
2021-05-20T13:30:36.062Z - info: [ui] [AppStore] found account: definitely-nobody-is-here (Radioactive64)
2021-05-20T13:30:36.097Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-05-20T13:30:36.472Z - info: [ui] launching: 2.8.1 (Windows 10.0.19042)
2021-05-20T13:30:36.472Z - info: [ui] execPath: 'C:\Users\jacki\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-20T13:30:39.310Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-05-20T13:30:40.644Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-05-20T13:30:41.988Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T13:30:50.323Z - info: [ui] [AppStore] loading 6 repositories from store
2021-05-20T13:30:50.324Z - info: [ui] [AppStore] found account: definitely-nobody-is-here (Radioactive64)
2021-05-20T13:30:50.385Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-05-20T13:30:50.867Z - info: [ui] launching: 2.8.1 (Windows 10.0.19042)
2021-05-20T13:30:50.868Z - info: [ui] execPath: 'C:\Users\jacki\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-20T13:30:58.944Z - info: [ui] [AppStore] loading 6 repositories from store
2021-05-20T13:30:58.945Z - info: [ui] [AppStore] found account: definitely-nobody-is-here (Radioactive64)
2021-05-20T13:30:59.194Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-05-20T13:30:59.369Z - info: [ui] launching: 2.8.1 (Windows 10.0.19042)
2021-05-20T13:30:59.370Z - info: [ui] execPath: 'C:\Users\jacki\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-20T13:31:01.786Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-05-20T13:31:23.426Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 2.4s of which 0.0s paused, total 2.4s
2021-05-20T13:31:41.523Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.000s
2021-05-20T13:31:43.121Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T13:31:43.231Z - info: [ui] [createDesktopStashEntry] a stash was created successfully but exit code 1 reported. stderr: 
2021-05-20T13:31:43.381Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress the-aniket-branch --` exited with an unexpected code: 1.
stdout:
app.js: needs merge

stderr:
error: you need to resolve your current index first

2021-05-20T13:31:44.048Z - info: [ui] [Timing] Action 'stash and checkout' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.926s
2021-05-20T13:32:49.895Z - info: [ui] [AppStore] loading 6 repositories from store
2021-05-20T13:32:49.896Z - info: [ui] [AppStore] found account: definitely-nobody-is-here (Radioactive64)
2021-05-20T13:32:49.946Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-05-20T13:32:50.347Z - info: [ui] launching: 2.8.1 (Windows 10.0.19042)
2021-05-20T13:32:50.347Z - info: [ui] execPath: 'C:\Users\jacki\AppData\Local\GitHubDesktop\app-2.8.1\GitHubDesktop.exe'
2021-05-20T13:33:06.937Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.078s)
2021-05-20T13:33:07.599Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 3.4s of which 0.0s paused, total 3.4s
2021-05-20T13:33:17.180Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T13:33:19.482Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.000s
2021-05-20T13:33:21.081Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T13:33:21.217Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress the-aniket-branch --` exited with an unexpected code: 1.
stdout:
app.js: needs merge

stderr:
error: you need to resolve your current index first

2021-05-20T13:33:21.794Z - info: [ui] [Timing] Action 'stash and checkout' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.711s
2021-05-20T13:33:23.658Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T13:33:23.790Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress the-aniket-branch --` exited with an unexpected code: 1.
stdout:
app.js: needs merge

stderr:
error: you need to resolve your current index first

2021-05-20T13:33:24.507Z - info: [ui] [Timing] Action 'stash and checkout' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.845s
2021-05-20T13:34:55.131Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-05-20T13:34:55.649Z - error: [ui] Could not load old contents for syntax highlighting
Error: Git returned an unexpected exit code '128' which should be handled by the caller.'
    at ChildProcess.<anonymous> (C:\Users\jacki\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\lib\git\spawn.ts:111:15)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2021-05-20T13:34:55.722Z - error: [ui] Could not load old contents for syntax highlighting
Error: Git returned an unexpected exit code '128' which should be handled by the caller.'
    at ChildProcess.<anonymous> (C:\Users\jacki\AppData\Local\GitHubDesktop\app-2.8.1\webpack:\app\src\lib\git\spawn.ts:111:15)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
2021-05-20T13:35:01.514Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-05-20T13:36:12.013Z - info: [ui] [Timing] Action 'checkout branch from list' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.000s
2021-05-20T13:36:14.721Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BattleBoxes_Multiplayer - definitely-nobody-is-here (has token)
2021-05-20T13:36:14.855Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress the-aniket-branch --` exited with an unexpected code: 1.
stdout:
app.js: needs merge

stderr:
error: you need to resolve your current index first

2021-05-20T13:36:15.383Z - info: [ui] [Timing] Action 'stash and checkout' for 'definitely-nobody-is-here/BattleBoxes_Multiplayer' took 0.661s
```

### Additional context

I was trying to recover my changes (that I did not make a backup of) that somehow got overwritten by GitHub and ended up having to rewrite everything.

**Comment by spsquared** [comment]
Also, as something that bugs me:
When switching branches, it shouldn't just overwrite stuff and delete things. I just had to rewrite an hour of stuff because I switched branches without making a backup. I don't even know if I rewrote everything that got deleted.

**Comment by steveward** [comment]
@definitely-nobody-is-here thanks for the report. After conflicts are resolved the changes need to be committed -- fixing the conflicts in your editor alone does not resolve the index. We have an open issue tracking potential improvements 
around this scenario (https://github.com/desktop/desktop/issues/11959). 

When switching branches with uncommitted changes you should be presented with the option to stash the changes or bring them to  the branch you are switching to.  Is it possible your changes were stashed?
