### ISSUE TITLE
App throws up "Git could not be found" and "Failed to execute getStatus: ENOENT" errors in a loop

### ISSUE THREAD

**Issue by radumg** [desktop/desktop#12850]
### Describe the bug
Github Desktop stopped working properly, with no change/update/action from 2 weeks ago when it was working.

### Version & OS

Windows 10 Pro, build 19043.1165, Windows Feature Experience Pack 120.2212.3530.0

Github app doesn't start any more, so can't use About menu. Here's a screenshot of executable though.

![image](https://user-images.githubusercontent.com/11439624/131145711-f815e4d5-b72b-4fc5-b5aa-69a44760c4d9.png)

### Steps to reproduce the behavior

1. Open Github Desktop
2. Error comes up - see `error 1` below, press Close
3. Another error comes up - see `error 2`, press Close
4. Error 2 comes up every time I press ok, stuck in a loop
5. Behind the error modals, a `Cannot find repo xx` is visible
6. App now refuses to start up at all

Error 1
> Git could not be found at the expected path: 'C:\Users\username\AppData\Local\GitHubDesktop\app-2.9.2\resources\app\git\cmd\git.exe'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.

Error 2
> Failed to execute getStatus: ENOENT

### Expected behavior

App should find and work with the existing repos, as it did last week.

### Actual behavior

See reproduction steps above.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

from Squirrel-Update.log

> [27/08/21 16:39:59] info: FileDownloader: Downloading url: https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=2.9.2&env=production&id=GitHubDesktop&localVersion=2.9.1&arch=amd64
[27/08/21 16:40:00] info: FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-2.9.2-full.nupkg
[27/08/21 16:40:22] warn: ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\radug\AppData\Local\GitHubDesktop\app-2.9.2
[27/08/21 16:40:22] error: IEnableLogger: Failed to install package to app dir: System.UnauthorizedAccessException: Access to the path 'C:\Users\radug\AppData\Local\GitHubDesktop\app-2.9.2\chrome_100_percent.pak' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
[27/08/21 16:40:22] error: Program: Really couldn't apply updates!: System.UnauthorizedAccessException: Access to the path 'C:\Users\radug\AppData\Local\GitHubDesktop\app-2.9.2\chrome_100_percent.pak' is denied.

**Comment by radumg** [comment]
- manually deleted the `app-2.9.2` folder and app is back to normal running state, reporting version `2.9.1`
- ran update
- app is now `2.9.2` and running ok

Please feel free to close the issue now since I can use the app again - or keep it open if you'd like to figure out what caused it in the first place since it was fine a few days ago (borked update I suspect given the logs?)

**Comment by sergiou87** [comment]
Thanks for your report!! ❤️ 

As you say, this seems to be a problem with the update, not much we can do on our side 😕
