### ISSUE TITLE
Github Desktop shows at startup: dyld: Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by manueljordan** [desktop/desktop#12868]
In MacOS El Capitan: `10.11.6 (15G22010)` and with GitHub Desktop `2.9.2 (x64)` and the previous version, at startup of the process always opens a dialog window with:

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git-lfs
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git-lfs
  Expected in: /usr/lib/libSystem.B.dylib

SIGTRAP: trace trap
PC=0x7fff6e360075 m=5 sigcode=1

goroutine 0 [idle]:
runtime.walltime1(0x0, 0xc000000000)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sys_darwin.go:270 +0x4a fp=0xc000193db0 sp=0xc000193d78 pc=0x4057e4a
runtime.walltime(...)
	hostedtoolcache/go/1.16.3/x64/src/runtime/time_nofake.go:23
time.now(0x45a4c60, 0x4602f01, 0xc000220010)
	hostedtoolcache/go/1.16.3/x64/src/runtime/timestub.go:16 +0x25 fp=0xc000193de0 sp=0xc000193db0 pc=0x406b3a5
time.Now(0x45a4c60, 0xc000220010, 0x0)
	hostedtoolcache/go/1.16.3/x64/src/time/time.go:1067 +0x26 fp=0xc000193e08 sp=0xc000193de0 pc=0x40c8266
github.com/git-lfs/git-lfs/config.NewIn(0x0, 0x0, 0x0, 0x0, 0x4628165)
	work/dugite-native/dugite-native/git-lfs/config/config.go:69 +0xe5 fp=0xc000193e88 sp=0xc000193e08 pc=0x41aa325
github.com/git-lfs/git-lfs/config.New(...)
	work/dugite-native/dugite-native/git-lfs/config/config.go:61
github.com/git-lfs/git-lfs/commands.Run(0x10)
	work/dugite-native/dugite-native/git-lfs/commands/run.go:97 +0x265 fp=0xc000193f20 sp=0xc000193e88 pc=0x4514445
main.main()
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:33 +0xec fp=0xc000193f88 sp=0xc000193f20 pc=0x4520eac
runtime.main()
	hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225 +0x256 fp=0xc000193fe0 sp=0xc000193f88 pc=0x403a556
runtime.goexit()
	hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000193fe8 sp=0xc000193fe0 pc=0x406e101

goroutine 1 [running]:
runtime.asmcgocall(0x406f8e0, 0xc000193d90)
	hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:652 +0x42 fp=0xc000193d48 sp=0xc000193d40 pc=0x406dd62
runtime.libcCall(0x406f8e0, 0xc000193d90, 0x10)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sys_libc.go:48 +0x6c fp=0xc000193d78 sp=0xc000193d48 pc=0x405848c
runtime.walltime1(0x0, 0xc000000000)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sys_darwin.go:270 +0x4a fp=0xc000193db0 sp=0xc000193d78 pc=0x4057e4a
runtime.walltime(...)
	hostedtoolcache/go/1.16.3/x64/src/runtime/time_nofake.go:23
time.now(0x45a4c60, 0x4602f01, 0xc000220010)
	hostedtoolcache/go/1.16.3/x64/src/runtime/timestub.go:16 +0x25 fp=0xc000193de0 sp=0xc000193db0 pc=0x406b3a5
time.Now(0x45a4c60, 0xc000220010, 0x0)
	hostedtoolcache/go/1.16.3/x64/src/time/time.go:1067 +0x26 fp=0xc000193e08 sp=0xc000193de0 pc=0x40c8266
github.com/git-lfs/git-lfs/config.NewIn(0x0, 0x0, 0x0, 0x0, 0x4628165)
	work/dugite-native/dugite-native/git-lfs/config/config.go:69 +0xe5 fp=0xc000193e88 sp=0xc000193e08 pc=0x41aa325
github.com/git-lfs/git-lfs/config.New(...)
	work/dugite-native/dugite-native/git-lfs/config/config.go:61
github.com/git-lfs/git-lfs/commands.Run(0x10)
	work/dugite-native/dugite-native/git-lfs/commands/run.go:97 +0x265 fp=0xc000193f20 sp=0xc000193e88 pc=0x4514445
main.main()
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:33 +0xec fp=0xc000193f88 sp=0xc000193f20 pc=0x4520eac
runtime.main()
	hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225 +0x256 fp=0xc000193fe0 sp=0xc000193f88 pc=0x403a556
runtime.goexit()
	hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000193fe8 sp=0xc000193fe0 pc=0x406e101

goroutine 34 [syscall]:
os/signal.signal_recv(0x0)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	hostedtoolcache/go/1.16.3/x64/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	hostedtoolcache/go/1.16.3/x64/src/os/signal/signal.go:151 +0x45

goroutine 35 [chan receive]:
main.main.func1(0xc0000302a0, 0xc00020a000)
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:21 +0x65
created by main.main
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:19 +0xe7

rax    0x7fff6e399290
rbx    0x2cd00020
rcx    0x0
rdx    0x0
rdi    0x7fff6e399400
rsi    0x0
rbp    0x700000209990
rsp    0x700000209978
r8     0x7fff6e38204c
r9     0xffc00000
r10    0x70000020977a
r11    0x7fff6e399400
r12    0x1
r13    0x1
r14    0x7fff6e399400
r15    0xffffffffffffffff
rip    0x7fff6e360075
rflags 0x246
cs     0x2b
fs     0x0
gs     0x0
```

I am able to close the dialog window and work in peace, therefore it is not a blocker.

**Comment by steveward** [comment]
Thanks for the issue @manueljordan. This was previously reported in https://github.com/desktop/desktop/issues/12436. Unfortunately the only workaround we have is to update to a more recent version of macOS. I'll make a note to update the supported versions of macOS in our documentation.
