### ISSUE TITLE
Crash without doing anything

### ISSUE THREAD

**Issue by Ionys320** [desktop/desktop#13006]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Version: 2.9.3
OS: Windows 10.0.22000

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Just wait

### Expected behavior

No crash should occurred.

### Actual behavior

A crash occurred.

### Screenshots

![image](https://user-images.githubusercontent.com/9364594/134407828-ea229bef-84ba-4521-baee-fb0ed709853d.png)

### Logs

```
RangeError: Invalid string length
    at u.<anonymous> (file:///app/renderer.js:55:334937)
    at u.emit (events.js:315:20)
    at T (file:///app/renderer.js:19:96653)
    at x (file:///app/renderer.js:19:96483)
    at u.k.push (file:///app/renderer.js:19:97267)
    at u.push (file:///app/renderer.js:19:119820)
    at c (file:///app/renderer.js:6:250300)
    at u.a [as _transform] (file:///app/renderer.js:6:249986)
    at u._read (file:///app/renderer.js:19:120281)
    at u._write (file:///app/renderer.js:19:120120)
```

**Comment by steveward** [comment]
Thanks for the issue @Ionys320. Is this happening consistently each time you launch GitHub Desktop?

I'd recommend trying a fresh install to see if that helps:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps at all.

**Comment by Ionys320** [comment]
Hi!
I've tried, but unfortunately, it doesn't change anything. The bug seems really specific to a single repository if the master branch is selected. Before the crash, the interface seems laggy, and GitHub Desktop seems to take a lot of RAM, even by clicking on the `Exit and restart` button and leaving GitHub Desktop in background.
Don't hesitate if you need more informations!

![image](https://user-images.githubusercontent.com/9364594/134432508-7f05c949-f535-47e0-82bd-b02df5a98fc9.png)

**Comment by sergiou87** [comment]
Hey @Ionys320! 👋 

Could you share your full logs from a day where you reproduced this issue? It might be helpful to diagnose the error.

Other than that, is there anything special about that repository in its `master` branch? Like maybe it uses special characters in some recent commit message 🤔

**Comment by Ionys320** [comment]
Hey @sergiou87 !

Here the fulls logs for the beginning of this day:
```
2021-09-23T08:37:22.712Z - info: [ui] [AppStore] loading 2 repositories from store
2021-09-23T08:37:22.714Z - info: [ui] [AppStore] found account: Ionys320 (Ionys)
2021-09-23T08:37:23.745Z - info: [ui] launching: 2.9.3 (Windows 10.0.22000)
2021-09-23T08:37:23.748Z - info: [ui] execPath: 'C:\Users\kylli\AppData\Local\GitHubDesktop\app-2.9.3\GitHubDesktop.exe'
2021-09-23T08:37:25.606Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.116s)
2021-09-23T08:37:51.065Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 6.997s)
2021-09-23T08:37:56.367Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 5.301s)
2021-09-23T08:37:56.367Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 14.297s)
2021-09-23T08:38:03.801Z - info: [ui] Executing getSymbolicRef: git symbolic-ref -q refs/remotes/origin/HEAD (took 7.428s)
2021-09-23T08:38:07.250Z - info: [ui] Executing getConfigValueInPath: git config -z --global init.defaultBranch (took 3.449s)
2021-09-23T08:38:08.748Z - error: [main] RangeError: Invalid string length
    at u.<anonymous> (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:55:334937)
    at u.emit (events.js:315:20)
    at T (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:19:96653)
    at x (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:19:96483)
    at u.k.push (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:19:97267)
    at u.push (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:19:119820)
    at c (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:6:250300)
    at u.a [as _transform] (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:6:249986)
    at u._read (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:19:120281)
    at u._write (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:19:120120)
2021-09-23T08:38:09.172Z - info: [main] Error report submitted
2021-09-23T08:42:56.209Z - info: [ui] [AppStore] loading 2 repositories from store
2021-09-23T08:42:56.211Z - info: [ui] [AppStore] found account: Ionys320 (Ionys)
2021-09-23T08:42:56.717Z - info: [ui] launching: 2.9.3 (Windows 10.0.22000)
2021-09-23T08:42:56.718Z - info: [ui] execPath: 'C:\Users\kylli\AppData\Local\GitHubDesktop\app-2.9.3\GitHubDesktop.exe'
2021-09-23T08:43:06.478Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 8.492s)
2021-09-23T08:43:06.599Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 8.463s)
2021-09-23T08:43:08.758Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.880s)
2021-09-23T08:43:08.961Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.944s)
2021-09-23T08:43:27.710Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 4.172s)
2021-09-23T08:43:30.786Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 3.075s)
2021-09-23T08:43:32.261Z - error: [main] RangeError: Invalid string length
    at u.<anonymous> (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:55:334937)
    at u.emit (events.js:315:20)
    at T (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:19:96653)
    at x (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:19:96483)
    at u.k.push (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:19:97267)
    at u.push (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:19:119820)
    at c (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:6:250300)
    at u.a [as _transform] (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:6:249986)
    at u._read (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:19:120281)
    at u._write (file:///C:/Users/kylli/AppData/Local/GitHubDesktop/app-2.9.3/resources/app/renderer.js:19:120120)
2021-09-23T08:43:32.571Z - info: [main] Error report submitted
2021-09-23T08:43:36.820Z - info: [ui] [AppStore] loading 2 repositories from store
2021-09-23T08:43:36.822Z - info: [ui] [AppStore] found account: Ionys320 (Ionys)
2021-09-23T08:43:37.285Z - info: [ui] launching: 2.9.3 (Windows 10.0.22000)
2021-09-23T08:43:37.286Z - info: [ui] execPath: 'C:\Users\kylli\AppData\Local\GitHubDesktop\app-2.9.3\GitHubDesktop.exe'
```

I checked the last commits, but there are not different from usual (a lot of stash made with GitHub Desktop, and normal commits without special characters):
![image](https://user-images.githubusercontent.com/9364594/134478682-605005ce-d67d-4fc9-bfe3-7b2e13056e15.png)

**Comment by sergiou87** [comment]
Thanks, @Ionys320 !! Unfortunately, there is nothing relevant in them 😢 

I have two ideas: if it's a public repo or a private repo you don't mind sharing with me, I can try and reproduce the issue myself. If you don't want to share it, that's completely fine!!

In that case, I'd suggest that you try to debug it for me following these steps:
1. From the command line, make sure you're in a branch other than `master` (so Desktop doesn't crash right away).
2. From Desktop, go to `View` -> `Toggle Developer Tools`
3. In those Developer Tools, go to the `Sources` tab and enable `Pause on Exceptions`, but **make sure `Pause on caught exceptions` is disabled**.

![2021-09-23 at 13 20](https://user-images.githubusercontent.com/1083228/134498392-eb5420ec-aeca-4301-ac34-cddf742e38e1.png)
4. Switch that repo to the `master` branch
5. Wait until the app "crashes"
6. It will pause the debugger inside the Developer Tools at this line of `core.ts`:

![2021-09-23 at 13 22](https://user-images.githubusercontent.com/1083228/134498618-53721b6d-687c-4f7b-9078-7ef11a604e34.png)
7. At that point, just press <kbd>Esc</kbd> while you're focused on the Developer Tools. That will show a console right above the source code:

![2021-09-23 at 13 23](https://user-images.githubusercontent.com/1083228/134498753-ec12e1b9-2750-453c-b377-b89d3b4c410d.png)
8. Type `o` and press <kbd>Enter</kbd>
9. Type `e` and press <kbd>Enter</kbd>

That should print some stuff, in theory, 2 strings. `o` is the output (**so far**) of a git command currently running (`combinedOutput`), and `e` is the next chunk of output from that git command (`line`).

If you decide to follow those steps, it'd be great to see what you get in steps (8) and (9). Thank you!!

**Comment by Ionys320** [comment]
Hi @sergiou87 !
Because it's a private repository, I've made the requested instructions for you. But it seems that everything was not working.. `o` and `e` was undefined, and the code didn't stop ib the right file at the good line. I keep my instance of Dekstop opened to be able to perform more operations if needed.

Thank you for your time!

![image](https://user-images.githubusercontent.com/9364594/134506975-731507af-17c1-4e95-91de-922cd17805d0.png)

**Comment by sergiou87** [comment]
Oops! I did not expect that 😂  The debugger didn't pause at the line I said but instead where the error was captured and re-thrown 😢 

Looking at the `Call Stack` (right side of the Developer Tools) I don't think there is anything in the `core.ts` file 😞  If there was, you would click on it and then type `o` and `e` to see their values.

If that's not possible, maybe I can make a special build that prints out those values right before the crash in order to help us understand what's going on. Please, try what I mentioned about the `Call Stack` and if that doesn't work I'll prepare a special build for you 😄

**Comment by Ionys320** [comment]
I can confirm that `core.ts` is not in the `Call Stack` 😞 Ready to have the special build!

![image](https://user-images.githubusercontent.com/9364594/134547040-41397f04-948a-4849-95c3-368c3681600f.png)

**Comment by sergiou87** [comment]
@Ionys320 thank you for checking 😄 

This is a custom build: https://centralreleases.blob.core.windows.net/github-desktop/releases/2.9.4-test3-95a6ec79/GitHubDesktopSetup-x64.exe

This one won't crash. Instead, it will log in the Developer Tools' Console both a `combinedOutput` and a `line`. Could you reproduce the issue and check what those values are when the app is supposed to crash?

Thank you!!!

**Comment by Ionys320** [comment]
Hi, here is the new steps! I'm not sure it will really help;;

![image](https://user-images.githubusercontent.com/9364594/134642099-ab35a17e-d642-4ee0-ba48-3c93df025edf.png)
![image](https://user-images.githubusercontent.com/9364594/134642233-b27d8f54-fcf1-4f7d-bed0-0f89f4e130db.png)

**Comment by sergiou87** [comment]
Hey @Ionys320 ! Sorry I wasn't more clear: you don't need to type anything in the console, that build should log the stuff I wanted to check for you. So once you have done the steps to crash the app, just check the `Console` and it should show the contents of `combinedOutput` and `line` already 😄

**Comment by Ionys320** [comment]
![image](https://user-images.githubusercontent.com/9364594/135066979-565bc555-7add-4c55-ad74-f19bd4585aa3.png)
In this case, here we go, but it doesn't seems to change anything =;-;=

**Comment by Ionys320** [comment]
Hi, after some tests, it seems that the branch had a problem, because trying to merge another branch on it was able to make VSCode crash too.

**Comment by sergiou87** [comment]
Thanks for reporting back! In theory the build I shared with you should've printed something. As you say, there might be something weird with that branch, my bet is it's either a really long `git` output in some command or that something in your branch (probably a commit message) has a special character that makes Desktop and VSCode blow up 😕  Maybe some kind of invisible character or something like that.

Another way of pinpointing the, according to my theory, offending commit, is to create a branch from `master` and then start moving that branch back using `git reset`, commit by commit (or jump X commits to make the process a bit faster), until the app stops crashing. Once you find the commit that makes it crash we can probably find why and even reproduce it ourselves here.

**Comment by Reecstuff** [comment]
Well this is quite an old Issue, but I solved it:
Squash and merge generates a commit with a description that includes all commits and all other squash and merge with their commits. This message gets with time so long it crashes the UI on load. Github Desktop loads the commit messages on startup in the background, so it crashes after some wait time and you get the ``Invalid String Length`` error. It even is crashing on other Git Clients like Fork if you click on the specific commit with your invalid string.

The solution is to save your local data and create a new repository with it. The git history of your old repository will be forever bugged, so you can delete it and never ever use squash and merge again!

**Comment by steveward** [comment]
@Reecstuff thanks for sharing that info! If you'd be up for opening a new issue with reproduction steps so that the team can take a look that would be helpful.
