### ISSUE TITLE
not able to restart Github. It keeps crashing

### ISSUE THREAD

**Issue by VishalModi12** [desktop/desktop#13062]
Error: read ENOTCONN
    at tryReadStart (net.js:573:20)
    at Socket._read (net.js:584:5)
    at Socket.Readable.read (_stream_readable.js:467:10)
    at Socket.read (net.js:624:39)
    at new Socket (net.js:376:12)
    at Object.Socket (net.js:267:41)
    at createSocket (internal/child_process.js:314:14)
    at ChildProcess.spawn (internal/child_process.js:437:23)
    at spawn (child_process.js:557:9)
    at Object.execFile (child_process.js:241:17)

Version: 2.9.3

**Comment by steveward** [comment]
Thanks for the report @VishalModi12. We've had some reports of this previously (https://github.com/desktop/desktop/issues/11441). 

- What operating system are you running on this machine? 
- Have you tried restarting your machine to see if that helps?

**Comment by VishalModi12** [comment]
It worked after restarting my system. I was working on MacBook air.

Thanks,
Vishal Modi

**Comment by steveward** [comment]
@VishalModi12 thanks for the update -- I'm going to close this out but let me know if you continue to run into this.
