### ISSUE TITLE
2.9.4 i make a mistake or bug ?

### ISSUE THREAD

**Issue by LolkerXD** [desktop/desktop#13155]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

Error: read ENOTCONN
    at tryReadStart (net.js:573:20)
    at Socket._read (net.js:584:5)
    at Socket.Readable.read (_stream_readable.js:467:10)
    at Socket.read (net.js:624:39)
    at new Socket (net.js:376:12)
    at Object.Socket (net.js:267:41)
    at createSocket (internal/child_process.js:314:14)
    at ChildProcess.spawn (internal/child_process.js:437:23)
    at Object.spawn (child_process.js:557:9)
    at spawnUpdate (electron/js2c/browser_init.js:21:553)

Version: 2.9.4
OS: Windows 10.0.19041

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
