### ISSUE TITLE
Issue in Compiler

### ISSUE THREAD

**Issue by AbhayKumawat** [desktop/desktop#13316]
This is issue - and in compiler there is recommendation that " Please report this bug with the details below.", so it is there... Solve the issue ASAP.

Last 200 Keys:
 h p o i n t e r Space } Space ; Space i f Space ( $ ? ) Space { Space . \ 6 a r r a y s w i t h p o i n t e r Space } Enter
 8 7 Backspace Backspace c d Space " c : \ U s e r s \ a b h a y \ D e s k t o p \ C O D E Space W I T H Space H A R R Y Space C Space t u t o r i a l \ C _ L a n g u a g e _ C h a p t e r Space 7 \ C h a p t e r Space 7 \ " Space ; Space i f Space ( $ ? ) Space { Space g c c Space 6 a r r a y s w i t h p o i n t e r . c Space - o Space 6 a r r a y s w i t h p o i n t e r Space } Space ; Space

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero 
and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)     
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg) 
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by steveward** [comment]
@AbhayKumawat this issue tracker is for GitHub Desktop -- it looks like you are having an issue with another project. If you have a specific question about GitHub Desktop please let me know.
