### ISSUE TITLE
post-merge hook

### ISSUE THREAD

**Issue by Sil-Boydens** [desktop/desktop#13362]
### Describe the bug
post-merge hook is not running when pulling through desktop

### Version & OS
issue persists on several computers, all have same version
desktop 2.9.4 (x64) & windows 10 (1909 | build 18363.720)

### Steps to reproduce the behavior

create a post-merge hook (place file with script in .git/hooks)
click "pull origin"

### Expected behavior

hook gets executed

### Actual behavior

hook does not get executed

### Logs

<details>
<summary> click to show</summary>
<br>
2021-11-22T14:50:24.376Z - info: [ui] [AppStore] loading 2 repositories from store<br>
2021-11-22T14:50:24.377Z - info: [ui] [AppStore] found account: Sil-Boydens (Sil-Boydens)<br>
2021-11-22T14:50:24.390Z - info: [ui] [BranchPruner] Last prune took place in 19 hours - skipping<br>
2021-11-22T14:50:25.343Z - warn: [ui] Error refreshing account 'Sil-Boydens'<br>
Error: Cannot update an account which doesn't have a token: Sil-Boydens<br>
    at te (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\fatal-error.ts:3:9)<br>
    at C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\accounts-store.ts:214:12<br>
    at Object.tryUpdateAccount (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\accounts-store.ts:134:20)<br>
    at C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\accounts-store.ts:114:37<br>
    at Array.map (<anonymous>)<br>
    at Object.refresh (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\accounts-store.ts:114:21)<br>
    at Object.loadInitialState (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:1847:24)<br>
2021-11-22T14:50:25.542Z - warn: [ui] fetchAll: 'repos/$ORGANISATION$/$REPOSITORY$/issues?state=open' returned a 404<br>
2021-11-22T14:50:25.561Z - info: [ui] Executing getRemotes: git remote -v (took 1.141s)<br>
2021-11-22T14:50:25.570Z - info: [ui] Executing getRemotes: git remote -v (took 1.168s)<br>
2021-11-22T14:50:25.571Z - info: [ui] [fetchProtectedBranches] unable to list protected branches<br>
Error: Not Found<br>
    at pt (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\http.ts:178:11)<br>
    at Lt.fetchProtectedBranches (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\api.ts:1132:7)<br>
    at Object.updateBranchProtectionsFromAPI (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:3587:11)<br>
2021-11-22T14:50:25.665Z - info: [ui] launching: 2.9.4 (Windows 6.1.7601)<br>
2021-11-22T14:50:25.665Z - info: [ui] execPath: 'C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\GitHubDesktop.exe'<br>
2021-11-22T14:50:25.712Z - warn: [ui] fetchRepository: '$ORGANISATION$/$REPOSITORY$' returned a 404<br>
2021-11-22T14:50:25.784Z - warn: [ui] fetchAll: 'repos/$ORGANISATION$/$REPOSITORY$/pulls?state=open' returned a 404<br>
2021-11-22T14:50:28.187Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 3.774s)<br>
2021-11-22T14:50:29.266Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 3.652s)<br>
2021-11-22T14:51:33.681Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: $REPOSITORY$ - Sil-Boydens (empty token)<br>
2021-11-22T14:51:36.069Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.313s)<br>
2021-11-22T14:51:36.349Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable<br>
Error: Not Found<br>
    at pt (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\http.ts:178:11)<br>
    at Lt.fetchPushControl (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\api.ts:1106:7)<br>
    at Object.refreshBranchProtectionState (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:1013:39)<br>
    at C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:4461:32<br>
    at Object.withPushPullFetch (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:4002:5)<br>
    at Object.performFetch (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:4417:5)<br>
2021-11-22T14:51:38.588Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 2.238s)<br>
2021-11-22T14:51:39.226Z - warn: [ui] fetchAll: 'repos/$ORGANISATION$/$REPOSITORY$/issues?state=open' returned a 404<br>
2021-11-22T14:52:01.062Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 2.257s)<br>
2021-11-22T14:52:01.445Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: $REPOSITORY$ - Sil-Boydens (empty token)<br>
2021-11-22T14:52:05.566Z - info: [ui] Executing pull: git -c credential.helper= -c protocol.version=2 -c rebase.backend=merge pull --progress origin (took 3.901s)<br>
2021-11-22T14:52:05.866Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable<br>
Error: Not Found<br>
    at pt (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\http.ts:178:11)<br>
    at Lt.fetchPushControl (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\api.ts:1106:7)<br>
    at Object.refreshBranchProtectionState (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:1013:39)<br>
    at C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:4130:45<br>
    at Object.withPushPullFetch (C:\Users\sil\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:4002:5)<br>
2021-11-22T14:52:08.035Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 2.168s)<br>
</details>

### Additional context

repository is private, i'm owner role in the organisation and admin in the repository.
authentication is using ssh keys (logs give a couple 404 and "(empty token)" so i think it's worth mentioning)
logs containg starting the app and pressing fetch and following pull button.
"git pull" in git bash works, this does trigger the hook
tried with these variants in the hook (wich all work from git bash "git pull" command but none from desktop):
 - call .bat file that then calls the compiler `./Compiler/compile.bat "$(git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD)"`
 - call compiler exe directly `"c:/program fil... "$(git diff-tree...)`
 - write to file `echo "test" > "test.txt"` (this to test if the hook even triggers)
 - all above with and without shebang in the hook script

am i missing a setting?
if you don't want to add the hook for everyone, could you somewhere in the options add a place where we can select wich hook to use? (or just "use hooks" as one option)

**Comment by niik** [comment]
Hey @Sil-Boydens, sorry that you've had to wait for so long to get an answer to your question.

GitHub Desktop doesn't skip hooks for any operation but we do ship a minimal Git environment in order to be able to rely on a consistent version of Git as opposed to depending on what's installed locally. That minimal environment doesn't include (among other things) `bash` which is a common reason why hooks fail to execute.

The `post-merge` hook can't abort a merge which is likely why Git doesn't treat it as an error if it fails to execute it.

Unfortunately I can't help with debugging the exact reason your post-merge script fails but I would try creating a minimal working hook and gradually work my way from that to your final script, ironing out what in the minimal environment of GitHub Desktop is causing your script to fail. I started with this `post-merge` hook.

```
#!/bin/sh
calc.exe
```

That `post-merge` hook script causes GitHub Desktop to open the calculator on pull for me. Give it a shot and see if that works for you and if it does you can hopefully work your way from there.

**Comment by Sil-Boydens** [comment]
Hey niik,

after your comment, i changed the hook script to open calc.exe.
after using it for a day now, i noticed that it sometimes opens calc but not always.
i did some more testing and came to this conclusion.
- anything on local drive => works well (but i don't need it here)
- pull on repository in networkshare => fail
- switching to branch on in a repository on a networkshare
   * works if the branch wasn't local yet and had to be downloaded first (listed as "origin/branchname" in the list of branches)
   * fails if the branch already exist localy (listed as "branchname" in the list of branches)

i already found an other way to quickly compile new files (using reflog and diff-tree to list modified files and only compile them, but developers have to start the script manually). 
if this is something that you don't want to put time in, i understand as most people don't work from networkshares. and you can close this issue if you want.

**Comment by niik** [comment]
Thank you for reporting back @Sil-Boydens. It seems like most of these issues has to do with how Git works and not GitHub Desktop so I am going to close this out. I hope you find a satisfactory solution to your problem.
