### ISSUE TITLE
Cant publish repo

### ISSUE THREAD

**Issue by bryant-the-coder** [desktop/desktop#13409]
### Describe the bug
So, I want to publish a repo from github desktop. But this shows up instead

### Version & OS

![image](https://user-images.githubusercontent.com/92417638/143971220-943641d2-2ba1-4aa3-a320-b71c3adf7a48.png)
windows 10

### Steps to reproduce the behavior

1. Create a new file in your computer
2. Add local repo
3. Publish it

### Expected behavior

I tried to publish a new repo from github desktop. An error showed up. This happens when I uninstalled and reinstalled nodejs as I am fixing a bug with node yesterday

### Actual behavior

Can publish repo

### Screenshots

![Version](https://user-images.githubusercontent.com/92417638/143971220-943641d2-2ba1-4aa3-a320-b71c3adf7a48.png)
![Error](https://user-images.githubusercontent.com/92417638/143971179-6cbad238-5d0c-436e-8c6b-686c5e237b88.png)

### Logs

```
2021-11-30T01:46:27.198Z - info: [main] Received possible protocol arguments: 2
2021-11-30T01:46:27.200Z - error: [main] Malformed launch arguments received: C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\GitHubDesktop.exe,--squirrel-firstrun
2021-11-30T01:46:28.459Z - info: [ui] [AppStore] loading 0 repositories from store
2021-11-30T01:46:28.507Z - info: [ui] [Welcome] no sign in step found. ignoring...
2021-11-30T01:46:28.565Z - info: [ui] [Welcome] no sign in step found. ignoring...
2021-11-30T01:46:28.686Z - info: [ui] [Welcome] no sign in step found. ignoring...
2021-11-30T01:46:30.471Z - info: [ui] launching: 2.9.4 (Windows 10.0.19043)
2021-11-30T01:46:30.471Z - info: [ui] execPath: 'C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\GitHubDesktop.exe'
2021-11-30T01:46:30.522Z - info: [ui] [Welcome] no sign in step found. ignoring...
2021-11-30T01:46:31.658Z - info: [ui] Opt in reported.
2021-11-30T01:46:31.967Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
2021-11-30T01:46:31.967Z - info: [ui] [SignInStore] initializing OAuth flow
2021-11-30T01:46:31.968Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=b71e2372-572a-4971-820a-ed8b7f91dec5
2021-11-30T01:46:31.968Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2021-11-30T01:46:32.116Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2021-11-30T01:46:32.724Z - info: [main] Received possible protocol arguments: 4
2021-11-30T01:46:32.724Z - info: [main] Processing protocol url
2021-11-30T01:46:32.726Z - info: [ui] [Dispatcher] requesting authenticated user
2021-11-30T01:46:32.740Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2021-11-30T01:46:33.762Z - info: [ui] [SignInStore] account resolved
2021-11-30T01:46:33.762Z - info: [ui] [AppStore] adding account bryant-the-coder (Bryant Foo) to store
2021-11-30T01:46:33.771Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2021-11-30T01:46:33.811Z - info: [ui] [Welcome] no sign in step found. ignoring...
2021-11-30T01:46:34.220Z - info: [ui] [Welcome] no sign in step found. ignoring...
2021-11-30T01:46:52.651Z - error: [ui] `git rev-parse --is-bare-repository` exited with an unexpected code: 128.
stderr:
fatal: not a git repository (or any of the parent directories): .git

(The error was parsed as 28: This is not a git repository.)
2021-11-30T01:46:58.394Z - info: [ui] [AppStore] adding repository at C:\Users\User\Documents\GitHub\generator-html-scss-js to store
2021-11-30T01:46:59.510Z - info: [ui] Executing isUsingLFS: git lfs track (took 1.001s)
2021-11-30T01:46:59.541Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-11-30T01:47:08.191Z - info: [ui] [AppStore] adding repository at C:\Users\User\Documents\GitHub\myStartpage to store
2021-11-30T01:47:18.531Z - info: [ui] [AppStore] adding repository at C:\Users\User\Documents\GitHub\vscode-langservers-extracted to store
2021-11-30T01:47:30.193Z - info: [ui] [AppStore] adding repository at C:\Users\User\Documents\GitHub\generator-web-development to store
2021-11-30T01:47:30.550Z - warn: [ui] fetchRepository: 'bryant-the-coder/generator-web-development' returned a 404
2021-11-30T01:47:31.503Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at pt (C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\http.ts:178:11)
    at Lt.fetchProtectedBranches (C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\api.ts:1132:7)
    at Object.updateBranchProtectionsFromAPI (C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:3587:11)
2021-11-30T01:47:31.506Z - warn: [ui] fetchMentionables: 'repos/bryant-the-coder/generator-web-development/mentionables/users' returned a 404
2021-11-30T01:47:31.506Z - warn: [ui] fetchAll: 'repos/bryant-the-coder/generator-web-development/pulls?state=open' returned a 404
2021-11-30T01:47:31.509Z - warn: [ui] fetchAll: 'repos/bryant-the-coder/generator-web-development/issues?state=open' returned a 404
2021-11-30T01:47:31.510Z - warn: [ui] fetchRepository: 'bryant-the-coder/generator-web-development' returned a 404
2021-11-30T01:47:32.983Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: generator-web-development - bryant-the-coder (has token)
2021-11-30T01:47:34.370Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master --set-upstream --progress (took 1.330s)
2021-11-30T01:47:34.370Z - error: [ui] `git -c credential.helper= -c protocol.version=2 push origin master --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2021-11-30T01:48:24.959Z - info: [ui] calling captureCommandOutput(where git)
2021-11-30T01:48:27.518Z - info: [ui] [AppStore] removing account bryant-the-coder (Bryant Foo) from store
2021-11-30T01:48:31.091Z - info: [ui] [SignInStore] initializing OAuth flow
2021-11-30T01:48:31.092Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=a681cc74-588e-449b-82d8-f304fbd74be2
2021-11-30T01:48:31.747Z - info: [main] Received possible protocol arguments: 4
2021-11-30T01:48:31.747Z - info: [main] Processing protocol url
2021-11-30T01:48:31.748Z - info: [ui] [Dispatcher] requesting authenticated user
2021-11-30T01:48:32.714Z - info: [ui] [SignInStore] account resolved
2021-11-30T01:48:32.714Z - info: [ui] [AppStore] adding account bryant-the-coder (Bryant Foo) to store
2021-11-30T01:48:49.646Z - warn: [ui] fetchRepository: 'bryant-the-coder/generator-web-development' returned a 404
2021-11-30T01:48:49.897Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-11-30T01:48:49.928Z - warn: [ui] fetchRepository: 'bryant-the-coder/generator-web-development' returned a 404
2021-11-30T01:48:49.929Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: generator-web-development - bryant-the-coder (has token)
2021-11-30T01:48:51.076Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.100s)
2021-11-30T01:48:51.326Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.330s)
2021-11-30T01:48:51.326Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2021-11-30T01:48:51.327Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 4 repositories took 3.3s of which 0.0s paused, total 3.3s
2021-11-30T01:48:53.814Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: myStartpage - bryant-the-coder (has token)
2021-11-30T01:48:55.931Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 2.062s)
2021-11-30T01:48:59.555Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: myStartpage - bryant-the-coder (has token)
2021-11-30T01:49:03.185Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-11-30T01:49:50.830Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-11-30T01:49:52.628Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-11-30T01:49:52.823Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at pt (C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\http.ts:178:11)
    at Lt.fetchProtectedBranches (C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\api.ts:1132:7)
    at Object.updateBranchProtectionsFromAPI (C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:3587:11)
2021-11-30T01:49:52.932Z - warn: [ui] fetchAll: 'repos/bryant-the-coder/generator-web-development/pulls?state=open' returned a 404
2021-11-30T01:49:52.933Z - warn: [ui] fetchAll: 'repos/bryant-the-coder/generator-web-development/issues?state=open' returned a 404
2021-11-30T01:49:53.268Z - warn: [ui] fetchRepository: 'bryant-the-coder/generator-web-development' returned a 404
2021-11-30T01:49:54.042Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.335s)
2021-11-30T01:49:54.043Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2021-11-30T01:49:54.382Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at pt (C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\http.ts:178:11)
    at Lt.fetchPushControl (C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\api.ts:1106:7)
    at Object.refreshBranchProtectionState (C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:1013:39)
    at C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:4461:32
    at Object.withPushPullFetch (C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:4002:5)
    at Object.performFetch (C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\app-store.ts:4417:5)
    at $i.performAndScheduleFetch (C:\Users\User\AppData\Local\GitHubDesktop\app-2.9.4\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2021-11-30T01:49:56.062Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: generator-web-development - bryant-the-coder (has token)
2021-11-30T01:49:57.430Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master --set-upstream --progress (took 1.314s)
2021-11-30T01:49:57.430Z - error: [ui] `git -c credential.helper= -c protocol.version=2 push origin master --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2021-11-30T01:53:59.686Z - warn: [ui] fetchAll: 'repos/bryant-the-coder/generator-web-development/pulls?state=open' returned a 404
```

**Comment by bryant-the-coder** [comment]
I also reinstalled github desktop again twice but still fail

**Comment by tidy-dev** [comment]
@bryant-the-coder thanks for the report. Can you go to File > Options > Accounts in GitHub Desktop and try logging out and then logging back in again to your GitHub account? Let me know if that does not get things working for you.

**Comment by bryant-the-coder** [comment]
No. Now it works. The solution is to remove all  .git  files from previously created files eith the old github desktop. Then remove all related to github desktop. After that install desktop again. It works again. That is how i solved it

**Comment by tidy-dev** [comment]
Ok. Awesome! I am glad you found a resolution. I am unsure how that resolved it unless there was an unusual git config in your setup. Thank you for the update. Seeing as you resolved it. I will close this issue.
