### ISSUE TITLE
Unable to clear the "Create a pull request from your current branch"

### ISSUE THREAD

**Issue by ahollenbach** [desktop/desktop#13630]
### Describe the bug
With a fresh repository, I am unable to clear the "Create a pull request from your current branch" while on the default branch.

### Version & OS

Version 2.9.6 (arm64), Mac with M1 chip

### Steps to reproduce the behavior

0. (optional) Of note: I initially created the repository with the same name and then deleted it from GH/local. Not sure if this is a required step.
1. Create a new repository on github using https://github.com/new
2. Follow the init setup shown (`git init`, `git remote add origin ...`, etc) and push up. The remote repository exists, has a main branch, and we are on main locally.
3. "Add existing repository" in GH desktop.
4. Ensure `main` is the default branch on GH

### Expected behavior

I expect no prompt to create a pull request when on the default branch.

### Actual behavior

I am given a prompt to create a pull request. It links me to a pull request from main to main with the URL `https://github.com/ahollenbach/<repository>/compare?expand=1`

### Screenshots

<img width="641" alt="Screen Shot 2022-01-04 at 12 03 32 PM" src="https://user-images.githubusercontent.com/1669563/148117049-36bd7aef-9ecd-4eb8-ac61-de80b71bad38.png">

<img width="625" alt="Screen Shot 2022-01-04 at 12 05 27 PM" src="https://user-images.githubusercontent.com/1669563/148117271-0b4d5a50-7e0d-45a7-b77f-57012fc593fc.png">

### Logs

```log
2022-01-04T20:10:03.513Z - info: [ui] [AppStore] adding repository at /Users/ahollenbach/projects/<repository> to store
2022-01-04T20:10:03.711Z - warn: [ui] fetchRepository: 'ahollenbach/<repository>' returned a 404
2022-01-04T20:10:03.786Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2022-01-04T20:10:03.934Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at ct (/webpack:/app/src/lib/http.ts:178:11)
    at Bt.fetchProtectedBranches (/webpack:/app/src/lib/api.ts:1191:7)
    at Object.updateBranchProtectionsFromAPI (/webpack:/app/src/lib/stores/app-store.ts:3589:11)
2022-01-04T20:10:03.939Z - warn: [ui] fetchRepository: 'ahollenbach/<repository>' returned a 404
2022-01-04T20:10:03.951Z - warn: [ui] fetchAll: 'repos/ahollenbach/<repository>/issues?state=open' returned a 404
2022-01-04T20:10:06.572Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: <repository> - ahollenbach (has token)
2022-01-04T20:10:07.781Z - warn: [ui] fetchAll: 'repos/ahollenbach/<repository>/issues?state=open' returned a 404
```

### Additional context

-

**Comment by sergiou87** [comment]
I think this is the problem:
> (optional) Of note: I initially created the repository with the same name and then deleted it from GH/local. Not sure if this is a required step.

There are some issues where deleted/renamed repositories cause some cache problems. Could you try to create a completely new repository with a name that you have never used and see if you can reproduce the behavior there?

Thank you!
