### ISSUE TITLE
cloning error

### ISSUE THREAD

**Issue by kesavan4954** [desktop/desktop#13690]
cant able to clone repositories in github desktop it showing cloning failed again and again

**Comment by steveward** [comment]
Thanks for the report @kesavan4954. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by kesavan4954** [comment]
On 18 January 2022 23:34:49 (+05:30), Steve Ward wrote:



Thanks for the report @kesavan4954. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.


-- As u said i attached my log file please check and try to slove my error



-- 
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

2022-01-18T10:55:40.444Z - info: [main] Received possible protocol arguments: 2
2022-01-18T10:56:07.947Z - info: [main] Received possible protocol arguments: 2
2022-01-18T10:56:08.169Z - error: [main] Malformed launch arguments received: C:\ProgramData\APTS-DXB-19\GitHubDesktop\app-2.9.6\GitHubDesktop.exe,--squirrel-firstrun
2022-01-18T10:57:21.930Z - info: [ui] [AppStore] loading 0 repositories from store
2022-01-18T10:58:10.535Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-01-18T10:58:14.916Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-01-18T10:59:44.302Z - info: [main] Received possible protocol arguments: 2
2022-01-18T10:59:44.309Z - error: [main] Malformed launch arguments received: C:\Users\APTS-DXB-19\AppData\Local\GitHubDesktop\app-2.9.6\GitHubDesktop.exe,--squirrel-firstrun
2022-01-18T10:59:53.347Z - info: [ui] [AppStore] loading 0 repositories from store
2022-01-18T10:59:55.035Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-01-18T10:59:55.849Z - info: [ui] launching: 2.9.6 (Windows 10.0.19042)
2022-01-18T10:59:55.849Z - info: [ui] execPath: 'C:\Users\APTS-DXB-19\AppData\Local\GitHubDesktop\app-2.9.6\GitHubDesktop.exe'
2022-01-18T10:59:55.858Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-01-18T10:59:55.863Z - error: [ui] Error checking for updates
Error: The application is missing a dependency it needs to check and install updates. This is very, very bad.
    at file:///C:/Users/APTS-DXB-19/AppData/Local/GitHubDesktop/app-2.9.6/resources/app/renderer.js:55:146726
    at onAutoUpdaterError (file:///C:/Users/APTS-DXB-19/AppData/Local/GitHubDesktop/app-2.9.6/resources/app/renderer.js:55:147142)
    at CallbacksRegistry.apply (electron/js2c/renderer_init.js:107:834)
    at electron/js2c/renderer_init.js:83:5623
    at electron/js2c/renderer_init.js:83:5332
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:103:732)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)
2022-01-18T10:59:59.666Z - info: [ui] Opt in reported.
2022-01-18T11:00:09.454Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 13.036s)
2022-01-18T11:01:04.472Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-01-18T11:01:07.016Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
2022-01-18T11:01:07.017Z - info: [ui] [SignInStore] initializing OAuth flow
2022-01-18T11:01:07.018Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=bb67f641-95ba-4051-935c-4f40163b2eb5
2022-01-18T11:01:07.019Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2022-01-18T11:01:13.336Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2022-01-18T11:03:12.822Z - info: [main] Received possible protocol arguments: 4
2022-01-18T11:03:12.822Z - info: [main] Processing protocol url
2022-01-18T11:03:12.877Z - info: [ui] [Dispatcher] requesting authenticated user
2022-01-18T11:03:12.882Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2022-01-18T11:03:13.189Z - info: [main] Received possible protocol arguments: 3
2022-01-18T11:03:15.148Z - info: [ui] [SignInStore] account resolved
2022-01-18T11:03:15.148Z - info: [ui] [AppStore] adding account kesavan4954 (kesavan4954) to store
2022-01-18T11:03:15.398Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2022-01-18T11:03:17.793Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-01-18T11:03:17.933Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-01-18T11:03:18.632Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-01-18T11:03:18.637Z - info: [ui] Executing getConfigValueInPath: git config -z --global user.email (took 1.106s)
2022-01-18T11:03:18.637Z - info: [ui] Executing getConfigValueInPath: git config -z --global user.name (took 1.132s)
2022-01-18T11:22:31.228Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/kesavan4954/ConditionalStatement.git - kesavan4954 (has token)
2022-01-18T11:22:35.651Z - info: [ui] Executing getConfigValueInPath: git config -z --global protocol.version (took 4.326s)
2022-01-18T11:22:51.535Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/kesavan4954/ConditionalStatement.git C:\Users\APTS-DXB-19\Documents\GitHub\ConditionalStatement (took 13.784s)
2022-01-18T11:22:52.143Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/kesavan4954/ConditionalStatement.git C:\Users\APTS-DXB-19\Documents\GitHub\ConditionalStatement` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\APTS-DXB-19\Documents\GitHub\ConditionalStatement'...
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T11:23:25.995Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/kesavan4954/ConditionalStatement.git - kesavan4954 (has token)
2022-01-18T11:23:28.311Z - info: [ui] Executing getConfigValueInPath: git config -z --global protocol.version (took 1.953s)
2022-01-18T11:23:28.877Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/kesavan4954/ConditionalStatement.git C:\Users\APTS-DXB-19\Documents\GitHub\ConditionalStatement` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\APTS-DXB-19\Documents\GitHub\ConditionalStatement'...
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T11:25:07.791Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/kesavan4954/projectdemo.git - kesavan4954 (has token)
2022-01-18T11:25:09.732Z - info: [ui] Executing getConfigValueInPath: git config -z --global protocol.version (took 1.923s)
2022-01-18T11:25:10.270Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/kesavan4954/projectdemo.git C:\Users\APTS-DXB-19\eclipse-workspace\projectdemo` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\APTS-DXB-19\eclipse-workspace\projectdemo'...
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T11:27:28.040Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.411s)
2022-01-18T11:27:51.152Z - info: [ui] Executing initGitRepository: git -c init.defaultBranch=main init (took 1.248s)
2022-01-18T11:27:51.632Z - info: [ui] [AppStore] adding repository at C:\Users\APTS-DXB-19\eclipse-workspace\demo_loop\MyRepo to store
2022-01-18T11:27:55.112Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.221s)
2022-01-18T11:27:56.195Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 1.077s)
2022-01-18T11:27:56.479Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.347s)
2022-01-18T11:27:58.564Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --skip=0 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.023s)
2022-01-18T11:28:08.248Z - info: [ui] Executing isUsingLFS: git lfs track (took 14.260s)
2022-01-18T11:28:11.115Z - info: [ui] Executing createCommit: git commit -F - (took 1.021s)
2022-01-18T11:28:43.111Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main --set-upstream --progress (took 2.917s)
2022-01-18T11:28:43.112Z - error: [ui] `git -c credential.helper= -c protocol.version=2 push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T11:29:58.919Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.417s)
2022-01-18T17:14:54.705Z - info: [main] Received possible protocol arguments: 2
2022-01-18T17:14:54.710Z - error: [main] Malformed launch arguments received: C:\Users\APTS-DXB-19\AppData\Local\GitHubDesktop\app-2.9.6\GitHubDesktop.exe,--squirrel-firstrun
2022-01-18T17:15:03.989Z - info: [ui] [AppStore] loading 1 repositories from store
2022-01-18T17:15:04.286Z - info: [ui] [AppStore] found account: kesavan4954 (kesavan4954)
2022-01-18T17:15:21.630Z - info: [ui] [BranchPruner] Last prune took place in 18 hours - skipping
2022-01-18T17:15:23.782Z - info: [ui] launching: 2.9.6 (Windows 10.0.19042)
2022-01-18T17:15:23.782Z - info: [ui] execPath: 'C:\Users\APTS-DXB-19\AppData\Local\GitHubDesktop\app-2.9.6\GitHubDesktop.exe'
2022-01-18T17:15:24.482Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 3.781s)
2022-01-18T17:15:24.483Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 3.096s)
2022-01-18T17:15:24.483Z - info: [ui] Executing getBranchesDifferingFromUpstream: git for-each-ref --format=%00%(refname)%00%(objectname)%00%(upstream)%00%(symref)%00%(HEAD)%00 refs/heads refs/remotes (took 3.182s)
2022-01-18T17:15:24.484Z - info: [ui] Executing getRemotes: git remote -v (took 2.798s)
2022-01-18T17:15:24.485Z - info: [ui] Executing getRemotes: git remote -v (took 5.984s)
2022-01-18T17:15:26.684Z - info: [ui] Stats reported.
2022-01-18T17:15:26.733Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 1.369s)
2022-01-18T17:15:26.955Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 1.696s)
2022-01-18T17:15:28.799Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 4.685s)
2022-01-18T17:16:52.172Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/kesavan4954/ConditionalStatement.git - kesavan4954 (has token)
2022-01-18T17:16:55.380Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/kesavan4954/ConditionalStatement.git C:\Users\APTS-DXB-19\eclipse-workspace\demo_loop\ConditionalStatement (took 2.486s)
2022-01-18T17:16:55.388Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/kesavan4954/ConditionalStatement.git C:\Users\APTS-DXB-19\eclipse-workspace\demo_loop\ConditionalStatement` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\APTS-DXB-19\eclipse-workspace\demo_loop\ConditionalStatement'...
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T17:18:22.239Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.228s)
2022-01-18T17:18:23.416Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MyRepo - kesavan4954 (has token)
2022-01-18T17:18:23.779Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T17:18:23.780Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 2.8s of which 0.0s paused, total 2.8s
2022-01-18T17:18:29.065Z - info: [ui] [BranchPruner] Last prune took place in 18 hours - skipping
2022-01-18T17:18:29.449Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T17:19:11.855Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/kesavan4954/projectdemo.git - kesavan4954 (has token)
2022-01-18T17:19:12.261Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/kesavan4954/projectdemo.git C:\Users\APTS-DXB-19\eclipse-workspace\demo_loop\projectdemo` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\APTS-DXB-19\eclipse-workspace\demo_loop\projectdemo'...
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T17:20:46.150Z - info: [ui] [BranchPruner] Last prune took place in 18 hours - skipping
2022-01-18T17:20:46.958Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T17:21:48.508Z - info: [ui] [AppStore] adding repository at C:\Users\APTS-DXB-19\eclipse-workspace\Trailclone to store
2022-01-18T17:21:54.255Z - info: [ui] Executing isUsingLFS: git lfs track (took 5.435s)
2022-01-18T17:22:33.479Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/kesavan4954/ConditionalStatement.git - kesavan4954 (has token)
2022-01-18T17:22:34.421Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/kesavan4954/ConditionalStatement.git C:\Users\APTS-DXB-19\eclipse-workspace\ConditionalStatement` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\APTS-DXB-19\eclipse-workspace\ConditionalStatement'...
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T17:28:13.554Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.029s)
2022-01-18T17:30:21.246Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/kesavan4954/MyRepo.git - kesavan4954 (has token)
2022-01-18T17:30:23.397Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=main clone --recursive --progress -- https://github.com/kesavan4954/MyRepo.git C:\Users\APTS-DXB-19\eclipse-workspace\MyRepo (took 1.742s)
2022-01-18T17:30:23.398Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=main clone --recursive --progress -- https://github.com/kesavan4954/MyRepo.git C:\Users\APTS-DXB-19\eclipse-workspace\MyRepo` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\APTS-DXB-19\eclipse-workspace\MyRepo'...
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T17:30:24.792Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/kesavan4954/MyRepo.git - kesavan4954 (has token)
2022-01-18T17:30:25.134Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=main clone --recursive --progress -- https://github.com/kesavan4954/MyRepo.git C:\Users\APTS-DXB-19\eclipse-workspace\MyRepo` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\APTS-DXB-19\eclipse-workspace\MyRepo'...
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T17:30:25.916Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/kesavan4954/MyRepo.git - kesavan4954 (has token)
2022-01-18T17:30:26.267Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=main clone --recursive --progress -- https://github.com/kesavan4954/MyRepo.git C:\Users\APTS-DXB-19\eclipse-workspace\MyRepo` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\APTS-DXB-19\eclipse-workspace\MyRepo'...
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T17:30:27.788Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/kesavan4954/MyRepo.git - kesavan4954 (has token)
2022-01-18T17:30:28.130Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=main clone --recursive --progress -- https://github.com/kesavan4954/MyRepo.git C:\Users\APTS-DXB-19\eclipse-workspace\MyRepo` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\APTS-DXB-19\eclipse-workspace\MyRepo'...
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T17:32:11.014Z - info: [ui] calling captureCommandOutput(where git)
2022-01-18T17:34:39.957Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 3.127s)
2022-01-18T17:34:40.866Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MyRepo - kesavan4954 (has token)
2022-01-18T17:34:43.059Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.099s)
2022-01-18T17:34:43.068Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T17:50:18.858Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.012s)
2022-01-18T17:53:33.484Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 2 repositories took 12.1s of which 1129.1s paused, total 1141.2s
2022-01-18T17:53:52.050Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MyRepo - kesavan4954 (has token)
2022-01-18T17:53:53.478Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.321s)
2022-01-18T17:53:53.479Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T17:53:53.662Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 2 repositories took 3.8s of which 0.0s paused, total 3.8s
2022-01-18T17:54:54.613Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/kesavan4954/TypeCasting.git - kesavan4954 (has token)
2022-01-18T17:54:55.476Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/kesavan4954/TypeCasting.git C:\Users\APTS-DXB-19\eclipse-workspace\TypeCasting` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\APTS-DXB-19\eclipse-workspace\TypeCasting'...
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T17:55:06.859Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/kesavan4954/TypeCasting.git - kesavan4954 (has token)
2022-01-18T17:55:07.213Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/kesavan4954/TypeCasting.git C:\Users\APTS-DXB-19\eclipse-workspace\TypeCasting` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\APTS-DXB-19\eclipse-workspace\TypeCasting'...
git: 'remote-https' is not a git command. See 'git --help'.

2022-01-18T18:08:02.225Z - info: [ui] [AppStore] loading 2 repositories from store
2022-01-18T18:08:02.269Z - info: [ui] [AppStore] found account: kesavan4954 (kesavan4954)
2022-01-18T18:08:11.190Z - info: [ui] Executing getRemotes: git remote -v (took 1.648s)
2022-01-18T18:08:11.199Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.711s)
2022-01-18T18:08:11.200Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.006s)
2022-01-18T18:08:14.093Z - info: [ui] launching: 2.9.6 (Windows 10.0.19042)
2022-01-18T18:08:14.093Z - info: [ui] execPath: 'C:\Users\APTS-DXB-19\AppData\Local\GitHubDesktop\app-2.9.6\GitHubDesktop.exe'
2022-01-18T18:08:17.259Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 3.164s)
2022-01-18T18:08:17.259Z - info: [ui] Executing getChangedFilesNumStats: git log 1631d54aa1b9e782087f83810d74d765bc978900 -C -M -m -1 --no-show-signature --first-parent --format=format: -z --numstat -- (took 2.726s)

**Comment by steveward** [comment]
Thanks for the log file. It looks like there is an issue with your installation. Could you try performing a fresh installation of GitHub Desktop by following these steps?

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that does not get things working for you.
