### ISSUE TITLE
Unable to sign in to Github Enterprise instance

### ISSUE THREAD

**Issue by indexanalytics** [desktop/desktop#13817]
When attempting to sign in to a Github Enterprise account, I receive the following error: 
Unable to authenticate with the Github Enterprise instance. Verify that the URL is correct, that your Github Enterprise instance is running version 2.8.0 or later, that you have an internet connection and try again.

### Version & OS

OS: Windows 10 Business (Build 10.0.19041)
Github Desktop Version: 2.9.6 (x64)
Github Enterprise Server version: 3.2

### Steps to reproduce the behavior

1. Open the Accounts tab of the Options menu in Github Desktop
2. Click "Sign In" on the Github Enterprise section
3. Input the enterprise address
4. Click "continue"

### Expected behavior

The account sign in should progress to the next phase of authentication

### Actual behavior

An error message is returned and sign in fails

### Screenshots

![image](https://user-images.githubusercontent.com/62109297/152382675-13b1ed31-ddc2-441d-8225-2fa29c9120ee.png)

### Logs

2022-02-03T15:52:06.732Z - error: [ui] fetchMetadata: unable to load metadata from 'https://cms.github.gov/api/v3/meta' as a fallback
TypeError: Failed to fetch
2022-02-03T15:52:13.424Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.cms.gov/api/v3/meta' as a fallback
Error: API rate limit exceeded for [IP]. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at dt (C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.5\webpack:\app\src\lib\http.ts:178:11)
    at C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.5\webpack:\app\src\lib\api.ts:1525:11
    at Object.endpointSupportsBasicAuth (C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.5\webpack:\app\src\lib\stores\sign-in-store.ts:255:11)
    at Object.setEndpoint (C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.5\webpack:\app\src\lib\stores\sign-in-store.ts:549:13)
2022-02-03T15:52:24.103Z - info: [ui] [AppStore] loading 3 repositories from store
2022-02-03T15:52:24.169Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2022-02-03T15:52:24.608Z - info: [ui] launching: 2.9.6 (Windows 10.0.19041)
2022-02-03T15:52:24.609Z - info: [ui] execPath: 'C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.6\GitHubDesktop.exe'
2022-02-03T15:52:30.526Z - info: [ui] calling captureCommandOutput(where git)
2022-02-03T15:52:45.808Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.cms.gov/api/v3/meta' as a fallback
Error: API rate limit exceeded for [IP]. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at dt (C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\http.ts:178:11)
    at C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\api.ts:1525:11
    at Object.endpointSupportsBasicAuth (C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\stores\sign-in-store.ts:255:11)
    at Object.setEndpoint (C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\stores\sign-in-store.ts:549:13)
2022-02-03T15:56:07.839Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Anonymous access denied
fatal: Authentication failed for 'https://github.cms.gov/[ORGANIZATION]/[REPO].git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-02-03T15:56:12.791Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Anonymous access denied
fatal: Authentication failed for 'https://github.cms.gov/[ORGANIZATION]/[REPO].git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-02-03T15:56:12.906Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 2 repositories took 2.9s of which 3.6s paused, total 6.6s
2022-02-03T15:56:27.574Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.cms.gov/api/v3/meta' as a fallback
Error: API rate limit exceeded for [IP]. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at dt (C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\http.ts:178:11)
    at C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\api.ts:1525:11
    at Object.endpointSupportsBasicAuth (C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\stores\sign-in-store.ts:255:11)
    at Object.setEndpoint (C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\stores\sign-in-store.ts:549:13)
2022-02-03T15:56:31.215Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.cms.gov/api/v3/meta' as a fallback
Error: API rate limit exceeded for [IP]. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at dt (C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\http.ts:178:11)
    at C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\api.ts:1525:11
    at Object.endpointSupportsBasicAuth (C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\stores\sign-in-store.ts:255:11)
    at Object.setEndpoint (C:\Users\[USER]\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\stores\sign-in-store.ts:549:13)

### Additional context

I previously had another account with the same Github Enterprise instance active on this Github Desktop application and computer. After removing that and attempting to add the new account I received the message described above. The error occurs when inputting the Enterprise address and clicking continue.

**Comment by indexanalytics** [comment]
Similar to issue 4159 https://github.com/desktop/desktop/issues/4159

**Comment by indexanalytics** [comment]
User error. Turns out the enterprise address needs to be the full path to the organization, not just the enterprise instance itself (github.cms.gov/my-org rather than github.cms.gov). This is probably due to the access controls involved with the instance.

**Comment by Khanyisa-Ngejane** [comment]
@indexanalytics i have an enterprise account with address https://github.com/Peniel-Impact-Investment
I am trying the solution you suggested not I follow: [ what is /my-org?]

**Comment by costcokramer** [comment]
found a successful workaround by:
1. create a personal access token via the GitHub web application's Settings menu, and copy it somewhere safe for later use (step 4) 
2. Go to the GitHub repo you'd like to clone, select the Code dropdown, Open in GitHub Desktop
3. Proceed with opening and confirm the org/repo URLs pre-populate as expected
4. sign in with your GitHub username and use the Personal Access Token as your password. 
5. Clone takes place on GitHub desktop, then all future clones are authenticated to your enterprise.

**Comment by TravisJoe** [comment]
I am unable to get around this. I keep getting the same authentication issue. But because now Github desktop requires you to authenticate through the browser there is no other authentication options. I can see the repos, I can clone them, but then it keeps saying it fails. I can then switch other to another git GUI tool and work with the repo.

**Comment by steveward** [comment]
@TravisJoe if you're still having issues please open a new issue and fill out the template so we can assist you further. Thanks!

**Comment by marknn3** [comment]
Use the GitHub.com Sign-in, even though you have an Enterprise account. This worked for me.
![image](https://github.com/desktop/desktop/assets/4366965/a26906b0-50ca-474d-9c18-7e76881306f8)

**Comment by ProfKaz** [comment]
> found a successful workaround by:
> 
>     1. create a personal access token via the GitHub web application's Settings menu, and copy it somewhere safe for later use (step 4)
> 
>     2. Go to the GitHub repo you'd like to clone, select the Code dropdown, Open in GitHub Desktop
> 
>     3. Proceed with opening and confirm the org/repo URLs pre-populate as expected
> 
>     4. sign in with your GitHub username and use the Personal Access Token as your password.
> 
>     5. Clone takes place on GitHub desktop, then all future clones are authenticated to your enterprise.

Is still not show me as connected, nevertheless, this workaround works for me. I´m connected to each repo and I can update.
