### ISSUE TITLE
Switched to branch 'feature-s105300' Your branch is up to date with 'origin/feature-s105300'. husky > post-checkout (node v14.17.0) error: GIT_CONFIG_PARAMETERS 中格式错误 fatal: 无法解析命令行中的配置 husky > post-checkout hook failed (cannot be bypassed with --no-verify due to Git specs)

### ISSUE THREAD

**Issue by caslanbigeyes** [desktop/desktop#13861]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by caslanbigeyes** [comment]
when checkout other branch ,alaways happen this tip ,is so hard to use;

**Comment by steveward** [comment]
Thanks for the issue. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by caslanbigeyes** [comment]
thank you your answer ，these are error logs

**Comment by caslanbigeyes** [comment]
2022-03-04T02:57:04.142Z - warn: [ui] fetchRepository: an error occurred for 'caslanbigeyes/LLF_blog'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Ke (/webpack:/app/src/lib/http.ts:170:11)
    at gt.fetchRepository (/webpack:/app/src/lib/api.ts:602:16)
    at /webpack:/app/src/lib/infer-last-push-for-repository.ts:38:13
    at ca.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/webpack:/app/src/lib/stores/app-store.ts:2815:11)
    at ca.refreshAllRepositories (/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2022-03-04T02:57:04.348Z - warn: [ui] fetchRepository: an error occurred for 'caslanbigeyes/LLF_blog'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Ke (/webpack:/app/src/lib/http.ts:170:11)
    at gt.fetchRepository (/webpack:/app/src/lib/api.ts:602:16)
    at /webpack:/app/src/lib/infer-last-push-for-repository.ts:48:11
    at ca.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/webpack:/app/src/lib/stores/app-store.ts:2815:11)
    at ca.refreshAllRepositories (/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2022-03-04T02:57:04.349Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: LLF_blog - caslanbigeyes (empty token)
2022-03-04T02:57:06.259Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.836s)
2022-03-04T02:57:06.287Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 11.2s of which 148178.5s paused, total 148189.7s
2022-03-04T02:57:31.884Z - info: [ui] [AppStore] adding repository at /Applications/code/ZY/srm-front-slod to store
2022-03-04T02:57:34.993Z - warn: [ui] fetchRepository: an error occurred for 'open-hand/choerodon-ui'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Ke (/webpack:/app/src/lib/http.ts:170:11)
    at gt.fetchRepository (/webpack:/app/src/lib/api.ts:602:16)
    at /webpack:/app/src/lib/infer-last-push-for-repository.ts:38:13
    at ca.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/webpack:/app/src/lib/stores/app-store.ts:2815:11)
    at ca.refreshAllRepositories (/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2022-03-04T02:57:35.184Z - warn: [ui] fetchRepository: an error occurred for 'open-hand/choerodon-ui'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Ke (/webpack:/app/src/lib/http.ts:170:11)
    at gt.fetchRepository (/webpack:/app/src/lib/api.ts:602:16)
    at /webpack:/app/src/lib/infer-last-push-for-repository.ts:48:11
    at ca.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/webpack:/app/src/lib/stores/app-store.ts:2815:11)
    at ca.refreshAllRepositories (/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2022-03-04T02:57:35.187Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: choerodon-ui - caslanbigeyes (empty token)
2022-03-04T02:57:38.422Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 3.209s)
2022-03-04T02:57:41.584Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.045s)
2022-03-04T02:57:44.641Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.402s)
2022-03-04T02:57:44.939Z - warn: [ui] fetchRepository: an error occurred for 'caslanbigeyes/LLF_blog'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Ke (/webpack:/app/src/lib/http.ts:170:11)
    at gt.fetchRepository (/webpack:/app/src/lib/api.ts:602:16)
    at /webpack:/app/src/lib/infer-last-push-for-repository.ts:38:13
    at ca.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/webpack:/app/src/lib/stores/app-store.ts:2815:11)
    at ca.refreshAllRepositories (/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2022-03-04T02:57:45.121Z - warn: [ui] fetchRepository: an error occurred for 'caslanbigeyes/LLF_blog'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Ke (/webpack:/app/src/lib/http.ts:170:11)
    at gt.fetchRepository (/webpack:/app/src/lib/api.ts:602:16)
    at /webpack:/app/src/lib/infer-last-push-for-repository.ts:48:11
    at ca.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/webpack:/app/src/lib/stores/app-store.ts:2815:11)
    at ca.refreshAllRepositories (/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2022-03-04T02:57:45.152Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 10 repositories took 11.7s of which 0.0s paused, total 11.7s
2022-03-04T02:58:28.144Z - info: [ui] [Timing] Action 'checkout branch from list' for 'srm-front-slod' took 0.888s
2022-03-04T03:10:42.579Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/SKHon/diudiu.git - caslanbigeyes (empty token)
2022-03-04T03:10:45.763Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=main clone --recursive --progress -- https://github.com/SKHon/diudiu.git /Applications/code/diudiu (took 3.107s)
2022-03-04T03:10:45.797Z - info: [ui] [AppStore] adding repository at /Applications/code/diudiu to store
2022-03-04T03:10:47.036Z - info: [ui] [BranchPruner] No branches to prune.
2022-03-04T03:13:04.093Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: diudiu - caslanbigeyes (empty token)
2022-03-04T03:13:05.550Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.431s)
2022-03-04T03:13:05.566Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 11 repositories took 4.9s of which 0.0s paused, total 4.9s
2022-03-04T03:36:56.343Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.146s)
2022-03-04T03:43:19.741Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.130s)
2022-03-04T04:54:37.553Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.077s)
2022-03-04T04:54:38.505Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Ke (/webpack:/app/src/lib/http.ts:170:11)
    at gt.fetchPushControl (/webpack:/app/src/lib/api.ts:951:7)
    at Object.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:961:39)
    at /webpack:/app/src/lib/stores/app-store.ts:4203:32
    at Object.withPushPullFetch (/webpack:/app/src/lib/stores/app-store.ts:3806:5)
    at Object.performFetch (/webpack:/app/src/lib/stores/app-store.ts:4159:5)
    at _o.performAndScheduleFetch (/webpack:/app/src/lib/stores/helpers/background-fetcher.ts:102:7)
2022-03-04T05:27:46.404Z - info: [ui] Stats reported.
2022-03-04T05:53:16.858Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 11 repositories took 9.2s of which 8643.0s paused, total 8652.3s
2022-03-04T05:55:05.255Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.942s)
2022-03-04T07:00:57.609Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.244s)
2022-03-04T07:00:58.505Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Ke (/webpack:/app/src/lib/http.ts:170:11)
    at gt.fetchPushControl (/webpack:/app/src/lib/api.ts:951:7)
    at Object.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:961:39)
    at /webpack:/app/src/lib/stores/app-store.ts:4203:32
    at Object.withPushPullFetch (/webpack:/app/src/lib/stores/app-store.ts:3806:5)
    at Object.performFetch (/webpack:/app/src/lib/stores/app-store.ts:4159:5)
    at _o.performAndScheduleFetch (/webpack:/app/src/lib/stores/helpers/background-fetcher.ts:102:7)
2022-03-04T07:10:47.199Z - info: [ui] [BranchPruner] Last prune took place in 20 hours - skipping
2022-03-04T07:17:51.442Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.333s)
2022-03-04T07:17:53.397Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 11 repositories took 8.9s of which 0.0s paused, total 8.9s
2022-03-04T07:17:54.840Z - info: [ui] [BranchPruner] No branches to prune.
2022-03-04T07:17:55.002Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2022-03-04T07:17:56.405Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.032s)
2022-03-04T07:24:51.867Z - info: [ui] [AppStore] loading 11 repositories from store
2022-03-04T07:24:51.868Z - info: [ui] [AppStore] found account: caslanbigeyes (blue)
2022-03-04T07:24:51.961Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2022-03-04T07:24:53.181Z - warn: [ui] Error refreshing account 'caslanbigeyes'
Error: Cannot update an account which doesn't have a token: caslanbigeyes
    at Ye (/webpack:/app/src/lib/fatal-error.ts:3:9)
    at /webpack:/app/src/lib/stores/accounts-store.ts:214:12
    at Fr.tryUpdateAccount (/webpack:/app/src/lib/stores/accounts-store.ts:134:20)
    at /webpack:/app/src/lib/stores/accounts-store.ts:114:37
    at Array.map (<anonymous>)
    at Fr.refresh (/webpack:/app/src/lib/stores/accounts-store.ts:114:21)
    at Fr.loadInitialState (/webpack:/app/src/lib/stores/app-store.ts:1900:24)
2022-03-04T07:24:53.334Z - info: [ui] launching: 2.9.11 (Mac OS 10.15.7)
2022-03-04T07:24:53.335Z - info: [ui] execPath: '/Users/lilingfeng/Desktop/GitHub Desktop 上午11.31.54.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2022-03-04T07:24:53.673Z - warn: [ui] Alive channel request failed: Error: Not Found
2022-03-04T07:24:54.172Z - warn: [ui] Alive channel request failed: Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
2022-03-04T07:24:54.256Z - warn: [ui] Alive web socket request failed: Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
2022-03-04T07:24:54.257Z - error: [ui] Could not get Alive web socket URL for 'caslanbigeyes'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at qt (/webpack:/app/src/lib/http.ts:178:11)
    at Pn.getAliveWebSocketURL (/webpack:/app/src/lib/api.ts:714:7)
    at Object.createSessionForAccount (/webpack:/app/src/lib/stores/alive-store.ts:150:7)
    at Object.subscribeToAccount (/webpack:/app/src/lib/stores/alive-store.ts:207:11)
    at Object._subscribeToAccounts (/webpack:/app/src/lib/stores/alive-store.ts:126:37)
2022-03-04T07:24:54.323Z - warn: [ui] Alive channel request failed: Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
2022-03-04T07:24:54.473Z - warn: [ui] Alive channel request failed: Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
2022-03-04T07:24:54.547Z - warn: [ui] fetchAll: 'repos/open-hand/choerodon-ui/issues?state=all&since=2021-10-14T13%3A24%3A50Z' returned a 403
2022-03-04T07:24:56.768Z - info: [ui] [BranchPruner] Last prune took place in 20 hours - skipping
2022-03-04T07:24:56.858Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at qt (/webpack:/app/src/lib/http.ts:178:11)
    at Pn.fetchProtectedBranches (/webpack:/app/src/lib/api.ts:1271:7)
    at Fr.updateBranchProtectionsFromAPI (/webpack:/app/src/lib/stores/app-store.ts:3700:11)
2022-03-04T07:24:56.933Z - warn: [ui] fetchAll: 'repos/skhon/diudiu/issues?state=all&since=2022-03-04T02%3A41%3A39Z' returned a 403
2022-03-04T07:24:56.933Z - warn: [ui] fetchAll: 'repos/skhon/diudiu/pulls?state=open' returned a 403
2022-03-04T07:24:56.960Z - warn: [ui] fetchRepository: an error occurred for 'SKHon/diudiu'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at qt (/webpack:/app/src/lib/http.ts:178:11)
    at Pn.fetchRepository (/webpack:/app/src/lib/api.ts:730:16)
    at Fr.repositoryWithRefreshedGitHubRepository (/webpack:/app/src/lib/stores/app-store.ts:3656:11)
2022-03-04T07:24:56.961Z - warn: [ui] fetchMentionables: failed for skhon/diudiu
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at qt (/webpack:/app/src/lib/http.ts:178:11)
    at Pn.fetchMentionables (/webpack:/app/src/lib/api.ts:1404:13)
    at XP.constructor.updateMentionables (/webpack:/app/src/lib/stores/github-user-store.ts:90:11)
2022-03-04T07:24:58.265Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: diudiu - caslanbigeyes (empty token)
2022-03-04T07:24:58.528Z - info: [ui] [Timing] Action 'checkout branch from list' for 'skhon/diudiu' took 0.264s
2022-03-04T07:24:58.538Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at qt (/webpack:/app/src/lib/http.ts:178:11)
    at Pn.fetchPushControl (/webpack:/app/src/lib/api.ts:1245:7)
    at Fr.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:1057:39)
2022-03-04T07:25:00.304Z - error: [ui] Highlighter worked failed for old contents
Error: timed out
    at /webpack:/app/src/lib/highlighter/worker.ts:85:14
2022-03-04T07:25:00.306Z - error: [ui] Highlighter worked failed for new contents
Error: timed out
    at /webpack:/app/src/lib/highlighter/worker.ts:85:14
2022-03-04T07:25:00.310Z - error: [ui] Highlighter worked failed for old contents
Error: timed out
    at /webpack:/app/src/lib/highlighter/worker.ts:85:14
2022-03-04T07:25:00.312Z - error: [ui] Highlighter worked failed for new contents
Error: timed out
    at /webpack:/app/src/lib/highlighter/worker.ts:85:14
2022-03-04T07:25:02.835Z - error: [ui] `git -c credential.helper= checkout --progress feature-s80490-99615 --` exited with an unexpected code: 1.
stdout:
Your branch is up to date with 'origin/feature-s80490-99615'.

stderr:
Switched to branch 'feature-s80490-99615'
husky > post-checkout (node v14.17.0)
error: GIT_CONFIG_PARAMETERS 中格式错误
fatal: 无法解析命令行中的配置
husky > post-checkout hook failed (cannot be bypassed with --no-verify due to Git specs)

2022-03-04T07:25:03.131Z - info: [ui] [Timing] Action 'checkout branch from list' for 'srm-front-slod' took 0.780s
2022-03-04T07:26:48.984Z - warn: [ui] fetchRepository: an error occurred for 'open-hand/choerodon-ui'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at qt (/webpack:/app/src/lib/http.ts:178:11)
    at Pn.fetchRepository (/webpack:/app/src/lib/api.ts:730:16)
    at /webpack:/app/src/lib/infer-last-push-for-repository.ts:38:13
    at Ra.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/webpack:/app/src/lib/stores/app-store.ts:3119:11)
    at Ra.refreshAllRepositories (/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2022-03-04T07:26:49.127Z - warn: [ui] fetchRepository: an error occurred for 'open-hand/choerodon-ui'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at qt (/webpack:/app/src/lib/http.ts:178:11)
    at Pn.fetchRepository (/webpack:/app/src/lib/api.ts:730:16)
    at /webpack:/app/src/lib/infer-last-push-for-repository.ts:48:11
    at Ra.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/webpack:/app/src/lib/stores/app-store.ts:3119:11)
    at Ra.refreshAllRepositories (/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2022-03-04T07:26:50.396Z - warn: [ui] fetchRepository: an error occurred for 'caslanbigeyes/LLF_blog'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at qt (/webpack:/app/src/lib/http.ts:178:11)
    at Pn.fetchRepository (/webpack:/app/src/lib/api.ts:730:16)
    at /webpack:/app/src/lib/infer-last-push-for-repository.ts:38:13
    at Ra.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/webpack:/app/src/lib/stores/app-store.ts:3119:11)
    at Ra.refreshAllRepositories (/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2022-03-04T07:26:50.617Z - warn: [ui] fetchRepository: an error occurred for 'caslanbigeyes/LLF_blog'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at qt (/webpack:/app/src/lib/http.ts:178:11)
    at Pn.fetchRepository (/webpack:/app/src/lib/api.ts:730:16)
    at /webpack:/app/src/lib/infer-last-push-for-repository.ts:48:11
    at Ra.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/webpack:/app/src/lib/stores/app-store.ts:3119:11)
    at Ra.refreshAllRepositories (/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2022-03-04T07:26:50.618Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: LLF_blog - caslanbigeyes (empty token)
2022-03-04T07:26:52.504Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.858s)
2022-03-04T07:26:52.727Z - warn: [ui] fetchRepository: an error occurred for 'SKHon/diudiu'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at qt (/webpack:/app/src/lib/http.ts:178:11)
    at Pn.fetchRepository (/webpack:/app/src/lib/api.ts:730:16)
    at /webpack:/app/src/lib/infer-last-push-for-repository.ts:38:13
    at Ra.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/webpack:/app/src/lib/stores/app-store.ts:3119:11)
    at Ra.refreshAllRepositories (/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2022-03-04T07:26:52.909Z - warn: [ui] fetchRepository: an error occurred for 'skhon/diudiu'
Error: API rate limit exceeded for 42.2.67.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at qt (/webpack:/app/src/lib/http.ts:178:11)
    at Pn.fetchRepository (/webpack:/app/src/lib/api.ts:730:16)
    at /webpack:/app/src/lib/infer-last-push-for-repository.ts:48:11
    at Ra.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/webpack:/app/src/lib/stores/app-store.ts:3119:11)
    at Ra.refreshAllRepositories (/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2022-03-04T07:26:52.910Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 10 repositories took 4.5s of which 0.0s paused, total 4.5s
2022-03-04T07:27:46.845Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.250s)
2022-03-04T07:28:14.852Z - error: [ui] `git -c credential.helper= checkout --progress workbench --` exited with an unexpected code: 1.
stdout:
Your branch is up to date with 'origin/workbench'.

stderr:
Switched to branch 'workbench'
husky > post-checkout (node v14.17.0)
error: GIT_CONFIG_PARAMETERS 中格式错误
fatal: 无法解析命令行中的配置
husky > post-checkout hook failed (cannot be bypassed with --no-verify due to Git specs)

2022-03-04T07:28:15.138Z - info: [ui] [Timing] Action 'checkout branch from list' for 'srm-front-slod' took 0.624s

**Comment by caslanbigeyes** [comment]
i hope you can resolve my question ,I use very early git deskTop version  。thank you I  alse hope to use the latest version

**Comment by caslanbigeyes** [comment]
There is no husky problem caused by switching branches about GitHub Desktop 上午11.31.54 版本

**Comment by steveward** [comment]
@caslanbigeyes it looks like the issue is with your `post-checkout` hook:

```
Switched to branch 'workbench'
husky > post-checkout (node v14.17.0)
error: bad format in GIT_CONFIG_PARAMETERS
fatal: cannot parse configuration from command line
```

Can you see if you encounter this error when using the command line as well?

**Comment by caslanbigeyes** [comment]
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/53009552/157147064-6ebd9e43-af85-4c93-93b0-1d76fc37ea4b.png">
好像没有出现post-checkout 这个问题

**Comment by caslanbigeyes** [comment]
I understand that this problem only exists in the updated version of desktop. Can desktop skip this check because the config in my code is specified by the company and cannot be changed.

**Comment by steveward** [comment]
>Can desktop skip this check because the config in my code is specified by the company and cannot be changed.

What specific check are you referring to?

**Comment by steveward** [comment]
@caslanbigeyes as we have not heard back from you I am going to close this issue. Let me know if we can assist any further.
