### ISSUE TITLE
Desktop access to Enterprise denied after in-browser authentication

### ISSUE THREAD

**Issue by BramVanroy** [desktop/desktop#14012]
### Describe the bug

When I try to add my enterprise account to the program, I get an error message saying I must authenticate to access this API. Even though that is exactly what I did a second before. Under settings/applications in the browser, I can also see that Github Desktop has indeed been granted API access. Yet the program does not seem to see it so.

### Version & OS

Version 2.9.10 (x64) on Windows 10

### Steps to reproduce the behavior

1. Add new account to Github Enterprise
2. Add correct enterprise url
3. Click the button "Sign in using your browser"
4. Authenticate
5. The browser redirects to the app, which shows the error "Must authenticate to access this API."

### Expected behavior

Simply add an enterprise account via browser login.

### Actual behavior

The browser redirects to the app, which shows the error "Must authenticate to access this API."

### Screenshot

![error](https://user-images.githubusercontent.com/2779410/155701495-8ecbb4fa-3944-4ba1-8d8d-13422eef1827.png)

### Logs

```
2022-02-25T10:39:35.188Z - info: [ui] [SignInStore] initializing OAuth flow
2022-02-25T10:39:35.194Z - info: [main] opening in browser: <auth-link>
2022-02-25T10:39:35.551Z - info: [main] Received possible protocol arguments: 4
2022-02-25T10:39:35.551Z - info: [main] Processing protocol url
2022-02-25T10:39:35.551Z - info: [ui] [Dispatcher] requesting authenticated user
2022-02-25T10:39:35.708Z - warn: [ui] fetchAccount: failed with endpoint <endpoint-link/v3>
Error: Must authenticate to access this API.
    at qt (C:\Users\bramv\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\lib\http.ts:178:11)
    at Pn.fetchAccount (C:\Users\bramv\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\lib\api.ts:807:7)
    at In (C:\Users\bramv\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\lib\api.ts:1580:11)
    at Object.dispatchURLAction (C:\Users\bramv\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\ui\dispatcher\dispatcher.ts:1770:17)
2022-02-25T10:39:35.708Z - warn: [ui] fetchUser: failed with endpoint <endpoint-link/v3>
Error: Must authenticate to access this API.
    at qt (C:\Users\bramv\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\lib\http.ts:178:11)
    at Pn.fetchAccount (C:\Users\bramv\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\lib\api.ts:807:7)
    at In (C:\Users\bramv\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\lib\api.ts:1580:11)
    at Object.dispatchURLAction (C:\Users\bramv\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\ui\dispatcher\dispatcher.ts:1770:17)
2022-02-25T10:39:35.709Z - info: [ui] [SignInStore] error with OAuth flow
Error: Must authenticate to access this API.
    at qt (C:\Users\bramv\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\lib\http.ts:178:11)
    at Pn.fetchAccount (C:\Users\bramv\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\lib\api.ts:807:7)
    at In (C:\Users\bramv\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\lib\api.ts:1580:11)
    at Object.dispatchURLAction (C:\Users\bramv\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\ui\dispatcher\dispatcher.ts:1770:17)
```

**Comment by BramVanroy** [comment]
It seems that restarting the client solved the issue.
