### ISSUE TITLE
cannot discard changes due to way that recycle bin is working

### ISSUE THREAD

**Issue by PeterTaylor2** [desktop/desktop#14170]
### Describe the bug
When trying to discard some changes I was told that changes could not be discarded.

"Failed to discard changes.

A common reason for this is that the Recycle bin is set to discard changes immediately"

Obviously this is absurd!

### Version & OS

Version 2.9.9 (x64) - Windows 10

### Steps to reproduce the behavior

Not sure I can get you to reproduce the error since you are not on my PC.

Anyway I have some binaries for which I want to discard the changes. What happens is that I get a pop-up window (with the contents as above). This is obviously irritating, ridiculous and also didn't used to happen.

### Expected behavior

Allow the changes to be discarded. If you must give me a warning that I can't recover (due to behaviour of the recycle bin), but do not break the application.

### Actual behavior

See above.

### Screenshots

![image](https://user-images.githubusercontent.com/33470226/158290145-7a21718a-899b-428c-ac63-6eed98c310bc.png)

### Logs

extract with names redacted

2022-03-15T01:51:42.246Z - error: [ui] Failed discarding changes
Error: Error invoking remote method 'move-to-trash': Error: Failed to perform delete operation
    at EventEmitter.i.invoke (node:electron/js2c/renderer_init:57:526)
    at C:\Users\redacted\AppData\Local\GitHubDesktop\app-2.9.9\webpack:\app\src\lib\stores\git-store.ts:1462:62
    at C:\Users\redacted\AppData\Local\GitHubDesktop\app-2.9.9\webpack:\app\src\lib\queue-work.ts:39:5
    at Es.discardChanges (C:\Users\redacted\AppData\Local\GitHubDesktop\app-2.9.9\webpack:\app\src\lib\stores\git-store.ts:1457:50)
    at Pr._discardChanges (C:\Users\redacted\AppData\Local\GitHubDesktop\app-2.9.9\webpack:\app\src\lib\stores\app-store.ts:4356:5)
    at Object.PS.discard [as onSubmit] (C:\Users\redacted\AppData\Local\GitHubDesktop\app-2.9.9\webpack:\app\src\ui\discard-changes\discard-changes-dialog.tsx:153:42)

**Comment by sergiou87** [comment]
Thanks for your report! This was already fixed in #13904 and the fix was released in 2.9.11, so you just need to upgrade the app and it should work again 😄
