### ISSUE TITLE
Repo is potentially unsafe and trust button does not work

### ISSUE THREAD

**Issue by marticliment** [desktop/desktop#14369]
### The problem

I can't trust a repository placed in a mapped network drive at `Y:` by clicking the "Trust Repository" button when a repo is marked as potentially unsafe.

### Release version

2.9.14

### Operating system

Windows 11 10.0.22593.1

### Steps to reproduce the behavior

1. Open github desktop
2. Select a repo placed on a mapped network drive
3. Click trust and expect something to happen

### Log files

```
2022-04-14T12:26:23.773Z - info: [ui] [AppStore] loading 2 repositories from store
2022-04-14T12:26:23.775Z - info: [ui] [AppStore] found account: martinet101 (Martí Climent)
2022-04-14T12:26:25.554Z - info: [ui] Subscribed 'martinet101' to Alive channel
2022-04-14T12:26:25.730Z - info: [ui] launching: 2.9.12 (Windows 10.0.22593)
2022-04-14T12:26:25.732Z - info: [ui] execPath: 'C:\Users\marti\AppData\Local\GitHubDesktop\app-2.9.12\GitHubDesktop.exe'
2022-04-14T12:26:25.732Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.871s)
2022-04-14T12:26:26.083Z - info: [ui] Stats reported.
2022-04-14T12:26:28.801Z - info: [ui] Executing getWorkingDirectoryDiff: git diff --no-ext-diff --patch-with-raw -z --no-color --no-index -- /dev/null __init__.exe (took 2.130s)
2022-04-14T12:26:28.805Z - info: [ui] Executing getWorkingDirectoryDiff: git diff --no-ext-diff --patch-with-raw -z --no-color --no-index -- /dev/null __init__.exe (took 2.167s)
2022-04-14T12:26:29.067Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ElevenClock - martinet101 (has token)
2022-04-14T12:26:38.401Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 9.261s)
2022-04-14T12:26:42.463Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.803s)
2022-04-14T12:26:42.478Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 14.107s)
2022-04-14T12:26:42.488Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 15.806s)
2022-04-14T12:26:42.496Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 15.852s)
2022-04-14T12:38:11.026Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.032s)
2022-04-14T12:38:11.503Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 1.5s of which 0.0s paused, total 1.5s
2022-04-14T12:38:12.294Z - info: [ui] Executing getWorkingDirectoryDiff: git diff --no-ext-diff --patch-with-raw -z --no-color --no-index -- /dev/null __init__.exe (took 1.266s)
2022-04-14T12:38:12.524Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ElevenClock - martinet101 (has token)
2022-04-14T12:38:13.992Z - info: [ui] Executing getWorkingDirectoryDiff: git diff --no-ext-diff --patch-with-raw -z --no-color --no-index -- /dev/null __init__.exe (took 1.402s)
2022-04-14T12:38:15.371Z - info: [ui] Executing pull: git -c credential.helper= -c protocol.version=2 -c rebase.backend=merge pull --progress origin (took 2.682s)
2022-04-14T12:38:17.859Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 5.261s)
2022-04-14T12:38:17.868Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.119s)
2022-04-14T12:38:17.876Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 6.842s)
2022-04-14T12:39:36.704Z - info: [ui] Executing getWorkingDirectoryDiff: git diff --no-ext-diff --patch-with-raw -z --no-color --no-index -- /dev/null __init__.exe (took 1.133s)
2022-04-14T12:39:38.886Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 3.309s)
2022-04-14T12:39:52.374Z - info: [ui] Executing createCommit: git commit -F - (took 1.119s)
2022-04-14T12:39:53.963Z - info: [ui] [Timing] Action 'create commit' for 'martinet101/ElevenClock' took 3.202s
2022-04-14T12:39:54.691Z - info: [ui] Executing getWorkingDirectoryDiff: git diff --no-ext-diff --patch-with-raw -z --no-color --no-index -- /dev/null __init__.exe (took 1.177s)
2022-04-14T12:39:55.830Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ElevenClock - martinet101 (has token)
2022-04-14T12:39:57.245Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.957s)
2022-04-14T12:39:57.570Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 1.689s)
2022-04-14T12:40:00.261Z - info: [ui] Executing getWorkingDirectoryDiff: git diff --no-ext-diff --patch-with-raw -z --no-color --no-index -- /dev/null __init__.exe (took 1.175s)
2022-04-14T12:40:12.151Z - info: [ui] [AppStore] loading 2 repositories from store
2022-04-14T12:40:12.154Z - info: [ui] [AppStore] found account: martinet101 (Martí Climent)
2022-04-14T12:40:12.170Z - info: [ui] [BranchPruner] Last prune took place 14 minutes ago - skipping
2022-04-14T12:40:13.863Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.681s)
2022-04-14T12:40:13.868Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//samba-server/SPTPrograms/ElevenClock' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //samba-server/SPTPrograms/ElevenClock

2022-04-14T12:40:13.919Z - info: [ui] Subscribed 'martinet101' to Alive channel
2022-04-14T12:40:13.920Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//samba-server/SPTPrograms/ElevenClock' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //samba-server/SPTPrograms/ElevenClock

2022-04-14T12:40:13.927Z - info: [ui] launching: 2.9.14 (Windows 10.0.22593)
2022-04-14T12:40:13.928Z - info: [ui] execPath: 'C:\Users\marti\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-14T12:40:14.489Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//samba-server/SPTPrograms/ElevenClock' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //samba-server/SPTPrograms/ElevenClock

2022-04-14T12:40:31.974Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//samba-server/SPTPrograms/win32mica' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //samba-server/SPTPrograms/win32mica

2022-04-14T12:40:31.991Z - error: [ui] `git for-each-ref --format=%00%(refname)%00%(objectname)%00%(upstream)%00%(symref)%00%(HEAD)%00 refs/heads refs/remotes` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//samba-server/SPTPrograms/win32mica' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //samba-server/SPTPrograms/win32mica

2022-04-14T12:40:32.571Z - error: [ui] Branch fast-forwarding failed
GitError: fatal: unsafe repository ('//samba-server/SPTPrograms/win32mica' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //samba-server/SPTPrograms/win32mica

    at C:\Users\marti\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\git\core.ts:253:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at C:\Users\marti\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\trampoline\trampoline-environment.ts:40:13
    at C:\Users\marti\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\trampoline\trampoline-tokens.ts:33:5
    at C:\Users\marti\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\git\for-each-ref.ts:90:9
    at $r.fastForwardBranches (C:\Users\marti\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4264:13)
    at C:\Users\marti\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4589:18
    at $r.withPushPullFetch (C:\Users\marti\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4119:5)
    at $r.performFetch (C:\Users\marti\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4553:5)
    at Zo.performAndScheduleFetch (C:\Users\marti\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2022-04-14T12:40:32.582Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//samba-server/SPTPrograms/win32mica' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //samba-server/SPTPrograms/win32mica

2022-04-14T12:40:51.820Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 2 repositories took 0.0s of which 0.0s paused, total 0.0s
2022-04-14T12:41:10.926Z - info: [ui] [AppStore] loading 2 repositories from store
2022-04-14T12:41:10.929Z - info: [ui] [AppStore] found account: martinet101 (Martí Climent)
2022-04-14T12:41:12.518Z - info: [ui] Subscribed 'martinet101' to Alive channel
2022-04-14T12:41:12.581Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.640s)
2022-04-14T12:41:12.636Z - info: [ui] launching: 2.9.14 (Windows 10.0.22593)
2022-04-14T12:41:12.639Z - info: [ui] execPath: 'C:\Users\marti\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-14T12:45:06.929Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.0s of which 0.0s paused, total 0.0s
2022-04-14T12:45:07.683Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//samba-server/SPTPrograms/ElevenClock' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //samba-server/SPTPrograms/ElevenClock

2022-04-14T12:45:47.294Z - info: [ui] [AppStore] loading 2 repositories from store
2022-04-14T12:45:47.299Z - info: [ui] [AppStore] found account: martinet101 (Martí Climent)
2022-04-14T12:45:47.422Z - info: [ui] launching: 2.9.14 (Windows 10.0.22593)
2022-04-14T12:45:47.426Z - info: [ui] execPath: 'C:\Users\marti\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-14T12:45:47.689Z - info: [ui] Subscribed 'martinet101' to Alive channel
2022-04-14T12:48:29.088Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.0s of which 0.0s paused, total 0.0s
```

### Screenshots

![image](https://user-images.githubusercontent.com/53119851/163393856-9dedb94f-c56e-4f68-b210-117e4e61bd19.png)

(Please note that the repo selected is Y:/ElevenClock, but Github desktop recognizes it as the entire network path)

### Additional context

Only happens on the latest version

**Comment by niik** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The [latest update](https://github.com/desktop/desktop/issues/14336#issuecomment-1098490973) as of writing this is that WSL and NAS (or path beginning with `//`) will not work. This is due to a security fix in Git for Windows and we're working with that team to come up with a permanent fix. In the meantime there are links to the installer for an older version of Desktop here: https://github.com/desktop/desktop/issues/14336#issuecomment-1098309322.

**Comment by marticliment** [comment]
Ah, ok, sorry for the duplicate
