### ISSUE TITLE
GithHub Desktop unable to load enterprise repository

### ISSUE THREAD

**Issue by Jeeyuen-Rick** [desktop/desktop#14387]
### The problem

I login with both my personal and enterprise account for my GitHub Desktop on Winddows 10. I am not able to load my enterprise repository after I upgraded to version 2.1.14. I tried the "Trust repository..." button on the GitHub Desktop and "git config --global --add safe.directory" in Git Shell.

### Release version

2.1.14

### Operating system

Wins

### Log files

2022-04-15T13:20:32.008Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T13:20:32.013Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T13:20:33.656Z - info: [ui] Executing getRemotes: git remote -v (took 1.623s)
2022-04-15T13:20:33.662Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//batfs-sb04-cifs/vmgr/sb04/rickyu/Ccti/scm/javascript_build_harness' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //batfs-sb04-cifs/vmgr/sb04/rickyu/Ccti/scm/javascript_build_harness

2022-04-15T13:20:33.719Z - info: [ui] launching: 2.9.13 (Windows 10.0.19044)
2022-04-15T13:20:33.721Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.13\GitHubDesktop.exe'
2022-04-15T13:20:33.890Z - info: [ui] Stats reported.
2022-04-15T13:20:46.606Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T13:20:46.612Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T13:20:48.217Z - info: [ui] launching: 2.9.13 (Windows 10.0.19044)
2022-04-15T13:20:48.219Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.13\GitHubDesktop.exe'
2022-04-15T13:20:48.236Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.602s)
2022-04-15T13:22:19.261Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T13:22:19.267Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T13:22:20.808Z - info: [ui] launching: 2.9.13 (Windows 10.0.19044)
2022-04-15T13:22:20.810Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.13\GitHubDesktop.exe'
2022-04-15T13:22:20.936Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.629s)
2022-04-15T13:22:59.325Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//batfs-sb04-cifs/vmgr/sb04/rickyu/Ccti/scm/javascript_build_harness' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //batfs-sb04-cifs/vmgr/sb04/rickyu/Ccti/scm/javascript_build_harness

2022-04-15T13:23:23.939Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T13:23:23.945Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T13:23:25.605Z - info: [ui] launching: 2.9.14 (Windows 10.0.19044)
2022-04-15T13:23:25.607Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-15T13:23:25.708Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.740s)
2022-04-15T13:24:26.336Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven

2022-04-15T13:24:26.369Z - error: [ui] `git for-each-ref --format=%00%(refname)%00%(objectname)%00%(upstream)%00%(symref)%00%(HEAD)%00 refs/heads refs/remotes` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven

2022-04-15T13:24:27.094Z - error: [ui] Branch fast-forwarding failed
GitError: fatal: unsafe repository ('//batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven

    at C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\git\core.ts:253:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\trampoline\trampoline-environment.ts:40:13
    at C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\trampoline\trampoline-tokens.ts:33:5
    at C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\git\for-each-ref.ts:90:9
    at $r.fastForwardBranches (C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4264:13)
    at C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4589:18
    at $r.withPushPullFetch (C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4119:5)
    at $r.performFetch (C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4553:5)
    at Zo.performAndScheduleFetch (C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2022-04-15T13:24:27.138Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven

2022-04-15T13:24:27.246Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven

2022-04-15T13:25:10.980Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T13:25:10.983Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T13:25:12.586Z - info: [ui] launching: 2.9.14 (Windows 10.0.19044)
2022-04-15T13:25:12.590Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-15T13:25:12.666Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.654s)
2022-04-15T13:25:12.757Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven

2022-04-15T13:25:41.117Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/Jeeyuen-Rick/bundle_size_benchmarking.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-04-15T13:25:41.350Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 2.2s of which 0.0s paused, total 2.2s
2022-04-15T13:28:10.906Z - info: [ui] [SignInStore] initializing OAuth flow
2022-04-15T13:28:10.907Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=88689334-dcbf-4078-b936-156dc75017ad
2022-04-15T13:29:14.024Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T13:29:14.027Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T13:29:15.586Z - info: [ui] launching: 2.9.14 (Windows 10.0.19044)
2022-04-15T13:29:15.592Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-15T13:29:15.628Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.577s)
2022-04-15T13:29:48.176Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/Jeeyuen-Rick/bundle_size_benchmarking.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-04-15T13:29:48.428Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 1.9s of which 0.0s paused, total 1.9s
2022-04-15T13:30:19.587Z - info: [ui] [SignInStore] initializing OAuth flow
2022-04-15T13:30:19.588Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=5a1a12ab-7533-4cfb-bc16-36294cd7359b
2022-04-15T13:33:32.146Z - info: [ui] [SignInStore] initializing OAuth flow
2022-04-15T13:33:32.154Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=bb129093-d430-4d6a-92c9-f938e8ce7995
2022-04-15T13:36:04.903Z - info: [ui] [AppStore] removing account rickyu (Rick Yu) from store
2022-04-15T13:36:38.498Z - info: [ui] [SignInStore] initializing OAuth flow
2022-04-15T13:36:38.505Z - info: [main] opening in browser: https://github.mathworks.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=9e2ae573-f6ef-437f-839b-0cf6fad86477
2022-04-15T13:37:03.745Z - info: [main] Received possible protocol arguments: 4
2022-04-15T13:37:03.749Z - info: [main] Processing protocol url
2022-04-15T13:37:03.757Z - info: [ui] [Dispatcher] requesting authenticated user
2022-04-15T13:37:03.911Z - info: [ui] [SignInStore] account resolved
2022-04-15T13:37:03.912Z - info: [ui] [AppStore] adding account rickyu (Rick Yu) to store
2022-04-15T13:38:06.972Z - info: [ui] [BranchPruner] Last prune took place 6 minutes ago - skipping
2022-04-15T13:44:14.107Z - info: [ui] [SignInStore] initializing OAuth flow
2022-04-15T13:44:14.116Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=3de87050-c7ed-4e22-89f1-102c9b6ab6d1
2022-04-15T13:44:24.794Z - info: [main] Received possible protocol arguments: 4
2022-04-15T13:44:24.802Z - info: [main] Processing protocol url
2022-04-15T13:44:24.802Z - info: [ui] [Dispatcher] requesting authenticated user
2022-04-15T13:44:25.359Z - info: [ui] [SignInStore] account resolved
2022-04-15T13:44:25.360Z - info: [ui] [AppStore] adding account Jeeyuen-Rick (Rick Yu) to store
2022-04-15T13:44:25.511Z - info: [ui] Subscribed 'Jeeyuen-Rick' to Alive channel
2022-04-15T13:45:13.047Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: bundle_size_benchmarking - Jeeyuen-Rick (has token)
2022-04-15T13:45:14.100Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 2.5s of which 0.0s paused, total 2.5s
2022-04-15T13:46:27.422Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T13:46:27.425Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T13:46:27.425Z - info: [ui] [AppStore] found account: Jeeyuen-Rick (Rick Yu)
2022-04-15T13:46:29.118Z - info: [ui] Subscribed 'Jeeyuen-Rick' to Alive channel
2022-04-15T13:46:29.165Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.704s)
2022-04-15T13:46:29.188Z - info: [ui] launching: 2.9.14 (Windows 10.0.19044)
2022-04-15T13:46:29.188Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-15T13:47:17.852Z - info: [main] Received possible protocol arguments: 2
2022-04-15T13:47:17.859Z - error: [main] Malformed launch arguments received: C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe,--squirrel-firstrun
2022-04-15T13:47:19.915Z - info: [ui] Subscribed 'Jeeyuen-Rick' to Alive channel
2022-04-15T13:47:19.927Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T13:47:19.929Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T13:47:19.929Z - info: [ui] [AppStore] found account: Jeeyuen-Rick (Rick Yu)
2022-04-15T13:47:21.591Z - info: [ui] launching: 2.9.14 (Windows 10.0.19044)
2022-04-15T13:47:21.593Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-15T13:47:21.721Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.774s)
2022-04-15T13:48:27.759Z - info: [ui] [AppStore] removing account Jeeyuen-Rick (Rick Yu) from store
2022-04-15T13:48:27.762Z - info: [ui] Unubscribed 'Jeeyuen-Rick' from Alive channel
2022-04-15T13:58:27.495Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T13:58:27.498Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T13:58:27.660Z - info: [ui] launching: 2.9.14 (Windows 10.0.19044)
2022-04-15T13:58:27.662Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-15T13:58:29.986Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.345s)
2022-04-15T14:06:35.230Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T14:06:35.236Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T14:06:35.404Z - info: [ui] launching: 2.9.14 (Windows 10.0.19044)
2022-04-15T14:06:35.405Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-15T14:06:37.533Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.133s)
2022-04-15T14:11:00.330Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 3.7s of which 0.0s paused, total 3.7s
2022-04-15T14:12:30.034Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T14:12:30.036Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T14:12:31.660Z - info: [ui] launching: 2.9.14 (Windows 10.0.19044)
2022-04-15T14:12:31.663Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-15T14:12:31.681Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.631s)
2022-04-15T14:12:39.726Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 1.4s of which 0.0s paused, total 1.4s
2022-04-15T14:12:55.773Z - info: [ui] [BranchPruner] Last prune took place 41 minutes ago - skipping
2022-04-15T14:13:32.220Z - info: [ui] [SignInStore] initializing OAuth flow
2022-04-15T14:13:32.221Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=3f9b5c1f-cb5b-440f-9440-fc5acdba409b
2022-04-15T14:13:42.079Z - info: [main] Received possible protocol arguments: 4
2022-04-15T14:13:42.081Z - info: [main] Processing protocol url
2022-04-15T14:13:42.081Z - info: [ui] [Dispatcher] requesting authenticated user
2022-04-15T14:13:42.666Z - info: [ui] [SignInStore] account resolved
2022-04-15T14:13:42.666Z - info: [ui] [AppStore] adding account Jeeyuen-Rick (Rick Yu) to store
2022-04-15T14:13:42.821Z - info: [ui] Subscribed 'Jeeyuen-Rick' to Alive channel
2022-04-15T14:26:43.994Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T14:26:43.997Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T14:26:43.997Z - info: [ui] [AppStore] found account: Jeeyuen-Rick (Rick Yu)
2022-04-15T14:26:45.575Z - info: [ui] launching: 2.9.14 (Windows 10.0.19044)
2022-04-15T14:26:45.578Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-15T14:26:45.595Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.563s)
2022-04-15T14:26:45.597Z - info: [ui] Subscribed 'Jeeyuen-Rick' to Alive channel
2022-04-15T14:27:00.171Z - info: [ui] [AppStore] removing account rickyu (Rick Yu) from store
2022-04-15T14:28:31.226Z - info: [ui] [SignInStore] initializing OAuth flow
2022-04-15T14:28:31.227Z - info: [main] opening in browser: https://github.mathworks.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=a5c22be5-fd9d-4297-be04-216532ab08bb
2022-04-15T14:28:31.804Z - info: [main] Received possible protocol arguments: 4
2022-04-15T14:28:31.809Z - info: [main] Processing protocol url
2022-04-15T14:28:31.809Z - info: [ui] [Dispatcher] requesting authenticated user
2022-04-15T14:28:32.004Z - info: [ui] [SignInStore] account resolved
2022-04-15T14:28:32.005Z - info: [ui] [AppStore] adding account rickyu (Rick Yu) to store
2022-04-15T14:29:14.880Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 2.1s of which 0.0s paused, total 2.1s
2022-04-15T14:37:05.164Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T14:37:05.168Z - info: [ui] [AppStore] found account: Jeeyuen-Rick (Rick Yu)
2022-04-15T14:37:05.168Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T14:37:06.721Z - info: [ui] launching: 2.9.14 (Windows 10.0.19044)
2022-04-15T14:37:06.723Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-15T14:37:06.766Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.572s)
2022-04-15T14:37:06.780Z - info: [ui] Subscribed 'Jeeyuen-Rick' to Alive channel
2022-04-15T14:37:29.690Z - info: [ui] [AppStore] loading 6 repositories from store
2022-04-15T14:37:29.693Z - info: [ui] [AppStore] found account: Jeeyuen-Rick (Rick Yu)
2022-04-15T14:37:29.693Z - info: [ui] [AppStore] found account: rickyu (Rick Yu)
2022-04-15T14:37:31.225Z - info: [ui] Subscribed 'Jeeyuen-Rick' to Alive channel
2022-04-15T14:37:31.278Z - info: [ui] launching: 2.9.14 (Windows 10.0.19044)
2022-04-15T14:37:31.282Z - info: [ui] execPath: 'C:\Users\rickyu\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-15T14:37:31.307Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.602s)
2022-04-15T14:38:04.316Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 2.2s of which 0.0s paused, total 2.2s
2022-04-15T14:44:42.947Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven

2022-04-15T14:47:10.564Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven

2022-04-15T14:50:46.380Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven

2022-04-15T14:52:52.888Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //batfs-sb04-cifs/vmgr/sb04/rickyu/goMaven

**Comment by tidy-dev** [comment]
Issue is being tracked #14336. ([More Info 1](https://github.com/desktop/desktop/issues/14336#issuecomment-1098294609)) ([More Info 2](https://github.com/desktop/desktop/issues/14336#issuecomment-1099881641)) . Currently, a fix for it is on our [Beta channel.](https://desktop.github.com/beta/)
