### ISSUE TITLE
Untrusted network repository directory exception issue

### ISSUE THREAD

**Issue by ergec** [desktop/desktop#14383]
### The problem

"add an exception for this directory" button doesn't work when a "untrusted" network folder is added.

### Release version

2.9.14 x64

### Operating system

Windows 10

### Steps to reproduce the behavior

1. File
2. Add Local Repository
3. Choose
4. Navigate to an existing repository on a network folder
5. Select Folder
6. "add an exception for this directory" doesn't click

### Log files

2022-04-15T06:47:37.832Z - info: [ui] [AppStore] loading 21 repositories from store
2022-04-15T06:47:37.839Z - info: [ui] [AppStore] found account: mylocaluser (mylocaluser)
2022-04-15T06:47:38.428Z - info: [ui] launching: 2.9.13 (Windows 10.0.19043)
2022-04-15T06:47:38.441Z - info: [ui] execPath: 'C:\Users\mylocaluser\AppData\Local\GitHubDesktop\app-2.9.13\GitHubDesktop.exe'
2022-04-15T06:47:38.533Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//10.10.xx.xx/gitrepos/MyProject' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory '//10.10.xx.xx/gitrepos/MyProject'

2022-04-15T06:47:38.535Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//10.10.xx.xx/gitrepos/MyProject' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory '//10.10.xx.xx/gitrepos/MyProject'

2022-04-15T06:47:38.844Z - info: [ui] Subscribed 'mylocaluser' to Alive channel
2022-04-15T06:48:45.117Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.327s)
2022-04-15T06:48:53.516Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 21 repositories took 9.7s of which 0.0s paused, total 9.7s
2022-04-15T06:49:26.601Z - info: [ui] [BranchPruner] Last prune took place 2 minutes ago - skipping
2022-04-15T06:49:26.626Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//10.10.xx.xx/gitrepos/MyProject' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory '//10.10.xx.xx/gitrepos/MyProject'

2022-04-15T06:49:26.627Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//10.10.xx.xx/gitrepos/MyProject' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory '//10.10.xx.xx/gitrepos/MyProject'

2022-04-15T06:49:26.706Z - error: [ui] `git for-each-ref --format=%00%(refname)%00%(objectname)%00%(upstream)%00%(symref)%00%(HEAD)%00 refs/heads refs/remotes` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//10.10.xx.xx/gitrepos/MyProject' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory '//10.10.xx.xx/gitrepos/MyProject'

2022-04-15T06:49:27.377Z - error: [ui] Branch fast-forwarding failed
GitError: fatal: unsafe repository ('//10.10.xx.xx/gitrepos/MyProject' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory '//10.10.xx.xx/gitrepos/MyProject'

    at C:\Users\mylocaluser\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\git\core.ts:253:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at C:\Users\mylocaluser\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\trampoline\trampoline-environment.ts:40:13
    at C:\Users\mylocaluser\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\trampoline\trampoline-tokens.ts:33:5
    at C:\Users\mylocaluser\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\git\for-each-ref.ts:90:9
    at Wr.fastForwardBranches (C:\Users\mylocaluser\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\app-store.ts:4264:13)
    at C:\Users\mylocaluser\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\app-store.ts:4589:18
    at Wr.withPushPullFetch (C:\Users\mylocaluser\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\app-store.ts:4119:5)
    at Wr.performFetch (C:\Users\mylocaluser\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\app-store.ts:4553:5)
    at Ko.performAndScheduleFetch (C:\Users\mylocaluser\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2022-04-15T06:49:33.604Z - info: [ui] [AppStore] loading 21 repositories from store
2022-04-15T06:49:33.607Z - info: [ui] [AppStore] found account: mylocaluser (mylocaluser)
2022-04-15T06:49:33.952Z - info: [ui] launching: 2.9.14 (Windows 10.0.19043)
2022-04-15T06:49:33.970Z - info: [ui] execPath: 'C:\Users\mylocaluser\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-15T06:49:34.474Z - info: [ui] Subscribed 'mylocaluser' to Alive channel
2022-04-15T06:50:29.291Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 20 repositories took 6.7s of which 0.0s paused, total 6.7s
2022-04-15T06:50:33.579Z - error: [ui] `git remote -v` exited with an unexpected code: 128.

### Screenshots

![image](https://user-images.githubusercontent.com/422056/163537152-f4de608f-5964-4802-a36a-c0153da630c4.png)

**Comment by ergec** [comment]
Duplicate of https://github.com/desktop/desktop/issues/14336
