### ISSUE TITLE
xxx is potentially unsafe

### ISSUE THREAD

**Issue by sparc** [desktop/desktop#14407]
### The problem

repos on network shares are now blocked with the message "xxx is potentially unsafe", a "trust repository" button is offered but clicking on it does nothing

### Release version

2.9.14

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Try to open a repo on a network drive

### Log files

2022-04-19T00:31:58.341Z - info: [ui] Executing getConfigValueInPath: git config -z protocol.version (took 1.459s)
2022-04-19T00:31:59.405Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.055s)
2022-04-19T01:04:31.364Z - info: [ui] Executing getConfigValueInPath: git config -z protocol.version (took 1.487s)
2022-04-19T01:04:32.532Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.161s)
2022-04-19T01:23:22.870Z - info: [ui] [BranchPruner] Last prune took place 8 hours ago - skipping
2022-04-19T01:37:05.353Z - info: [ui] Executing getConfigValueInPath: git config -z protocol.version (took 1.470s)
2022-04-19T01:37:06.421Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.061s)
2022-04-19T02:09:38.341Z - info: [ui] Executing getConfigValueInPath: git config -z protocol.version (took 1.462s)
2022-04-19T02:09:39.507Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.159s)
2022-04-19T02:42:11.328Z - info: [ui] Executing getConfigValueInPath: git config -z protocol.version (took 1.453s)
2022-04-19T02:42:12.375Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.040s)
2022-04-19T03:14:44.380Z - info: [ui] Executing getConfigValueInPath: git config -z protocol.version (took 1.490s)
2022-04-19T03:14:45.522Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.135s)
2022-04-19T03:47:17.348Z - info: [ui] Executing getConfigValueInPath: git config -z protocol.version (took 1.467s)
2022-04-19T03:47:18.388Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.034s)
2022-04-19T04:19:51.382Z - info: [ui] Executing getConfigValueInPath: git config -z protocol.version (took 2.493s)
2022-04-19T04:19:52.449Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.060s)
2022-04-19T04:52:24.442Z - info: [ui] Executing getConfigValueInPath: git config -z protocol.version (took 1.557s)
2022-04-19T04:52:25.481Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.032s)
2022-04-19T05:23:22.872Z - info: [ui] [BranchPruner] Last prune took place 12 hours ago - skipping
2022-04-19T05:24:57.363Z - info: [ui] Executing getConfigValueInPath: git config -z protocol.version (took 1.473s)
2022-04-19T05:24:58.432Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.062s)
2022-04-19T05:57:30.374Z - info: [ui] Executing getConfigValueInPath: git config -z protocol.version (took 1.492s)
2022-04-19T05:57:31.473Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.092s)
2022-04-19T06:30:03.457Z - info: [ui] Executing getConfigValueInPath: git config -z protocol.version (took 1.574s)
2022-04-19T06:30:04.547Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.083s)
2022-04-19T06:42:02.223Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.570s)
2022-04-19T06:42:06.734Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 23 repositories took 6.1s of which 0.0s paused, total 6.1s
2022-04-19T06:42:11.735Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//DEBIAN2/webs/webs/col.vortexfdc.com' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/col.vortexfdc.com

2022-04-19T06:42:11.765Z - error: [ui] `git for-each-ref --format=%00%(refname)%00%(objectname)%00%(upstream)%00%(symref)%00%(HEAD)%00 refs/heads refs/remotes` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//DEBIAN2/webs/webs/col.vortexfdc.com' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/col.vortexfdc.com

2022-04-19T06:42:12.378Z - error: [ui] Branch fast-forwarding failed
GitError: fatal: unsafe repository ('//DEBIAN2/webs/webs/col.vortexfdc.com' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/col.vortexfdc.com

    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\git\core.ts:253:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\trampoline\trampoline-environment.ts:40:13
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\trampoline\trampoline-tokens.ts:33:5
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\git\for-each-ref.ts:90:9
    at Wr.fastForwardBranches (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\app-store.ts:4264:13)
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\app-store.ts:4589:18
    at Wr.withPushPullFetch (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\app-store.ts:4119:5)
    at Wr.performFetch (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\app-store.ts:4553:5)
2022-04-19T06:42:12.403Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//DEBIAN2/webs/webs/col.vortexfdc.com' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/col.vortexfdc.com

2022-04-19T06:42:38.232Z - info: [ui] [BranchPruner] Last prune took place 27 seconds ago - skipping
2022-04-19T06:42:38.277Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//DEBIAN2/webs/webs/col.vortexfdc.com' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/col.vortexfdc.com

2022-04-19T06:42:38.279Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//DEBIAN2/webs/webs/col.vortexfdc.com' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/col.vortexfdc.com

2022-04-19T06:42:38.339Z - error: [ui] `git for-each-ref --format=%00%(refname)%00%(objectname)%00%(upstream)%00%(symref)%00%(HEAD)%00 refs/heads refs/remotes` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//DEBIAN2/webs/webs/col.vortexfdc.com' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/col.vortexfdc.com

2022-04-19T06:42:38.340Z - error: [ui] Branch fast-forwarding failed
GitError: fatal: unsafe repository ('//DEBIAN2/webs/webs/col.vortexfdc.com' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/col.vortexfdc.com

    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\git\core.ts:253:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\trampoline\trampoline-environment.ts:40:13
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\trampoline\trampoline-tokens.ts:33:5
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\git\for-each-ref.ts:90:9
    at Wr.fastForwardBranches (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\app-store.ts:4264:13)
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\app-store.ts:4589:18
    at Wr.withPushPullFetch (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\app-store.ts:4119:5)
    at Wr.performFetch (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\app-store.ts:4553:5)
    at Ko.performAndScheduleFetch (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.13\webpack:\[name]\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2022-04-19T06:43:02.484Z - info: [ui] [AppStore] loading 24 repositories from store
2022-04-19T06:43:02.488Z - info: [ui] [AppStore] found account: sparc (David Saez Padros)
2022-04-19T06:43:04.383Z - info: [ui] launching: 2.9.14 (Windows 10.0.19043)
2022-04-19T06:43:04.387Z - info: [ui] execPath: 'C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-19T06:43:04.387Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.751s)
2022-04-19T06:43:04.562Z - info: [ui] Subscribed 'sparc' to Alive channel
2022-04-19T06:43:40.199Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//DEBIAN2/webs/webs/delhortacasa.ols.es' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/delhortacasa.ols.es

2022-04-19T06:43:40.210Z - error: [ui] `git for-each-ref --format=%00%(refname)%00%(objectname)%00%(upstream)%00%(symref)%00%(HEAD)%00 refs/heads refs/remotes` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//DEBIAN2/webs/webs/delhortacasa.ols.es' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/delhortacasa.ols.es

2022-04-19T06:43:40.848Z - error: [ui] Branch fast-forwarding failed
GitError: fatal: unsafe repository ('//DEBIAN2/webs/webs/delhortacasa.ols.es' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/delhortacasa.ols.es

    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\git\core.ts:253:11
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\trampoline\trampoline-environment.ts:40:13
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\trampoline\trampoline-tokens.ts:33:5
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\git\for-each-ref.ts:90:9
    at $r.fastForwardBranches (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4264:13)
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4589:18
    at $r.withPushPullFetch (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4119:5)
    at $r.performFetch (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4553:5)
    at Zo.performAndScheduleFetch (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2022-04-19T06:43:40.863Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//DEBIAN2/webs/webs/delhortacasa.ols.es' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/delhortacasa.ols.es

2022-04-19T06:44:02.876Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 23 repositories took 7.0s of which 0.0s paused, total 7.0s
2022-04-19T06:56:22.631Z - info: [ui] [AppStore] loading 24 repositories from store
2022-04-19T06:56:22.634Z - info: [ui] [AppStore] found account: sparc (David Saez Padros)
2022-04-19T06:56:24.297Z - info: [ui] launching: 2.9.14 (Windows 10.0.19043)
2022-04-19T06:56:24.300Z - info: [ui] execPath: 'C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-19T06:56:24.300Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.610s)
2022-04-19T06:56:24.326Z - info: [ui] Subscribed 'sparc' to Alive channel
2022-04-19T06:56:44.872Z - error: [ui] `git for-each-ref --format=%00%(refname)%00%(objectname)%00%(upstream)%00%(symref)%00%(HEAD)%00 refs/heads refs/remotes` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//DEBIAN2/webs/webs/myhome.ols.es' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/myhome.ols.es

2022-04-19T06:56:45.431Z - error: [ui] Branch fast-forwarding failed
GitError: fatal: unsafe repository ('//DEBIAN2/webs/webs/myhome.ols.es' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/myhome.ols.es

    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\git\core.ts:253:11
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\trampoline\trampoline-environment.ts:40:13
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\trampoline\trampoline-tokens.ts:33:5
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\git\for-each-ref.ts:90:9
    at $r.fastForwardBranches (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4264:13)
    at C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4589:18
    at $r.withPushPullFetch (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4119:5)
    at $r.performFetch (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\app-store.ts:4553:5)
    at Zo.performAndScheduleFetch (C:\Users\Flytech\AppData\Local\GitHubDesktop\app-2.9.14\webpack:\[name]\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2022-04-19T06:56:45.435Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//DEBIAN2/webs/webs/myhome.ols.es' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/myhome.ols.es

2022-04-19T06:56:45.436Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//DEBIAN2/webs/webs/myhome.ols.es' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //DEBIAN2/webs/webs/myhome.ols.es

2022-04-19T06:58:12.552Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 24 repositories took 5.1s of which 60.5s paused, total 65.5s

**Comment by niik** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The [latest update](https://github.com/desktop/desktop/issues/14336#issuecomment-1099881641) as of writing this is that we've shipped an update to our [beta channel](https://desktop.github.com/beta/) which solves the issue of WSL and NAS (or path beginning with `//`) not working. We're planning on shipping an updated version to our production channel this week.
