### ISSUE TITLE
Github Desktop won't re-open

### ISSUE THREAD

**Issue by 275RR** [desktop/desktop#14732]
### The problem

Just installed Desktop on several of my Windows 10 machines today. It seems Desktop is not closing properly. 

On my newer, faster machine, I am able to open and close and re-open Desktop multiple times; however, it does spawn an additional background process each time that never goes away(at least after watching and checking for an hour). For example, after 5 open and closes, I'll have 5 background processes.

More importantly, on the slower machine, I might be able to open and close once or twice before the program will not open. When it enters this state, several different results can happen. Sometimes the program will show a white screen but never fully opens, sometimes nothing will show, sometimes nothing will show and a background process will run away with high CPU and Memory.

In all cases, ending all Github background processes does allow the program to re-open and function normally on the first attempt.

**The log file is from the slowest machine with the worst issue.**

### Release version

Version 3.0.1 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open Github Desktop
2. Close Github Desktop
3. Repeat

### Log files

2022-06-04T01:02:51.091Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-04T01:02:56.774Z - info: [ui] [AppStore] loading 1 repositories from store
2022-06-04T01:02:56.781Z - info: [ui] [AppStore] found account: davidhofer (davidhofer)
2022-06-04T01:02:56.865Z - info: [ui] [BranchPruner] Last prune took place 3 hours ago - skipping
2022-06-04T01:03:01.788Z - info: [ui] Subscribed 'davidhofer' to Alive channel
2022-06-04T01:03:01.794Z - info: [ui] Executing getRemotes: git remote -v (took 4.862s)
2022-06-04T01:03:02.260Z - info: [ui] launching: 3.0.1 (Windows 10.0.19044)
2022-06-04T01:03:02.264Z - info: [ui] execPath: 'C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe'
2022-06-04T01:03:04.782Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 1.005s)
2022-06-04T01:03:05.043Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.798s)
2022-06-04T01:03:05.809Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.924s)
2022-06-04T01:31:14.686Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 4.311s)
2022-06-04T01:32:41.678Z - info: [ui] [BranchPruner] Last prune took place 3 hours ago - skipping
2022-06-04T01:33:01.455Z - error: [ui] Highlighter worked failed for old contents
Error: timed out
    at C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\highlighter\worker.ts:85:14
2022-06-04T01:33:23.402Z - info: [main] opening in browser: https://github.com/275RR/BB-Editor-V3
2022-06-04T01:34:13.514Z - error: [ui] Highlighter worked failed for new contents
Error: timed out
    at C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\highlighter\worker.ts:85:14
2022-06-04T01:34:48.843Z - info: [ui] [Timing] Action 'create commit' for '275RR/BB-Editor-V3' took 1.462s
2022-06-04T01:35:11.279Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BB-Editor-V3 - davidhofer (has token)
2022-06-04T01:35:12.674Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 1.246s)
2022-06-04T01:35:35.004Z - info: [main] opening in browser: https://github.com/275RR/BB-Editor-V3
2022-06-04T01:36:55.418Z - info: [ui] [BranchPruner] Last prune took place 3 hours ago - skipping
2022-06-04T01:42:56.635Z - info: [main] opening in browser: https://git-scm.com/docs/gitignore
2022-06-04T01:43:44.188Z - info: [ui] [Timing] Action 'create commit' for '275RR/BB-Editor-V3' took 1.966s
2022-06-04T01:45:28.089Z - warn: [ui] Failed trying to find Git on PATH
Error: Command failed: C:\WINDOWS\System32\where.exe git
INFO: Could not find files for the given pattern(s).

    at ChildProcess.exithandler (node:child_process:406:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
2022-06-04T01:46:24.529Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BB-Editor-V3 - davidhofer (has token)
2022-06-04T01:46:25.906Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 1.218s)
2022-06-04T02:23:14.994Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 4.337s)
2022-06-04T02:25:23.276Z - info: [ui] Executing createCommit: git commit -F - (took 1.185s)
2022-06-04T02:25:24.247Z - info: [ui] [Timing] Action 'create commit' for '275RR/BB-Editor-V3' took 2.984s
2022-06-04T02:25:36.005Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BB-Editor-V3 - davidhofer (has token)
2022-06-04T02:25:41.336Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 5.174s)
2022-06-04T02:26:29.801Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BB-Editor-V3 - davidhofer (has token)
2022-06-04T02:28:55.605Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-04T02:29:01.643Z - info: [ui] Subscribed 'davidhofer' to Alive channel
2022-06-04T02:29:05.239Z - error: [ui] PullRequestCoordinator: Error loading repositories
OpenFailedError: UnknownError Internal error opening backing store for indexedDB.open.
    at F.create (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1013903)
    at file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1005522
    at file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:990571
    at kd (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:985803)
    at _d (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986562)
    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986931)
2022-06-04T02:29:32.409Z - info: [main] Received possible protocol arguments: 2
2022-06-04T02:29:32.440Z - error: [main] Malformed launch arguments received: C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe,--allow-file-access-from-files
2022-06-04T02:31:13.914Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-04T02:31:19.934Z - info: [ui] Subscribed 'davidhofer' to Alive channel
2022-06-04T02:31:23.520Z - error: [ui] PullRequestCoordinator: Error loading repositories
OpenFailedError: UnknownError Internal error opening backing store for indexedDB.open.
    at F.create (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1013903)
    at file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1005522
    at file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:990571
    at kd (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:985803)
    at _d (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986562)
    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986931)
2022-06-04T02:34:28.928Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-04T02:34:34.277Z - info: [ui] [AppStore] loading 1 repositories from store
2022-06-04T02:34:34.279Z - info: [ui] [AppStore] found account: davidhofer (davidhofer)
2022-06-04T02:34:34.347Z - info: [ui] [BranchPruner] Last prune took place 4 hours ago - skipping
2022-06-04T02:34:39.130Z - info: [ui] Subscribed 'davidhofer' to Alive channel
2022-06-04T02:34:39.156Z - info: [ui] Executing getRemotes: git remote -v (took 4.765s)
2022-06-04T02:34:39.251Z - info: [ui] launching: 3.0.1 (Windows 10.0.19044)
2022-06-04T02:34:39.265Z - info: [ui] execPath: 'C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe'
2022-06-04T02:34:41.291Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.094s)
2022-06-04T02:35:49.461Z - info: [ui] [Timing] Action 'create commit' for '275RR/BB-Editor-V3' took 1.482s
2022-06-04T02:35:51.158Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BB-Editor-V3 - davidhofer (has token)
2022-06-04T02:35:52.709Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 1.323s)
2022-06-04T02:39:00.470Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-04T02:39:06.273Z - info: [ui] Subscribed 'davidhofer' to Alive channel
2022-06-04T02:39:09.865Z - error: [ui] PullRequestCoordinator: Error loading repositories
OpenFailedError: UnknownError Internal error opening backing store for indexedDB.open.
    at F.create (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1013903)
    at file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1005522
    at file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:990571
    at kd (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:985803)
    at _d (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986562)
    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986931)
2022-06-04T02:49:01.626Z - info: [main] Received possible protocol arguments: 2
2022-06-04T02:49:01.640Z - error: [main] Malformed launch arguments received: C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe,--allow-file-access-from-files
2022-06-04T02:50:00.896Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-04T02:50:06.229Z - info: [ui] [AppStore] loading 1 repositories from store
2022-06-04T02:50:06.231Z - info: [ui] [AppStore] found account: davidhofer (davidhofer)
2022-06-04T02:50:06.298Z - info: [ui] [BranchPruner] Last prune took place 5 hours ago - skipping
2022-06-04T02:50:11.062Z - info: [ui] Subscribed 'davidhofer' to Alive channel
2022-06-04T02:50:11.087Z - info: [ui] Executing getRemotes: git remote -v (took 4.748s)
2022-06-04T02:50:11.191Z - info: [ui] launching: 3.0.1 (Windows 10.0.19044)
2022-06-04T02:50:11.196Z - info: [ui] execPath: 'C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe'
2022-06-04T02:50:13.642Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.451s)
2022-06-04T02:51:18.526Z - warn: [ui] Failed trying to find Git on PATH
Error: Command failed: C:\WINDOWS\System32\where.exe git
INFO: Could not find files for the given pattern(s).

    at ChildProcess.exithandler (node:child_process:406:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
2022-06-04T02:52:31.274Z - info: [ui] Unubscribed 'davidhofer' from Alive channel
2022-06-04T02:55:56.020Z - info: [ui] [Timing] Action 'create commit' for '275RR/BB-Editor-V3' took 1.785s
2022-06-04T02:55:58.005Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BB-Editor-V3 - davidhofer (has token)
2022-06-04T02:55:59.389Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 1.241s)
2022-06-04T03:01:18.860Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-04T03:01:24.133Z - info: [ui] [AppStore] loading 1 repositories from store
2022-06-04T03:01:24.135Z - info: [ui] [AppStore] found account: davidhofer (davidhofer)
2022-06-04T03:01:24.206Z - info: [ui] [BranchPruner] Last prune took place 5 hours ago - skipping
2022-06-04T03:01:28.970Z - info: [ui] Executing getRemotes: git remote -v (took 4.720s)
2022-06-04T03:01:29.380Z - info: [ui] launching: 3.0.1 (Windows 10.0.19044)
2022-06-04T03:01:29.383Z - info: [ui] execPath: 'C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe'
2022-06-04T03:01:31.657Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.295s)
2022-06-04T03:01:42.937Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BB-Editor-V3 - davidhofer (has token)
2022-06-04T03:19:45.691Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-04T03:19:55.998Z - info: [ui] [AppStore] loading 1 repositories from store
2022-06-04T03:19:56.000Z - info: [ui] [AppStore] found account: davidhofer (davidhofer)
2022-06-04T03:19:56.089Z - info: [ui] [BranchPruner] Last prune took place 5 hours ago - skipping
2022-06-04T03:20:00.304Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 4.184s)
2022-06-04T03:20:01.822Z - info: [ui] launching: 3.0.1 (Windows 10.0.19044)
2022-06-04T03:20:01.841Z - info: [ui] execPath: 'C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe'
2022-06-04T03:20:04.439Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 3.271s)
2022-06-04T03:20:48.993Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-04T03:20:58.362Z - error: [ui] PullRequestCoordinator: Error loading repositories
OpenFailedError: UnknownError Internal error opening backing store for indexedDB.open.
    at F.create (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1013903)
    at file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1005522
    at file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:990571
    at kd (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:985803)
    at _d (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986562)
    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986931)
2022-06-04T03:58:05.644Z - info: [main] Received possible protocol arguments: 2
2022-06-04T03:58:05.657Z - error: [main] Malformed launch arguments received: C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe,--allow-file-access-from-files
2022-06-04T03:59:11.695Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-04T03:59:21.040Z - error: [ui] PullRequestCoordinator: Error loading repositories
OpenFailedError: UnknownError Internal error opening backing store for indexedDB.open.
    at F.create (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1013903)
    at file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1005522
    at file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:990571
    at kd (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:985803)
    at _d (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986562)
    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Austria/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986931)
2022-06-04T03:59:42.286Z - info: [main] Received possible protocol arguments: 2
2022-06-04T03:59:42.313Z - error: [main] Malformed launch arguments received: C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe,--allow-file-access-from-files
2022-06-04T04:00:24.246Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-04T04:00:29.563Z - info: [ui] [AppStore] loading 1 repositories from store
2022-06-04T04:00:29.565Z - info: [ui] [AppStore] found account: davidhofer (davidhofer)
2022-06-04T04:00:29.634Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2022-06-04T04:00:34.432Z - info: [ui] Executing getRemotes: git remote -v (took 4.757s)
2022-06-04T04:00:34.570Z - info: [ui] launching: 3.0.1 (Windows 10.0.19044)
2022-06-04T04:00:34.590Z - info: [ui] execPath: 'C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe'
2022-06-04T04:00:36.986Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.502s)
2022-06-04T04:01:30.627Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-04T04:01:35.943Z - info: [ui] [AppStore] loading 1 repositories from store
2022-06-04T04:01:35.945Z - info: [ui] [AppStore] found account: davidhofer (davidhofer)
2022-06-04T04:01:36.017Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2022-06-04T04:01:40.690Z - info: [ui] Executing getRemotes: git remote -v (took 4.631s)
2022-06-04T04:01:40.810Z - info: [ui] launching: 3.0.1 (Windows 10.0.19044)
2022-06-04T04:01:40.825Z - info: [ui] execPath: 'C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe'
2022-06-04T04:01:42.779Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.011s)
2022-06-04T04:06:08.601Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-04T04:06:13.922Z - info: [ui] [AppStore] loading 1 repositories from store
2022-06-04T04:06:13.924Z - info: [ui] [AppStore] found account: davidhofer (davidhofer)
2022-06-04T04:06:13.996Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2022-06-04T04:06:18.759Z - info: [ui] Executing getRemotes: git remote -v (took 4.721s)
2022-06-04T04:06:18.923Z - info: [ui] launching: 3.0.1 (Windows 10.0.19044)
2022-06-04T04:06:18.941Z - info: [ui] execPath: 'C:\Users\Austria\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe'
2022-06-04T04:06:19.904Z - info: [ui] Executing getCommits: git log 89fd6414d64fb69d9408c02eccef94e347ab5e8c --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.019s)
2022-06-04T04:06:22.052Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 3.213s)

**Comment by sergiou87** [comment]
I think this is closed by https://github.com/desktop/desktop/pull/14733

You can download the latest beta from https://desktop.github.com/beta if you need the fix for this ASAP, otherwise it will be available in the upcoming production release.

Thank you for your report and patience! 🙇‍♂️
