### ISSUE TITLE
UI completly white after update 

### ISSUE THREAD

**Issue by Theoyeah** [desktop/desktop#14730]
### The problem

After downloading the fresh new version of Github Desktop, i opened the app and noticed that everything is white.
I tried everything ecept re-installing

### Release version

3.0.1

### Operating system

Windows 11 build 22000.613

### Log files
2022-06-03T16:01:06.724Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-03T16:01:09.128Z - info: [ui] Subscribed 'Theoyeah' to Alive channel
2022-06-03T16:01:12.496Z - error: [ui] PullRequestCoordinator: Error loading repositories
OpenFailedError: UnknownError Internal error opening backing store for indexedDB.open.
    at F.create (file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1013903)
    at file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1005522
    at file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:990571
    at kd (file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:985803)
    at _d (file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986562)
    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986931)
2022-06-03T16:01:21.299Z - info: [main] Received possible protocol arguments: 2
2022-06-03T16:01:21.304Z - error: [main] Malformed launch arguments received: C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe,--allow-file-access-from-files
2022-06-03T16:15:43.226Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-03T16:15:45.622Z - info: [ui] Subscribed 'Theoyeah' to Alive channel
2022-06-03T16:15:49.875Z - error: [ui] PullRequestCoordinator: Error loading repositories
OpenFailedError: UnknownError Internal error opening backing store for indexedDB.open.
    at F.create (file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1013903)
    at file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1005522
    at file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:990571
    at kd (file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:985803)
    at _d (file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986562)
    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986931)
2022-06-03T16:16:20.806Z - info: [main] Received possible protocol arguments: 2
2022-06-03T16:16:20.826Z - error: [main] Malformed launch arguments received: C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe,--allow-file-access-from-files
2022-06-03T16:17:26.802Z - info: [main] Received possible protocol arguments: 2
2022-06-03T16:17:26.838Z - error: [main] Malformed launch arguments received: C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.0\GitHubDesktop.exe,--allow-file-access-from-files
2022-06-03T16:17:44.791Z - info: [main] Received possible protocol arguments: 2
2022-06-03T16:17:48.181Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-03T16:17:51.134Z - info: [ui] Subscribed 'Theoyeah' to Alive channel
2022-06-03T16:17:53.896Z - error: [ui] PullRequestCoordinator: Error loading repositories
OpenFailedError: UnknownError Internal error opening backing store for indexedDB.open.
    at F.create (file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1013903)
    at file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:1005522
    at file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:990571
    at kd (file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:985803)
    at _d (file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986562)
    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/theodelalot/AppData/Local/GitHubDesktop/app-3.0.1/resources/app/renderer.js:2:986931)
2022-06-03T16:17:59.411Z - info: [main] Received possible protocol arguments: 2
2022-06-03T16:17:59.417Z - error: [main] Malformed launch arguments received: C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe,--allow-file-access-from-files
2022-06-03T16:21:12.570Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-03T16:21:15.335Z - info: [ui] [AppStore] loading 5 repositories from store
2022-06-03T16:21:15.352Z - info: [ui] [AppStore] found account: Theoyeah (Theoyeah)
2022-06-03T16:21:16.068Z - info: [ui] launching: 3.0.1 (Windows 10.0.22000)
2022-06-03T16:21:16.073Z - info: [ui] execPath: 'C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe'
2022-06-03T16:21:16.657Z - info: [ui] Subscribed 'Theoyeah' to Alive channel
2022-06-03T16:21:16.739Z - info: [ui] Stats reported.
2022-06-03T16:21:17.318Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.273s)
2022-06-03T16:21:44.139Z - info: [ui] Executing getRepositoryType: git rev-parse --is-bare-repository --show-cdup (took 1.215s)
2022-06-03T16:21:47.722Z - info: [ui] Executing getRemotes: git remote -v (took 1.648s)
2022-06-03T16:21:47.818Z - info: [ui] Executing getRemotes: git remote -v (took 1.708s)
2022-06-03T16:21:47.981Z - info: [ui] Executing getBranchesDifferingFromUpstream: git for-each-ref --format=%00%(refname)%00%(objectname)%00%(upstream)%00%(symref)%00%(HEAD)%00 refs/heads refs/remotes (took 1.215s)
2022-06-03T16:21:50.219Z - info: [ui] Executing getCommits: git log 2aa676180cb91a07354a8e349a73b506ac5ef312 --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.410s)
2022-06-03T16:21:50.459Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 1.268s)
2022-06-03T16:21:51.695Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 1.754s)
2022-06-03T16:21:52.205Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 1.985s)
2022-06-03T16:21:52.761Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.691s)
2022-06-03T16:21:53.360Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 2.711s)
2022-06-03T16:21:54.019Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.911s)
2022-06-03T16:21:55.340Z - info: [ui] Executing getConfigValueInPath: git config -z pull.rebase (took 2.575s)
2022-06-03T16:21:56.132Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 3.805s)
2022-06-03T16:21:56.227Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 3.784s)
2022-06-03T16:21:57.326Z - info: [ui] Executing getConfigValueInPath: git config -z pull.rebase (took 3.302s)
2022-06-03T16:21:58.382Z - info: [ui] Executing getRemotes: git remote -v (took 2.688s)
2022-06-03T16:21:58.382Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 2.382s)
2022-06-03T16:21:58.846Z - info: [ui] Executing getStashEntries: git log -g -z --pretty=%gD%x1F%H%x1F%gs refs/stash (took 3.042s)
2022-06-03T16:21:58.848Z - info: [ui] Executing getCommits: git log origin/main..main --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 3.506s)
2022-06-03T16:21:59.026Z - info: [ui] Executing getConfigValueInPath: git config -z pull.rebase (took 2.797s)
2022-06-03T16:21:59.973Z - info: [ui] Executing getCommits: git log origin/main..main --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 2.644s)
2022-06-03T16:22:00.153Z - info: [ui] Executing getRemotes: git remote -v (took 2.733s)
2022-06-03T16:22:00.157Z - info: [ui] Executing getStashEntries: git log -g -z --pretty=%gD%x1F%H%x1F%gs refs/stash (took 2.676s)
2022-06-03T16:22:00.163Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 2.260s)
2022-06-03T16:22:00.464Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 1.615s)
2022-06-03T16:22:00.752Z - info: [ui] Executing getCommits: git log origin/main..main --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.724s)
2022-06-03T16:22:00.835Z - info: [ui] Executing getRemotes: git remote -v (took 1.504s)
2022-06-03T16:22:00.839Z - info: [ui] Executing getStashEntries: git log -g -z --pretty=%gD%x1F%H%x1F%gs refs/stash (took 1.228s)
2022-06-03T16:22:00.894Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.112s)
2022-06-03T16:22:01.678Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 1.212s)
2022-06-03T16:22:02.013Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 1.261s)
2022-06-03T16:22:07.332Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --skip=0 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 5.652s)
2022-06-03T16:22:08.240Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 6.226s)
2022-06-03T16:22:13.514Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 5.874s)
2022-06-03T16:22:42.038Z - info: [ui] Executing getChangedFilesNameStatus: git log 2aa676180cb91a07354a8e349a73b506ac5ef312 -C -M -m -1 --no-show-signature --first-parent --format=format: -z --name-status -- (took 28.669s)
2022-06-03T16:22:43.796Z - info: [ui] Executing getChangedFilesNumStats: git log 2aa676180cb91a07354a8e349a73b506ac5ef312 -C -M -m -1 --no-show-signature --first-parent --format=format: -z --numstat -- (took 1.708s)
2022-06-03T16:27:37.461Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.532s)
2022-06-03T17:00:37.311Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 21.377s)
2022-06-03T17:00:37.345Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/Theoyeah/Theoyeah-Engine.git/': Failed to connect to github.com port 443 after 21089 ms: Timed out

2022-06-03T17:00:59.803Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
TypeError: Failed to fetch
    at _t (C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\http.ts:152:10)
    at yn.request (C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\api.ts:1401:28)
    at yn.fetchPushControl (C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\api.ts:1319:35)
    at dr.refreshBranchProtectionState (C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\stores\app-store.ts:1056:37)
    at C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\stores\app-store.ts:4579:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at dr.withPushPullFetch (C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\stores\app-store.ts:4096:5)
    at dr.performFetch (C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\stores\app-store.ts:4530:5)
    at To.performAndScheduleFetch (C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2022-06-03T17:01:21.915Z - warn: [ui] getFetchPollInterval: failed for Theoyeah/Theoyeah-Engine
TypeError: Failed to fetch
    at _t (C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\http.ts:152:10)
    at yn.request (C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\api.ts:1401:28)
    at yn.getFetchPollInterval (C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\api.ts:1439:35)
    at To.getFetchInterval (C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\stores\helpers\background-fetcher.ts:136:38)
    at To.performAndScheduleFetch (C:\Users\theodelalot\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\stores\helpers\background-fetcher.ts:117:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-06-03T17:12:10.374Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2022-06-03T17:12:33.136Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2022-06-03T17:12:57.132Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2022-06-03T17:13:23.200Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2022-06-03T17:13:53.122Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2022-06-03T17:14:31.186Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2022-06-03T17:15:27.134Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch

### Screenshots

![image](https://user-images.githubusercontent.com/97792861/171903699-df64d154-7a0f-4b94-a6bf-29031b1b74b6.png)

**Comment by tsvetilian-ty** [comment]
@Theoyeah 👋  Could you upload the log file from GitHub Desktop? You can find them in `%APPDATA%\GitHub Desktop\logs`

**Comment by jmssmth** [comment]
Seeing the same on my end as well. Same release, but on Windows Server 2019. Attached most recent log file
[2022-06-04.desktop.production.log](https://github.com/desktop/desktop/files/8837136/2022-06-04.desktop.production.log)
.

**Comment by Theoyeah** [comment]
> @Theoyeah 👋 Could you upload the log file from GitHub Desktop? You can find them in `%APPDATA%\GitHub Desktop\logs`

Ok, sure

**Comment by Theoyeah** [comment]
just updated the thing, but i restarted my computer and it worked fine

**Comment by steveward** [comment]
Closing this, let us know if you have further issues @Theoyeah.

**Comment by Theoyeah** [comment]
The only thing that i found out is that at one moment, the app got frozen (without a "Not responding"), i closed it, and opened it again and it the bug restarted
