### ISSUE TITLE
GitHub Desktop shows an empty page

### ISSUE THREAD

**Issue by JaylyDev** [desktop/desktop#14775]
### The problem

when I open the app, the window doesnt open and you need to start the app for the second time for the app to show a white screen.

### Release version

3.0.1

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Window shows with nothing display / white screen

### Log files

When github desktop window does not show for the first time you open:
```
2022-06-09T18:26:21.828Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-09T18:26:22.405Z - info: [main] Received possible protocol arguments: 2
2022-06-09T18:26:22.414Z - error: [main] Malformed launch arguments received: C:\Users\user\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe,--squirrel-firstrun
2022-06-09T18:26:22.414Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-09T18:26:23.142Z - error: [ui] PullRequestCoordinator: Error loading repositories
Error: Missing owner '1'
    at ot (C:\Users\user\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\fatal-error.ts:3:9)
    at lt (C:\Users\user\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\fatal-error.ts:48:12)
    at QN.constructor.toGitHubRepository (C:\Users\user\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\lib\stores\repositories-store.ts:118:7)
```

When i click on the desktop app 2nd time and window with a white screen opens:
```
2022-06-09T18:27:18.160Z - info: [main] Received possible protocol arguments: 2
2022-06-09T18:27:18.162Z - error: [main] Malformed launch arguments received: C:\Users\user\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe,--allow-file-access-from-files
```

Here's the log file
[2022-06-09.desktop.production.log](https://github.com/desktop/desktop/files/8872969/2022-06-09.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/65847850/172919003-b3f1c3f8-adc9-48f8-a3d3-19130f8a3b75.png)

**Comment by steveward** [comment]
Thanks for the issue @JaylyDev. Can you try resetting GitHub Desktop by following these steps?

1. Close GitHub Desktop (you may need to use the Task Manger if you are unable to close the application directly)
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

Let me know if that doesn't get things working.

**Comment by JaylyDev** [comment]
Hi, thank you for your advice. The app now works properly.

**Comment by Cdddo** [comment]
Had the same issue. Restarted windows and it opened properly...

**Comment by steveward** [comment]
Glad to hear things are working now!
