### ISSUE TITLE
GitHub Desktop exits when viewing repo with revoked PAT

### ISSUE THREAD

**Issue by martincostello** [desktop/desktop#14780]
### The problem

I was having an issue with commits being rejected due to a workflow file being added to a repository hosted in GitHub Enterprise Server due to the Personal Access Token associated with GitHub Desktop not having the `workflow` scope.

I tried logging out and regenerating it, but that didn't seem to work either, so I "nuked" the PAT I had already configured for the GitHub CLI and generated a new one. I also logged out and in to GitHub Desktop again.

Now when I view any repository whose remote is in GHES, GitHub Desktop closes. Viewing repositories whose remote is GitHub.com works normally.

GitHub Desktop also exits if I try to open the options menu to log out of the GHES instance.

### Release version

3.0.1

### Operating system

Windows 11

### Steps to reproduce the behavior

I'm not sure _exactly_ what the minimal repro for this is, but something like:

1. Log into a GitHub instance in GitHub Desktop
2. Clone a repo from that remote
3. Close GitHub Desktop
4. Revoke the PAT associated with the GitHub instance
5. Re-launch GitHub Desktop to view that repo _or_ view the Options menu.

### Log files

```
2022-06-10T08:45:46.469Z - info: [main] Received possible protocol arguments: 3
2022-06-10T08:45:46.475Z - info: [main] Processing protocol url
2022-06-10T08:45:46.476Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-10T08:45:47.038Z - info: [ui] [AppStore] loading 146 repositories from store
2022-06-10T08:45:47.039Z - info: [ui] [AppStore] found account: martincostello (Martin Costello)
2022-06-10T08:45:47.039Z - info: [ui] [AppStore] found account: martin-costello (Martin Costello)
2022-06-10T08:45:47.088Z - info: [ui] [BranchPruner] Last prune took place 15 minutes ago - skipping
2022-06-10T08:45:47.583Z - warn: [ui] fetchAccount: failed with endpoint https://<GHES_HOSTNAME>/api/v3
TypeError: Failed to execute 'fetch' on 'Window': Invalid value
    at _t (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\http.ts:152:10)
    at yn.request (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1401:28)
    at yn.fetchAccount (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:818:35)
    at bn (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1657:28)
    at C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\accounts-store.ts:219:10
    at dr.tryUpdateAccount (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\accounts-store.ts:134:20)
    at C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\accounts-store.ts:114:37
    at Array.map (<anonymous>)
    at dr.refresh (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\accounts-store.ts:114:21)
    at dr.loadInitialState (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\app-store.ts:1886:24)
2022-06-10T08:45:47.584Z - warn: [ui] fetchUser: failed with endpoint https://<GHES_HOSTNAME>/api/v3
TypeError: Failed to execute 'fetch' on 'Window': Invalid value
    at _t (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\http.ts:152:10)
    at yn.request (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1401:28)
    at yn.fetchAccount (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:818:35)
    at bn (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1657:28)
    at C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\accounts-store.ts:219:10
    at dr.tryUpdateAccount (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\accounts-store.ts:134:20)
    at C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\accounts-store.ts:114:37
    at Array.map (<anonymous>)
    at dr.refresh (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\accounts-store.ts:114:21)
    at dr.loadInitialState (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\app-store.ts:1886:24)
2022-06-10T08:45:47.584Z - warn: [ui] Error refreshing account 'martin-costello'
TypeError: Failed to execute 'fetch' on 'Window': Invalid value
    at _t (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\http.ts:152:10)
    at yn.request (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1401:28)
    at yn.fetchAccount (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:818:35)
    at bn (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1657:28)
    at C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\accounts-store.ts:219:10
    at dr.tryUpdateAccount (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\accounts-store.ts:134:20)
    at C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\accounts-store.ts:114:37
    at Array.map (<anonymous>)
    at dr.refresh (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\accounts-store.ts:114:21)
    at dr.loadInitialState (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\app-store.ts:1886:24)
2022-06-10T08:45:47.680Z - info: [ui] launching: 3.0.1 (Windows 10.0.22000)
2022-06-10T08:45:47.697Z - info: [ui] execPath: 'C:\Users\martin.costello\AppData\Local\GitHubDesktop\app-3.0.1\GitHubDesktop.exe'
2022-06-10T08:45:47.740Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
TypeError: Failed to execute 'fetch' on 'Window': Invalid value
    at _t (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\http.ts:152:10)
    at yn.request (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1401:28)
    at yn.fetchProtectedBranches (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1347:35)
    at dr.updateBranchProtectionsFromAPI (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\app-store.ts:3681:32)
    at dr._selectRepository (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\app-store.ts:1538:10)
    at Object.dispatchURLAction (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\ui\dispatcher\dispatcher.ts:1829:13)
2022-06-10T08:45:47.750Z - warn: [ui] getFetchPollInterval: failed for martin-costello/blog-posts
TypeError: Failed to execute 'fetch' on 'Window': Invalid value
    at _t (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\http.ts:152:10)
    at yn.request (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1401:28)
    at yn.getFetchPollInterval (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1439:35)
    at To.getFetchInterval (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\helpers\background-fetcher.ts:136:38)
    at To.performAndScheduleFetch (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\helpers\background-fetcher.ts:117:33)
2022-06-10T08:45:47.754Z - warn: [ui] fetchIssues: failed for repository martin-costello/blog-posts
TypeError: Failed to execute 'fetch' on 'Window': Invalid value
    at _t (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\http.ts:152:10)
    at yn.request (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1401:28)
    at yn.fetchAll (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1372:45)
    at yn.fetchIssues (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:922:33)
    at YN.constructor.refreshIssues (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\issues-store.ts:81:30)
    at dr._refreshIssues (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\app-store.ts:1650:5)
2022-06-10T08:45:47.754Z - warn: [ui] Unable to fetch issues for martin-costello/blog-posts
TypeError: Failed to execute 'fetch' on 'Window': Invalid value
    at _t (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\http.ts:152:10)
    at yn.request (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1401:28)
    at yn.fetchAll (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1372:45)
    at yn.fetchIssues (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:922:33)
    at YN.constructor.refreshIssues (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\issues-store.ts:81:30)
    at dr._refreshIssues (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\app-store.ts:1650:5)
2022-06-10T08:45:47.755Z - warn: [ui] fetchMentionables: failed for martin-costello/blog-posts
TypeError: Failed to execute 'fetch' on 'Window': Invalid value
    at _t (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\http.ts:152:10)
    at yn.request (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1401:28)
    at yn.fetchMentionables (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1469:35)
    at VN.constructor.updateMentionables (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\github-user-store.ts:90:32)
2022-06-10T08:45:47.756Z - info: [ui] [BranchPruner] Last prune took place 15 minutes ago - skipping
2022-06-10T08:45:47.761Z - warn: [ui] failed fetching open PRs for repository martin-costello/blog-posts
TypeError: Failed to execute 'fetch' on 'Window': Invalid value
    at _t (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\http.ts:152:10)
    at yn.request (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1401:28)
    at yn.fetchAll (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1372:45)
    at yn.fetchAllOpenPullRequests (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:938:25)
    at eB.constructor.fetchAndStoreOpenPullRequests (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\pull-request-store.ts:110:28)
    at eB.constructor.fetchAndStorePullRequests (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\pull-request-store.ts:99:19)
    at Object.refreshPullRequests (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\pull-request-coordinator.ts:160:45)
2022-06-10T08:45:47.763Z - error: [ui] Error refreshing pull requests for 'martin-costello/blog-posts'
TypeError: Failed to execute 'fetch' on 'Window': Invalid value
    at _t (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\http.ts:152:10)
    at yn.request (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1401:28)
    at yn.fetchAll (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1372:45)
    at yn.fetchAllOpenPullRequests (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:938:25)
    at eB.constructor.fetchAndStoreOpenPullRequests (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\pull-request-store.ts:110:28)
    at eB.constructor.fetchAndStorePullRequests (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\pull-request-store.ts:99:19)
    at Object.refreshPullRequests (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\pull-request-coordinator.ts:160:45)
2022-06-10T08:45:47.813Z - warn: [ui] fetchRepository: an error occurred for 'martin-costello/blog-posts'
TypeError: Failed to execute 'fetch' on 'Window': Invalid value
    at _t (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\http.ts:152:10)
    at yn.request (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:1401:28)
    at yn.fetchRepository (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\api.ts:742:35)
    at dr.repositoryWithRefreshedGitHubRepository (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\lib\stores\app-store.ts:3637:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.dispatchURLAction (C:\Coding\martin-costello\blog-posts\webpack:\[name]\app\src\ui\dispatcher\dispatcher.ts:1829:13)
2022-06-10T08:45:47.851Z - info: [ui] Subscribed 'martincostello' to Alive channel
```

**Comment by steveward** [comment]
@martincostello thanks for the report. Just to confirm -- did you revoke GitHub Desktop at `Settings` > `Applications` > `Authorized OAuth Apps`? You mentioned revoking GitHub CLI so I wanted to clarify.

**Comment by martincostello** [comment]
Sorry, I meant the git CLI, not GitHub CLI.

I revoked my PAT using `Settings` > `Developer settings` > `Personal access tokens`.

**Comment by steveward** [comment]
@martincostello Can you try revoking the GitHub Desktop auth from the location I mentioned above? Then try logging out/logging back in again to GitHub Desktop. Revoking the Git CLI PAT does not affect GitHub Desktop as they use separate authentication methods.

**Comment by martincostello** [comment]
I re-restored my previous `C:\Users\{username}\AppData\Roaming\GitHub Desktop` folder (I'd backed it up) to see if it was still crashing, and it isn't anymore without me touching anything (including revoking the app).

Seems that whatever it was that was breaking it has been resolved by me reinstalling GitHub Desktop since I opened this issue.
