### ISSUE TITLE
Github Desktop does not distinguish between uppercase and lowercase

### ISSUE THREAD

**Issue by NhanAZ** [desktop/desktop#14800]
### The problem

When I rename any file
Git doesn't recognize it
For example:
I have a file named `basic.php` I renamed it `Basic.php`
Github won't recognize this so I won't be able to commit.

### Release version

Version 3.0.2-beta4 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Pull any repo to device
2. Change any file name. Example: `basic.php` to `Basic.php`
At this point Github won't recognize what you just changed, and you can't commit.

### Log files

```log
2022-06-14T02:09:33.481Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-14T02:09:36.912Z - info: [ui] [AppStore] loading 4 repositories from store
2022-06-14T02:09:36.914Z - info: [ui] [AppStore] found account: NhanAZ (Thành Nhân)
2022-06-14T02:09:36.955Z - info: [ui] [BranchPruner] Last prune took place 22 hours ago - skipping
2022-06-14T02:09:39.201Z - info: [ui] Executing getRemotes: git remote -v (took 2.218s)
2022-06-14T02:09:39.227Z - info: [ui] Subscribed 'NhanAZ' to Alive channel
2022-06-14T02:09:39.268Z - info: [ui] launching: 3.0.2-beta4 (Windows 10.0.22000)
2022-06-14T02:09:39.279Z - info: [ui] execPath: 'C:\Users\nhang\AppData\Local\GitHubDesktop\app-3.0.2-beta4\GitHubDesktop.exe'
2022-06-14T02:09:40.057Z - info: [main] Received possible protocol arguments: 2
2022-06-14T02:09:40.060Z - error: [main] Malformed launch arguments received: C:\Users\nhang\AppData\Local\GitHubDesktop\app-3.0.2-beta4\GitHubDesktop.exe,--allow-file-access-from-files
2022-06-14T02:09:41.854Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.608s)
2022-06-14T02:09:45.758Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune --recurse-submodules=on-demand origin (took 1.754s)
2022-06-14T02:09:49.397Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/BeeAZ-pm-pl/AcidIsland.git - NhanAZ (has token)
2022-06-14T02:09:54.250Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/BeeAZ-pm-pl/AcidIsland.git D:\Dev\plugins\AcidIsland (took 4.756s)
2022-06-14T02:09:54.350Z - info: [ui] [AppStore] adding repository at D:\Dev\plugins\AcidIsland to store
2022-06-14T02:09:54.442Z - info: [ui] [BranchPruner] Last prune took place 22 hours ago - skipping
2022-06-14T02:09:55.845Z - info: [ui] Executing isUsingLFS: git lfs track (took 1.304s)
2022-06-14T02:09:55.885Z - info: [ui] [BranchPruner] Last prune took place 11 hours ago - skipping
2022-06-14T02:10:10.092Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: AcidIsland - NhanAZ (has token)
2022-06-14T02:10:11.263Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune --recurse-submodules=on-demand origin (took 1.049s)
2022-06-14T02:10:11.322Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 11.5s of which 11.4s paused, total 22.9s
2022-06-14T02:16:41.960Z - info: [ui] [BranchPruner] Last prune took place 22 hours ago - skipping
2022-06-14T02:19:12.201Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/NhanAZ/AcidIsland.git - NhanAZ (has token)
2022-06-14T02:19:16.620Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/NhanAZ/AcidIsland.git D:\Dev\plugins\AcidIsland (took 4.345s)
2022-06-14T02:19:16.683Z - info: [ui] [AppStore] adding repository at D:\Dev\plugins\AcidIsland to store
2022-06-14T02:19:16.750Z - info: [ui] [BranchPruner] Last prune took place 22 hours ago - skipping
2022-06-14T02:19:18.194Z - info: [ui] Executing isUsingLFS: git lfs track (took 1.380s)
2022-06-14T02:19:18.284Z - info: [ui] [BranchPruner] Last prune took place 11 hours ago - skipping
2022-06-14T02:19:31.624Z - info: [ui] [BranchPruner] Last prune took place 11 hours ago - skipping
2022-06-14T02:21:16.702Z - info: [ui] [Timing] Action 'create commit' for 'NhanAZ/AcidIsland' took 0.728s
2022-06-14T02:21:18.080Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: AcidIsland - NhanAZ (has token)
2022-06-14T02:21:19.771Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 1.626s)
2022-06-14T02:21:54.847Z - info: [ui] [BranchPruner] Last prune took place 22 hours ago - skipping
2022-06-14T02:25:18.579Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 3 repositories took 2.1s of which 8.3s paused, total 10.4s
2022-06-14T02:25:22.582Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/BeeAZ-pm-pl/AcidIsland.git - NhanAZ (has token)
2022-06-14T02:25:26.551Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/BeeAZ-pm-pl/AcidIsland.git D:\Dev\plugins\AcidIsland (took 3.894s)
2022-06-14T02:25:26.624Z - info: [ui] [AppStore] adding repository at D:\Dev\plugins\AcidIsland to store
2022-06-14T02:25:26.718Z - info: [ui] [BranchPruner] Last prune took place 22 hours ago - skipping
2022-06-14T02:25:27.878Z - info: [ui] [BranchPruner] Last prune took place 11 hours ago - skipping
2022-06-14T02:26:24.524Z - info: [ui] [Timing] Action 'create commit' for 'BeeAZ-pm-pl/AcidIsland' took 0.696s
2022-06-14T02:26:26.309Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: AcidIsland - NhanAZ (has token)
2022-06-14T02:26:29.439Z - info: [ui] [BranchPruner] Last prune took place 11 hours ago - skipping
2022-06-14T02:26:32.020Z - info: [ui] [BranchPruner] Last prune took place 11 hours ago - skipping
2022-06-14T02:26:35.092Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: AcidIsland - NhanAZ (has token)
2022-06-14T02:26:36.113Z - error: [ui] `git -c credential.helper= -c protocol.version=2 push origin master:master --progress` exited with an unexpected code: 1.
stderr:
To https://github.com/NhanAZ/AcidIsland.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/NhanAZ/AcidIsland.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

(The error was parsed as 10: The repository has been updated since you last pulled. Try pulling before pushing.)
2022-06-14T02:26:40.384Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: AcidIsland - NhanAZ (has token)
2022-06-14T02:26:41.928Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune --recurse-submodules=on-demand origin (took 1.463s)
2022-06-14T02:26:47.440Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: AcidIsland - NhanAZ (has token)
2022-06-14T02:26:51.155Z - info: [ui] Executing pull: git -c credential.helper= -c protocol.version=2 -c rebase.backend=merge pull --ff --recurse-submodules --progress origin (took 3.530s)
2022-06-14T02:27:00.222Z - error: [ui] Failed moving repository to trash
Error: Error invoking remote method 'move-to-trash': Error: Operation was aborted
    at EventEmitter.i.invoke (node:electron/js2c/renderer_init:57:526)
    at pr._removeRepository (C:\Users\nhang\AppData\Local\GitHubDesktop\app-3.0.2-beta4\webpack:\[name]\app\src\lib\stores\app-store.ts:5446:9)
    at Object.onConfirmRepoRemoval [as onConfirmation] (C:\Users\nhang\AppData\Local\GitHubDesktop\app-3.0.2-beta4\webpack:\[name]\app\src\ui\app.tsx:1159:5)
    at Object.onSubmit (C:\Users\nhang\AppData\Local\GitHubDesktop\app-3.0.2-beta4\webpack:\[name]\app\src\ui\remove-repository\confirm-remove-repository.tsx:42:43)
2022-06-14T02:27:07.478Z - info: [ui] [BranchPruner] Last prune took place 22 hours ago - skipping
2022-06-14T02:28:17.624Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/BeeAZ-pm-pl/AcidIsland.git - NhanAZ (has token)
2022-06-14T02:28:22.116Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/BeeAZ-pm-pl/AcidIsland.git D:\Dev\plugins\AcidIsland (took 4.401s)
2022-06-14T02:28:22.189Z - info: [ui] [AppStore] adding repository at D:\Dev\plugins\AcidIsland to store
2022-06-14T02:28:22.295Z - info: [ui] [BranchPruner] Last prune took place 22 hours ago - skipping
2022-06-14T02:28:23.409Z - info: [ui] [BranchPruner] Last prune took place 11 hours ago - skipping
2022-06-14T02:29:00.563Z - info: [ui] [Timing] Action 'create commit' for 'BeeAZ-pm-pl/AcidIsland' took 0.686s
2022-06-14T02:29:01.419Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: AcidIsland - NhanAZ (has token)
2022-06-14T02:29:04.737Z - info: [ui] [BranchPruner] Last prune took place 11 hours ago - skipping
2022-06-14T02:29:06.880Z - info: [ui] [BranchPruner] Last prune took place 11 hours ago - skipping
2022-06-14T02:29:09.346Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: AcidIsland - NhanAZ (has token)
2022-06-14T02:29:10.946Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 1.533s)
2022-06-14T02:29:15.321Z - info: [main] opening in browser: https://github.com/NhanAZ/AcidIsland/pull/new/master
2022-06-14T02:31:47.245Z - info: [ui] [Timing] Action 'create commit' for 'NhanAZ/AcidIsland' took 0.818s
2022-06-14T02:32:20.525Z - info: [ui] [Timing] Action 'create commit' for 'NhanAZ/AcidIsland' took 0.814s
2022-06-14T02:32:21.556Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: AcidIsland - NhanAZ (has token)
2022-06-14T02:32:23.335Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 1.714s)
2022-06-14T02:32:25.380Z - info: [main] opening in browser: https://github.com/NhanAZ/AcidIsland/pull/new/master
2022-06-14T02:33:14.451Z - error: [ui] Failed moving repository to trash
Error: Error invoking remote method 'move-to-trash': Error: Operation was aborted
    at EventEmitter.i.invoke (node:electron/js2c/renderer_init:57:526)
    at pr._removeRepository (C:\Users\nhang\AppData\Local\GitHubDesktop\app-3.0.2-beta4\webpack:\[name]\app\src\lib\stores\app-store.ts:5446:9)
    at Object.onConfirmRepoRemoval [as onConfirmation] (C:\Users\nhang\AppData\Local\GitHubDesktop\app-3.0.2-beta4\webpack:\[name]\app\src\ui\app.tsx:1159:5)
    at Object.onSubmit (C:\Users\nhang\AppData\Local\GitHubDesktop\app-3.0.2-beta4\webpack:\[name]\app\src\ui\remove-repository\confirm-remove-repository.tsx:42:43)
2022-06-14T02:33:22.836Z - info: [ui] [BranchPruner] Last prune took place 22 hours ago - skipping
2022-06-14T02:34:08.062Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune --recurse-submodules=on-demand origin (took 1.862s)
2022-06-14T02:34:21.047Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: PocketMine-MP - NhanAZ (has token)
2022-06-14T02:34:23.427Z - info: [ui] Executing checkoutBranch: git -c credential.helper= -c protocol.version=2 checkout --progress stable --recurse-submodules -- (took 2.305s)
2022-06-14T02:34:24.222Z - info: [ui] [Timing] Action 'checkout branch from list' for 'pmmp/PocketMine-MP' took 3.176s
2022-06-14T02:34:29.246Z - info: [main] opening in browser: https://desktop.github.com

```

### Screenshots

N/A

### Additional context

N/A

**Comment by HeCorr** [comment]
I can confirm this but it's an issue with Git itself, not GitHub Desktop.

This seems to explain how to work around this issue: https://daily-dev-tips.com/posts/git-basics-help-my-case-sensitive-filename-changes-dont-commit/

**Comment by tsvetilian-ty** [comment]
@NhanAZ as @HeCorr shared it, 's a behavior-driven by git and, more specifically `core.ignorecase`. To bypass the case sensitivity, you can use `git mv <old> <new>` from the command line. You can check https://github.com/desktop/desktop/issues/2672#issuecomment-329011490 for more information. I'm going to close this issue.
