### ISSUE TITLE
Github Desktop tries to remove files

### ISSUE THREAD

**Issue by Cerabbite** [desktop/desktop#14850]
### The problem

I was trying to get started on an open-source project I have been working on for the last month. When I went to fetch the changes I had made on my laptop everything worked fine. Upuntill Github desktop showed 1 changed file which was a file that was deleted from the repository. But I did not remove anything from the repository. When I went to discard changes it removed another file I discarded that change it went back to removing the first file.

### Release version

3.0.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

I do not know it happend after fetching changes made from another computer.

### Log files

2022-06-22T05:56:30.409Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-06-22T05:56:31.106Z - info: [ui] [AppStore] loading 20 repositories from store
2022-06-22T05:56:31.107Z - info: [ui] [AppStore] found account: Cerabbite (Cerabbite)
2022-06-22T05:56:31.189Z - info: [ui] [BranchPruner] Last prune took place 17 hours ago - skipping
2022-06-22T05:56:31.518Z - info: [ui] launching: 3.0.2 (Windows 10.0.19044)
2022-06-22T05:56:31.520Z - info: [ui] execPath: 'C:\Users\'Username'\AppData\Local\GitHubDesktop\app-3.0.2\GitHubDesktop.exe'
2022-06-22T05:56:31.675Z - info: [ui] Subscribed 'Cerabbite' to Alive channel
2022-06-22T05:56:39.144Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.285s)
2022-06-22T05:56:39.171Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.300s)
2022-06-22T05:56:40.892Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: learn-programming - Cerabbite (has token)
2022-06-22T05:56:41.784Z - info: [ui] Executing getChangedFilesNameStatus: git log 78c6c205fbcd0620f2b93921d509ef13bb0dbb46 -C -M -m -1 --no-show-signature --first-parent --format=format: -z --name-status -- (took 1.877s)
2022-06-22T05:56:42.080Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.054s)
2022-06-22T05:56:47.822Z - info: [ui] Executing getChangedFilesNumStats: git log 78c6c205fbcd0620f2b93921d509ef13bb0dbb46 -C -M -m -1 --no-show-signature --first-parent --format=format: -z --numstat -- (took 6.037s)
2022-06-22T05:58:47.348Z - info: [ui] [Timing] Action 'create commit' for 'Cerabbite/learn-programming' took 1.508s
2022-06-22T05:58:48.421Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: learn-programming - Cerabbite (has token)
2022-06-22T05:58:49.873Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 1.372s)
2022-06-22T06:17:11.379Z - info: [ui] [Timing] Action 'create commit' for 'Cerabbite/learn-programming' took 1.059s
2022-06-22T06:17:53.888Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 19 repositories took 12.6s of which 1234.2s paused, total 1246.7s
2022-06-22T06:17:56.521Z - info: [ui] [Timing] Action 'create commit' for 'Cerabbite/learn-programming' took 1.033s
2022-06-22T06:17:57.797Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: learn-programming - Cerabbite (has token)
2022-06-22T06:17:59.267Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 1.389s)
2022-06-22T06:19:45.495Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.278s)
2022-06-22T06:19:46.956Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: writing - Cerabbite (has token)
2022-06-22T06:19:48.334Z - info: [ui] Executing pull: git -c credential.helper= -c protocol.version=2 -c rebase.backend=merge pull --ff --progress origin (took 1.060s)
2022-06-22T06:19:48.611Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 19 repositories took 6.6s of which 0.0s paused, total 6.6s
2022-06-22T06:21:46.668Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: writing - Cerabbite (has token)
2022-06-22T06:22:20.987Z - info: [ui] No submodules found. Skipping "git submodule status"
2022-06-22T06:22:27.139Z - error: [ui] Highlighter worked failed for old contents
Error: timed out
    at C:\Users\'Username'\AppData\Local\GitHubDesktop\app-3.0.2\webpack:\[name]\app\src\lib\highlighter\worker.ts:85:14
2022-06-22T06:22:27.141Z - error: [ui] Highlighter worked failed for old contents
Error: timed out
    at C:\Users\'Username'\AppData\Local\GitHubDesktop\app-3.0.2\webpack:\[name]\app\src\lib\highlighter\worker.ts:85:14
2022-06-22T06:22:33.192Z - info: [ui] No submodules found. Skipping "git submodule status"
2022-06-22T06:22:37.332Z - info: [ui] No submodules found. Skipping "git submodule status"
2022-06-22T06:22:42.974Z - error: [ui] Highlighter worked failed for old contents
Error: timed out
    at C:\Users\'Username'\AppData\Local\GitHubDesktop\app-3.0.2\webpack:\[name]\app\src\lib\highlighter\worker.ts:85:14
2022-06-22T06:22:42.975Z - error: [ui] Highlighter worked failed for old contents
Error: timed out
    at C:\Users\'Username'\AppData\Local\GitHubDesktop\app-3.0.2\webpack:\[name]\app\src\lib\highlighter\worker.ts:85:14
2022-06-22T06:22:55.736Z - info: [ui] No submodules found. Skipping "git submodule status"
2022-06-22T06:23:32.576Z - info: [ui] No submodules found. Skipping "git submodule status"
2022-06-22T06:23:38.222Z - error: [ui] Highlighter worked failed for old contents
Error: timed out
    at C:\Users\'Username'\AppData\Local\GitHubDesktop\app-3.0.2\webpack:\[name]\app\src\lib\highlighter\worker.ts:85:14
2022-06-22T06:23:38.223Z - error: [ui] Highlighter worked failed for old contents
Error: timed out
    at C:\Users\'Username'\AppData\Local\GitHubDesktop\app-3.0.2\webpack:\[name]\app\src\lib\highlighter\worker.ts:85:14
2022-06-22T06:23:43.382Z - info: [ui] No submodules found. Skipping "git submodule status"

**Comment by Cerabbite** [comment]
I commited the removal of one file since it was a file with just a version number in it. I tried to remake the file, but Windows says that the file already exists even though I cannot find it anywhere.

**Comment by Cerabbite** [comment]
So the file had no extension, and I had a folder with the same name, I created the folder on the web version of Github and Windows had a problem with it.
