### ISSUE TITLE
Unable to login (API v2 would go away)

### ISSUE THREAD

**Issue by Firestar-Reimu** [desktop/desktop#14938]
### The problem

https://github.blog/2012-06-12-github-api-v2-end-of-life/

### The problem

![Screenshot_20220710_162446](https://user-images.githubusercontent.com/65082432/178137202-63779cd6-c505-4db1-af74-dba9ae3e80da.png)

The login using browser

### Release version

3.0.3

### Operating system

 Manjaro Linux

**Comment by niik** [comment]
Hi @Firestar-Reimu, thanks for reaching out. Are you seeing this error every time you attempt to sign in? That warning is for an ancient API which we certainly don't use in GitHub Desktop any more so I'm very surprised you'd be seeing it in the app today. 

I'm unable to reproduce this myself so some more details would be much appreciated. Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by Firestar-Reimu** [comment]
> Are you seeing this error every time you attempt to sign in?

Yes

**Comment by Carlos920** [comment]
> > Are you seeing this error every time you attempt to sign in?
> 
> Yes

I have the same problem.

this is my log 
```
2022-07-11T01:44:14.543Z - info: [main] Received possible protocol arguments: 4
2022-07-11T01:44:14.543Z - info: [main] Processing protocol url
2022-07-11T01:44:14.544Z - info: [ui] [Dispatcher] requesting authenticated user
2022-07-11T01:44:18.883Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
Error: Hello there, wayfaring stranger. If you’re reading this then you probably didn’t see our blog post a couple of years back announcing that this API would go away: http://git.io/17AROg Fear not, you should be able to get what you need from the shiny new Events API instead.
    at Bt (C:\Users\Azraias\AppData\Local\GitHubDesktop\app-3.0.3\webpack:\[name]\app\src\lib\http.ts:178:11)
    at En.fetchAccount (C:\Users\Azraias\AppData\Local\GitHubDesktop\app-3.0.3\webpack:\[name]\app\src\lib\api.ts:820:7)
    at Rn (C:\Users\Azraias\AppData\Local\GitHubDesktop\app-3.0.3\webpack:\[name]\app\src\lib\api.ts:1657:11)
    at Object.dispatchURLAction (C:\Users\Azraias\AppData\Local\GitHubDesktop\app-3.0.3\webpack:\[name]\app\src\ui\dispatcher\dispatcher.ts:1787:17)
2022-07-11T01:44:18.883Z - warn: [ui] fetchUser: failed with endpoint https://api.github.com
Error: Hello there, wayfaring stranger. If you’re reading this then you probably didn’t see our blog post a couple of years back announcing that this API would go away: http://git.io/17AROg Fear not, you should be able to get what you need from the shiny new Events API instead.
    at Bt (C:\Users\Azraias\AppData\Local\GitHubDesktop\app-3.0.3\webpack:\[name]\app\src\lib\http.ts:178:11)
    at En.fetchAccount (C:\Users\Azraias\AppData\Local\GitHubDesktop\app-3.0.3\webpack:\[name]\app\src\lib\api.ts:820:7)
    at Rn (C:\Users\Azraias\AppData\Local\GitHubDesktop\app-3.0.3\webpack:\[name]\app\src\lib\api.ts:1657:11)
    at Object.dispatchURLAction (C:\Users\Azraias\AppData\Local\GitHubDesktop\app-3.0.3\webpack:\[name]\app\src\ui\dispatcher\dispatcher.ts:1787:17)
2022-07-11T01:44:18.884Z - info: [ui] [SignInStore] error with OAuth flow
Error: Hello there, wayfaring stranger. If you’re reading this then you probably didn’t see our blog post a couple of years back announcing that this API would go away: http://git.io/17AROg Fear not, you should be able to get what you need from the shiny new Events API instead.
    at Bt (C:\Users\Azraias\AppData\Local\GitHubDesktop\app-3.0.3\webpack:\[name]\app\src\lib\http.ts:178:11)
    at En.fetchAccount (C:\Users\Azraias\AppData\Local\GitHubDesktop\app-3.0.3\webpack:\[name]\app\src\lib\api.ts:820:7)
    at Rn (C:\Users\Azraias\AppData\Local\GitHubDesktop\app-3.0.3\webpack:\[name]\app\src\lib\api.ts:1657:11)
    at Object.dispatchURLAction (C:\Users\Azraias\AppData\Local\GitHubDesktop\app-3.0.3\webpack:\[name]\app\src\ui\dispatcher\dispatcher.ts:1787:17)
2022-07-11T01:44:18.885Z - error: [ui] Error checking for updates
undefined: 

```

**Comment by tsvetilian-ty** [comment]
I tried to reproduce it as well, but no luck 😞 

There are reports of the same problem in https://github.com/desktop/desktop/issues/11110, https://github.com/desktop/desktop/issues/10285, and https://github.com/desktop/desktop/issues/11506.

A fix that worked in the other reports is to clear `%APPDATA%\GitHub Desktop` alternatively on Linux distro should be `~/.config/GitHub\ Desktop/`

> Removing the files and folders from the data dir will reset GitHub Desktop!

The interesting part is that it looks the common thing between the reports is that the systems are using non-ascii encoding 🤔

**Comment by Firestar-Reimu** [comment]
This does not happen every day. This week I tried 2 times and do not happen.

**Comment by tsvetilian-ty** [comment]
Hey @Firestar-Reimu did you try the thing I suggested in https://github.com/desktop/desktop/issues/14938#issuecomment-1180327288 ?
