### ISSUE TITLE
Authentication failed : GitHub Desktop

### ISSUE THREAD

**Issue by atulismyname** [desktop/desktop#14979]
### The problem

2022-07-16T03:52:05.373Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\HPvns\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at X (C:\Users\HPvns\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\HPvns\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\HPvns\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\main-process\notifications.ts:23:32
    at C:\Users\HPvns\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\main-process\main.ts:709:55
    at Object.<anonymous> (C:\Users\HPvns\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\main-process\main.ts:709:55)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
2022-07-16T03:52:05.387Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\HPvns\Desktop\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at X (C:\Users\HPvns\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\HPvns\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\HPvns\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\main-process\notifications.ts:23:32
    at C:\Users\HPvns\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\main-process\main.ts:709:55
    at Object.<anonymous> (C:\Users\HPvns\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\main-process\main.ts:709:55)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
2022-07-16T03:52:05.387Z - error: [main] Toast activator CLSID not found in any of the shortucts. Falling back to known CLSIDs.
2022-07-16T03:52:05.387Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-07-16T03:52:06.797Z - info: [main] Received possible protocol arguments: 2
2022-07-16T03:52:06.818Z - error: [main] Malformed launch arguments received: C:\Users\HPvns\AppData\Local\GitHubDesktop\app-3.0.5\GitHubDesktop.exe,--squirrel-firstrun
2022-07-16T03:52:06.818Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-07-16T03:52:07.855Z - info: [ui] [AppStore] loading 0 repositories from store
2022-07-16T03:52:08.354Z - info: [ui] launching: 3.0.5 (Windows 10.0.22000)
2022-07-16T03:52:08.361Z - info: [ui] execPath: 'C:\Users\HPvns\AppData\Local\GitHubDesktop\app-3.0.5\GitHubDesktop.exe'
2022-07-16T03:52:08.497Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-07-16T03:52:08.930Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-07-16T03:52:08.936Z - info: [ui] Opt in reported.
2022-07-16T03:52:09.683Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-07-16T03:52:09.907Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-07-16T03:52:11.019Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.635s)
2022-07-16T03:52:11.832Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
2022-07-16T03:52:11.834Z - info: [ui] [SignInStore] initializing OAuth flow
2022-07-16T03:52:11.836Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=af63fdae-72db-45b3-88bc-815c53ca08df
2022-07-16T03:52:11.836Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2022-07-16T03:52:12.058Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2022-07-16T03:53:16.320Z - info: [main] Received possible protocol arguments: 4
2022-07-16T03:53:16.322Z - info: [main] Processing protocol url
2022-07-16T03:53:16.337Z - info: [ui] [Dispatcher] requesting authenticated user
2022-07-16T03:53:16.343Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2022-07-16T03:53:16.355Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2022-07-16T03:53:17.943Z - info: [ui] [SignInStore] account resolved
2022-07-16T03:53:17.945Z - info: [ui] [AppStore] adding account atulismyname (ATUL RAI) to store
2022-07-16T03:53:17.996Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2022-07-16T03:53:18.143Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-07-16T03:53:18.168Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-07-16T03:53:18.608Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-07-16T03:53:18.754Z - info: [ui] Subscribed 'atulismyname' to Alive channel
2022-07-16T05:54:09.978Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2022-07-16T05:54:11.781Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2022-07-16T05:54:14.806Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2022-07-16T05:54:19.781Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2022-07-16T05:54:28.776Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2022-07-16T06:02:01.680Z - info: [ui] [AppStore] adding repository at C:\Users\HPvns\Desktop\my_react_app to store
2022-07-16T06:02:03.357Z - info: [ui] Executing isUsingLFS: git lfs track (took 1.350s)
2022-07-16T06:02:03.629Z - info: [ui] [BranchPruner] Last prune took place 1 second ago - skipping
2022-07-16T06:02:40.176Z - info: [ui] [Timing] Action 'create commit' for 'atulismyname/my_react_app' took 1.873s
2022-07-16T06:02:59.070Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: my_react_app - atulismyname (has token)
2022-07-16T06:03:08.463Z - info: [ui] Executing push: git -c credential.helper= push origin main --set-upstream --progress (took 9.345s)
2022-07-16T06:03:08.465Z - error: [ui] `git -c credential.helper= push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
Warning: Permanently added 'github.com,13.234.210.38' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-07-16T06:03:45.982Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: my_react_app - atulismyname (has token)
2022-07-16T06:03:47.628Z - info: [ui] Executing push: git -c credential.helper= push origin main --set-upstream --progress (took 1.641s)
2022-07-16T06:03:47.639Z - error: [ui] `git -c credential.helper= push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-07-16T06:04:12.574Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: my_react_app - atulismyname (has token)
2022-07-16T06:04:14.369Z - info: [ui] Executing push: git -c credential.helper= push origin main --set-upstream --progress (took 1.790s)
2022-07-16T06:04:14.380Z - error: [ui] `git -c credential.helper= push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-07-16T06:04:54.546Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: my_react_app - atulismyname (has token)
2022-07-16T06:04:56.470Z - info: [ui] Executing push: git -c credential.helper= push origin main --set-upstream --progress (took 1.888s)
2022-07-16T06:04:56.472Z - error: [ui] `git -c credential.helper= push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-07-16T06:06:00.812Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: my_react_app - atulismyname (has token)
2022-07-16T06:06:02.305Z - info: [ui] Executing push: git -c credential.helper= push origin main --set-upstream --progress (took 1.454s)
2022-07-16T06:06:02.317Z - error: [ui] `git -c credential.helper= push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
Warning: Permanently added the ECDSA host key for IP address '13.234.176.102' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-07-16T06:07:15.545Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.770s)
2022-07-16T06:07:15.547Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-07-16T06:08:20.921Z - info: [main] Received possible protocol arguments: 4
2022-07-16T06:08:20.926Z - info: [main] Processing protocol url
2022-07-16T06:08:21.049Z - info: [ui] [BranchPruner] Last prune took place 6 minutes ago - skipping
2022-07-16T06:08:22.637Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.584s)
2022-07-16T06:08:22.639Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-07-16T06:08:25.234Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: my_react_app - atulismyname (has token)
2022-07-16T06:08:26.754Z - info: [ui] Executing push: git -c credential.helper= push origin main --set-upstream --progress (took 1.513s)
2022-07-16T06:08:26.757Z - error: [ui] `git -c credential.helper= push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-07-16T06:08:29.835Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: my_react_app - atulismyname (has token)
2022-07-16T06:08:31.277Z - info: [ui] Executing push: git -c credential.helper= push origin main --set-upstream --progress (took 1.407s)
2022-07-16T06:08:31.279Z - error: [ui] `git -c credential.helper= push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-07-16T06:08:42.228Z - info: [main] Received possible protocol arguments: 3
2022-07-16T06:08:42.237Z - info: [main] Processing protocol url
2022-07-16T06:08:42.237Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-07-16T06:08:43.226Z - info: [ui] [AppStore] loading 1 repositories from store
2022-07-16T06:08:43.228Z - info: [ui] [AppStore] found account: atulismyname (ATUL RAI)
2022-07-16T06:08:43.398Z - info: [ui] [BranchPruner] Last prune took place 7 minutes ago - skipping
2022-07-16T06:08:43.947Z - info: [ui] launching: 3.0.5 (Windows 10.0.22000)
2022-07-16T06:08:43.953Z - info: [ui] execPath: 'C:\Users\HPvns\AppData\Local\GitHubDesktop\app-3.0.5\GitHubDesktop.exe'
2022-07-16T06:08:44.580Z - info: [ui] [BranchPruner] Last prune took place 7 minutes ago - skipping
2022-07-16T06:08:44.619Z - info: [ui] Subscribed 'atulismyname' to Alive channel
2022-07-16T06:08:44.953Z - info: [ui] Stats reported.
2022-07-16T06:08:44.980Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.046s)
2022-07-16T06:08:45.716Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.579s)
2022-07-16T06:08:45.722Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-07-16T06:08:47.835Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: my_react_app - atulismyname (has token)
2022-07-16T06:08:49.321Z - info: [ui] Executing push: git -c credential.helper= push origin main --set-upstream --progress (took 1.467s)
2022-07-16T06:08:49.326Z - error: [ui] `git -c credential.helper= push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)

### Release version

3.0.5

### Operating system

windows 11

### Log files

![image](https://user-images.githubusercontent.com/76132275/179342532-fe2398c5-5b38-47eb-819d-a5a8245d3f83.png)

### Screenshots

![image](https://user-images.githubusercontent.com/76132275/179342534-07a95d14-f114-44c5-9964-715586d696e7.png)

**Comment by sergiou87** [comment]
Hello @atulismyname 👋 

Could you give us more details about your setup? Have you uploaded your public SSH key to your GitHub profile?

Take a look at the documentation if you need help with that process: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
