### ISSUE TITLE
TypeError: Cannot read property 'entries' of undefined

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1507]
https://haystack.githubapp.com/desktop/needles/ReyhJX1USeqUUEHOJ2K2bg

```
TypeError: Cannot read property 'entries' of undefined
at J.renderOrgs (file:///app/renderer.js:3:532032)
at J.render (file:///app/renderer.js:3:532773)
at ee._renderValidatedComponentWithoutOwnerOrContext (file:///app/renderer.js:3:105873)
at ee._renderValidatedComponent (file:///app/renderer.js:3:106009)
at ee._updateRenderedComponent (file:///app/renderer.js:3:105261)
at ee._performComponentUpdate (file:///app/renderer.js:3:105046)
at ee.updateComponent (file:///app/renderer.js:3:104248)
at ee.receiveComponent (file:///app/renderer.js:3:103301)
at Object.receiveComponent (file:///app/renderer.js:1:54097)
at Object.updateChildren (file:///app/renderer.js:3:97737)
```

**Comment by niik** [comment]
Seems like this is still occuring https://haystack.githubapp.com/desktop/needles/rOz6NRRj29rsAkGADdUIrQ

**Comment by niik** [comment]
Never mind me, that needle was for 0.5.3
