### ISSUE TITLE
GitHub Enterprise log in error

### ISSUE THREAD

**Issue by katiyar-pradeep** [desktop/desktop#15168]
### The problem

![image](https://user-images.githubusercontent.com/112002466/186696119-62a5905f-8d50-47c9-a11d-f4e64be456ac.png)

### Release version

Version 3.0.6 (x64)

### Operating system

Windows 10

### Log files

2022-08-25T05:35:30.435Z - info: [ui] [BranchPruner] Last prune took place 14 hours ago - skipping
2022-08-25T05:55:45.204Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.com/api/v3/meta' as a fallback
Error: API error https://github.com/api/v3/meta:  (404)
    at Bt (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\http.ts:178:11)
    at C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\api.ts:1688:11
    at or.endpointSupportsBasicAuth (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:255:11)
    at or.setEndpoint (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:549:13)
2022-08-25T14:42:27.147Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-08-25T14:42:32.746Z - info: [ui] [AppStore] loading 1 repositories from store
2022-08-25T14:42:32.769Z - info: [ui] [BranchPruner] Last prune took place 23 hours ago - skipping
2022-08-25T14:42:35.363Z - info: [ui] launching: 3.0.6 (Windows 10.0.19043)
2022-08-25T14:42:35.424Z - info: [ui] execPath: 'C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\GitHubDesktop.exe'
2022-08-25T14:42:36.747Z - info: [ui] Executing getConfigValueInPath: git config -z pull.rebase (took 1.017s)
2022-08-25T14:42:38.418Z - info: [ui] Executing getCommits: git log origin/main..main --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.669s)
2022-08-25T14:42:38.419Z - info: [ui] Executing getCommits: git log origin/main..main --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.771s)
2022-08-25T14:42:38.427Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 3.063s)
2022-08-25T14:42:38.429Z - info: [ui] Executing getStashEntries: git log -g -z --pretty=%gD%x1F%H%x1F%gs refs/stash (took 1.625s)
2022-08-25T14:42:38.429Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.594s)
2022-08-25T14:42:38.429Z - info: [ui] Executing getRemotes: git remote -v (took 1.658s)
2022-08-25T14:42:38.446Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.736s)
2022-08-25T14:42:38.447Z - info: [ui] Executing getRemotes: git remote -v (took 1.781s)
2022-08-25T14:42:38.448Z - info: [ui] Executing getStashEntries: git log -g -z --pretty=%gD%x1F%H%x1F%gs refs/stash (took 1.762s)
2022-08-25T14:42:40.742Z - info: [ui] Executing getChangesFiles: git log f777269f1cf792dd7465ac29c75df7abf323e76e -C -M -m -1 --no-show-signature --first-parent --raw --format=format: --numstat -z -- (took 1.945s)
2022-08-25T14:43:18.062Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.com/api/v3/meta' as a fallback
Error: API error https://github.com/api/v3/meta:  (404)
    at Bt (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\http.ts:178:11)
    at C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\api.ts:1688:11
    at or.endpointSupportsBasicAuth (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:255:11)
    at or.setEndpoint (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:549:13)
2022-08-25T14:43:45.153Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.com/api/v3/meta' as a fallback
Error: API error https://github.com/api/v3/meta:  (404)
    at Bt (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\http.ts:178:11)
    at C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\api.ts:1688:11
    at or.endpointSupportsBasicAuth (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:255:11)
    at or.setEndpoint (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:549:13)
2022-08-25T14:43:47.484Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.com/api/v3/meta' as a fallback
Error: API error https://github.com/api/v3/meta:  (404)
    at Bt (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\http.ts:178:11)
    at C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\api.ts:1688:11
    at or.endpointSupportsBasicAuth (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:255:11)
    at or.setEndpoint (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:549:13)
2022-08-25T14:43:59.232Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.com/api/v3/meta' as a fallback
Error: API error https://github.com/api/v3/meta:  (404)
    at Bt (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\http.ts:178:11)
    at C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\api.ts:1688:11
    at or.endpointSupportsBasicAuth (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:255:11)
    at or.setEndpoint (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:549:13)
2022-08-25T14:44:26.556Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.886s)
2022-08-25T14:44:27.963Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.406s)
2022-08-25T14:44:44.740Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.com/api/v3/meta' as a fallback
Error: API error https://github.com/api/v3/meta:  (404)
    at Bt (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\http.ts:178:11)
    at C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\api.ts:1688:11
    at or.endpointSupportsBasicAuth (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:255:11)
    at or.setEndpoint (C:\Users\pradeep.katiyar\AppData\Local\GitHubDesktop\app-3.0.6\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:549:13)

### Screenshots

![image](https://user-images.githubusercontent.com/112002466/186695853-9a255fc0-9bde-4efb-940b-5d5a0a314a27.png)

**Comment by sergiou87** [comment]
Hello @katiyar-pradeep!

If the repositories you're trying to access live within github.com (let's say `https://github.com/Lam-Research/my-awesome-repository`), you don't need to sign in as a GitHub Enterprise account.

You only need that if the repositories are hosted somewhere else (let's say `https://lamresearch.com/my-awesome-repository`).

I hope that helps!

**Comment by marknn3** [comment]
For anyone having this same issue. This solved it for me:
Use the GitHub.com Sign-in.
Even though you have an Enterprise account.
![image](https://github.com/desktop/desktop/assets/4366965/59eb9229-9f97-4f1b-b536-1634ef3feea8)
