### ISSUE TITLE
building on arm64 is a hassle

### ISSUE THREAD

**Issue by monomycelium** [desktop/desktop#15245]
### problem

here are the documentation for building on arm64 i've found so far:
source | date
---|---
official [`setup.md`](/desktop/desktop/blob/development/docs/contributing/setup.md) | 21 january 2022
official [`setup-linux.md`](https://github.com/desktop/desktop/blob/development/docs/contributing/setup-linux.md) | 13 may 2021
official [`building-arm64.md`](https://github.com/desktop/desktop/blob/development/docs/contributing/building-arm64.md) | 22 november 2018
shiftkey's [`setup.md`](https://github.com/shiftkey/desktop/blob/linux/docs/contributing/setup.md) | 21 january 2022
shiftkey's [`setup-linux.md`](https://github.com/shiftkey/desktop/blob/linux/docs/contributing/setup-linux.md) | 13 may 2021
shiftkey's [`building-arm64.md`](https://github.com/shiftkey/desktop/blob/linux/docs/contributing/building-arm64.md) | 22 november 2018

when i try to `yarn build:dev` on my arm64 mac running arch linux through the asahi kernel, i get this error:

```
Error: ENOENT: no such file or directory, stat '/home/mycelium/Documents/desktop/app/node_modules/dugite/git'
    at Object.statSync (node:fs:1551:3)
    at Object.statSync (/home/mycelium/Documents/desktop/node_modules/graceful-fs/polyfills.js:307:34)
    at statSync (/home/mycelium/Documents/desktop/node_modules/fs-extra/lib/util/stat.js:10:52)
    at getStatsSync (/home/mycelium/Documents/desktop/node_modules/fs-extra/lib/util/stat.js:24:19)
    at Object.checkPathsSync (/home/mycelium/Documents/desktop/node_modules/fs-extra/lib/util/stat.js:49:33)
    at copySync (/home/mycelium/Documents/desktop/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at copyDependencies (/home/mycelium/Documents/desktop/script/build.ts:353:11)
    at Object.<anonymous> (/home/mycelium/Documents/desktop/script/build.ts:74:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/home/mycelium/Documents/desktop/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/home/mycelium/Documents/desktop/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at Object.<anonymous> (/home/mycelium/Documents/desktop/node_modules/ts-node/src/bin.ts:147:12)
error Command failed with exit code 1.
```

the whole output: [error.log](https://github.com/desktop/desktop/files/9502866/error.log)

i know that i'm the one who did something wrong when building, but i followed all the build instructions in [building-arm64.md](https://github.com/desktop/desktop/blob/development/docs/contributing/building-arm64.md). when i cross-referenced to the general [setup.md](https://github.com/desktop/desktop/blob/258d0deacdfdf7b97ea1c08ca2bb9ce8d4f931d7/docs/contributing/setup.md#arm64-builds), i realised some version mismatches. i tried playing around with `node` versions using `nvm`, but the same error happened or some packages required a later version of node. my `python` version is set to `3.10`, which could be the problem.

### operating system

arch linux arm aarch64

### log files

the whole output: [error.log](https://github.com/desktop/desktop/files/9502866/error.log)

### additional context

i hope we could have more documentation on how to build on arm64 linux (and other distributions than fedora and debian, like arch linux).

**Comment by sergiou87** [comment]
Hello! The problem might be there is no arm64 builds of [dugite](https://github.com/desktop/dugite) / [dugite-native](https://github.com/desktop/dugite-native).

In any case, issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.

Sorry!

**Comment by monomycelium** [comment]
thank you for looking into this.

**Comment by swoopertr** [comment]
is there any solution for this problem?
