### ISSUE TITLE
Unable to connect to enterprise via GitHub Desktop

### ISSUE THREAD

**Issue by ET3117** [desktop/desktop#15315]
### The problem

Tried connecting via the GitHub Desktop application to my enterprise organization. Receive error message saying unable to connect.  
![image](https://user-images.githubusercontent.com/4107146/191085787-d25120b6-3b62-4faa-a0c0-659e7e99f9df.png)
![image](https://user-images.githubusercontent.com/4107146/191085852-01d80a9e-2c1c-4702-8f38-10bf8e98a6b7.png)

### Release version

3.0.8

### Operating system

Windows 10 Enterprise

### Steps to reproduce the behavior

From options, attempt to sign in to the GitHub enterprise (see images above) ... fails

### Log files

2022-09-19T18:18:51.393Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.com/api/v3/meta' as a fallback
Error: API error https://github.com/api/v3/meta:  (404)
    at Bt (C:\Users\r625216\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\http.ts:178:11)
    at C:\Users\r625216\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\api.ts:1688:11
    at or.endpointSupportsBasicAuth (C:\Users\r625216\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:255:11)
    at or.setEndpoint (C:\Users\r625216\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:549:13)
2022-09-19T18:18:54.664Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.com/api/v3/meta' as a fallback
Error: API error https://github.com/api/v3/meta:  (404)
    at Bt (C:\Users\r625216\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\http.ts:178:11)
    at C:\Users\r625216\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\api.ts:1688:11
    at or.endpointSupportsBasicAuth (C:\Users\r625216\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:255:11)
    at or.setEndpoint (C:\Users\r625216\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:549:13)
2022-09-19T18:18:55.631Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.com/api/v3/meta' as a fallback
Error: API error https://github.com/api/v3/meta:  (404)
    at Bt (C:\Users\r625216\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\http.ts:178:11)
    at C:\Users\r625216\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\api.ts:1688:11
    at or.endpointSupportsBasicAuth (C:\Users\r625216\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:255:11)
    at or.setEndpoint (C:\Users\r625216\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:549:13)

### Screenshots

![image](https://user-images.githubusercontent.com/4107146/191086894-4baca7f8-7332-4c79-b2fc-9eb81413a1c2.png)

![image](https://user-images.githubusercontent.com/4107146/191086954-a4b67fda-600a-4922-8c6c-af3d82abafea.png)

**Comment by steveward** [comment]
@ET3117 thanks for the issue. If you are using GitHub Enterprise Cloud you can log in under the `GitHub.com` section. Let me know if you have any further problems.
