### ISSUE TITLE
TypeError: Cannot read property 'action' of undefined

### ISSUE THREAD

**Issue by niik** [desktop/desktop#1532]
```
TypeError: Cannot read property 'action' of undefined
at EventEmitter.X.ipcRenderer.once (file:///app/renderer.js:1:41820)
    at Object.onceWrapper (events.js:290:19)
    at emitTwo (events.js:111:20)
    at EventEmitter.emit (events.js:191:7)
```

I'm guessing this is https://github.com/desktop/desktop/blob/4275f0c7352fe88cb3dfdc2136eb96223362a212/app/src/ui/main-process-proxy.ts#L65-L75 where we're unable to look up the item for some reason

**Comment by niik** [comment]
Reproduced.

1. Right click on a repository item to show its context menu (don't click on anything)
2. Right click on a file item and click on anything but the first menu item

:boom:

In step one we subscribe to the 'contextual-menu-item' event once but since we never click on anything that event never fires

In step two we subscribe again (making us the second in line for that event) and but when we click and the event fires our first handler gets the call and is unable to look up the item in its closed-over items array.

**Comment by niik** [comment]
> event fires our first handler gets the call and is unable to look up the item in its closed-over items array.

And I should add that the event then propagates to the second caller so you can end up in some really weird situation with this. If you turn off repository removal confirmation and follow the steps above but in the second step you click on the first item in whatever context menu you'll remove the repository _and_ invoke whatever action the second context menu wanted to invoke.

In other words, each time you open a context menu you queue up an action that will possibly run when you click on a context menu item in the future.
