### ISSUE TITLE
Unable to sign in using my browser

### ISSUE THREAD

**Issue by TatendaDhliwayo** [desktop/desktop#15331]
### The problem

When I try to sign in to my GitHub .com account on my desktop app to access my repositories it just keeps loading but nothing happens. It asked to authorize on the browser but after I confirm nothing happens.. no redirecting...
![sign in to github](https://user-images.githubusercontent.com/109549134/191633413-d3f7f68d-6644-4c0f-8a11-7d9dd493efd8.JPG)

### Release version

Version 3.0.8 (x64)

### Operating system

Windows 10 Pro

### Log files

2022-09-21T23:54:45.511Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\Admin\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at te (C:\Users\Admin\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\Admin\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\Admin\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\main-process\notifications.ts:28:32
    at C:\Users\Admin\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\main-process\main.ts:710:7
    at Object.<anonymous> (C:\Users\Admin\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\main-process\main.ts:710:7)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
2022-09-21T23:54:45.529Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\Admin\Desktop\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at te (C:\Users\Admin\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\Admin\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\Admin\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\main-process\notifications.ts:28:32
    at C:\Users\Admin\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\main-process\main.ts:710:7
    at Object.<anonymous> (C:\Users\Admin\AppData\Local\SquirrelTemp\webpack:\[name]\app\src\main-process\main.ts:710:7)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
2022-09-21T23:54:45.529Z - error: [main] Toast activator CLSID not found in any of the shortcuts. Falling back to known CLSIDs.
2022-09-21T23:54:45.529Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-09-21T23:54:47.238Z - info: [main] Received possible protocol arguments: 2
2022-09-21T23:54:47.244Z - error: [main] Malformed launch arguments received: C:\Users\Admin\AppData\Local\GitHubDesktop\app-3.0.8\GitHubDesktop.exe,--squirrel-firstrun
2022-09-21T23:54:47.244Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-09-21T23:54:48.353Z - info: [ui] [AppStore] loading 0 repositories from store
2022-09-21T23:54:48.510Z - info: [ui] Opt in reported.
2022-09-21T23:54:48.562Z - info: [ui] launching: 3.0.8 (Windows 10.0.19044)
2022-09-21T23:54:48.563Z - info: [ui] execPath: 'C:\Users\Admin\AppData\Local\GitHubDesktop\app-3.0.8\GitHubDesktop.exe'
2022-09-21T23:54:48.847Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-09-21T23:54:49.340Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-09-21T23:54:49.663Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.124s)
2022-09-21T23:55:25.448Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
2022-09-21T23:55:25.450Z - info: [ui] [SignInStore] initializing OAuth flow
2022-09-21T23:55:25.451Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=f68c8d54-a208-4edb-8179-08ff54a6adae
2022-09-21T23:55:25.451Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2022-09-21T23:55:25.660Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2022-09-21T23:55:36.057Z - info: [main] Received possible protocol arguments: 4
2022-09-21T23:55:36.058Z - info: [main] Processing protocol url
2022-09-21T23:55:36.067Z - info: [ui] [Dispatcher] requesting authenticated user
2022-09-21T23:55:36.069Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2022-09-21T23:55:36.084Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2022-09-21T23:55:36.890Z - info: [ui] [SignInStore] account resolved
2022-09-21T23:55:36.891Z - info: [ui] [AppStore] adding account TatendaDhliwayo (TatendaDhliwayo) to store
2022-09-21T23:55:36.892Z - error: [ui] Error adding account 'TatendaDhliwayo'
Error: Not enough memory resources are available to process this command.

2022-09-21T23:55:36.901Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2022-09-21T23:55:36.933Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-09-21T23:59:27.085Z - info: [ui] [AppStore] adding repository at C:\Users\Admin\Documents\GitHub\100-Days-of-Code to store

### Screenshots

![sign in to github](https://user-images.githubusercontent.com/109549134/191633693-7d4cbec8-105b-4ac7-93aa-a8088fff4394.JPG)

**Comment by sergiou87** [comment]
Hello! That's usually related to having too many credentials stored in the Windows Credentials Manager. Please, take a look at this document which should contain the solution/workaround to your problem: https://github.com/desktop/desktop/blob/development/docs/known-issues.md#not-enough-resources-error-when-signing-in
