### ISSUE TITLE
3.0.8 completely stopped working (presumably after update) - Win 7

### ISSUE THREAD

**Issue by BrainAnnex** [desktop/desktop#15344]
### The problem

Errors galore, no matter what I do!  But until very recently it worked perfectly.  Maybe an update broke it??

It keeps saying that it cannot find the local repo, even though it's in the same place it has always been! 
![desktop3](https://user-images.githubusercontent.com/41893046/191891064-0cd0f1df-ed62-4322-bb07-51cbceb76e9d.PNG)

If I manually locate that folder, it gives this error:

![desktop](https://user-images.githubusercontent.com/41893046/191890888-4bd3b12c-2de5-4f6b-a18d-a20fd37963df.PNG)

Even trying to update GitHub Desktop hangs up for a long time and then generates this "helpful" error:
![desktop2](https://user-images.githubusercontent.com/41893046/191890962-d2f754b5-786f-4ade-80d4-5579350e6242.PNG)

The remote repository, on GitHub, is just fine. (https://github.com/BrainAnnex/life123)

I'm on Win7.  Rebooting didn't help.  Switching to another local repository gives the same errors.  Something is profoundly broken!

### Release version

3.0.8 (x64)

### Operating system

Win 7

### Steps to reproduce the behavior

Simply starting the program

### Log files

2022-09-23T04:07:00.988Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-09-23T04:07:01.736Z - info: [ui] [AppStore] loading 4 repositories from store
2022-09-23T04:07:01.736Z - info: [ui] [AppStore] found account: BrainAnnex (Julian West)
2022-09-23T04:07:01.899Z - error: [ui] `git rev-parse --is-bare-repository --show-cdup` exited with an unexpected code: 1.
stderr:
error launching git: The system cannot find the path specified.

2022-09-23T04:07:01.960Z - error: [ui] `git rev-parse --is-bare-repository --show-cdup` exited with an unexpected code: 1.
stderr:
error launching git: The system cannot find the path specified.

2022-09-23T04:07:01.973Z - error: [ui] `git rev-parse --is-bare-repository --show-cdup` exited with an unexpected code: 1.
stderr:
error launching git: The system cannot find the path specified.

2022-09-23T04:07:01.995Z - info: [ui] launching: 3.0.8 (Windows 6.1.7601)
2022-09-23T04:07:01.996Z - info: [ui] execPath: 'C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\GitHubDesktop.exe'
2022-09-23T04:07:02.092Z - error: [ui] `git lfs install --skip-repo` exited with an unexpected code: 1.
stderr:
error launching git: The system cannot find the path specified.

2022-09-23T04:07:02.244Z - info: [ui] Subscribed 'BrainAnnex' to Alive channel
2022-09-23T04:07:02.387Z - error: [ui] `git remote -v` exited with an unexpected code: 1.
stderr:
error launching git: The system cannot find the path specified.

2022-09-23T04:07:10.893Z - error: [ui] `git rev-parse --is-bare-repository --show-cdup` exited with an unexpected code: 1.
stderr:
error launching git: The system cannot find the path specified.

2022-09-23T04:07:42.422Z - error: [ui] `git rev-parse --is-bare-repository --show-cdup` exited with an unexpected code: 1.
stderr:
error launching git: The system cannot find the path specified.

2022-09-23T04:07:42.597Z - error: [ui] `git remote -v` exited with an unexpected code: 1.
stderr:
error launching git: The system cannot find the path specified.

2022-09-23T04:07:42.598Z - error: [ui] `git remote -v` exited with an unexpected code: 1.
stderr:
error launching git: The system cannot find the path specified.

2022-09-23T04:07:42.622Z - info: [ui] [BranchPruner] Last prune took place 23 hours ago - skipping
2022-09-23T04:07:42.626Z - error: [ui] `git for-each-ref --format=%00%(refname)%00%(objectname)%00%(upstream)%00%(symref)%00%(HEAD)%00 refs/heads refs/remotes` exited with an unexpected code: 1.
stderr:
error launching git: The system cannot find the path specified.

2022-09-23T04:07:43.155Z - error: [ui] Branch fast-forwarding failed
GitError: error launching git: The system cannot find the path specified.

    at C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\git\core.ts:247:11
    at C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\trampoline\trampoline-environment.ts:40:13
    at C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\trampoline\trampoline-tokens.ts:33:5
    at C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\git\for-each-ref.ts:90:9
    at or.fastForwardBranches (C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\stores\app-store.ts:4388:13)
    at C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\stores\app-store.ts:4713:18
    at or.withPushPullFetch (C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\stores\app-store.ts:4241:5)
    at or.performFetch (C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\stores\app-store.ts:4677:5)
    at _o.performAndScheduleFetch (C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2022-09-23T04:07:43.218Z - error: [ui] `git rev-parse --is-bare-repository --show-cdup` exited with an unexpected code: 1.
stderr:
error launching git: The system cannot find the path specified.

2022-09-23T04:07:43.229Z - error: [ui] `git rev-parse --is-bare-repository --show-cdup` exited with an unexpected code: 1.
stderr:
error launching git: The system cannot find the path specified.

2022-09-23T04:08:16.428Z - error: [ui] `git rev-parse --is-bare-repository --show-cdup` exited with an unexpected code: 1.
stderr:
error launching git: The system cannot find the path specified.

2022-09-23T04:08:51.864Z - error: [ui] Error checking for updates
undefined: 
2022-09-23T04:09:07.067Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 4 repositories took 0.0s of which 0.0s paused, total 0.0s
2022-09-23T04:11:54.412Z - error: [ui] Error checking for updates
undefined: 
2022-09-23T04:15:44.246Z - info: [main] opening in browser: https://github.com/BrainAnnex/life123
2022-09-23T04:16:27.209Z - info: [ui] [BranchPruner] Last prune took place 23 hours ago - skipping
2022-09-23T04:16:27.231Z - error: [ui] Branch fast-forwarding failed
Error: Git could not be found at the expected path: 'C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\resources\app\git\cmd\git.exe'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\webpack:\[name]\app\node_modules\dugite\build\lib\git-process.js:119:39
    at exithandler (node:child_process:415:5)
    at ChildProcess.errorhandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:526:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-09-23T04:19:25.177Z - error: [ui] Error checking for updates
undefined:

**Comment by sergiou87** [comment]
> Error: Git could not be found at the expected path: 'C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\resources\app\git\cmd\git.exe'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.

This looks bad 😕 Could you check if git.exe is still in that path? If it doesn't, users usually have that problem when their antivirus removes or puts certain GitHub Desktop files in quarantine 😢 

Please, take a look at let us know! Maybe just reinstalling GitHub Desktop will just fix the issue 🤞

**Comment by BrainAnnex** [comment]
Thanks for getting back to me quickly!  Those files are indeed gone!
This is what my folder `C:\Users\juls\AppData\Local\GitHubDesktop\app-3.0.8\resources\app` looks like:
![3 0 8 folder](https://user-images.githubusercontent.com/41893046/192064070-0ba9c6e9-ca55-4fa2-8773-55e3e14df9fc.PNG)
**No trace of the subfolders/file you mentioned!**  :o

By contrast, the same folder in the previous version 3.0.7 : 
![3 0 7 folder](https://user-images.githubusercontent.com/41893046/192064171-c146aef8-a06d-45c3-a854-1764242be01c.PNG)

It'd seem that the update to 3.0.8 got botched.  I didn't get any notification from the antivirus (ESET)... so, I doubt it's the cause.

I have a nagging suspicious that 3.0.8 is problematic...  but let me try re-installing it...

**Comment by BrainAnnex** [comment]
All good :smiley:  I uninstalled and re-installed : "like new" now!  (3.0.8)
