### ISSUE TITLE
Discard changes fails on network drive

### ISSUE THREAD

**Issue by Plankokan** [desktop/desktop#15559]
### The problem

Hello,
I have several git projects on a network drive on a windows 11 machine. When trying to discard changes, the following error occurs:

```
2022-11-03T15:58:17.027Z - error: [ui] Failed discarding changes
GitError: /mingw64/libexec/git-core/git-sh-setup: line 365: cd: .git: Not a directory
Unable to determine absolute path of git directory

    at C:\ProgramData\plank\GitHubDesktop\app-3.1.3-beta2\webpack:\[name]\app\src\lib\git\core.ts:247:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at C:\ProgramData\plank\GitHubDesktop\app-3.1.3-beta2\webpack:\[name]\app\src\lib\trampoline\trampoline-environment.ts:40:13
    at C:\ProgramData\plank\GitHubDesktop\app-3.1.3-beta2\webpack:\[name]\app\src\lib\trampoline\trampoline-tokens.ts:33:5
    at C:\ProgramData\plank\GitHubDesktop\app-3.1.3-beta2\webpack:\[name]\app\src\lib\git\submodule.ts:24:19
    at ws.discardChanges (C:\ProgramData\plank\GitHubDesktop\app-3.1.3-beta2\webpack:\[name]\app\src\lib\stores\git-store.ts:1497:11)
    at ar._discardChanges (C:\ProgramData\plank\GitHubDesktop\app-3.1.3-beta2\webpack:\[name]\app\src\lib\stores\app-store.ts:4599:5)
2022-11-03T15:58:27.766Z - error: [ui] `git submodule status --` exited with an unexpected code: 1.
stderr:
/mingw64/libexec/git-core/git-sh-setup: line 365: cd: .git: Not a directory
Unable to determine absolute path of git directory
```

The GUI error shows the following:

`/mingw64/libexec/git-core/git-sh-setup: line 365: cd: .git: Not a directory
Unable to determine absolute path of git directory`

This happens for single files as well as the option to discard all changes.

However, it is possible to fetch und push without this error. It seems to only occur when trying to discard changes.

Error occurs on stable version as well as on the mentioned beta version.

Any idea, what could be wrong here?

### Release version

Version 3.1.3-beta2 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Make a change to the local repository
2. Right click on changed file
3. Click on discard changes 

### Log files

2022-11-03T15:58:17.027Z - error: [ui] Failed discarding changes
GitError: /mingw64/libexec/git-core/git-sh-setup: line 365: cd: .git: Not a directory
Unable to determine absolute path of git directory

    at C:\ProgramData\plank\GitHubDesktop\app-3.1.3-beta2\webpack:\[name]\app\src\lib\git\core.ts:247:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at C:\ProgramData\plank\GitHubDesktop\app-3.1.3-beta2\webpack:\[name]\app\src\lib\trampoline\trampoline-environment.ts:40:13
    at C:\ProgramData\plank\GitHubDesktop\app-3.1.3-beta2\webpack:\[name]\app\src\lib\trampoline\trampoline-tokens.ts:33:5
    at C:\ProgramData\plank\GitHubDesktop\app-3.1.3-beta2\webpack:\[name]\app\src\lib\git\submodule.ts:24:19
    at ws.discardChanges (C:\ProgramData\plank\GitHubDesktop\app-3.1.3-beta2\webpack:\[name]\app\src\lib\stores\git-store.ts:1497:11)
    at ar._discardChanges (C:\ProgramData\plank\GitHubDesktop\app-3.1.3-beta2\webpack:\[name]\app\src\lib\stores\app-store.ts:4599:5)
2022-11-03T15:58:27.766Z - error: [ui] `git submodule status --` exited with an unexpected code: 1.
stderr:
/mingw64/libexec/git-core/git-sh-setup: line 365: cd: .git: Not a directory
Unable to determine absolute path of git directory

### Screenshots

![image](https://user-images.githubusercontent.com/91032635/199773426-1799bbb7-dcc2-4fa3-b9f7-300725beaba5.png)

**Comment by steveward** [comment]
Thanks for the report @Plankokan. I'll take a look and see if I can reproduce this issue. For reference this is a reported issue with discarding changes for [repositories hosted in WSL ](https://github.com/desktop/desktop/issues/14244), but that doesn't seem to surface an error.

**Comment by steveward** [comment]
@Plankokan I took a look at this issue and was unable to reproduce the specific error you are encountering, but I did hit the issue where the changes were unable to be discarded (like the WSL issue I linked above). This is specifically in an NFS network share on Windows 11. I previously had [tested this](https://github.com/desktop/desktop/issues/14244#issuecomment-1082129591) in March and discarding changes on a network drive did work even though WSL failed, so it seems like this has regressed since then. I'll label this as a bug for the team to investigate.
