### ISSUE TITLE
Unable to sign in Github Enterprise

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#15599]
### The problem

When i try to sign in from Github Desktop , i got below screenshot error.

### Release version

3.1.2

### Operating system

Windows 11

### Log files

2022-11-10T15:21:55.970Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.com/api/v3/meta' as a fallback
Error: API error https://github.com/api/v3/meta:  (404)
    at Bt (C:\Users\sivagurunathan.s02\AppData\Local\GitHubDesktop\app-3.1.2\webpack:\[name]\app\src\lib\http.ts:178:11)
    at C:\Users\sivagurunathan.s02\AppData\Local\GitHubDesktop\app-3.1.2\webpack:\[name]\app\src\lib\api.ts:1688:11
    at or.endpointSupportsBasicAuth (C:\Users\sivagurunathan.s02\AppData\Local\GitHubDesktop\app-3.1.2\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:255:11)
    at or.setEndpoint (C:\Users\sivagurunathan.s02\AppData\Local\GitHubDesktop\app-3.1.2\webpack:\[name]\app\src\lib\stores\sign-in-store.ts:549:13)

### Screenshots

<img width="295" alt="image" src="https://user-images.githubusercontent.com/117800341/201140303-e95054ec-065f-48fc-bbd1-3d0be91c392b.png">

**Comment by steveward** [comment]
@sivagurunathan-s-infy thanks for the issue. It looks like you may be trying to sign into a GitHub or GitHub Enterprise Cloud account -- you should be able to sign directly into the github.com section if that is the case. Let me know if that does not get things working for you!
