### ISSUE TITLE
An annoying modal window which appears on every check for updates when there is no internet connection

### ISSUE THREAD

**Issue by angezid** [desktop/desktop#16057]
### The problem

It popped up even if the program was checked for update 5 second ago.
It becomes appeared after last update on 01.02.2023.

### Release version

1.3.5

### Operating system

Windows 7

### Log files

2023-02-03T10:52:33.689Z - warn: [ui] failed fetching open PRs for repository angezid/Markjs-playground
TypeError: Failed to fetch
    at Nt (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\http.ts:152:10)
    at Rn.request (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\api.ts:1408:28)
    at Rn.fetchAll (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\api.ts:1379:45)
    at Rn.fetchAllOpenPullRequests (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\api.ts:938:25)
    at aL.constructor.fetchAndStoreOpenPullRequests (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\stores\pull-request-store.ts:110:28)
    at aL.constructor.fetchAndStorePullRequests (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\stores\pull-request-store.ts:99:19)
    at Object.refreshPullRequests (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\stores\pull-request-coordinator.ts:160:45)
2023-02-03T10:52:33.690Z - error: [ui] Error refreshing pull requests for 'angezid/Markjs-playground'
TypeError: Failed to fetch
    at Nt (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\http.ts:152:10)
    at Rn.request (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\api.ts:1408:28)
    at Rn.fetchAll (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\api.ts:1379:45)
    at Rn.fetchAllOpenPullRequests (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\api.ts:938:25)
    at aL.constructor.fetchAndStoreOpenPullRequests (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\stores\pull-request-store.ts:110:28)
    at aL.constructor.fetchAndStorePullRequests (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\stores\pull-request-store.ts:99:19)
    at Object.refreshPullRequests (C:\Users\.\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\stores\pull-request-coordinator.ts:160:45)

### Screenshots

![window](https://user-images.githubusercontent.com/82150610/216580620-bf011d4c-504a-49e6-a1f7-37f1cb134491.png)

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Explorer`.

The log files are created daily -- please upload a log file as an attachment from today, thanks!

**Comment by angezid** [comment]
I found this in the changelog.json:
"3.1.5": 
"[Improved] Always show an error message when an update fails - #15530"

**Comment by tidy-dev** [comment]
👋 @angezid, The only change made for that was that if an error occurred without an error message, it provides it with the "Checking for updates failed" message you are seeing. Otherwise, it would have been behaving the same way except your modal would be just the error icon and no message. 

I just tested what would happen if I check for updates and did not have an internet connection; and I received the expected error message.

![image](https://user-images.githubusercontent.com/75402236/216639557-4d6cd6c8-f3e9-48b7-ac50-3c0b43117972.png)

The scenario I found that resulted in an empty error message (that prompted the referenced PR) was when I attempted to download the update and my machine did not have enough space to download the update.  Could that apply to you? 

Additionally, would appreciate if you could upload the entire log for the day as asked for above - there could be additional errors may help indicate the problem :)

**Comment by angezid** [comment]
[2023-02-03.desktop.production.log](https://github.com/desktop/desktop/files/10580526/2023-02-03.desktop.production.log)

I close Desktop, disconnect the Internet, rename old log file in order to create new one, launch Desktop, close pop up window, and upload log file.

I agree, this failed for updates window is normal if I am manually checking for an update, but not on every launch.

By the way, I found that version 3.1.4 is not deleted and launch GitHubDesktop.exe. There is no any pop up window on launch.

**Comment by tidy-dev** [comment]
Thank you for those logs. Unfortunately, no additionally error was provided. However, it does clearly confirm you are not getting the correct internet connection error which would suggest to me something else in the checking for updates process is failing first.

Sometimes users get a partial/incomplete update and we get strange behavior.
Could you try a fresh install?

Here's how to do that:
- Close GitHub Desktop
- Open File Explorer
- Go to %LocalAppData% and delete the GitHubDesktop directory
- Go to %AppData% and delete the GitHub Desktop directory
- Reinstall GitHub Desktop from http://desktop.github.com/

Other notes:
> but not on every launch

The app does check for updates every time you open it or if it is left open on a 4 hr interval.

**Comment by angezid** [comment]
I restart Windows, rename both `GitHubDesktop` and `GitHub Desktop` directories, install fresh GitHub Desktop from given URL - the same pop-up window on launch.

**Comment by angezid** [comment]
The program become work as usual when I reverted '15530' improvement (it was found 'GitHubDesktop\app-3.1.5\resources\app\renderer.js' file, changed `this.props.dispatcher.postError(t?e:new Error("Checking for updates failed."))` to `this.props.dispatcher.postError(e)`).
	
When I manually try to check for update, the window without message was showed.

**Comment by tidy-dev** [comment]
Curious. I would expect the same behavior whether initiated through  the daily auto update logic or the manual check for update. It sounds as tho in both situations you are receiving an "empty" error (also strange for your scenario/I cannot reproduce).. and, for auto-update logic it is somehow ignoring the error. Ideally.. we don't want errors to be ignored altogether; tho, I could see reasoning for the auto-updater spurred errors to be logged silently as to not the annoy the user in a scenario such as yours where that would popup everyday the internet is disconnected. Going to mark as a bug to get further investigation; tho hesitant to revert that change altogether.

**Comment by angezid** [comment]
As it's turned out, this window is popped up on every check for update.
When I change the update time to 2.4 minutes, the pop-up window becomes appeared every 2.4 minutes. When the program is in the background, these windows are accumulated.

**Comment by jeffpapp** [comment]
Even after updating to 3.1.8 I am still getting the `Checking for updates failed` every morning if I leave the GitHub Desktop app open overnight and my computer goes into sleep mode.  It seems like it checks right when the computer wakes up but maybe the network hasn't fully resolved yet?  Is it possible to add some kind of delay in there?

**Comment by r3faat1** [comment]
Same issue "Checking for updates failed" every morning. It's a harmless error but still annoying. My regular update works fine normally.

**Comment by AnthonyOvermatch** [comment]
Just wanted to echo that I've been experiencing this message every morning as well. I tend to leave my work machine on overnight so it just enters sleep mode.

**Comment by killroy42** [comment]
Still happening in v3.2.0. Not sure why it got closed :(

**Comment by abelbraaksma** [comment]
When is the fix, assuming the revert is the fix, be released? I just clicked a few dozen of these messages away, as they overlay on one another (which, to be fair, seems to be a bug on its own: do not show the model dialog on top of itself).

Version 3.2.0 clearly doesn't have this fix in it yet (see: https://desktop.github.com/release-notes/).

**Comment by abelbraaksma** [comment]
Ok, I just tried the beta build, @tidy-dev, as mentioned in this thread, it wouldn't fix the bug to revert that issue, instead it just now shows an empty  message:

<img src="https://user-images.githubusercontent.com/16015770/229159500-12cb1d5c-a076-45cf-973e-6c045e302fd6.png" width="300px"/>

However, it does seem to fix the annoying "always showing an error message when starting GD, or on opening your laptop". As if there's something in the code that ignores that message when it is empty.

Pressing "check for updates" manually in the `About` box leads to showing the above empty box.

**Comment by rrjat4840** [comment]
https://h25.in/super/vibyor?f=w&p=default&l=hi&tp=super1

Jechaport lucky teen Patti

**Comment by rrjat4840** [comment]
> https://h25.in/super/vibyor?f=w&p=default&l=hi&tp=super1
> 
> Jechaport lucky teen Patti

Coding

**Comment by steveward** [comment]
Reopening since https://github.com/desktop/desktop/issues/17358 was reported.
