### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by 1anuraggupta** [desktop/desktop#16072]
### The problem

I'm unable to login in windows github with valid credentials

### Release version

Version 3.1.5 (x64)

### Operating system

Windoes

### Steps to reproduce the behavior

Pull origin
Enter username - angupta@innominds.com
password - 
Save and retry

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

Is the project you're working with hosted on GItHub.com, or a GitHub Enterprise Server? Or is this a third party Git service like bitbucket/gitlab/etc?

Thanks!

**Comment by Tony-TL** [comment]
2023-02-07T06:55:00.357Z - warn: [ui] Failed trying to find Git on PATH
Error: Command failed: C:\Windows\System32\where.exe git
INFO: Could not find files for the given pattern(s).

    at ChildProcess.exithandler (node:child_process:408:12)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2023-02-07T06:55:04.288Z - info: [ui] [SignInStore] initializing OAuth flow
2023-02-07T06:55:04.289Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=b42c2da7-3ef0-4aee-a95a-3ac638f7dc46
2023-02-07T06:56:10.675Z - info: [main] Received possible protocol arguments: 4
2023-02-07T06:56:10.676Z - info: [main] Processing protocol url
2023-02-07T06:56:10.685Z - info: [ui] [Dispatcher] requesting authenticated user
2023-02-07T06:56:15.700Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
Error: Hello there, wayfaring stranger. If you’re reading this then you probably didn’t see our blog post a couple of years back announcing that this API would go away: http://git.io/17AROg Fear not, you should be able to get what you need from the shiny new Events API instead.
    at Ft (C:\Users\TonyTong\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\http.ts:178:11)
    at Rn.fetchAccount (C:\Users\TonyTong\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\api.ts:820:7)
    at _n (C:\Users\TonyTong\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\api.ts:1664:11)
    at Object.dispatchURLAction (C:\Users\TonyTong\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\ui\dispatcher\dispatcher.ts:1799:17)
2023-02-07T06:56:15.700Z - warn: [ui] fetchUser: failed with endpoint https://api.github.com
Error: Hello there, wayfaring stranger. If you’re reading this then you probably didn’t see our blog post a couple of years back announcing that this API would go away: http://git.io/17AROg Fear not, you should be able to get what you need from the shiny new Events API instead.
    at Ft (C:\Users\TonyTong\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\http.ts:178:11)
    at Rn.fetchAccount (C:\Users\TonyTong\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\api.ts:820:7)
    at _n (C:\Users\TonyTong\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\api.ts:1664:11)
    at Object.dispatchURLAction (C:\Users\TonyTong\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\ui\dispatcher\dispatcher.ts:1799:17)
2023-02-07T06:56:15.700Z - info: [ui] [SignInStore] error with OAuth flow
Error: Hello there, wayfaring stranger. If you’re reading this then you probably didn’t see our blog post a couple of years back announcing that this API would go away: http://git.io/17AROg Fear not, you should be able to get what you need from the shiny new Events API instead.
    at Ft (C:\Users\TonyTong\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\http.ts:178:11)
    at Rn.fetchAccount (C:\Users\TonyTong\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\api.ts:820:7)
    at _n (C:\Users\TonyTong\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\lib\api.ts:1664:11)
    at Object.dispatchURLAction (C:\Users\TonyTong\AppData\Local\GitHubDesktop\app-3.1.5\webpack:\[name]\app\src\ui\dispatcher\dispatcher.ts:1799:17)

**Comment by niik** [comment]
Hey @Tony-TL, thanks for sending that over. It would appear that when we attempt to make a request to `api.github.com` that gets resolved to an IP address associated with `github.com`, not `api.github.com`. After that GitHub.com performs an http redirect to `https://github.com/user` instead of `https://api.github.com/user` where the former is a deprecated endpoint.

I've simulated this below by making a request to https://api.github.com/user while overriding the resolved IP of `api.github.com` to be what `github.com` resolved to on my machine.

```shellsession
% curl 'https://api.github.com/user' \
  -H 'authority: api.github.com' \
  -H 'accept: application/vnd.github.v3+json, application/json' \
  -H 'content-type: application/json' \  
  --resolve api.github.com:443:140.82.121.4 \
  -D -
HTTP/2 301 
content-length: 0
location: https://github.com/user
```

Unfortunately there's not much we can do here. We've seen this error a [number of times from users based in China](https://github.com/desktop/desktop/issues?q=is%3Aissue+wayfaring+is%3Aclosed) and it appears someone is providing incorrect IP addresses when resolving `api.github.com`.

Are you able to try a VPN or manually [set the IP address of api.github.com](https://www.liquidweb.com/kb/dns-hosts-file/) on your machine to [a valid address](https://www.nslookup.io/domains/api.github.com/dns-records/) (note that this approach will need to be updated from time to time)?

I'm afraid I'm going to have to close this issue as this isn't an error within Desktop itself but I'm happy to continue helping to troubleshoot and work around this.
