### ISSUE TITLE
Github Desktop won't open

### ISSUE THREAD

**Issue by mniesen** [desktop/desktop#16164]
### The problem

Hi, if I install GitHub desktop the program will not open and githubdesktop.exe will use 2GB of ram and this will increase very fast to 3GB and more. Sometimes if I am able to install GitHub Desktop the app will freeze after some time (max an hour). After opening the githubdesktop.exe via cmd I noticed multiple errors. I am sad to mention that I have real bad experience with electron apps, only Visual Studio Code works continuously. Postman, Insomnia, GitHub Desktop, the previous versions of the WhatsApp desktop app and more stop working after some time. I am using folder redirection (this is a feautre in windows by microsoft) on my roaming appdata folder. This means that my roaming appdata is not on my local computer but on a network share. I see that some file and folders are searched in roaming appdata under my user's folder. These folder aren't there because they are on a network share. In my own electron apps that I made I use the appdata environment variable without any problems.

The output of running GithubDesktop.exe via cmd:
```[desktop-notifications] [error] Failed to initialize with RO_INIT_MULTITHREADED: -2147417850
error: [main] Error looking for toast activator CLSID in shortcut C:\Users\MyUserName\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at te (C:\Users\MyUserName\AppData\Local\GitHubDesktop\app-3.1.7\webpack:\[name]\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\MyUserName\AppData\Local\GitHubDesktop\app-3.1.7\webpack:\[name]\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\MyUserName\AppData\Local\GitHubDesktop\app-3.1.7\webpack:\[name]\app\src\main-process\notifications.ts:28:32
    at C:\Users\MyUserName\AppData\Local\GitHubDesktop\app-3.1.7\webpack:\[name]\app\src\main-process\main.ts:712:7
    at Object.<anonymous> (C:\Users\MyUserName\AppData\Local\GitHubDesktop\app-3.1.7\webpack:\[name]\app\src\main-process\main.ts:712:7)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
error: [main] Error looking for toast activator CLSID in shortcut C:\Users\MyUserName\Desktop\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at te (C:\Users\MyUserName\AppData\Local\GitHubDesktop\app-3.1.7\webpack:\[name]\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\MyUserName\AppData\Local\GitHubDesktop\app-3.1.7\webpack:\[name]\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\MyUserName\AppData\Local\GitHubDesktop\app-3.1.7\webpack:\[name]\app\src\main-process\notifications.ts:28:32
    at C:\Users\MyUserName\AppData\Local\GitHubDesktop\app-3.1.7\webpack:\[name]\app\src\main-process\main.ts:712:7
    at Object.<anonymous> (C:\Users\MyUserName\AppData\Local\GitHubDesktop\app-3.1.7\webpack:\[name]\app\src\main-process\main.ts:712:7)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
error: [main] Toast activator CLSID not found in any of the shortcuts. Falling back to known CLSIDs.
[12724:0218/154236.413:ERROR:quota_database.cc(836)] Could not open the quota database, resetting.
[12724:0218/154236.515:ERROR:quota_database.cc(836)] Could not open the quota database, resetting.
[12724:0218/154236.580:ERROR:quota_database.cc(838)] Failed to reset the quota database.
[12724:0218/154236.580:ERROR:quota_database.cc(838)] Failed to reset the quota database.
[12724:0218/154236.755:ERROR:leveldb_factory.cc(88)] Failed to open LevelDB database from \\TheNameOfTheServer\fldrredir$\MyUserName\AppData\Roaming\GitHub Desktop\IndexedDB\file__0.indexeddb.leveldb,IO error: \\TheNameOfTheServer\fldrredir$\MyUserName\AppData\Roaming\GitHub Desktop\IndexedDB\file__0.indexeddb.leveldb/MANIFEST-000001: FILE_ERROR_FAILED (ChromeMethodBFE: 6::WritableFileSync::1)
[12724:0218/154236.848:ERROR:leveldb_factory.cc(88)] Failed to open LevelDB database from \\TheNameOfTheServer\fldrredir$\MyUserName\AppData\Roaming\GitHub Desktop\IndexedDB\file__0.indexeddb.leveldb,IO error: \\TheNameOfTheServer\fldrredir$\MyUserName\AppData\Roaming\GitHub Desktop\IndexedDB\file__0.indexeddb.leveldb/MANIFEST-000001: FILE_ERROR_FAILED (ChromeMethodBFE: 6::WritableFileSync::1)
error: [ui] PullRequestCoordinator: Error loading repositories
OpenFailedError: UnknownError Internal error opening backing store for indexedDB.open.
 UnknownError: Internal error opening backing store for indexedDB.open.
    at pm.create (file:///C:/Users/MyUserName/AppData/Local/GitHubDesktop/app-3.1.7/resources/app/renderer.js:2:1022838)
    at file:///C:/Users/MyUserName/AppData/Local/GitHubDesktop/app-3.1.7/resources/app/renderer.js:2:1037201
    at file:///C:/Users/MyUserName/AppData/Local/GitHubDesktop/app-3.1.7/resources/app/renderer.js:2:1000943
    at Qd (file:///C:/Users/MyUserName/AppData/Local/GitHubDesktop/app-3.1.7/resources/app/renderer.js:2:995658)
    at rf (file:///C:/Users/MyUserName/AppData/Local/GitHubDesktop/app-3.1.7/resources/app/renderer.js:2:996417)
    at tf (file:///C:/Users/MyUserName/AppData/Local/GitHubDesktop/app-3.1.7/resources/app/renderer.js:2:996268)
[12724:0218/154236.962:ERROR:leveldb_factory.cc(88)] Failed to open LevelDB database from \\TheNameOfTheServer\fldrredir$\MyUserName\AppData\Roaming\GitHub Desktop\IndexedDB\file__0.indexeddb.leveldb,IO error: \\TheNameOfTheServer\fldrredir$\MyUserName\AppData\Roaming\GitHub Desktop\IndexedDB\file__0.indexeddb.leveldb/MANIFEST-000001: FILE_ERROR_FAILED (ChromeMethodBFE: 6::WritableFileSync::1)
[12724:0218/154237.050:ERROR:leveldb_factory.cc(88)] Failed to open LevelDB database from \\TheNameOfTheServer\fldrredir$\MyUserName\AppData\Roaming\GitHub Desktop\IndexedDB\file__0.indexeddb.leveldb,IO error: \\TheNameOfTheServer\fldrredir$\MyUserName\AppData\Roaming\GitHub Desktop\IndexedDB\file__0.indexeddb.leveldb/MANIFEST-000001: FILE_ERROR_FAILED (ChromeMethodBFE: 6::WritableFileSync::1)
```
The name of the server is replace by TheNameOfTheServer and my username is replace by MyUserName.

### Release version

3.1.7 and previous

### Operating system

Windows 10 22H2 and previous

**Comment by steveward** [comment]
Thanks for the issue @mniesen. This has been previously reported in https://github.com/desktop/desktop/issues/2972, and you can see in [@niik's comment](https://github.com/desktop/desktop/issues/2972#issuecomment-341446027) some of the underlying issues here. There are some major changes we would have to make to support this, and unfortunately at this time we don't have the capacity as a team to investigate this further. Thank you for sharing your specific setup and use case, and I'm sorry that I don't have better news.
