### ISSUE TITLE
Checking for updates failed.

### ISSUE THREAD

**Issue by eladlavi** [desktop/desktop#16170]
### The problem

Ever since recent version (3.1.7) I am getting "Checking for updates failed."
This message is annoying and I have to click a button to release this blocking pop-up message.
I keep my GitHub desktop open usually and on my laptop, perhaps some times there's no Internet connection and I assume this is the reason updates are failing.
When I see this message, not only I do have Internet connection but GitHub desktop is working just fine so why would I care about this blocking aggressive message?
It needs to go away automatically if update did not fail or not to be shown at all in the first place.
What kind of "updates" are you checking for? version update of the GitHub desktop this has such a low importance that I don't see how it justifies such an annoying blocking message.

### Release version

3.1.7

### Operating system

Windows

**Comment by steveward** [comment]
Thanks for the report @eladlavi. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by lewri** [comment]
I also see this error on any system resume (i.e. wake from sleep) since the last few updates. Unfortunately I can't pin down what version it started at. My thought would be the check for update call happens too soon for the internet to reconnect. 
Same OS+Version as above, will test on 3.1.8 too and report back as it just updated.

Since the log is small see below:
```bash
2023-02-26T15:50:18.752Z - info: [ui] [BranchPruner] Last prune took place 18 hours ago - skipping
2023-02-26T15:50:19.721Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
    at rL.constructor.post (C:\Users\raimu\AppData\Local\GitHubDesktop\app-3.1.7\webpack:\[name]\app\src\lib\stats\stats-store.ts:1952:12)
    at rL.constructor.reportStats (C:\Users\raimu\AppData\Local\GitHubDesktop\app-3.1.7\webpack:\[name]\app\src\lib\stats\stats-store.ts:485:35)
2023-02-26T15:50:22.004Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 2.900s)
2023-02-26T15:50:22.113Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/lewri/CorsixTH.git/': Could not resolve host: github.com

2023-02-26T15:50:23.261Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand upstream` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/CorsixTH/CorsixTH.git/': Could not resolve host: github.com

2023-02-26T15:50:28.405Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 1.182s)
2023-02-26T15:52:50.630Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 2.2s of which 0.0s paused, total 2.2s
```

**Comment by eladlavi** [comment]
I will also try to include a log file but I am not sure it is required to identify this bug.
To be clear, it is a matter of how user works with GitHub desktop.
For me, I keep it open at all time. So when my laptop/pc goes to sleep and later wakes up, this message box appears.
I am not familiar with GitHub desktop source code but obviously, there's a point in the code where this messages box is launched to the screen.
The bug is logically simple, the condition to launch this message/error dialog box is incomplete or it is missing the condition to close this message box (when connectivity resumes - close it).
So for comparison, Windows, Google Chrome, Zoom or many other examples of software that update itself, doesn't show such a blocking dialog box when checking for updates fail.
I think that it isn't a bug but rather an incorrect behavior.
I hope I made it clear.

**Comment by tidy-dev** [comment]
I believe this is another case of https://github.com/desktop/desktop/issues/16057 and marked as a bug.

I'll close this issue, so we follow the progress in one place https://github.com/desktop/desktop/issues/16057
