### ISSUE TITLE
GitHub Desktop failed to launch on Version 0.5.5

### ISSUE THREAD

**Issue by JomaMinoza** [desktop/desktop#1629]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

[GitHub Desktop failed to launch]

### Version

**GitHub Desktop version:** [0.5.5]

**OS version:** [10.11.6]

### Steps to Reproduce

1. Update version of GitHub Desktop Beta
2. Restart OS
3. Re launch GitHub Desktop

**Expected behaviour:** Run smoothly new version of GitHub Desktop

**Actual behaviour:** GitHub Desktop failed to launch.

**Reproduces how often:** Everytime launching the App

### Logs

```
2017-05-18T18:22:27.804Z - error: fetchCommit: not found for 'JomaMinoza' and commit 'edukasyonph/edukasyon-p6@8a332b6584f0c27ef8aaa15309e2693401c47247'
Error: {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}

    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:3:78193
    at XMLHttpRequest.J.ae.onreadystatechange (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:3:75070)
2017-05-18T18:23:12.059Z - error: Uncaught exception on main process
TypeError: Cannot read property 'screen' of undefined
    at o.exports (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:12:10249)
    at new L (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:1:37416)
    at g (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:14:79026)
    at App.S.app.on (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:14:80223)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

#### Additional Information

```
Version: 0.5.5
Platform: darwin
```

**Comment by joshaber** [comment]
Thanks! This looks like #1564, so I'm gonna close this. Feel free to follow along over there!
