### ISSUE TITLE
It is not letting me commit

### ISSUE THREAD

**Issue by monohi** [desktop/desktop#16474]
### The problem

I write the summary and description but when I try to commit it doesn't work 

### Release version

Version 3.2.1 (x64)

### Operating system

windows 10

### Steps to reproduce the behavior

make summary and description 
then try to commit

**Comment by steveward** [comment]
Thanks for the report @monohi. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by findawei** [comment]
Facing same issue after having updated to 3.2.1

Being shown this
<img width="536" alt="Screen Shot 2023-04-07 at 3 18 47 PM" src="https://user-images.githubusercontent.com/50174504/230665088-0aa0ffc3-ee1d-43c0-8c8b-537f0dd6be29.png">

Can you just let me download 3.2.0 so I can go about my day?

**Comment by battsteam** [comment]
Sure On Fri, Apr 7, 2023 at 12:21 PM Alex Benjamignan ***@***.***> wrote:
Facing same issue after having updated to 3.2.1
Being shown this

Can you just let me download 3.2.0 so I can go about my day?

**Comment by krisu5** [comment]
Similar issue, happens at least when I try to commit to someone else's PR on my own repo.

<details><summary>Log info</summary>
<p>

```
2023-04-10T08:28:13.068Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-04-10T08:28:13.774Z - info: [ui] [AppStore] loading 1 repositories from store
2023-04-10T08:28:13.776Z - info: [ui] [AppStore] found account: krisu5 (Kristian Salonen)
2023-04-10T08:28:14.006Z - info: [ui] launching: 3.2.1 (Windows 10.0.19045)
2023-04-10T08:28:14.007Z - info: [ui] execPath: 'C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\GitHubDesktop.exe'
2023-04-10T08:28:14.460Z - info: [ui] Subscribed 'krisu5' to Alive channel
2023-04-10T08:28:14.732Z - info: [ui] Stats reported.
2023-04-10T08:29:17.839Z - info: [ui] [Timing] Action 'create commit' for 'aegis-icons/aegis-icons' took 0.467s
2023-04-10T08:59:27.252Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand github-desktop-5HT2C (took 1.062s)
2023-04-10T09:30:31.389Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand github-desktop-5HT2C (took 1.208s)
2023-04-10T10:01:33.794Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.001s)
2023-04-10T13:37:14.994Z - info: [ui] [BranchPruner] Last prune took place 5 hours ago - skipping
2023-04-10T13:37:15.222Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand github-desktop-5HT2C` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/5HT2C/aegis-icons.git/': Could not resolve host: github.com

2023-04-10T13:37:15.491Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/aegis-icons/aegis-icons.git/': Could not resolve host: github.com

2023-04-10T13:37:15.523Z - error: [ui] Error checking for updates
undefined: 
2023-04-10T13:37:16.496Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
TypeError: Failed to fetch
    at Bt (C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\webpack:\app\src\lib\http.ts:152:10)
    at Rn.request (C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\webpack:\app\src\lib\api.ts:1603:28)
    at Rn.fetchPushControl (C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\webpack:\app\src\lib\api.ts:1519:35)
    at lr.refreshBranchProtectionState (C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\webpack:\app\src\lib\stores\app-store.ts:1151:37)
    at C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\webpack:\app\src\lib\stores\app-store.ts:4862:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at lr.withPushPullFetch (C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\webpack:\app\src\lib\stores\app-store.ts:4374:5)
    at lr.performFetch (C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\webpack:\app\src\lib\stores\app-store.ts:4813:5)
    at Lo.performAndScheduleFetch (C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2023-04-10T13:37:16.874Z - warn: [ui] getFetchPollInterval: failed for aegis-icons/aegis-icons
TypeError: Failed to fetch
    at Bt (C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\webpack:\app\src\lib\http.ts:152:10)
    at Rn.request (C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\webpack:\app\src\lib\api.ts:1603:28)
    at Rn.getFetchPollInterval (C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\webpack:\app\src\lib\api.ts:1641:35)
    at Lo.getFetchInterval (C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:136:38)
    at Lo.performAndScheduleFetch (C:\Users\krisu\AppData\Local\GitHubDesktop\app-3.2.1\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:117:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-04-10T14:41:25.800Z - info: [ui] [Timing] Action 'create commit' for 'aegis-icons/aegis-icons' took 0.631s
2023-04-10T14:41:27.003Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: aegis-icons - krisu5 (has token)
```

</p>
</details> 

> Can you just let me download 3.2.0 so I can go about my day?

Not a possible solution, because of forced auto-update.

**Comment by steveward** [comment]
@krisu5 the error messages in the log file look like DNS/network issues -- I'm not seeing anything related to committing. What specific operation are you trying? For the network errors -- are you behind a proxy or firewall? It could also be possible that your antivirus flagged GitHub Desktop after the update, which we have occasionally seen when we update binaries in the app.

**Comment by krisu5** [comment]
> For the network errors -- are you behind a proxy or firewall? 

I have WireGuard VPN sometimes, but it wasn't even active when I tried to commit to the someone's PR on my repo. For firewall, I only use the Windows default.

> your antivirus flagged GitHub Desktop

Very unlikely, I'm only using Windows Defender. And it hasn't notified me anything related to this.

---

Works when I commit to my repo's master, but not when I commit to someone's PR on my repo.

EDIT: okay, it's possible that in this specific PR was deleted, privated or something else now when I look at it, based of "Authentication failed." error and this guy's repo list. False alarm I think.

**Comment by steveward** [comment]
Thanks for the update. I'm going to close this out.
