### ISSUE TITLE
Double clicking the title bar when maximized doesn't always restore the window size

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#1655]
### Description

When the application is maximized (via the maximize button, not F11) double clicking on the title bar will restore the window to its previous size, but if you click on the top few pixels of the title bar nothing happens. That area will trigger the menus and min/restore/close buttons, but it doesn't trigger the window restore.

### Version

**GitHub Desktop version:** 0.5.5
**OS version:** Win10 Creators Update (10.0.15063)

### Steps to Reproduce

1. Maximize the window so it's full screen (not the F11 option)
1. Move your mouse pointer to the very top of your screen
1. Double click

**Expected behaviour:** The window should be restored to its previous size just like when you double click in the middle of the title bar.

**Actual behaviour:** Nothing.

**Reproduces how often:** Every time.

#### Additional Information

It looks like `#desktop-app-title-bar .resize-handle.top` should be hidden when the window is maximized. Hiding it with dev tools looks to have solved the problem.

**Comment by niik** [comment]
> It looks like #desktop-app-title-bar .resize-handle.top should be hidden when the window is maximized. Hiding it with dev tools looks to have solved the problem.

@xt0rted That sounds like a great idea. Would you like to open a PR to fix that?

**Comment by xt0rted** [comment]
I'll take a shot at it.

I was trying to do it in the css but wasn't seeing a top level class that indicated if the window was maximized or not. Is that how we'd like to handle it or would removing that element from the control be a better approach? I haven't used Electron or React so I'm not really familiar with the best practices when doing things like this.

**Comment by niik** [comment]
@xtorted awesome! In this case I'd say removing it from the control would be the way to go about it. We already have a condition to only render it on Win32 so that's where I'd try to add a condition for when the app is in full screen. See https://github.com/desktop/desktop/blob/master/app/src/ui/app.tsx#L613 and let us know if you need any assistance

**Comment by xt0rted** [comment]
So far I haven't had the best of luck getting my environment setup. Despite having node, npm, and VS2015 installed I still needed to do some extra things. This is a list of updates that should be added to the docs once it's all working:

- When installing python make sure to check the option `Add python.exe to Path`
- Even with VS 2015 already installed I still needed to run `npm config set msvs_version 2015`
- Even with VS 2015 & 2017 installed I still needed to install the Win8.1 SDK (I'm on Win10 Creators Update)
    - Only the SDK option is needed
    - https://developer.microsoft.com/en-us/windows/downloads/windows-8-1-sdk
- Even with VS 2015 installed I needed to update the config and install c++ (it's not installed by default)

At this point I was able to `npm install` without errors, but now `npm run build:dev` is giving an error:
```powershell
C:\dev\GitHub\desktop [master ↑6]> npm run build:dev

> @ build:dev C:\dev\GitHub\desktop
> npm run compile:dev && cross-env NODE_ENV=development node script/build


> @ compile:dev C:\dev\GitHub\desktop
> cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js

[WEBPACK] Building 4 targets
[WEBPACK] Started building renderer.js
[WEBPACK] Started building main.js
[WEBPACK] Started building shared.js
[WEBPACK] Started building ask-pass.js

[at-loader] Using typescript@2.3.2 from typescript and "tsconfig.json" from C:\dev\GitHub\desktop/tsconfig.json.


[at-loader] Using typescript@2.3.2 from typescript and "tsconfig.json" from C:\dev\GitHub\desktop/tsconfig.json.


[at-loader] Using typescript@2.3.2 from typescript and "tsconfig.json" from C:\dev\GitHub\desktop/tsconfig.json.


[at-loader] Using typescript@2.3.2 from typescript and "tsconfig.json" from C:\dev\GitHub\desktop/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Checking started in a separate process...

[at-loader] Checking started in a separate process...

[at-loader] Ok, 2.451 sec.
Hash: 4d9c182f5dd963840b1a
Version: webpack 2.5.1
Time: 5409ms
      Asset    Size  Chunks             Chunk Names
keytar.node  110 kB          [emitted]
ask-pass.js   15 kB       0  [emitted]  ask-pass
chunk    {0} ask-pass.js (ask-pass) 4.44 kB [entry] [rendered]
    [0] ./app/src/ask-pass/ask-pass.ts 1.77 kB {0} [built]
    [1] ./app/~/keytar/lib/keytar.js 1.39 kB {0} [built]
    [2] ./app/src/ask-pass/main.ts 367 bytes {0} [built]
    [3] ./app/src/lib/auth.ts 412 bytes {0} [built]
    [4] ./app/src/shared-process/token-store.ts 446 bytes {0} [built]
    [5] ./app/~/keytar/build/Release/keytar.node 57 bytes {0} [built]
[WEBPACK] Finished building ask-pass.js within 5.409 seconds

[at-loader] Ok, 2.559 sec.

[at-loader] Ok, 2.598 sec.
Hash: 28404499ae4e87db045b
Version: webpack 2.5.1
Time: 6698ms
      Asset       Size  Chunks                    Chunk Names
keytar.node     110 kB          [emitted]
  shared.js    1.24 MB       0  [emitted]  [big]  shared
 error.html    1.34 kB          [emitted]
shared.html  182 bytes          [emitted]
chunk    {0} shared.js (shared) 463 kB [entry] [rendered]
    [5] ./app/src/lib/api.ts 19.9 kB {0} [built]
    [6] ./app/src/models/account.ts 1.16 kB {0} [built]
   [12] ./app/src/lib/logging/renderer.ts 1.6 kB {0} [built]
   [13] ./app/src/models/repository.ts 1.53 kB {0} [built]
   [14] ./app/~/dexie/dist/dexie.js 199 kB {0} [built]
   [18] ./app/~/octokat/dist/node/plugins/authorization.js 1.71 kB {0} [built]
   [35] ./app/src/shared-process/accounts-store.ts 3.81 kB {0} [built]
   [36] ./app/src/shared-process/communication.ts 2.77 kB {0} [built]
   [37] ./app/src/shared-process/database.ts 627 bytes {0} [built]
   [38] ./app/src/shared-process/repositories-store.ts 9.72 kB {0} [built]
   [39] ./app/src/shared-process/token-store.ts 446 bytes {0} [built]
   [40] ./app/src/ui/lib/exception-reporting.ts 2.42 kB {0} [built]
   [87] ./app/src/lib/2fa.ts 1.15 kB {0} [built]
   [90] ./app/src/lib/fatal-error.ts 777 bytes {0} [built]
   [98] ./app/src/shared-process/index.ts 5.3 kB {0} [built]
     + 91 hidden modules
Child html-webpack-plugin for "shared.html":
          Asset     Size  Chunks  Chunk Names
    shared.html  1.42 MB       0
    chunk    {0} shared.html 541 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-plugin/default_index.ejs 538 bytes {0} [built]
        [2] (webpack)/buildin/module.js 517 bytes {0} [built]
Child html-webpack-plugin for "error.html":
         Asset     Size  Chunks  Chunk Names
    error.html  1.42 MB       0
    chunk    {0} error.html 542 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] ./~/html-webpack-plugin/lib/loader.js!./app/static/error.html 1.8 kB {0} [built]
        [2] (webpack)/buildin/module.js 517 bytes {0} [built]
[WEBPACK] Finished building shared.js within 6.698 seconds
Hash: d43bcf3e9d773cee9024
Version: webpack 2.5.1
Time: 7271ms
  Asset     Size  Chunks                    Chunk Names
main.js  1.36 MB       0  [emitted]  [big]  main
chunk    {0} main.js (main) 485 kB [entry] [rendered]
    [0] external "path" 42 bytes {0} [not cacheable]
    [3] external "electron" 42 bytes {0} [not cacheable]
   [22] ./app/src/lib/fatal-error.ts 777 bytes {0} [built]
   [23] ./app/src/lib/logging/main.ts 3.75 kB {0} [built]
   [44] ./app/~/electron-debug/index.js 2.19 kB {0} [built]
   [45] ./app/~/electron-devtools-installer/dist/index.js 4.63 kB {0} [built]
   [46] ./app/src/lib/parse-url.ts 1.98 kB {0} [built]
   [47] ./app/src/main-process/app-window.ts 9.89 kB {0} [built]
   [48] ./app/src/main-process/error-page.ts 1.94 kB {0} [built]
   [49] ./app/src/main-process/menu/index.ts 296 bytes {0} [built]
   [50] ./app/src/main-process/squirrel-updater.ts 1.17 kB {0} [built]
   [51] ./app/src/shared-process/shared-process.ts 2.27 kB {0} [built]
   [73] ./app/~/electron-localshortcut/index.js 3.33 kB {0} [built]
   [74] ./app/~/electron-window-state/index.js 4.6 kB {0} [built]
  [124] ./app/src/main-process/main.ts 8.41 kB {0} [built]
     + 119 hidden modules

WARNING in ./app/~/colors/lib/colors.js
127:29-43 Critical dependency: the request of a dependency is an expression
[WEBPACK] Finished building main.js within 7.271 seconds

[at-loader] Checking started in a separate process...

[at-loader] Ok, 3.322 sec.
Hash: b7c57f144baad7c93133
Version: webpack 2.5.1
Time: 14218ms
      Asset       Size  Chunks                    Chunk Names
renderer.js    10.3 MB       0  [emitted]  [big]  renderer
 index.html  234 bytes          [emitted]
chunk    {0} renderer.js (renderer) 3.78 MB [entry] [rendered]
    [0] ./app/~/react/react.js 56 bytes {0} [built]
    [3] external "path" 42 bytes {0} [not cacheable]
  [288] ./app/src/ui/app.tsx 41.4 kB {0} [built]
  [305] (webpack)/buildin/module.js 517 bytes {0} [built]
  [308] external "querystring" 42 bytes {0} [not cacheable]
  [310] ./app/~/webpack-hot-middleware/client.js?path=http://localhost:3000/__webpack_hmr 6.68 kB {0} [built]
  [311] ./app/src/ui/index.tsx 4.23 kB {0} [built]
  [585] ./app/~/strip-ansi/index.js 161 bytes {0} [built]
  [595] ./app/~/webpack-hot-middleware/client-overlay.js 1.82 kB {0} [built]
  [596] ./app/~/webpack-hot-middleware/process-update.js 3.88 kB {0} [built]
  [598] ./app/~/wicg-focus-ring/dist/focus-ring.js 8.21 kB {0} [built]
  [710] ./app/src/ui/install-globals.ts 521 bytes {0} [built]
  [716] ./app/src/ui/lib/exception-reporting.ts 2.42 kB {0} [built]
  [774] ./app/styles/desktop.scss 1.11 kB {0} [built]
  [781] multi webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr ./app/src/ui/index 40 bytes {0} [built]
     + 767 hidden modules
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  1.44 MB       0
    chunk    {0} index.html 541 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] ./~/html-webpack-plugin/lib/loader.js!./app/static/index.html 529 bytes {0} [built]
        [2] (webpack)/buildin/module.js 517 bytes {0} [built]
[WEBPACK] Finished building renderer.js within 14.218 seconds
[WEBPACK] Finished build after 15.314 seconds
Building for development…
Removing old distribution…
Copying dependencies…
  Installing 7zip (dependency for electron-devtools-installer)
  Copying git environment…
fs.js:968
  binding.stat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, stat 'C:\dev\GitHub\desktop\app\node_modules\dugite\git'
    at Object.fs.statSync (fs.js:968:11)
    at Object.statSync (C:\dev\GitHub\desktop\node_modules\graceful-fs\polyfills.js:297:22)
    at Object.copySync (C:\dev\GitHub\desktop\node_modules\fs-extra\lib\copy-sync\copy-sync.js:31:86)
    at copyDependencies (C:\dev\GitHub\desktop\script\build:204:6)
    at Object.<anonymous> (C:\dev\GitHub\desktop\script\build:23:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:dev: `npm run compile:dev && cross-env NODE_ENV=development node script/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\brian\AppData\Roaming\npm-cache\_logs\2017-05-20T01_48_10_919Z-debug.log
```

**Comment by xt0rted** [comment]
For some reason the `postinstall` script for dugite didn't run, or if it did it failed and wasn't running on subsequent `npm install` attempts. Either way I had to run that manually like so:
```
c:\dev\GitHub\desktop\app\node_modules\dugite> node ./script/download-git.js
Downloading Git from: https://github.com/desktop/dugite-native/releases/download/v2.12.2-rc3/dugite-native-v2.12.2-win32-181.tar.gz

Downloading Git [==================================================] 100% 0.0s
```

After doing that `npm run build:dev` succeeded.

**Comment by shiftkey** [comment]
@xt0rted my gut feeling on this is something caused an earlier `npm install` to fail to download the necessary `dugite-native` package - it then extracts it to that folder.

```
> fs.js:968
  binding.stat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, stat 'C:\dev\GitHub\desktop\app\node_modules\dugite\git'
    at Object.fs.statSync (fs.js:968:11)
```

If you're able to reproduce this consistently, let's get to the bottom of it over here: https://github.com/desktop/dugite

**Comment by shiftkey** [comment]
> So far I haven't had the best of luck getting my environment setup. Despite having node, npm, and VS2015 installed I still needed to do some extra things. This is a list of updates that should be added to the docs once it's all working:
> 
> ...

Some of these are already called out in the [`setup.md`](https://github.com/desktop/desktop/blob/master/docs/contributing/setup.md) document, but I'd love to refine this further based on your setup and experience :metal:

**Comment by lastingman** [comment]
@xt0rted @shiftkey  I had same issue on my mac.

There is no error with `npm install`.

### versions
- node: v8.1.2
- npm: 5.0.3
- python: 2.7.13

```powershell
> npm run build:dev

> @ build:dev /Users/Like/Desktop/gitrepo/desktop
> npm run compile:dev && cross-env NODE_ENV=development node script/build


> @ compile:dev /Users/Like/Desktop/gitrepo/desktop
> cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js

[WEBPACK] Building 5 targets
[WEBPACK] Started building renderer.js
[WEBPACK] Started building main.js
[WEBPACK] Started building ask-pass.js
[WEBPACK] Started building shared.js
[WEBPACK] Started building crash.js

[at-loader] Using typescript@2.3.4 from typescript and "tsconfig.json" from /Users/Like/Desktop/gitrepo/desktop/tsconfig.json.


[at-loader] Using typescript@2.3.4 from typescript and "tsconfig.json" from /Users/Like/Desktop/gitrepo/desktop/tsconfig.json.


[at-loader] Using typescript@2.3.4 from typescript and "tsconfig.json" from /Users/Like/Desktop/gitrepo/desktop/tsconfig.json.


[at-loader] Using typescript@2.3.4 from typescript and "tsconfig.json" from /Users/Like/Desktop/gitrepo/desktop/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Using typescript@2.3.4 from typescript and "tsconfig.json" from /Users/Like/Desktop/gitrepo/desktop/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Ok, 7.759 sec.
Hash: 6ebf056adb6a5431d4c0
Version: webpack 2.6.1
Time: 16312ms
          Asset     Size  Chunks             Chunk Names
    keytar.node  42.3 kB          [emitted]  
    ask-pass.js  7.56 kB       0  [emitted]  ask-pass
ask-pass.js.map  7.94 kB       0  [emitted]  ask-pass
chunk    {0} ask-pass.js, ask-pass.js.map (ask-pass) 4.51 kB [entry] [rendered]
    [0] ./app/src/ask-pass/ask-pass.ts 1.77 kB {0} [built]
    [1] ./app/~/keytar/lib/keytar.js 1.39 kB {0} [built]
    [2] ./app/src/ask-pass/main.ts 367 bytes {0} [built]
    [3] ./app/src/lib/auth.ts 479 bytes {0} [built]
    [4] ./app/src/shared-process/token-store.ts 446 bytes {0} [built]
    [5] ./app/~/keytar/build/Release/keytar.node 57 bytes {0} [built]
[WEBPACK] Finished building ask-pass.js within 16.312 seconds

[at-loader] Ok, 7.573 sec.
Hash: af8f6c7332ff00f0cbae
Version: webpack 2.6.1
Time: 18883ms
        Asset       Size  Chunks                    Chunk Names
  keytar.node    42.3 kB          [emitted]         
    shared.js     443 kB       0  [emitted]  [big]  shared
shared.js.map     539 kB       0  [emitted]         shared
   error.html     1.3 kB          [emitted]         
  shared.html  182 bytes          [emitted]         
chunk    {0} shared.js, shared.js.map (shared) 436 kB [entry] [rendered]
    [4] ./app/src/models/account.ts 1.16 kB {0} [built]
    [5] ./app/src/lib/api.ts 22.4 kB {0} [built]
    [6] ./app/src/lib/source-map-support.ts 4.73 kB {0} [built]
    [7] ./app/src/models/repository.ts 1.55 kB {0} [built]
   [14] ./app/src/models/owner.ts 409 bytes {0} [built]
   [18] ./app/src/lib/logging/renderer/install.ts 1.19 kB {0} [built]
   [19] ./app/src/shared-process/accounts-store.ts 3.81 kB {0} [built]
   [20] ./app/src/shared-process/communication.ts 2.77 kB {0} [built]
   [21] ./app/src/shared-process/database.ts 627 bytes {0} [built]
   [22] ./app/src/shared-process/repositories-store.ts 9.8 kB {0} [built]
   [23] ./app/src/shared-process/token-store.ts 446 bytes {0} [built]
   [24] ./app/src/ui/main-process-proxy.ts 3.61 kB {0} [built]
   [34] ./app/~/file-uri-to-path/index.js 1.72 kB {0} [built]
   [61] ./app/src/lib/auth.ts 479 bytes {0} [built]
   [68] ./app/src/shared-process/index.ts 5.22 kB {0} [built]
     + 59 hidden modules
Child html-webpack-plugin for "shared.html":
          Asset    Size  Chunks  Chunk Names
    shared.html  544 kB       0  
    chunk    {0} shared.html 541 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-plugin/default_index.ejs 538 bytes {0} [built]
        [2] (webpack)/buildin/module.js 517 bytes {0} [built]
Child html-webpack-plugin for "error.html":
         Asset    Size  Chunks  Chunk Names
    error.html  545 kB       0  
    chunk    {0} error.html 542 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] ./~/html-webpack-plugin/lib/loader.js!./app/static/error.html 1.71 kB {0} [built]
        [2] (webpack)/buildin/module.js 517 bytes {0} [built]
[WEBPACK] Finished building shared.js within 18.883 seconds

[at-loader] Checking started in a separate process...

[at-loader] Checking started in a separate process...

[at-loader] Ok, 4.302 sec.
Hash: 9c3b4510c8c2c88e7ea2
Version: webpack 2.6.1
Time: 25174ms
      Asset    Size  Chunks                    Chunk Names
    main.js  610 kB       0  [emitted]  [big]  main
main.js.map  765 kB       0  [emitted]         main
chunk    {0} main.js, main.js.map (main) 596 kB [entry] [rendered]
    [3] external "electron" 42 bytes {0} [not cacheable]
   [16] ./app/src/main-process/log.ts 4.65 kB {0} [built]
   [25] ./app/src/lib/fatal-error.ts 777 bytes {0} [built]
   [26] ./app/src/lib/logging/format-error.ts 599 bytes {0} [built]
   [27] ./app/src/lib/source-map-support.ts 4.73 kB {0} [built]
   [28] ./app/src/main-process/now.ts 450 bytes {0} [built]
   [54] ./app/~/electron-debug/index.js 2.19 kB {0} [built]
   [58] ./app/src/lib/shell.ts 5.33 kB {0} [built]
   [59] ./app/src/main-process/app-window.ts 8.37 kB {0} [built]
   [60] ./app/src/main-process/crash-window.ts 5.51 kB {0} [built]
   [61] ./app/src/main-process/exception-reporting.ts 2.73 kB {0} [built]
   [62] ./app/src/main-process/menu/index.ts 331 bytes {0} [built]
   [63] ./app/src/main-process/squirrel-updater.ts 1.17 kB {0} [built]
   [64] ./app/src/shared-process/shared-process.ts 1.85 kB {0} [built]
  [145] ./app/src/main-process/main.ts 10.6 kB {0} [built]
     + 142 hidden modules

WARNING in ./app/~/colors/lib/colors.js
127:29-43 Critical dependency: the request of a dependency is an expression
[WEBPACK] Finished building main.js within 25.174 seconds

[at-loader] Checking started in a separate process...

[at-loader] Ok, 4.947 sec.
Hash: fd8f2a057088140bbd0b
Version: webpack 2.6.1
Time: 28651ms
          Asset       Size  Chunks                    Chunk Names
    renderer.js    4.02 MB       0  [emitted]  [big]  renderer
renderer.js.map    5.01 MB       0  [emitted]         renderer
     index.html  225 bytes          [emitted]         
chunk    {0} renderer.js, renderer.js.map (renderer) 3.88 MB [entry] [rendered]
    [0] ./app/~/react/react.js 56 bytes {0} [built]
    [1] external "path" 42 bytes {0} [not cacheable]
  [293] (webpack)/buildin/module.js 517 bytes {0} [built]
  [297] ./app/~/webpack-hot-middleware/client.js?path=http://localhost:3000/__webpack_hmr 6.68 kB {0} [built]
  [298] ./app/src/ui/index.tsx 4.48 kB {0} [built]
  [563] ./app/~/strip-ansi/index.js 161 bytes {0} [built]
  [573] ./app/~/webpack-hot-middleware/client-overlay.js 1.82 kB {0} [built]
  [574] ./app/~/webpack-hot-middleware/process-update.js 3.88 kB {0} [built]
  [576] ./app/~/wicg-focus-ring/dist/focus-ring.js 8.21 kB {0} [built]
  [619] ./app/src/lib/logging/renderer/install.ts 1.19 kB {0} [built]
  [630] ./app/src/lib/shell.ts 5.33 kB {0} [built]
  [695] ./app/src/ui/install-globals.ts 521 bytes {0} [built]
  [760] ./app/styles/desktop.scss 1.11 kB {0} [built]
  [765] external "querystring" 42 bytes {0} [not cacheable]
  [767] multi webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr ./app/src/ui/index 40 bytes {0} [built]
     + 753 hidden modules
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  566 kB       0  
    chunk    {0} index.html 541 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] ./~/html-webpack-plugin/lib/loader.js!./app/static/index.html 511 bytes {0} [built]
        [2] (webpack)/buildin/module.js 517 bytes {0} [built]
[WEBPACK] Finished building renderer.js within 28.651 seconds

[at-loader] Ok, 3.086 sec.
Hash: cec57214f8ae8c23a8d9
Version: webpack 2.6.1
Time: 29940ms
       Asset       Size  Chunks                    Chunk Names
    crash.js    1.64 MB       0  [emitted]  [big]  crash
crash.js.map    2.04 MB       0  [emitted]         crash
  crash.html  184 bytes          [emitted]         
chunk    {0} crash.js, crash.js.map (crash) 1.62 MB [entry] [rendered]
   [18] external "electron" 42 bytes {0} [not cacheable]
   [20] ./app/~/react/react.js 56 bytes {0} [built]
   [28] ./app/~/react/lib/React.js 3.32 kB {0} [built]
   [50] ./app/src/ui/octicons/index.ts 376 bytes {0} [built]
   [74] ./app/src/lib/window-state.ts 2.15 kB {0} [built]
  [131] ./app/~/react-dom/index.js 59 bytes {0} [built]
  [132] ./app/src/crash/crash-app.tsx 5.57 kB {0} [built]
  [133] ./app/src/crash/styles/crash.scss 1.15 kB {0} [built]
  [184] ./app/~/react-dom/lib/ReactDOM.js 5.14 kB {0} [built]
  [262] ./app/src/crash/index.tsx 641 bytes {0} [built]
  [279] ./app/src/lib/get-os.ts 758 bytes {0} [built]
  [319] ./app/src/ui/lib/button.tsx 2.35 kB {0} [built]
  [322] ./app/src/ui/lib/link-button.tsx 1.22 kB {0} [built]
  [327] ./~/css-loader?sourceMap!./~/sass-loader/lib/loader.js?sourceMap!./app/src/crash/styles/crash.scss 52.1 kB {0} [built]
  [329] ./~/style-loader/addStyles.js 8.51 kB {0} [built]
     + 319 hidden modules
Child html-webpack-plugin for "crash.html":
         Asset    Size  Chunks  Chunk Names
    crash.html  544 kB       0  
    chunk    {0} crash.html 541 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-plugin/default_index.ejs 538 bytes {0} [built]
        [2] (webpack)/buildin/module.js 517 bytes {0} [built]
[WEBPACK] Finished building crash.js within 29.94 seconds
[WEBPACK] Finished build after 31.363 seconds
Building for development…
Removing old distribution…
Copying dependencies…
  Installing 7zip (dependency for electron-devtools-installer)
  Copying git environment…
fs.js:953
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '/Users/Like/Desktop/gitrepo/desktop/app/node_modules/dugite/git'
    at Object.fs.statSync (fs.js:953:11)
    at Object.statSync (/Users/Like/Desktop/gitrepo/desktop/node_modules/graceful-fs/polyfills.js:297:22)
    at Object.copySync (/Users/Like/Desktop/gitrepo/desktop/node_modules/fs-extra/lib/copy-sync/copy-sync.js:31:86)
    at copyDependencies (/Users/Like/Desktop/gitrepo/desktop/script/build:205:6)
    at Object.<anonymous> (/Users/Like/Desktop/gitrepo/desktop/script/build:23:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:dev: `npm run compile:dev && cross-env NODE_ENV=development node script/build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Like/.npm/_logs/2017-07-10T10_04_11_379Z-debug.log
```
