### ISSUE TITLE
Publish Branch is hanging in Github Desktop.

### ISSUE THREAD

**Issue by boneoh** [desktop/desktop#16635]
### The problem

Publish Branch is hanging in Github Desktop.

### Release version

Version 3.2.2 (x64)

### Operating system

Mac OS X 12.6.5

### Steps to reproduce the behavior

Created a new repository. Click publish branch. Get spinning wheel 'Pushing to origin' 

### Log files

[2023-05-02.desktop.production.log](https://github.com/desktop/desktop/files/11378162/2023-05-02.desktop.production.log)

**Comment by sergiou87** [comment]
Hey @boneoh ! 👋 

Looking at the attached logs, seems like your repo doesn't exist anymore 🤔 

```
2023-05-02T22:37:51.918Z - warn: [ui] fetchAll: 'repos/boneoh/S3test/issues?state=open' returned a 404
2023-05-02T22:37:52.537Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
    at Nt (/webpack:/app/src/lib/http.ts:178:11)
    at En.fetchProtectedBranches (/webpack:/app/src/lib/api.ts:1548:7)
    at lr.updateBranchProtectionsFromAPI (/webpack:/app/src/lib/stores/app-store.ts:3969:11)
2023-05-02T22:38:13.802Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/boneoh/S3test.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
```
