### ISSUE TITLE
When fetch origin is clicked, many ssh.exe processors are executed.

### ISSUE THREAD

**Issue by juniair** [desktop/desktop#16672]
### The problem

After upgrading git for windows version to 2.40.1, when fetch origin is clicked, ssh.exe processors are executed in large numbers.
It was confirmed that the process was created innumerably, and the system's memory usage rate was over 99%.

### Release version

3.2.3(x64)

### Operating system

Windows 10 pro

### Steps to reproduce the behavior

1. Install or update git for windows 2.40.1.
2. Run task manager.
3. Click fetch origin from the existing local git repository.
4. Check the running processes and total memory usage in the task manager.

### Log files

2023-05-10T02:28:12.522Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-05-10T02:28:12.954Z - info: [ui] [AppStore] loading 18 repositories from store
2023-05-10T02:28:12.955Z - info: [ui] [AppStore] found account: juniair (KimKyengJun)
2023-05-10T02:28:13.147Z - info: [ui] launching: 3.2.3 (Windows 10.0.19045)
2023-05-10T02:28:13.158Z - info: [ui] execPath: 'C:\Users\Alice\AppData\Local\GitHubDesktop\app-3.2.3\GitHubDesktop.exe'
2023-05-10T02:28:13.448Z - info: [ui] Subscribed 'juniair' to Alive channel
2023-05-10T02:28:13.775Z - info: [ui] Stats reported.
2023-05-10T04:25:42.033Z - info: [ui] Executing checkoutBranch: git -c credential.helper= checkout --progress origin/develop -b develop --recurse-submodules -- (took 1.540s)
2023-05-10T04:25:42.753Z - info: [ui] [Timing] Action 'checkout branch from list' for 'murph_temp' took 2.269s
2023-05-10T04:26:10.730Z - info: [ui] [Timing] Action 'checkout branch from list' for 'murph' took 0.000s
2023-05-10T04:26:19.041Z - info: [ui] Executing createStashEntry: git stash push -m !!GitHub_Desktop<CC_2023> (took 2.417s)
2023-05-10T04:26:31.955Z - info: [ui] Executing checkoutBranch: git -c credential.helper= checkout --progress fix/backdrop-not-disappearing --recurse-submodules -- (took 12.906s)
2023-05-10T04:26:33.335Z - info: [ui] [Timing] Action 'stash and checkout' for 'murph' took 16.762s
2023-05-10T04:27:00.828Z - info: [ui] [Timing] Action 'checkout branch from list' for 'murph' took 0.000s
2023-05-10T04:27:05.483Z - info: [ui] [Timing] Action 'checkout branch from list' for 'murph' took 0.000s
2023-05-10T04:27:08.373Z - info: [ui] Executing checkoutBranch: git -c credential.helper= checkout --progress develop --recurse-submodules -- (took 1.125s)
2023-05-10T04:27:08.440Z - error: [ui] Could not load new contents for syntax highlighting
Error: ENOENT: no such file or directory, open 'D:\workspace\00_git\murph_project\murph\Brand\codemind.lic'
2023-05-10T04:27:09.041Z - info: [ui] [Timing] Action 'stash and checkout' for 'murph' took 2.838s
2023-05-10T04:27:26.776Z - info: [ui] Executing checkoutBranch: git -c credential.helper= checkout --progress CC_2023 --recurse-submodules -- (took 11.322s)
2023-05-10T04:27:27.395Z - info: [ui] [Timing] Action 'checkout branch from list' for 'murph' took 11.951s
2023-05-10T04:33:10.003Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 2.601s)
2023-05-10T04:33:19.540Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 12.259s)
2023-05-10T04:33:21.251Z - info: [ui] Executing getStashEntries: git log -g -z --format=%gD%x00%H%x00%gs refs/stash (took 1.365s)
2023-05-10T04:33:26.060Z - info: [ui] Executing getCommits: git log origin/CC_2023..CC_2023 --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 6.306s)
2023-05-10T04:36:39.880Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-05-10T04:36:40.295Z - info: [ui] [AppStore] loading 18 repositories from store
2023-05-10T04:36:40.296Z - info: [ui] [AppStore] found account: juniair (KimKyengJun)
2023-05-10T04:36:40.409Z - info: [ui] launching: 3.2.3 (Windows 10.0.19045)
2023-05-10T04:36:40.420Z - info: [ui] execPath: 'C:\Users\Alice\AppData\Local\GitHubDesktop\app-3.2.3\GitHubDesktop.exe'
2023-05-10T04:36:40.757Z - info: [ui] Subscribed 'juniair' to Alive channel
2023-05-10T04:36:42.601Z - info: [ui] Executing getRemotes: git remote -v (took 2.287s)
2023-05-10T04:36:52.342Z - info: [ui] [AppStore. _popStashEntry] popped stash with commit id 79f706f648f5a26c4c5df35450a29bb7a6b1a5b5
2023-05-10T04:43:25.909Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-05-10T04:43:26.512Z - info: [ui] [AppStore] loading 18 repositories from store
2023-05-10T04:43:26.512Z - info: [ui] [AppStore] found account: juniair (KimKyengJun)
2023-05-10T04:43:26.657Z - info: [ui] launching: 3.2.3 (Windows 10.0.19045)
2023-05-10T04:43:26.663Z - info: [ui] execPath: 'C:\Users\Alice\AppData\Local\GitHubDesktop\app-3.2.3\GitHubDesktop.exe'
2023-05-10T04:43:26.998Z - info: [ui] Subscribed 'juniair' to Alive channel
2023-05-10T04:43:27.964Z - info: [ui] Executing getRemotes: git remote -v (took 1.431s)
2023-05-10T04:43:28.320Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.682s)
2023-05-10T05:16:53.367Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-05-10T05:16:53.821Z - info: [ui] [AppStore] loading 18 repositories from store
2023-05-10T05:16:53.822Z - info: [ui] [AppStore] found account: juniair (KimKyengJun)
2023-05-10T05:16:54.040Z - info: [ui] launching: 3.2.3 (Windows 10.0.19045)
2023-05-10T05:16:54.045Z - info: [ui] execPath: 'C:\Users\Alice\AppData\Local\GitHubDesktop\app-3.2.3\GitHubDesktop.exe'
2023-05-10T05:16:54.381Z - info: [ui] Subscribed 'juniair' to Alive channel
2023-05-10T05:17:06.194Z - info: [ui] Executing checkoutBranch: git -c credential.helper= checkout --progress feature/andrew --recurse-submodules -- (took 1.418s)
2023-05-10T05:17:07.291Z - info: [ui] [Timing] Action 'checkout branch from list' for 'murph_temp' took 2.528s
2023-05-10T06:28:36.390Z - info: [ui] No submodules found. Skipping "git submodule status"
2023-05-10T07:53:04.142Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-05-10T07:53:05.146Z - info: [ui] [AppStore] loading 18 repositories from store
2023-05-10T07:53:05.148Z - info: [ui] [AppStore] found account: juniair (KimKyengJun)
2023-05-10T07:53:05.545Z - info: [ui] launching: 3.2.3 (Windows 10.0.19045)
2023-05-10T07:53:05.558Z - info: [ui] execPath: 'C:\Users\Alice\AppData\Local\GitHubDesktop\app-3.2.3\GitHubDesktop.exe'
2023-05-10T07:53:05.849Z - info: [ui] Subscribed 'juniair' to Alive channel
2023-05-10T08:08:03.362Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-05-10T08:08:03.738Z - info: [ui] [AppStore] loading 18 repositories from store
2023-05-10T08:08:03.739Z - info: [ui] [AppStore] found account: juniair (KimKyengJun)
2023-05-10T08:08:03.876Z - info: [ui] launching: 3.2.3 (Windows 10.0.19045)
2023-05-10T08:08:03.898Z - info: [ui] execPath: 'C:\Users\Alice\AppData\Local\GitHubDesktop\app-3.2.3\GitHubDesktop.exe'
2023-05-10T08:08:04.502Z - info: [ui] Subscribed 'juniair' to Alive channel
2023-05-10T08:08:09.195Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.094s)
2023-05-10T08:08:09.199Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.087s)
2023-05-10T08:08:09.350Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --skip=0 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 2.585s)
2023-05-10T08:14:14.584Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-05-10T08:22:27.365Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\Alice\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at te (C:\Users\Alice\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\Alice\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\Alice\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\Alice\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\Alice\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
2023-05-10T08:22:27.371Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\Alice\Desktop\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at te (C:\Users\Alice\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\Alice\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\Alice\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\Alice\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\Alice\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
2023-05-10T08:22:27.371Z - error: [main] Toast activator CLSID not found in any of the shortcuts. Falling back to known CLSIDs.
2023-05-10T08:22:27.371Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-05-10T08:22:28.008Z - info: [main] Received possible protocol arguments: 2
2023-05-10T08:22:28.014Z - error: [main] Malformed launch arguments received: C:\Users\Alice\AppData\Local\GitHubDesktop\app-3.2.3\GitHubDesktop.exe,--squirrel-firstrun
2023-05-10T08:22:28.014Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-05-10T08:22:28.362Z - info: [ui] [AppStore] loading 18 repositories from store
2023-05-10T08:22:28.362Z - info: [ui] [AppStore] found account: juniair (KimKyengJun)
2023-05-10T08:22:28.531Z - info: [ui] launching: 3.2.3 (Windows 10.0.19045)
2023-05-10T08:22:28.534Z - info: [ui] execPath: 'C:\Users\Alice\AppData\Local\GitHubDesktop\app-3.2.3\GitHubDesktop.exe'
2023-05-10T08:22:28.893Z - info: [ui] Subscribed 'juniair' to Alive channel
2023-05-10T08:39:32.673Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-05-10T08:39:32.953Z - info: [ui] [AppStore] loading 18 repositories from store
2023-05-10T08:39:32.954Z - info: [ui] [AppStore] found account: juniair (KimKyengJun)
2023-05-10T08:39:33.092Z - info: [ui] launching: 3.2.3 (Windows 10.0.19045)
2023-05-10T08:39:33.095Z - info: [ui] execPath: 'C:\Users\Alice\AppData\Local\GitHubDesktop\app-3.2.3\GitHubDesktop.exe'
2023-05-10T08:39:33.459Z - info: [ui] Subscribed 'juniair' to Alive channel
2023-05-10T08:41:15.177Z - info: [ui] [Timing] Action 'create commit' for 'murph' took 0.477s
2023-05-10T08:44:03.966Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-05-10T08:44:04.456Z - info: [ui] [AppStore] loading 18 repositories from store
2023-05-10T08:44:04.457Z - info: [ui] [AppStore] found account: juniair (KimKyengJun)
2023-05-10T08:44:04.630Z - info: [ui] launching: 3.2.3 (Windows 10.0.19045)
2023-05-10T08:44:04.639Z - info: [ui] execPath: 'C:\Users\Alice\AppData\Local\GitHubDesktop\app-3.2.3\GitHubDesktop.exe'
2023-05-10T08:44:05.008Z - info: [ui] Subscribed 'juniair' to Alive channel
2023-05-10T08:47:05.582Z - info: [ui] Executing getRemotes: git remote -v (took 2.253s)
2023-05-10T08:47:06.705Z - info: [ui] Executing getCommits: git log a40dda4707128b3c57015cf4ece1ea37a7c4ef3d --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 3.986s)
2023-05-10T08:47:08.734Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 3.142s)
2023-05-10T08:51:58.006Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 2.336s)
2023-05-10T08:52:46.830Z - info: [ui] Executing getRemotes: git remote -v (took 2.354s)
2023-05-10T08:52:50.918Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 4.078s)
2023-05-10T08:53:30.319Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 43.414s)
2023-05-10T08:53:32.007Z - info: [ui] Executing getSymbolicRef: git symbolic-ref -q refs/remotes/origin/HEAD (took 1.681s)
2023-05-10T08:53:33.248Z - info: [ui] Executing getConfigValueInPath: git config -z --global init.defaultBranch (took 1.241s)
2023-05-10T08:53:35.214Z - info: [ui] Executing getCommits: git log origin/CC_2023..CC_2023 --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.672s)
2023-05-10T08:53:35.397Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.828s)
2023-05-10T08:53:36.600Z - info: [ui] Executing getStashEntries: git log -g -z --format=%gD%x00%H%x00%gs refs/stash (took 3.050s)

### Screenshots

![image](https://github.com/desktop/desktop/assets/12860272/c397f619-8ee6-426f-8662-cde2dc869eaa)

**Comment by steveward** [comment]
@juniair thanks for the issue. I have Git 2.40.1 installed in a Windows test machine and am not seeing this issue. There is a known issue where SSH processes are hanging when system OpenSSH is being used (see https://github.com/desktop/desktop/issues/16542). Are your SSH operations completing? Can you go to `File` > `Options` > `Advanced` and let me know if `Use system OpenSSH` is enabled?

**Comment by juniair** [comment]
![image](https://github.com/desktop/desktop/assets/12860272/bea558d8-461c-470e-8cb8-9875ab0abdbc)

The OpenSSH you mentioned seems to be disabled.

**Comment by juniair** [comment]
![image](https://github.com/desktop/desktop/assets/12860272/baeaae23-5c55-4c78-a8fc-80c0135a2072)

The OpenSSH you mentioned seems to be disabled.

**Comment by juniair** [comment]
I made a mistake. The cause was that the hostname had the same value in the ssh settings registered as a test. I sincerely apologize. Also, thank you for your help in resolving the issue.
