### ISSUE TITLE
Github desktop push problem

### ISSUE THREAD

**Issue by mlynarskim** [desktop/desktop#16851]
### The problem

GitHub desktop application on macOS, endlessly uploads files to the repository, resetting the application does not help.

### Release version

Version 3.2.3 (arm64)

### Operating system

MacOS 13.4

### Steps to reproduce the behavior

add summary 
commit to ...
push

### Log files

2023-06-06T04:58:30.173Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: mediumish-gohugo-theme - mlynarskim (has token)
2023-06-06T04:58:32.371Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 3.6s of which 0.0s paused, total 3.6s
2023-06-06T05:00:54.190Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Rules - mlynarskim (has token)
2023-06-06T05:52:36.748Z - info: [ui] [BranchPruner] Last prune took place 15 hours ago - skipping
2023-06-06T06:49:33.032Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: mediumish-gohugo-theme - mlynarskim (has token)
2023-06-06T07:41:56.807Z - warn: [ui] getFetchPollInterval: failed for mlynarskim/Rules
TypeError: Failed to fetch
    at It (/webpack:/app/src/lib/http.ts:152:10)
    at Sn.request (/webpack:/app/src/lib/api.ts:1603:28)
    at Sn.getFetchPollInterval (/webpack:/app/src/lib/api.ts:1641:35)
    at Mo.getFetchInterval (/webpack:/app/src/lib/stores/helpers/background-fetcher.ts:136:38)
    at Mo.performAndScheduleFetch (/webpack:/app/src/lib/stores/helpers/background-fetcher.ts:117:33)
2023-06-06T09:52:00.007Z - info: [ui] [BranchPruner] Last prune took place 19 hours ago - skipping
2023-06-06T11:01:25.693Z - warn: [ui] getFetchPollInterval: failed for mlynarskim/Rules
TypeError: Failed to fetch
    at It (/webpack:/app/src/lib/http.ts:152:10)
    at Sn.request (/webpack:/app/src/lib/api.ts:1603:28)
    at Sn.getFetchPollInterval (/webpack:/app/src/lib/api.ts:1641:35)
    at Mo.getFetchInterval (/webpack:/app/src/lib/stores/helpers/background-fetcher.ts:136:38)
    at Mo.performAndScheduleFetch (/webpack:/app/src/lib/stores/helpers/background-fetcher.ts:117:33)
2023-06-06T14:30:07.959Z - info: [ui] [BranchPruner] Last prune took place 23 hours ago - skipping
2023-06-06T15:47:51.420Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 4.2s of which 32294.9s paused, total 32299.1s
2023-06-06T15:47:53.506Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: mediumish-gohugo-theme - mlynarskim (has token)
2023-06-06T15:57:56.233Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 3.5s of which 600.6s paused, total 604.1s
2023-06-06T18:28:25.595Z - info: [ui] [BranchPruner] No branches to prune.
2023-06-06T18:28:26.794Z - info: [ui] Stats reported.
2023-06-06T21:29:40.645Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: mediumish-gohugo-theme - mlynarskim (has token)
2023-06-06T21:29:43.020Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 4.0s of which 0.0s paused, total 4.0s
2023-06-06T21:29:53.536Z - info: [ui] [AppStore] loading 9 repositories from store
2023-06-06T21:29:53.553Z - info: [ui] [AppStore] found account: mlynarskim (Mateuszn Młynarski)
2023-06-06T21:29:53.589Z - info: [ui] [BranchPruner] Last prune took place 3 hours ago - skipping
2023-06-06T21:29:53.991Z - info: [ui] launching: 3.2.3 (Mac OS 13.4.0)
2023-06-06T21:29:53.994Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2023-06-06T21:29:54.108Z - info: [ui] Subscribed 'mlynarskim' to Alive channel
2023-06-06T21:29:56.798Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Rules - mlynarskim (has token)
2023-06-06T21:38:51.200Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: mediumish-gohugo-theme - mlynarskim (has token)
2023-06-06T21:38:53.226Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 3.4s of which 0.0s paused, total 3.4s
2023-06-06T21:46:25.057Z - info: [ui] [AppStore] loading 9 repositories from store
2023-06-06T21:46:25.073Z - info: [ui] [AppStore] found account: mlynarskim (Mateuszn Młynarski)
2023-06-06T21:46:25.091Z - info: [ui] [BranchPruner] Last prune took place 3 hours ago - skipping
2023-06-06T21:46:25.477Z - info: [ui] launching: 3.2.3 (Mac OS 13.4.0)
2023-06-06T21:46:25.477Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2023-06-06T21:46:25.606Z - info: [ui] Subscribed 'mlynarskim' to Alive channel
2023-06-06T21:46:38.349Z - info: [ui] [Timing] Action 'create commit' for 'mlynarskim/Rules' took 0.074s
2023-06-06T21:46:49.506Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Rules - mlynarskim (has token)

### Screenshots

<img width="956" alt="Screenshot 2023-06-06 at 23 49 48" src="https://github.com/desktop/desktop/assets/51798227/e5572778-0663-476a-8446-01800d1dd1e9">

**Comment by steveward** [comment]
@mlynarskim thanks for the issue. Unfortunately I'm not seeing any push output in the log file you shared. Is that the entirety of the log?

**Comment by mlynarskim** [comment]
Yes this is the whole log, it is possible that it does not display this problem because the commit was not completed, I also noticed that the problem with pushing the commit to master occurs when there are more files e.g. 5-10. 
I am attaching the logs from the last 3 days, maybe this will help somehow.

[2023-06-07.desktop.production.log](https://github.com/desktop/desktop/files/11678938/2023-06-07.desktop.production.log)
[2023-06-06.desktop.production.log](https://github.com/desktop/desktop/files/11678939/2023-06-06.desktop.production.log)
[2023-06-05.desktop.production.log](https://github.com/desktop/desktop/files/11678940/2023-06-05.desktop.production.log)

**Comment by steveward** [comment]
Thanks, that output did show something interesting:

```
2023-06-06T15:47:51.420Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 4.2s of which 32294.9s paused, total 32299.1s
```

For some reason the background fetch there seemed to hang. I do see a fetch error that's likely correlated:

```
2023-06-06T11:01:25.693Z - warn: [ui] getFetchPollInterval: failed for mlynarskim/Rules
TypeError: Failed to fetch
```

This doesn't seem to be happening consistently, though. Have you tried pushing via the command line to see if that operation successfully completes?

**Comment by mlynarskim** [comment]
I have not tried via the command line, the repository treats it as a backup for the application, nothing special. I thought it was worth reporting, if there is a problem with the commit next time, will try via the command line.

**Comment by steveward** [comment]
Thanks for the update, I'll close this out for the time being.
