### ISSUE TITLE
Adding any Repository says "Untrusted Repository"

### ISSUE THREAD

**Issue by RudraSen2** [desktop/desktop#16967]
### The problem

Whenever I add any of my local repository in the app, it says, "Untrusted Repository". I don't know why this is happening and it is very annoying that I cannot add all of my repos at once because of this.  

### Release version

Version 3.2.6 (x64)

### Operating system

Windows 11 Insider Preview Developer 23481.1000

### Steps to reproduce the behavior

I don't know if this is happening only to me or to everyone. Here are the steps to reproduce:

1. Install/Open GitHub Desktop
2. If you Drag n' Drop, nothing happens. If you add any repository, this comes up:
![image](https://github.com/desktop/desktop/assets/91307601/79970a45-d5cd-44a6-9773-2ea246b55dc2)
3. But this is my repository from my org account. Even adding personal repos shows the same thing.

### Log files

2023-06-23T12:14:43.262Z - info: [main] Received possible protocol arguments: 2
2023-06-23T12:14:43.306Z - error: [main] Malformed launch arguments received: C:\Users\Rudra\AppData\Local\GitHubDesktop\app-3.2.6\GitHubDesktop.exe,--squirrel-firstrun
2023-06-23T12:14:43.306Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\Rudra\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at te (C:\Users\Rudra\AppData\Local\GitHubDesktop\app-3.2.6\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\Rudra\AppData\Local\GitHubDesktop\app-3.2.6\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\Rudra\AppData\Local\GitHubDesktop\app-3.2.6\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\Rudra\AppData\Local\GitHubDesktop\app-3.2.6\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\Rudra\AppData\Local\GitHubDesktop\app-3.2.6\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
2023-06-23T12:14:43.306Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\Rudra\Desktop\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at te (C:\Users\Rudra\AppData\Local\GitHubDesktop\app-3.2.6\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\Rudra\AppData\Local\GitHubDesktop\app-3.2.6\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\Rudra\AppData\Local\GitHubDesktop\app-3.2.6\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\Rudra\AppData\Local\GitHubDesktop\app-3.2.6\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\Rudra\AppData\Local\GitHubDesktop\app-3.2.6\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
2023-06-23T12:14:43.306Z - error: [main] Toast activator CLSID not found in any of the shortcuts. Falling back to known CLSIDs.
2023-06-23T12:14:43.306Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-06-23T12:14:48.408Z - info: [ui] [AppStore] loading 0 repositories from store
2023-06-23T12:14:49.083Z - info: [ui] launching: 3.2.6 (Windows 10.0.23481)
2023-06-23T12:14:49.209Z - info: [ui] execPath: 'C:\Users\Rudra\AppData\Local\GitHubDesktop\app-3.2.6\GitHubDesktop.exe'
2023-06-23T12:14:51.722Z - info: [ui] [Welcome] no sign in step found. ignoring...
2023-06-23T12:14:51.724Z - info: [ui] [Welcome] no sign in step found. ignoring...
2023-06-23T12:14:52.000Z - info: [ui] Opt in reported.
2023-06-23T12:14:58.792Z - info: [ui] [Welcome] no sign in step found. ignoring...
2023-06-23T12:15:01.988Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 12.288s)
2023-06-23T12:17:11.540Z - info: [ui] [Welcome] no sign in step found. ignoring...
2023-06-23T12:17:13.216Z - info: [ui] [Welcome] no sign in step found. ignoring...
2023-06-23T12:19:45.471Z - info: [ui] [Welcome] no sign in step found. ignoring...
2023-06-23T12:19:46.810Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
2023-06-23T12:19:46.812Z - info: [ui] [SignInStore] initializing OAuth flow
2023-06-23T12:19:46.814Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=b7afbca8-30f9-41f0-95a0-57129cef5ba3
2023-06-23T12:19:46.818Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2023-06-23T12:19:49.580Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2023-06-23T12:19:58.249Z - info: [main] Received possible protocol arguments: 4
2023-06-23T12:19:58.354Z - info: [main] Processing protocol url
2023-06-23T12:19:58.354Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2023-06-23T12:19:58.354Z - info: [ui] [Dispatcher] requesting authenticated user
2023-06-23T12:19:58.354Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2023-06-23T12:20:01.641Z - info: [ui] [SignInStore] account resolved
2023-06-23T12:20:01.654Z - info: [ui] [AppStore] adding account RudraSen2 (Rudra Sen) to store
2023-06-23T12:20:01.654Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2023-06-23T12:20:03.362Z - info: [ui] [Welcome] no sign in step found. ignoring...
2023-06-23T12:20:03.378Z - info: [ui] [Welcome] no sign in step found. ignoring...
2023-06-23T12:20:04.214Z - info: [ui] Executing getConfigValueInPath: git config -z --global user.name (took 2.495s)
2023-06-23T12:20:04.504Z - info: [ui] Subscribed 'RudraSen2' to Alive channel
2023-06-23T12:20:05.758Z - info: [ui] [Welcome] no sign in step found. ignoring...
2023-06-23T12:20:06.948Z - info: [ui] [Welcome] no sign in step found. ignoring...
2023-06-23T12:20:08.020Z - info: [ui] [Welcome] no sign in step found. ignoring...
2023-06-23T12:20:13.551Z - info: [ui] Executing setConfigValueInPath: git config --global --replace-all user.name Rudra Sen (took 1.658s)
2023-06-23T12:20:17.111Z - info: [ui] Executing setConfigValueInPath: git config --global --replace-all user.email rudra_sen@outlook.com (took 3.559s)
2023-06-23T12:20:17.248Z - info: [ui] [Welcome] no sign in step found. ignoring...

### Screenshots

![image](https://github.com/desktop/desktop/assets/91307601/79970a45-d5cd-44a6-9773-2ea246b55dc2)

### Additional context

None

**Comment by steveward** [comment]
@RudraSen2 thanks for the issue. Clicking the "add an exception for this directory" link in the error message will trust the directory and cause this warning to disappear. This is due to a security change in Git that happened last year (see https://github.com/desktop/desktop/issues/14336#issuecomment-1098294609). Let me know if you have any further issues.
