### ISSUE TITLE
Can't access github desktop

### ISSUE THREAD

**Issue by SeriaLudo** [desktop/desktop#17321]
### The problem

I can't see a window, access any settings, see any errors. I can't even see abou
<img width="297" alt="image" src="https://github.com/desktop/desktop/assets/56519491/edc0acfe-a44e-4ef0-b5aa-95beb3025cb3">

### Release version

3.3.1 - I think - can't access current version

### Operating system

Mac OS Ventura 13.4.1

### Steps to reproduce the behavior

1. Launch gitHub desktop
2. Nothing happens. All options greyed out

### Log files

2023-08-31T18:47:45.851Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.247s)
2023-08-31T18:47:47.173Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 23 repositories took 10.0s of which 0.0s paused, total 10.0s
2023-08-31T18:47:56.676Z - error: [ui] PullRequestCoordinator: Error loading repositories
Error: Missing owner '1'
    at nt (/webpack:/app/src/lib/fatal-error.ts:3:9)
    at ot (/webpack:/app/src/lib/fatal-error.ts:47:12)
    at sI.constructor.toGitHubRepository (/webpack:/app/src/lib/stores/repositories-store.ts:117:7)
2023-08-31T18:47:56.791Z - info: [ui] Opt in reported.
2023-08-31T19:01:09.458Z - error: [ui] PullRequestCoordinator: Error loading repositories
Error: Missing owner '1'
    at nt (/webpack:/app/src/lib/fatal-error.ts:3:9)
    at ot (/webpack:/app/src/lib/fatal-error.ts:47:12)
    at sI.constructor.toGitHubRepository (/webpack:/app/src/lib/stores/repositories-store.ts:117:7)
2023-08-31T19:05:31.661Z - error: [ui] PullRequestCoordinator: Error loading repositories
Error: Missing owner '1'
    at nt (/webpack:/app/src/lib/fatal-error.ts:3:9)
    at ot (/webpack:/app/src/lib/fatal-error.ts:47:12)
    at hM.constructor.toGitHubRepository (/webpack:/app/src/lib/stores/repositories-store.ts:117:7)
2023-08-31T19:45:28.147Z - error: [ui] PullRequestCoordinator: Error loading repositories
Error: Missing owner '1'
    at nt (/webpack:/app/src/lib/fatal-error.ts:3:9)
    at ot (/webpack:/app/src/lib/fatal-error.ts:47:12)
    at hM.constructor.toGitHubRepository (/webpack:/app/src/lib/stores/repositories-store.ts:117:7)
2023-08-31T20:23:12.285Z - error: [ui] PullRequestCoordinator: Error loading repositories
Error: Missing owner '1'
    at nt (/webpack:/app/src/lib/fatal-error.ts:3:9)
    at ot (/webpack:/app/src/lib/fatal-error.ts:47:12)
    at hM.constructor.toGitHubRepository (/webpack:/app/src/lib/stores/repositories-store.ts:117:7)
2023-08-31T20:36:42.371Z - error: [ui] PullRequestCoordinator: Error loading repositories
Error: Missing owner '1'
    at nt (/webpack:/app/src/lib/fatal-error.ts:3:9)
    at ot (/webpack:/app/src/lib/fatal-error.ts:47:12)
    at hM.constructor.toGitHubRepository (/webpack:/app/src/lib/stores/repositories-store.ts:117:7)
2023-08-31T20:37:36.027Z - error: [ui] PullRequestCoordinator: Error loading repositories
Error: Missing owner '1'
    at nt (/webpack:/app/src/lib/fatal-error.ts:3:9)
    at ot (/webpack:/app/src/lib/fatal-error.ts:47:12)
    at hM.constructor.toGitHubRepository (/webpack:/app/src/lib/stores/repositories-store.ts:117:7)
2023-08-31T20:44:24.696Z - error: [ui] PullRequestCoordinator: Error loading repositories
Error: Missing owner '1'
    at nt (/webpack:/app/src/lib/fatal-error.ts:3:9)
    at ot (/webpack:/app/src/lib/fatal-error.ts:47:12)
    at hM.constructor.toGitHubRepository (/webpack:/app/src/lib/stores/repositories-store.ts:117:7)

**Comment by steveward** [comment]
Thanks for the report @SeriaLudo. Was GitHub Desktop previously working on your machine, or is this a fresh installation?

You can try running this command from the Terminal to see if it gets things working:

`rm -r ~/Library/Application\ Support/GitHub\ Desktop/IndexedDB`

Let me know if that helps.

**Comment by SeriaLudo** [comment]
Yeah it was working previously. I tried reinstalling, no luck. But then I deleted all cache files and reinstalled - fixed. Lmk whether I should close this or not. Thanks for getting back to me!

**Comment by steveward** [comment]
Glad to hear that got things working!
