### ISSUE TITLE
Interface issues.

### ISSUE THREAD

**Issue by Evilkeeper** [desktop/desktop#1735]
### Description

Faced several at the very start.
**-Menu at the top:**
Should <b>Repository</b> and <b>Branch</b> be inactive, while there is no repositiory?
They look like they are, but actually they are not. Plus while one tab (like <b>File</b>)
is open, when you move cursor through all those tab, it stucks at <b>Repository</b>,
then move cursor further to </b>Help</b> and then back to <b>Branch</b>. It will open.
So, looks like only those two tabs are conflicting with each other or some kind of.

**-Options:**
Switching a tab (to both "Git" and "Advanced") makes it play animation and close.
I want to take a look at those tab, not to close options.

### Version

**GitHub Desktop version:** 0.5.7

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Open <b>File</b> tab at the top menu;
2. Move cursor forward to <b>Help</b>, not fast, through every tab;
3. And back to <b>File</b>.

1. Open <b>File -> Options</b>;
2. Switch tab to any: "Git" or "Advanced".

**Expected behaviour:** Every tab will open at hover; I will open different tab in <b>Options</b>

**Actual behaviour:** Got stuck at <b>Repository</b>; <b>Options</b> closed.

**Reproduces how often:** 100%

### Logs

<i>Not sure if it's usefull.</i>

2017-05-24T08:36:40.918Z - error: Uncaught exception on main process
Error: Cannot find module '../screen'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\Michael\AppData\Local\GitHubDesktop\app-0.5.7\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as screen] (C:\Users\Michael\AppData\Local\GitHubDesktop\app-0.5.7\resources\electron.asar\browser\api\exports\electron.js:11:16)
    at o.exports (C:\Users\Michael\AppData\Local\GitHubDesktop\app-0.5.7\resources\app\main.js:12:10094)
    at new L (C:\Users\Michael\AppData\Local\GitHubDesktop\app-0.5.7\resources\app\main.js:1:37614)
    at g (C:\Users\Michael\AppData\Local\GitHubDesktop\app-0.5.7\resources\app\main.js:14:79619)
    at App.S.app.on (C:\Users\Michael\AppData\Local\GitHubDesktop\app-0.5.7\resources\app\main.js:14:80993)

#### Additional Information

-

**Comment by niik** [comment]
Thank you for opening this @Evilkeeper.

> Should Repository and Branch be inactive, while there is no repositiory?
> They look like they are, but actually they are not. Plus while one tab (like File)
> is open, when you move cursor through all those tab, it stucks at Repository,
> then move cursor further to Help and then back to Branch. It will open.
> So, looks like only those two tabs are conflicting with each other or some kind of.

I think this is captured in #1521 so please subscribe to that issue to follow along.

> Switching a tab (to both "Git" and "Advanced") makes it play animation and close.
> I want to take a look at those tab, not to close options.

This is captured in #1724 and was fixed in #1726 and will go out in the next release (probably today).

I'm gonna close this issue out since it seems like both these issues are addressed elsewhere.

**Comment by shiftkey** [comment]
Reopening this as I have a report of this ocurring with `0.5.9` and this OS:

> Windows 10 x64 (Version 1703, OS Build 15063.332), ie Creators Update GA.

https://gist.github.com/jstangroome/82f832dd66be0e77c9f6e338bff2bced

cc @jstangroome

**Comment by shiftkey** [comment]
Actually, I'll open a fresh issue for this.
