### ISSUE TITLE
Should have support for UTF8 files

### ISSUE THREAD

**Issue by BA-ajcardona-dev** [desktop/desktop#17662]
### The problem

It means that I am a Spanish speaker and we use the Ññ for some words, when adding regular expressions in my validations such as those observed when committing, my files leave with a ? inside a rhombus.

In addition to that I have configured my time zone and region in my Spanish speaking country and I also have git configured to work with utf8 files as attached in the second image

### Release version

3.3.5

### Operating system

Windows 10

### Steps to reproduce the behavior

Use a file that contains the letter ñ and verify as shown in the preview of the changes in the files

### Log files

2023-11-02T14:32:43.150Z - info: [ui] [BranchPruner] Last prune took place 16 hours ago - skipping
2023-11-02T14:33:12.970Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 26.608s)
2023-11-02T14:33:14.160Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/AtlantidaSA/BA-Jteller.git/': Could not resolve host: github.com

2023-11-02T14:33:27.920Z - info: [ui] Executing fastForwardBranches: git fetch . --show-forced-updates --no-write-fetch-head --stdin (took 11.252s)
2023-11-02T14:37:06.033Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.639s)
2023-11-02T14:42:14.963Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 6.147s)
2023-11-02T14:42:16.503Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.515s)
2023-11-02T14:42:18.601Z - info: [ui] Executing fastForwardBranches: git fetch . --show-forced-updates --no-write-fetch-head --stdin (took 1.340s)
2023-11-02T14:58:15.706Z - info: [ui] [BranchPruner] Last prune took place 16 hours ago - skipping
2023-11-02T15:12:54.756Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 22.040s)
2023-11-02T15:12:54.774Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/AtlantidaSA/BA-Jteller.git/': Failed to connect to github.com port 443 after 21078 ms: Couldn't connect to server

2023-11-02T15:13:00.421Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 5.645s)
2023-11-02T15:13:02.296Z - info: [ui] Executing fastForwardBranches: git fetch . --show-forced-updates --no-write-fetch-head --stdin (took 1.223s)
2023-11-02T15:18:30.437Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 21.719s)
2023-11-02T15:18:30.458Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/AtlantidaSA/BA-Jteller.git/': Failed to connect to github.com port 443 after 21078 ms: Couldn't connect to server

2023-11-02T15:18:33.574Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 3.113s)
2023-11-02T15:18:35.370Z - info: [ui] Executing fastForwardBranches: git fetch . --show-forced-updates --no-write-fetch-head --stdin (took 1.165s)
2023-11-02T15:24:05.351Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 21.643s)
2023-11-02T15:24:05.368Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/AtlantidaSA/BA-Jteller.git/': Failed to connect to github.com port 443 after 21064 ms: Couldn't connect to server

2023-11-02T15:24:23.199Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 17.829s)
2023-11-02T15:24:25.132Z - info: [ui] Executing fastForwardBranches: git fetch . --show-forced-updates --no-write-fetch-head --stdin (took 1.210s)
2023-11-02T15:29:48.665Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 2.945s)
2023-11-02T15:30:10.249Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 21.564s)
2023-11-02T15:30:12.120Z - info: [ui] Executing fastForwardBranches: git fetch . --show-forced-updates --no-write-fetch-head --stdin (took 1.197s)
2023-11-02T15:31:43.708Z - info: [ui] [Timing] Action 'checkout branch from list' for 'AtlantidaSA/BA-Jteller' took 0.001s
2023-11-02T15:31:45.183Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BA-Jteller - BA-ajcardona-dev (has token)
2023-11-02T15:31:49.188Z - info: [ui] Executing createStashEntry: git stash push -m !!GitHub_Desktop<Feature_JS0212_shenriquez_SIISAR-64> (took 3.679s)
2023-11-02T15:31:50.653Z - error: [ui] Could not load new contents for syntax highlighting
Error: ENOENT: no such file or directory, open 'C:\Users\ajcardona\Documents\GitHub\BA-Jteller\JS0212\nbactions-JS0212.xml'
2023-11-02T15:31:50.976Z - error: [ui] `git show HEAD:JS0212/nbactions-JS0212.xml` exited with an unexpected code: 128.
stderr:
fatal: path 'JS0212/nbactions-JS0212.xml' does not exist in 'HEAD'

(The error was parsed as 32: The path does not exist on disk.)
2023-11-02T15:31:50.977Z - error: [ui] Could not load old contents for syntax highlighting
GitError: The path does not exist on disk.
    at C:\Users\ajcardona\AppData\Local\GitHubDesktop\app-3.3.4\webpack:\app\src\lib\git\core.ts:247:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at C:\Users\ajcardona\AppData\Local\GitHubDesktop\app-3.3.4\webpack:\app\src\lib\trampoline\trampoline-environment.ts:61:13
    at C:\Users\ajcardona\AppData\Local\GitHubDesktop\app-3.3.4\webpack:\app\src\lib\trampoline\trampoline-tokens.ts:33:5
    at C:\Users\ajcardona\AppData\Local\GitHubDesktop\app-3.3.4\webpack:\app\src\lib\git\show.ts:93:9
    at async Promise.all (index 0)
    at C:\Users\ajcardona\AppData\Local\GitHubDesktop\app-3.3.4\webpack:\app\src\ui\diff\syntax-highlighting\index.ts:111:23
    at Ax.loadFileContentsIfNeeded (C:\Users\ajcardona\AppData\Local\GitHubDesktop\app-3.3.4\webpack:\app\src\ui\diff\seamless-diff-switcher.tsx:258:11)
2023-11-02T15:31:53.180Z - info: [ui] [Timing] Action 'stash and checkout' for 'AtlantidaSA/BA-Jteller' took 7.997s
2023-11-02T15:32:29.388Z - info: [ui] No submodules found. Skipping "git submodule status"
2023-11-02T15:33:46.941Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BA-Jteller - BA-ajcardona-dev (has token)
2023-11-02T15:34:08.507Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 21.553s)
2023-11-02T15:34:08.528Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/AtlantidaSA/BA-Jteller.git/': Failed to connect to github.com port 443 after 21067 ms: Couldn't connect to server

2023-11-02T15:34:30.149Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 21.619s)
2023-11-02T15:34:31.886Z - info: [ui] Executing fastForwardBranches: git fetch . --show-forced-updates --no-write-fetch-head --stdin (took 1.219s)
2023-11-02T15:35:37.482Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BA-Jteller - BA-ajcardona-dev (has token)
2023-11-02T15:35:59.087Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 21.580s)
2023-11-02T15:35:59.101Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/AtlantidaSA/BA-Jteller.git/': Failed to connect to github.com port 443 after 21082 ms: Couldn't connect to server

2023-11-02T15:36:10.591Z - info: [ui] [AppStore] removing account BA-ajcardona-dev (Alessandro Cardona) from store
2023-11-02T15:36:10.594Z - info: [ui] Unubscribed 'BA-ajcardona-dev' from Alive channel
2023-11-02T15:36:19.893Z - info: [ui] [SignInStore] initializing OAuth flow
2023-11-02T15:36:19.895Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=d521e7ae-3554-4a64-87d4-aad337213c75
2023-11-02T15:36:20.821Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 21.689s)
2023-11-02T15:36:23.849Z - info: [ui] Executing fastForwardBranches: git fetch . --show-forced-updates --no-write-fetch-head --stdin (took 2.377s)
2023-11-02T15:36:29.718Z - info: [main] Received possible protocol arguments: 4
2023-11-02T15:36:29.721Z - info: [main] Processing protocol url
2023-11-02T15:36:29.747Z - info: [ui] [Dispatcher] requesting authenticated user
2023-11-02T15:36:45.432Z - info: [ui] [SignInStore] account resolved
2023-11-02T15:36:45.433Z - info: [ui] [AppStore] adding account BA-ajcardona-dev (Alessandro Cardona) to store
2023-11-02T15:36:45.735Z - info: [ui] Subscribed 'BA-ajcardona-dev' to Alive channel
2023-11-02T15:36:48.452Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BA-Jteller - BA-ajcardona-dev (has token)
2023-11-02T15:36:49.989Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.528s)
2023-11-02T15:36:58.585Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 8.594s)
2023-11-02T15:37:00.322Z - info: [ui] Executing fastForwardBranches: git fetch . --show-forced-updates --no-write-fetch-head --stdin (took 1.062s)
2023-11-02T15:37:32.280Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BA-Jteller - BA-ajcardona-dev (has token)
2023-11-02T15:37:35.895Z - info: [ui] [Timing] Action 'create branch' for 'AtlantidaSA/BA-Jteller' took 5.024s
2023-11-02T15:45:50.824Z - warn: [ui] getFetchPollInterval: failed for AtlantidaSA/BA-Jteller
TypeError: Failed to fetch
    at Ot (C:\Users\ajcardona\AppData\Local\GitHubDesktop\app-3.3.4\webpack:\app\src\lib\http.ts:152:10)
    at Rn.request (C:\Users\ajcardona\AppData\Local\GitHubDesktop\app-3.3.4\webpack:\app\src\lib\api.ts:1740:28)
    at Rn.getFetchPollInterval (C:\Users\ajcardona\AppData\Local\GitHubDesktop\app-3.3.4\webpack:\app\src\lib\api.ts:1778:35)
    at qo.getFetchInterval (C:\Users\ajcardona\AppData\Local\GitHubDesktop\app-3.3.4\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:136:38)
    at qo.performAndScheduleFetch (C:\Users\ajcardona\AppData\Local\GitHubDesktop\app-3.3.4\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:117:33)
2023-11-02T15:54:52.849Z - info: [ui] [Timing] Action 'checkout branch from list' for 'AtlantidaSA/BA-Jteller' took 0.000s
2023-11-02T15:54:53.905Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: BA-Jteller - BA-ajcardona-dev (has token)
2023-11-02T15:54:57.742Z - info: [ui] Executing createStashEntry: git stash push -m !!GitHub_Desktop<pruebasRemesas2023-11-02> (took 3.518s)
2023-11-02T15:55:01.750Z - info: [ui] [Timing] Action 'stash and checkout' for 'AtlantidaSA/BA-Jteller' took 7.845s
2023-11-02T15:55:19.374Z - info: [ui] [AppStore. _popStashEntry] popped stash with commit id c1e8d27611abb5af82e38097a59e7dc5db10cde1
2023-11-02T16:19:39.801Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-11-02T16:19:44.116Z - info: [ui] [AppStore] loading 1 repositories from store
2023-11-02T16:19:44.117Z - info: [ui] [AppStore] found account: BA-ajcardona-dev (Alessandro Cardona)
2023-11-02T16:19:44.333Z - info: [ui] [BranchPruner] Last prune took place 17 hours ago - skipping
2023-11-02T16:19:45.225Z - info: [ui] Subscribed 'BA-ajcardona-dev' to Alive channel
2023-11-02T16:19:45.233Z - info: [ui] launching: 3.3.5 (Windows 10.0.19045)
2023-11-02T16:19:45.233Z - info: [ui] execPath: 'C:\Users\ajcardona\AppData\Local\GitHubDesktop\app-3.3.5\GitHubDesktop.exe'
2023-11-02T16:19:50.509Z - info: [ui] Executing getRemotes: git remote -v (took 4.407s)
2023-11-02T16:19:50.510Z - info: [ui] Executing getCommits: git log c9c16a52558198f42c71d934263b208e4b31ce3d --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 4.627s)
2023-11-02T16:19:51.295Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 6.093s)
2023-11-02T16:19:54.309Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 2.446s)
2023-11-02T16:19:55.697Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.386s)
2023-11-02T16:19:57.903Z - info: [ui] Executing fastForwardBranches: git fetch . --show-forced-updates --no-write-fetch-head --stdin (took 1.480s)

### Screenshots

![imagen](https://github.com/desktop/desktop/assets/113557526/ef90af40-7fa7-48f5-9df8-7c9ae8218872)
![imagen](https://github.com/desktop/desktop/assets/113557526/fe90efe0-8d86-4841-9786-4ecd5b3e2ea7)

**Comment by steveward** [comment]
Thanks for the report @BA-ajcardona-dev. I was unable to reproduce this with UTF-8 (confirmed in VSCode):

<img width="236" alt="Screenshot 2023-11-02 at 2 46 07 PM" src="https://github.com/desktop/desktop/assets/721500/aff20a24-2745-401b-8358-239bbb825541">

 Can you confirm you're using UTF-8?

I'm going to add this to https://github.com/desktop/desktop/issues/3923 where we are tracking encoding issues for diffs.

**Comment by BA-ajcardona-dev** [comment]
Hi @steveward I am using netbeans 18 and java 8, and I am seeing if it is encoding my project in utf8

![imagen](https://github.com/desktop/desktop/assets/113557526/4e5b1aff-931a-4578-a3e8-41fdff9d32aa)
