### ISSUE TITLE
Can't clone a repository, specifically in my computer

### ISSUE THREAD

**Issue by MrSirHaku** [desktop/desktop#17695]
### The problem

When I go into GitHub Desktop and copy the URL that I need to start on my studio project, the "Cloning [Title_Name]" just continues on for an extended amount of time. I tried cloning something else before as well and left it for about 2 hours and it was still on the same screen. 

Keep in mind that the projects are not big at all and that one only has the preset Unity project stuff.

### Release version

Version 3.3.5

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Go to "Clone a repository from the Internet"
2. Go to "URL"
3. Copy URL 
4. Paste in "Repository URL or GitHub username and repository"
5. Click "Clone"
6. Observe. 

### Log files

2023-11-07T22:48:34.015Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-11-07T22:48:34.402Z - info: [ui] [AppStore] loading 0 repositories from store
2023-11-07T22:48:34.402Z - info: [ui] [AppStore] found account: MrSirHaku (MrSirHaku)
2023-11-07T22:48:34.572Z - info: [ui] launching: 3.3.3 (Windows 10.0.22621)
2023-11-07T22:48:34.574Z - info: [ui] execPath: 'C:\ProgramData\jhuyn\GitHubDesktop\app-3.3.3\GitHubDesktop.exe'
2023-11-07T22:48:34.813Z - info: [ui] Subscribed 'MrSirHaku' to Alive channel
2023-11-07T22:48:34.843Z - info: [ui] Stats reported.
2023-11-07T22:49:45.624Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/LOcadiz64/Star-Beads.git - MrSirHaku (has token)
2023-11-07T22:50:05.229Z - error: [ui] Trampoline client error
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2023-11-07T22:50:09.537Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-11-07T22:50:10.508Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-11-07T22:53:40.960Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-11-07T22:53:41.295Z - info: [ui] [AppStore] loading 0 repositories from store
2023-11-07T22:53:41.296Z - info: [ui] [AppStore] found account: MrSirHaku (MrSirHaku)
2023-11-07T22:53:41.434Z - info: [ui] launching: 3.3.5 (Windows 10.0.22621)
2023-11-07T22:53:41.442Z - info: [ui] execPath: 'C:\ProgramData\jhuyn\GitHubDesktop\app-3.3.5\GitHubDesktop.exe'
2023-11-07T22:53:41.661Z - info: [ui] Subscribed 'MrSirHaku' to Alive channel
2023-11-07T22:55:02.655Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/LOcadiz64/Star-Beads.git - MrSirHaku (has token)
2023-11-07T22:55:22.370Z - error: [ui] Trampoline client error
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2023-11-07T22:55:54.858Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-11-07T22:55:55.162Z - info: [ui] [AppStore] loading 0 repositories from store
2023-11-07T22:55:55.162Z - info: [ui] [AppStore] found account: MrSirHaku (MrSirHaku)
2023-11-07T22:55:55.289Z - info: [ui] launching: 3.3.5 (Windows 10.0.22621)
2023-11-07T22:55:55.292Z - info: [ui] execPath: 'C:\ProgramData\jhuyn\GitHubDesktop\app-3.3.5\GitHubDesktop.exe'
2023-11-07T22:55:55.540Z - info: [ui] Subscribed 'MrSirHaku' to Alive channel
2023-11-07T22:56:12.440Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/LOcadiz64/Star-Beads.git - MrSirHaku (has token)
2023-11-07T22:56:31.850Z - error: [ui] Trampoline client error
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2023-11-07T23:03:33.308Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-11-07T23:07:51.824Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\jhuyn\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\jhuyn\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\jhuyn\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\jhuyn\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\jhuyn\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\jhuyn\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2023-11-07T23:07:51.831Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\jhuyn\Desktop\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\jhuyn\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\jhuyn\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\jhuyn\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\jhuyn\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\jhuyn\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2023-11-07T23:07:51.831Z - error: [main] Toast activator CLSID not found in any of the shortcuts. Falling back to known CLSIDs.
2023-11-07T23:07:51.831Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-11-07T23:07:52.507Z - info: [main] Received possible protocol arguments: 2
2023-11-07T23:07:52.519Z - error: [main] Malformed launch arguments received: C:\Users\jhuyn\AppData\Local\GitHubDesktop\app-3.3.5\GitHubDesktop.exe,--squirrel-firstrun
2023-11-07T23:07:52.520Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-11-07T23:07:52.924Z - info: [ui] [AppStore] loading 0 repositories from store
2023-11-07T23:07:52.927Z - info: [ui] [AppStore] found account: MrSirHaku (MrSirHaku)
2023-11-07T23:07:53.343Z - info: [ui] launching: 3.3.5 (Windows 10.0.22621)
2023-11-07T23:07:53.406Z - info: [ui] execPath: 'C:\Users\jhuyn\AppData\Local\GitHubDesktop\app-3.3.5\GitHubDesktop.exe'
2023-11-07T23:07:53.908Z - info: [ui] Subscribed 'MrSirHaku' to Alive channel
2023-11-07T23:07:54.061Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.030s)
2023-11-07T23:09:18.014Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/LOcadiz64/Star-Beads.git - MrSirHaku (has token)
2023-11-07T23:09:37.817Z - error: [ui] Trampoline client error
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2023-11-07T23:24:23.814Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-11-07T23:24:24.141Z - info: [ui] [AppStore] loading 0 repositories from store
2023-11-07T23:24:24.141Z - info: [ui] [AppStore] found account: MrSirHaku (MrSirHaku)
2023-11-07T23:24:24.262Z - info: [ui] launching: 3.3.5 (Windows 10.0.22621)
2023-11-07T23:24:24.263Z - info: [ui] execPath: 'C:\Users\jhuyn\AppData\Local\GitHubDesktop\app-3.3.5\GitHubDesktop.exe'
2023-11-07T23:24:24.444Z - info: [ui] Subscribed 'MrSirHaku' to Alive channel
2023-11-07T23:25:29.187Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/LOcadiz64/Star-Beads.git - MrSirHaku (has token)
2023-11-07T23:25:48.602Z - error: [ui] Trampoline client error
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2023-11-07T23:29:00.028Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-11-07T23:29:00.331Z - info: [ui] [AppStore] loading 0 repositories from store
2023-11-07T23:29:00.332Z - info: [ui] [AppStore] found account: MrSirHaku (MrSirHaku)
2023-11-07T23:29:00.453Z - info: [ui] launching: 3.3.5 (Windows 10.0.22621)
2023-11-07T23:29:00.454Z - info: [ui] execPath: 'C:\Users\jhuyn\AppData\Local\GitHubDesktop\app-3.3.5\GitHubDesktop.exe'
2023-11-07T23:29:00.723Z - info: [ui] Subscribed 'MrSirHaku' to Alive channel
2023-11-07T23:29:42.030Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/LOcadiz64/Star-Beads.git - MrSirHaku (has token)
2023-11-07T23:30:01.375Z - error: [ui] Trampoline client error
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2023-11-07T23:32:09.414Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'github.com/LOcadiz64/Star-Beads.git'
2023-11-07T23:32:09.632Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- github.com/LOcadiz64/Star-Beads.git C:\Users\jhuyn\Desktop\GitHub\Star-Beads` exited with an unexpected code: 128.
stderr:
fatal: repository 'github.com/LOcadiz64/Star-Beads.git' does not exist

2023-11-07T23:33:48.030Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/LOcadiz64/Star-Beads.git - MrSirHaku (has token)
2023-11-07T23:34:07.391Z - error: [ui] Trampoline client error
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2023-11-07T23:36:19.937Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/LOcadiz64/Star-Beads.git - MrSirHaku (has token)
2023-11-07T23:36:39.270Z - error: [ui] Trampoline client error
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)

**Comment by steveward** [comment]
@MrSirHaku can you verify you have access to this repository, and that it exists?

`fatal: repository 'github.com/LOcadiz64/Star-Beads.git' does not exist`

Are you running any antivirus or security software on this machine that also could be causing this? This error seems to indicate that may be the case:

```
2023-11-07T23:34:07.391Z - error: [ui] Trampoline client error
Error: read ECONNRESET
```
