### ISSUE TITLE
GetVSyncParametersIfAvailable() failed for 1 times!

### ISSUE THREAD

**Issue by rizitis** [desktop/desktop#17789]
### The problem

App`s screen going white, this happens if i use:
 Wayland or Xorg. 
Intel GPU or  Nvidia
Gnome-45 or XFCE

### Release version

flatpak 3.3.5

### Operating system

Slackware64-current

### Steps to reproduce the behavior

1. install github-desktop 3.3.5 flatpak 
2. Ran app either from desktop.entry or from cli
3. app getting white.

### Log files

```
[47:1129/203239.921591:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[47:1129/203248.880012:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at U (/app/github-desktop/resources/app/main.js:2:211774)
    at BrowserWindow.<anonymous> (/app/github-desktop/resources/app/main.js:2:216319)
    at BrowserWindow.emit (node:events:525:35)
```

### Screenshots

![github-electron-crash](https://github.com/desktop/desktop/assets/412135/ae8f2ac9-4f07-4794-a4f9-1f11b207adf7)

### Additional context

I think its electron problem https://github.com/electron/electron/issues/32760#issuecomment-1785162315

**Comment by niik** [comment]
Hey @rizitis, thanks for reaching out and for including a screen recording, that's always helpful. Unfortunately this appears to be a linux-specific problem and GitHub Desktop doesn't officially support Linux so you would probably have better luck opening an issue in the [unofficial Linux fork](https://github.com/shiftkey/desktop).

That said I will mention that it's possible to set the environment variable `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION` in order to force GitHub Desktop to do software rendering. I imagine that would work on Linux as well. Hope that helps!
