### ISSUE TITLE
GitHub Desktop not recognizing my PyCharm as an external editor

### ISSUE THREAD

**Issue by sunnyspectra** [desktop/desktop#17781]
### The problem

I have PyCharm installed and when I go into GitHub Desktop's integrations tab and open the drop down menu, PyCharm is not being recognized as an external editor for me to use.

### Release version

Version 3.3.5 (x64)

### Operating system

Windows 10

### Log files

2023-11-29T01:17:36.298Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2023-11-29T01:17:36.927Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
    at yO.constructor.post (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stats\stats-store.ts:1103:5)
    at yO.constructor.reportStats (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stats\stats-store.ts:482:35)
2023-11-29T01:17:37.522Z - error: [ui] Error checking for updates
undefined: 
2023-11-29T01:17:38.276Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/theenkfree/CS3337Fall2023.git/': Could not resolve host: github.com

2023-11-29T01:33:37.260Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 965.772s)
2023-11-29T01:33:37.480Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
TypeError: Failed to fetch
    at un (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\http.ts:152:10)
    at Zn.request (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1740:28)
    at Zn.fetchPushControl (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1590:35)
    at Za.refreshBranchProtectionState (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:1172:37)
    at C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:5027:20
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Za.withPushPullFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4536:5)
    at Za.performFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4978:5)
    at Dc.performAndScheduleFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2023-11-29T01:33:37.483Z - info: [ui] [fetchAllRepoRulesets] unable to fetch all repo rulesets | repos/theenkfree/CS3337Fall2023/rulesets
TypeError: Failed to fetch
    at un (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\http.ts:152:10)
    at Zn.request (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1740:28)
    at Zn.fetchAllRepoRulesets (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1662:35)
    at Za.refreshBranchProtectionState (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:1177:40)
    at C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:5022:32
    at Za.withPushPullFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4536:5)
    at Za.performFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4978:5)
    at Dc.performAndScheduleFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2023-11-29T01:33:37.486Z - info: [ui] [fetchRepoRulesForBranch] unable to fetch repo rules for branch: main | repos/theenkfree/CS3337Fall2023/rules/branches/main
TypeError: Failed to fetch
    at un (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\http.ts:152:10)
    at Zn.request (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1740:28)
    at Zn.fetchRepoRulesForBranch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1641:35)
    at Za.refreshBranchProtectionState (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:1198:39)
    at C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:5022:32
    at Za.withPushPullFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4536:5)
    at Za.performFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4978:5)
    at Dc.performAndScheduleFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2023-11-29T01:33:39.604Z - warn: [ui] getFetchPollInterval: failed for theenkfree/CS3337Fall2023
TypeError: Failed to fetch
    at un (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\http.ts:152:10)
    at Zn.request (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1740:28)
    at Zn.getFetchPollInterval (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1778:35)
    at Dc.getFetchInterval (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:136:38)
    at Dc.performAndScheduleFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:117:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29T02:34:00.452Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 2.340s)
2023-11-29T02:34:01.756Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.286s)
2023-11-29T02:34:03.029Z - info: [ui] [fetchAllRepoRulesets] unable to fetch all repo rulesets | repos/theenkfree/CS3337Fall2023/rulesets
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at hn (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\http.ts:178:11)
    at Zn.fetchAllRepoRulesets (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1663:7)
    at Za.refreshBranchProtectionState (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:1177:15)
    at C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:5022:32
    at Za.withPushPullFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4536:5)
    at Za.performFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4978:5)
    at Dc.performAndScheduleFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2023-11-29T02:34:03.230Z - info: [ui] [fetchRepoRulesForBranch] unable to fetch repo rules for branch: main | repos/theenkfree/CS3337Fall2023/rules/branches/main
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at hn (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\http.ts:178:11)
    at Zn.fetchRepoRulesForBranch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1642:7)
    at Za.refreshBranchProtectionState (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:1198:15)
    at C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:5022:32
    at Za.withPushPullFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4536:5)
    at Za.performFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4978:5)
    at Dc.performAndScheduleFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2023-11-29T03:06:02.655Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 2.530s)
2023-11-29T03:06:03.913Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.236s)
2023-11-29T03:06:04.903Z - info: [ui] [fetchAllRepoRulesets] unable to fetch all repo rulesets | repos/theenkfree/CS3337Fall2023/rulesets
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at hn (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\http.ts:178:11)
    at Zn.fetchAllRepoRulesets (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1663:7)
    at Za.refreshBranchProtectionState (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:1177:15)
    at C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:5022:32
    at Za.withPushPullFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4536:5)
    at Za.performFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4978:5)
    at Dc.performAndScheduleFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2023-11-29T03:06:05.130Z - info: [ui] [fetchRepoRulesForBranch] unable to fetch repo rules for branch: main | repos/theenkfree/CS3337Fall2023/rules/branches/main
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at hn (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\http.ts:178:11)
    at Zn.fetchRepoRulesForBranch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1642:7)
    at Za.refreshBranchProtectionState (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:1198:15)
    at C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:5022:32
    at Za.withPushPullFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4536:5)
    at Za.performFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4978:5)
    at Dc.performAndScheduleFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2023-11-29T03:59:45.321Z - error: [ui] Error checking for updates
undefined: 
2023-11-29T03:59:45.420Z - info: [ui] [BranchPruner] Last prune took place 8 hours ago - skipping
2023-11-29T03:59:45.779Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
    at yO.constructor.post (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stats\stats-store.ts:1103:5)
    at yO.constructor.reportStats (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stats\stats-store.ts:482:35)
2023-11-29T03:59:46.032Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/theenkfree/CS3337Fall2023.git/': Could not resolve host: github.com

2023-11-29T03:59:46.507Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
TypeError: Failed to fetch
    at un (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\http.ts:152:10)
    at Zn.request (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1740:28)
    at Zn.fetchPushControl (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1590:35)
    at Za.refreshBranchProtectionState (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:1172:37)
    at C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:5027:20
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Za.withPushPullFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4536:5)
    at Za.performFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4978:5)
    at Dc.performAndScheduleFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2023-11-29T03:59:46.510Z - info: [ui] [fetchAllRepoRulesets] unable to fetch all repo rulesets | repos/theenkfree/CS3337Fall2023/rulesets
TypeError: Failed to fetch
    at un (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\http.ts:152:10)
    at Zn.request (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1740:28)
    at Zn.fetchAllRepoRulesets (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1662:35)
    at Za.refreshBranchProtectionState (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:1177:40)
    at C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:5022:32
    at Za.withPushPullFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4536:5)
    at Za.performFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4978:5)
    at Dc.performAndScheduleFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2023-11-29T03:59:46.513Z - info: [ui] [fetchRepoRulesForBranch] unable to fetch repo rules for branch: main | repos/theenkfree/CS3337Fall2023/rules/branches/main
TypeError: Failed to fetch
    at un (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\http.ts:152:10)
    at Zn.request (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1740:28)
    at Zn.fetchRepoRulesForBranch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1641:35)
    at Za.refreshBranchProtectionState (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:1198:39)
    at C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:5022:32
    at Za.withPushPullFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4536:5)
    at Za.performFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\app-store.ts:4978:5)
    at Dc.performAndScheduleFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:102:7)
2023-11-29T03:59:49.154Z - warn: [ui] getFetchPollInterval: failed for theenkfree/CS3337Fall2023
TypeError: Failed to fetch
    at un (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\http.ts:152:10)
    at Zn.request (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1740:28)
    at Zn.getFetchPollInterval (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\api.ts:1778:35)
    at Dc.getFetchInterval (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:136:38)
    at Dc.performAndScheduleFetch (C:\Users\sleng2\AppData\Local\GitHubDesktop\app-3.3.5\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:117:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

### Screenshots

![image](https://github.com/desktop/desktop/assets/93362448/3d7505f7-4b90-4cf5-a0f0-99f1b1164514)

### Additional context

Tried adding PyCharm into environment variables and restarting the system. Didn't work

**Comment by steveward** [comment]
Thanks for the issue @sunnyspectra, I'm taking. a look at this in https://github.com/desktop/desktop/issues/17738 so you can follow along there.

**Comment by steveward** [comment]
@sunnyspectra I looked into this and PyCharm is showing up without issue. Did you possibly install PyCharm while GitHub Desktop was open? If so, try restarting GitHub Desktop to see if that helps.

**Comment by sunnyspectra** [comment]
My PyCharm was installed before I opened GitHub. I've tried adding it into my computer's environment variables, restarting GitHub Desktop, but it is still not showing up. I haven't tried the uninstalling and reinstalling Desktop like the other user on the other issue tried though.

**Comment by steveward** [comment]
Did you install it the standard installation method or JetBrains Toolbox?

**Comment by sunnyspectra** [comment]
I went on their site to install it, so I presume that would be the standard method.
