### ISSUE TITLE
Github Desktop Freezes

### ISSUE THREAD

**Issue by ngsea123** [desktop/desktop#17871]
### The problem

Whenever I open up Github Desktop, the window freezes after a few seconds and I am unable to do anything. I've tried uninstalling and reinstalling Github Desktop, but no matter what I do, Github always freezes. I suspect the repository is corrupted, but I want to know how to move onto another repository before Github Desktop freezes again.
![gitfreeze](https://github.com/desktop/desktop/assets/111990933/c8defefd-2902-4015-8b98-3ee7a9386f94)

### Release version

Windows-64 Version

### Operating system

Windows 11

### Screenshots

![gitfreeze](https://github.com/desktop/desktop/assets/111990933/c66a48d1-390b-4b16-b7ed-ba3ba3536957)

**Comment by steveward** [comment]
Thanks for the report @ngsea123. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by ngsea123** [comment]
> Thanks for the report @ngsea123. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

I can't do that either. It just freezes completely and I'm not able to do anything.

**Comment by niik** [comment]
> I can't do that either. It just freezes completely and I'm not able to do anything.

Hey @ngsea123, could you go look in `%APPDATA%\GitHub Desktop\logs\`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by ngsea123** [comment]
> > I can't do that either. It just freezes completely and I'm not able to do anything.
> 
> Hey @ngsea123, could you go look in `%APPDATA%\GitHub Desktop\logs\`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

Don't recall the exact date, but it was around 12/10 to 12/13.

[2023-12-10.desktop.production.log](https://github.com/desktop/desktop/files/13760413/2023-12-10.desktop.production.log)
[2023-12-12.desktop.production.log](https://github.com/desktop/desktop/files/13760414/2023-12-12.desktop.production.log)
[2023-12-13.desktop.production.log](https://github.com/desktop/desktop/files/13760415/2023-12-13.desktop.production.log)

**Comment by steveward** [comment]
@ngsea123 I'm seeing some operations that are taking a fair amount of time in the log from 12/12:

```
2023-12-12T20:57:15.396Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 98.456s)
```
If you'd like to try a fresh reset you can do that and then add other repositories. Here's how to reset the application:

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

You will need to log in again as well. Let me know if that helps.

**Comment by andrewcollier-com-au** [comment]
Hello I'm getting the same issue on windows 11 using GH Desktop 3.3.8. The issue brings my entire system to a crawl until I close the application and everything comes good again.


2024-02-02T14:12:08.355Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-02-02T14:12:20.149Z - info: [ui] [AppStore] loading 2 repositories from store
2024-02-02T14:12:20.152Z - info: [ui] [AppStore] found account: andrewcollier-com-au (AndyRooAU)
2024-02-02T14:12:20.181Z - info: [ui] [BranchPruner] Last prune took place 1 hour ago - skipping
2024-02-02T14:12:20.741Z - info: [ui] Subscribed 'andrewcollier-com-au' to Alive channel
2024-02-02T14:12:32.684Z - info: [ui] Executing getPartialBlobContentsCatchPathNotInRef: git show HEAD:.gitignore (took 8.696s)
2024-02-02T14:12:32.692Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 11.608s)
2024-02-02T14:12:37.821Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 11.656s)
2024-02-02T14:12:37.860Z - info: [ui] Executing getConfigValueInPath: git config -z --local user.name (took 5.051s)
2024-02-02T14:12:37.879Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 5.180s)
2024-02-02T14:12:37.988Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 5.289s)
2024-02-02T14:12:45.606Z - info: [ui] Executing getConfigValueInPath: git config -z --local user.email (took 7.760s)
2024-02-02T14:12:50.946Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --skip=0 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 13.065s)
2024-02-02T14:12:51.684Z - error: [ui] Highlighter worked failed for new contents
Error: timed out
    at C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\webpack:\app\src\lib\highlighter\worker.ts:85:14
2024-02-02T14:12:51.685Z - error: [ui] Highlighter worked failed for new contents
Error: timed out
    at C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\webpack:\app\src\lib\highlighter\worker.ts:85:14
2024-02-02T14:12:51.726Z - info: [ui] launching: 3.3.8 (Windows 10.0.22621)
2024-02-02T14:12:51.731Z - info: [ui] execPath: 'C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\GitHubDesktop.exe'
2024-02-02T14:12:56.907Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 4.794s)
2024-02-02T14:14:14.934Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 6.270s)
2024-02-02T14:14:19.170Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 4.232s)
2024-02-02T14:14:20.931Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.350s)
2024-02-02T14:16:05.910Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 8.378s)
2024-02-02T14:16:05.936Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 8.9s of which 0.0s paused, total 8.9s
2024-02-02T14:16:26.933Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 3.457s)

**Comment by ngsea123** [comment]
> @ngsea123 I'm seeing some operations that are taking a fair amount of time in the log from 12/12:
> 
> ```
> 2023-12-12T20:57:15.396Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 98.456s)
> ```
> 
> If you'd like to try a fresh reset you can do that and then add other repositories. Here's how to reset the application:
> 
> 1. Close GitHub Desktop
> 2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
> 3. Restart GitHub Desktop
> 
> You will need to log in again as well. Let me know if that helps.

Thanks! Fixed the issue!
