### ISSUE TITLE
Github Destop failing to connect to Enterprise Github

### ISSUE THREAD

**Issue by etanaka817** [desktop/desktop#17970]
### The problem

My Github Desjtop has been working for years for this repository and this year it started to get this error.

I am able to connect to my Enterprise Github using my browser and credentials.

### Release version

Version 3.3.6 (arm64)

### Operating system

MacOS Sonoma 14.1.2

### Steps to reproduce the behavior

I tried to Fetch origin and I got the following error:
![image](https://github.com/desktop/desktop/assets/155780993/81dca56f-325c-4ddd-b497-3e40bf72a100)

I then clicked "Open Preferences", then Sign In for Github Enterprise with address https://github.ibm.com and clicked Continue.
Then I clicked Continue With Browser.
Then, I got error:
![image](https://github.com/desktop/desktop/assets/155780993/e36a4d20-62a3-476d-84e8-6e23d96d0abe)

### Log files

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-01-07T00:04:18.069Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
remote: Anonymous access denied
fatal: Authentication failed for 'https://github.ibm.com/VMWSolutions/ic4v-tests.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-01-07T00:07:08.697Z - error: [ui] fetchMetadata: unable to load metadata from 'https://https/api/v3/meta' as a fallback
TypeError: Failed to fetch
    at nn (/webpack:/app/src/lib/http.ts:152:10)
    at /webpack:/app/src/lib/api.ts:2022:28
    at Ya.endpointSupportsBasicAuth (/webpack:/app/src/lib/stores/sign-in-store.ts:256:7)
    at Ya.setEndpoint (/webpack:/app/src/lib/stores/sign-in-store.ts:549:44)
    at Ya._setSignInEndpoint (/webpack:/app/src/lib/stores/app-store.ts:5681:29)
    at Object.setSignInEndpoint (/webpack:/app/src/ui/dispatcher/dispatcher.ts:1495:26)
    at Object.onSubmit (/webpack:/app/src/ui/sign-in/sign-in.tsx:92:31)
    at onSubmit (/webpack:/app/src/ui/dialog/dialog.tsx:707:18)
    at Object.l (/webpack:/app/node_modules/react-dom/cjs/react-dom.production.min.js:14:428)
    at m (/webpack:/app/node_modules/react-dom/cjs/react-dom.production.min.js:15:118)
2024-01-07T00:07:46.487Z - info: [ui] [SignInStore] initializing OAuth flow
2024-01-07T00:07:46.488Z - info: [main] opening in browser: https://github.ibm.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=963eaf27-a07f-4ec0-9f4f-03d560ade764
2024-01-07T00:07:46.826Z - info: [main] Processing protocol url
2024-01-07T00:07:46.827Z - info: [ui] [Dispatcher] requesting authenticated user
2024-01-07T00:07:47.158Z - info: [ui] [SignInStore] account resolved
2024-01-07T00:07:47.159Z - info: [ui] [AppStore] adding account etanaka (Eduardo Tanaka) to store
2024-01-07T00:07:47.173Z - error: [ui] Error adding account 'etanaka'
Error: An unknown error occurred.

**Comment by etanaka817** [comment]
Never mind, fixed the problem.

**Comment by steveward** [comment]
@etanaka817 any chance you can share what was causing this issue and potentially how you fixed it? We have another GitHub Desktop user encountering this error in https://github.com/desktop/desktop/issues/18502 as well and any information you can provide that could give us some clues would be helpful! Thanks.

**Comment by etanaka817** [comment]
Sorry, it has been some time so I dod not recall what was done. Maybe I reset my laptop?

**Comment by steveward** [comment]
No problem, thanks for following up! The other user was able to resolve the issue as well.
