### ISSUE TITLE
Desktop Tree Status Out of Sync with Local git

### ISSUE THREAD

**Issue by miqrogroove** [desktop/desktop#18023]
### The problem

Fresh install of GitHub Desktop.  Opened a local git repo over an SMB mapped drive letter.  After 2 commits, the commit log is synced but the tree status is not.  GitHub Desktop shows "0 changed files".  The Ubuntu `git status` shows all of the files from the past 2 commits are still in the `modified` state.

I hope this is a trivial fix because I won't be able to use Desktop if it's incompatible with all the other software.

### Release version

3.3.6

### Operating system

Windows 10

### Log files

2024-01-16T18:32:00.692Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\robert\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\robert\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\robert\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\robert\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\robert\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\robert\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2024-01-16T18:32:00.704Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\robert\Desktop\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\robert\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\robert\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\robert\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\robert\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\robert\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2024-01-16T18:32:00.704Z - error: [main] Toast activator CLSID not found in any of the shortcuts. Falling back to known CLSIDs.
2024-01-16T18:32:00.704Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-01-16T18:32:02.158Z - info: [main] Received possible protocol arguments: 2
2024-01-16T18:32:02.186Z - error: [main] Malformed launch arguments received: C:\Users\robert\AppData\Local\GitHubDesktop\app-3.3.6\GitHubDesktop.exe,--squirrel-firstrun
2024-01-16T18:32:02.187Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-01-16T18:32:04.122Z - info: [ui] Opt in reported.
2024-01-16T18:32:05.153Z - info: [ui] [AppStore] loading 0 repositories from store
2024-01-16T18:32:05.261Z - info: [ui] launching: 3.3.6 (Windows 10.0.19045)
2024-01-16T18:32:05.263Z - info: [ui] execPath: 'C:\Users\robert\AppData\Local\GitHubDesktop\app-3.3.6\GitHubDesktop.exe'
2024-01-16T18:32:05.685Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-16T18:32:06.187Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-16T18:32:07.813Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.536s)
2024-01-16T18:34:09.774Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
2024-01-16T18:34:09.775Z - info: [ui] [SignInStore] initializing OAuth flow
2024-01-16T18:34:09.775Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=be14d2c2-3f4c-4a6d-b516-2dc1ef7eb806
2024-01-16T18:34:09.776Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2024-01-16T18:34:09.919Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2024-01-16T18:34:45.801Z - info: [main] Received possible protocol arguments: 4
2024-01-16T18:34:45.802Z - info: [main] Processing protocol url
2024-01-16T18:34:45.812Z - info: [ui] [Dispatcher] requesting authenticated user
2024-01-16T18:34:45.823Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2024-01-16T18:34:46.415Z - info: [ui] [SignInStore] account resolved
2024-01-16T18:34:46.416Z - info: [ui] [AppStore] adding account miqrogroove (miqrogroove) to store
2024-01-16T18:34:46.421Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2024-01-16T18:34:46.469Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-16T18:34:46.714Z - info: [ui] Subscribed 'miqrogroove' to Alive channel
2024-01-16T18:34:46.848Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-16T18:34:50.339Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-16T18:34:53.401Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-16T18:41:23.345Z - info: [ui] [AppStore] adding repository at Z:\ to store
2024-01-16T18:44:36.803Z - info: [ui] Executing getChangesFiles: git log 5dfe32be3dce18ef3074e8f52b8a64955f6f691a -C -M -m -1 --no-show-signature --first-parent --raw --format=format: --numstat -z -- (took 2.406s)
2024-01-16T18:45:52.934Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 5.418s)
2024-01-16T18:45:56.871Z - info: [ui] Executing createCommit: git commit -F - (took 3.814s)
2024-01-16T18:45:57.479Z - info: [ui] [Timing] Action 'create commit' for 'Z:\' took 10.737s
2024-01-16T18:46:22.064Z - info: [ui] Executing getChangesFiles: git log bbf29a03d68cf7eca3cb22b0bb15e5d5f517cceb -C -M -m -1 --no-show-signature --first-parent --raw --format=format: --numstat -z -- (took 2.566s)
2024-01-16T19:00:18.474Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.5s of which 0.0s paused, total 0.5s
2024-01-16T19:43:30.858Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.5s of which 0.0s paused, total 0.5s
2024-01-16T19:52:25.226Z - info: [ui] [Timing] Action 'create commit' for 'Z:\' took 1.823s
2024-01-16T19:58:47.163Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.6s of which 0.0s paused, total 0.6s
2024-01-16T20:14:46.430Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.7s of which 0.0s paused, total 0.7s
2024-01-16T20:16:06.413Z - info: [ui] [Timing] Action 'checkout branch from list' for 'Z:\' took 0.000s
2024-01-16T20:16:59.194Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-01-16T20:16:59.630Z - info: [ui] [AppStore] loading 1 repositories from store
2024-01-16T20:16:59.630Z - info: [ui] [AppStore] found account: miqrogroove (miqrogroove)
2024-01-16T20:16:59.838Z - info: [ui] launching: 3.3.6 (Windows 10.0.19045)
2024-01-16T20:16:59.841Z - info: [ui] execPath: 'C:\Users\robert\AppData\Local\GitHubDesktop\app-3.3.6\GitHubDesktop.exe'
2024-01-16T20:16:59.984Z - info: [ui] Subscribed 'miqrogroove' to Alive channel
2024-01-16T20:17:00.148Z - info: [ui] Stats reported.

### Additional context

Also using git v2.25.1 on Ubuntu 20.04.6.

**Comment by steveward** [comment]
Thanks for the issue @miqrogroove. We do not provide official support for the Linux fork of GitHub Desktop, so I would recommend opening an issue directly in the fork:

https://github.com/shiftkey/desktop/issues

I would take a look there to see if there is an existing issue about this that has been reported.

**Comment by miqrogroove** [comment]
@steveward I am not using GitHub Desktop for Linux.  Please reopen this issue.

**Comment by miqrogroove** [comment]
I am not using a Linux fork.  I did, however, find an existing issue that I'm experiencing: #9443

**Comment by steveward** [comment]
Apologies, I saw Ubuntu referenced and missed the fact that you were on Windows. Were you able to resolve things based off that issue thread?

**Comment by miqrogroove** [comment]
@steveward I added to the bottom of the referenced thread.  I was able to make Desktop compatible with the repo, but I found the solution extremely arcane.  The solution effectively defeats the purpose of having a GUI in the first place and will deter new users.  Some of the GitHub wizards need to take a look at improving on that.
