### ISSUE TITLE
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

### ISSUE THREAD

**Issue by silencekillsdesign** [desktop/desktop#18053]
### The problem

I keep getting this error. How do I resolve this?

### Release version

Version 3.3.8

### Operating system

Windows !0

### Steps to reproduce the behavior

it just does it everytime I open the program

### Log files

2024-01-20T02:29:46.643Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-01-20T02:29:48.773Z - info: [ui] [AppStore] loading 11 repositories from store
2024-01-20T02:29:48.781Z - info: [ui] [AppStore] found account: silencekillsdesign (CJ Williams)
2024-01-20T02:29:49.530Z - info: [ui] Subscribed 'silencekillsdesign' to Alive channel
2024-01-20T02:29:49.654Z - info: [ui] launching: 3.3.6 (Windows 10.0.19045)
2024-01-20T02:29:49.657Z - info: [ui] execPath: 'C:\Users\CJ\AppData\Local\GitHubDesktop\app-3.3.6\GitHubDesktop.exe'
2024-01-20T02:29:50.985Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:29:50.998Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:29:52.283Z - info: [ui] Stats reported.
2024-01-20T02:30:04.628Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.651s)
2024-01-20T02:30:04.628Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 1.
stderr:
error: cannot lock ref 'refs/remotes/origin/desktop.ini': unable to resolve reference 'refs/remotes/origin/desktop.ini': reference broken
error: could not remove reference refs/remotes/origin/desktop.ini
From https://github.com/silencekillsdesign/hirecj-old
 - [deleted]         (none)     -> origin/desktop.ini
fatal: bad object refs/desktop.ini
error: https://github.com/silencekillsdesign/hirecj-old.git did not send all necessary objects

2024-01-20T02:30:07.701Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:30:56.413Z - info: [ui] [Timing] Action 'create commit' for 'silencekillsdesign/hirecj-old' took 1.101s
2024-01-20T02:30:57.555Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:31:00.162Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: hirecj-old - silencekillsdesign (has token)
2024-01-20T02:31:01.485Z - info: [ui] Executing push: git -c credential.helper= push origin main:main --progress (took 1.319s)
2024-01-20T02:31:02.149Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 1.
stderr:
error: cannot lock ref 'refs/remotes/origin/desktop.ini': unable to resolve reference 'refs/remotes/origin/desktop.ini': reference broken
error: could not remove reference refs/remotes/origin/desktop.ini
From https://github.com/silencekillsdesign/hirecj-old
 - [deleted]         (none)     -> origin/desktop.ini
fatal: bad object refs/desktop.ini
error: https://github.com/silencekillsdesign/hirecj-old.git did not send all necessary objects

2024-01-20T02:31:03.885Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:31:57.149Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-01-20T02:34:28.959Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:34:30.306Z - warn: [ui] fetchRepository: 'silencekillsdesign/silencekillsdesign-vue-mdb' returned a 404
2024-01-20T02:34:30.307Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: silencekillsdesign-vue-mdb - silencekillsdesign (has token)
2024-01-20T02:34:33.849Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: PHPMailer - silencekillsdesign (has token)
2024-01-20T02:34:38.659Z - info: [ui] [Timing] Action 'create commit' for 'silencekillsdesign/hirecj-old' took 0.719s
2024-01-20T02:34:39.327Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:34:42.136Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: hirecj-old - silencekillsdesign (has token)
2024-01-20T02:34:43.598Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 1.
stderr:
error: cannot lock ref 'refs/remotes/origin/desktop.ini': unable to resolve reference 'refs/remotes/origin/desktop.ini': reference broken
error: could not remove reference refs/remotes/origin/desktop.ini
From https://github.com/silencekillsdesign/hirecj-old
 - [deleted]         (none)     -> origin/desktop.ini
fatal: bad object refs/desktop.ini
error: https://github.com/silencekillsdesign/hirecj-old.git did not send all necessary objects

2024-01-20T02:34:45.210Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:35:22.206Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-01-20T02:36:55.552Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\CJ\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\ProgramData\CJ\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\ProgramData\CJ\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\ProgramData\CJ\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\ProgramData\CJ\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\ProgramData\CJ\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2024-01-20T02:36:55.592Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\CJ\Desktop\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\ProgramData\CJ\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\ProgramData\CJ\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\ProgramData\CJ\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\ProgramData\CJ\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\ProgramData\CJ\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2024-01-20T02:36:55.592Z - error: [main] Toast activator CLSID not found in any of the shortcuts. Falling back to known CLSIDs.
2024-01-20T02:36:55.592Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-01-20T02:36:55.715Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\CJ\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\CJ\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\CJ\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\CJ\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\CJ\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\CJ\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2024-01-20T02:36:55.722Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\CJ\Desktop\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\CJ\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\CJ\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\CJ\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\CJ\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\CJ\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2024-01-20T02:36:55.722Z - error: [main] Toast activator CLSID not found in any of the shortcuts. Falling back to known CLSIDs.
2024-01-20T02:36:55.722Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-01-20T02:36:59.120Z - info: [main] Received possible protocol arguments: 2
2024-01-20T02:36:59.150Z - error: [main] Malformed launch arguments received: C:\Users\CJ\AppData\Local\GitHubDesktop\app-3.3.8\GitHubDesktop.exe,--squirrel-firstrun
2024-01-20T02:36:59.150Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-01-20T02:36:59.225Z - info: [main] Received possible protocol arguments: 3
2024-01-20T02:36:59.229Z - error: [main] Malformed launch arguments received: C:\ProgramData\CJ\GitHubDesktop\app-3.3.8\GitHubDesktop.exe,--squirrel-firstrun,--allow-file-access-from-files
2024-01-20T02:37:00.416Z - info: [ui] [AppStore] loading 11 repositories from store
2024-01-20T02:37:00.416Z - info: [ui] [AppStore] found account: silencekillsdesign (CJ Williams)
2024-01-20T02:37:00.467Z - info: [ui] [BranchPruner] Last prune took place 7 minutes ago - skipping
2024-01-20T02:37:00.932Z - info: [ui] launching: 3.3.8 (Windows 10.0.19045)
2024-01-20T02:37:00.932Z - info: [ui] execPath: 'C:\Users\CJ\AppData\Local\GitHubDesktop\app-3.3.8\GitHubDesktop.exe'
2024-01-20T02:37:01.700Z - info: [ui] Subscribed 'silencekillsdesign' to Alive channel
2024-01-20T02:37:02.024Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:37:02.538Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.605s)
2024-01-20T02:37:23.777Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 1.
stderr:
error: cannot lock ref 'refs/remotes/origin/desktop.ini': unable to resolve reference 'refs/remotes/origin/desktop.ini': reference broken
error: could not remove reference refs/remotes/origin/desktop.ini
From https://github.com/silencekillsdesign/hirecj-old
 - [deleted]         (none)     -> origin/desktop.ini
fatal: bad object refs/desktop.ini
error: https://github.com/silencekillsdesign/hirecj-old.git did not send all necessary objects

2024-01-20T02:37:24.847Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:37:52.955Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:38:42.360Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:39:19.576Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:39:19.648Z - warn: [ui] fetchRepository: 'silencekillsdesign/silencekillsdesign-vue-mdb' returned a 404
2024-01-20T02:39:40.094Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 10 repositories took 21.1s of which 0.0s paused, total 21.1s
2024-01-20T02:39:42.424Z - info: [ui] [BranchPruner] Last prune took place 10 minutes ago - skipping
2024-01-20T02:39:43.240Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:39:43.310Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:45:06.884Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 1.
stderr:
error: cannot lock ref 'refs/remotes/origin/desktop.ini': unable to resolve reference 'refs/remotes/origin/desktop.ini': reference broken
error: could not remove reference refs/remotes/origin/desktop.ini
From https://github.com/silencekillsdesign/hirecj-old
 - [deleted]         (none)     -> origin/desktop.ini
fatal: bad object refs/desktop.ini
error: https://github.com/silencekillsdesign/hirecj-old.git did not send all necessary objects

2024-01-20T02:45:08.713Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:48:09.926Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:50:32.698Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 1.
stderr:
error: cannot lock ref 'refs/remotes/origin/desktop.ini': unable to resolve reference 'refs/remotes/origin/desktop.ini': reference broken
error: could not remove reference refs/remotes/origin/desktop.ini
From https://github.com/silencekillsdesign/hirecj-old
 - [deleted]         (none)     -> origin/desktop.ini
fatal: bad object refs/desktop.ini
error: https://github.com/silencekillsdesign/hirecj-old.git did not send all necessary objects

2024-01-20T02:50:33.749Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.042s)
2024-01-20T02:50:35.362Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:55:59.166Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.028s)
2024-01-20T02:55:59.180Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 1.
stderr:
error: cannot lock ref 'refs/remotes/origin/desktop.ini': unable to resolve reference 'refs/remotes/origin/desktop.ini': reference broken
error: could not remove reference refs/remotes/origin/desktop.ini
From https://github.com/silencekillsdesign/hirecj-old
 - [deleted]         (none)     -> origin/desktop.ini
fatal: bad object refs/desktop.ini
error: https://github.com/silencekillsdesign/hirecj-old.git did not send all necessary objects

2024-01-20T02:56:00.294Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.111s)
2024-01-20T02:56:02.068Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:58:25.551Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:58:25.596Z - warn: [ui] fetchRepository: 'silencekillsdesign/silencekillsdesign-vue-mdb' returned a 404
2024-01-20T02:58:37.735Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 10 repositories took 13.3s of which 0.0s paused, total 13.3s
2024-01-20T02:58:44.341Z - info: [ui] [Timing] Action 'create commit' for 'silencekillsdesign/hirecj-old' took 1.492s
2024-01-20T02:58:44.912Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T02:58:46.641Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: hirecj-old - silencekillsdesign (has token)
2024-01-20T02:58:48.744Z - info: [ui] Executing push: git -c credential.helper= push origin main:main --progress (took 2.100s)
2024-01-20T02:58:49.248Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 1.
stderr:
error: cannot lock ref 'refs/remotes/origin/desktop.ini': unable to resolve reference 'refs/remotes/origin/desktop.ini': reference broken
error: could not remove reference refs/remotes/origin/desktop.ini
From https://github.com/silencekillsdesign/hirecj-old
 - [deleted]         (none)     -> origin/desktop.ini
fatal: bad object refs/desktop.ini
error: https://github.com/silencekillsdesign/hirecj-old.git did not send all necessary objects

2024-01-20T02:58:50.739Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T03:01:25.706Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 1.
stderr:
error: cannot lock ref 'refs/remotes/origin/desktop.ini': unable to resolve reference 'refs/remotes/origin/desktop.ini': reference broken
error: could not remove reference refs/remotes/origin/desktop.ini
From https://github.com/silencekillsdesign/hirecj-old
 - [deleted]         (none)     -> origin/desktop.ini
fatal: bad object refs/desktop.ini
error: https://github.com/silencekillsdesign/hirecj-old.git did not send all necessary objects

2024-01-20T03:01:27.557Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T03:01:50.281Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T03:02:22.536Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T03:02:26.108Z - info: [ui] [Timing] Action 'create commit' for 'silencekillsdesign/hirecj-old' took 0.689s
2024-01-20T03:02:26.651Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T03:02:28.930Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: hirecj-old - silencekillsdesign (has token)
2024-01-20T03:02:30.303Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 1.
stderr:
error: cannot lock ref 'refs/remotes/origin/desktop.ini': unable to resolve reference 'refs/remotes/origin/desktop.ini': reference broken
error: could not remove reference refs/remotes/origin/desktop.ini
From https://github.com/silencekillsdesign/hirecj-old
 - [deleted]         (none)     -> origin/desktop.ini
fatal: bad object refs/desktop.ini
error: https://github.com/silencekillsdesign/hirecj-old.git did not send all necessary objects

2024-01-20T03:02:31.783Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T03:03:35.538Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T03:03:55.059Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T03:04:04.090Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T03:04:57.811Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T03:06:15.387Z - info: [main] Received possible protocol arguments: 4
2024-01-20T03:06:15.391Z - info: [main] Processing protocol url
2024-01-20T03:06:16.327Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T03:06:22.704Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/silencekillsdesign/nuxt-ui-pro.git - silencekillsdesign (has token)
2024-01-20T03:06:26.154Z - info: [ui] Executing clone: git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/silencekillsdesign/nuxt-ui-pro.git C:\web\nuxt-ui-pro (took 3.446s)
2024-01-20T03:06:26.252Z - info: [ui] [AppStore] adding repository at C:\web\nuxt-ui-pro to store
2024-01-20T03:06:26.391Z - info: [ui] [BranchPruner] Last prune took place 37 minutes ago - skipping
2024-01-20T03:06:27.172Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 1.
stderr:
error: cannot lock ref 'refs/remotes/origin/desktop.ini': unable to resolve reference 'refs/remotes/origin/desktop.ini': reference broken
error: could not remove reference refs/remotes/origin/desktop.ini
From https://github.com/silencekillsdesign/hirecj-old
 - [deleted]         (none)     -> origin/desktop.ini
fatal: bad object refs/desktop.ini
error: https://github.com/silencekillsdesign/hirecj-old.git did not send all necessary objects

2024-01-20T03:06:27.387Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

2024-01-20T03:06:27.505Z - info: [ui] Executing isUsingLFS: git lfs track (took 1.063s)
2024-01-20T03:06:29.336Z - error: [ui] `git show-ref --tags -d` exited with an unexpected code: 128.
stderr:
fatal: git show-ref: bad ref refs/tags/desktop.ini (0000000000000000000000000000000000000000)

### Screenshots

![Screenshot 2024-01-19 210934](https://github.com/desktop/desktop/assets/7681943/018435bd-9a6d-40c2-94c0-cca2bf5111db)

**Comment by steveward** [comment]
@silencekillsdesign thanks for the issue. It looks like a file mistakenly got added to your repository.

`error: could not remove reference refs/remotes/origin/desktop.ini`

Can you go in your repository to `.git/refs/remotes/origin` and delete that `desktop.ini` file? That should hopefully get things working. You will have to turn on hidden files/folders on Windows to navigate to your `.git` repository in File Explorer.

I hope that helps. I'm going to close this out, but let me know if you have any further issues.

**Comment by VitaliML** [comment]
> @silencekillsdesign thanks for the issue. It looks like a file mistakenly got added to your repository.
> 
> `error: could not remove reference refs/remotes/origin/desktop.ini`
> 
> Can you go in your repository to `.git/refs/remotes/origin` and delete that `desktop.ini` file? That should hopefully get things working. You will have to turn on hidden files/folders on Windows to navigate to your `.git` repository in File Explorer.
> 
> I hope that helps. I'm going to close this out, but let me know if you have any further issues.

Thanks, its work.
