### ISSUE TITLE
Fetching origin: Gets stuck at 96% 

### ISSUE THREAD

**Issue by acluelesscandy** [desktop/desktop#18056]
### The problem

![image](https://github.com/desktop/desktop/assets/117528020/1fba0c18-9470-459c-9631-e3e94c2e2913)

This is my first time using github and the repository (that I made), and had some changes done. After not fetching origin for 2 days and finally doing so, I started experiencing this particular issue. When i fetch origin, it goes as normal and finally when it reaches 96% it gets stuck. 
usually the 96% is around 13330/13669 objects. 

### Release version

Version 3.3.8 

### Operating system

Windows 11 pro

### Log files

2024-01-14T17:08:23.159Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\moham\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\moham\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\moham\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\moham\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\moham\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\moham\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2024-01-14T17:08:23.179Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\moham\Desktop\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\moham\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\moham\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\moham\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\moham\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\moham\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2024-01-14T17:08:23.179Z - error: [main] Toast activator CLSID not found in any of the shortcuts. Falling back to known CLSIDs.
2024-01-14T17:08:23.179Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-01-14T17:08:27.560Z - info: [main] Received possible protocol arguments: 2
2024-01-14T17:08:27.655Z - error: [main] Malformed launch arguments received: C:\Users\moham\AppData\Local\GitHubDesktop\app-3.3.6\GitHubDesktop.exe,--squirrel-firstrun
2024-01-14T17:08:27.655Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-01-14T17:08:31.033Z - info: [ui] [AppStore] loading 0 repositories from store
2024-01-14T17:08:31.906Z - info: [ui] Opt in reported.
2024-01-14T17:08:31.942Z - info: [ui] launching: 3.3.6 (Windows 10.0.22000)
2024-01-14T17:08:31.942Z - info: [ui] execPath: 'C:\Users\moham\AppData\Local\GitHubDesktop\app-3.3.6\GitHubDesktop.exe'
2024-01-14T17:08:36.160Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-14T17:08:36.163Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-14T17:08:41.110Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-14T17:08:41.338Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 9.367s)
2024-01-14T17:08:50.962Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-14T17:08:52.650Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-14T17:10:17.817Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-14T17:10:20.244Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
2024-01-14T17:10:20.246Z - info: [ui] [SignInStore] initializing OAuth flow
2024-01-14T17:10:20.247Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=b90187a3-5638-479f-82d1-875b8f59f35d
2024-01-14T17:10:20.250Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2024-01-14T17:10:20.810Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2024-01-14T17:10:24.171Z - info: [main] Received possible protocol arguments: 4
2024-01-14T17:10:24.174Z - info: [main] Processing protocol url
2024-01-14T17:10:24.227Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2024-01-14T17:10:24.230Z - info: [ui] [Dispatcher] requesting authenticated user
2024-01-14T17:10:24.235Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2024-01-14T17:10:25.905Z - info: [ui] [SignInStore] account resolved
2024-01-14T17:10:25.906Z - info: [ui] [AppStore] adding account acluelesscandy (CANDII OR ZAL) to store
2024-01-14T17:10:25.918Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2024-01-14T17:10:26.356Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-14T17:10:26.906Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-01-14T17:10:27.345Z - info: [ui] Subscribed 'acluelesscandy' to Alive channel
2024-01-14T17:11:28.486Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/acluelesscandy/Pokemon-Celeste.git - acluelesscandy (has token)
2024-01-14T17:11:35.322Z - info: [ui] Executing clone: git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/acluelesscandy/Pokemon-Celeste.git C:\Users\moham\Desktop\Pokemon-Celeste (took 6.767s)
2024-01-14T17:11:35.507Z - info: [ui] [AppStore] adding repository at C:\Users\moham\Desktop\Pokemon-Celeste to store
2024-01-14T17:11:37.733Z - info: [ui] Executing getRemotes: git remote -v (took 1.063s)
2024-01-14T17:11:39.934Z - info: [ui] Executing isUsingLFS: git lfs track (took 4.188s)
2024-01-14T17:11:40.030Z - info: [ui] [BranchPruner] Last prune took place 3 seconds ago - skipping
2024-01-14T17:15:42.806Z - info: [ui] [Timing] Action 'create commit' for 'acluelesscandy/Pokemon-Celeste' took 1.597s
2024-01-14T17:16:51.231Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 68.682s)
2024-01-14T17:17:07.031Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.829s)
2024-01-14T17:17:09.113Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 2.079s)
2024-01-14T17:17:11.918Z - info: [ui] Executing getSymbolicRef: git symbolic-ref -q refs/remotes/origin/HEAD (took 1.281s)
2024-01-14T17:17:20.710Z - info: [ui] Executing getChangesFiles: git log e74a2c2f4838cc24c47a678ea64ac97b4e9030c5 -C -M -m -1 --no-show-signature --first-parent --raw --format=format: --numstat -z -- (took 7.381s)
2024-01-14T17:17:38.755Z - info: [ui] Executing createCommit: git commit -F - (took 47.508s)
2024-01-14T17:17:39.558Z - info: [ui] [Timing] Action 'create commit' for 'acluelesscandy/Pokemon-Celeste' took 120.189s
2024-01-14T17:21:16.275Z - info: [ui] [Timing] Action 'checkout branch from list' for 'acluelesscandy/Pokemon-Celeste' took 0.001s
2024-01-14T17:22:02.725Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Pokemon-Celeste - acluelesscandy (has token)
2024-01-14T17:23:10.561Z - info: [ui] Executing push: git -c credential.helper= push origin main:main --progress (took 67.800s)
2024-01-14T17:23:14.272Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 3.703s)
2024-01-14T17:23:16.586Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 2.308s)
2024-01-14T17:49:40.463Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 1.6s of which 0.0s paused, total 1.6s
2024-01-14T17:49:44.107Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Pokemon-Celeste - acluelesscandy (has token)
2024-01-14T17:49:47.812Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 3.692s)
2024-01-14T17:49:50.317Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 2.502s)
2024-01-14T17:50:11.194Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Pokemon-Celeste - acluelesscandy (has token)
2024-01-14T17:50:19.425Z - info: [ui] Executing pull: git -c credential.helper= -c rebase.backend=merge pull --ff --recurse-submodules --progress origin (took 7.839s)
2024-01-14T17:50:22.314Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 2.876s)
2024-01-14T19:05:43.677Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-01-14T19:05:45.356Z - info: [ui] [AppStore] loading 1 repositories from store
2024-01-14T19:05:45.358Z - info: [ui] [AppStore] found account: acluelesscandy (CANDII OR ZAL)
2024-01-14T19:05:46.557Z - info: [ui] [BranchPruner] Last prune took place 2 hours ago - skipping
2024-01-14T19:05:47.139Z - info: [ui] launching: 3.3.6 (Windows 10.0.22000)
2024-01-14T19:05:47.183Z - info: [ui] execPath: 'C:\Users\moham\AppData\Local\GitHubDesktop\app-3.3.6\GitHubDesktop.exe'
2024-01-14T19:05:48.793Z - info: [ui] Executing getCommits: git log 3f06ed707c6acc6169060d1a505411be830c879f --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.082s)
2024-01-14T19:05:48.993Z - info: [ui] Executing getRemotes: git remote -v (took 1.042s)
2024-01-14T19:05:49.262Z - info: [ui] Executing getRemotes: git remote -v (took 1.232s)
2024-01-14T19:05:52.069Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Pokemon-Celeste - acluelesscandy (has token)
2024-01-14T19:05:52.177Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 5.026s)
2024-01-14T19:05:52.178Z - info: [ui] Executing getCommits: git log origin/main..main --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.116s)
2024-01-14T19:05:53.081Z - info: [ui] Subscribed 'acluelesscandy' to Alive channel
2024-01-14T19:05:55.200Z - info: [ui] Stats reported.
2024-01-14T19:06:13.727Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 21.312s)
2024-01-14T19:06:15.865Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 2.135s)
2024-01-14T19:06:28.212Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Pokemon-Celeste - acluelesscandy (has token)
2024-01-14T19:06:35.855Z - info: [ui] Executing pull: git -c credential.helper= -c rebase.backend=merge pull --ff --recurse-submodules --progress origin (took 7.200s)
2024-01-14T19:06:37.743Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.885s)
2024-01-14T19:38:03.393Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 15.929s)
2024-01-14T19:38:10.150Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 6.695s)
2024-01-14T19:38:18.416Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.678s)
2024-01-14T19:38:18.425Z - info: [ui] Executing getStashEntries: git log -g -z --format=%gD%x00%H%x00%gs%x00%T%x00%P refs/stash (took 1.838s)
2024-01-14T19:38:18.432Z - info: [ui] Executing getCommits: git log origin/main..main --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 2.069s)
2024-01-14T19:38:18.933Z - info: [ui] Executing getConfigValueInPath: git config -z pull.rebase (took 1.864s)
2024-01-14T19:38:20.939Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 2.503s)
2024-01-14T19:38:21.042Z - info: [ui] Executing getCommits: git log origin/main..main --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 2.106s)
2024-01-14T19:38:21.129Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.685s)
2024-01-14T19:38:21.153Z - info: [ui] Executing getStashEntries: git log -g -z --format=%gD%x00%H%x00%gs%x00%T%x00%P refs/stash (took 1.974s)
2024-01-14T19:38:22.222Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 1.076s)

**Comment by steveward** [comment]
@acluelesscandy thanks for the report. Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing. Are you having this issue with multiple repositories? Can you try a different network to see if you encounter the same issue?'

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:


`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`


The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.


If neither of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. I hope that helps.
