### ISSUE TITLE
Github Desktop 3.3.8 freezes on Windows 11

### ISSUE THREAD

**Issue by andrewcollier-com-au** [desktop/desktop#18125]
### The problem

Hello I'm getting the same issue on windows 11 using GH Desktop 3.3.8. The issue brings my entire system to a crawl until I close the application and everything comes good again.

### Release version

3.3.8

### Operating system

Windows 11 22H2

### Steps to reproduce the behavior

Kill all processes and relaunch application

### Log files

2024-02-02T14:12:08.355Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-02-02T14:12:20.149Z - info: [ui] [AppStore] loading 2 repositories from store
2024-02-02T14:12:20.152Z - info: [ui] [AppStore] found account: andrewcollier-com-au (AndyRooAU)
2024-02-02T14:12:20.181Z - info: [ui] [BranchPruner] Last prune took place 1 hour ago - skipping
2024-02-02T14:12:20.741Z - info: [ui] Subscribed 'andrewcollier-com-au' to Alive channel
2024-02-02T14:12:32.684Z - info: [ui] Executing getPartialBlobContentsCatchPathNotInRef: git show HEAD:.gitignore (took 8.696s)
2024-02-02T14:12:32.692Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 11.608s)
2024-02-02T14:12:37.821Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 11.656s)
2024-02-02T14:12:37.860Z - info: [ui] Executing getConfigValueInPath: git config -z --local user.name (took 5.051s)
2024-02-02T14:12:37.879Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 5.180s)
2024-02-02T14:12:37.988Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 5.289s)
2024-02-02T14:12:45.606Z - info: [ui] Executing getConfigValueInPath: git config -z --local user.email (took 7.760s)
2024-02-02T14:12:50.946Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --skip=0 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 13.065s)
2024-02-02T14:12:51.684Z - error: [ui] Highlighter worked failed for new contents
Error: timed out
    at C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\webpack:\app\src\lib\highlighter\worker.ts:85:14
2024-02-02T14:12:51.685Z - error: [ui] Highlighter worked failed for new contents
Error: timed out
    at C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\webpack:\app\src\lib\highlighter\worker.ts:85:14
2024-02-02T14:12:51.726Z - info: [ui] launching: 3.3.8 (Windows 10.0.22621)
2024-02-02T14:12:51.731Z - info: [ui] execPath: 'C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\GitHubDesktop.exe'
2024-02-02T14:12:56.907Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 4.794s)
2024-02-02T14:14:14.934Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 6.270s)
2024-02-02T14:14:19.170Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 4.232s)
2024-02-02T14:14:20.931Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.350s)
2024-02-02T14:16:05.910Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 8.378s)
2024-02-02T14:16:05.936Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 8.9s of which 0.0s paused, total 8.9s
2024-02-02T14:16:26.933Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 3.457s)
2024-02-02T14:22:41.183Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-02-02T14:23:11.707Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2024-02-02T14:23:12.437Z - error: [ui] Could not get Alive web socket URL for 'andrewcollier-com-au'
TypeError: Failed to fetch
    at cn (C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\webpack:\app\src\lib\http.ts:152:10)
    at Zn.request (C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\webpack:\app\src\lib\api.ts:1757:28)
    at Zn.getAliveWebSocketURL (C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\webpack:\app\src\lib\api.ts:846:30)
    at Object.createSessionForAccount (C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\webpack:\app\src\lib\stores\alive-store.ts:170:32)
    at Object.subscribeToAccount (C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\webpack:\app\src\lib\stores\alive-store.ts:227:40)
    at Object._subscribeToAccounts (C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\webpack:\app\src\lib\stores\alive-store.ts:147:20)
    at subscribeToAccounts (C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\webpack:\app\src\lib\stores\alive-store.ts:126:44)
2024-02-02T14:23:12.448Z - info: [ui] [AppStore] loading 2 repositories from store
2024-02-02T14:23:12.448Z - info: [ui] [AppStore] found account: andrewcollier-com-au (AndyRooAU)
2024-02-02T14:23:12.476Z - info: [ui] [BranchPruner] Last prune took place 1 hour ago - skipping
2024-02-02T14:23:13.209Z - info: [ui] Subscribed 'andrewcollier-com-au' to Alive channel
2024-02-02T14:24:05.823Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 52.522s)
2024-02-02T14:24:05.831Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 52.365s)
2024-02-02T14:24:15.097Z - info: [ui] Executing getConfigValueInPath: git config -z --local user.name (took 9.216s)
2024-02-02T14:24:15.132Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 9.300s)
2024-02-02T14:24:15.239Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 9.415s)
2024-02-02T14:24:17.081Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.818s)
2024-02-02T14:24:25.243Z - info: [ui] launching: 3.3.8 (Windows 10.0.22621)
2024-02-02T14:24:25.282Z - info: [ui] execPath: 'C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\GitHubDesktop.exe'
2024-02-02T14:24:25.299Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 8.243s)
2024-02-02T14:24:25.317Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 7.083s)
2024-02-02T14:24:25.324Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 8.234s)
2024-02-02T14:24:26.328Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand upstream (took 1.002s)
2024-02-02T14:24:34.472Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a upstream (took 8.143s)
2024-02-02T14:24:34.531Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 6.341s)
2024-02-02T14:24:41.204Z - info: [ui] Executing getAheadBehind: git rev-list --left-right --count test-2024-01-30...origin/test-2024-01-30 -- (took 6.731s)
2024-02-02T14:24:41.233Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 6.702s)
2024-02-02T14:24:45.642Z - info: [ui] Executing getBranchesDifferingFromUpstream: git for-each-ref --format=%00%(refname)%00%(objectname)%00%(upstream)%00%(symref)%00%(HEAD)%00 refs/heads refs/remotes (took 4.437s)
2024-02-02T14:25:11.741Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 4.809s)
2024-02-02T14:25:11.752Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 24.746s)
2024-02-02T14:25:11.765Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 25.796s)
2024-02-02T14:25:49.740Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 4.449s)
2024-02-02T14:26:15.443Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 60.6s of which 8.3s paused, total 68.9s

**Comment by andrewcollier-com-au** [comment]
Working Now, I have done nothing 
2024-02-02T14:48:33.192Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-02-02T14:48:33.731Z - info: [ui] [AppStore] loading 2 repositories from store
2024-02-02T14:48:33.732Z - info: [ui] [AppStore] found account: andrewcollier-com-au (AndyRooAU)
2024-02-02T14:48:33.757Z - info: [ui] [BranchPruner] Last prune took place 2 hours ago - skipping
2024-02-02T14:48:34.109Z - info: [ui] launching: 3.3.8 (Windows 10.0.22621)
2024-02-02T14:48:34.109Z - info: [ui] execPath: 'C:\Users\Andrew\AppData\Local\GitHubDesktop\app-3.3.8\GitHubDesktop.exe'
2024-02-02T14:48:34.512Z - info: [ui] Subscribed 'andrewcollier-com-au' to Alive channel

**Comment by steveward** [comment]
Thanks for the report @andrewcollier-com-au. I do see some operations taking longer than usual in the log file. I'll add this to our performance tracking issue. Any chance you are using antivirus/security software on this machine?
