### ISSUE TITLE
Cannot copy private repositories

### ISSUE THREAD

**Issue by thebluuu** [desktop/desktop#18164]
### The problem

Okay! so first of all, I can't copy private repositories from my organization for some reason.. when i try to it does this (you're supposed to look at the screenshots btw)
after that happens, i can't even login with my normal username and password, I also use arch linux.

### Release version

Version 3.3.8-linux2 (x64)

### Operating system

Arch Linux

### Steps to reproduce the behavior

Just install it from arch aur by using yay 
after that, try copying a private repository from your organization

### Log files

2024-02-11T16:46:28.645Z - info: [ui] [AppStore] removing account thebluuu (thebluuu) from store
2024-02-11T16:46:28.650Z - info: [ui] Unubscribed 'thebluuu' from Alive channel
2024-02-11T16:46:30.245Z - info: [ui] [SignInStore] initializing OAuth flow
2024-02-11T16:46:30.250Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=no peaking!
2024-02-11T16:46:31.241Z - info: [main] Received possible protocol arguments: 3
2024-02-11T16:46:31.241Z - info: [main] Processing protocol url
2024-02-11T16:46:31.242Z - info: [ui] [Dispatcher] requesting authenticated user
2024-02-11T16:46:32.228Z - info: [ui] [SignInStore] account resolved
2024-02-11T16:46:32.228Z - info: [ui] [AppStore] adding account thebluuu (thebluuu) to store
2024-02-11T16:46:32.661Z - info: [ui] Subscribed 'thebluuu' to Alive channel
2024-02-11T16:46:36.695Z - error: [ui] Failed to look up repository clone info for 'https://github.com/Francium-cf/Francium-Reborn.git'
Error: Although you appear to have the correct authorization credentials, the `Francium-cf` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at cn (/home/ablue/webpack:/app/src/lib/http.ts:178:11)
    at Xn.fetchRepositoryCloneInfo (/home/ablue/webpack:/app/src/lib/api.ts:984:11)
    at Object.clone [as onSubmit] (/home/ablue/webpack:/app/src/ui/clone-repository/clone-repository.tsx:727:11)
2024-02-11T16:46:36.696Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/Francium-cf/Francium-Reborn.git - thebluuu (has token)
2024-02-11T16:46:37.201Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/Francium-cf/Francium-Reborn.git /home/ablue/Documents/GitHub/Francium-Reborn` exited with an unexpected code: 128.
stderr:
Cloning into '/home/ablue/Documents/GitHub/Francium-Reborn'...
remote: Repository not found.
fatal: repository 'https://github.com/Francium-cf/Francium-Reborn.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2024-02-11T16:46:51.707Z - error: [ui] Failed to look up repository clone info for 'https://github.com/Francium-cf/Francium-Reborn.git'
Error: Although you appear to have the correct authorization credentials, the `Francium-cf` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at cn (/home/ablue/webpack:/app/src/lib/http.ts:178:11)
    at Xn.fetchRepositoryCloneInfo (/home/ablue/webpack:/app/src/lib/api.ts:984:11)
    at Object.clone [as onSubmit] (/home/ablue/webpack:/app/src/ui/clone-repository/clone-repository.tsx:727:11)
2024-02-11T16:46:51.707Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/Francium-cf/Francium-Reborn.git - thebluuu (has token)
2024-02-11T16:46:52.230Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/Francium-cf/Francium-Reborn.git /home/ablue/Documents/GitHub/Francium-Reborn` exited with an unexpected code: 128.
stderr:
Cloning into '/home/ablue/Documents/GitHub/Francium-Reborn'...
remote: Repository not found.
fatal: repository 'https://github.com/Francium-cf/Francium-Reborn.git/' not found

### Screenshots

![image](https://github.com/desktop/desktop/assets/154030933/75130497-a954-4f7b-99d7-d176753f3c6d)

**Comment by steveward** [comment]
@thebluuu can you confirm you have access to these repositories? The error in the log is indicating a permissions issue. I would verify that you have the correct access rights in your organization. See [this article](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories).

**Comment by thebluuu** [comment]
> @thebluuu can you confirm you have access to these repositories? The error in the log is indicating a permissions issue. I would verify that you have the correct access rights in your organization. See [this article](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories).

![image](https://github.com/desktop/desktop/assets/154030933/d5542342-2f76-41f7-8bb3-6497342d9d34)

**Comment by steveward** [comment]
Thanks, I actually missed that you were using the Linux fork. There are some open issues around authentication -- it's likely you're running into this issue: https://github.com/shiftkey/desktop/issues/972 and https://github.com/shiftkey/desktop/issues/217. I hope that helps!
