### ISSUE TITLE
unable to update local ref

### ISSUE THREAD

**Issue by ShaliniSekar22** [desktop/desktop#18180]
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0        error: cannot lock ref 'refs/remotes/origin/sha/task': 'refs/remotes/origin/sha' exists; cannot create 'refs/remotes/origin/sha/task'
From https://github.com/Rubix-StyleSpot-NopCommerce/Uzhavar-Nanban ! [new branch]      sha/task           -> origin/sha/task  (unable to update local ref)
   c487e0f..9e99de8  uzhavar-dev-deploy -> origin/uzhavar-dev-deploy
error: some local refs could not be updated; try running
'git remote prune [https://github.com/Rubix-StyleSpot-NopCommerce/Uzhavar-Nanban.git'](https://github.com/Rubix-StyleSpot-NopCommerce/Uzhavar-Nanban.git%27) to remove any old, conflicting branches
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2842)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2185)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:635)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:170)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:377)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	... 4 more
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to agent_140
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:153)
		at jdk.internal.reflect.GeneratedMethodAccessor480.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:138)
		at com.sun.proxy.$Proxy148.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:997)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1241)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1305)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		... 4 more
[Pipeline] }[Pipeline] // stage[Pipeline] }[Pipeline] // node[Pipeline] End of PipelineERROR: Error fetching remote repo 'origin'
Finished: FAILURE

I have this error How can I fixed it.

**Comment by steveward** [comment]
@ShaliniSekar22 this issue tracker is for GitHub Desktop -- are you encountering any specific errors in GitHub Desktop? It looks like this is associated with Jenkins, so you'll need to reach out for assistance in their community:

https://community.jenkins.io

I hope that helps.

**Comment by ShaliniSekar22** [comment]
@steveward Thanks for your support
