### ISSUE TITLE
In TexStudio, useing GIT to check-in but it can't start GitHub Desktop (with error)

### ISSUE THREAD

**Issue by MZM96** [desktop/desktop#18218]
### The problem

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:61:25)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Socket.write (node:internal/streams/writable:337:10)
    at console.value (node:internal/console/constructor:300:16)
    at console.warn (node:internal/console/constructor:382:26)
    at f.log (app\src\main-process\desktop-console-transport.ts:41:7)
    at f.s._write (app\node_modules\winston-transport\index.js:82:19)
    at O (app\node_modules\readable-stream\lib\_stream_writable.js:409:139)
    at C:\Users\zemin\AppData\Local\GitHubDesktop\app-3.3.9\webpack:\app\node_modules\readable-stream\lib\_stream_writable.js:398:5

Version: 3.3.9
OS: Windows 10.0.22631

### Release version

Version 3.3.9 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Close GitHub Desktop
2. Open TexStudio.exe
3. Configure SVN/GIT
4. Save and expect check-in

### Screenshots

![image](https://github.com/desktop/desktop/assets/160684598/df14860b-2a86-428a-8cb7-cd8a908a51b9)

**Comment by sergiou87** [comment]
Thank you for your report @MZM96 

Let me try to understand this better… you are able to open GitHub Desktop except when TexStudio is already running?

**Comment by Uzlopak** [comment]
@sergiou87 seems to be spam.
