### ISSUE TITLE
Could not call remote function 'getPath'

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1825]
https://haystack.githubapp.com/desktop/rollups/167356e71427a3160469fe4b7065c859

It looks like this is unique to Windows. Is it possible to not have a `Documents` directory?

```
Error: Could not call remote function 'getPath'. Check that the function signature is correct. Underlying error: Failed to get 'documents' path
at callFunction (app-0.5.8\resources\electron.asar\browser\rpc-server.js:257:11)
at EventEmitter.<anonymous> (app-0.5.8\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
at WebContents.<anonymous> (app-0.5.8\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
at metaToValue (app-0.5.8\resources\electron.asar\renderer\api\remote.js:234:13)
at Object.remoteMemberFunction (app-0.5.8\resources\electron.asar\renderer\api\remote.js:118:18)
at Object.I.getDocumentsPath (file:///app/renderer.js:1:42476)
at Object.I.getDefaultDir (file:///app/renderer.js:1:589751)
at le (file:///app/renderer.js:3:363293)
at ee._constructComponentWithoutOwner (file:///app/renderer.js:3:100821)
at ee._constructComponent (file:///app/renderer.js:3:100678)
at ee.mountComponent (file:///app/renderer.js:3:99775)
at Object.mountComponent (file:///app/renderer.js:1:49664)
at ee.performInitialMount (file:///app/renderer.js:3:101708)
```

**Comment by shiftkey** [comment]
Looks like it's [this code](https://github.com/electron/electron/blob/9137a2279ad6b5d01084f667644a92e1602eceef/atom/browser/api/atom_api_app.cc#L743) inside Electron that's failing.

> It looks like this is unique to Windows. Is it possible to not have a `Documents` directory?

I'm trying to find some history on this from the classic app and whether we've handled this, but nothing jumps out. @steveward might remember more from the support side.

I found [this loosely related issue](https://forums.asp.net/t/1889407.aspx?GetFolderPath+Environment+GetFolderPath+Environment+SpecialFolder+MyDocuments+returning+blank+when+hosted+on+IIS) which talks about `Environment.SpecialFolder.MyDocuments` being an empty string, which suggests that we shouldn't assume this is going to be a valid path - because the account may be setup with a weird profile.
