### ISSUE TITLE
Github Desktop not working/installing

### ISSUE THREAD

**Issue by Astradeni** [desktop/desktop#18424]
### The problem

I had Github Desktop before and it suddenly stopped working (I opened it, and when it loaded it shut down again by its own. After that my shortcut icons led nowhere, and the program itself did not show up in the program search). I dowloaded it again and tried to install it, and it gives me an error that says to check the setup log and contact the program author.

### **Setup Log**
```
16608> 2023-02-24 19:43:09> Program: Starting Squirrel Updater: --install .
16608> 2023-02-24 19:43:09> Program: Starting install, writing to C:\Users\astra\AppData\Local\SquirrelTemp
16608> 2023-02-24 19:43:09> Program: About to install to: C:\Users\astra\AppData\Local\Discord
16608> 2023-02-24 19:43:09> SingleGlobalInstance: Grabbing lockfile with timeout of 00:00:10
16608> 2023-02-24 19:43:09> CheckForUpdateImpl: Reading RELEASES file from C:\Users\astra\AppData\Local\SquirrelTemp
16608> 2023-02-24 19:43:09> CheckForUpdateImpl: Remote version 1.0.9011 differs from local 
16608> 2023-02-24 19:43:09> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
16608> 2023-02-24 19:43:09> ApplyReleasesImpl: Writing files to app directory: C:\Users\astra\AppData\Local\Discord\app-1.0.9011
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\app.ico to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\app.ico
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\chrome_200_percent.pak to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\chrome_200_percent.pak
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\chrome_100_percent.pak to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\chrome_100_percent.pak
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\d3dcompiler_47.dll to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\d3dcompiler_47.dll
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\Discord.exe to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\Discord.exe
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\ffmpeg.dll to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\ffmpeg.dll
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\icudtl.dat to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\icudtl.dat
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\installer.db to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\installer.db
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\libEGL.dll to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\libEGL.dll
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\libGLESv2.dll to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\libGLESv2.dll
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\resources.pak to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\resources.pak
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\snapshot_blob.bin to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\snapshot_blob.bin
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\updater.node to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\updater.node
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\vk_swiftshader.dll to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\vk_swiftshader.dll
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\vulkan-1.dll to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\vulkan-1.dll
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\v8_context_snapshot.bin to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\v8_context_snapshot.bin
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Moving file C:\Users\astra\AppData\Local\Discord\app-1.0.9011\lib\net45\vk_swiftshader_icd.json to C:\Users\astra\AppData\Local\Discord\app-1.0.9011\vk_swiftshader_icd.json
16608> 2023-02-24 19:43:11> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\astra\AppData\Local\Discord\app-1.0.9011\Discord.exe]
16608> 2023-02-24 19:43:15> Utility: Process Started: C:\Users\astra\AppData\Local\Discord\app-1.0.9011\Discord.exe --squirrel-install 1.0.9011, pid 19132
16608> 2023-02-24 19:43:17> Utility: Received exitcode 0 from process C:\Users\astra\AppData\Local\Discord\app-1.0.9011\Discord.exe
16608> 2023-02-24 19:43:17> ApplyReleasesImpl: ran C:\Users\astra\AppData\Local\Discord\app-1.0.9011\Discord.exe, pid 19404
16608> 2023-02-24 19:43:17> ApplyReleasesImpl: Starting fixPinnedExecutables
16608> 2023-02-24 19:43:17> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-1.0.9011
16608> 2023-02-24 19:43:17> ApplyReleasesImpl: File 'C:\Users\astra\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\LiveCaptions.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
16608> 2023-02-24 19:43:17> ApplyReleasesImpl: File 'C:\Users\astra\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\Narrator.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
16608> 2023-02-24 19:43:17> ApplyReleasesImpl: File 'C:\Users\astra\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\On-Screen Keyboard.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
16608> 2023-02-24 19:43:17> ApplyReleasesImpl: File 'C:\Users\astra\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\VoiceAccess.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
16608> 2023-02-24 19:43:17> ApplyReleasesImpl: Updating shortcut C:\Users\astra\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Discord Inc\Discord.lnk
16608> 2023-02-24 19:43:17> ApplyReleasesImpl: Updating shortcut C:\Users\astra\OneDrive\Desktop\Discord.lnk
16608> 2023-02-24 19:43:17> ApplyReleasesImpl: Fixing up tray icons
16608> 2023-02-24 19:43:17> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9011
16608> 2023-02-24 19:43:17> ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-1.0.9011
2023-05-10 18:03:16> Program: Starting Squirrel Updater: --install . --checkInstall --source=PROPLUS --silent --exeName=Teams.exe
2023-05-10 18:03:16> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\ProductReleaseIds exists. Data - OneNoteFreeRetail,O365ProPlusRetail
2023-05-10 18:03:16> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\AudienceData exists. Data - Production::CC
2023-05-10 18:03:16> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\LastScenario exists. Data - UPDATE
2023-05-10 18:03:16> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Cloud\Office\16.0\Teams does not exist
2023-05-10 18:03:16> Program: Registry value Software\Policies\Microsoft\Cloud\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2023-05-10 18:03:16> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\Teams does not exist
2023-05-10 18:03:16> Program: Registry value Software\Policies\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2023-05-10 18:03:16> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Teams does not exist
2023-05-10 18:03:16> Program: Registry value Software\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2023-05-10 18:03:16> Program: Registry flags are not set: proceed with default value NotConfigured
2023-05-10 18:03:16> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams does not exist
2023-05-10 18:03:16> RegistryService: TryDeleteRegKey: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams not found
2023-05-10 18:03:16> LogHost: Write failed.
2023-05-10 18:03:16> LogHost: Message: Scenario.Status: success, scenario: 4a69dccc-96a4-4438-809f-acc279ce7548, Scenario.Name: desktop_squirrel_install, Scenario.Step: start, sequence: 0, appversion: 1.5.00.30767, platformId: 27, DeviceInfo.OsName: Windows, DeviceInfo.CpuArchitecture: x64, DeviceInfo.OsVersion: 10.0.22621.0, AppInfo.ProcessArchitecture: x86, AppInfo.ClientType: desktop, dllSearchPathState: unset, clientType: desktop, source: msi, distSrc: PROPLUS_OneNoteFreeRetail,O365ProPlusRetail, breadcrumb: , ppChannel: Production::CC, ppInstallMode: UPDATE, autoStartGpoPolicy: NotConfigured, desktopSession: desktop-e8680aea-3709-4f48-8faf-55e40757cdd0, installSessionId: 899930f0c704216cd49e589341e6dfc8b1947287193a264299689e17d41cbcdb, delta: 2, scenarioDelta: 2, elapsed: 1683734596863, stepDelta: 0, DeviceInfo.ComputerUuid: fcfed3f9f93eed1180e8088fc37b9312, DeviceInfo.OfficeMachineId: e506c74f9908d24ea32124af646109c9, InstallerVersion: 3.2.7.0, eventpdclevel: 1, userpdclevel: 0
2023-05-10 18:03:17> LogHost: Stack trace: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\astra\AppData\Roaming\Microsoft\Teams\SquirrelTelemetry.log'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at Telemetry.AriaWrapper.LogToFile(String message)
2023-05-10 18:03:17> Program: Starting install, writing to C:\Users\astra\AppData\Local\SquirrelTemp
2023-05-10 18:03:17> Program: File does not contain contextual info: Teams.exe
2023-05-10 18:03:17> UpdateManager: using rootAppDirectory: C:\Users\astra\AppData\Local\Microsoft\Teams
2023-05-10 18:03:17> Program: About to install to: C:\Users\astra\AppData\Local\Microsoft\Teams
2023-05-10 18:03:17> Program: Setup.json exist, copying over
2023-05-10 18:03:17> RegistryService: RegKeyExists: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run has TeamsMachineInstaller. Data - C:\Program Files (x86)\Teams Installer\Teams.exe --checkInstall --source=PROPLUS
2023-05-10 18:03:17> RegistryService: TrySetRegKey: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams\InstallSource created
2023-05-10 18:03:17> RegistryService: TrySetRegKey: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams\InstallSource set successfully as MSI
2023-05-10 18:03:17> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\astra\AppData\Local\Microsoft\Teams\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2023-05-10 18:03:17> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\astra\AppData\Local\Microsoft\Teams\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__8.MoveNext()
2023-05-10 18:03:17> CheckForUpdateImpl: Reading RELEASES file from C:\Users\astra\AppData\Local\SquirrelTemp
2023-05-10 18:03:17> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2023-05-10 18:03:17> RegistryService: RegKeyExists: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\Teams\ does not exist
2023-05-10 18:03:17> ApplyReleasesImpl: No delta packages found. Applying current release package.
2023-05-10 18:03:17> ApplyReleasesImpl: getting squirrel aware apps failed with exception Could not find a part of the path 'C:\Users\astra\AppData\Local\Microsoft\Teams\current'.
2023-05-10 18:03:17> ApplyReleasesImpl: Writing files to app directory: C:\Users\astra\AppData\Local\Microsoft\Teams\current
2023-05-10 18:03:20> RegistryService: RegKeyExists: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\Teams\ does not exist
2023-05-10 18:03:21> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\astra\AppData\Local\Microsoft\Teams\current\Teams.exe]
2023-05-10 18:03:28> ApplyReleasesImpl: About to RemoveOldShorcuts for Teams.exe, rootAppDir C:\Users\astra\AppData\Local\Microsoft\Teams
2023-05-10 18:03:28> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Cloud\Office\16.0\Teams does not exist
2023-05-10 18:03:28> ApplyReleasesImpl: Registry value Software\Policies\Microsoft\Cloud\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2023-05-10 18:03:28> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\Teams does not exist
2023-05-10 18:03:28> ApplyReleasesImpl: Registry value Software\Policies\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2023-05-10 18:03:28> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Teams does not exist
2023-05-10 18:03:28> ApplyReleasesImpl: Registry value Software\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2023-05-10 18:03:28> ApplyReleasesImpl: Registry flags are not set: proceed with default value NotConfigured
2023-05-10 18:03:28> ApplyReleasesImpl: Starting fixPinnedExecutables
2023-05-10 18:03:28> ApplyReleasesImpl: Examining Pin: Cisco AnyConnect Secure Mobility Client.lnk
2023-05-10 18:03:28> ApplyReleasesImpl: Examining Pin: Control Panel.lnk
2023-05-10 18:03:28> ApplyReleasesImpl: Examining Pin: Epic Games Launcher.lnk
2023-05-10 18:03:28> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2023-05-10 18:03:28> ApplyReleasesImpl: Examining Pin: GitHub Desktop.lnk
2023-05-10 18:03:28> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2023-05-10 18:03:28> ApplyReleasesImpl: Examining Pin: Microsoft Edge.lnk
2023-05-10 18:03:28> ApplyReleasesImpl: Examining Pin: OBS Studio (64bit).lnk
2023-05-10 18:03:28> ApplyReleasesImpl: Examining Pin: Planet9 Stub.lnk
2023-05-10 18:03:28> ApplyReleasesImpl: Examining Pin: Task Manager.lnk
2023-05-10 18:03:28> ApplyReleasesImpl: Examining Pin: Unity Hub.lnk
2023-05-10 18:03:28> ApplyReleasesImpl: Examining Pin: Visual Studio 2022.lnk
2023-05-10 18:03:28> ApplyReleasesImpl: Examining Pin: Zoom.lnk
2023-05-10 18:03:28> ApplyReleasesImpl: Fixing up tray icons
2023-05-10 18:03:28> MeetingAddinInstaller: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Squirrel.MeetingAddinInstaller.<InstallMeetingAddinAsync>d__15.MoveNext()
2023-05-10 18:03:28> MeetingAddinInstaller: StagedAppDirectory does not exist. Using Current
2023-05-10 18:03:28> MeetingAddinInstaller: There is no version.txt. Falling back to getting version from folder name
2023-05-10 18:03:28> MeetingAddinInstaller: Version: 1.0.22272.2; addinPackageDirectory: 1.0.22272.2
2023-05-10 18:03:28> MeetingAddinInstaller: .dead exists: False
2023-05-10 18:03:28> MeetingAddinInstaller: path to .dead: C:\Users\astra\AppData\Local\Microsoft\TeamsMeetingAddin\1.0.22272.2\.dead
2023-05-10 18:03:28> MeetingAddinInstaller: before cleanup unused versions
2023-05-10 18:03:28> MeetingAddinInstaller: Addin directory exists. Copy was successful
2023-05-10 18:03:28> MeetingAddinInstaller: Version 1.0.22272.2 of the meeting add-in is now installed
2023-05-10 18:03:28> PresenceAddinInstaller: Installing Teams Presence addin for Outlook...
2023-05-10 18:03:28> PresenceAddinInstaller: Copying C:\Users\astra\AppData\Local\Microsoft\Teams\current\resources\assets\tlb\Uc.tlb to C:\Users\astra\AppData\Local\Microsoft\TeamsPresenceAddin
2023-05-10 18:03:28> PresenceAddinInstaller: Copying C:\Users\astra\AppData\Local\Microsoft\Teams\current\resources\assets\tlb\Uc.win32.tlb to C:\Users\astra\AppData\Local\Microsoft\TeamsPresenceAddin
2023-05-10 18:03:28> PresenceAddinInstaller: check if UC TypeLib points to current\resources\assets\tlb\Uc.tlb
2023-05-10 18:03:28> PresenceAddinInstaller: Registering UC Typelib WIN32 under HKCU...
2023-05-10 18:03:29> PresenceAddinInstaller: UC Typelib WIN32 successfully registered to C:\Users\astra\AppData\Local\Microsoft\TeamsPresenceAddin\Uc.win32.tlb under HKCU!
2023-05-10 18:03:29> PresenceAddinInstaller: UC Typelib WIN64 is registered under HKLM and file exists. Registration not needed!
2023-05-10 18:03:29> PresenceAddinInstaller: IM Provider registry key already exists!
2023-05-10 18:03:29> ApplyReleasesImpl: cleanDeadVersions: for original version of  and current version of 1.5.00.30767
2023-05-10 18:03:29> ApplyReleasesImpl: cleanDeadVersions: exclude current folder stage
2023-05-10 18:04:06> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine 2.16.100.168:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__6.MoveNext()
2023-05-10 18:04:06> RegistryService: TryDeleteRegKey: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams\PreventInstallationFromMsi not found
```

### Release version

Github Desktop Installer

### Operating system

Windows 11

### Log files

[SquirrelSetup_LogError.txt](https://github.com/desktop/desktop/files/14885848/SquirrelSetup_LogError.txt)

**Comment by sergiou87** [comment]
Thanks for your report @Astradeni 

Unfortunately, that log doesn't say anything relevant to GitHub Desktop 😞 

Is that a work machine or is a personal one? If it's a work machine, maybe try to contact the admin because it's really odd that GitHub Desktop just disappeared from your system.

The other option is that you might be running an antivirus that is blocking/deleting it for some reason? It could even be Windows Defender. If so, I recommend disabling the antivirus temporarily to test this and see if it makes a difference.

**Comment by Astradeni** [comment]
Thank you! The moment I disabled the antivirus I ran it and it worked

**Comment by steveward** [comment]
Glad to hear things are working for you now!
