### ISSUE TITLE
My github desktop is crashing

### ISSUE THREAD

**Issue by etunay-mufin** [desktop/desktop#18476]
### The problem

When I start a Github Desktop. App is frozzen

2024-04-17T00:02:23.545Z - info: [ui] [Timing] Action 'create commit' for 'globalmsq/msq-real-time-translator-backend' took 0.471s
2024-04-17T00:04:32.164Z - warn: [ui] fetchRepository: 'Tuntii/InvestLyst' returned a 404
2024-04-17T00:04:53.888Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T00:04:54.230Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T00:04:54.230Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T00:04:54.248Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2024-04-17T00:04:54.446Z - info: [ui] launching: 3.3.13 (Windows 10.0.19045)
2024-04-17T00:04:54.448Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.13\GitHubDesktop.exe'
2024-04-17T00:05:13.184Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T00:05:13.521Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T00:05:13.522Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T00:05:13.551Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2024-04-17T00:05:34.317Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T00:05:34.698Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T00:05:34.700Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T00:05:34.708Z - info: [ui] Subscribed 'etunay-mufin' to Alive channel
2024-04-17T00:05:34.722Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2024-04-17T00:05:35.093Z - info: [ui] launching: 3.3.13 (Windows 10.0.19045)
2024-04-17T00:05:35.093Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.13\GitHubDesktop.exe'
2024-04-17T00:07:02.786Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T00:07:03.137Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T00:07:03.138Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T00:07:03.158Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2024-04-17T00:07:03.410Z - info: [ui] launching: 3.3.13 (Windows 10.0.19045)
2024-04-17T00:07:03.417Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.13\GitHubDesktop.exe'
2024-04-17T00:07:53.936Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: msq-real-time-translator-backend - etunay-mufin (has token)
2024-04-17T00:10:03.678Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T00:10:04.075Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T00:10:04.075Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T00:10:04.094Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2024-04-17T00:10:04.297Z - info: [ui] launching: 3.3.13 (Windows 10.0.19045)
2024-04-17T00:10:04.303Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.13\GitHubDesktop.exe'
2024-04-17T00:10:04.679Z - info: [ui] Subscribed 'etunay-mufin' to Alive channel
2024-04-17T11:47:21.444Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T11:47:22.193Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T11:47:22.194Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T11:47:22.227Z - info: [ui] [BranchPruner] Last prune took place 18 hours ago - skipping
2024-04-17T11:47:22.577Z - info: [ui] launching: 3.3.13 (Windows 10.0.19045)
2024-04-17T11:47:22.588Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.13\GitHubDesktop.exe'
2024-04-17T11:47:46.324Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T11:58:00.134Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\tunay\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2024-04-17T11:58:00.145Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\tunay\Desktop\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2024-04-17T11:58:00.145Z - error: [main] Toast activator CLSID not found in any of the shortcuts. Falling back to known CLSIDs.
2024-04-17T11:58:00.145Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T11:58:01.010Z - info: [main] Received possible protocol arguments: 2
2024-04-17T11:58:01.031Z - error: [main] Malformed launch arguments received: C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.11\GitHubDesktop.exe,--squirrel-firstrun
2024-04-17T11:58:01.032Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T11:58:01.489Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T11:58:01.490Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T11:58:01.524Z - info: [ui] [BranchPruner] Last prune took place 18 hours ago - skipping
2024-04-17T11:58:01.937Z - info: [ui] launching: 3.3.11 (Windows 10.0.19045)
2024-04-17T11:58:01.939Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.11\GitHubDesktop.exe'
2024-04-17T11:58:02.336Z - info: [ui] Subscribed 'etunay-mufin' to Alive channel
2024-04-17T12:00:17.685Z - info: [ui] Executing getRemotes: git remote -v (took 135.287s)
2024-04-17T12:00:17.746Z - info: [ui] Executing getRemotes: git remote -v (took 80.110s)
2024-04-17T12:00:17.747Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 135.810s)
2024-04-17T12:00:17.747Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 135.380s)
2024-04-17T12:00:17.747Z - info: [ui] Executing getStashEntries: git log -g -z --format=%gD%x00%H%x00%gs%x00%T%x00%P refs/stash (took 135.384s)
2024-04-17T12:00:17.748Z - info: [ui] Executing getCommits: git log origin/AI-458-fixing..AI-458-fixing --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 135.388s)
2024-04-17T12:00:17.752Z - info: [ui] Executing getConfigValueInPath: git config -z --local user.name (took 135.400s)
2024-04-17T12:00:17.760Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 135.421s)
2024-04-17T12:00:19.448Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.624s)
2024-04-17T12:00:20.566Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.116s)
2024-04-17T12:03:37.870Z - info: [ui] Executing getRemotes: git remote -v (took 149.490s)
2024-04-17T12:26:49.011Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T12:26:49.357Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T12:26:49.358Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T12:26:49.375Z - info: [ui] [BranchPruner] Last prune took place 19 hours ago - skipping
2024-04-17T12:26:49.599Z - info: [ui] launching: 3.3.11 (Windows 10.0.19045)
2024-04-17T12:26:49.603Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.11\GitHubDesktop.exe'
2024-04-17T12:26:49.929Z - info: [ui] Subscribed 'etunay-mufin' to Alive channel

### Release version

release-3.3.14

### Operating system

Windows

### Log files

2024-04-17T00:02:23.545Z - info: [ui] [Timing] Action 'create commit' for 'globalmsq/msq-real-time-translator-backend' took 0.471s
2024-04-17T00:04:32.164Z - warn: [ui] fetchRepository: 'Tuntii/InvestLyst' returned a 404
2024-04-17T00:04:53.888Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T00:04:54.230Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T00:04:54.230Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T00:04:54.248Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2024-04-17T00:04:54.446Z - info: [ui] launching: 3.3.13 (Windows 10.0.19045)
2024-04-17T00:04:54.448Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.13\GitHubDesktop.exe'
2024-04-17T00:05:13.184Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T00:05:13.521Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T00:05:13.522Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T00:05:13.551Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2024-04-17T00:05:34.317Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T00:05:34.698Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T00:05:34.700Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T00:05:34.708Z - info: [ui] Subscribed 'etunay-mufin' to Alive channel
2024-04-17T00:05:34.722Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2024-04-17T00:05:35.093Z - info: [ui] launching: 3.3.13 (Windows 10.0.19045)
2024-04-17T00:05:35.093Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.13\GitHubDesktop.exe'
2024-04-17T00:07:02.786Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T00:07:03.137Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T00:07:03.138Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T00:07:03.158Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2024-04-17T00:07:03.410Z - info: [ui] launching: 3.3.13 (Windows 10.0.19045)
2024-04-17T00:07:03.417Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.13\GitHubDesktop.exe'
2024-04-17T00:07:53.936Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: msq-real-time-translator-backend - etunay-mufin (has token)
2024-04-17T00:10:03.678Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T00:10:04.075Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T00:10:04.075Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T00:10:04.094Z - info: [ui] [BranchPruner] Last prune took place 6 hours ago - skipping
2024-04-17T00:10:04.297Z - info: [ui] launching: 3.3.13 (Windows 10.0.19045)
2024-04-17T00:10:04.303Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.13\GitHubDesktop.exe'
2024-04-17T00:10:04.679Z - info: [ui] Subscribed 'etunay-mufin' to Alive channel
2024-04-17T11:47:21.444Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T11:47:22.193Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T11:47:22.194Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T11:47:22.227Z - info: [ui] [BranchPruner] Last prune took place 18 hours ago - skipping
2024-04-17T11:47:22.577Z - info: [ui] launching: 3.3.13 (Windows 10.0.19045)
2024-04-17T11:47:22.588Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.13\GitHubDesktop.exe'
2024-04-17T11:47:46.324Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T11:58:00.134Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\tunay\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2024-04-17T11:58:00.145Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\tunay\Desktop\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7
    at Object.<anonymous> (C:\Users\tunay\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:713:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
2024-04-17T11:58:00.145Z - error: [main] Toast activator CLSID not found in any of the shortcuts. Falling back to known CLSIDs.
2024-04-17T11:58:00.145Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T11:58:01.010Z - info: [main] Received possible protocol arguments: 2
2024-04-17T11:58:01.031Z - error: [main] Malformed launch arguments received: C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.11\GitHubDesktop.exe,--squirrel-firstrun
2024-04-17T11:58:01.032Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T11:58:01.489Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T11:58:01.490Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T11:58:01.524Z - info: [ui] [BranchPruner] Last prune took place 18 hours ago - skipping
2024-04-17T11:58:01.937Z - info: [ui] launching: 3.3.11 (Windows 10.0.19045)
2024-04-17T11:58:01.939Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.11\GitHubDesktop.exe'
2024-04-17T11:58:02.336Z - info: [ui] Subscribed 'etunay-mufin' to Alive channel
2024-04-17T12:00:17.685Z - info: [ui] Executing getRemotes: git remote -v (took 135.287s)
2024-04-17T12:00:17.746Z - info: [ui] Executing getRemotes: git remote -v (took 80.110s)
2024-04-17T12:00:17.747Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 135.810s)
2024-04-17T12:00:17.747Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 135.380s)
2024-04-17T12:00:17.747Z - info: [ui] Executing getStashEntries: git log -g -z --format=%gD%x00%H%x00%gs%x00%T%x00%P refs/stash (took 135.384s)
2024-04-17T12:00:17.748Z - info: [ui] Executing getCommits: git log origin/AI-458-fixing..AI-458-fixing --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 135.388s)
2024-04-17T12:00:17.752Z - info: [ui] Executing getConfigValueInPath: git config -z --local user.name (took 135.400s)
2024-04-17T12:00:17.760Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 135.421s)
2024-04-17T12:00:19.448Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.624s)
2024-04-17T12:00:20.566Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.116s)
2024-04-17T12:03:37.870Z - info: [ui] Executing getRemotes: git remote -v (took 149.490s)
2024-04-17T12:26:49.011Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-17T12:26:49.357Z - info: [ui] [AppStore] loading 11 repositories from store
2024-04-17T12:26:49.358Z - info: [ui] [AppStore] found account: etunay-mufin (Tunay Engin)
2024-04-17T12:26:49.375Z - info: [ui] [BranchPruner] Last prune took place 19 hours ago - skipping
2024-04-17T12:26:49.599Z - info: [ui] launching: 3.3.11 (Windows 10.0.19045)
2024-04-17T12:26:49.603Z - info: [ui] execPath: 'C:\Users\tunay\AppData\Local\GitHubDesktop\app-3.3.11\GitHubDesktop.exe'
2024-04-17T12:26:49.929Z - info: [ui] Subscribed 'etunay-mufin' to Alive channel

**Comment by steveward** [comment]
Thanks for the report @etunay-mufin. I'm seeing some Git operations in the log file that are taking a while to complete. Are you possibly running any antivirus or other security software that could be interfering with GitHub Desktop? We've seen performance issues like this caused by antivirus software.

**Comment by etunay-mufin** [comment]
No, but I install new version and now its working fine.
