### ISSUE TITLE
Pushing stopped working for me after update

### ISSUE THREAD

**Issue by ghostWDFR** [desktop/desktop#18581]
### The problem

After update I can't even push any file...

### Release version

Version 3.3.16 (x64)

### Operating system

Windows 11

### Log files

2024-05-09T00:56:02.743Z - info: [ui] [fetchAllRepoRulesets] unable to fetch all repo rulesets | repos/*/*/rulesets
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at yn (C:\Users\*\AppData\Local\GitHubDesktop\app-3.3.16\webpack:\app\src\lib\http.ts:178:11)
    at ir.fetchAllRepoRulesets (C:\Users\*\AppData\Local\GitHubDesktop\app-3.3.16\webpack:\app\src\lib\api.ts:1682:7)
    at $p.refreshBranchProtectionState (C:\Users\*\AppData\Local\GitHubDesktop\app-3.3.16\webpack:\app\src\lib\stores\app-store.ts:1210:15)
    at $p.repositoryWithRefreshedGitHubRepository (C:\Users\*\AppData\Local\GitHubDesktop\app-3.3.16\webpack:\app\src\lib\stores\app-store.ts:4139:5)
2024-05-09T00:56:03.118Z - info: [ui] [fetchRepoRulesForBranch] unable to fetch repo rules for branch: main | repos/*/*/rules/branches/main
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.

**Comment by tidy-dev** [comment]
👋 Sorry for your troubles @ghostWDFR. We are investigating the issue and tracking under https://github.com/desktop/desktop/issues/18579 as you have found. I am closing this in favor of that one.
