### ISSUE TITLE
Windows installer never completes installation

### ISSUE THREAD

**Issue by francisrath** [desktop/desktop#1863]
### Description

Installer goes into a loop, never finishing the install. No UI is shown at all.

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

1. Clean install of Windows 10 Pro
2. Download and install
3. Installer never completes, looping a squirrel-task appoximately once per second

It looks like all the files are installed, but running GitHub Desktop.exe does not start the program.

**Expected behaviour:** Installer completes

**Actual behaviour:** Installer loops indefinitely

**Reproduces how often:** 100%

### Logs

Contents of `C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9\SquirrelSetup.log`: (complete)
```
2017-06-01 17.28.23> Program: Starting Squirrel Updater: --updateSelf=C:\Users\fr\AppData\Local\SquirrelTemp\Update.exe
2017-06-01 17.28.23> Program: About to wait for parent PID 8960
```

Content of `C:\Users\fr\AppData\Local\GitHubDesktop\SquirrelSetup.log`: (partial)
```
2017-06-01 17.28.23> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
2017-06-01 17.28.23> ApplyReleasesImpl: About to create shortcuts for GitHub Desktop.exe, rootAppDir C:\Users\fr\AppData\Local\GitHubDesktop
2017-06-01 17.28.23> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\fr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2017-06-01 17.28.23> ApplyReleasesImpl: About to save shortcut: C:\Users\fr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\fr\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-01 17.28.23> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\fr\Desktop\GitHub Desktop.lnk
2017-06-01 17.28.23> ApplyReleasesImpl: About to save shortcut: C:\Users\fr\Desktop\GitHub Desktop.lnk (target C:\Users\fr\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-01 17.28.23> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-06-01 17.28.23> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
2017-06-01 17.28.23> ApplyReleasesImpl: About to create shortcuts for GitHub Desktop.exe, rootAppDir C:\Users\fr\AppData\Local\GitHubDesktop
2017-06-01 17.28.23> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\fr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2017-06-01 17.28.23> ApplyReleasesImpl: About to save shortcut: C:\Users\fr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\fr\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-01 17.28.23> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\fr\Desktop\GitHub Desktop.lnk
2017-06-01 17.28.23> ApplyReleasesImpl: About to save shortcut: C:\Users\fr\Desktop\GitHub Desktop.lnk (target C:\Users\fr\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-01 17.28.23> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
[repeatedly]
```

#### Additional Information

New machine with AMD Ryzen CPU.

**Comment by shiftkey** [comment]
```
2017-06-01 17.28.23> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
```

@francisrath this is interesting - what other things do you have installed that have icons on the desktop?

**Comment by francisrath** [comment]
Oh, I forgot: I tried to kill `GitHub Desktop.exe` but it keeps popping up. Deleting the installation folder finally kills it.

After a reboot I tried again with the same results.

**Comment by francisrath** [comment]
Since this is a new machine, I just have a few things installed:

- Chrome
- Visual Studio Code
- Slack
- Spotify
- GitHub Desktop

All of those (except GitHub Desktop) have a desktop icon.

**Comment by francisrath** [comment]
I deleted the Chrome link, and now the Squrrel log says:

```
2017-06-01 17.46.49> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
2017-06-01 17.46.49> ApplyReleasesImpl: About to create shortcuts for GitHub Desktop.exe, rootAppDir C:\Users\fr\AppData\Local\GitHubDesktop
2017-06-01 17.46.49> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\fr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2017-06-01 17.46.49> ApplyReleasesImpl: About to save shortcut: C:\Users\fr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\fr\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-01 17.46.49> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\fr\Desktop\GitHub Desktop.lnk
2017-06-01 17.46.49> ApplyReleasesImpl: About to save shortcut: C:\Users\fr\Desktop\GitHub Desktop.lnk (target C:\Users\fr\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
```

**Comment by francisrath** [comment]
That was strange. I rebooted for Windows Update, and then it seems to work.

Last bits from the log Squirrel log (before and after reboot):

```
2017-06-01 17.48.25> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
2017-06-01 17.48.25> ApplyReleasesImpl: About to create shortcuts for GitHub Desktop.exe, rootAppDir C:\Users\fr\AppData\Local\GitHubDesktop
2017-06-01 17.48.25> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\fr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2017-06-01 17.48.25> ApplyReleasesImpl: About to save shortcut: C:\Users\fr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\fr\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-01 17.48.25> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\fr\Desktop\GitHub Desktop.lnk
2017-06-01 17.48.25> ApplyReleasesImpl: About to save shortcut: C:\Users\fr\Desktop\GitHub Desktop.lnk (target C:\Users\fr\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
```
```
2017-06-01 17.53.45> Program: Starting Squirrel Updater: --download https://central.github.com/api/deployments/desktop/desktop/latest?version=0.5.9&username=
2017-06-01 17.53.45> Program: Fetching update information, downloading from https://central.github.com/api/deployments/desktop/desktop/latest?version=0.5.9&username=
2017-06-01 17.53.45> CheckForUpdateImpl: Generated new staging user ID: 79842121-7b88-5768-a58e-2e1f4cfd12e8
2017-06-01 17.53.46> CheckForUpdateImpl: Downloading RELEASES file from https://central.github.com/api/deployments/desktop/desktop/latest?version=0.5.9&username=
2017-06-01 17.53.46> FileDownloader: Downloading url: https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=0.5.9&username=&id=GitHubDesktop&localVersion=0.5.9&arch=amd64
```

**Comment by smazoyer** [comment]
Hello 

I think I have a similar problem.

**Version**

GitHub Desktop version: 0.5.9
OS version: Microsoft Windows 7 Version 6.1

Content of ```C:\Users\Simon\AppData\Local\GitHubDesktop\SquirrelSetup.log:```  (partial)
```
2017-06-02 16:41:26> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
2017-06-02 16:41:26> ApplyReleasesImpl: About to create shortcuts for GitHub Desktop.exe, rootAppDir C:\Users\Simon\AppData\Local\GitHubDesktop
2017-06-02 16:41:26> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\Simon\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2017-06-02 16:41:27> ApplyReleasesImpl: About to save shortcut: C:\Users\Simon\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\Simon\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\Simon\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-02 16:41:27> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\Simon\Desktop\GitHub Desktop.lnk
2017-06-02 16:41:27> ApplyReleasesImpl: About to save shortcut: C:\Users\Simon\Desktop\GitHub Desktop.lnk (target C:\Users\Simon\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\Simon\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-02 16:41:27> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-06-02 16:41:27> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2017-06-02 16:41:27> ApplyReleasesImpl: Examining Pin: Microsoft Outlook 2010.lnk
2017-06-02 16:41:27> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
```

This loop repeats itself in the log.

**Comment by francisrath** [comment]
The same happened on my laptop, installing the same version of GitHub Desktop today. "Fixed" it by rebooting after the Squirrel loop started.

**Comment by leonardooliveira95** [comment]
I'm having the same problem

GitHub Desktop 0.5.9
Windows 10

The log loops:
``
C:\Users\leonardo.oliveira\AppData\Local\GitHubDesktop\SquirrelSetup.log:
``

```
2017-06-06 10:48:48> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-06-06 10:48:48> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
2017-06-06 10:48:48> ApplyReleasesImpl: About to create shortcuts for GitHub Desktop.exe, rootAppDir C:\Users\leonardo.oliveira\AppData\Local\GitHubDesktop
2017-06-06 10:48:49> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\leonardo.oliveira\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2017-06-06 10:48:49> ApplyReleasesImpl: About to save shortcut: C:\Users\leonardo.oliveira\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\leonardo.oliveira\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\leonardo.oliveira\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-06 10:48:49> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\leonardo.oliveira\Desktop\GitHub Desktop.lnk
2017-06-06 10:48:49> ApplyReleasesImpl: About to save shortcut: C:\Users\leonardo.oliveira\Desktop\GitHub Desktop.lnk (target C:\Users\leonardo.oliveira\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\leonardo.oliveira\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-06 10:48:49> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-06-06 10:48:49> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
2017-06-06 10:48:49> ApplyReleasesImpl: About to create shortcuts for GitHub Desktop.exe, rootAppDir C:\Users\leonardo.oliveira\AppData\Local\GitHubDesktop
2017-06-06 10:48:49> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\leonardo.oliveira\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2017-06-06 10:48:49> ApplyReleasesImpl: About to save shortcut: C:\Users\leonardo.oliveira\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\leonardo.oliveira\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\leonardo.oliveira\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-06 10:48:49> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\leonardo.oliveira\Desktop\GitHub Desktop.lnk
2017-06-06 10:48:49> ApplyReleasesImpl: About to save shortcut: C:\Users\leonardo.oliveira\Desktop\GitHub Desktop.lnk (target C:\Users\leonardo.oliveira\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\leonardo.oliveira\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-06 10:48:49> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
```

After rebooting, it works ok, but the installation is broken.

**Comment by cpdavngr** [comment]
Same problem here. Tried two different systems. I couldn't even kill the processes that kept popping back up. I had to logout and log back in again. However, after I logged back in, it appeared to be installed.

**Comment by norgepaul** [comment]
Same issue on two different Windows 10 machines. Installer continually creates new processes and seems impossible to kill without logging out.

**Comment by mzannoni** [comment]
Same here. I then rebooted, the process creation was not looping any more, but nothing was installed. But I had GitHub Desktop among the software in the Control Panel, from where I could unistall it.

**Comment by beatcracker** [comment]
Similar issue on `Windows Server 2012 R2 x64`:

```
2017-06-29 22:31:56> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
2017-06-29 22:31:56> ApplyReleasesImpl: About to create shortcuts for GitHub Desktop.exe, rootAppDir C:\Users\Administrator\AppData\Local\GitHubDesktop
2017-06-29 22:31:57> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\Administrator\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2017-06-29 22:31:57> ApplyReleasesImpl: About to save shortcut: C:\Users\Administrator\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\Administrator\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\Administrator\AppData\Local\GitHubDesktop\app-0.6.2, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-29 22:31:57> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\Administrator\Desktop\GitHub Desktop.lnk
2017-06-29 22:31:57> ApplyReleasesImpl: About to save shortcut: C:\Users\Administrator\Desktop\GitHub Desktop.lnk (target C:\Users\Administrator\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\Administrator\AppData\Local\GitHubDesktop\app-0.6.2, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-29 22:31:57> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-06-29 22:31:57> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-06-29 22:31:57> ApplyReleasesImpl: Examining Pin: Server Manager.lnk
2017-06-29 22:31:57> ApplyReleasesImpl: File 'C:\Users\Administrator\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Server Manager.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
```

Workaround:

* Kill all `GitHub Desktop` processes using `taskkill "GitHub Desktop"` from `Win+R` "Run" window.
* Move `Server Manager.lnk` to some other dir.
* Relaunch `GitHub Desktop`.

I've been able to move shortcut back after that. Not sure if it wouldn't break again when `Update.exe` tries to update next time.

**Comment by zeusly** [comment]
Hi, same issue. Noticed my Surface Book running on full blast during install and nothing happening.

Log showed this loop:

```
2017-06-30 20:48:23> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
2017-06-30 20:48:24> ApplyReleasesImpl: About to create shortcuts for GitHub Desktop.exe, rootAppDir C:\Users\Oskar\AppData\Local\GitHubDesktop
2017-06-30 20:48:24> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\Oskar\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2017-06-30 20:48:24> ApplyReleasesImpl: About to save shortcut: C:\Users\Oskar\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\Oskar\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\Oskar\AppData\Local\GitHubDesktop\app-0.6.2, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-30 20:48:24> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\Oskar\Desktop\GitHub Desktop.lnk
2017-06-30 20:48:24> ApplyReleasesImpl: About to save shortcut: C:\Users\Oskar\Desktop\GitHub Desktop.lnk (target C:\Users\Oskar\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\Oskar\AppData\Local\GitHubDesktop\app-0.6.2, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-30 20:48:24> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-06-30 20:48:24> ApplyReleasesImpl: Examining Pin: Visual Studio Code.lnk
2017-06-30 20:48:24> ApplyReleasesImpl: Examining Pin: WhatsApp.lnk
```
Interestingly, these aren't Shortcuts on the Desktop but in the Task Bar.
I removed all three, but it still doesn't move any further, log shows this now in a loop:
```
2017-06-30 20:51:49> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
2017-06-30 20:51:49> ApplyReleasesImpl: About to create shortcuts for GitHub Desktop.exe, rootAppDir C:\Users\Oskar\AppData\Local\GitHubDesktop
2017-06-30 20:51:49> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\Oskar\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2017-06-30 20:51:49> ApplyReleasesImpl: About to save shortcut: C:\Users\Oskar\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\Oskar\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\Oskar\AppData\Local\GitHubDesktop\app-0.6.2, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-30 20:51:49> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\Oskar\Desktop\GitHub Desktop.lnk
2017-06-30 20:51:49> ApplyReleasesImpl: About to save shortcut: C:\Users\Oskar\Desktop\GitHub Desktop.lnk (target C:\Users\Oskar\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\Oskar\AppData\Local\GitHubDesktop\app-0.6.2, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
```

Then I killed the process with @beatcracker 's method above (tskill) and clicked the new desktop icon (which has been placed there before the loop started) to restart, now everything works fine. Last log entry shows:

```
2017-06-30 20:57:19> Program: Starting Squirrel Updater: --download https://central.github.com/api/deployments/desktop/desktop/latest?version=0.6.2&username=
2017-06-30 20:57:19> Program: Fetching update information, downloading from https://central.github.com/api/deployments/desktop/desktop/latest?version=0.6.2&username=
2017-06-30 20:57:19> CheckForUpdateImpl: Generated new staging user ID: dbe6ba29-25e3-5a23-a1ba-c0057c814864
2017-06-30 20:57:19> CheckForUpdateImpl: Downloading RELEASES file from https://central.github.com/api/deployments/desktop/desktop/latest?version=0.6.2&username=
2017-06-30 20:57:19> FileDownloader: Downloading url: https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=0.6.2&username=&id=GitHubDesktop&localVersion=0.6.2&arch=amd64
```

**Comment by CraigStuntz** [comment]
Same problem here. Like @zeusly, launching GitHub Desktop from the desktop icon actually does work after killing the auto-launching installers.

**Comment by blaise-braye** [comment]
Hi dears, exactly the same issue on my professional computer. as mentioned above, killing all process first then trying to run it again makes it working as expected. If you are not afraid by command line, here you are a quick Powershell command to achieve the killer result (probably needs to be executed as administrator)
`
Get-Process -Name 'GitHub Desktop' | % { $_.Kill() }
`

**Comment by pyromanci** [comment]
I had the same problem, So i went into the: C:\Users\<user>\AppData\Local\GitHubDesktop\app-0.6.2
Folder and saw another SquirrelSetup.log. Looking at it see:
```
2017-07-18 12:35:00> Program: Starting Squirrel Updater: --updateSelf=C:\Users\<user>\AppData\Local\SquirrelTemp\Update.exe
2017-07-18 12:35:00> Program: About to wait for parent PID 216484
2017-07-18 12:35:03> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\<user>\AppData\Local\GitHubDesktop\app-0.6.2\..\Update.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass6_0.<UpdateSelf>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<UpdateSelf>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\<user>\AppData\Local\GitHubDesktop\app-0.6.2\..\Update.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass6_0.<UpdateSelf>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<UpdateSelf>d__6.MoveNext()<---


```

**Comment by joshaber** [comment]
Yes, this'll be fixed in the 0.7.0 update later today.

**Comment by robotnikthingy** [comment]
Having the same problem and came accross this when doing a google search. Im on a fresh Windows 10 install, and I have this in my SquirrelSetup file

`2018-01-04 20:48:02> Program: Starting Squirrel Updater: --createShortcut GitHubDesktop.exe -l StartMenu,Desktop
2018-01-04 20:48:02> ApplyReleasesImpl: About to create shortcuts for GitHubDesktop.exe, rootAppDir C:\Users\admin\AppData\Local\GitHubDesktop
2018-01-04 20:48:02> ApplyReleasesImpl: Creating shortcut for GitHubDesktop.exe => C:\Users\admin\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2018-01-04 20:48:02> ApplyReleasesImpl: About to save shortcut: C:\Users\admin\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\admin\AppData\Local\GitHubDesktop\GitHubDesktop.exe, workingDir C:\Users\admin\AppData\Local\GitHubDesktop\app-1.0.11, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2018-01-04 20:48:02> ApplyReleasesImpl: Creating shortcut for GitHubDesktop.exe => C:\Users\admin\Desktop\GitHub Desktop.lnk
2018-01-04 20:48:02> ApplyReleasesImpl: About to save shortcut: C:\Users\admin\Desktop\GitHub Desktop.lnk (target C:\Users\admin\AppData\Local\GitHubDesktop\GitHubDesktop.exe, workingDir C:\Users\admin\AppData\Local\GitHubDesktop\app-1.0.11, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2018-01-04 20:48:02> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
`

**Comment by lucastaehli** [comment]
Having the same problem and not the first time. Reinstalling helped sometimes, now it doesnt...

2018-02-09 17:57:20> Program: Starting Squirrel Updater: --createShortcut GitHubDesktop.exe -l StartMenu,Desktop
2018-02-09 17:57:20> ApplyReleasesImpl: About to create shortcuts for GitHubDesktop.exe, rootAppDir C:\Users\lucas\AppData\Local\GitHubDesktop
2018-02-09 17:57:20> ApplyReleasesImpl: Creating shortcut for GitHubDesktop.exe => C:\Users\lucas\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2018-02-09 17:57:20> ApplyReleasesImpl: About to save shortcut: C:\Users\lucas\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\lucas\AppData\Local\GitHubDesktop\GitHubDesktop.exe, workingDir C:\Users\lucas\AppData\Local\GitHubDesktop\app-1.0.13, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2018-02-09 17:57:20> ApplyReleasesImpl: Creating shortcut for GitHubDesktop.exe => C:\Users\lucas\Desktop\GitHub Desktop.lnk
2018-02-09 17:57:20> ApplyReleasesImpl: About to save shortcut: C:\Users\lucas\Desktop\GitHub Desktop.lnk (target C:\Users\lucas\AppData\Local\GitHubDesktop\GitHubDesktop.exe, workingDir C:\Users\lucas\AppData\Local\GitHubDesktop\app-1.0.13, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2018-02-09 17:57:20> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-02-09 17:57:20> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2018-02-09 17:57:20> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2018-02-09 17:57:20> ApplyReleasesImpl: Examining Pin: Outlook 2016.lnk
2018-02-09 17:57:20> ApplyReleasesImpl: Examining Pin: Word 2016.lnk

**Comment by j-f1** [comment]
Can you open a new issue so we can investigate this separately?
