### ISSUE TITLE
Constant flickering

### ISSUE THREAD

**Issue by UsmaJulian** [desktop/desktop#18684]
### The problem

When opening the application in Windows, I have noticed a constant flickering of the application, which is constantly present in relatively short intervals. 

### Release version

3.3.18

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Open the application

### Log files

2024-05-24T20:24:16.129Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\jgame\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\jgame\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\jgame\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\jgame\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\jgame\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:722:7
    at Object.<anonymous> (C:\Users\jgame\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:722:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
2024-05-24T20:24:16.132Z - error: [main] Error looking for toast activator CLSID in shortcut C:\Users\jgame\Desktop\GitHub Desktop.lnk
Error: Failed to read shortcut link
    at ne (C:\Users\jgame\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:38:29)
    at C:\Users\jgame\AppData\Local\SquirrelTemp\webpack:\app\src\lib\find-toast-activator-clsid.ts:26:33
    at C:\Users\jgame\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\notifications.ts:28:32
    at C:\Users\jgame\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:722:7
    at Object.<anonymous> (C:\Users\jgame\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:722:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
2024-05-24T20:24:16.132Z - error: [main] Toast activator CLSID not found in any of the shortcuts. Falling back to known CLSIDs.
2024-05-24T20:24:16.132Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-05-24T20:24:16.554Z - info: [main] Received possible protocol arguments: 2
2024-05-24T20:24:16.573Z - error: [main] Malformed launch arguments received: C:\Users\jgame\AppData\Local\GitHubDesktop\app-3.3.18\GitHubDesktop.exe,--squirrel-firstrun
2024-05-24T20:24:16.573Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-05-24T20:24:16.995Z - info: [ui] [AppStore] loading 0 repositories from store
2024-05-24T20:24:17.089Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-05-24T20:24:17.093Z - info: [ui] launching: 3.3.18 (Windows 10.0.22631)
2024-05-24T20:24:17.094Z - info: [ui] execPath: 'C:\Users\jgame\AppData\Local\GitHubDesktop\app-3.3.18\GitHubDesktop.exe'
2024-05-24T20:24:17.293Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-05-24T20:24:17.339Z - info: [ui] Opt in reported.
2024-05-24T20:24:20.641Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
2024-05-24T20:24:20.642Z - info: [ui] [SignInStore] initializing OAuth flow
2024-05-24T20:24:20.642Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=a48fcc1f-5e76-4a48-adca-ac67589367d6
2024-05-24T20:24:20.643Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2024-05-24T20:24:32.343Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2024-05-24T20:24:45.690Z - info: [main] Received possible protocol arguments: 4
2024-05-24T20:24:45.695Z - info: [main] Processing protocol url
2024-05-24T20:24:45.700Z - info: [ui] [Dispatcher] requesting authenticated user
2024-05-24T20:24:45.705Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2024-05-24T20:24:46.653Z - info: [ui] [SignInStore] account resolved
2024-05-24T20:24:46.653Z - info: [ui] [AppStore] adding account UsmaJulian (Julian Usma Giraldo) to store
2024-05-24T20:24:46.654Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2024-05-24T20:24:46.678Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-05-24T20:24:46.939Z - info: [ui] Subscribed 'UsmaJulian' to Alive channel
2024-05-24T20:24:49.285Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-05-24T20:31:31.020Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-05-24T20:31:31.334Z - info: [ui] [AppStore] loading 0 repositories from store
2024-05-24T20:31:31.335Z - info: [ui] [AppStore] found account: UsmaJulian (Julian Usma Giraldo)
2024-05-24T20:31:31.419Z - info: [ui] launching: 3.3.18 (Windows 10.0.22631)
2024-05-24T20:31:31.420Z - info: [ui] execPath: 'C:\Users\jgame\AppData\Local\GitHubDesktop\app-3.3.18\GitHubDesktop.exe'
2024-05-24T20:31:31.737Z - info: [ui] Stats reported.
2024-05-24T20:31:31.834Z - info: [ui] Subscribed 'UsmaJulian' to Alive channel

**Comment by steveward** [comment]
Thanks for the report @UsmaJulian. See my comment [here](https://github.com/desktop/desktop/issues/18572#issuecomment-2101060343) to see if it resolves things for you. Some users have mentioned that G-Sync can cause this as well.
