### ISSUE TITLE
DEPTH_ZERO_SELF_SIGNED_CERT error on Github Enterprise

### ISSUE THREAD

**Issue by tintinn** [desktop/desktop#1895]
### Description

All of the users of our Github Enterprise instance have been using Github for Mac/Windows until last week when someone downloaded the Github Desktop beta version.

When logging into Github Enterprise with a username/password combo the process hangs without any error message printed out.

On the other hand, when authorizing the application with the browser an error message does pop up instead of indefinitely hanging.

The log from Developer Tools in the log section below

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** Mac OS X 10.11.16, 10.12.4

**Github Enterprise version:** 2.9.4

### Steps to Reproduce

1. Download and Extract Github Desktop anywhere on the system.
1. Launch Github Desktop
1. Follow the instructions to sign in.
1. Error, or lack of error with username/password

**Expected behaviour:** To be able to log into enterprise instance

**Actual behaviour:** Wasn't able to log into enterprise instance

**Reproduces how often:** 90% of the time?

### Logs

**Developer Tools**
```
renderer.js:1 App ready time: 125.19276699982584ms
renderer.js:1 Load time: 730.5050309989601ms
renderer.js:1 Renderer ready time: 346.96000000000004ms
renderer.js:3 Uncaught (in promise) L
code: "DEPTH_ZERO_SELF_SIGNED_CERT"
errno: "DEPTH_ZERO_SELF_SIGNED_CERT"
message: "request to https://internal.url/api/v3/user failed, reason: self signed certificate"
name: "L"
stack: "Error↵
    at ClientRequest.<anonymous> (/webpack:/app/~/node-fetch/index.js:133:1)↵    at emitOne (events.js:96:13)↵
    at ClientRequest.emit (events.js:188:7)↵    at TLSSocket.socketErrorListener (_http_client.js:309:9)↵
    at emitOne (events.js:96:13)↵
    at TLSSocket.emit (events.js:188:7)↵
    at emitErrorNT (net.js:1281:8)↵
    at _combinedTickCallback (internal/process/next_tick.js:74:11)↵
    at process._tickCallback (internal/process/next_tick.js:98:9)"
type: "system"
__proto__: Error
```

**Console Logs**
```
3004	default	15:07:13.106621 -0400	GitHub Desktop Helper	GVA info: preferred scaler idx 0
2999	default	15:07:14.009224 -0400	GitHub Desktop	Faulting in NSHTTPCookieStorage singleton
2999	default	15:07:14.009256 -0400	GitHub Desktop	Faulting in CFHTTPCookieStorage singleton
2999	default	15:07:14.009285 -0400	GitHub Desktop	Creating default cookie storage with process/bundle identifier
2999	default	15:07:14.016062 -0400	GitHub Desktop	0x61000026e100 opened /var/folders/gf/1fvbhl2x1xnfl92mc14_hgd9xr5vdf/C//mds/mdsObject.db: 4636 bytes
2999	default	15:07:14.016573 -0400	GitHub Desktop	0x61800046bc80 opened /var/folders/gf/1fvbhl2x1xnfl92mc14_hgd9xr5vdf/C//mds/mdsDirectory.db: 50744 bytes
2999	default	15:07:14.019047 -0400	GitHub Desktop	0x60000026f880 opened /var/folders/gf/1fvbhl2x1xnfl92mc14_hgd9xr5vdf/C//mds/mdsDirectory.db: 50744 bytes
2999	default	15:07:14.021129 -0400	GitHub Desktop	0x610000270a00 opened /Users/_username_/Library/Keychains/login.keychain-db: 132584 bytes
2999	default	15:07:14.024621 -0400	GitHub Desktop	0x600000271b80 opened /Library/Keychains/System.keychain: 81652 bytes
2999	default	15:07:14.029796 -0400	GitHub Desktop	TIC TCP Conn Start [1:0x61000038e2b0]
2999	default	15:07:14.058045 -0400	GitHub Desktop	TIC TCP Conn Event [1:0x61000038e2b0]: 1 Err(0)
2999	default	15:07:14.058069 -0400	GitHub Desktop	TIC TCP Conn Connected [1:0x61000038e2b0]: Err(0)
2999	default	15:07:14.058252 -0400	GitHub Desktop	TIC Enabling TLS [1:0x61000038e2b0]
2999	default	15:07:14.069121 -0400	GitHub Desktop	TIC TLS Event [1:0x61000038e2b0]: 2, Pending(0)
2999	default	15:07:14.069409 -0400	GitHub Desktop	TIC TLS Event [1:0x61000038e2b0]: 11, Pending(0)
2999	default	15:07:14.070235 -0400	GitHub Desktop	TIC TLS Event [1:0x61000038e2b0]: 12, Pending(0)
2999	default	15:07:14.070322 -0400	GitHub Desktop	TIC TLS Event [1:0x61000038e2b0]: 14, Pending(0)
2999	default	15:07:14.094414 -0400	GitHub Desktop	TIC TLS Trust Result [1:0x61000038e2b0]: 0
2999	default	15:07:14.105073 -0400	GitHub Desktop	TIC TLS Event [1:0x61000038e2b0]: 20, Pending(0)
2999	default	15:07:14.106179 -0400	GitHub Desktop	TIC TCP Conn Event [1:0x61000038e2b0]: 8 Err(0)
2999	default	15:07:14.106210 -0400	GitHub Desktop	TIC TLS Handshake Complete [1:0x61000038e2b0]
2999	default	15:07:38.202336 -0400	GitHub Desktop	0x608000275f40 opened /var/folders/gf/1fvbhl2x1xnfl92mc14_hgd9xr5vdf/C//mds/mdsObject.db: 4636 bytes
2999	default	15:07:38.202639 -0400	GitHub Desktop	0x60800026c080 opened /var/folders/gf/1fvbhl2x1xnfl92mc14_hgd9xr5vdf/C//mds/mdsDirectory.db: 50744 bytes
2999	default	15:07:38.204369 -0400	GitHub Desktop	0x608000278740 opened /System/Library/Keychains/SystemRootCertificates.keychain: 385940 bytes
2999	default	15:07:38.210222 -0400	GitHub Desktop	Invalid serial number length (21), must be 1..20
2999	default	15:07:45.097087 -0400	GitHub Desktop	TIC TCP Conn Cancel [1:0x61000038e2b0]
```

#### Additional Information

The self-signed cert is trusted on the machine and is in the keychain.

I tried deleting the cert from the keychain and redoing the login process but was not notified to "Trust" the certificate from the Github Client

One user was able to log in after bypassing the initial setup/login screen, but others have not had the same luck.

Maybe this is a case of PEBCAK, but I'm not sure where to begin resolving this issue.

Could this perhaps be a system configuration issue somewhere? One of our users was able to log in with the same process. Not sure what is going on

**Comment by joshaber** [comment]
Thanks for opening this @tintinn!

Would you be able to send us the certificate?

**Comment by thojansen** [comment]
We get an "unable to get local issuer certificate" at SAP. And this seems to be a new issue as this was working fine before.

**Comment by shiftkey** [comment]
> And this seems to be a new issue as this was working fine before.

When you say "before", is this referring to the classic Mac and Windows apps? Or was there a build of the Electron app that worked previously?

**Comment by tintinn** [comment]
@joshaber the cert is one that is automatically generated by Github Enterprise. It contains internal IP information as well as the internal URL. I'm not too comfortable with attaching it publicly.

Is there any specific information on the cert that you're looking for?

Some addition information is that the only user that has had luck with the 0.5.9 originally logged in with 0.5.7 or 0.5.8.

**Comment by joshaber** [comment]
>the cert is one that is automatically generated by Github Enterprise. It contains internal IP information as well as the internal URL. I'm not too comfortable with attaching it publicly.

Yeah, that's certainly understandable 👍 

>Is there any specific information on the cert that you're looking for?

Unfortunately I'm not terribly sure. I don't know what a "DEPTH_ZERO_SELF_SIGNED_CERT" is or how it should be handled 🤔

**Comment by tintinn** [comment]
Thanks for the responses, but I was able to get a legitimate certificate yesterday and installed it. The valid cert works fine, so I suppose you can close this issue until another person brings it up. So, I'm not sure what was going on with the self-signed certificate 🤔 

Sorry I couldn't be of more help as this is not my area of expertise  

And I believe [DEPTH_ZERO](http://gagravarr.org/writing/openssl-certs/errors.shtml) is referring to the the fact that in attempting to verify the cert it reached the end of the chain and found a self-signed certificate.

**Comment by tintinn** [comment]
@thojansen i had this issue with a certificate signed by an intermediate root authority. I didn't chain the intermediate certificate along with the SSL certificate installed on the GitHub Enterprise server and got this error. IIRC.

If you did chain your certificate, make sure you actually chained the correct one.

**Comment by thojansen** [comment]
thanks, we will look into that
