### ISSUE TITLE
Cannot fetch, clone, push... to private repo on GitLab with SSH

### ISSUE THREAD

**Issue by thucne** [desktop/desktop#18995]
### The problem

I cannot do any action on GitHub desktop recently to a private repo on GitLab, enough it works before. I tried to clone the repo again, and it took forever.

### Release version

3.4.2

### Operating system

Windows

**Comment by steveward** [comment]
Thanks for the report @thucne. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Bogeyx** [comment]
Same problem here. Basically can do everything, but some actions (push/pull/?) take ages. 3-10min for a single file push (took 4 sec in older versions or by using cmd).
The log doesnt show anything, just:
`2024-07-22T14:23:58.636Z - info: [ui] credential-helper: found generic credential for https://*myserver*/
2024-07-22T14:23:58.812Z - info: [ui] Executing push: git push origin master:master --progress (took 122.729s)
2024-07-22T14:24:01.036Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 4.825s)
`

However the dev console log spams:
`isGitHubHost: failed with endpoint https://*myserver*/api/v3
Error: signal is aborted without reason
    at file:///C:/Users/***/AppData/Local/GitHubDesktop/app-3.4.2/resources/app/renderer.js:2:2356810`
    
And once in the end:
`isGitHubHost: failed with endpoint https://*myserver*/api/v3
TypeError: Failed to fetch
    at C:\Users\***\AppData\Local\GitHubDesktop\app-3.4.2\webpack:\app\src\lib\api.ts:2278:28
    at sU (C:\Users\***\AppData\Local\GitHubDesktop\app-3.4.2\webpack:\app\src\lib\trampoline\trampoline-credential-helper.ts:168:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at oU (C:\Users\***\AppData\Local\GitHubDesktop\app-3.4.2\webpack:\app\src\lib\trampoline\trampoline-credential-helper.ts:101:9)
    at C:\Users\***\AppData\Local\GitHubDesktop\app-3.4.2\webpack:\app\src\lib\trampoline\trampoline-credential-helper.ts:232:13
    at Object.processCommand (C:\Users\***\AppData\Local\GitHubDesktop\app-3.4.2\webpack:\app\src\lib\trampoline\trampoline-server.ts:174:11)`

**Comment by thucne** [comment]
2024-07-23T02:45:50.285Z - info: [main] Using toast activator CLSID {this-info-is-removed}
2024-07-23T02:45:51.042Z - info: [ui] [AppStore] loading 13 repositories from store
2024-07-23T02:45:51.042Z - info: [ui] [AppStore] found account: thucne (Tran Trong Thuc)
2024-07-23T02:45:51.201Z - info: [ui] launching: 3.4.2 (Windows 10.0.22631)
2024-07-23T02:45:51.203Z - info: [ui] execPath: 'C:\Users\tthuc\AppData\Local\GitHubDesktop\app-3.4.2\GitHubDesktop.exe'
2024-07-23T02:45:52.635Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.046s)
2024-07-23T02:45:52.692Z - info: [ui] Stats reported.
2024-07-23T02:45:52.760Z - info: [ui] Subscribed 'thucne' to Alive channel
2024-07-23T02:46:33.989Z - info: [ui] Executing checkoutBranch: git checkout --progress master --recurse-submodules -- (took 1.008s)
2024-07-23T02:46:35.146Z - info: [ui] [Timing] Action 'checkout branch from list' for 'frontend' took 2.167s
2024-07-23T02:46:52.148Z - info: [ui] Executing getCommits: git log _this-log-id-is-altered_ --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.016s)
2024-07-23T02:46:57.613Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 21.905s)
2024-07-23T02:46:57.615Z - error: [ui] `git fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
ssh: connect to host _{this-domain-is-altered}_.private port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-07-23T02:49:55.734Z - info: [ui] [Timing] Action 'checkout branch from list' for 'frontend' took 1.442s
2024-07-23T02:52:12.393Z - info: [ui] [Timing] Action 'create branch' for 'frontend' took 0.382s
2024-07-23T02:52:16.460Z - info: [ui] [Timing] Action 'stash and checkout' for 'frontend' took 1.141s
2024-07-23T02:53:12.402Z - info: [ui] Executing createCommit: git commit -F - (took 7.240s)
2024-07-23T02:53:12.696Z - info: [ui] [Timing] Action 'create commit' for 'frontend' took 7.719s
2024-07-23T03:00:17.502Z - info: [main] Using toast activator CLSID {this-info-is-removed}
2024-07-23T03:00:18.611Z - info: [ui] [AppStore] loading 13 repositories from store
2024-07-23T03:00:18.612Z - info: [ui] [AppStore] found account: thucne (Tran Trong Thuc)
2024-07-23T03:00:18.969Z - info: [ui] launching: 3.4.2 (Windows 10.0.22631)
2024-07-23T03:00:18.971Z - info: [ui] execPath: 'C:\Users\tthuc\AppData\Local\GitHubDesktop\app-3.4.2\GitHubDesktop.exe'
2024-07-23T03:00:20.093Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.123s)
2024-07-23T03:00:20.420Z - info: [ui] Subscribed 'thucne' to Alive channel
2024-07-23T03:05:33.448Z - info: [main] Using toast activator CLSID {this-info-is-removed}
2024-07-23T03:05:34.176Z - info: [ui] [AppStore] loading 13 repositories from store
2024-07-23T03:05:34.176Z - info: [ui] [AppStore] found account: thucne (Tran Trong Thuc)
2024-07-23T03:05:34.462Z - info: [ui] launching: 3.4.2 (Windows 10.0.22631)
2024-07-23T03:05:34.464Z - info: [ui] execPath: 'C:\Users\tthuc\AppData\Local\GitHubDesktop\app-3.4.2\GitHubDesktop.exe'
2024-07-23T03:05:35.556Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.093s)
2024-07-23T03:05:36.280Z - info: [ui] Subscribed 'thucne' to Alive channel

Hello @steveward, this is the log, I'm using GitHub desktop for a private repo on GitLab using SSH connection. It used to work before, but now the actions take forever.

**Comment by steveward** [comment]
@thucne thanks for the log. In this case it just looks like the connection is timing out. Does pushing via the command line using SSH work without issue? Can you also check to see what you have selected under `File` > `Options` > `Advanced` > `Use system openSSH`?

**Comment by thucne** [comment]
Hello @steveward, it works normally with command line (of course I have to type in the SSH password)

Yes, I use the system OpenSSH
![image](https://github.com/user-attachments/assets/520a6ced-fcb2-450b-a808-cecdf6ab1726)

**Comment by steveward** [comment]
Can you try unchecking `Use system OpenSSH` to see if that gets things working?

**Comment by thucne** [comment]
Yes, it works again! Thank you @steveward !!

**Comment by steveward** [comment]
I'm glad to hear that got things working!
