### ISSUE TITLE
I can not push my work

### ISSUE THREAD

**Issue by josshare** [desktop/desktop#19024]
### The problem

<img width="951" alt="Screenshot 2024-07-26 at 8 32 37 p m" src="https://github.com/user-attachments/assets/4cc53f68-e8f5-46c2-986b-833f89345d10">

### Release version

Version 3.4.2 (arm64)

### Operating system

Mac

### Steps to reproduce the behavior

file > add local repository > select files
<img width="951" alt="Screenshot 2024-07-26 at 8 32 37 p m" src="https://github.com/user-attachments/assets/61d41e89-b257-4acf-a9b5-d901f809f01f">

### Log files

2024-07-27T01:40:28.831Z - info: [main] Processing protocol url
2024-07-27T01:40:29.031Z - info: [ui] [AppStore] loading 4 repositories from store
2024-07-27T01:40:29.031Z - info: [ui] [AppStore] found account: josshare (josshare)
2024-07-27T01:40:29.395Z - info: [ui] launching: 3.4.2 (Mac OS 14.5.0)
2024-07-27T01:40:29.395Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2024-07-27T01:40:29.715Z - info: [ui] Subscribed 'josshare' to Alive channel
2024-07-27T01:40:29.866Z - info: [ui] Stats reported.
2024-07-27T01:40:34.607Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T01:40:34.958Z - info: [ui] [AppStore] adding repository at /Users/jmm/code/website/Tarea to store
2024-07-27T01:40:34.974Z - info: [ui] [BranchPruner] Last prune took place 6 seconds ago - skipping
2024-07-27T01:40:35.329Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T01:40:36.084Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T01:45:53.812Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T01:45:54.557Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T01:51:14.904Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T01:51:15.680Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T01:56:35.879Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T01:56:36.632Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:01:56.878Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:01:57.599Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:04:59.786Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:05:00.642Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:05:01.955Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:05:02.893Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:05:03.260Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 5.3s of which 0.0s paused, total 5.3s
2024-07-27T02:06:30.208Z - info: [ui] [AppStore] adding repository at /Users/jmm/IdeaProjects/Tarea/src to store
2024-07-27T02:06:38.266Z - error: [ui] `git push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-07-27T02:09:44.861Z - info: [ui] [SignInStore] initializing OAuth flow
2024-07-27T02:09:44.866Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=8c815e98-c4c5-4071-a3b8-f1a6482f73c3
2024-07-27T02:09:44.867Z - info: [ui] [SignInStore] account resolved
2024-07-27T02:09:49.351Z - info: [main] Processing protocol url
2024-07-27T02:09:50.009Z - warn: [ui] fetchAccount: failed with endpoint https://github.com/api/v3
Error: API error https://github.com/api/v3/user:  (404)
    at cn (/webpack:/app/src/lib/http.ts:178:11)
    at Yn.fetchAccount (/webpack:/app/src/lib/api.ts:1040:7)
    at Qn (/webpack:/app/src/lib/api.ts:2040:11)
    at Fp.resolveOAuthRequest (/webpack:/app/src/lib/stores/sign-in-store.ts:570:13)
    at Object.dispatchURLAction (/webpack:/app/src/ui/dispatcher/dispatcher.ts:1872:12)
2024-07-27T02:09:50.010Z - warn: [ui] fetchUser: failed with endpoint https://github.com/api/v3
Error: API error https://github.com/api/v3/user:  (404)
    at cn (/webpack:/app/src/lib/http.ts:178:11)
    at Yn.fetchAccount (/webpack:/app/src/lib/api.ts:1040:7)
    at Qn (/webpack:/app/src/lib/api.ts:2040:11)
    at Fp.resolveOAuthRequest (/webpack:/app/src/lib/stores/sign-in-store.ts:570:13)
    at Object.dispatchURLAction (/webpack:/app/src/ui/dispatcher/dispatcher.ts:1872:12)
2024-07-27T02:09:54.410Z - info: [ui] [SignInStore] initializing OAuth flow
2024-07-27T02:09:54.425Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=f38a258b-ae1d-4fe4-b2d0-8a257b15a50c
2024-07-27T02:09:54.426Z - info: [ui] [SignInStore] account resolved
2024-07-27T02:09:58.349Z - info: [main] Processing protocol url
2024-07-27T02:09:58.931Z - warn: [ui] fetchAccount: failed with endpoint https://github.com/api/v3
Error: API error https://github.com/api/v3/user:  (404)
    at cn (/webpack:/app/src/lib/http.ts:178:11)
    at Yn.fetchAccount (/webpack:/app/src/lib/api.ts:1040:7)
    at Qn (/webpack:/app/src/lib/api.ts:2040:11)
    at Fp.resolveOAuthRequest (/webpack:/app/src/lib/stores/sign-in-store.ts:570:13)
    at Object.dispatchURLAction (/webpack:/app/src/ui/dispatcher/dispatcher.ts:1872:12)
2024-07-27T02:09:58.931Z - warn: [ui] fetchUser: failed with endpoint https://github.com/api/v3
Error: API error https://github.com/api/v3/user:  (404)
    at cn (/webpack:/app/src/lib/http.ts:178:11)
    at Yn.fetchAccount (/webpack:/app/src/lib/api.ts:1040:7)
    at Qn (/webpack:/app/src/lib/api.ts:2040:11)
    at Fp.resolveOAuthRequest (/webpack:/app/src/lib/stores/sign-in-store.ts:570:13)
    at Object.dispatchURLAction (/webpack:/app/src/ui/dispatcher/dispatcher.ts:1872:12)
2024-07-27T02:10:08.206Z - info: [ui] [SignInStore] OAuth error but session has changed: Error: cancelled
2024-07-27T02:10:11.421Z - error: [ui] `git push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-07-27T02:10:39.843Z - info: [ui] [AppStore] removing account josshare (josshare) from store
2024-07-27T02:10:39.873Z - info: [ui] Unubscribed 'josshare' from Alive channel
2024-07-27T02:10:42.877Z - info: [ui] [SignInStore] initializing OAuth flow
2024-07-27T02:10:42.880Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=c83ff148-23a1-4c9a-a90e-14067f8a2f35
2024-07-27T02:10:42.880Z - info: [ui] [SignInStore] account resolved
2024-07-27T02:10:47.828Z - info: [main] Processing protocol url
2024-07-27T02:10:49.033Z - info: [ui] [AppStore] adding account josshare (josshare) to store
2024-07-27T02:10:49.495Z - info: [ui] Subscribed 'josshare' to Alive channel
2024-07-27T02:10:52.002Z - error: [ui] `git push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-07-27T02:12:22.613Z - error: [ui] `git push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-07-27T02:14:05.236Z - error: [ui] `git push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-07-27T02:22:08.885Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:22:09.575Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:22:10.276Z - error: [ui] `git push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-07-27T02:22:11.943Z - error: [ui] `git fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-07-27T02:22:11.944Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 6 repositories took 4.8s of which 0.0s paused, total 4.8s
2024-07-27T02:22:25.121Z - error: [ui] `git push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-07-27T02:22:28.114Z - info: [ui] [AppStore] removing account josshare (josshare) from store
2024-07-27T02:22:28.137Z - info: [ui] Unubscribed 'josshare' from Alive channel
2024-07-27T02:22:30.969Z - info: [ui] [SignInStore] initializing OAuth flow
2024-07-27T02:22:30.971Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=0862aa96-00d1-40ac-b702-da0f4f1eb5a8
2024-07-27T02:22:30.971Z - info: [ui] [SignInStore] account resolved
2024-07-27T02:22:36.537Z - info: [main] Processing protocol url
2024-07-27T02:22:37.599Z - info: [ui] [AppStore] adding account josshare (josshare) to store
2024-07-27T02:22:37.970Z - info: [ui] Subscribed 'josshare' to Alive channel
2024-07-27T02:22:44.863Z - error: [ui] `git push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-07-27T02:23:05.234Z - info: [ui] [AppStore] adding repository at /Users/jmm/IdeaProjects/Tarea/src to store
2024-07-27T02:23:17.381Z - error: [ui] `git push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-07-27T02:24:06.367Z - info: [ui] [AppStore] loading 6 repositories from store
2024-07-27T02:24:06.372Z - info: [ui] [AppStore] found account: josshare (josshare)
2024-07-27T02:24:06.719Z - info: [ui] launching: 3.4.2 (Mac OS 14.5.0)
2024-07-27T02:24:06.720Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2024-07-27T02:24:06.943Z - info: [ui] Subscribed 'josshare' to Alive channel
2024-07-27T02:24:16.145Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:24:16.849Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:24:17.999Z - error: [ui] `git push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-07-27T02:24:18.371Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 5 repositories took 3.6s of which 0.0s paused, total 3.6s
2024-07-27T02:29:02.566Z - info: [ui] [BranchPruner] Last prune took place 1 hour ago - skipping
2024-07-27T02:29:03.067Z - info: [ui] [BranchPruner] Last prune took place 1 hour ago - skipping
2024-07-27T02:29:11.143Z - info: [ui] [BranchPruner] Last prune took place 1 hour ago - skipping
2024-07-27T02:29:11.561Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:29:12.324Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:29:13.549Z - info: [ui] [BranchPruner] Last prune took place 1 hour ago - skipping
2024-07-27T02:29:41.838Z - info: [main] opening in browser: https://github.com/josshare/Tarea/issues/new/choose
2024-07-27T02:30:48.377Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:30:48.746Z - info: [ui] [AppStore] adding repository at /Users/jmm/code/website/Tarea_uvm to store
2024-07-27T02:30:48.758Z - info: [ui] [BranchPruner] Last prune took place 1 hour ago - skipping
2024-07-27T02:30:52.093Z - info: [ui] [BranchPruner] Last prune took place 1 hour ago - skipping
2024-07-27T02:30:55.691Z - info: [ui] [BranchPruner] Last prune took place 7 seconds ago - skipping
2024-07-27T02:30:56.083Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:30:56.835Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-07-27T02:31:12.027Z - info: [ui] [AppStore] adding repository at /Users/jmm/IdeaProjects/Tarea/src to store
2024-07-27T02:31:16.563Z - error: [ui] `git push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)

### Screenshots

<img width="951" alt="Screenshot 2024-07-26 at 8 32 37 p m" src="https://github.com/user-attachments/assets/12d7023a-522e-434b-84db-1c72665e5623">

### Additional context

same in intelij

**Comment by sergiou87** [comment]
It seems you cloned your repository using SSH. Could you try cloning it with HTTPS and see if that works?

**Comment by josshare** [comment]
correct I was using git@github.com: instead of https://github.com/ thank you!

**Comment by josshare** [comment]
correct I was using git@github.com: instead of https://github.com/ thank you!
