### ISSUE TITLE
The application “GitHub Desktop.app” can’t be opened.

### ISSUE THREAD

**Issue by mohijalili** [desktop/desktop#19050]
### The problem

I've installed GitHub Desktop a few times, but after a while (not sure exactly how long), it stopped working. I can't open it and get an error saying, "can't be opened." I don't think I can access the log since the app won't open.

### Release version

N/A (probably the latest)

### Operating system

macOS Sonoma

### Steps to reproduce the behavior

N/A

### Log files

N/A

### Screenshots

![image](https://github.com/user-attachments/assets/d9a48a3a-2dfc-4178-902b-6dfb5b6ad69e)

**Comment by sergiou87** [comment]
Could you try following these steps?

1. Quitting GitHub Desktop and restarting your machine to ensure no rogue processes are hanging about
1. Uninstalling GitHub Desktop
1. Deleting (or moving/renaming temporarily) the `~/Library/Application Support/GitHub Desktop/` folder. This folder has all your GitHub Desktop settings and the list of repositories.
1. Downloading and installing GitHub Desktop again from https://desktop.github.com

**Comment by mohijalili** [comment]
@sergiou87 Thanks for the tips. I’ve tried this before, but I keep running into the same issue. Also, I've been collecting this info for a while, so I'll probably need to check back with you in a month.

Here's my latest log from today:

```
2024-08-01T07:28:19.853Z - error: [ui] Error performing periodic fetch for '******'
Error: Git could not be found at the expected path: '/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:289454
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:518:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-08-01T07:28:19.857Z - warn: [ui] getFetchPollInterval: failed for ****** 
TypeError: Failed to fetch
    at ln (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:701976)
    at Yn.request (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:716228)
    at Yn.getFetchPollInterval (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:716549)
    at mv.getFetchInterval (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:1198358)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at mv.performAndScheduleFetch (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:1198089)
2024-08-01T08:28:20.882Z - error: [ui] Error performing periodic fetch for '******'
Error: Git could not be found at the expected path: '/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:289454
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:518:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-08-01T08:33:21.881Z - error: [ui] Error performing periodic fetch for '******'
Error: Git could not be found at the expected path: '/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:289454
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:518:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-08-01T08:38:22.884Z - error: [ui] Error performing periodic fetch for '******'
Error: Git could not be found at the expected path: '/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:289454
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:518:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-08-01T08:43:23.898Z - error: [ui] Error performing periodic fetch for '******'
Error: Git could not be found at the expected path: '/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:289454
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:518:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-08-01T08:48:24.885Z - error: [ui] Error performing periodic fetch for '******'
Error: Git could not be found at the expected path: '/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:289454
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:518:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-08-01T08:53:25.893Z - error: [ui] Error performing periodic fetch for '******'
Error: Git could not be found at the expected path: '/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:289454
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:518:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-08-01T08:58:26.896Z - error: [ui] Error performing periodic fetch for '******'
Error: Git could not be found at the expected path: '/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:289454
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:518:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-08-01T09:03:27.893Z - error: [ui] Error performing periodic fetch for '******'
Error: Git could not be found at the expected path: '/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:2:289454
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:

```

**Comment by sergiou87** [comment]
Ouch! Those errors are bad indeed 😱 

Have you checked if `/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git` exists or not? If it does not… does your machine have an antivirus or is it managed by your organization? Maybe an antivirus or your organization configuration is removing important files of Desktop for whatever reason 🤔

**Comment by mohijalili** [comment]
Dear @sergiou87, Unfortunately, I removed the app again, as you mentioned earlier. I'm not entirely sure if the files were there or not. To answer your question, yes, it is managed by the organisation and I never used any antivirus, but I don't think they removed it at all.

I renamed this folder ~/Library/Application Support/GitHub Desktop/. If anything here can be of help, please inform me.

**Comment by sergiou87** [comment]
It seems like _something_ in your machine is deleting those files, since they definitely are included in the app bundle we distribute 😕 

If you can install the app again, and see if the mentioned files exist right after installing it and then check if they get removed after a while, we can confirm _something_ is deleting them.

In any case I'd suggest you talk to the admin of your organization and ask them, they will probably know better.

Since I don't think this is an issue with Desktop itself, I will close the issue. I'll be happy to reopen it if that's not the case though!

Thanks for your patience 🙏

**Comment by dunnkers** [comment]
> * Deleting (or moving/renaming temporarily) the `~/Library/Application Support/GitHub Desktop/` folder. This folder has all your GitHub Desktop settings and the list of repositories.

running:

```
sudo rm -rf ~/Library/Application Support/GitHub Desktop/
```

... worked for me.

Thanks @sergiou87 🙌🏻
