### ISSUE TITLE
Can't sign in with GitHub Desktop - error with OAuth 

### ISSUE THREAD

**Issue by expdal3** [desktop/desktop#19085]
### The problem

I'm unable to sign in with my GitHub desktop - the log mention error with OAuth token

2024-08-10T08:51:52.855Z - info: [ui] [SignInStore] error with OAuth flow
Error: Failed retrieving authenticated user
    at Gp.resolveOAuthRequest (C:\Users\ducan\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\sign-in-store.ts:574:9)
    at Object.dispatchURLAction (C:\Users\ducan\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\ui\dispatcher\dispatcher.ts:1873:12)
2024-08-10T08:52:07.439Z - info: [main] Received possible protocol arguments: 4
2024-08-10T08:52:07.442Z - info: [main] Processing protocol url
2024-08-10T08:52:07.443Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"x-github-desktop-auth://oauth?code=0216b365a03c3015134b"}
2024-08-10T08:52:33.331Z - info: [main] Received possible protocol arguments: 4
2024-08-10T08:52:33.332Z - error: [main] Malformed launch arguments received: C:\Users\ducan\AppData\Local\GithubDesktop\app-3.4.3\GitHubDesktop.exe,--protocol-launcher,--allow-file-access-from-files,%1
2024-08-10T08:52:44.019Z - info: [main] Received possible protocol arguments: 4
2024-08-10T08:52:44.022Z - info: [main] Processing protocol url
2024-08-10T08:52:44.145Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com

### Release version

Version 3.4.3 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1 On Github desktop go to Option >> Accounts
2 Click "Sign into Github.com
3 Click "Continue with browser"
4 Sign in to Github in browser
5. the browser redirect me back to Desktop interface which is now display the error "Failed retrieving authenticated user"

![image](https://github.com/user-attachments/assets/9cfec970-1736-4180-977a-f2dd9900c178)

### Log files

2024-08-10T08:51:52.855Z - info: [ui] [SignInStore] error with OAuth flow
Error: Failed retrieving authenticated user
    at Gp.resolveOAuthRequest (C:\Users\ducan\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\sign-in-store.ts:574:9)
    at Object.dispatchURLAction (C:\Users\ducan\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\ui\dispatcher\dispatcher.ts:1873:12)
2024-08-10T08:52:07.439Z - info: [main] Received possible protocol arguments: 4
2024-08-10T08:52:07.442Z - info: [main] Processing protocol url
2024-08-10T08:52:07.443Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"x-github-desktop-auth://oauth?code=0216b365a03c3015134b"}
2024-08-10T08:52:33.331Z - info: [main] Received possible protocol arguments: 4
2024-08-10T08:52:33.332Z - error: [main] Malformed launch arguments received: C:\Users\ducan\AppData\Local\GithubDesktop\app-3.4.3\GitHubDesktop.exe,--protocol-launcher,--allow-file-access-from-files,%1
2024-08-10T08:52:44.019Z - info: [main] Received possible protocol arguments: 4
2024-08-10T08:52:44.022Z - info: [main] Processing protocol url
2024-08-10T08:52:44.145Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
    at yn (C:\Users\ducan\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\http.ts:152:10)
    at C:\Users\ducan\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\api.ts:2191:28
    at Gp.resolveOAuthRequest (C:\Users\ducan\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\sign-in-store.ts:567:25)
    at Gp._resolveOAuthRequest (C:\Users\ducan\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\app-store.ts:5795:29)
    at Object.dispatchURLAction (C:\Users\ducan\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\ui\dispatcher\dispatcher.ts:1874:29)
    at IpcRenderer.<anonymous> (C:\Users\ducan\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\ui\index.tsx:351:14)
    at IpcRenderer.emit (node:events:518:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:8837)
2024-08-10T08:52:53.725Z - info: [main] Received possible protocol arguments: 4
2024-08-10T08:52:53.729Z - info: [main] Processing protocol url
2024-08-10T08:52:53.832Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
[2024-08-10.desktop.production.log](https://github.com/user-attachments/files/16569034/2024-08-10.desktop.production.log)

### Screenshots

![image](https://github.com/user-attachments/assets/73c03085-1b14-4eb2-8e6c-b5217d3af0db)

**Comment by steveward** [comment]
Thanks for the issue. Are you running any antivirus or security software that could be interfering with authentication? Most of the cases we've seen have been caused by this.

**Comment by expdal3** [comment]
Ah yes I do have Karpersky anti virus run

How it can be fixed?

**Comment by steveward** [comment]
Are you running Kaspersky Internet Security? That was the cause of this issue for [another user](https://github.com/desktop/desktop/issues/16901#issuecomment-1597068643) of GitHub Desktop who was running Kaspersky. 

If you're not running that version of Kaspersky I would recommend looking at this documentation to see if you can prevent GitHub Desktop from being scanned:

https://support.kaspersky.com/KESWin/11/en-US/165718.htm
