### ISSUE TITLE
Not able to install in my Desktop #Windows 8-64 bit

### ISSUE THREAD

**Issue by AlwinJCOde667** [desktop/desktop#19124]
Tried using the .net framework repair tool,but there is no difference,it is still showing Github installation error.
2020-06-08 09:39:55> Program: Starting Squirrel Updater: --install . --exeName=Teams_windows_x64.exe
2020-06-08 09:39:56> Program: setup.json does not exist
2020-06-08 09:39:56> Program: Starting install, writing to C:\Users\Alan Paul\AppData\Local\SquirrelTemp
2020-06-08 09:39:56> Program: File does not contain contextual info: Teams_windows_x64.exe
2020-06-08 09:39:56> UpdateManager: using rootAppDirectory: C:\Users\Alan Paul\AppData\Local\Microsoft\Teams
2020-06-08 09:39:56> Program: About to install to: C:\Users\Alan Paul\AppData\Local\Microsoft\Teams
2020-06-08 09:39:56> Program: Setup.json exist, copying over
2020-06-08 09:39:56> RegistryService: RegKeyExists: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run does not have TeamsMachineInstaller
2020-06-08 09:39:56> Program: CheckMsiAndTryAddInstallSource: Not MSI, no need to add HKEY_CURRENT_USER\Software\Microsoft\Office\Teams\InstallSource
2020-06-08 09:39:56> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Alan Paul\AppData\Local\Microsoft\Teams\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2020-06-08 09:39:56> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Alan Paul\AppData\Local\Microsoft\Teams\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2020-06-08 09:39:56> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Alan Paul\AppData\Local\SquirrelTemp
2020-06-08 09:39:56> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2020-06-08 09:39:56> ApplyReleasesImpl: No delta packages found. Applying current release package.
2020-06-08 09:39:56> ApplyReleasesImpl: getting squirrel aware apps failed with exception Could not find a part of the path 'C:\Users\Alan Paul\AppData\Local\Microsoft\Teams\current'.
2020-06-08 09:39:56> ApplyReleasesImpl: Writing files to app directory: C:\Users\Alan Paul\AppData\Local\Microsoft\Teams\current
2020-06-08 09:40:40> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Alan Paul\AppData\Local\Microsoft\Teams\current\Teams.exe]
2020-06-08 09:40:57> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\Alan Paul\AppData\Local\Microsoft\Teams\current\Teams.exe: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClass11_0.<InvokeProcessAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass18_1.<<invokePostInstall>b__2>d.MoveNext()
2020-06-08 09:40:57> ApplyReleasesImpl: About to RemoveOldShorcuts for Teams.exe, rootAppDir C:\Users\Alan Paul\AppData\Local\Microsoft\Teams
2020-06-08 09:40:57> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Cloud\Office\16.0\Teams does not exist
2020-06-08 09:40:57> ApplyReleasesImpl: Registry value Software\Policies\Microsoft\Cloud\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2020-06-08 09:40:57> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\Teams does not exist
2020-06-08 09:40:57> ApplyReleasesImpl: Registry value Software\Policies\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2020-06-08 09:40:57> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Teams does not exist
2020-06-08 09:40:57> ApplyReleasesImpl: Registry value Software\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2020-06-08 09:40:57> ApplyReleasesImpl: Registry flags are not set: proceed with default value NotConfigured
2020-06-08 09:40:58> ApplyReleasesImpl: Starting fixPinnedExecutables
2020-06-08 09:40:58> ApplyReleasesImpl: Examining Pin: Excel 2016.lnk
2020-06-08 09:40:58> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2020-06-08 09:41:01> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2020-06-08 09:41:01> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2020-06-08 09:41:01> ApplyReleasesImpl: Examining Pin: OneNote 2016.lnk
2020-06-08 09:41:01> ApplyReleasesImpl: Examining Pin: Outlook 2016.lnk

Please kindly help me to resolve this issue ASAP,
Thank you

**Comment by sergiou87** [comment]
Hello @AlwinJCOde667 👋 

I'm afraid Windows 8 is not supported anymore: https://docs.github.com/en/desktop/installing-and-authenticating-to-github-desktop/installing-github-desktop

Windows 10 is the minimum Windows version supported. Sorry!
