### ISSUE TITLE
Remote Disconnected Error (not a large file)

### ISSUE THREAD

**Issue by marwaygreg** [desktop/desktop#19174]
GitHub Desktop Version 3.4.3 (x64) : macOS Sonoma 14.6.1

I have a half dozen or so small private repos been using for months. Suddenly a couple have been generating "The remote disconnected...." errors when trying to Push Origin. 

I've read numerous posts about this error. So far every one has been about large files. As far as I can tell, these are small files, small changes. Internet reliability is fine. All other internet functionality is fine. My other repos are fine (same account, same setup configurations). I've logged everything out, relogged in. Even re-cloned one repo and redid the changes as a test. I've been retrying at different times over two days (ruling out short term network blips).

I found the logs other posts referred to, and captured the content below after trying a Push again. ( the repo paths are "--blurred--").

At a loss for what else to look at and try. Any ideas appreciated.

Thanks for your time.

```
2024-08-28T17:53:34.081Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 7 repositories took 2.2s of which 0.0s paused, total 2.2s
2024-08-28T17:53:36.590Z - info: [ui] [BranchPruner] Last prune took place 23 hours ago - skipping
2024-08-28T17:53:36.985Z - info: [ui] [fetchAllRepoRulesets] unable to fetch all repo rulesets | repos/--blurred--/--blurred--/rulesets
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at dn (/webpack:/app/src/lib/http.ts:178:11)
    at er.fetchAllRepoRulesets (/webpack:/app/src/lib/api.ts:1688:7)
    at $p.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:1239:15)
    at $p.repositoryWithRefreshedGitHubRepository (/webpack:/app/src/lib/stores/app-store.ts:4190:5)
2024-08-28T17:53:37.160Z - info: [ui] [fetchRepoRulesForBranch] unable to fetch repo rules for branch: main | repos/--blurred--/--blurred--/rules/branches/main
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at dn (/webpack:/app/src/lib/http.ts:178:11)
    at er.fetchRepoRulesForBranch (/webpack:/app/src/lib/api.ts:1667:7)
    at $p.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:1260:15)
    at $p.repositoryWithRefreshedGitHubRepository (/webpack:/app/src/lib/stores/app-store.ts:4190:5)
2024-08-28T17:53:42.967Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-08-28T17:53:44.220Z - info: [ui] Executing push: git push origin main:main --progress (took 1.573s)
2024-08-28T17:53:44.221Z - error: [ui] `git push origin main:main --progress` exited with an unexpected code: 1.
stderr:
Enumerating objects: 25, done.
Counting objects:   4% (1/25)
Counting objects:   8% (2/25)
Counting objects:  12% (3/25)
Counting objects:  16% (4/25)
Counting objects:  20% (5/25)
Counting objects:  24% (6/25)
Counting objects:  28% (7/25)
Counting objects:  32% (8/25)
Counting objects:  36% (9/25)
Counting objects:  40% (10/25)
Counting objects:  44% (11/25)
Counting objects:  48% (12/25)
Counting objects:  52% (13/25)
Counting objects:  56% (14/25)
Counting objects:  60% (15/25)
Counting objects:  64% (16/25)
Counting objects:  68% (17/25)
Counting objects:  72% (18/25)
Counting objects:  76% (19/25)
Counting objects:  80% (20/25)
Counting objects:  84% (21/25)
Counting objects:  88% (22/25)
Counting objects:  92% (23/25)
Counting objects:  96% (24/25)
Counting objects: 100% (25/25)
Counting objects: 100% (25/25), done.
Delta compression using up to 10 threads
Compressing objects:   5% (1/19)
Compressing objects:  10% (2/19)
Compressing objects:  15% (3/19)
Compressing objects:  21% (4/19)
Compressing objects:  26% (5/19)
Compressing objects:  31% (6/19)
Compressing objects:  36% (7/19)
Compressing objects:  42% (8/19)
Compressing objects:  47% (9/19)
Compressing objects:  52% (10/19)
Compressing objects:  57% (11/19)
Compressing objects:  63% (12/19)
Compressing objects:  68% (13/19)
Compressing objects:  73% (14/19)
Compressing objects:  78% (15/19)
Compressing objects:  84% (16/19)
Compressing objects:  89% (17/19)
Compressing objects:  94% (18/19)
Compressing objects: 100% (19/19)
Compressing objects: 100% (19/19), done.
Writing objects:   5% (1/20)
Writing objects:  10% (2/20)
Writing objects:  15% (3/20)
Writing objects:  20% (4/20)
Writing objects:  25% (5/20)
Writing objects:  30% (6/20)
Writing objects:  35% (7/20)
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
Writing objects:  40% (8/20)
Writing objects:  50% (10/20)
Writing objects:  55% (11/20)
Writing objects:  60% (12/20)
Writing objects:  65% (13/20)
Writing objects:  70% (14/20)
Writing objects:  75% (15/20)
Writing objects:  80% (16/20)
Writing objects:  85% (17/20)
Writing objects:  90% (18/20)
Writing objects:  95% (19/20)
Writing objects: 100% (20/20)
Writing objects: 100% (20/20), 3.70 MiB | 6.94 MiB/s, done.
Total 20 (delta 7), reused 0 (delta 0), pack-reused 0 (from 0)
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 5: The remote disconnected. Check your Internet connection and try again.)
```

A successful push with one of my other repos on the same account looked like this:

```
2024-08-28T18:16:20.163Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-08-28T18:16:20.936Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-08-28T18:16:21.564Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-08-28T18:16:22.123Z - info: [ui] [fetchAllRepoRulesets] unable to fetch all repo rulesets | repos/--blurred--/--blurred--/rulesets
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at dn (/webpack:/app/src/lib/http.ts:178:11)
    at er.fetchAllRepoRulesets (/webpack:/app/src/lib/api.ts:1688:7)
    at $p.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:1239:15)
    at d.performFailableOperation.retryAction (/webpack:/app/src/lib/stores/app-store.ts:4565:45)
    at Fw.performFailableOperation (/webpack:/app/src/lib/stores/git-store.ts:908:7)
    at /webpack:/app/src/lib/stores/app-store.ts:4521:49
    at $p.withPushPullFetch (/webpack:/app/src/lib/stores/app-store.ts:4633:5)
2024-08-28T18:16:22.303Z - info: [ui] [fetchRepoRulesForBranch] unable to fetch repo rules for branch: master | repos/--blurred--/--blurred--/rules/branches/master
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at dn (/webpack:/app/src/lib/http.ts:178:11)
    at er.fetchRepoRulesForBranch (/webpack:/app/src/lib/api.ts:1667:7)
    at $p.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:1260:15)
    at d.performFailableOperation.retryAction (/webpack:/app/src/lib/stores/app-store.ts:4565:45)
    at Fw.performFailableOperation (/webpack:/app/src/lib/stores/git-store.ts:908:7)
    at /webpack:/app/src/lib/stores/app-store.ts:4521:49
    at $p.withPushPullFetch (/webpack:/app/src/lib/stores/app-store.ts:4633:5)
```

**Comment by steveward** [comment]
Thanks for sharing the log file! Here's the error I'm seeing:

```
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
```
You can try using the command line to push a subset of commits by using the following command:

`git push origin commit-SHA:branch`

For example, if you have three commits A (4d3bf9) - B (e55b5f) - C (c109e0) and wanted to push A and B to your `main` branch you would run this command:

`git push origin e55b5f:main`

Some users have had also success running this command to try and prevent timeouts:

`git config --global http.postBuffer 157286400`


There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

If none of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. 

I'm going to close this out since there isn't anything we can do from our end about network timeouts, but let me know if you have any further questions.

**Comment by marwaygreg** [comment]
Many thanks for the quick and detailed ideas.

I started with what seemed the simplest, and this one worked for me. `git config --global http.postBuffer 157286400` Ran that in Terminal, then tried the Desktop Push Origin button again — worked for both problem repos.

**Comment by steveward** [comment]
Glad to hear that got things working!

**Comment by Handfast** [comment]
Thanks a lot for the quick response. As marwaygreg I did the general config change `git config --global http.postBuffer 157286400` And it resolved my problems. 👍

**Comment by ygg2** [comment]
I got this error message too, also on MacOS.

At first, I was going to increase the postBuffer as well, but the FAQ https://git-scm.com/docs/gitfaq#http-postbuffer states that nowadays uploading a file larger than the base 1MB should be fine:

> If the data is larger than this size, libcurl, which handles the HTTP support for Git, will use chunked transfer encoding since it isn’t known ahead of time what the size of the pushed data will be.

Between this and the recent resurgence of this message for small files for Mac users (see also recent comments in https://github.com/desktop/desktop/issues/14936), I believe **there really is an issue somewhere for MacOS and Github Desktop.**

I was able to upload the files by using the command line instead, without changing the buffer size.
