### ISSUE TITLE
SSH KEY PROBLEM 

### ISSUE THREAD

**Issue by zdhix** [desktop/desktop#19222]
NEWBIE HERE ..... so my github desktop suddenly can't sync with my github i think its because i have not made my ssh key yet. When i try to make one i can only see the private key only in my folder the .pub or public key doesn't exist. I try to check on my git bash it seems like it exist. Why can't i find it on my folder? here some steps i do to create the key
 : 
`$ ssh-keygen`

Your identification has been saved in /c/Users/Dhian/.ssh/id_ed25519
Your public key has been saved in /c/Users/Dhian/.ssh/id_ed25519.pub

`$ cat id_ed25519.pub~`
cat: id_ed25519.pub~: No such file or directory
`$ cat ~/ .ssh/id_ed25519.pub`
cat: /c/Users/Dhian/: Is a directory

for additional information i try a couple of method on the internet such as using email and all but the result is still the same : 
`$ ls -al ~/ .ssh`
.ssh:
total 26
drwxr-xr-x 1 Dhian 197609    0 Sep  9 14:38 ./
drwxr-xr-x 1 Dhian 197609    0 Sep  9 13:34 ../
-rw-r--r-- 1 Dhian 197609  444 Sep  9 14:38 id_ed25519
-rw-r--r-- 1 Dhian 197609   93 Sep  9 14:38 id_ed25519.pub
-rw-r--r-- 1 Dhian 197609 2610 Sep  9 13:38 mykey

`$ ls ~/.ssh/id_ed25519*`
/c/Users/Dhian/.ssh/id_ed25519  /c/Users/Dhian/.ssh/id_ed25519.pub

**SEE IT EXIST BUT WHERE ?** _i try searching on my folder none was found_ 
here some tutorial i follow : 
(
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)
(https://www.youtube.com/watch?v=X40b9x9BFGo&t=38s&pp=ygUaaG93IHRvIG1ha2Ugc3NoIGtleSBnaXRodWI%3D)

![image](https://github.com/user-attachments/assets/32af97d6-ce0c-4ed0-a1b9-321a646caae9)

**Comment by steveward** [comment]
@zdhix thanks for the issue. GitHub Desktop defaults to using HTTPS unless you specifically clone using a SSH remote URL. 

Could you upload the log file from GitHub Desktop so that I could get some more information about any errors you're experiencing? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by zdhix** [comment]
here is my log. Please help

2024-09-10T01:34:53.068Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-09-10T01:34:53.951Z - info: [ui] [AppStore] loading 7 repositories from store
2024-09-10T01:34:53.952Z - info: [ui] [AppStore] found account: zdhix (DhianPrameswari)
2024-09-10T01:34:54.621Z - info: [ui] launching: 3.4.3 (Windows 10.0.22631)
2024-09-10T01:34:54.623Z - info: [ui] execPath: 'C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\GitHubDesktop.exe'
2024-09-10T01:34:55.236Z - info: [ui] Subscribed 'zdhix' to Alive channel
2024-09-10T01:34:56.591Z - info: [ui] [fetchAllRepoRulesets] unable to fetch all repo rulesets | repos/zdhix-viscoflow/chatbot-viscoflow/rulesets
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at wn (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\http.ts:178:11)
    at sr.fetchAllRepoRulesets (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\api.ts:1688:7)
    at Gp.refreshBranchProtectionState (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\app-store.ts:1239:15)
    at Gp.repositoryWithRefreshedGitHubRepository (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\app-store.ts:4190:5)
2024-09-10T01:34:56.598Z - info: [ui] Stats reported.
2024-09-10T01:34:56.972Z - info: [ui] [fetchRepoRulesForBranch] unable to fetch repo rules for branch: main | repos/zdhix-viscoflow/chatbot-viscoflow/rules/branches/main
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at wn (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\http.ts:178:11)
    at sr.fetchRepoRulesForBranch (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\api.ts:1667:7)
    at Gp.refreshBranchProtectionState (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\app-store.ts:1260:15)
    at Gp.repositoryWithRefreshedGitHubRepository (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\app-store.ts:4190:5)
2024-09-10T01:35:03.002Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-09-10T01:35:03.948Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 2.222s)
2024-09-10T01:35:04.642Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-09-10T01:35:05.502Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.547s)
2024-09-10T01:35:05.998Z - info: [ui] [fetchAllRepoRulesets] unable to fetch all repo rulesets | repos/zdhix-viscoflow/chatbot-viscoflow/rulesets
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at wn (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\http.ts:178:11)
    at sr.fetchAllRepoRulesets (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\api.ts:1688:7)
    at Gp.refreshBranchProtectionState (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\app-store.ts:1239:15)
    at C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\app-store.ts:5133:32
    at Gp.withPushPullFetch (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\app-store.ts:4633:5)
    at Gp.performFetch (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\app-store.ts:5090:5)
    at ww.performAndScheduleFetch (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:92:7)
2024-09-10T01:35:06.386Z - info: [ui] [fetchRepoRulesForBranch] unable to fetch repo rules for branch: main | repos/zdhix-viscoflow/chatbot-viscoflow/rules/branches/main
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at wn (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\http.ts:178:11)
    at sr.fetchRepoRulesForBranch (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\api.ts:1667:7)
    at Gp.refreshBranchProtectionState (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\app-store.ts:1260:15)
    at C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\app-store.ts:5133:32
    at Gp.withPushPullFetch (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\app-store.ts:4633:5)
    at Gp.performFetch (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\app-store.ts:5090:5)
    at ww.performAndScheduleFetch (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:92:7)
2024-09-10T01:40:30.389Z - warn: [ui] getFetchPollInterval: failed for zdhix-viscoflow/chatbot-viscoflow
TypeError: Failed to fetch
    at yn (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\http.ts:152:10)
    at sr.request (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\api.ts:1765:28)
    at sr.getFetchPollInterval (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\api.ts:1803:35)
    at ww.getFetchInterval (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:133:40)
    at ww.performAndScheduleFetch (C:\Users\Dhian\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\src\lib\stores\helpers\background-fetcher.ts:107:11)

**Comment by steveward** [comment]
I'm not seeing any specific connection timeouts in the portion of the log file you sent over. Can you confirm in the repository that you are having issues with that you are using SSH? You can check this in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`.

I would recommend using HTTPS to simplify things unless you have a specific need to use SSH over HTTPS. HTTPS will work as long as you are logged in to GitHub Desktop with your GitHub account.

**Comment by zdhix** [comment]
ah i see , so i need to clone my repo manually everytime i make a new repo right ? i thought at first my github can't detect my repo . But if i want to set up my SSH key to make it more secure how so that i can find my public SHH KEY on the **.shh** folder ? Because i can't seem to find one everytime i create a new shh key . Right now i'm using HTTPS . 
Thank you for your help sir .

**Comment by steveward** [comment]
> ah i see , so i need to clone my repo manually everytime i make a new repo right ? i

That's correct. If you are wanting to use SSH you will need to manually enter the SSH clone URL into GitHub Desktop to clone.

>But if i want to set up my SSH key to make it more secure how so that i can find my public SHH KEY on the .shh folder ? Because i can't seem to find one everytime i create a new shh key . Right now i'm using HTTPS .

I would recommend HTTPS, but if you are wanting to use SSH I would recommend taking a look at our helps docs:

https://docs.github.com/en/authentication/connecting-to-github-with-ssh

If you have an existing key you'll need to add it: `ssh-add c:/Users/<your_user>/.ssh/id_ed25519`.

I'm going to close this out.

**Comment by trane77** [comment]
Hi, is there any particular reason of why ssh connection can be used only by entering the URL manually? 
Opening github web to get the ssh address kills the point of point of having the Github app, in my case at least.

**Comment by steveward** [comment]
@funder7 GitHub Desktop defaults to HTTPS because it bypasses the need to go through the process of setting up a SSH key. You can clone the repository via SSH on the command line and then run `github .` to quickly open the repository in GitHub Desktop, or you can use this config option to force the app to always use SSH:

`git config --global url."git@github.com:".insteadOf https://github.com/`

**Comment by trane77** [comment]
Hi @steveward, Ok, I wasn't using Github Desktop before, with ssh keys I was able to clone all my repos without entering the credentials every time, and that works everywhere in the system (terminal, IDEs, etc.).
Basically cloning the repository with GH Desktop (so with https), requires another step of authentication if any git operation is done from the terminal. With ssh this is not required as keys are already installed. 

Thanks for the configuration ;)
