### ISSUE TITLE
GitHub Enterprise fails to login on the 'GitHub Enterprise Account' option, but works when signing in via GitHub.com account option

### ISSUE THREAD

**Issue by CubitsDev** [desktop/desktop#19264]
### The problem

When trying to sign in to a GitHub enterprise account using the sign into GitHub enterprise option, the app redirects and fails to fetch the user on the API. However logging out of my personal account and signing into my enterprise account on the GitHub.com sign in section allows me to authenticate my enterprise account.

### Release version

Version 3.4.5 (arm64)

### Operating system

MacOS Sonoma 14.6.1

### Steps to reproduce the behavior

1. Try to sign in to Enterprise account on the enterprise login
2. After authenticating in browser, app redirects but doesn't update
3. Sign out of 'GitHub.com' account
4. Sign in to enterprise on that account
5. Redirects and authenticates my enterprise account as a personal account

### Log files

Logs for attempting to sign in to the enterprise account
```
2024-09-16T10:42:03.701Z - info: [ui] [AppStore] loading 46 repositories from store
2024-09-16T10:42:03.701Z - info: [ui] [AppStore] found account: CubitsDev (Tom Roman)
2024-09-16T10:42:03.720Z - info: [ui] [BranchPruner] Last prune took place 15 minutes ago - skipping
2024-09-16T10:42:04.108Z - info: [ui] launching: 3.4.5 (Mac OS 14.6.1)
2024-09-16T10:42:04.108Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2024-09-16T10:42:11.921Z - info: [ui] [SignInStore] initializing OAuth flow
2024-09-16T10:42:11.922Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=786c6080-cbb0-4c03-90a2-ce204329b041
2024-09-16T10:42:11.922Z - info: [ui] [SignInStore] account resolved
2024-09-16T10:42:14.205Z - info: [main] Processing protocol url
2024-09-16T10:42:14.597Z - warn: [ui] fetchAccount: failed with endpoint https://github.com/api/v3
Error: API error https://github.com/api/v3/user:  (404)
    at pn (/webpack:/app/src/lib/http.ts:178:11)
    at Jn.fetchAccount (/webpack:/app/src/lib/api.ts:1040:7)
    at tr (/webpack:/app/src/lib/api.ts:2040:11)
    at Zp.resolveOAuthRequest (/webpack:/app/src/lib/stores/sign-in-store.ts:570:13)
    at Object.dispatchURLAction (/webpack:/app/src/ui/dispatcher/dispatcher.ts:1873:12)
2024-09-16T10:42:14.598Z - warn: [ui] fetchUser: failed with endpoint https://github.com/api/v3
Error: API error https://github.com/api/v3/user:  (404)
    at pn (/webpack:/app/src/lib/http.ts:178:11)
    at Jn.fetchAccount (/webpack:/app/src/lib/api.ts:1040:7)
    at tr (/webpack:/app/src/lib/api.ts:2040:11)
    at Zp.resolveOAuthRequest (/webpack:/app/src/lib/stores/sign-in-store.ts:570:13)
    at Object.dispatchURLAction (/webpack:/app/src/ui/dispatcher/dispatcher.ts:1873:12)
```

Signing out of the 'GitHub.com' account and using it to login to the enterprise account
```
2024-09-16T10:45:52.271Z - info: [ui] Unubscribed 'CubitsDev' from Alive channel
2024-09-16T10:45:54.243Z - info: [ui] [SignInStore] initializing OAuth flow
2024-09-16T10:45:54.245Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=7c086978-bf70-49fa-abdb-f519f91a968f
2024-09-16T10:45:54.245Z - info: [ui] [SignInStore] account resolved
2024-09-16T10:45:56.614Z - info: [main] Processing protocol url
2024-09-16T10:45:57.408Z - info: [ui] [AppStore] adding account Tom-Roman-5mo_nbcuni (Roman, Tom (Engineer - Software Engineering - Sky - Guest)) to store
```

**Comment by steveward** [comment]
@CubitsDev it sounds like you are using using GitHub Enterprise Cloud, in which case where you are logging in is correct. At this time you can't be logged in to both at the same time, but we are tracking multi-account support in https://github.com/desktop/desktop/issues/3707.

Let me know if you have any further questions.
