### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by NateKim37** [desktop/desktop#19293]
### The problem

Can't log in. Web browser log in appears when I tried to, and when I successfully log in on the browser, it still doesn't let my github deskop to be logged in.

### Release version

3.4.5 (x64

### Operating system

Windows 10

### Steps to reproduce the behavior

go to file
go to options
go to accounts
select Sign into GitHub.com
log in on the browser.
Then problem happens.

**Comment by sergiou87** [comment]
Could you try temporarily changing your system default browser to another browser to rule out issues with your current one?

If that doesn't work I would also recommend rebooting your machine to see if that helps 🤞

**Comment by NateKim37** [comment]
Both didn't work. Error is still there.

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by NateKim37** [comment]
This is the log from today, I tried to log in again, to create log for this particular error. I still cannot log in.
Thanks.

2024-09-25T02:16:38.274Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-09-25T02:16:38.665Z - info: [ui] [AppStore] loading 2 repositories from store
2024-09-25T02:16:38.683Z - info: [ui] [BranchPruner] Last prune took place 23 hours ago - skipping
2024-09-25T02:16:38.791Z - info: [ui] launching: 3.4.5 (Windows 10.0.19045)
2024-09-25T02:16:38.792Z - info: [ui] execPath: 'C:\Users\nkim\AppData\Local\GitHubDesktop\app-3.4.5\GitHubDesktop.exe'
2024-09-25T02:16:56.838Z - info: [ui] credential-helper: could not find credential for https://github.com/
2024-09-25T02:16:56.857Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.145s)
2024-09-25T02:16:56.860Z - error: [ui] `git fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

2024-09-25T02:17:39.785Z - info: [ui] [SignInStore] initializing OAuth flow
2024-09-25T02:17:39.786Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=2525f3cb-7a7f-4b6f-9a4e-5ebb296dfd10
2024-09-25T02:17:39.786Z - info: [ui] [SignInStore] account resolved
2024-09-25T02:17:46.312Z - info: [main] Received possible protocol arguments: 4
2024-09-25T02:17:46.312Z - info: [main] Processing protocol url
2024-09-25T02:17:47.469Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
Error: Requires authentication
    at yn (C:\Users\nkim\AppData\Local\GitHubDesktop\app-3.4.5\webpack:\app\src\lib\http.ts:178:11)
    at ir.fetchAccount (C:\Users\nkim\AppData\Local\GitHubDesktop\app-3.4.5\webpack:\app\src\lib\api.ts:1040:7)
    at or (C:\Users\nkim\AppData\Local\GitHubDesktop\app-3.4.5\webpack:\app\src\lib\api.ts:2040:11)
    at Vp.resolveOAuthRequest (C:\Users\nkim\AppData\Local\GitHubDesktop\app-3.4.5\webpack:\app\src\lib\stores\sign-in-store.ts:570:13)
    at Object.dispatchURLAction (C:\Users\nkim\AppData\Local\GitHubDesktop\app-3.4.5\webpack:\app\src\ui\dispatcher\dispatcher.ts:1873:12)
2024-09-25T02:17:47.470Z - warn: [ui] fetchUser: failed with endpoint https://api.github.com
Error: Requires authentication
    at yn (C:\Users\nkim\AppData\Local\GitHubDesktop\app-3.4.5\webpack:\app\src\lib\http.ts:178:11)
    at ir.fetchAccount (C:\Users\nkim\AppData\Local\GitHubDesktop\app-3.4.5\webpack:\app\src\lib\api.ts:1040:7)
    at or (C:\Users\nkim\AppData\Local\GitHubDesktop\app-3.4.5\webpack:\app\src\lib\api.ts:2040:11)
    at Vp.resolveOAuthRequest (C:\Users\nkim\AppData\Local\GitHubDesktop\app-3.4.5\webpack:\app\src\lib\stores\sign-in-store.ts:570:13)
    at Object.dispatchURLAction (C:\Users\nkim\AppData\Local\GitHubDesktop\app-3.4.5\webpack:\app\src\ui\dispatcher\dispatcher.ts:1873:12)
2024-09-25T02:18:52.028Z - info: [ui] [SignInStore] OAuth error but session has changed: Error: cancelled
2024-09-25T02:18:52.029Z - info: [ui] credential-helper: could not find credential for https://github.com/
2024-09-25T02:18:57.131Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 79.928s)
2024-09-25T02:18:57.132Z - error: [ui] `git fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

2024-09-25T02:18:57.338Z - warn: [ui] Failed trying to find Git on PATH
Error: Command failed: C:\windows\System32\where.exe git
INFO: Could not find files for the given pattern(s).

    at __node_internal_genericNodeError (node:internal/errors:932:15)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)

**Comment by NateKim37** [comment]
I attached the log. 
[2024-09-25.desktop.production.log](https://github.com/user-attachments/files/17123566/2024-09-25.desktop.production.log)

**Comment by steveward** [comment]
Thanks for sharing the log file. 

Can you try to reset GitHub Desktop by following these steps?

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

You will need to log in and add your repositories again, which can be done quickly in bulk by drag-and-drop. Let me know if that doesn't get things working.

**Comment by NateKim37** [comment]
![image](https://github.com/user-attachments/assets/49bbc294-98c1-4b69-99f7-caf71313b361)
I deleted everything in %APPDATA%\GitHub Desktop\ and restarted github desktop,
Now I"m stuck in this page though I logged in on my web browser.
For some reason it doesn't log in.

**Comment by sergiou87** [comment]
If you open this repository from your browser, then click on Code -> Open with GitHub Desktop… does it do anything at all?

![Image](https://github.com/user-attachments/assets/f05f700d-9cbd-492b-b77e-c413aa00f592)

**Comment by NateKim37** [comment]
![image](https://github.com/user-attachments/assets/5cbc944d-8b5c-482e-b64f-ce30e3289dd2)
it goes to this page, and once I'm trying to log in, it's just same problem again.
Directed to auth page, once log in, ask me to continue on github desktop, and still stuck in the same page that you can see above.
![image](https://github.com/user-attachments/assets/e5fad3e6-0154-4abb-bb26-6b8ffc8e41cb)

**Comment by steveward** [comment]
Can you check to see if GitHub Desktop is set to open as an administrator? We've seen that cause this issue. Here's how to check:

1. Open the start menu and search for GitHub Desktop
2. Right-click and select `Open file location`
3. Right-click on GitHub Desktop and select `Properties`
4. Go to the `Compatibility` tab
5. Under `Settings`, uncheck `Run this program as administrator`

**Comment by NateKim37** [comment]
![image](https://github.com/user-attachments/assets/2c855a7c-2415-41c9-ba9c-55fbac8f9c3e)
As you can see, "Run this program as administrator" was already unchecked.
Any other suggestions?

**Comment by steveward** [comment]
It would be helpful to get some information from the Developer Tools window to see if that shows any further information about why the authentication requests are failing. To do this open the Developer tools by selecting the "View" menu and "Toggle Developer Tools". Once opened try signing in again and see if the dev tools console provides any more insight as to why to the requests are failing.

**Comment by NateKim37** [comment]
Where do you mean by view menu on where?
I'm using chrome to do web sign in. Please specify the steps little more.

Thanks.

**Comment by steveward** [comment]
The "View" option is in the top file menu, and you'll see "Toggle Developer Tools" at the bottom:

![Image](https://github.com/user-attachments/assets/063f3e3c-5b49-4826-a677-b6b9c6ab688f)

**Comment by NateKim37** [comment]
![image](https://github.com/user-attachments/assets/1c4b8a63-f06d-499f-8651-59592f4cdaff)
This is what I got after trying to sign in from developer tools.

Thanks,

**Comment by steveward** [comment]
What default browsers have you tried using to resolve this?
