### ISSUE TITLE
 Git hub desktop is extremely slow.

### ISSUE THREAD

**Issue by DongJu-Na** [desktop/desktop#19381]
### The problem

Git hub desktop is extremely slow.

So I checked the log and it seems to be referencing a deleted repo. How can I solve this?

```
fatal: repository 'https://github.com/xxx/anonymity-repo.git/' not found

(The error was parsed as 9: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2024-10-11T00:03:45.864Z - info: [ui] [fetchAllRepoRulesets] unable to fetch all repo rulesets | repos/anonymity/anonymity-repo/rulesets
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at gn (C:\Users\anonymity\AppData\Local\GitHubDesktop\app-3.4.6\webpack:\app\src\lib\http.ts:178:11)
    at ir.fetchAllRepoRulesets (C:\Users\anonymity\AppData\Local\GitHubDesktop\app-3.4.6\webpack:\app\src\lib\api.ts:1692:7)
    at Vp.refreshBranchProtectionState (C:\Users\anonymity\AppData\Local\GitHubDesktop\app-3.4.6\webpack:\app\src\lib\stores\app-store.ts:1248:15)
    at Vp.repositoryWithRefreshedGitHubRepository (C:\Users\anonymity\AppData\Local\GitHubDesktop\app-3.4.6\webpack:\app\src\lib\stores\app-store.ts:4245:5)
2024-10-11T00:03:46.107Z - info: [ui] [fetchRepoRulesForBranch] unable to fetch repo rules for branch: dev | repos/anonymity/anonymity-repo/rules/branches/dev
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at gn (C:\Users\anonymity\AppData\Local\GitHubDesktop\app-3.4.6\webpack:\app\src\lib\http.ts:178:11)
    at ir.fetchRepoRulesForBranch (C:\Users\anonymity\AppData\Local\GitHubDesktop\app-3.4.6\webpack:\app\src\lib\api.ts:1671:7)
    at Vp.refreshBranchProtectionState (C:\Users\anonymity\AppData\Local\GitHubDesktop\app-3.4.6\webpack:\app\src\lib\stores\app-store.ts:1269:15)
    at Vp.repositoryWithRefreshedGitHubRepository (C:\Users\anonymity\AppData\Local\GitHubDesktop\app-3.4.6\webpack:\app\src\lib\stores\app-store.ts:4245:5)
2024-10-11T00:03:49.056Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 14 repositories took 42.6s of which 62.6s paused, total 105.2s

```

### Release version

3.4.6

### Operating system

window 11

**Comment by steveward** [comment]
It looks like background fetching is taking some time to complete:

`2024-10-11T00:03:49.056Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 14 repositories took 42.6s of which 62.6s paused, total 105.2s`

You can try disabling this to see if it helps performance. You can do this by going to `File` > `Options` > `Advanced` > `Show status icons in the repository list`.

It also would be helpful if I could take a look at the full log file from that day, if you wouldn't mind uploading it as an attachment. There may be some more relevant data in there.

**Comment by DongJu-Na** [comment]
I'll disable background fetching and check for a day or two. Thank you for your reply. If the same symptom repeats, I will attach a log file.

have a good day!

We will close this issue.
