### ISSUE TITLE
HISTORY BUG

### ISSUE THREAD

**Issue by theweblato** [desktop/desktop#19404]
### The problem

bug

### Release version

3.4.6

### Operating system

OS: Windows 10.0.22631

### Log files

Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at file:///app/renderer.js:2:244552
    at o (file:///app/renderer.js:2:244657)
    at ta (file:///app/renderer.js:2:339102)
    at Object.enqueueSetState (file:///app/renderer.js:2:288833)
    at C.setState (file:///app/renderer.js:2:351489)
    at q_.resizeIfNecessary (file:///app/renderer.js:2:1457142)
    at q_.componentDidUpdate (file:///app/renderer.js:2:1455577)
    at Wo (file:///app/renderer.js:2:321716)
    at Go (file:///app/renderer.js:2:324512)
    at file:///app/renderer.js:2:342121

Version: 3.4.6
OS: Windows 10.0.22631

### Screenshots

bug

### Additional context

bug

**Comment by steveward** [comment]
@theweblato thanks for the issue. Can you share a few more details about how you are encountering this error? Any steps to reproduce would be helpful. 

It would also be helpful if you could share the full log file from GitHub Desktop. TTo access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
