### ISSUE TITLE
GitHub Desktop : Failed retrieving authenticated user

### ISSUE THREAD

**Issue by nenadsabo** [desktop/desktop#19532]
### The problem

Authentication just stopped working after the most recent update. Whatever I do I cannot make it work in the latest update.

Using an older version of the desktop works just fine, but again stops working after the software automatically updates itself to the latest version.

### Release version

Version 3.4.8 (x64)

### Operating system

Windows 10 Home

### Steps to reproduce the behavior

1) Try to fetch the remote state from the desktop

2) Observe the error message
![image](https://github.com/user-attachments/assets/b15894a6-a616-4d64-b1fd-6688961106ce)

3) Try to sign-in again
![image](https://github.com/user-attachments/assets/62f5c72f-b9d7-44d0-81bb-55c214a98ee3)

4) Another error message
![image](https://github.com/user-attachments/assets/ea19f34a-f1d0-4211-a230-3c4f474f72ff)

### Log files

2024-11-10T22:07:16.452Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-11-10T22:07:16.658Z - info: [ui] [AppStore] loading 3 repositories from store
2024-11-10T22:07:16.670Z - info: [ui] [BranchPruner] Last prune took place 14 minutes ago - skipping
2024-11-10T22:07:16.864Z - info: [ui] launching: 3.4.8 (Windows 10.0.19045)
2024-11-10T22:07:16.864Z - info: [ui] execPath: 'C:\Users\nenad\AppData\Local\GitHubDesktop\app-3.4.8\GitHubDesktop.exe'
2024-11-10T22:07:18.991Z - error: [ui] `git fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/ExponentialGamesInc/unity_thesled_urp.git/': Send failure: Connection was reset

2024-11-10T22:07:39.081Z - error: [ui] `git fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/ExponentialGamesInc/unity_thesled_urp.git/': Send failure: Connection was reset

2024-11-10T22:08:22.087Z - info: [ui] [SignInStore] initializing OAuth flow
2024-11-10T22:08:22.088Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=9ecb450f-819f-47fb-ab50-2630efa3be95
2024-11-10T22:08:22.088Z - info: [ui] [SignInStore] account resolved
2024-11-10T22:08:24.073Z - info: [main] Received possible protocol arguments: 4
2024-11-10T22:08:24.073Z - info: [main] Processing protocol url
2024-11-10T22:08:24.492Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
    at fn (C:\Users\nenad\AppData\Local\GitHubDesktop\app-3.4.8\webpack:\app\src\lib\http.ts:152:10)
    at C:\Users\nenad\AppData\Local\GitHubDesktop\app-3.4.8\webpack:\app\src\lib\api.ts:2216:28
    at Vp.resolveOAuthRequest (C:\Users\nenad\AppData\Local\GitHubDesktop\app-3.4.8\webpack:\app\src\lib\stores\sign-in-store.ts:642:25)
    at Vp._resolveOAuthRequest (C:\Users\nenad\AppData\Local\GitHubDesktop\app-3.4.8\webpack:\app\src\lib\stores\app-store.ts:5918:29)
    at Object.dispatchURLAction (C:\Users\nenad\AppData\Local\GitHubDesktop\app-3.4.8\webpack:\app\src\ui\dispatcher\dispatcher.ts:1909:29)
    at IpcRenderer.<anonymous> (C:\Users\nenad\AppData\Local\GitHubDesktop\app-3.4.8\webpack:\app\src\ui\index.tsx:352:14)
    at IpcRenderer.emit (node:events:518:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:8837)
2024-11-10T22:08:24.493Z - info: [ui] [SignInStore] error with OAuth flow
Error: Failed retrieving authenticated user
    at Vp.resolveOAuthRequest (C:\Users\nenad\AppData\Local\GitHubDesktop\app-3.4.8\webpack:\app\src\lib\stores\sign-in-store.ts:649:9)
    at Object.dispatchURLAction (C:\Users\nenad\AppData\Local\GitHubDesktop\app-3.4.8\webpack:\app\src\ui\dispatcher\dispatcher.ts:1908:12)

**Comment by nenadsabo** [comment]
Workaround in the meantime for anyone having the issue:

1) Go to the old releases https://github.com/desktop/desktop/releases
2) Choose an earlier release, in my case is version 3.4.7
3) Uninstall the github deskrop and reinstall the old version
4) Important: Open the location of the GitHubDesktop.exe
5) In my case it's C:\Users\USERNAME\AppData\Local\GitHubDesktop
6) Rename the Update.exe to DontUpdate.exe
7) This will prevent the auto updates from happening

Attempting to update will produce the following message:
![image](https://github.com/user-attachments/assets/7328acb7-b72e-41d4-b201-8f3a3fa41cc3)

This is very very good because stuff works now ;D 

Update: I had to go back one version earlier, 3.4.6 seems to do the trick

**Comment by Sinryou** [comment]
I met the same issue when i tried to login with my account.

- **Release version**
Version 3.4.9 (x64)
- **Operating system**
MacOS 13.7.1 arm64
```
2024-11-12T03:56:27.401Z - info: [ui] [SignInStore] initializing OAuth flow
2024-11-12T03:56:27.402Z - info: [main] opening in browser: https://enterprise.addr.git.com/login/oauth/authorize?client_id=xxxxxxxxxxxxxxxxxxxx&scope=repo%20user%20workflow&state=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (i've Hidden some Sensitive Information from this link)
2024-11-12T03:56:27.402Z - info: [ui] [SignInStore] account resolved
2024-11-12T03:56:39.746Z - info: [main] Processing protocol url
2024-11-12T03:56:41.317Z - info: [ui] [SignInStore] error with OAuth flow
Error: Failed retrieving authenticated user
    at _p.resolveOAuthRequest (/webpack:/app/src/lib/stores/sign-in-store.ts:358:9)
    at Object.dispatchURLAction (/webpack:/app/src/ui/dispatcher/dispatcher.ts:1860:12)
```

**Comment by niik** [comment]
Hey @nenadsabo, thanks for reaching out. Do you have any sort of antivirus or other security software on your machine? I ask because the changes between 3.4.7 (which works for you) and 3.4.8 (which doesn't) are minuscule and there's no chance they could have an effect on Git's ability to connect which makes me wonder if something else is at play. We've seen false-positive detections from AV products and firewalls cause connectivity issues in the past so I'm wonder if 3.4.8 has been misidentified by some security software on your machine to not be allowed to connect.

**Comment by nenadsabo** [comment]
Yes, I'm running Kaspersky AV. It does not show any alerts in the AV dashboard related to GihHub.

**Comment by steveward** [comment]
@nenadsabo we've seen quite a few issues with Kaspersky in the past. Is it possible you can temporarily disable Kaspersky or put an exception for GitHub Desktop to see if that gets things working?

**Comment by nenadsabo** [comment]
Yeah for sure, stopping Kaspersky will make the latest version 3.4.9 work without any issue. 

Did not find a reliable way to exclude GitHubDesktop from being blocked, the only thing that worked is completely exiting KAV.

**Comment by ifwn** [comment]
I had the same issue after manually allowing the latest github desktop to update. I resolved it before looking here for a solution. Here is my summary. 

ENVIRONMENT
- OS: Windows 10
- GitHub Desktop: Latest version (3.4.12)
- Git version: 2.47.1.windows.1
- Repository: Hosted on GitHub (https://github.com/user/repo.git)
- Antivirus: Kaspersky

SYMPTOM
- after updating GitHub Desktop, all operations through desktop failed with  "fatal: unable to access 'https://github.com/user/repo.git/': Send failure: Connection was reset"

OBSERVATIONS
- Ensured https url was correct and accessible in browser
- verified network connectivity (ping and DNS lookups succeeded)
- The issue seems isolated to GitHub Desktop’s handling of HTTPS connections post-update, as Git on the command line worked (and still works) perfectly with HTTPS.
- curl tests consistently failed with: "Send failure: Connection was reset"
- curl errors occurred with my own .git endpoint, but also with the base URL (https://github.com)
- Testing with curl and Git’s built-in curl (via OpenSSL) failed during the TLS handshake: "schannel: failed to send initial handshake data: sent -1 of 181 bytes"
- Explicit attempts to force TLS 1.2 (--tlsv1.2) and use Git’s CA bundle didn’t resolve the issue.

RESOLUTION — SWITCH FROM HTTPS TO SSH
- Configured SSH with a new ed25519 key, added the key to GitHub, and updated .ssh/config to explicitly point to the key
- In repository settings (GitHub Desktop->Repository->Repository Settings->Remote), switched repository's remote URL to SSH (git@github.com:user/repo.git)
- After switching to SSH, GitHub Desktop started functioning normally.

SUGGESTIONS
- Investigate whether recent changes in GitHub Desktop's HTTPS handling (e.g., TLS libraries or proxy configurations) might cause connection resets in certain environments.
- Provide clearer error diagnostics for HTTPS issues in GitHub Desktop.
- Consider prompting users to switch to SSH when HTTPS fails persistently.

FINAL NOTES
- I did not try to disable Kaspersky before I resolved the problem with SSH. I can't confirm that solution. I've never had an issue prior to this latest update.

**Comment by steveward** [comment]
Closing as Kaspersky was the culprit here. Glad to here SSH got things working for you @ifwn.

**Comment by cantgetin** [comment]
got the same issue somehow and the problem was that my email wasn't verified.

**Comment by camrespi5** [comment]
I've been experiencing this same trouble. Using a old release made it work for a second but now is not working again. I also have kapersky antivirus however suspending it didnt help either.

**Comment by nenadsabo** [comment]
Yep, suspend didn't help me as well, you need to "kill" it totally.
