### ISSUE TITLE
Invalid String Length error

### ISSUE THREAD

**Issue by historianem** [desktop/desktop#19536]
### The problem

I keep getting this error, and was told to report it here if I encountered it repeatedly. GitHub keeps crashing and giving me this: 

RangeError: Invalid string length
    at u.<anonymous> (file:///app/renderer.js:2:904184)
    at u.emit (node:events:518:28)
    at A (file:///app/renderer.js:2:424730)
    at R (file:///app/renderer.js:2:424560)
    at k.push (file:///app/renderer.js:2:425344)
    at u.push (file:///app/renderer.js:2:435149)
    at c (file:///app/renderer.js:2:453933)
    at u.a [as _transform] (file:///app/renderer.js:2:453619)
    at u._read (file:///app/renderer.js:2:435610)
    at u._write (file:///app/renderer.js:2:435449)

Version: 3.4.8
OS: Mac OS 14.1.0

### Release version

3.4.8

### Operating system

Mac OS 14.1.0

**Comment by steveward** [comment]
@historianem thanks for the report. There's an existing issue (https://github.com/desktop/desktop/issues/15355) where this is caused by repeatedly using squash and merge. Are there any specific steps you are taking when this crash is occurring?
