### ISSUE TITLE
Infinity Fetch

### ISSUE THREAD

**Issue by LoboMetalurgico** [desktop/desktop#19584]
### The problem

When using a repository where the origin is in ssh, the application keeps fetching infinitely, making it impossible to pull, push or perform other operations besides commit.

### Release version

Version 3.4.9 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1 - Clone a repository using SSH
2 - Restart the github desktop (Sometimes it happens immediately, sometimes only after reopening)
3 - Click "Fetch Origin" or just wait for it to be done automatically
4 - The fetch never ends (Texts shows "Hang On...")

### Log files

<pre>
2024-11-20T15:26:04.058Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-11-20T15:26:04.609Z - info: [ui] [AppStore] loading 99 repositories from store
2024-11-20T15:26:04.609Z - info: [ui] [AppStore] found account: LoboMetalurgico (Lobo Metalúrgico)
2024-11-20T15:26:04.630Z - info: [ui] [BranchPruner] Last prune took place 2 minutes ago - skipping
2024-11-20T15:26:04.889Z - info: [ui] launching: 3.4.9 (Windows 10.0.22631)
2024-11-20T15:26:04.890Z - info: [ui] execPath: 'C:\Users\hugoh\AppData\Local\GitHubDesktop\app-3.4.9\GitHubDesktop.exe'
2024-11-20T15:26:05.052Z - info: [ui] Subscribed 'LoboMetalurgico' to Alive channel
2024-11-20T15:26:06.795Z - info: [ui] [fetchAllRepoRulesets] unable to fetch all repo rulesets | repos/Blue-Station/WhatsPending-APP/rulesets
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at pn (C:\Users\hugoh\AppData\Local\GitHubDesktop\app-3.4.9\webpack:\app\src\lib\http.ts:178:11)
    at Yn.fetchAllRepoRulesets (C:\Users\hugoh\AppData\Local\GitHubDesktop\app-3.4.9\webpack:\app\src\lib\api.ts:1672:7)
    at Bp.refreshBranchProtectionState (C:\Users\hugoh\AppData\Local\GitHubDesktop\app-3.4.9\webpack:\app\src\lib\stores\app-store.ts:1242:15)
    at Bp.repositoryWithRefreshedGitHubRepository (C:\Users\hugoh\AppData\Local\GitHubDesktop\app-3.4.9\webpack:\app\src\lib\stores\app-store.ts:4239:5)
2024-11-20T15:26:06.811Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.925s)
2024-11-20T15:26:07.097Z - info: [ui] [fetchRepoRulesForBranch] unable to fetch repo rules for branch: main | repos/Blue-Station/WhatsPending-APP/rules/branches/main
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at pn (C:\Users\hugoh\AppData\Local\GitHubDesktop\app-3.4.9\webpack:\app\src\lib\http.ts:178:11)
    at Yn.fetchRepoRulesForBranch (C:\Users\hugoh\AppData\Local\GitHubDesktop\app-3.4.9\webpack:\app\src\lib\api.ts:1651:7)
    at Bp.refreshBranchProtectionState (C:\Users\hugoh\AppData\Local\GitHubDesktop\app-3.4.9\webpack:\app\src\lib\stores\app-store.ts:1263:15)
    at Bp.repositoryWithRefreshedGitHubRepository (C:\Users\hugoh\AppData\Local\GitHubDesktop\app-3.4.9\webpack:\app\src\lib\stores\app-store.ts:4239:5)
2024-11-20T15:26:17.494Z - error: [ui] Could not load old contents for syntax highlighting
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (node:child_process:490:14)
    at Socket.emit (node:events:531:35)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)
</pre>

### Screenshots

![image](https://github.com/user-attachments/assets/dd61df30-2860-414c-b078-dec68d4aa45d)

### Additional context

`Use System OpenSSH (Recommended)` is enable

**Comment by steveward** [comment]
Thanks for the report @LoboMetalurgico. Does unchecking `Use system OpenSSH` get things working?

**Comment by LoboMetalurgico** [comment]
Yes @steveward.
