### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1960]
https://haystack.githubapp.com/desktop/rollups/e0ce36f051d9c5bae2902e523060b8a9

I think this is new in 0.6.0.

```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
at EventEmitter.L.ipcMain.on (app/main.js:3:103217)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
at WebContents.<anonymous> (app/Contents/Resources/electron.asar/browser/api/web-contents.js:247:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by joshaber** [comment]
It turns out this was @niik trolling :hurtrealbad:
