### ISSUE TITLE
TypeError: Cannot read property 'nextSelectableRow' of null

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1961]
https://haystack.githubapp.com/desktop/rollups/8871769c94d47911b855addc2fbb5758

```
TypeError: Cannot read property 'nextSelectableRow' of null
at Z.onKeyDown (app\src\ui\autocompletion\autocompleting-text-input.tsx:291:47)
at Object.L (app\~\react-dom\lib\ReactComponentEnvironment.js:43:1)
at U (app\~\react-dom\lib\EventPluginUtils.js:81:1)
at Object.executeDispatchesInOrder (app\~\react-dom\lib\EventPluginUtils.js:100:1)
at ee (app\~\react-dom\lib\EventPluginHub.js:19:1)
at oe (app\~\react-dom\lib\EventPluginHub.js:49:1)
    at Array.forEach (native)
at R.exports (app\~\react-dom\lib\accumulateInto.js:55:1)
at Object.processEventQueue (app\~\react-dom\lib\EventPluginHub.js:242:1)
at L (app\~\react-dom\lib\ReactEventEmitterMixin.js:18:1)
at Object.handleTopLevel [as _handleTopLevel] (app\~\react-dom\lib\ReactEventEmitterMixin.js:28:1)
```

**Comment by shiftkey** [comment]
I think this is related to what I stumbled upon in https://github.com/desktop/desktop/issues/996 ages ago

**Comment by alealues** [comment]
TypeError: Cannot read property 'nextSelectableRow' of null
at Z.onKeyDown (app\src\ui\autocompletion\autocompleting-text-input.tsx:291:47)
at Object.L (app\~\react-dom\lib\ReactComponentEnvironment.js:43:1)
at U (app\~\react-dom\lib\EventPluginUtils.js:81:1)
at Object.executeDispatchesInOrder (app\~\react-dom\lib\EventPluginUtils.js:100:1)
at ee (app\~\react-dom\lib\EventPluginHub.js:19:1)
at oe (app\~\react-dom\lib\EventPluginHub.js:49:1)
    at Array.forEach (native)
at R.exports (app\~\react-dom\lib\accumulateInto.js:55:1)
at Object.processEventQueue (app\~\react-dom\lib\EventPluginHub.js:242:1)
at L (app\~\react-dom\lib\ReactEventEmitterMixin.js:18:1)
at Object.handleTopLevel [as _handleTopLevel] (app\~\react-dom\lib\ReactEventEmitterMixin.js:28:1)
