### ISSUE TITLE
Showing Git logs as errors in the app

### ISSUE THREAD

**Issue by anshuman910** [desktop/desktop#19768]
### The problem

Whenever i am trying to change my repo branch, or trying to commit and push or do any "transactions"  the git logs are showing as errors.  also getting remote disconnected error when pushing.....

### Release version

Version 3.4.12 (x64)

### Operating system

Windows 10 64bit

### Steps to reproduce the behavior

Already explained

### Log files

not needed

### Screenshots

![image](https://github.com/user-attachments/assets/927c1a19-6908-4aae-b87b-8bb4059cc005)
![image](https://github.com/user-attachments/assets/0e8a1093-6144-4bcb-9dcb-dcd605aaabdf)

### Additional context

I have two different windows 10 devices with the same GitHub account linked.  facing the same error on both devices.

**Comment by tidy-dev** [comment]
@anshuman910 Thank you for reaching out! Can you upload logs for the day when this occurred?

> I have two different windows 10 devices with the same GitHub account linked. facing the same error on both devices.

Does that mean that you have other GitHub repositories where this is not an issue?

**Comment by anshuman910** [comment]
@tidy-dev @mtodd @probablycorey @mutle 

Okay, I need to be a little bit specific. 
1. I have 2 devices with the same version of Windows 10 running and using the same github.com account on GitHub desktop app.
2. I have more than 60 repositories that are identically cloned on each device. 
3. **I am facing this issue for the last 1 month on both of the devices.**  whenever I am trying to commit and push, getting this error==> 
![image](https://github.com/user-attachments/assets/d0bf4cae-e34c-4333-b710-56aedbfcafa5)

and whenever i am trying to switch between branches of any of the more than 60 repositories, getting the same type of error==> 
![image](https://github.com/user-attachments/assets/11842581-a479-4a67-880b-ce181b914a01)


**THE SAME THING HAPPENS ON EVERY REPOSITORY, EVERY BRANCH, EVERY DEVICE I OWN.**


Also, I am sending the logs just like you requested. 

Log==>
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at Lt (C:\Users\removed_for_privacy\AppData\Local\GitHubDesktop\app-3.4.12\webpack:\app\src\lib\http.ts:178:11)
    at Xn.fetchAllRepoRulesets (C:\Users\removed_for_privacy\AppData\Local\GitHubDesktop\app-3.4.12\webpack:\app\src\lib\api.ts:1672:7)
    at Zp.refreshBranchProtectionState (C:\Users\removed_for_privacy\AppData\Local\GitHubDesktop\app-3.4.12\webpack:\app\src\lib\stores\app-store.ts:1243:15)
    at Zp.repositoryWithRefreshedGitHubRepository (C:\Users\removed_for_privacy\AppData\Local\GitHubDesktop\app-3.4.12\webpack:\app\src\lib\stores\app-store.ts:4240:5)
2024-12-27T18:48:10.705Z - info: [ui] [fetchRepoRulesForBranch] unable to fetch repo rules for branch: master | repos/removed_for_privacy/removed_for_privacy/rules/branches/master
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
    at Lt (C:\Users\removed_for_privacy\AppData\Local\GitHubDesktop\app-3.4.12\webpack:\app\src\lib\http.ts:178:11)
    at Xn.fetchRepoRulesForBranch (C:\Users\removed_for_privacy\AppData\Local\GitHubDesktop\app-3.4.12\webpack:\app\src\lib\api.ts:1651:7)
    at Zp.refreshBranchProtectionState (C:\Users\removed_for_privacy\AppData\Local\GitHubDesktop\app-3.4.12\webpack:\app\src\lib\stores\app-store.ts:1264:15)
    at Zp.repositoryWithRefreshedGitHubRepository (C:\Users\removed_for_privacy\AppData\Local\GitHubDesktop\app-3.4.12\webpack:\app\src\lib\stores\app-store.ts:4240:5)
2024-12-27T18:48:11.685Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T18:48:13.713Z - info: [ui] Executing isUsingLFS: git lfs track (took 3.844s)
2024-12-27T18:48:14.138Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 4.765s)
2024-12-27T18:48:16.554Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T18:48:18.392Z - info: [ui] Executing getCommits: git log origin/main..main --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.018s)
2024-12-27T18:48:18.777Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 4.604s)
2024-12-27T18:48:21.656Z - info: [ui] Executing getCommits: git log 74c2f55f5b759047396d7e771c761a48b0a02c25 --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.658s)
2024-12-27T18:48:25.145Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.061s)
2024-12-27T18:48:25.705Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T18:48:27.383Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 4.095s)
2024-12-27T18:48:28.520Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T18:48:29.473Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 2.090s)
2024-12-27T18:48:31.722Z - info: [ui] Executing getBranchesDifferingFromUpstream: git for-each-ref --format=%00%(refname)%00%(objectname)%00%(upstream)%00%(symref)%00%(HEAD)%00 refs/heads refs/remotes (took 2.031s)
2024-12-27T18:48:33.764Z - info: [ui] Executing getRemotes: git remote -v (took 1.402s)
2024-12-27T18:48:35.719Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.948s)
2024-12-27T18:48:35.731Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(symref)%00 refs/heads refs/remotes (took 1.974s)
2024-12-27T18:48:38.816Z - info: [ui] Executing getStashEntries: git log -g -z --format=%gD%x00%H%x00%gs%x00%T%x00%P refs/stash -- (took 2.066s)
2024-12-27T18:48:38.832Z - info: [ui] Executing getCommits: git log origin/main..main --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 2.118s)
2024-12-27T18:48:38.839Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 2.057s)
2024-12-27T18:54:26.541Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T18:54:28.732Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 3.652s)
2024-12-27T18:54:30.611Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T18:54:31.645Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 2.912s)
2024-12-27T18:54:37.268Z - error: [ui] Branch fast-forwarding failed
Error: ENOENT: Git failed to execute. This typically means that the path provided doesn't exist or that the Git executable could not be found which could indicate a problem with the packaging of dugite. Verify that resolveGitBinary returns a valid path to the git binary.
    at C:\Users\removed_for_privacy\AppData\Local\GitHubDesktop\app-3.4.12\webpack:\app\node_modules\dugite\build\lib\exec.js:37:20
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:519:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-12-27T18:54:38.850Z - error: [ui] Branch fast-forwarding failed
Error: ENOENT: Git failed to execute. This typically means that the path provided doesn't exist or that the Git executable could not be found which could indicate a problem with the packaging of dugite. Verify that resolveGitBinary returns a valid path to the git binary.
    at C:\Users\removed_for_privacy\AppData\Local\GitHubDesktop\app-3.4.12\webpack:\app\node_modules\dugite\build\lib\exec.js:37:20
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:519:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-12-27T18:54:55.416Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T18:55:02.393Z - warn: [ui] fetchRepository: 'removed_for_privacy/removed_for_privacy' returned a 404
2024-12-27T18:55:03.070Z - warn: [ui] fetchRepository: 'removed_for_privacy/removed_for_privacy' returned a 404
2024-12-27T18:55:04.557Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T18:55:04.854Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.780s)
2024-12-27T18:55:04.856Z - error: [ui] `git fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
remote: Repository not found.
fatal: repository 'https://github.com/removed_for_privacy/removed_for_privacy.git/' not found

(The error was parsed as 9: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2024-12-27T18:55:05.340Z - info: [ui] Executing clone: git -c init.defaultBranch=main clone --recursive --progress -- https://github.com/repo_name_removed_for_privacy.git D:\removed_for_privacy\removed_for_privacy\removed_for_privacy (took 11.933s)
2024-12-27T18:55:05.432Z - info: [ui] [BranchPruner] Last prune took place 27 seconds ago - skipping
2024-12-27T18:55:07.492Z - warn: [ui] fetchRepository: 'removed_for_privacy' returned a 404
2024-12-27T18:55:07.900Z - warn: [ui] fetchRepository: 'removed_for_privacy' returned a 404
2024-12-27T18:55:09.233Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(symref)%00 refs/heads refs/remotes (took 2.312s)
2024-12-27T18:55:09.251Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.322s)
2024-12-27T18:55:09.277Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.309s)
2024-12-27T18:55:09.286Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(symref)%00 refs/heads refs/remotes (took 2.324s)
2024-12-27T18:55:11.387Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T18:55:11.786Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 3.495s)
2024-12-27T18:55:11.787Z - error: [ui] `git fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
remote: Repository not found.
fatal: repository 'https://github.com/removed_for_privacy/' not found

(The error was parsed as 9: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2024-12-27T18:55:27.268Z - info: [ui] Executing getRemotes: git remote -v (took 13.647s)
2024-12-27T19:10:44.170Z - info: [main] opening in browser: https://github.com/repo_name_removed_for_privacy
2024-12-27T19:10:45.369Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T19:11:02.123Z - info: [ui] Executing pull: git -c rebase.backend=merge pull --ff --recurse-submodules --progress origin (took 18.775s)
2024-12-27T19:11:04.027Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T19:11:05.081Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 2.939s)
2024-12-27T19:11:10.245Z - info: [ui] Executing getRemotes: git remote -v (took 2.380s)
2024-12-27T19:59:46.779Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T19:59:48.540Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 4.103s)
2024-12-27T19:59:50.378Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T19:59:51.626Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 3.084s)
2024-12-27T20:32:15.333Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T20:32:17.011Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 3.571s)
2024-12-27T20:32:18.554Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T20:32:19.716Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 2.700s)
2024-12-27T21:04:42.730Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T21:04:43.925Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 2.492s)
2024-12-27T21:04:45.125Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T21:04:46.086Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 2.159s)
2024-12-27T21:34:54.113Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T21:35:02.979Z - info: [ui] Executing pull: git -c rebase.backend=merge pull --ff --recurse-submodules --progress origin (took 11.095s)
2024-12-27T21:35:04.410Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-12-27T21:35:05.508Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 2.517s)
2024-12-27T21:41:15.843Z - error: [ui] `git checkout --progress origin/stage_branch -b stage_branch --recurse-submodules --` exited with an unexpected code: 3221226505.
branch 'stage_branch' set up to track 'origin/stage_branch'.

2024-12-27T21:41:17.774Z - info: [ui] [Timing] Action 'checkout branch from list' for 'repo_name_removed_for_privacy' took 2.465s
2024-12-27T21:41:21.846Z - error: [ui] `git checkout --progress dev --recurse-submodules --` exited with an unexpected code: 3221226505.
Your branch is up to date with 'origin/dev'.

2024-12-27T21:41:24.039Z - info: [ui] [Timing] Action 'checkout branch from list' for 'repo_name_removed_for_privacy' took 2.907s

**Comment by tidy-dev** [comment]
@anshuman910 Thank you for that added detail. The logs were quite helpful. 

``Error: ENOENT: Git failed to execute. This typically means that the path provided doesn't exist or that the Git executable could not be found which could indicate a problem with the packaging of dugite. Verify that resolveGitBinary returns a valid path to the git binary.``

Would indicate that there is something wrong with your installation of GitHub Desktop. 

Could you try a full uninstall and reinstall GitHub Desktop?

1. Close GitHub Desktop
2. Remove all of the files in `%LOCALAPPDATA%\GitHubDesktop\`
3. Reinstall GitHub Desktop from http://desktop.github.com


Other information:
- Have you tried fetching or pushing in the command line? Does it work there?

**Comment by anshuman910** [comment]
@tidy-dev @mtodd @probablycorey @mutle 

 Hello, I have done complete reinstallation on both of my laptops by following the steps you have mentioned.  but still facing the issue.  
and yes git works everywhere just except in GitHub desktop app.    it even works inside vs code, but not in the app.    On Saturday 28 December, 2024 at 06:02:46 am IST, tidy-dev ***@***.***> wrote:  
 
 


@anshuman910 Thank you for that added detail. The logs were quite helpful.

Error: ENOENT: Git failed to execute. This typically means that the path provided doesn't exist or that the Git executable could not be found which could indicate a problem with the packaging of dugite. Verify that resolveGitBinary returns a valid path to the git binary.

Would indicate that there is something wrong with your installation of GitHub Desktop.

Could you try a full uninstall and reinstall GitHub Desktop?
   
   - Close GitHub Desktop
   - Remove all of the files in %LOCALAPPDATA%\GitHubDesktop\
   - Reinstall GitHub Desktop from http://desktop.github.com

Other information:
   
   - Have you tried fetching or pushing in the command line? Does it work there?

**Comment by steveward** [comment]
@anshuman910 are you running any antivirus or other security software that could be interfering with GitHub Desktop?

**Comment by anshuman910** [comment]
Thank you very much for your help. I discovered that it was actually my good old **antivirus** program that had decided to prank me for three months!

Added to exclutions and it's fine now.
