### ISSUE TITLE
500 error on successful Enterprise login 

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2066]
I removed Oauth access, and tested the Enterprise login. Although the login was successful, there was a 500 error in the logs.

Build v0.6.1, OSX 10.11.5

```Uncaught (in promise) se: {"message":"Server Error","documentation_url":"https://developer.github.com/v3"} GET https://api.github.com/user Status: 500```
    ```at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/shared.js:1:636206
    at process._tickCallback (internal/process/next_tick.js:103:7)```

Reproduce:
- Remove oAuth access in Settings for Enterprise user
- Login to Enterprise user via Desktop, complete all steps

LOGS:
2017-06-20T10:50:21.385Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: No path specified. See 'man git-pull' for valid url syntax

2017-06-20T11:50:47.823Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: No path specified. See 'man git-pull' for valid url syntax

2017-06-20T12:51:14.303Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: No path specified. See 'man git-pull' for valid url syntax

2017-06-20T13:51:40.803Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: No path specified. See 'man git-pull' for valid url syntax

2017-06-20T13:57:59.006Z - info: [ui] Stats reported.
2017-06-20T14:52:07.318Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: No path specified. See 'man git-pull' for valid url syntax

2017-06-20T15:52:33.799Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: No path specified. See 'man git-pull' for valid url syntax

2017-06-20T17:33:38.488Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: No path specified. See 'man git-pull' for valid url syntax

2017-06-20T17:33:38.600Z - error: [ui] Unable to deserialize JSON string to object [object Response]
SyntaxError: Unexpected token N in JSON at position 0
2017-06-20T17:33:38.604Z - warn: [ui] Unable to fetch issues for testcrew/jjjjj
Error: Could not fetch issues, server responded with 404 Not Found.
    at I.API.<anonymous> (/webpack:/app/src/lib/api.ts:376:26)
    at Generator.next (<anonymous>)
    at De (/webpack:/app/src/lib/api.ts:654:2)
2017-06-20T17:34:24.808Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: No path specified. See 'man git-pull' for valid url syntax

2017-06-20T17:34:24.911Z - error: [ui] Unable to deserialize JSON string to object [object Response]
SyntaxError: Unexpected token N in JSON at position 0
2017-06-20T17:34:24.913Z - warn: [ui] Unable to fetch issues for testcrew/jjjjj
Error: Could not fetch issues, server responded with 404 Not Found.
    at I.API.<anonymous> (/webpack:/app/src/lib/api.ts:376:26)
    at Generator.next (<anonymous>)
    at De (/webpack:/app/src/lib/api.ts:654:2)
2017-06-20T17:34:29.524Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: No path specified. See 'man git-pull' for valid url syntax

2017-06-20T17:34:29.570Z - error: [ui] Unable to deserialize JSON string to object [object Response]
SyntaxError: Unexpected token N in JSON at position 0
2017-06-20T17:34:29.572Z - warn: [ui] Unable to fetch issues for testcrew/jjjjj
Error: Could not fetch issues, server responded with 404 Not Found.
    at I.API.<anonymous> (/webpack:/app/src/lib/api.ts:376:26)
    at Generator.next (<anonymous>)
    at De (/webpack:/app/src/lib/api.ts:654:2)
2017-06-20T17:36:43.166Z - error: [ui] `git -c credential.helper= push origin vbvbvb:vbvbvb --progress` exited with an unexpected code: 128.
fatal: No path specified. See 'man git-pull' for valid url syntax

2017-06-20T17:36:48.041Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: No path specified. See 'man git-pull' for valid url syntax

2017-06-20T17:36:48.166Z - error: [ui] Unable to deserialize JSON string to object [object Response]
SyntaxError: Unexpected token N in JSON at position 0
2017-06-20T17:36:48.166Z - warn: [ui] Unable to fetch issues for testcrew/jjjjj
Error: Could not fetch issues, server responded with 404 Not Found.
    at I.API.<anonymous> (/webpack:/app/src/lib/api.ts:376:26)
    at Generator.next (<anonymous>)
    at De (/webpack:/app/src/lib/api.ts:654:2)
2017-06-20T17:37:12.674Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/tierninho-tester/Whatss.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository. Open preferences and verify that you're signed in with an account that has permission to access this repository.)
2017-06-20T17:37:20.447Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/tierninho-tester/Whatss.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository. Open preferences and verify that you're signed in with an account that has permission to access this repository.)
2017-06-20T17:37:35.946Z - error: [ui] Unable to deserialize JSON string to object [object Response]
SyntaxError: Unexpected token N in JSON at position 0
2017-06-20T17:37:35.947Z - warn: [ui] Unable to fetch issues for tierninho/dscsdcsd
Error: Could not fetch issues, server responded with 404 Not Found.
    at I.API.<anonymous> (/webpack:/app/src/lib/api.ts:376:26)
    at Generator.next (<anonymous>)
    at De (/webpack:/app/src/lib/api.ts:654:2)
2017-06-20T17:37:36.003Z - error: [ui] Unable to deserialize JSON string to object [object Response]
SyntaxError: Unexpected token N in JSON at position 0
2017-06-20T17:37:36.005Z - warn: [ui] Unable to fetch issues for tierninho/dscsdcsd
Error: Could not fetch issues, server responded with 404 Not Found.
    at I.API.<anonymous> (/webpack:/app/src/lib/api.ts:376:26)
    at Generator.next (<anonymous>)
    at De (/webpack:/app/src/lib/api.ts:654:2)
2017-06-20T17:37:36.182Z - error: [ui] Unable to deserialize JSON string to object [object Response]
SyntaxError: Unexpected token N in JSON at position 0
2017-06-20T17:37:36.184Z - warn: [ui] Unable to fetch issues for tierninho/dscsdcsd
Error: Could not fetch issues, server responded with 404 Not Found.
    at I.API.<anonymous> (/webpack:/app/src/lib/api.ts:376:26)
    at Generator.next (<anonymous>)
    at De (/webpack:/app/src/lib/api.ts:654:2)
2017-06-20T17:38:50.636Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/tierninho-tester/Testtttt.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository. Open preferences and verify that you're signed in with an account that has permission to access this repository.)

**Comment by joshaber** [comment]
Was the 500 user-facing? When did you get it?

**Comment by tierninho** [comment]
Not user facing, but wanted to bring it up just in case. 

Got the error yesterday, right after logging in with the Enterprise user. Should we close this and move over to dotcom Issues?

**Comment by joshaber** [comment]
I'm not sure, but given that the API layer changed dramatically in #2080, let's close this and wait to see if there are any concrete problems.
