### ISSUE TITLE
GITHUB WINDOWS GUI FREEZES UP

### ISSUE THREAD

**Issue by CarloTonyDaristotile** [desktop/desktop#2110]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

[Description of the issue]

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** [version here]

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [What you expected to happen]

**Actual behaviour:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behaviour of the
application on your machine.

**Comment by shiftkey** [comment]
@CarloTonyDaristotile please create a new issue with the issue template pre-filled so we can investigate further.

**Comment by CarloTonyDaristotile** [comment]
Description
GITHUB DESKTOP WINDOWS GUI FREEZES UP SOMETIMES
Version 0.6.2
Microsoft Windows [Version 10.0.14393]
Steps to Reproduce
1. CLONE REPOSITORY
2. NOW FROZEN / NOW MENU BUTTONS WORKING. TOTAL DEEP FREEZE
3. TO FIX CLOSED IN TASK MANAGER, AND REOPENED
logs
2017-06-24T15:50:15.634Z - info: [ui] Stats reported.
2017-06-24T15:50:16.437Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.092s)
2017-06-24T15:51:45.039Z - warn: [ui] Unknown URL action: unknown - payload: {"args":{},"name":"unknown"}
2017-06-24T16:24:43.442Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.230s)
2017-06-24T16:24:45.049Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.082s)
2017-06-24T16:28:43.379Z - warn: [ui] Unable to deserialize JSON string to object [object Response]
SyntaxError: Unexpected end of JSON input
2017-06-24T16:28:43.628Z - warn: [ui] fetchMentionables: failed for carlotonydaristotile/Coding-Crash-Course
Error: API error https://api.github.com/repos/carlotonydaristotile/Coding-Crash-Course/mentionables/users: Not Modified (304)
    at Object.<anonymous> (C:\Users\CarloTony\AppData\Local\GitHubDesktop\app-0.6.2\webpack:\app\src\lib\http.ts:126:13)
    at Generator.throw (<anonymous>)
    at se (C:\Users\CarloTony\AppData\Local\GitHubDesktop\app-0.6.2\webpack:\app\src\lib\http.ts:115:4)
2017-06-24T16:47:00.325Z - warn: [ui] Unable to deserialize JSON string to object [object Response]
SyntaxError: Unexpected end of JSON input
2017-06-24T16:47:00.573Z - warn: [ui] fetchMentionables: failed for carlotonydaristotile/Coding-Crash-Course
Error: API error https://api.github.com/repos/carlotonydaristotile/Coding-Crash-Course/mentionables/users: Not Modified (304)
    at Object.<anonymous> (C:\Users\CarloTony\AppData\Local\GitHubDesktop\app-0.6.2\webpack:\app\src\lib\http.ts:126:13)
    at Generator.throw (<anonymous>)
    at se (C:\Users\CarloTony\AppData\Local\GitHubDesktop\app-0.6.2\webpack:\app\src\lib\http.ts:115:4)
2017-06-24T16:50:53.993Z - warn: [ui] Unable to deserialize JSON string to object [object Response]
SyntaxError: Unexpected end of JSON input
2017-06-24T16:50:53.996Z - warn: [ui] fetchMentionables: failed for carlotonydaristotile/Coding-Crash-Course
Error: API error https://api.github.com/repos/carlotonydaristotile/Coding-Crash-Course/mentionables/users: Not Modified (304)
    at Object.<anonymous> (C:\Users\CarloTony\AppData\Local\GitHubDesktop\app-0.6.2\webpack:\app\src\lib\http.ts:126:13)
    at Generator.throw (<anonymous>)
    at se (C:\Users\CarloTony\AppData\Local\GitHubDesktop\app-0.6.2\webpack:\app\src\lib\http.ts:115:4)
2017-06-24T16:51:40.315Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress --progress -- https://github.com/CarloTonyDaristotile/FIOS.git C:\PROJECTS\GIT\FIOS (took 4.072s)
2017-06-24T17:09:36.461Z - warn: [ui] Unable to deserialize JSON string to object [object Response]
SyntaxError: Unexpected end of JSON input
2017-06-24T17:09:36.722Z - warn: [ui] fetchMentionables: failed for carlotonydaristotile/FIOS
Error: API error https://api.github.com/repos/carlotonydaristotile/FIOS/mentionables/users: Not Modified (304)
    at Object.<anonymous> (C:\Users\CarloTony\AppData\Local\GitHubDesktop\app-0.6.2\webpack:\app\src\lib\http.ts:126:13)
    at Generator.throw (<anonymous>)
    at se (C:\Users\CarloTony\AppData\Local\GitHubDesktop\app-0.6.2\webpack:\app\src\lib\http.ts:115:4)
2017-06-24T17:09:37.285Z - error: [ui] `git var GIT_AUTHOR_IDENT` exited with an unexpected code: 3221225794.

**Comment by shiftkey** [comment]
@CarloTonyDaristotile some further questions I have:

> GITHUB DESKTOP WINDOWS GUI FREEZES UP SOMETIMES

"Sometimes" here is interesting to me. How often are you able to recreate this? Are there things that seem to make it more likely to occur?

> CLONE REPOSITORY

This needs more information.

 - Did you clone this from the "Clone in Desktop" button on GitHub? Or did you use the "Clone Repository" menu item to start the clone from in the app?
 - Can you tell me about the repository you were cloning? Is it public, so that I can test out the same experience you're seeing? 

> NOW FROZEN / NOW MENU BUTTONS WORKING. TOTAL DEEP FREEZE

Do you mean "no menu buttons working" here? And do you see the repository in the app when you restart the app?

I don't see a clone operation in the log file (whether it succeeds or failed), but I do see a `fetch` - which suggests it has a repository to work with:

```
2017-06-24T16:24:45.049Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.082s)
```

I also see this Git operation fail, which while interesting probably isn't important here:

```
2017-06-24T17:09:37.285Z - error: [ui] git var GIT_AUTHOR_IDENT exited with an unexpected code: 3221225794.
```

**Comment by joshaber** [comment]
Closing until more information is provided.

**Comment by tristoboydo** [comment]
You might want to check for old GIT installs that might be causing a conflict.

I had a freezing problem from install, so I uninstalled and in the process found an old installation of GIT which I also unistalled. The re-install seems to work fine.
