### ISSUE TITLE
unnecessary squirrel noise in logs

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2152]
If you're testing out the app with `NODE_ENV=production` enabled, like this:

```
npm run build:prod
npm run start:prod
```

You'll probably see an error like this after the app launches. This also occurs on CI environments:

```
$ npm run start:prod

> @ start:prod C:\Users\shiftkey\Documents\GitHub\desktop
> cross-env NODE_ENV=production node script/start


error: [ui] Error checking for updates
Error: Can not find Squirrel
    at AutoUpdater.emitError (C:\Users\shiftkey\Documents\GitHub\desktop\dist\GitHub Desktop-win32-x64\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:58:24)
    at AutoUpdater.checkForUpdates (C:\Users\shiftkey\Documents\GitHub\desktop\dist\GitHub Desktop-win32-x64\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:29:19)
    at callFunction (C:\Users\shiftkey\Documents\GitHub\desktop\dist\GitHub Desktop-win32-x64\resources\electron.asar\browser\rpc-server.js:249:18)
    at EventEmitter.<anonymous> (C:\Users\shiftkey\Documents\GitHub\desktop\dist\GitHub Desktop-win32-x64\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\shiftkey\Documents\GitHub\desktop\dist\GitHub Desktop-win32-x64\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**It'd be nice to detect if the app is installed and not try to update things on Windows.**

**Comment by shiftkey** [comment]
This is so minor that I might be the only one who cares about it. And it's not a user-facing issue so I'm going to close this out.
