### ISSUE TITLE
Can't download: 500 error

### ISSUE THREAD

**Issue by wjk** [desktop/desktop#2348]
### Description

Quite simply, I cannot download the application. I have tried the default Windows installer, the Windows MSI installer, and the Mac DMG for good measure. Each link gives me a 500 error page and no further details. I have tried this in both Microsoft Edge and Google Chrome, just in case it was a browser issue.

### Version

**GitHub Desktop version:** Not applicable.  
**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Go to <https://desktop.github.com/> and try to download the application.

**Expected behavior:** It should download!  
**Actual behavior:** 500 error as described above.  
**Reproduces how often:** Every time I try, at least for me. As far as I can tell, everyone on my work network has this problem. Don't know if it happens to anyone outside it, though.

**Comment by shiftkey** [comment]
@wjk oof, thanks for the report. Looking into it now.

**Comment by shiftkey** [comment]
Looks like some upstream AWS issues are affecting the backend we use for serving up downloads and updates. Will update this as the issue evolves.

**Comment by shiftkey** [comment]
I think things are back and have stabilized. We'll keep an eye on it. Thanks for the report @wjk!

**Comment by Bitwix** [comment]
It's happening again.

Steps to Reproduce
Go to https://desktop.github.com/ and try to download the application. 
Expected behavior: It should download!
Actual behavior: 500 error at https://central.github.com/deployments/desktop/desktop/latest/darwin

**Comment by Needmeme** [comment]
Mine too. It always download fail open something log

**Comment by shiftkey** [comment]
@Needmeme could you open a new issue and provide the log details

**Comment by Needmeme** [comment]
@shiftkey It says "Installation has failed
                              There was an error while installing the application.
                              Check the setup log for more information and contact 
                              the author"
And then there's two button that says "Open Setup Log" and "Close"

**Comment by Needmeme** [comment]
2018-02-10 10:29:04> Program: Starting Squirrel Updater: --install .
2018-02-10 10:29:04> Program: Starting install, writing to C:\ProgramData\Luzzitto\SquirrelTemp
2018-02-10 10:29:05> Program: About to install to: C:\ProgramData\Luzzitto\GitHubDesktop
2018-02-10 10:29:05> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ProgramData\Luzzitto\GitHubDesktop\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-02-10 10:29:06> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ProgramData\Luzzitto\GitHubDesktop\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-02-10 10:29:06> CheckForUpdateImpl: Reading RELEASES file from C:\ProgramData\Luzzitto\SquirrelTemp
2018-02-10 10:29:07> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-02-10 10:29:08> ApplyReleasesImpl: Writing files to app directory: C:\ProgramData\Luzzitto\GitHubDesktop\app-1.0.13
2018-02-10 10:29:47> LogHost: Rigging execution stub for lib/net45/GitHubDesktop_ExecutionStub.exe to C:\ProgramData\Luzzitto\GitHubDesktop\GitHubDesktop.exe
2018-02-10 10:30:22> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\ProgramData\Luzzitto\GitHubDesktop\app-1.0.13\GitHubDesktop.exe]
2018-02-10 10:30:22> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\ProgramData\Luzzitto\GitHubDesktop\app-1.0.13\GitHubDesktop.exe: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2018-02-10 10:30:22> IEnableLogger: Failed to invoke post-install: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
2018-02-10 10:30:22> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

**Comment by shiftkey** [comment]
@Needmeme thanks for the details

> System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.

This suggest you're trying to install Desktop on a 32-bit version of Windows - this isn't currently supported, see #1214 for further details

**Comment by zhanarkaliyeva** [comment]
I cannot download the application too. Windows 64bit. It says 500 Error

**Comment by MissyM2** [comment]
Me, neither.  My windows 64-bit laptop is brand new.  I get a 500 error.

**Comment by joshaber** [comment]
This should be resolved now, sorry for the inconvenience!

**Comment by brandiqa** [comment]
I also can't download. Am getting Error 500. Is there an alternative link?

**Comment by shiftkey** [comment]
@brandiqa not currently. My guess is that it's an intermittent error - can you try again and see if it's still occurring?

**Comment by j-f1** [comment]
That looks like the download page for Now Desktop, not GitHub Desktop.

**Comment by brandiqa** [comment]
My Apologies. Wrong thread

**Comment by revolution01** [comment]
Github desktop installation after download give error of logs .. can't install it .. !

**Comment by shiftkey** [comment]
@revolution01 if this is something you would like us to investigate, please open a new [bug report](https://github.com/desktop/desktop/issues/new?template=bug_report.md) and fill out the provided template.

**Comment by FlyDragon2030** [comment]
I also cannot download github source.
500 internal error is happend.

**Comment by FlyDragon2030** [comment]
Can you help me?

**Comment by shiftkey** [comment]
@FlyDragon2030 there is an availability issue ongoing, please follow along with the details on GitHub Status: https://www.githubstatus.com/incidents/2y6v4ltq26g7
