### ISSUE TITLE
Failed To Launch

### ISSUE THREAD

**Issue by JustIAmBanana** [desktop/desktop#2678]
Error: spawn chcp ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Version: 0.8.1
OS: Windows 6.1.7601

**Comment by shiftkey** [comment]
@JustIAmBanana could you open a command prompt and run this command?

```
> where chcp
```

This should be at `C:\Windows\System32\chcp.com` according to my Win7 VM, and I'd like to figure out what might be different about your setup.

**Comment by joshaber** [comment]
This is fairly popular: https://haystack.githubapp.com/desktop/rollups/43e26f51053292195dde1fe824254c53

**Comment by Sowmiya2992** [comment]
While launching the github desktop i'm getting the below error.

Error: spawn chcp ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Version: 0.8.1
OS: Windows 6.1.7601

**Comment by joshaber** [comment]
@Sowmiya2992 Thanks for letting us know! We're trying to get to the bottom of it.

Could you open a command prompt and run this command?

```
> where chcp
```

What does that print out for you?

**Comment by Sowmiya2992** [comment]
I tried to run the command but it shows me the below message.

'chcp' is not recognized as an internal or external command,
operable program or batch file.

**Comment by gveriello** [comment]
I tried to run Github Desktop and it shows me this message:
Error: spawn chcp ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Version: 0.8.1
OS: Windows 10.0.15063
@joshaber i tried to run the command and it shows me this response: 
Active code table: 850

**Comment by joshaber** [comment]
Thanks @Sowmiya2992 and @gveriello! Is that from running `chcp`?

What if you run `where chcp` instead of just `chcp`?

**Comment by gveriello** [comment]
@joshaber this is the result:

Microsoft Windows [Versione 10.0.15063]
(c) 2017 Microsoft Corporation. Tutti i diritti sono riservati.

C:\Users\gveri>cd C:\Windows\System32

C:\Windows\System32>where chcp
C:\Windows\System32\chcp.com

C:\Windows\System32>

**Comment by shiftkey** [comment]
@gveriello what happens if you run `where chcp` from your home directory? Does it still work there?

**Comment by Sowmiya2992** [comment]
C:\Users\admin>where chcp
'where' is not recognized as an internal or external command,
operable program or batch file.

this is message i'm getting when i try to run the command from my home directory.

**Comment by shiftkey** [comment]
@Sowmiya2992 that's very interesting - maybe `C:\Windows\System32\` isn't on your `PATH` after all. Could you confirm this by running this command in `cmd` and attaching the output?

```
> echo %PATH%
```

@gveriello @JustIAmBanana could you also share what your `PATH` environment variable currently is in `cmd`?

**Comment by Sowmiya2992** [comment]
C:\Users\admin>echo %PATH%
C:\Program Files\Java\jdk1.8.0_45\bin;C:\Maven\apache-maven-3.3.9\bin;C:\Maven\a
pache-maven-3.3.9\bin;C:\Users\admin\AppData\Local\GitHubDesktop\bin

this is the output i'm getting

**Comment by Sowmiya2992** [comment]
After set 'C:\Windows\System32' this path in environment variable it is opening. Thanks for the help @shiftkey

**Comment by shiftkey** [comment]
@Sowmiya2992 thanks for the troubleshooting work. This means #2688 is the right fix, and should go out in the next update after it's been reviewed!

**Comment by Genieliu** [comment]
I got the same error while starting github desktop. 

Error: spawn chcp ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Version: 0.8.1
OS: Windows 6.1.7601

**Comment by shiftkey** [comment]
@Genieliu please confirm you don't have `C:\Windows\System32\` on your `PATH` environment variable - until we get an update published, you should be able to workaround the issue by adding it to your `PATH`.
