### ISSUE TITLE
Client Hangs on Sign In

### ISSUE THREAD

**Issue by danothemen** [desktop/desktop#2769]
### Description
Sign in fails on fresh install. The program appears to freeze after an attempted sign in. Signing in works on the older client.
[Description of the issue]

### Version

**GitHub Desktop version:** 0.9.1

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Download and Install Client
2. Attempt to sign in with correct credentials

![capture](https://user-images.githubusercontent.com/11731011/30567633-8dd18110-9c8e-11e7-88c7-44b01e3a89fb.PNG)

**Expected behavior:** Expected to be taken to main screen and allowed to select a repo

**Actual behavior:** Hung on the screen shown in the attached image

**Reproduces how often:** 100%

### Logs

2017-09-18T22:15:11.515Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--squirrel-firstrun"}

**Comment by shiftkey** [comment]
@danothemen if you leave it alone, does it ever move to the main view? In either case, we should show some sort of indicator that stuff is happening in the background here.

**Comment by shiftkey** [comment]
@danothemen actually, I have further questions:

 - are you signing into GitHub rather than GitHub Enterprise? 
 - are you using your browser to authenticate, or entering credentials within the app?
 - do you have 2FA enabled?

Before signing in, could you press <kbd>Ctrl + Shift + I</kbd> to bring up the dev tools and then try and sign in? If this fails, check the **Console** tab for any error messages, and the **Network** tab for any network requests that fail which we might not handle correctly.

Here's what it looks like on my machine when I get a 2FA challenge, which I then complete and proceed to the **Configure Git** screen:

<img width="812" alt="screen shot 2017-09-19 at 8 59 16 am" src="https://user-images.githubusercontent.com/359239/30568521-f3d97c30-9d18-11e7-9413-77c4022ed5ff.png">

**Comment by danothemen** [comment]
@shiftkey Thanks for looking at this bug. This has been sitting overnight and not changed for me. I am connecting to Github (not enterprise) and entering my credentials in the app. I do not have two factor authentication enabled. Oddly enough as I'm writing this it transitioned to the configure git page (I haven't touched the UI yet). I did just quit and reproduced the bug and am attaching a screencapture of the network tab as requested.
![githubnetworkcapture](https://user-images.githubusercontent.com/11731011/30608854-e03d2d98-9d36-11e7-8919-5d567685b1a3.PNG)

**Comment by lonekorean** [comment]
Same thing happened to me, as described by @danothemen. I'm on Win10, non-enterprise, with 2fa enabled.

Happened twice, then on the third try with the console open... it went through just fine.

**Comment by shiftkey** [comment]
@danothemen @lonekorean thanks for the details! My gut feeling at this point is that there's a subtle race condition in this flow which cause it to not transition to the next view in some cases.

> Happened twice, then on the third try with the console open... it went through just fine.

I'll try and recreate this locally to :fire: this bug, but this seems like a (mediocre) workaround to help you proceed beyond the welcome wizard.

**Comment by shiftkey** [comment]
So I've thrown a bunch of tracing into a release build of the app to try and reproduce this, but the best I've been able to do so far is see it wait for 5 seconds before proceeding:

```
2017-09-21T03:13:52.819Z - info: [ui] --- SignInStore.emitAuthenticate: {"login":"shiftkey-tester", ... , "name":"Brendan's Test Account"}
2017-09-21T03:13:52.819Z - info: [ui] --- SignInStore.emitUpdate: {"kind":3}
2017-09-21T03:13:52.834Z - info: [ui] --- [Welcome] got props: {"kind":3}
2017-09-21T03:13:52.834Z - info: [ui] --- [Welcome] not advancing as kind '2' !== '3'
2017-09-21T03:13:57.510Z - info: [ui] --- [Welcome] got props: {"kind":3}
2017-09-21T03:13:57.511Z - info: [ui] --- [Welcome] advancing to configure Git
```

Now to figure out what the app is doing in those five seconds 🤔

**Comment by ssp0929** [comment]
It seems if you get this bug and sign in, you can force close and skip login on restart; which signs you in to your Github account.

Don't think this is intended.

**Comment by shiftkey** [comment]
Hey all, I've added some tracing to `1.0.4`which was published late last week.

If someone is able to trigger this, please attach a new log file which will have the steps leading up to it, so I can understand how it's getting into this state.

**Comment by gmvi** [comment]
Just installed the desktop client and ran into this bug. I've tried logging in by entering credentials into the app, and by authenticating through a browser. Both attempts failed. BTW I'm logging into github.com, not enterprise. Here's my logfile:
```
2017-10-21T19:25:01.467Z - info: [ui] [AppStore] loading 0 repositories from store
2017-10-21T19:25:01.612Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-21T19:25:01.634Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-21T19:25:01.650Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--squirrel-firstrun"}
2017-10-21T19:25:01.652Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--squirrel-firstrun"}
2017-10-21T19:25:01.662Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-21T19:25:01.675Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)
2017-10-21T19:25:01.699Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-21T19:25:20.604Z - info: [ui] [Welcome] advancing to step: SignInToDotCom
2017-10-21T19:25:20.607Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2017-10-21T19:26:38.046Z - info: [ui] [Welcome] kind Authentication does not match TwoFactorAuthentication. ignoring...
2017-10-21T19:27:02.625Z - info: [ui] [AppStore] adding account gmvi (George Matter) to store
2017-10-21T19:27:02.638Z - info: [ui] [Welcome] kind TwoFactorAuthentication does not match Success. ignoring...
2017-10-21T19:31:21.045Z - info: [ui] [AppStore] loading 0 repositories from store
2017-10-21T19:31:21.047Z - info: [ui] [AppStore] found account: gmvi (George Matter)
2017-10-21T19:31:21.141Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-21T19:31:21.173Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-21T19:31:21.203Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-21T19:31:21.329Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)
2017-10-21T19:31:21.345Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-21T19:31:21.532Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-21T19:31:22.916Z - info: [ui] [Welcome] advancing to step: SignInToDotCom
2017-10-21T19:31:22.919Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2017-10-21T19:31:25.900Z - info: [ui] [SignInStore] initializing OAuth flow
2017-10-21T19:31:30.681Z - info: [ui] [Dispatcher] requesting authenticated user
2017-10-21T19:31:31.281Z - info: [ui] [SignInStore] account resolved
2017-10-21T19:31:31.281Z - info: [ui] [AppStore] adding account gmvi (George Matter) to store
2017-10-21T19:31:31.294Z - info: [ui] [Welcome] kind Authentication does not match Success. ignoring...
```
Right after this, I tried logging in via a browser again, and it went through! Yeah, this smells like a race condition.

**Comment by mattkanwisher** [comment]
Repeated having this happen on windows 10 with 2fa, GitHub desktop version 1.0.9  (Unprocessed entity 422)

**Comment by j-f1** [comment]
Thanks for reporting this @mattkanwisher! Can you open a new issue and fill out the issue template so we can figure out what’s happening?

**Comment by shiftkey** [comment]
> Repeated having this happen on windows 10 with 2fa, GitHub desktop version 1.0.9 (Unprocessed entity 422)

@mattkanwisher @j-f1 yep, this is a different issue to the one originally encountered

**Comment by pcantrell** [comment]
Just encountered this in a fresh-out-of-the-box Windows 10 VM, and this section of the GitHub Desktop log seems relevant:

```
[SignInStore] initializing OAuth flow
install.ts:31 [Welcome] kind Authentication is the same as Authentication. ignoring...
api.github.com/meta:1 Failed to load resource: the server responded with a status of 403 (rate limit exceeded)
install.ts:23 fetchMetadata: unable to load metadata from 'https://api.github.com/meta' as a fallback
Error: API rate limit exceeded for 207.153.15.32. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Ue (C:\Users\paul\AppData\Local\GitHubDesktop\app-2.5.4\webpack:\app\src\lib\http.ts:170:11)
    at C:\Users\paul\AppData\Local\GitHubDesktop\app-2.5.4\webpack:\app\src\lib\api.ts:1136:11
    at Object.endpointSupportsBasicAuth (C:\Users\paul\AppData\Local\GitHubDesktop\app-2.5.4\webpack:\app\src\lib\stores\sign-in-store.ts:317:11)
error @ renderer.js:45
4install.ts:31 [Welcome] kind Authentication is the same as Authentication. ignoring...
```

**Comment by AndreyStille** [comment]
[Welcome] no sign in step found. ignoring...

**Comment by RemingtonHolder** [comment]
I was trying to login and i used Ctrl Shift I to get to the console. When i tired to login to my non-enterprise 2fa'd account I got a post error `http.ts:149: POST https://api.github.com/authorizations 404`
