### ISSUE TITLE
Strange behavior when cloning large repos

### ISSUE THREAD

**Issue by Herrie82** [desktop/desktop#2891]
### Description

When cloning large repos, for example linux kernel repos I always end up with "changed files" locally right after cloning even when there were no changed files locally.

For example: https://github.com/Halium/android_kernel_lge_hammerhead/

I tried to clone this multiple times with each time the same result. 

### Version

**GitHub Desktop version:** [1.0.1]
**OS version:** [Windows 10 Pro, 64 bits]

### Steps to Reproduce

1. Clone: https://github.com/Halium/android_kernel_lge_hammerhead/
2. Wait for it to finish cloning and see right away changed files while nothing was changed locally (I repeatedly had 12 files at my end)

**Expected behavior:** [Correctly cloned repo without pending changes locally]

**Actual behavior:** [Incorrectly cloned repo, with pending changes locally, however now files have been modified locally]

**Reproduces how often:** [100%]

### Logs

As per below, seems it might be caused by API rate limit which kicks in when cloning a large repo. Easiest solution would probably be to increase the API rate limit?

2017-09-23T15:46:39.011Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.446s)
2017-09-23T15:46:39.090Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.010s)
2017-09-23T15:46:39.090Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 1.042s)
2017-09-23T15:46:47.033Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.791s)
2017-09-23T15:47:55.115Z - info: [ui] Executing push: git -c credential.helper= push origin tenderloin/halium-5.1-new:tenderloin/halium-5.1-new --progress (took 7.409s)
2017-09-23T15:47:56.411Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.295s)
2017-09-23T16:24:44.678Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.744s)
2017-09-23T16:24:45.748Z - info: [ui] launching: 1.0.1 (Windows 10.0.15063)
2017-09-23T16:24:46.572Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.102s)
2017-09-23T16:53:18.372Z - info: [ui] Executing clone: git -c credential.helper= lfs clone --recursive --progress --skip-repo --progress -- https://github.com/Herrie82/android_kernel_lge_hammerhead.git C:\Users\hhazendonk\Documents\GitHub\android_kernel_lge_hammerhead (took 1690.966s)
2017-09-23T16:53:37.315Z - info: [ui] Executing getRemotes: git remote -v (took 17.317s)
2017-09-23T16:55:35.903Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 135.927s)
2017-09-23T16:55:36.761Z - info: [ui] Executing isUsingLFS: git lfs track (took 137.852s)
2017-09-23T16:55:36.970Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.067s)
2017-09-23T16:55:38.034Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.262s)
2017-09-23T16:55:40.631Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.877s)
2017-09-23T16:55:41.722Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.091s)
2017-09-23T16:55:42.897Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.040s)
2017-09-23T17:06:39.043Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.245s)
2017-09-23T17:12:06.802Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.154s)
2017-09-23T17:28:29.451Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.017s)
2017-09-23T17:50:19.721Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.021s)
2017-09-23T18:06:42.372Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.033s)
2017-09-23T18:28:33.011Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.241s)
2017-09-23T18:34:00.736Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.053s)
2017-09-23T18:50:23.469Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.053s)
2017-09-23T19:01:18.552Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.018s)
2017-09-23T19:34:03.883Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.028s)
2017-09-23T20:28:40.375Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.709s)
2017-09-23T20:45:03.185Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.001s)
2017-09-23T20:50:30.893Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.041s)
2017-09-23T20:55:59.493Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.837s)
2017-09-23T20:56:00.851Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.361s)
2017-09-23T21:01:29.235Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.537s)
2017-09-23T21:01:30.491Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.258s)
2017-09-23T21:06:58.555Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.303s)
2017-09-23T21:12:26.470Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.146s)
2017-09-23T21:17:54.450Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.209s)
2017-09-23T21:23:22.350Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.127s)
2017-09-23T21:24:54.717Z - warn: [ui] searchForUserWithEmail: not found 'efault@gmx.de'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:24:54.717Z - warn: [ui] searchForUserWithEmail: not found 'david_mccullough@mcafee.com'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:24:54.717Z - warn: [ui] searchForUserWithEmail: not found 'sadas@codeaurora.org'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:24:54.733Z - warn: [ui] searchForUserWithEmail: not found 'tkarra@codeaurora.org'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:24:54.733Z - warn: [ui] searchForUserWithEmail: not found 'ccooper@codeaurora.org'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:24:54.733Z - warn: [ui] searchForUserWithEmail: not found 'a18689@motorola.com'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:24:54.733Z - warn: [ui] searchForUserWithEmail: not found 'ek@google.com'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:24:54.733Z - warn: [ui] searchForUserWithEmail: not found 'a17711@motorola.com'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:24:54.733Z - warn: [ui] searchForUserWithEmail: not found 'ashwin.bhat@broadcom.com'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:24:54.733Z - warn: [ui] searchForUserWithEmail: not found 'lmark@codeaurora.org'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:24:54.733Z - warn: [ui] searchForUserWithEmail: not found 'jcrouse@codeaurora.org'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:24:54.733Z - warn: [ui] searchForUserWithEmail: not found 'heiko.carstens@de.ibm.com'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:24:54.733Z - warn: [ui] searchForUserWithEmail: not found 'viro@zeniv.linux.org.uk'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:25:03.636Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.294s)
2017-09-23T21:25:14.077Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.157s)
2017-09-23T21:25:26.835Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_rateest.h (took 1.002s)
2017-09-23T21:25:26.835Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_mark.h (took 1.060s)
2017-09-23T21:25:26.836Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_mark.h (took 1.086s)
2017-09-23T21:25:27.305Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter_ipv6/ip6t_hl.h (took 1.316s)
2017-09-23T21:25:27.306Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter_ipv4/ipt_ttl.h (took 1.375s)
2017-09-23T21:25:27.306Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_rateest.h (took 1.499s)
2017-09-23T21:25:27.866Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_dscp.c (took 1.702s)
2017-09-23T21:25:27.867Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_hl.c (took 1.572s)
2017-09-23T21:25:27.867Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter_ipv6/ip6t_hl.h (took 1.826s)
2017-09-23T21:25:27.867Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_dscp.c (took 1.774s)
2017-09-23T21:25:27.868Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_hl.c (took 1.666s)
2017-09-23T21:25:27.868Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_dscp.c (took 1.729s)
2017-09-23T21:25:28.388Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_tcpmss.c (took 1.709s)
2017-09-23T21:25:28.389Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_tcpmss.c (took 1.813s)
2017-09-23T21:25:28.389Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_tcpmss.c (took 1.769s)
2017-09-23T21:25:28.390Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_rateest.c (took 1.853s)
2017-09-23T21:25:28.390Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_rateest.c (took 1.886s)
2017-09-23T21:25:28.392Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_rateest.c (took 1.958s)
2017-09-23T21:25:28.392Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_rateest.c (took 1.934s)
2017-09-23T21:25:28.393Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_rateest.c (took 2.006s)
2017-09-23T21:25:28.394Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_hl.c (took 2.047s)
2017-09-23T21:25:28.394Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_hl.c (took 2.146s)
2017-09-23T21:25:28.404Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_connmark.h (took 1.158s)
2017-09-23T21:25:28.404Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_connmark.h (took 1.097s)
2017-09-23T21:25:28.405Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_connmark.h (took 1.273s)
2017-09-23T21:25:28.405Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_connmark.h (took 1.231s)
2017-09-23T21:25:28.405Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_connmark.h (took 1.332s)
2017-09-23T21:25:28.405Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_connmark.h (took 1.391s)
2017-09-23T21:25:28.406Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_connmark.h (took 1.490s)
2017-09-23T21:25:28.406Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_connmark.h (took 1.437s)
2017-09-23T21:25:28.406Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_connmark.h (took 1.526s)
2017-09-23T21:25:28.406Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_tcpmss.c (took 1.569s)
2017-09-23T21:25:28.407Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_tcpmss.c (took 1.627s)
2017-09-23T21:25:28.407Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- net/netfilter/xt_tcpmss.c (took 1.678s)
2017-09-23T21:25:28.410Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_dscp.h (took 1.054s)
2017-09-23T21:25:28.410Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- include/linux/netfilter/xt_dscp.h (took 1.009s)
2017-09-23T21:25:43.076Z - info: [ui] launching: 1.0.1 (Windows 10.0.15063)
2017-09-23T21:25:43.903Z - warn: [ui] searchForUserWithEmail: not found 'dojip.kim@lge.com'
Error: API rate limit exceeded for Herrie82.
    at Object.t.parsedResponse (C:\Users\hhazendonk\AppData\Local\GitHubDesktop\app-1.0.1\webpack:\app\src\lib\http.ts:153:1)
    at <anonymous>
2017-09-23T21:25:52.862Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.212s)
2017-09-23T21:26:00.429Z - info: [ui] Executing checkoutBranch: git checkout --progress cm-12.1-caf -- (took 6.711s)
2017-09-23T21:26:18.211Z - info: [ui] Executing checkoutBranch: git checkout --progress halium-5.1 -- (took 11.873s)
2017-09-23T21:28:47.224Z - info: [ui] launching: 1.0.1 (Windows 10.0.15063)
2017-09-23T21:29:49.764Z - info: [ui] launching: 1.0.1 (Windows 10.0.15063)
2017-09-23T21:44:41.435Z - info: [ui] Executing clone: git -c credential.helper= lfs clone --recursive --progress --skip-repo --progress -- https://github.com/Herrie82/android_kernel_lge_hammerhead.git C:\Users\hhazendonk\Documents\GitHub\android_kernel_lge_hammerhead (took 872.290s)
2017-09-23T21:44:42.811Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.373s)
2017-09-23T21:44:44.683Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.503s)
2017-09-23T21:50:00.041Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.430s)

**Comment by shiftkey** [comment]
@Herrie82 thanks for the report!

This is a very interesting problem, and can be created using vanilla Git. I've tested this on the latest version of Git (2.14.2 as of writing) and after a fresh clone on Mac _and_ Windows this is what a `git status` looks like:

```sh
$ git status
On branch halium-5.1
Your branch is up-to-date with 'origin/halium-5.1'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   include/linux/netfilter/xt_CONNMARK.h
	modified:   include/linux/netfilter/xt_DSCP.h
	modified:   include/linux/netfilter/xt_MARK.h
	modified:   include/linux/netfilter/xt_RATEEST.h
	modified:   include/linux/netfilter/xt_TCPMSS.h
	modified:   include/linux/netfilter_ipv4/ipt_ECN.h
	modified:   include/linux/netfilter_ipv4/ipt_TTL.h
	modified:   include/linux/netfilter_ipv6/ip6t_HL.h
	modified:   net/netfilter/xt_DSCP.c
	modified:   net/netfilter/xt_HL.c
	modified:   net/netfilter/xt_RATEEST.c
	modified:   net/netfilter/xt_TCPMSS.c

no changes added to commit (use "git add" and/or "git commit -a")
```

If you look at this repository on GitHub you'll see two files that differ only by the casing of the file names:

<img width="394" src="https://user-images.githubusercontent.com/359239/30945383-5005375e-a441-11e7-82cc-3bdc1fa92cb6.png">

The root cause of this problem is the underlying filesystem that Git relies on being _case insensitive_. I wrote some more about this over here: https://github.com/desktop/desktop/issues/2672#issuecomment-329011490

We're kind of stuck with this limitation for the foreseeable future. Even APFS (the new filesystem support coming in High Sierra) will default to case insensitive for its volumes.
