### ISSUE TITLE
Development Environment Setup failed

### ISSUE THREAD

**Issue by 709889989** [desktop/desktop#3043]
```
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

E:\源代码\GitHub\desktop>npm install

> undefined postinstall E:\源代码\GitHub\desktop
> cd app && npm install && cd .. && git submodule update --recursive --init && npm run compile:tslint


> runas@3.1.1 install E:\源代码\GitHub\desktop\app\node_modules\runas
> node-gyp rebuild


E:\源代码\GitHub\desktop\app\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\Ming\AppData\Roaming\npm\node_modules\npm\bin\
node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 52.216.130.43:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ming\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\n
ode-gyp.js" "rebuild"
gyp ERR! cwd E:\源代码\GitHub\desktop\app\node_modules\runas
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ming\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v8.1.3
npm ERR! npm  v4.0.1
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\源代码\GitHub\desktop\app\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ming\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v8.1.3
npm ERR! npm  v4.0.1
npm ERR! code ELIFECYCLE
npm ERR! undefined postinstall: `cd app && npm install && cd .. && git submodule update --recursive --init && npm run compile:tslint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the undefined postinstall script 'cd app && npm install && cd .. && git submodule update --recursive --init && npm run compile
:tslint'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd app && npm install && cd .. && git submodule update --recursive --init && npm run compile:tslint
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\源代码\GitHub\desktop\npm-debug.log
```

[log file](https://github.com/709889989/publicFile/blob/master/npm-debug.log)

**Comment by joshaber** [comment]
The log file link isn't working for me 😞 Just from guessing, it looks like it's not able to download some dependency.

**Comment by 709889989** [comment]
[try this !](https://github.com/709889989/publicFile/blob/master/npm-debug.log)

**Comment by shiftkey** [comment]
@709889989 can you update to a more recent version of npm?

```
2 info using npm@4.0.1
```

This is the version we're currently using on our CI environments:

```
$ npm install -g npm@4.6.1
```

**Comment by shiftkey** [comment]
Closing this out because we've migrated over to `yarn` as of #2864.

Please review the [setup guide](https://github.com/desktop/desktop/blob/master/docs/contributing/setup.md) and confirm you have the right set of dependencies.
