### ISSUE TITLE
Unable to push, because "explorer.exe: no such file or directory"

### ISSUE THREAD

**Issue by ragoston** [desktop/desktop#3208]
Trying to push, but after file explorer pops up I get the message described in the title and pushing takes literally forever even if I just pushed a single line of txt file. 
![boi](https://user-images.githubusercontent.com/32418241/32234127-4d76830a-be5c-11e7-9fe0-100afa9de126.jpg)

**Comment by shiftkey** [comment]
@ragoston thanks for the report!

Could you walk me through the steps you made to trigger this issue, and if there are any repository hooks under the `.git/hooks/` folder?

Could you also attach the log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Lastly, is this repository public? This might help reproduce the issue quicker on my end.

**Comment by ragoston** [comment]
Thank you for getting back to me. 
![hooks](https://user-images.githubusercontent.com/32418241/32271452-34140128-befa-11e7-8d53-6a69e6d97b7b.jpg)
This is what I have in the `.git/hooks/` folder. 
The repo is not public (for this homework assignment we required to leave it as it is )
The steps were: 

- In the app, I selected "clone repo" and selected a location in my "Documents" folder. The path had no special characters (only english alphabet letters)
- The cloning went all right. After that I opened the cloned repo in Android Studio and added a `.txt` file to it to try out commiting.
- The app noted I have a new file. I selected it for commit, and made that commit, it was successful. 
- After that I clicked `repo > push` and the issue happened. 
I tried this many times, with the same unfortunate result. 

I'm entering the log message here with some translation as it's in hungarian (and non-ASCII characters were replaced by some wingdings anyway)

> 2017-10-31T12:46:27.687Z - info: [ui] [AppStore] loading 0 repositories from store
2017-10-31T12:46:29.102Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-31T12:46:29.111Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-31T12:46:29.204Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-31T12:46:29.255Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--squirrel-firstrun"}
2017-10-31T12:46:29.258Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-31T12:46:29.343Z - info: [ui] launching: 1.0.6 (Windows 10.0.14393)
2017-10-31T12:46:29.399Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-31T12:46:31.602Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Exception: Couldn't acquire lock, is another instance running
   on the following place: Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   on the following place: Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   on the following place: System.Threading.Tasks.Task`1.InnerInvoke()
   on the following place: System.Threading.Tasks.Task.Execute()
--- End-of-stack tracing from the exception's prior occurrence ---
   on the following place: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   on the following place: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   on the following place: Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End-of-stack tracing from the exception's prior occurrence  ---
   on the following place: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  on the following place:System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   a on the following place: Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- End of internal stack extraction ---
   on the following place: System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   a on the following place: System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   on the following place: System.Threading.Tasks.Task`1.get_Result()
   on the following place: Squirrel.Update.Program.executeCommandLine(String[] args)
   on the following place: Squirrel.Update.Program.main(String[] args)
   on the following place: Squirrel.Update.Program.Main(String[] args)
---> (0 th internal exception) System.Exception: Couldn't acquire lock, is another instance running
   on the following place: Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   on the following place: Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   on the following place: System.Threading.Tasks.Task`1.InnerInvoke()
   on the following place: System.Threading.Tasks.Task.Execute()
---End-of-stack tracing from the exception's prior occurrence---
   on the following place: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   on the following place: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   on the following place: Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End-of-stack tracing from the exception's prior occurrence ---
   on the following place: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   on the following place: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   on the following place: Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---


    at AutoUpdater.emitError (C:\Users\agoston\AppData\Local\GitHubDesktop\app-1.0.6\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:58:24)
    at squirrelUpdate.checkForUpdate (C:\Users\agoston\AppData\Local\GitHubDesktop\app-1.0.6\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:34:21)
    at C:\Users\agoston\AppData\Local\GitHubDesktop\app-1.0.6\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:89:14
    at ChildProcess.<anonymous> (C:\Users\agoston\AppData\Local\GitHubDesktop\app-1.0.6\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:71:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
2017-10-31T12:46:31.780Z - info: [ui] [Welcome] advancing to step: SignInToDotCom
2017-10-31T12:46:31.787Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2017-10-31T12:47:05.628Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2017-10-31T12:47:07.320Z - info: [ui] [AppStore] adding account ragoston (null) to store
2017-10-31T12:47:07.329Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2017-10-31T12:47:07.417Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-31T12:47:25.778Z - info: [ui] [Welcome] advancing to step: UsageOptOut
2017-10-31T12:47:31.698Z - info: [ui] Opt out reported.
2017-10-31T14:18:38.192Z - info: [ui] [AppStore] loading 0 repositories from store
2017-10-31T14:18:38.195Z - info: [ui] [AppStore] found account: ragoston (null)
2017-10-31T14:18:39.595Z - info: [ui] launching: 1.0.6 (Windows 10.0.14393)
2017-10-31T14:23:18.227Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/adakiss/android.git - ragoston (has token)
2017-10-31T14:23:22.103Z - info: [ui] Executing clone: git -c credential.helper= lfs clone --recursive --skip-repo --progress -- https://github.com/adakiss/android.git C:\Users\agoston\Documents\GitHub\android (took 3.843s)
2017-10-31T14:23:22.164Z - info: [ui] [AppStore] adding repository at C:\Users\agoston\Documents\GitHub\android to store
2017-10-31T14:25:01.913Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: android - ragoston (has token)
2017-10-31T14:28:08.097Z - info: [ui] [AppStore] loading 1 repositories from store
2017-10-31T14:28:08.100Z - info: [ui] [AppStore] found account: ragoston (null)
2017-10-31T14:28:09.756Z - info: [ui] launching: 1.0.6 (Windows 10.0.14393)
2017-10-31T14:28:14.814Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: android - ragoston (has token)
2017-10-31T14:36:33.583Z - info: [ui] [AppStore] loading 1 repositories from store
2017-10-31T14:36:33.586Z - info: [ui] [AppStore] found account: ragoston (null)
2017-10-31T14:36:35.311Z - info: [ui] launching: 1.0.6 (Windows 10.0.14393)
2017-10-31T14:37:00.826Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: android - ragoston (has token)
2017-10-31T14:41:38.051Z - info: [ui] [AppStore] loading 1 repositories from store
2017-10-31T14:41:38.055Z - info: [ui] [AppStore] found account: ragoston (null)
2017-10-31T14:41:40.009Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--squirrel-firstrun"}
2017-10-31T14:41:40.395Z - info: [ui] launching: 1.0.6 (Windows 10.0.14393)
2017-10-31T14:41:56.480Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: android - ragoston (has token)
2017-10-31T14:55:09.279Z - info: [ui] [AppStore] loading 1 repositories from store
2017-10-31T14:55:09.284Z - info: [ui] [AppStore] found account: ragoston (null)
2017-10-31T14:55:11.076Z - info: [ui] launching: 1.0.6 (Windows 10.0.14393)
2017-10-31T14:57:29.453Z - warn: [ui] fetchRepository: 'master/Timetable2' returned a 404
2017-10-31T14:57:29.622Z - warn: [ui] fetchRepository: 'master/Timetable2' returned a 404
2017-10-31T14:57:29.625Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'https://github.com/adakiss/android/tree/master/Timetable2'
2017-10-31T14:57:30.744Z - info: [ui] Executing clone: git -c credential.helper= lfs clone --recursive --skip-repo --progress -- https://github.com/adakiss/android/tree/master/Timetable2 C:\Users\agoston\Documents\GitHub\Timetable2 (took 1.081s)
2017-10-31T14:57:30.745Z - error: [ui] `git -c credential.helper= lfs clone --recursive --skip-repo --progress -- https://github.com/adakiss/android/tree/master/Timetable2 C:\Users\agoston\Documents\GitHub\Timetable2` exited with an unexpected code: 2.
Cloning into 'C:\Users\agoston\Documents\GitHub\Timetable2'...
remote: Not Found
fatal: repository 'https://github.com/adakiss/android/tree/master/Timetable2/' not found
Error(s) during clone:
git clone failed: exit status 128

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2017-10-31T14:57:46.780Z - info: [ui] storing generic credentials for 'github.com/adakiss/android/tree' and 'ragoston'
2017-10-31T14:57:46.794Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'github.com/adakiss/android/tree' and 'ragoston'
2017-10-31T14:57:47.752Z - error: [ui] `git -c credential.helper= lfs clone --recursive --skip-repo --progress -- https://github.com/adakiss/android/tree/master/Timetable2 C:\Users\agoston\Documents\GitHub\Timetable2` exited with an unexpected code: 2.
Cloning into 'C:\Users\agoston\Documents\GitHub\Timetable2'...
remote: Not Found
fatal: repository 'https://github.com/adakiss/android/tree/master/Timetable2/' not found
Error(s) during clone:
git clone failed: exit status 128

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2017-10-31T14:58:18.140Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/adakiss/android.git - ragoston (has token)
2017-10-31T14:58:21.794Z - info: [ui] Executing clone: git -c credential.helper= lfs clone --recursive --skip-repo --progress -- https://github.com/adakiss/android.git C:\Users\agoston\Documents\GitHub\android (took 3.659s)
2017-10-31T14:58:21.885Z - info: [ui] [AppStore] adding repository at C:\Users\agoston\Documents\GitHub\android to store
2017-10-31T15:05:34.610Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: android - ragoston (has token)
2017-10-31T15:05:35.947Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.326s)
2017-10-31T15:07:41.031Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/adakiss/android.git - ragoston (has token)
2017-10-31T15:07:44.555Z - info: [ui] Executing clone: git -c credential.helper= lfs clone --recursive --skip-repo --progress -- https://github.com/adakiss/android.git C:\Users\agoston\Documents\GitHub\android (took 3.517s)
2017-10-31T15:07:44.624Z - info: [ui] [AppStore] adding repository at C:\Users\agoston\Documents\GitHub\android to store
2017-10-31T15:16:09.274Z - info: [ui] [AppStore] loading 1 repositories from store
2017-10-31T15:16:09.278Z - info: [ui] [AppStore] found account: ragoston (null)
2017-10-31T15:16:11.554Z - info: [ui] launching: 1.0.6 (Windows 10.0.14393)
2017-10-31T15:18:19.403Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: android - ragoston (has token)
2017-10-31T15:23:12.496Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.023s)
2017-10-31T15:23:12.611Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 1.069s)

**Comment by niik** [comment]
Hey @ragoston, that log excerpt doesn't seem to include the actual push command. Could you have a look again and see if there's any other log files in that directory? If there isn't could you please try to reproduce the problem again, close the app and attach the latest log file?

**Comment by ragoston** [comment]
I successfully reproduced the issue with this log file created:

> 2017-11-01T10:53:35.711Z - info: [ui] [AppStore] loading 1 repositories from store
2017-11-01T10:53:35.715Z - info: [ui] [AppStore] found account: ragoston (null)
2017-11-01T10:53:35.930Z - error: [ui] `git status --untracked-files=all --branch --porcelain=2 -z` exited with an unexpected code: 128.
fatal: Not a git repository (or any of the parent directories): .git

(The error was parsed as 27: This is not a git repository.)
2017-11-01T10:53:35.970Z - error: [ui] `git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes` exited with an unexpected code: 128.
fatal: Not a git repository (or any of the parent directories): .git

(The error was parsed as 27: This is not a git repository.)
2017-11-01T10:53:36.145Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
fatal: Not a git repository (or any of the parent directories): .git

(The error was parsed as 27: This is not a git repository.)
2017-11-01T10:53:37.632Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--squirrel-firstrun"}
2017-11-01T10:53:37.972Z - info: [ui] launching: 1.0.6 (Windows 10.0.14393)
2017-11-01T13:13:56.699Z - info: [ui] [AppStore] loading 1 repositories from store
2017-11-01T13:13:56.703Z - info: [ui] [AppStore] found account: ragoston (null)
2017-11-01T13:13:58.453Z - info: [ui] launching: 1.0.6 (Windows 10.0.14393)
2017-11-01T13:14:44.214Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/ragoston/UnityDecompiled.git - ragoston (has token)
2017-11-01T13:15:21.480Z - info: [ui] Executing clone: git -c credential.helper= lfs clone --recursive --skip-repo --progress -- https://github.com/ragoston/UnityDecompiled.git C:\Users\agoston\Documents\GitHub\UnityDecompiled (took 37.218s)
2017-11-01T13:15:21.572Z - info: [ui] [AppStore] adding repository at C:\Users\agoston\Documents\GitHub\UnityDecompiled to store
2017-11-01T13:15:22.735Z - info: [ui] Executing isUsingLFS: git lfs track (took 1.130s)
2017-11-01T13:15:24.878Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.216s)
2017-11-01T13:15:49.294Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: UnityDecompiled - ragoston (has token)

**Comment by shiftkey** [comment]
@ragoston out of curiosity, do either of the repositories you've encountered the problem with have hooks defined under `.git/hooks`? Maybe there's some code that's running as part of pushing that is being displayed as part of the `push` progress...

**Comment by ragoston** [comment]
@shiftkey Sorry for the delay in response. 
The first I have seen the error with (our school project), I already posted a screenshot of the `.git/hooks` folder. The other one, Unity decompiled has no such folder, not even on the cloned repo on my machine. 
Did I misunderstand the question?

**Comment by shiftkey** [comment]
@ragoston apologies, I totally forgot that I'd asked you the same question last week.

Let's try a manual push and see if that does anything interesting. I'm assuming you have [Git for Windows](https://git-for-windows.github.io/) installed - if you don't, could you do that first?

Then open a **Command Prompt** to this repository, run these steps and attach the output here:

```
cd [path to android repo]
git --version
set GIT_TRACE=1
set GIT_CURL_VERBOSE=1
git push origin master --progress
```

You might be prompted for credentials, because this is occurring outside GitHub Desktop.

**Comment by ragoston** [comment]
It was a successful push. No error, nothing interesting. I made a `.txt` file named "asd" in the master (added by explorer) and the desktop app detected it. Then commit successful. Then opened git bash on the explorer folder of the repo on my disk, typed what you wrote me to type, 1-2 secs of waiting and success :/

**Comment by shiftkey** [comment]
@ragoston could you attach the output from the successful push?

Another thing that maybe we've overlooked - configuration. **From within the repository,** could you run this command and attach the output here:

```
$ git config -l --show-origin
```

I'm still trying to figure out where this message is coming from, and I'm running out of places it might be lurking...

**Comment by joshaber** [comment]
Whoops, looks like our bot got a little too aggressive. Re-opening.

**Comment by ragoston** [comment]
Thank you for reminding me gently anyway :D I go and give you the output in
a moment.

2017-11-14 17:42 GMT+01:00 Josh Abernathy <notifications@github.com>:

**Comment by JakubSteplowski** [comment]
I have the same issue since the latest update.
It happens with all my repos.
I pushed about 1.500 commits without any problem, until yesterday, now it shows me this error message.

Can't find anything in the logs.
I hope @ragoston will be more lucky and will find the reason.

**Comment by ragoston** [comment]
> file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"D:\\Applications\\Git\\mingw64/etc/gitconfig"     http.sslcainfo=D:/Applications/Git/mingw64/ssl/certs/ca-bundle.crt
file:"D:\\Applications\\Git\\mingw64/etc/gitconfig"     http.sslbackend=openssl
file:"D:\\Applications\\Git\\mingw64/etc/gitconfig"     diff.astextplain.textconv=astextplain
file:"D:\\Applications\\Git\\mingw64/etc/gitconfig"     filter.lfs.clean=git-lfs clean -- %f
file:"D:\\Applications\\Git\\mingw64/etc/gitconfig"     filter.lfs.smudge=git-lfs smudge -- %f
file:"D:\\Applications\\Git\\mingw64/etc/gitconfig"     filter.lfs.process=git-lfs filter-process
file:"D:\\Applications\\Git\\mingw64/etc/gitconfig"     filter.lfs.required=true
file:"D:\\Applications\\Git\\mingw64/etc/gitconfig"     credential.helper=manager
file:C:/Users/agoston/.gitconfig        user.name=<my name alright>
file:C:/Users/agoston/.gitconfig        user.email=<my email adress alirght>
file:C:/Users/agoston/.gitconfig        core.autocrlf=true
file:C:/Users/agoston/.gitconfig        core.excludesfile=
file:C:/Users/agoston/.gitconfig        filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/agoston/.gitconfig        filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/agoston/.gitconfig        filter.lfs.process=git-lfs filter-process
file:C:/Users/agoston/.gitconfig        filter.lfs.required=true
file:C:/Users/agoston/.gitconfig        gui.recentrepo=C:/Users/agoston/Documents/GitHub/android
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        submodule.active=.
file:.git/config        remote.origin.url=https://github.com/ragoston/UnityDecompiled.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
file:.git/config        remote.upstream.url=https://github.com/MattRix/UnityDecompiled.git
file:.git/config        remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*

**Comment by ragoston** [comment]
Note, name and email addresses are the alright, I just deleted them before pasting here. 
By the way did I get the config of the right folder? Right click to master > Git BASH here, then do the magic.

**Comment by thelazylion** [comment]
Any solution to this nonsense or should our team switch to perforce? None of the github repos are working anymore thanks to this error.

**Comment by JakubSteplowski** [comment]
I solved this problem by reinstalling Git and GitHub and adding to it again the local reposistories.

**Comment by shiftkey** [comment]
@JakubSteplowski I'm glad you were able to workaround the issue - which version of Git and GitHub Desktop are you now running that seem to work for you?

@thelazylion I'm still trying to figure out the source of this error - the best lead so far is [these mentions of `explorer.exe` in dependencies used by Git LFS](https://github.com/git-lfs/git-lfs/search?utf8=%E2%9C%93&q=explorer.exe&type=), but how I understand it's being used here (looking at the process tree for `explorer.exe`) doesn't match up with the error (`find` is probably the unix find command, which is for searching the file system).

So, I have a few questions about your setup to help try and recreate this on my end:

 - which version of Desktop are you running? And is it on macOS or Windows?
 - are you using Git LFS in any of these problem repositories? `git lfs track` is the quickest way to test this
 - are you able to push from the command line? If so, which version of Git do you have installed (this will probably be different to the version embedded with Desktop)?

**Comment by JakubSteplowski** [comment]
@shiftkey GitHub Desktop 1.0.9 and Git 2.15.0.
They are the same versions I had before, but somehow by reinstalling them, the problem vanished.

**Comment by shiftkey** [comment]
Closing due to inactivity. @thelazylion if you're able to answer those questions above I'm happy to reopen this and see if I can recreate the issue on my end.

**Comment by Mrkvozrout** [comment]
@shiftkey I also have this problem. Update of git (to 2.15.1.windows.2) and reinstall of GitHub Desktop (to 1.0.10) did not help. Also I do not have LFS.

**Comment by shiftkey** [comment]
@Mrkvozrout please open a fresh issue and fill out the required details - if this looks like the same issue and I can reproduce it on my end I'm going to be so happy!

**Comment by shiftkey** [comment]
For others who stumble onto this issue, check that some malware hasn't been installed to hijack `cmd.exe` - which Git launches as part of invoking `GIT_ASKPASS`. See https://github.com/desktop/desktop/issues/3604#issuecomment-352192406 for some more context (and a link out to cleaning this up).
