### ISSUE TITLE
New update to 1.0.7 crashes on Win10

### ISSUE THREAD

**Issue by nivanmorgan** [desktop/desktop#3270]
I got a notification to update my Github desktop yesterday and after  I updated it crashes every time I open it. This is the error I get

Error: Mode github-diff-syntax failed to advance stream.
    at at (app\node_modules\codemirror\lib\codemirror.js:1639:1)
    at dt (app\node_modules\codemirror\lib\codemirror.js:1693:1)
    at tt (app\node_modules\codemirror\lib\codemirror.js:1539:1)
    at C:\Users\Owner\AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:4063:24
    at Jr.iterN (app\node_modules\codemirror\lib\codemirror.js:5539:8)
    at Bs.iterN (app\node_modules\codemirror\lib\codemirror.js:5651:41)
    at Bs.iter (app\node_modules\codemirror\lib\codemirror.js:6047:14)
    at Do (app\node_modules\codemirror\lib\codemirror.js:4058:1)
    at C:\Users\Owner\AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:148:21

Version: 1.0.7
OS: Windows 10.0.16299

**Comment by strafe** [comment]
See #3249 and @niik's [comment](https://github.com/desktop/desktop/issues/3249#issuecomment-342735764) on how to upgrade if you're stuck.

**Comment by nivanmorgan** [comment]
@strafe  thanks

**Comment by povargek** [comment]
+ same

**Comment by joshaber** [comment]
This has been fixed in 1.0.8. As @strafe noted, see #3249 and @niik's [comment](https://github.com/desktop/desktop/issues/3249#issuecomment-342735764) on how to upgrade if you're stuck.
