### ISSUE TITLE
Catastrophic error with new version

### ISSUE THREAD

**Issue by lom-chargebacks** [desktop/desktop#3274]
Error: Mode github-diff-syntax failed to advance stream.
    at at (app\node_modules\codemirror\lib\codemirror.js:1639:1)
    at dt (app\node_modules\codemirror\lib\codemirror.js:1693:1)
    at tt (app\node_modules\codemirror\lib\codemirror.js:1539:1)
    at \AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:4063:24
    at Jr.iterN (app\node_modules\codemirror\lib\codemirror.js:5539:8)
    at Bs.iterN (app\node_modules\codemirror\lib\codemirror.js:5651:41)
    at Bs.iter (app\node_modules\codemirror\lib\codemirror.js:6047:14)
    at Do (app\node_modules\codemirror\lib\codemirror.js:4058:1)
    at \AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:148:21

Version: 1.0.7
OS: Windows 10.0.15063

**Comment by strafe** [comment]
See #3249 and @niik's [comment](https://github.com/desktop/desktop/issues/3249#issuecomment-342735764) on how to upgrade if you're stuck.

**Comment by lom-chargebacks** [comment]
https://github.com/desktop/desktop/issues/3249#issuecomment-342735764 - Downloading and reinstalling the app fixed the issue.
