### ISSUE TITLE
Invalid string length

### ISSUE THREAD

**Issue by GewoonJaap** [desktop/desktop#3566]
RangeError: Invalid string length
    at Socket.onChildStdout (child_process.js:273:13)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

Version: 1.0.10
OS: Windows 10.0.15063

**Comment by shiftkey** [comment]
@GewoonJaap Can you tell me about the steps to reproduce this issue?

**Comment by shiftkey** [comment]
Closing this out as inactive. @GewoonJaap if you can provide some reproduction steps I'm happy to revisit this issue.
