### ISSUE TITLE
GithubDesktop Installation Error

### ISSUE THREAD

**Issue by Azurues24** [desktop/desktop#3637]
### Description

Installation Error of GitHubDesktop

### Version

**GitHub Desktop version:** [the most recent version found on download page]

**OS version:** [Microsoft Windows [Version 10.0.16299.19]]

**Expected behavior:** [to install]

**Actual behavior:** [error shows up]

**Reproduces how often:** [every time I run the installer]

<a href='https://postimages.org/' target='_blank'><img src='https://s33.postimg.org/9nfnqr1pb/Capture1.png' border='0' alt='Capture1'/></a>

**Comment by shiftkey** [comment]
@Azurues24 could you attach the contents of the setup log file? Also, are you running 32-bit or 64-bit Windows?

**Comment by Azurues24** [comment]
[SquirrelSetup.log](https://github.com/desktop/desktop/files/1571100/SquirrelSetup.log)

And also, I have this folder and whenever I try to access that folder it prompts me this dialog.

<a href='https://postimages.org/' target='_blank'><img src='https://s31.postimg.org/40mq22k1n/Capture2.png' border='0' alt='Capture2'/></a>

**Comment by shiftkey** [comment]
@Azurues24 thanks for the log!

```
2017-12-19 15:31:05> Program: Install path C:\Users\~USERNAME~\AppData\Local\GitHubDesktop already exists, burning it to the ground
2017-12-19 15:31:05> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: The file or directory is corrupted and unreadable.
```

Yeah, I'm not really sure what to do here. Try restarting Windows and clearing the `%LOCALAPPDATA%\GitHubDesktop` directory so you're starting from a clean slate before running the installer again...

**Comment by Azurues24** [comment]
@shiftkey Thanks for responding man. I really appreciate it while I'm trying to solve the problem myself.
I think reformat will do the work. I can't  clear GitHubDesktop folder.  I took ownership of it and try to delete the folder via terminal and even using application that is intended in force deleting an undeleted folder. I also tried installation via chocolatey. same result. 

The only solution so far is via explorer, the 600+kb installer version 3.3.4.0. I dont know if this is a legit one but this is all I can have.

**Comment by shiftkey** [comment]
> The only solution so far is via explorer, the 600+kb installer version 3.3.4.0. 

That sounds like the classic Desktop app - these can be installed side-by-side, but we're no longer actively working on the classic version.

**Comment by shiftkey** [comment]
Closing this out as external. The `System.IO.IOException: The file or directory is corrupted and unreadable.` suggests the filesystem we rely on under `%LOCALAPPDATA%\GitHubDesktop` cannot be trusted in it's current state, and the installer failing fast is the best we can do in this situation.

**Comment by tuseroni** [comment]
i am also having this problem, in my case i attempted to install, i got the installer, it asked for my login, i couldn't remember it so i closed the installer to go try and find it, when i ran it again it gave me that same error. my guess is that it made an incomplete install, it's installed enough that the installer won't run but not installed enough to run.

**Comment by tierninho** [comment]
@tuseroni can you try deleting `~/Library/Application Support/GitHub Desktop/` and reinstalling to see if that helps with this issue?

**Comment by tuseroni** [comment]
i do not have that folder, i do have a folder AppData\Local\GitHubDesktop but i cannot delete that folder (says it's in use) there was one in AppData\roaming too for some reason and i was able to delete that one fine (did not fix the issue)

**Comment by tierninho** [comment]
Thanks for the update. `AppData\Local\GitHubDesktop` should be deleted. Is Desktop still running? Please quit the application, restart the computer, and retry deleting. Keep us posted.

**Comment by andrenovado** [comment]
Hi, I experienced the same problem. I have just learned using github, and tried installing its desktop app. But it fails every time I try to install it. I have tried to look for solution on google, but couldn't find any. I have tried restarting my laptop and deleting the AppData\Local\GitHubDesktop folder before retrying installing it, and the result is always the same. Can anyone help me? Here I attached the log.
[SquirrelSetup.log](https://github.com/desktop/desktop/files/4123727/SquirrelSetup.log)

**Comment by tierninho** [comment]
@andrenovado Thanks for letting us know about the downloading issue and welcome to Desktop!! Curious if you are running a 32-bit operating system? I spotted the following error:

> Novado\AppData\Local\GitHubDesktop\app-2.2.4\GitHubDesktop.exe: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.

Unfortunately, Desktop only works with 64-bit operating systems.

**Comment by ASMFahim71** [comment]
having problem to install git desktop!
im using 64bit
setup log
[SquirrelSetup.log](https://github.com/desktop/desktop/files/4628818/SquirrelSetup.log)

**Comment by steveward** [comment]
@ASMFahim71 here's the error I'm seeing in the log file:

```
2020-05-14 19:50:45> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Invalid XML in file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config' near element ''. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0xC00CE556
 ```

I've seen this error once before and we were able to resolve it by running the [.NET Framework Repair Tool](https://www.microsoft.com/en-us/download/details.aspx?id=30135). Try doing that and if it doesn't get things working please open up a new issue.

**Comment by SirapopChu** [comment]
@steveward I have reinstall a .NET Framework but i also got the same problem

[SquirrelSetup.log](https://github.com/desktop/desktop/files/6325853/SquirrelSetup.log)

**Comment by SUM-SuporteUnionMundial** [comment]
infelismente o erro persiste.

**Comment by anjali012005** [comment]
2024-12-22 17.00.01> Program: Starting Squirrel Updater: --install .
2024-12-22 17.00.01> Program: Starting install, writing to C:\Users\ANJALI\AppData\Local\SquirrelTemp
2024-12-22 17.00.01> Program: About to install to: C:\Users\ANJALI\AppData\Local\insomnia
2024-12-22 17.00.01> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ANJALI\AppData\Local\insomnia\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2024-12-22 17.00.01> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ANJALI\AppData\Local\insomnia\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2024-12-22 17.00.01> CheckForUpdateImpl: Reading RELEASES file from C:\Users\ANJALI\AppData\Local\SquirrelTemp
2024-12-22 17.00.01> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2024-12-22 17.00.04> ApplyReleasesImpl: Writing files to app directory: C:\Users\ANJALI\AppData\Local\insomnia\app-10.3.0
2024-12-22 17.00.11> LogHost: Rigging execution stub for Insomnia_ExecutionStub.exe to C:\Users\ANJALI\AppData\Local\insomnia\Insomnia.exe
2024-12-22 17.00.15> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\ANJALI\AppData\Local\insomnia\app-10.3.0\Insomnia.exe]
2024-12-22 17.00.18> ApplyReleasesImpl: Starting fixPinnedExecutables
2024-12-22 17.00.18> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2024-12-22 17.00.18> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2024-12-22 17.00.19> ApplyReleasesImpl: Examining Pin: Microsoft Edge.lnk
2024-12-22 17.00.19> ApplyReleasesImpl: Fixing up tray icons
2024-12-22 17.00.19> ApplyReleasesImpl: cleanDeadVersions: for version 10.3.0
2024-12-22 17.00.19> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-10.3.0
  can anyone help please ?

**Comment by SirapopChu** [comment]
Ask ChatGPT or Claude will get right answer

ในวันที่ พ. 8 ม.ค. 2025 00:08 ANJALI DAHARWAL ***@***.***>
เขียนว่า:
