### ISSUE TITLE
Commits from individuals show up as organization

### ISSUE THREAD

**Issue by justinjett** [desktop/desktop#3939]
### Description

In GitHub Desktop, when I make a commit, it doesn't show up as justinjett as the author, instead it shows plixer (the name of the organization). 

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Microsoft Windows [Version 10.0.16299.192]

### Steps to Reproduce

1. Make a change to a respository
2. commit change to repository in GitHub Desktop while logged in as individual user
3. Review the commit in GitHub and see the organization not the user. 

**Expected behavior:** Author that pushed commit should be shows

**Actual behavior:** Organization is shown

**Reproduces how often:** 100%

### Logs

2018-02-05T21:15:48.270Z - info: [ui] [AppStore] loading 1 repositories from store
2018-02-05T21:15:48.272Z - info: [ui] [AppStore] found account: plixer (Plixer)
2018-02-05T21:15:49.428Z - info: [ui] launching: 1.0.13 (Windows 10.0.16299)
2018-02-05T21:15:49.428Z - info: [ui] execPath: 'C:\Users\JUSTINJ\AppData\Local\GitHubDesktop\app-1.0.13\GitHubDesktop.exe'
2018-02-05T21:15:49.914Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\JUSTINJ\AppData\Local\GitHubDesktop\app-1.0.13\webpack:\app\src\lib\http.ts:162:1)
    at <anonymous>
2018-02-05T21:15:49.915Z - warn: [ui] fetchUser: failed with endpoint https://api.github.com
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\JUSTINJ\AppData\Local\GitHubDesktop\app-1.0.13\webpack:\app\src\lib\http.ts:162:1)
    at <anonymous>
2018-02-05T21:15:49.915Z - warn: [ui] Error refreshing account 'plixer'
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\JUSTINJ\AppData\Local\GitHubDesktop\app-1.0.13\webpack:\app\src\lib\http.ts:162:1)
    at <anonymous>
2018-02-05T21:15:49.917Z - info: [ui] Stats reported.
2018-02-05T21:15:59.348Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 10.849s)
2018-02-05T21:15:59.679Z - warn: [ui] fetchIssues: failed for repository plixer/scrutinizer
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\JUSTINJ\AppData\Local\GitHubDesktop\app-1.0.13\webpack:\app\src\lib\http.ts:162:1)
    at <anonymous>
2018-02-05T21:15:59.680Z - warn: [ui] Unable to fetch issues for plixer/scrutinizer
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\JUSTINJ\AppData\Local\GitHubDesktop\app-1.0.13\webpack:\app\src\lib\http.ts:162:1)
    at <anonymous>
2018-02-05T21:16:00.905Z - warn: [ui] fetchMentionables: failed for plixer/scrutinizer
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\JUSTINJ\AppData\Local\GitHubDesktop\app-1.0.13\webpack:\app\src\lib\http.ts:162:1)
    at <anonymous>
2018-02-05T21:16:00.962Z - warn: [ui] fetchPullRequests: failed for repository plixer/scrutinizer
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\JUSTINJ\AppData\Local\GitHubDesktop\app-1.0.13\webpack:\app\src\lib\http.ts:162:1)
    at <anonymous>
2018-02-05T21:16:00.962Z - warn: [ui] Error refreshing pull requests for 'scrutinizer'
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\JUSTINJ\AppData\Local\GitHubDesktop\app-1.0.13\webpack:\app\src\lib\http.ts:162:1)
    at <anonymous>
2018-02-05T21:16:01.111Z - warn: [ui] fetchRepository: an error occurred for 'plixer/scrutinizer'
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\JUSTINJ\AppData\Local\GitHubDesktop\app-1.0.13\webpack:\app\src\lib\http.ts:162:1)
    at <anonymous>
2018-02-05T21:16:04.280Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.392s)
2018-02-05T21:16:04.281Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
'\\shares\Marketing\Website Management\GitHub\scrutinizer'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
'\\shares\Marketing\Website Management\GitHub\scrutinizer'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/plixer/scrutinizer.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.)
2018-02-05T21:16:08.401Z - info: [ui] [AppStore] removing account plixer (Plixer) from store
2018-02-05T21:16:18.193Z - info: [ui] [AppStore] adding account justinjett (justinjett) to store
2018-02-05T21:16:21.949Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: scrutinizer - justinjett (has token)
2018-02-05T21:16:29.370Z - info: [ui] Executing pull: git -c credential.helper= pull --no-rebase --progress origin (took 7.149s)
2018-02-05T21:26:01.209Z - warn: [ui] fetchPullRequests: failed for repository plixer/scrutinizer
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\JUSTINJ\AppData\Local\GitHubDesktop\app-1.0.13\webpack:\app\src\lib\http.ts:162:1)
    at <anonymous>
2018-02-05T21:26:01.210Z - warn: [ui] Error refreshing pull requests for 'scrutinizer'
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\JUSTINJ\AppData\Local\GitHubDesktop\app-1.0.13\webpack:\app\src\lib\http.ts:162:1)
    at <anonymous>
2018-02-05T21:40:14.650Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.128s)
2018-02-05T21:40:54.868Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/plixer/scrutinizer.git - justinjett (has token)
2018-02-05T21:41:14.844Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/plixer/scrutinizer.git \\shares\Marketing\Website Management\GitHub\scrutinizer (took 19.972s)
2018-02-05T21:41:15.017Z - info: [ui] [AppStore] adding repository at \\shares\Marketing\Website Management\GitHub\scrutinizer to store
2018-02-05T21:41:16.268Z - info: [ui] Executing isUsingLFS: git lfs track (took 1.208s)
2018-02-05T21:41:19.733Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.375s)
2018-02-05T21:43:36.835Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: scrutinizer - justinjett (has token)
2018-02-05T21:43:38.773Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.928s)
2018-02-05T21:46:48.712Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.373s)
2018-02-05T21:48:08.225Z - info: [ui] [AppStore] loading 1 repositories from store
2018-02-05T21:48:08.226Z - info: [ui] [AppStore] found account: justinjett (justinjett)
2018-02-05T21:48:09.057Z - info: [ui] launching: 1.0.13 (Windows 10.0.16299)
2018-02-05T21:48:09.057Z - info: [ui] execPath: 'C:\Users\JUSTINJ\AppData\Local\GitHubDesktop\app-1.0.13\GitHubDesktop.exe'
2018-02-05T21:48:10.516Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.604s)
2018-02-05T21:48:27.128Z - info: [ui] Executing createCommit: git commit -F - (took 1.029s)
2018-02-05T21:48:27.860Z - warn: [ui] fetchCommit: 'repos/plixer/scrutinizer/commits/e0f1025ffdaa40ed359bd5b41e994d69bbffa46f' returned a 404
2018-02-05T21:48:29.125Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: scrutinizer - justinjett (has token)
2018-02-05T21:48:32.812Z - info: [ui] Executing push: git -c credential.helper= push origin trunk:trunk --progress (took 3.674s)
2018-02-05T21:48:34.744Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.928s)
2018-02-05T21:53:44.972Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.452s)

**Comment by shiftkey** [comment]
@justinjett thanks for the report.

I'd like to visually understand what you're seeing, and that requires two further bits of information:

 - a screenshot of the problem commit in the app
 - the commit details related to the problem commit - I think it's `e0f1025ffdaa40ed359bd5b41e994d69bbffa46f` from the log, so this should do the trick:

```
$ git show e0f1025ffdaa40ed359bd5b41e994d69bbffa46f
```

If it's not the right one, swap in whichever SHA you want to troubleshoot.

**Comment by justinjett** [comment]
It indicates that the author is plixer; however, the user plixer was just converted to an organization and I have taken ownership of the plixer organization. I also logged out of GitHub Desktop and logged back in with my current username. 

Here is the output of the git show command:

$ git show e0f1025ffdaa40ed359bd5b41e994d69bbffa46f
commit e0f1025ffdaa40ed359bd5b41e994d69bbffa46f
Author: plixer <>
Date:   Mon Feb 5 16:48:26 2018 -0500

    arbitrary space

    Adding a space so I can make a commit.

diff --git a/conf.py b/conf.py
index 19e3c37..93d40e3 100644
--- a/conf.py
+++ b/conf.py
@@ -1,5 +1,5 @@
 # -*- coding: utf-8 -*-
-#
+#
 # plixer documentation build configuration file, created by
 # sphinx-quickstart on Tue Nov 21 14:39:10 2017.
 #

**Comment by justinjett** [comment]
I discovered the issue.
Under File > Options there are two sections (Accounts and Git) that need to be updated.

I updated the login details for GitHub.com but did not update the name in the Git tab.

**Comment by shiftkey** [comment]
@justinjett thanks for following up - I'm glad you were able to workaround this issue!

We have an open issue https://github.com/desktop/desktop/issues/610 for tracking when these get out of sync, please follow along with that issue.
