### ISSUE TITLE
Error watching file for changes

### ISSUE THREAD

**Issue by Fretice** [desktop/desktop#3952]
Error: Error watching file for changes: EPERM
    at exports._errnoException (util.js:1050:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1386:11)

Version: 1.0.13
OS: Windows 10.0.16299

Please help .. I do nothing ..but it show me this

**Comment by shiftkey** [comment]
@Fretice thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by Fretice** [comment]
2018-02-07T01:08:02.513Z - info: [ui] [AppStore] loading 4 repositories from store
2018-02-07T01:08:02.516Z - info: [ui] [AppStore] found account: Fretice (Justtery)
2018-02-07T01:08:02.931Z - info: [ui] launching: 1.0.13 (Windows 10.0.16299)
2018-02-07T01:08:02.931Z - info: [ui] execPath: 'C:\Users\Justtery\AppData\Local\GitHubDesktop\app-1.0.13\GitHubDesktop.exe'
2018-02-07T01:08:06.063Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 3.496s)
2018-02-07T01:08:07.281Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: aldelocloudmaster - Fretice (has token)
2018-02-07T01:08:31.480Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.033s)
2018-02-07T01:11:03.690Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 152.019s)
2018-02-07T01:11:52.612Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 225.298s)
2018-02-07T01:11:52.614Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: unable to access 'https://github.com/aldelo/aldelocloudmaster.git/': Failed to connect to github.com port 443: Timed out

2018-02-07T01:15:07.874Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: admincloud - Fretice (has token)
2018-02-07T01:15:09.618Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.735s)
2018-02-07T01:15:13.986Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.551s)
2018-02-07T01:20:49.493Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.817s)
2018-02-07T01:26:06.955Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.721s)
2018-02-07T01:31:23.171Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.924s)
2018-02-07T01:39:09.839Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 151.600s)
2018-02-07T01:44:26.834Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.582s)
2018-02-07T01:49:44.381Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.143s)
2018-02-07T01:53:20.487Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: admincloud - Fretice (has token)
2018-02-07T01:53:22.217Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.722s)
2018-02-07T01:53:27.151Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.747s)
2018-02-07T01:53:30.948Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.308s)
2018-02-07T01:53:32.766Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.598s)
2018-02-07T02:00:27.340Z - error: [main] Error: Error watching file for changes: EPERM
    at exports._errnoException (util.js:1050:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1386:11)
2018-02-07T02:00:28.475Z - info: [main] Error report submitted
2018-02-07T02:00:33.395Z - info: [main] opening in browser: https://github.com/desktop/desktop/issues
2018-02-07T02:12:53.499Z - info: [ui] [AppStore] loading 4 repositories from store
2018-02-07T02:12:53.501Z - info: [ui] [AppStore] found account: Fretice (Justtery)
2018-02-07T02:12:53.913Z - info: [ui] launching: 1.0.13 (Windows 10.0.16299)
2018-02-07T02:12:53.913Z - info: [ui] execPath: 'C:\Users\Justtery\AppData\Local\GitHubDesktop\app-1.0.13\GitHubDesktop.exe'
2018-02-07T02:12:55.136Z - info: [ui] Stats reported.
2018-02-07T02:13:02.986Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.588s)
2018-02-07T02:13:07.311Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.597s)
2018-02-07T02:13:11.330Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.601s)
2018-02-07T02:13:15.953Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.010s)
2018-02-07T02:13:17.708Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.576s)
2018-02-07T02:18:43.508Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.759s)

**Comment by Fretice** [comment]
Sorry ,perhaps it's my network error . Thx

**Comment by shiftkey** [comment]
@Fretice this feels similar to an earlier issue https://github.com/desktop/desktop/issues/3046

In particular, if your `TEMP` environment variable is pointing to a location that isn't writable by users, this error will occur. There's some extra discussion here about the underlying details from a different user: https://github.com/desktop/desktop/issues/3046#issuecomment-336675548
