### ISSUE TITLE
comment inserer dans windows

### ISSUE THREAD

**Issue by rossimonique** [desktop/desktop#4045]
### Descriptionwindows ne trouve plus mes fichiers

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by rossimonique** [comment]
###

**Comment by rossimonique** [comment]
windows n;a pas integre gitHub et ne trouve plus mes fichiers

**Comment by tierninho** [comment]
@rossimonique Merci d'avoir contacté!

Nous exigeons que le modèle soit rempli pour tous les nouveaux problèmes. Nous faisons cela pour que nous pouvons être certains que nous avons toutes les informations dont nous avons besoin pour répondre à votre soumission efficace.

Merci de votre compréhension et de nous avoir rencontré à mi-chemin 😀

**Comment by rossimonique** [comment]
j;ai utilise l,outil gitHub pour mon dossier apdata et depuis windows ne trouve plus le dossier alors que je le vois sur mon pc.

merci de me repondre  Mme ROSSi
[2018-02-17.desktop.production.log](https://github.com/desktop/desktop/files/1742247/2018-02-17.desktop.production.log)

**Comment by shiftkey** [comment]
From the log: Version 1.0.13 (Windows 6.3.9600)

*Note: I'm using some Google Translate-fu here as I don't speak French at all. Apologies in advance for anything lost in translation.*

@rossimonique est-ce l'erreur que vous voyez?

```
2018-02-17T09:54:19.049Z - error: [main] Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)
2018-02-17T09:54:19.050Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 27.656s)
2018-02-17T09:54:19.051Z - error: [ui] `git update-index --add --remove --replace -z --stdin` exited with an unexpected code: 128.
```

Il semble que le commit ne réussisse pas à se terminer - pouvez-vous confirmer que c'est ce que vous étiez en train de faire pour déclencher l'erreur, et aussi indiquer approximativement combien de fichiers vous souhaitez valider?

Je pense que c'est le même problème que # 2041, en regardant ce message d'erreur.

<details>
 <summary>For those who also don't speak French:</summary>
 @rossimonique is this the error that you are seeing?

```
2018-02-17T09:54:19.049Z - error: [main] Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)
2018-02-17T09:54:19.050Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 27.656s)
2018-02-17T09:54:19.051Z - error: [ui] `git update-index --add --remove --replace -z --stdin` exited with an unexpected code: 128.
```

It looks like the commit is failing to complete - can you confirm this is what you were doing to trigger the error, and also mention approximately how many files you wished to commit?

I think this is the same issue as #2041, looking at that error message.
</details>
