### ISSUE TITLE
warning: invalid release notes in package on Windows

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#406]
Found in `SquirrelSetup.log` while testing  #404 

```
2016-09-27 14:57:45> UpdateInfo: Couldn't get release notes for:desktop-0.0.2-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\shiftkey\AppData\Local\desktop\packages\desktop-0.0.2-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
```

Investigate whether we can make this error go away (put in a dummy value for the release notes?) because we never read it

**Comment by joshaber** [comment]
I don't think this is an actual thing we care about. We link to release notes on our own. No reason Squirrel.Windows should care, right?

**Comment by shiftkey** [comment]
Yeah, we got this. It'd be nice to remove the error from our logs, but that requires me to look into whether this is possible in Squirrel.Windows.

**Comment by shiftkey** [comment]
The work required to change this and get it integrated all the way into our tooling isn't really worth the benefit of a slightly shorter log. Ignoring for now.
