### ISSUE TITLE
Client that was built from sources are stuck in update process

### ISSUE THREAD

**Issue by crea7or** [desktop/desktop#4096]
### Description

Client that was built form latest sources are trying to update itself in the permanent cycle. Download, ask to restart, download again.

### Version

**GitHub Desktop version:** 1.0.14-beta2

**OS version:** Windows 6.3.9600

### Steps to Reproduce

1. Build package from source (yarn build:prod | yarn package)
1. Install package ("desktop\dist\installer\GitHubDesktopSetup.exe")
1. Client started update process

**Expected behavior:** I'm using latest beta version

**Actual behavior:** I'm using latest version with permanent update process

**Reproduces how often:** 100%

### Logs

2018-02-23T23:19:44.183Z - info: [ui] [AppStore] loading 5 repositories from store
2018-02-23T23:19:44.389Z - info: [ui] launching: 1.0.14-beta2 (Windows 6.3.9600)
2018-02-23T23:19:44.389Z - info: [ui] execPath: 'C:\Users\Pavel\AppData\Local\GitHubDesktop\app-1.0.14-beta2\GitHubDesktop.exe'
2018-02-23T23:20:36.508Z - info: [ui] [AppStore] loading 5 repositories from store
2018-02-23T23:20:36.678Z - info: [ui] launching: 1.0.14-beta2 (Windows 6.3.9600)
2018-02-23T23:20:36.678Z - info: [ui] execPath: 'C:\Users\Pavel\AppData\Local\GitHubDesktop\app-1.0.14-beta2\GitHubDesktop.exe'
2018-02-23T23:21:41.428Z - info: [ui] [AppStore] loading 5 repositories from store
2018-02-23T23:21:41.599Z - info: [ui] launching: 1.0.14-beta2 (Windows 6.3.9600)
2018-02-23T23:21:41.600Z - info: [ui] execPath: 'C:\Users\Pavel\AppData\Local\GitHubDesktop\app-1.0.14-beta2\GitHubDesktop.exe'
2018-02-23T23:22:05.080Z - info: [ui] [AppStore] loading 5 repositories from store
2018-02-23T23:22:05.317Z - info: [ui] launching: 1.0.14-beta2 (Windows 6.3.9600)
2018-02-23T23:22:05.318Z - info: [ui] execPath: 'C:\Users\Pavel\AppData\Local\GitHubDesktop\app-1.0.14-beta2\GitHubDesktop.exe'

![image](https://user-images.githubusercontent.com/467357/36621908-8b20a3ca-190b-11e8-8971-bdb09b695a84.png)

#### Additional Information

Client that was built have [this changes included](https://github.com/desktop/desktop/pull/4037).

**Comment by shiftkey** [comment]
@crea7or this kind of makes sense as you're building a beta that's earlier than the one available, but I'm curious if there's something with the update that's failing - it might be because your installed version isn't signed with a codesigning certificate.

Could you look for the `%LOCALAPPDATA%\SquirrelTemp\SquirrelSetup.log` file on disk and add it here? That might be able to tell us why the update isn't being applied correctly...

**Comment by crea7or** [comment]
@shiftkey here is it:
2018-02-24 02:19:40> Program: Starting Squirrel Updater: --install .
2018-02-24 02:19:40> Program: Starting install, writing to C:\Users\Pavel\AppData\Local\SquirrelTemp
2018-02-24 02:19:40> Program: About to install to: C:\Users\Pavel\AppData\Local\GitHubDesktop
2018-02-24 02:19:40> Program: Install path C:\Users\Pavel\AppData\Local\GitHubDesktop already exists, burning it to the ground
2018-02-24 02:19:41> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Pavel\AppData\Local\GitHubDesktop\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-02-24 02:19:41> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Pavel\AppData\Local\GitHubDesktop\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-02-24 02:19:41> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Pavel\AppData\Local\SquirrelTemp
2018-02-24 02:19:41> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-02-24 02:19:41> ApplyReleasesImpl: Writing files to app directory: C:\Users\Pavel\AppData\Local\GitHubDesktop\app-1.0.14-beta2
2018-02-24 02:19:41> LogHost: Rigging execution stub for lib/net45/GitHubDesktop_ExecutionStub.exe to C:\Users\Pavel\AppData\Local\GitHubDesktop\GitHubDesktop.exe
2018-02-24 02:19:42> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Pavel\AppData\Local\GitHubDesktop\app-1.0.14-beta2\GitHubDesktop.exe]
2018-02-24 02:19:43> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-02-24 02:19:43> ApplyReleasesImpl: Examining Pin: Snipping Tool.lnk
2018-02-24 02:19:43> ApplyReleasesImpl: File 'C:\Users\Pavel\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Snipping Tool.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
2018-02-24 02:19:43> ApplyReleasesImpl: Examining Pin: VMware Workstation.lnk
2018-02-24 02:19:43> ApplyReleasesImpl: Fixing up tray icons
2018-02-24 02:19:43> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.14-beta2
2018-02-24 02:19:43> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.14-beta2
2018-02-24 04:44:23> Program: Starting Squirrel Updater: --install .
2018-02-24 04:44:23> Program: Starting install, writing to C:\Users\Pavel\AppData\Local\SquirrelTemp
2018-02-24 04:44:23> Program: About to install to: C:\Users\Pavel\AppData\Local\GitHubDesktop
2018-02-24 04:44:23> Program: Install path C:\Users\Pavel\AppData\Local\GitHubDesktop already exists, burning it to the ground
2018-02-24 04:44:23> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Pavel\AppData\Local\GitHubDesktop\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-02-24 04:44:23> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Pavel\AppData\Local\GitHubDesktop\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-02-24 04:44:23> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Pavel\AppData\Local\SquirrelTemp
2018-02-24 04:44:23> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-02-24 04:44:23> ApplyReleasesImpl: Writing files to app directory: C:\Users\Pavel\AppData\Local\GitHubDesktop\app-1.0.13
2018-02-24 04:44:24> LogHost: Rigging execution stub for lib/net45/GitHubDesktop_ExecutionStub.exe to C:\Users\Pavel\AppData\Local\GitHubDesktop\GitHubDesktop.exe
2018-02-24 04:44:25> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Pavel\AppData\Local\GitHubDesktop\app-1.0.13\GitHubDesktop.exe]
2018-02-24 04:44:26> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-02-24 04:44:26> ApplyReleasesImpl: Examining Pin: Snipping Tool.lnk
2018-02-24 04:44:26> ApplyReleasesImpl: File 'C:\Users\Pavel\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Snipping Tool.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
2018-02-24 04:44:26> ApplyReleasesImpl: Examining Pin: VMware Workstation.lnk
2018-02-24 04:44:26> ApplyReleasesImpl: Fixing up tray icons
2018-02-24 04:44:26> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.13
2018-02-24 04:44:26> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.13

**Comment by shiftkey** [comment]
@crea7or what's weird about that error log is that there's no mention of the `1.0.14-beta3` update being applied. 

> Expected behavior: I'm using latest beta version
> Actual behavior: I'm using latest version with permanent update process

There's probably something in Squirrel's behaviour where it's falling back to installing latest stable version if it's unable to install a beta, but I don't have the bandwidth to dig into that.

> Client that was built have this changes included.

If this is what you want, I'd recommend keeping your branch up to date with `master` which will merge you in the latest version and any changes to the version. Then, your created installer will be considered the latest when doing `build:prod`, and update checks will be skipped.

If you're only interested in testing features and not the installation experience, it's much quicker to do `yarn build:prod` and then `yarn start:prod` which bypasses the whole installer generation process.
