### ISSUE TITLE
When checking for update: "Permission denied"

### ISSUE THREAD

**Issue by cameronsamuels** [desktop/desktop#4115]
### Description
Like said in [the thread](https://goo.gl/Epr1bJ) on Twitter, when I check for an update, it shows an error saying `Could not create temporary directory: Permission denied`. Then it says, `You have the latest version (last checked just now)`.

### Version
**GitHub Desktop version:** 1.0.9
**OS version:** macOS High Sierra 10.13.3 (17D47)

### Steps to Reproduce
1. In the menu, "GitHub Desktop->About GitHub Desktop"
2. Click "Check for Updates"
3. Error shows up here (`Could not create temporary directory: Permission denied`) (Image on Twitter link)

**Expected behavior:** It should check for an update, find v1.1 and update it
**Actual behavior:** Error shows up when checking
**Reproduces how often:** This problem happens every time, and it used to not do this

### Logs
```
2018-02-26T20:44:27.018Z - info: [ui] [AppStore] loading 34 repositories from store
2018-02-26T20:44:27.073Z - info: [ui] [AppStore] found account: CameronSamuels (Cameron Samuels)
2018-02-26T20:44:28.599Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 1.422s)
2018-02-26T20:44:28.681Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.460s)
2018-02-26T20:44:29.265Z - warn: [ui] fetchEmails: failed with endpoint https://api.github.com
Error: Not Found
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:153:1)
    at <anonymous>
2018-02-26T20:44:29.515Z - info: [ui] launching: 1.0.9 (Mac OS 10.13.3)
2018-02-26T20:44:30.411Z - error: [ui] Error checking for updates
Error: Could not create temporary directory: Permission denied
2018-02-26T20:44:30.912Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 3.760s)
2018-02-26T20:44:31.052Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.412s)
2018-02-26T20:44:32.682Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 3.338s)
2018-02-26T20:44:38.751Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.598s)
2018-02-26T20:49:46.783Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.250s)
2018-02-26T20:54:58.386Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.165s)
2018-02-26T21:00:10.939Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.090s)
2018-02-26T21:05:24.302Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.173s)
2018-02-26T21:10:33.525Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.124s)
2018-02-26T21:15:44.278Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.114s)
2018-02-26T21:20:54.973Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.142s)
2018-02-26T21:31:10.868Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.113s)
2018-02-26T21:41:27.631Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.155s)
2018-02-26T21:51:47.367Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.103s)
2018-02-26T21:56:57.754Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.094s)
2018-02-26T22:02:07.608Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.139s)
2018-02-26T22:17:33.863Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.106s)
2018-02-26T22:22:42.367Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.128s)
2018-02-26T22:32:56.974Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.209s)
2018-02-26T22:35:33.708Z - info: [ui] [AppStore] loading 34 repositories from store
2018-02-26T22:35:33.711Z - info: [ui] [AppStore] found account: CameronSamuels (Cameron Samuels)
2018-02-26T22:35:34.413Z - info: [ui] launching: 1.0.9 (Mac OS 10.13.3)
2018-02-26T22:35:35.148Z - warn: [ui] fetchEmails: failed with endpoint https://api.github.com
Error: Not Found
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:153:1)
    at <anonymous>
2018-02-26T22:35:35.156Z - error: [ui] Error checking for updates
Error: Could not create temporary directory: Permission denied
2018-02-26T22:36:06.314Z - error: [ui] Error checking for updates
Error: Could not create temporary directory: Permission denied
2018-02-26T22:36:09.688Z - error: [ui] Error checking for updates
Error: Could not create temporary directory: Permission denied
2018-02-26T22:36:12.166Z - error: [ui] Error checking for updates
Error: Could not create temporary directory: Permission denied
2018-02-26T22:37:32.622Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.296s)
2018-02-26T22:37:34.416Z - error: [ui] Error checking for updates
Error: Could not create temporary directory: Permission denied
2018-02-26T22:40:16.790Z - error: [ui] Error checking for updates
Error: Could not create temporary directory: Permission denied
2018-02-26T22:43:21.564Z - error: [ui] Error checking for updates
Error: Could not create temporary directory: Permission denied
2018-02-26T22:50:40.314Z - error: [ui] Error checking for updates
Error: Could not create temporary directory: Permission denied
2018-02-26T22:50:41.218Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color -- (took 3.109s)
2018-02-26T22:51:04.566Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.138s)
2018-02-26T22:54:11.053Z - error: [ui] Error checking for updates
Error: Could not create temporary directory: Permission denied
2018-02-26T22:54:31.832Z - error: [ui] Error checking for updates
Error: Could not create temporary directory: Permission denied
```

**Comment by shiftkey** [comment]
@cameronsamuels thanks for the report! My initial theory is that this was https://github.com/Squirrel/Squirrel.Mac/issues/131 but you're running a later version of Electron that contains a fix for that issue. The error message also looks different, so it's potentially something else.

**Comment by shiftkey** [comment]
@cameronsamuels can you confirm you have moved GitHub Desktop into the `/Applications` directory? And that there aren't any interesting permissions issues that we might not be handling correctly (like https://github.com/Squirrel/Squirrel.Mac/issues/131 mentions).

Squirrel is a bit finicky about this when applying updates, and understanding a bit more about your setup will definitely save time getting to the bottom of this.

**Comment by cameronsamuels** [comment]
GitHub Desktop is in the `/Applications` directory.

![screen shot 2018-02-27 at 2 49 52 pm](https://user-images.githubusercontent.com/25394678/36754101-ba1cb26c-1bcd-11e8-8078-4c3b253aba50.png)

**Comment by shiftkey** [comment]
I've traced this error to [here](https://github.com/Squirrel/Squirrel.Mac/blob/91f86ea8da1e773483008967f07b9d41a921e96a/Squirrel/SQRLUpdater.m#L533-L536) inside the updater framework, but I'm hazy on the details after that.

These two log files might help - can you find anything interesting at the end of these files that might tell us _which_ folder the updater is trying to create?

 - `~/Library/Caches/com.github.GitHubClient.ShipIt/ShipIt_stderr.log`
 - `~/Library/Caches/com.github.GitHubClient.ShipIt/ShipIt_stdout.log` (this was empty on my machine)

**Comment by cameronsamuels** [comment]
![screen shot 2018-02-28 at 4 12 51 pm](https://user-images.githubusercontent.com/25394678/36816031-45ba2ec4-1ca2-11e8-85d7-f97da7c7a42c.png)
![screen shot 2018-02-28 at 4 12 05 pm](https://user-images.githubusercontent.com/25394678/36816032-46f18c88-1ca2-11e8-98fa-29b4714223ea.png)

I do not have permission to the `com.github.GitHubClient.ShipIt` folder.

As you can see in the first screenshot, it does not have the drop arrow to the left. As you can see in the second screenshot, I have custom permission.

This is the problem of why the error message shows up.

By modifying the permissions to allow me Read & Write access, I was able to successfully check, download, and install the update.

The issue is now resolved for me, but it should still be resolved for future happenings.

**Comment by shiftkey** [comment]
@cameronsamuels thanks for the troubleshooting. I'm going to fold this up into our Known Issues doc until there's enough details about the underlying issue to report it upstream (I couldn't see an existing issue for this reported).

**Comment by leocnj** [comment]
Follow the solution posted at [vscode](https://github.com/Microsoft/vscode/issues/43793), we can correct the file ownership error by

    sudo rm -Rf ~/Library/Caches/com.microsoft.GitHubClient.ShipIt

**Comment by shiftkey** [comment]
@leocnj that folder path is not correct - it should be `com.github.GitHubClient.ShipIt`

**Comment by Jurek54321** [comment]
Hello-World

**Comment by Jurek54321** [comment]
https://github.com/desktop/desktop/issues/4115#issuecomment-932949879

**Comment by Gyaalll** [comment]
@shiftkey
