### ISSUE TITLE
Changing sources for a project isn't handled... well.

### ISSUE THREAD

**Issue by WillSullivan** [desktop/desktop#4427]
## Description
I cloned a repo to the desktop, then I decided to create a fork instead of cloning. So I forked it in the website, and asked to open the fork on the desktop. Now, it defaulted to the same directory as the clone, which I wanted (I wanted to nuke the clone and go with the fork), but the desktop client started freaking out.

I didn't record exactly what happened, but it did at least three different things, none of which indicated the actual problem (trying to overlay a fork on the original). As I knew what was going on, I was able to fix. In this case, I had to close the desktop client (it was seriously going bonkers), nuke the clone, and re-open the fork on the desktop from the website.

Not horrible, not something that is common, but you might want to embetter the exception handling for a situation like this.

## Version

* GitHub Desktop:
1.1.1

* Operating system:
Win 10 x64 1709

## Steps to Reproduce

1. Clone a repro on the desktop, use the suggested folder
2. Fork the repo
3. Open the fork on the desktop using the suggested folder (should be the same as in 1 above)
4. Attempt to remedy without closing the desktop client.

### Expected Behavior

"Hey, dopey, a repo already exists in that folder. Choose something else, or overwrite?" 

### Actual Behavior

OMG OMG OMG WHAT IS THIS I DONT EVEN ABORT ABORT SEGFAULT DRRRRRRR

## Additional Information

It was all my fault, I shouldn't have done it, I'm sorry.

### Logs

2018-04-10T19:06:01.248Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/ufcpp/ContextFreeTask.git D:\GitHub.Com\ContextFreeTask (took 2.549s)
2018-04-10T19:06:01.332Z - info: [ui] [AppStore] adding repository at D:\GitHub.Com\ContextFreeTask to store
2018-04-10T19:06:06.183Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ContextFreeTask - WillSullivan (has token)
2018-04-10T19:06:07.542Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.352s)
2018-04-10T19:12:07.563Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.251s)
2018-04-10T19:23:10.602Z - info: [main] Received possible protocol arguments: 4
2018-04-10T19:23:10.602Z - info: [main] Processing protocol url
2018-04-10T19:23:10.639Z - info: [main] Received possible protocol arguments: 4
2018-04-10T19:25:09.241Z - info: [main] Received possible protocol arguments: 4
2018-04-10T19:25:09.243Z - info: [main] Processing protocol url
2018-04-10T19:25:09.917Z - info: [ui] [AppStore] loading 3 repositories from store
2018-04-10T19:25:09.918Z - info: [ui] [AppStore] found account: WillSullivan (Will Sullivan)
2018-04-10T19:25:10.164Z - info: [ui] launching: 1.1.1 (Windows 10.0.16299)
2018-04-10T19:25:10.164Z - info: [ui] execPath: 'C:\Users\wsullivan\AppData\Local\GitHubDesktop\app-1.1.1\GitHubDesktop.exe'
2018-04-10T19:25:11.421Z - warn: [ui] Error refreshing pull requests for 'ContextFreeTask'
Error: Unable to find path to repository on disk.
    at C:\WINDOWS\system32\webpack:\app\node_modules\dugite\build\lib\git-process.js:87:1
    at exithandler (child_process.js:289:5)
    at ChildProcess.errorhandler (child_process.js:301:5)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2018-04-10T19:25:13.936Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/WillSullivan/ContextFreeTask.git - WillSullivan (has token)
2018-04-10T19:25:16.983Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/WillSullivan/ContextFreeTask.git D:\GitHub.Com\ContextFreeTask (took 3.042s)
2018-04-10T19:25:17.054Z - info: [ui] [AppStore] adding repository at D:\GitHub.Com\ContextFreeTask to store
2018-04-10T19:25:21.351Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/WillSullivan/ContextFreeTask.git - WillSullivan (has token)
2018-04-10T19:25:21.433Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/WillSullivan/ContextFreeTask.git D:\GitHub.Com\ContextFreeTask` exited with an unexpected code: 128.
fatal: destination path 'D:\GitHub.Com\ContextFreeTask' already exists and is not an empty directory.

2018-04-10T19:25:36.557Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ContextFreeTask - WillSullivan (has token)

**Comment by shiftkey** [comment]
@WillSullivan thanks for the report! 

Can you confirm that you were using the "Clone in Desktop" flow to launch the app and clone your fork? When I try and clone my fork of Desktop I end up on this screen with the path being detected and a warning being shown:

<img width="583" src="https://user-images.githubusercontent.com/359239/38593654-d7dcbd9a-3d85-11e8-8c86-5533dd3a32bc.png">

**Comment by billygriffin** [comment]
Given the multiple times we've tried to repro this unsuccessfully, we're going to close it for now, but if it's happening to others and able to be reproduced, we're happy to reopen. Thanks!
