### ISSUE TITLE
Can't push to origin on Desktop. Have verified that the login information is correct.

### ISSUE THREAD

**Issue by LOL-XDD** [desktop/desktop#4565]
## Description
Recently I connected my site to the domain ioi-xd.xyz. It works as it should, but now I cannot push any files to the origin. When I do, it gives me the following error:

"Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository."

I am logged in with the correct account, I have verified this. I have also looked up the issue and followed the instructions, but I'm still having the issue. This the error that comes up in the log:

`git merge-base master origin/master` exited with an unexpected code: 1.`
```
error @ install.ts:23
core.ts:167 Uncaught (in promise) d: Unknown error
    at Object.t.git (file:///C:/Users/Owner/AppData/Local/GitHubDesktop/app-1.1.1/resources/app/renderer.js:1:8045)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
## Version
* GitHub Desktop: 1.1.1
* Operating system: Windows 10

## Steps to Reproduce
1. Make changes to the site.
2. Push to origin.

### Expected Behavior
The website would update as expected.

### Actual Behavior
I got an error message.

### Logs
See above.

**Comment by shiftkey** [comment]
@LOL-XDD could you attach the full log? That specific error is called within `getMergeBase` which is part of the [`performPull`](https://github.com/desktop/desktop/blob/2406f4b29a5641bbbf4c40db3add047bc8685074/app/src/lib/stores/app-store.ts#L2254) function, which seems unrelated to the repro steps outlined above.

**Comment by LOL-XDD** [comment]
Thanks for the response but I've actually quit the site now. I just realized I can't use PHP so I need to use an actual apache server. Apologies to anyone having this issue as well.
