### ISSUE TITLE
handle mammoth repositories like Unreal Engine

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#478]
A [user report](https://halp.githubapp.com/discussions/fb7051c2869311e68e5c65ea82374dfa) recently that Desktop Classic (Windows) still has issues with repositories such as [EpicGames/UnrealEngine](https://github.com/epicgames/unrealengine/):

```
2016-09-30 01:34:38.7208|WARN|thread: 1|RepositoryViewModel|Unable to display commit on tooltip
LibGit2Sharp.LibGit2SharpException: Failed to mmap. No data written: Not enough storage is available to process this command.

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_revparse_ext(RepositorySafeHandle repo, String objectish)
   at LibGit2Sharp.Core.Proxy.git_revparse_single(RepositorySafeHandle repo, String objectish)
   at LibGit2Sharp.Repository.Lookup(String objectish, GitObjectType type, LookUpOptions lookUpOptions)
   at LibGit2Sharp.Repository.Lookup(String objectish, ObjectType type)
   at LibGit2Sharp.RepositoryExtensions.Lookup[T](IRepository repository, String objectish)
   at GitHub.ConcurrentRepositoryConnection.<>c__DisplayClass1b.<GetCommit>b__1a()
   at System.Reactive.Linq.ObservableImpl.Defer`1.Eval()
   at System.Reactive.Linq.ObservableImpl.Defer`1._.Run()
```

With our move to out-of-proc Git operations, hopefully this is no longer an issue.

However, here's a rough list of things we should run through for both platforms - at least for the internal beta:
- can drag and drop the repository onto the app
- can view changes for the repository
- can view history for the repository
- can scroll and load in new commits for the repository
- everything remains snappy

**Comment by z5aEn** [comment]
[BrandingMedia_Logos_Unreal_Engine_Logos-194aec037564e2e849650161de30d5a294a592ee-1.zip](https://github.com/desktop/desktop/files/2086469/BrandingMedia_Logos_Unreal_Engine_Logos-194aec037564e2e849650161de30d5a294a592ee-1.zip)
