### ISSUE TITLE
Crash Down While Launching

### ISSUE THREAD

**Issue by mashirozx** [desktop/desktop#5068]
## Description

Crash down while launching, the same issue every time restart the application, so I guess I got to reinstall the application to solve this problem.
![image](https://user-images.githubusercontent.com/16148054/42082152-d9aceeb6-7bb9-11e8-83ac-8597ec7a152b.png)

## Version

* GitHub Desktop:
![image](https://user-images.githubusercontent.com/16148054/42082221-020f7220-7bba-11e8-8daa-9f97ab753baf.png)

* Operating system:
![image](https://user-images.githubusercontent.com/16148054/42082277-284a2e58-7bba-11e8-9313-d413dc390852.png)

## Steps to Reproduce

I don't know. it just occurred suddenly.

### Logs

```
2018-06-29T07:56:22.243Z - info: [ui] [AppStore] loading 20 repositories from store
2018-06-29T07:56:22.243Z - info: [ui] [AppStore] found account: mashirozx (Mashiro)
2018-06-29T07:56:24.204Z - info: [ui] Executing getRemotes: git remote -v (took 1.846s)
2018-06-29T07:56:24.408Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 2.276s)
2018-06-29T07:56:24.412Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.253s)
2018-06-29T07:56:24.620Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 2.313s)
2018-06-29T07:56:24.628Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 1.463s)
2018-06-29T07:56:25.139Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.971s)
2018-06-29T07:56:25.143Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.828s)
2018-06-29T07:56:25.709Z - info: [ui] launching: 1.2.6 (Windows 10.0.17134)
2018-06-29T07:56:25.709Z - info: [ui] execPath: 'C:\Users\Mashiro\AppData\Local\GitHubDesktop\app-1.2.6\GitHubDesktop.exe'
2018-06-29T07:56:27.313Z - info: [ui] Stats reported.
2018-06-29T07:56:27.568Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.104s)
2018-06-29T07:56:38.516Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 6.364s)
2018-06-29T07:56:39.568Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.045s)
2018-06-29T07:56:39.744Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.227s)
2018-06-29T07:56:40.764Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 1.360s)
2018-06-29T07:56:42.107Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.330s)
2018-06-29T07:56:42.339Z - info: [ui] Executing getRemotes: git remote -v (took 1.566s)
2018-06-29T07:56:42.339Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-color -- (took 1.571s)
2018-06-29T07:56:43.779Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-color -- (took 1.320s)
2018-06-29T07:56:45.045Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 1.387s)
2018-06-29T07:57:24.550Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 1.448s)
2018-06-29T07:57:24.634Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.531s)
2018-06-29T07:57:24.638Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.633s)
2018-06-29T07:57:39.351Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.001s)
2018-06-29T07:57:39.523Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.127s)
2018-06-29T07:58:00.909Z - info: [ui] [AppStore] adding repository at C:\WorkDirectory\GitHub\Akame Ga Kill! to store
2018-06-29T07:58:05.644Z - info: [ui] Executing isUsingLFS: git lfs track (took 4.690s)
2018-06-29T07:58:58.306Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 4.228s)
2018-06-29T07:58:58.307Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 4.224s)
2018-06-29T07:58:59.466Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 5.391s)
2018-06-29T07:58:59.917Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 1.622s)
2018-06-29T07:59:01.160Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-color -- (took 1.226s)
2018-06-29T07:59:01.160Z - info: [ui] Executing getRemotes: git remote -v (took 1.222s)
2018-06-29T07:59:01.229Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.297s)
2018-06-29T07:59:08.476Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.057s)
2018-06-29T07:59:09.986Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-color -- (took 1.048s)
2018-06-29T07:59:13.311Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 1.090s)
2018-06-29T07:59:13.407Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.178s)
2018-06-29T07:59:13.408Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.164s)
2018-06-29T08:00:59.614Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.778s)
2018-06-29T08:00:59.694Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 1.850s)
2018-06-29T08:01:00.251Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.406s)
2018-06-29T08:01:57.433Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 4.272s)
2018-06-29T08:03:19.800Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 1.032s)
2018-06-29T08:03:19.874Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.111s)
2018-06-29T08:03:19.964Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.167s)
2018-06-29T08:03:30.691Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-color -- (took 10.422s)
2018-06-29T08:03:30.691Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 10.369s)
2018-06-29T08:03:30.691Z - info: [ui] Executing getRemotes: git remote -v (took 10.374s)
2018-06-29T08:03:45.404Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-color -- (took 14.706s)
2018-06-29T08:03:50.045Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 4.651s)
2018-06-29T08:05:09.413Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.856s)
2018-06-29T08:05:09.497Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 1.931s)
2018-06-29T08:05:09.918Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.359s)
2018-06-29T08:05:38.278Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Mashiro\AppData\Local\GitHubDesktop\app-1.2.6\blink_image_resources_200_percent.pak' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\Mashiro\AppData\Local\GitHubDesktop\app-1.2.6\blink_image_resources_200_percent.pak' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()<---


    at AutoUpdater.emitError (C:\Users\Mashiro\AppData\Local\GitHubDesktop\app-1.2.6\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:58:24)
    at squirrelUpdate.update (C:\Users\Mashiro\AppData\Local\GitHubDesktop\app-1.2.6\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:43:23)
    at ChildProcess.<anonymous> (C:\Users\Mashiro\AppData\Local\GitHubDesktop\app-1.2.6\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:71:14)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
2018-06-29T08:07:08.963Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 541.584s)
2018-06-29T08:07:11.599Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.467s)
2018-06-29T08:07:11.607Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
git: 'remote-https' is not a git command. See 'git --help'.

2018-06-29T08:09:28.351Z - info: [ui] Executing createCommit: git commit -F - (took 139.388s)
2018-06-29T08:22:45.083Z - error: [ui] `git -c credential.helper= push origin master --set-upstream --progress` exited with an unexpected code: 128.
git: 'remote-https' is not a git command. See 'git --help'.

2018-06-29T08:22:46.810Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.079s)
2018-06-29T08:22:46.888Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.130s)
2018-06-29T08:22:50.585Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Akame-Ga-Kill- - mashirozx (has token)
2018-06-29T08:22:50.826Z - error: [ui] `git -c credential.helper= push origin master --set-upstream --progress` exited with an unexpected code: 128.
git: 'remote-https' is not a git command. See 'git --help'.

2018-06-29T08:23:02.127Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Akame-Ga-Kill- - mashirozx (has token)
2018-06-29T08:23:02.315Z - error: [ui] `git -c credential.helper= push origin master --set-upstream --progress` exited with an unexpected code: 128.
git: 'remote-https' is not a git command. See 'git --help'.
```

**Comment by mashirozx** [comment]
Update: Problem solved by installing the latest version (no uninstall), but I still keep this issue open, and be free to close it directly if you think this was no longer a problem~ 😄

**Comment by shiftkey** [comment]
@mashirozx thanks for the report. It's not quite clear how the updater got into this state while upgrading from 1.2.3 to 1.2.6, but here are some insights.

This is a file from the new update - could the updater be running twice somehow to trigger this?

```
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Mashiro\AppData\Local\GitHubDesktop\app-1.2.6\blink_image_resources_200_percent.pak' because it is being used by another process.
```

`git-remote-https` is a component from the live application, which shouldn't be removed as part of the upgrade process, but seems to have been. Why?

```
2018-06-29T08:07:11.607Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
git: 'remote-https' is not a git command. See 'git --help'.
```

There's a log file that the updater generates at `%LOCALAPPDATA%\GitHubDesktop\SquirrelSetup.log` that might provide some extra context to what's happened here - are you able to share that?

**Comment by mashirozx** [comment]
@shiftkey Fine.
```
2018-06-29 16:41:23> Program: Starting Squirrel Updater: --createShortcut GitHubDesktop.exe -l StartMenu,Desktop
2018-06-29 16:41:23> ApplyReleasesImpl: About to create shortcuts for GitHubDesktop.exe, rootAppDir C:\Users\Mashiro\AppData\Local\GitHubDesktop
2018-06-29 16:41:24> ApplyReleasesImpl: Creating shortcut for GitHubDesktop.exe => C:\Users\Mashiro\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2018-06-29 16:41:24> ApplyReleasesImpl: About to save shortcut: C:\Users\Mashiro\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\Mashiro\AppData\Local\GitHubDesktop\GitHubDesktop.exe, workingDir C:\Users\Mashiro\AppData\Local\GitHubDesktop\app-1.2.6, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2018-06-29 16:41:24> ApplyReleasesImpl: Creating shortcut for GitHubDesktop.exe => C:\Users\Mashiro\Desktop\GitHub Desktop.lnk
2018-06-29 16:41:24> ApplyReleasesImpl: About to save shortcut: C:\Users\Mashiro\Desktop\GitHub Desktop.lnk (target C:\Users\Mashiro\AppData\Local\GitHubDesktop\GitHubDesktop.exe, workingDir C:\Users\Mashiro\AppData\Local\GitHubDesktop\app-1.2.6, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2018-06-29 16:41:24> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-06-29 16:41:24> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2018-06-29 16:41:44> Program: Starting Squirrel Updater: --checkForUpdate https://central.github.com/api/deployments/desktop/desktop/latest?version=1.2.6&env=production
2018-06-29 16:41:44> Program: Fetching update information, downloading from https://central.github.com/api/deployments/desktop/desktop/latest?version=1.2.6&env=production
2018-06-29 16:41:44> CheckForUpdateImpl: Generated new staging user ID: f49cca0e-d7b9-554c-83ac-33c06b1dd797
2018-06-29 16:41:45> CheckForUpdateImpl: Downloading RELEASES file from https://central.github.com/api/deployments/desktop/desktop/latest?version=1.2.6&env=production
2018-06-29 16:41:45> FileDownloader: Downloading url: https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=1.2.6&env=production&id=GitHubDesktop&localVersion=1.2.6&arch=amd64

```

**Comment by shiftkey** [comment]
@mashirozx that file looks like the installation of the latest version (~8 hours later?) which didn't have any issues - I guess it cleaned up the old log. 

I'll close this out but keep an eye out for any other reports in this vein. Thanks for the info!

**Comment by mashirozx** [comment]
@shiftkey Yes, after reporting this issue I installed the latest version.
