### ISSUE TITLE
Unable to yarn install in development on macOS

### ISSUE THREAD

**Issue by OiYouYeahYou** [desktop/desktop#5107]
When using the yarn command to install dependencies a wall of errors is produced

This is possibly out of your scope, but I only have this issue on this repo. I am unable to resolve this issue after removing and reinstalling node, npm, yarn, node-gym and xcode. I am hoping there is a less nuclear solution than wiping my device

## Version
* GitHub Desktop: 1.2.6
* Operating system: macOS 10.13.4
* yarn version v1.7.0
* node v8.11.3
* npm 5.6.0

### Expected Behavior
Installs dependencies

### Actual Behavior
Fails

### Logs

Output from `yarn`:
```
yarn install v1.7.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
info 7zip-bin-linux@1.3.1: The platform "darwin" is incompatible with this module.
info "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-win@2.2.0: The platform "darwin" is incompatible with this module.
info "7zip-bin-win@2.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-linux@1.5.0: The platform "darwin" is incompatible with this module.
info "app-builder-bin-linux@1.5.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-win@1.5.0: The platform "darwin" is incompatible with this module.
info "app-builder-bin-win@1.5.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] 🔗  Linking dependencies...
[5/5] 📃  Building fresh packages...
$ cd app && yarn install --force && cd .. && git submodule update --recursive --init && yarn compile:tslint && yarn compile:script
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Rebuilding all packages...
[1/4] ⡀ dugite
[2/4] ⡀ keytar
[3/4] ⡀ registry-js
error /Users/jason/code/desktop/app/node_modules/runas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/jason/code/desktop/app/node_modules/runas
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.3 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jason/code/desktop/app/node_modules/runas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jason/.node-gyp/iojs-1.8.7/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jason/.node-gyp/iojs-1.8.7',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/jason/.node-gyp/iojs-1.8.7/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/jason/code/desktop/app/node_modules/runas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/runas/src/main.o
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:48:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:62:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-unix.h:56:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-darwin.h:26:
In file included from /usr/include/mach/mach.h:67:
In file included from /usr/include/mach/mach_interface.h:42:
In file included from /usr/include/mach/clock_priv.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:
In file included from /usr/local/include/string.h:26:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:639:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:58:1: error: templates must have C++ linkage
template<class _Ep>
^~~~~~~~~~~~~~~~~~~
/Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:27:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:48:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:62:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-unix.h:56:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-darwin.h:26:
In file included from /usr/include/mach/mach.h:67:
In file included from /usr/include/mach/mach_interface.h:42:
In file included from /usr/include/mach/clock_priv.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:
In file included from /usr/local/include/string.h:26:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:639:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:96:1: error: templates must have C++ linkage
template<class _Ep>
^~~~~~~~~~~~~~~~~~~
/Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:27:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:48:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:62:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-unix.h:56:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-darwin.h:26:
In file included from /usr/include/mach/mach.h:67:
In file included from /usr/include/mach/mach_interface.h:42:
In file included from /usr/include/mach/clock_priv.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:
In file included from /usr/local/include/string.h:26:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:639:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:100:7: error: use of undeclared identifier 'initializer_list'
begin(initializer_list<_Ep> __il) _NOEXCEPT
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:100:24: error: '_Ep' does not refer to a value
begin(initializer_list<_Ep> __il) _NOEXCEPT
                       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:96:16: note: declared here
template<class _Ep>
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:100:29: error: use of undeclared identifier '__il'
begin(initializer_list<_Ep> __il) _NOEXCEPT
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:100:34: error: expected ';' at end of declaration
begin(initializer_list<_Ep> __il) _NOEXCEPT
                                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:100:35: error: expected unqualified-id
begin(initializer_list<_Ep> __il) _NOEXCEPT
                                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:754:21: note: expanded from macro '_NOEXCEPT'
#  define _NOEXCEPT noexcept
                    ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:48:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:62:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-unix.h:56:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-darwin.h:26:
In file included from /usr/include/mach/mach.h:67:
In file included from /usr/include/mach/mach_interface.h:42:
In file included from /usr/include/mach/clock_priv.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:
In file included from /usr/local/include/string.h:26:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:639:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:105:1: error: templates must have C++ linkage
template<class _Ep>
^~~~~~~~~~~~~~~~~~~
/Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:27:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:48:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:62:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-unix.h:56:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-darwin.h:26:
In file included from /usr/include/mach/mach.h:67:
In file included from /usr/include/mach/mach_interface.h:42:
In file included from /usr/include/mach/clock_priv.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:
In file included from /usr/local/include/string.h:26:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:639:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:109:5: error: use of undeclared identifier 'initializer_list'
end(initializer_list<_Ep> __il) _NOEXCEPT
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:109:22: error: '_Ep' does not refer to a value
end(initializer_list<_Ep> __il) _NOEXCEPT
                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:105:16: note: declared here
template<class _Ep>
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:109:27: error: use of undeclared identifier '__il'
end(initializer_list<_Ep> __il) _NOEXCEPT
                          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:109:32: error: expected ';' at end of declaration
end(initializer_list<_Ep> __il) _NOEXCEPT
                               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:109:33: error: expected unqualified-id
end(initializer_list<_Ep> __il) _NOEXCEPT
                                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:754:21: note: expanded from macro '_NOEXCEPT'
#  define _NOEXCEPT noexcept
                    ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:48:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:62:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-unix.h:56:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-darwin.h:26:
In file included from /usr/include/mach/mach.h:67:
In file included from /usr/include/mach/mach_interface.h:42:
In file included from /usr/include/mach/clock_priv.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:
In file included from /usr/local/include/string.h:26:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:640:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:398:1: error: templates must have C++ linkage
template <class _T1, class _T2> struct _LIBCPP_TEMPLATE_VIS pair;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:27:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:48:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:62:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-unix.h:56:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-darwin.h:26:
In file included from /usr/include/mach/mach.h:67:
In file included from /usr/include/mach/mach_interface.h:42:
In file included from /usr/include/mach/clock_priv.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:
In file included from /usr/local/include/string.h:26:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:640:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:399:1: error: templates must have C++ linkage
template <class _Tp> class _LIBCPP_TEMPLATE_VIS reference_wrapper;
^~~~~~~~~~~~~~~~~~~~
/Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:27:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:48:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:62:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-unix.h:56:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-darwin.h:26:
In file included from /usr/include/mach/mach.h:67:
In file included from /usr/include/mach/mach_interface.h:42:
In file included from /usr/include/mach/clock_priv.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:
In file included from /usr/local/include/string.h:26:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:640:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:400:1: error: templates must have C++ linkage
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS hash;
^~~~~~~~~~~~~~~~~~~~
/Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:27:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:48:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:62:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-unix.h:56:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-darwin.h:26:
In file included from /usr/include/mach/mach.h:67:
In file included from /usr/include/mach/mach_interface.h:42:
In file included from /usr/include/mach/clock_priv.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:
In file included from /usr/local/include/string.h:26:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:640:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:402:1: error: templates must have C++ linkage
template <class>
^~~~~~~~~~~~~~~~
/Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:27:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:48:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:62:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-unix.h:56:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-darwin.h:26:
In file included from /usr/include/mach/mach.h:67:
In file included from /usr/include/mach/mach_interface.h:42:
In file included from /usr/include/mach/clock_priv.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:
In file included from /usr/local/include/string.h:26:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:640:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:405:1: error: templates must have C++ linkage
template <class _Tp>
^~~~~~~~~~~~~~~~~~~~
/Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:27:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:48:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:62:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-unix.h:56:
In file included from /Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv-darwin.h:26:
In file included from /usr/include/mach/mach.h:67:
In file included from /usr/include/mach/mach_interface.h:42:
In file included from /usr/include/mach/clock_priv.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:
In file included from /usr/local/include/string.h:26:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:640:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:408:1: error: templates must have C++ linkage
template <class _Tp, bool>
^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:27:1: note: extern "C" language linkage specification begins here
extern "C" {
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jason/code/desktop/app/node_modules/runas
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by shiftkey** [comment]
@OiYouYeahYou I've not stumbled across that specific error before. What version of XCode are you running?

```
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:639:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/initializer_list:58:1: error: templates must have C++ linkage
template<class _Ep>
^~~~~~~~~~~~~~~~~~~
/Users/jason/.node-gyp/iojs-1.8.7/deps/uv/include/uv.h:27:1: note: extern "C" language linkage specification begins here
extern "C" {
^
```

**Comment by OiYouYeahYou** [comment]
Xcode Version 9.4.1 (9F2000)

**Comment by shiftkey** [comment]
@OiYouYeahYou alright, same version as mine. I've not been able to turn up much else on the googles aside from this looking like a GCC error (which is weird because XCode should be using clang).

**Comment by OiYouYeahYou** [comment]
I seem to have both, and they seem to be the same thing?

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ which gcc
/usr/bin/gcc
$ which clang
/usr/bin/clang
```

**Comment by shiftkey** [comment]
One thing to try would be to ensure Node is building using clang. [These environment variables](https://github.com/atom-archive/node-runas/blob/master/.travis.yml#L17) might help:

```
$ CC=clang CXX=clang++ npm_config_clang=1
```

**Comment by OiYouYeahYou** [comment]
Just ran the following in both repo root and app, still throwing errors

```
$ CC=clang CXX=clang++ npm_config_clang=1 yarn
```

**Comment by OiYouYeahYou** [comment]
Resolved by formatting and reinstalling

**Comment by shiftkey** [comment]
@OiYouYeahYou 

![](https://user-images.githubusercontent.com/359239/42533086-41c56a0c-845f-11e8-9d3a-6a3df586fef9.gif)
