### ISSUE TITLE
runtime error: "Error: Cannot call function 'isFullScreen' on missing remote object 2"

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#5267]
Stack trace:

```
Cannot call function 'isFullScreen' on missing remote object 2
Error: Cannot call function 'isFullScreen' on missing remote object 2
    at throwRPCError (C:\Users\MYSHIT\AppData\Local\GitHubDesktop\app-1.2.6\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\MYSHIT\AppData\Local\GitHubDesktop\app-1.2.6\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:146:13)
    at EventEmitter.emit (events.js:223:7)
    at WebContents.<anonymous> (C:\Users\MYSHIT\AppData\Local\GitHubDesktop\app-1.2.6\resources\electron.asar\browser\api\web-contents.js:275:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
```

Probably related to this function:

https://github.com/desktop/desktop/blob/908a2695640cbc6d00cad303d5c0c2d2eb864245/app/src/lib/window-state.ts#L11-L23

**Comment by ADustyOldMuffin** [comment]
@shiftkey I'm here to bug you some more, is this still an issue?

**Comment by shiftkey** [comment]
@ADustyOldMuffin this was a report I saw through our bug reporting, and apologies for not writing this up at the time.

I believe this related to how we're using some Electron APIs, and `window.isFullScreen()` is a function that performs a remote inter-process call (from the renderer process to the main process) and is raising an error because it's encountered an invalid state.

It feels like the error is being reported by this code inside Electron:

https://github.com/electron/electron/blob/6f5c850d60d05a188212f247e9edc746f6fce18c/lib/browser/rpc-server.js#L404-L419

```js
  args = unwrapArgs(event.sender, event.frameId, contextId, args)
  const object = objectsRegistry.get(id)

  if (object == null) {
    throwRPCError(`Cannot call method '${method}' on missing remote object ${id}`)
  }
```

I think the steps to reproduce this would involve connecting and disconnecting an external monitor (the `2` here might mean a second monitor, but I could be wrong) when maximizing/minimizing on this screen.

The goal would be to trigger this callback:

https://github.com/desktop/desktop/blob/a5f05859fa58ad26bd750dea57a4a60a31f67449/app/src/lib/stores/app-store.ts#L414-L420

I won't have a chance to try and reproduce this over the next few days because of the release tomorrow, but I suspect this is just a hard-to-reproduce bug that very few users have noticed.

**Comment by shiftkey** [comment]
Tagging this one with `electron` because it's related to our use of some Electron APIs that could be improved.
