### ISSUE TITLE
Enterprise sign-in: Cannot read property 'email' of undefined

### ISSUE THREAD

**Issue by mkudija** [desktop/desktop#5585]
## Description

When signing into an Enterprise GitHub account, an error displays with `Cannot read property 'email' of undefined`. 

![image](https://user-images.githubusercontent.com/14117837/45311756-1b6fc900-b4f8-11e8-859b-a8968571cf67.png)

## Version

* GitHub Desktop: `1.3.5`

* Operating system: `Microsoft Windows [Version 10.0.15063]`

## Steps to Reproduce

- Set default web browser to Chrome (since experiencing issues with Internet Explorer / Edge when it continues to browser to authenticate)
- Download and install fresh version of GitHub Desktop (tested on 1.3.4)
- Authenticate with Enterprise credentials either during initial setup, or "skip" and then attempt to clone a repository 

### Expected Behavior

Expect "Continue with browser" to lead to a browser, authenticate, and then return to GitHub Desktop having signed into that user's account. 

### Actual Behavior

"Continue with browser" opens new browser window, authenticates, but then when returning to GitHub Desktop the `Cannot read property 'email' of undefined` error is shown.

**Comment by shiftkey** [comment]
@mkudija thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Also, if would be great if you're able to figure out which version of GitHub Enterprise you're connecting to.

**Comment by mkudija** [comment]
Running GitHub Enterprise 2.13.1

I'll revert tomorrow morning with logs.

**Comment by mkudija** [comment]
Example log with error below:

```
2018-09-11T12:04:29.149Z - info: [ui] [AppStore] loading 0 repositories from store
2018-09-11T12:04:29.649Z - info: [ui] launching: 1.3.5 (Windows 10.0.15063)
2018-09-11T12:04:29.649Z - info: [ui] execPath: 'C:\Users\SSO\AppData\Local\GitHubDesktop\app-1.3.5\GitHubDesktop.exe'
2018-09-11T12:04:30.524Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.179s)
2018-09-11T13:30:54.739Z - info: [ui] [AppStore] loading 0 repositories from store
2018-09-11T13:30:55.378Z - info: [ui] launching: 1.3.5 (Windows 10.0.15063)
2018-09-11T13:30:55.378Z - info: [ui] execPath: 'C:\Users\SSO\AppData\Local\GitHubDesktop\app-1.3.5\GitHubDesktop.exe'
2018-09-11T13:30:56.225Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.317s)
2018-09-11T13:33:29.753Z - info: [ui] [SignInStore] initializing OAuth flow
2018-09-11T13:33:30.129Z - info: [main] opening in browser: https://github.build.ge.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user&state=523da2ba-b66a-4677-a982-e168c3a6297e
2018-09-11T13:33:41.119Z - info: [main] Received possible protocol arguments: 3
2018-09-11T13:33:41.119Z - info: [main] Processing protocol url
2018-09-11T13:33:41.131Z - info: [ui] [Dispatcher] requesting authenticated user
2018-09-11T13:33:42.459Z - warn: [ui] fetchUser: failed with endpoint https://github.build.ge.com/api/v3
TypeError: Cannot read property 'email' of undefined
    at Object.t.fetchUser (C:\Users\SSO\AppData\Local\GitHubDesktop\app-1.3.5\webpack:\app\src\lib\api.ts:723:36)
    at <anonymous>
2018-09-11T13:33:42.459Z - info: [ui] [SignInStore] error with OAuth flow
TypeError: Cannot read property 'email' of undefined
    at Object.t.fetchUser (C:\Users\SSO\AppData\Local\GitHubDesktop\app-1.3.5\webpack:\app\src\lib\api.ts:723:36)
    at <anonymous>
2018-09-11T13:33:46.464Z - info: [ui] [SignInStore] initializing OAuth flow
2018-09-11T13:33:46.548Z - info: [main] opening in browser: https://github.build.ge.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user&state=51fc854d-51e6-475c-836a-f3169aa0aed5
2018-09-11T13:33:50.486Z - info: [main] Received possible protocol arguments: 3
2018-09-11T13:33:50.486Z - info: [main] Processing protocol url
2018-09-11T13:33:50.496Z - info: [ui] [Dispatcher] requesting authenticated user
2018-09-11T13:33:51.164Z - warn: [ui] fetchUser: failed with endpoint https://github.build.ge.com/api/v3
TypeError: Cannot read property 'email' of undefined
    at Object.t.fetchUser (C:\Users\SSO\AppData\Local\GitHubDesktop\app-1.3.5\webpack:\app\src\lib\api.ts:723:36)
    at <anonymous>
2018-09-11T13:33:51.166Z - info: [ui] [SignInStore] error with OAuth flow
TypeError: Cannot read property 'email' of undefined
    at Object.t.fetchUser (C:\Users\SSO\AppData\Local\GitHubDesktop\app-1.3.5\webpack:\app\src\lib\api.ts:723:36)
    at <anonymous>

```

**Comment by shiftkey** [comment]
@mkudija thanks for the log file, this shows you've been able to trip a bug that we didn't notice before. Here's the code on that line:

```
    const defaultEmail = emails[0].email || ''
```

Somehow, your GHE account doesn't have any emails set, so `emails[0]` will be undefined. That's The Bug™. As a workaround you may be able to add an email address to your GHE account, but we should definitely handle that better within the app.

**Comment by mkudija** [comment]
@shiftkey thanks for the info and fix. We got it working by adding email address for the users impacted (Profile > Settings > Emails > Add email address).
