### ISSUE TITLE
'spawn UNKNOWN' error. 

### ISSUE THREAD

**Issue by michael-coffey** [desktop/desktop#5633]
## Description

After GD updated itself, i clicked restart and then started getting 'spawn UNKNOWN' error.  It says that my projects don't exist at their locations even though i know they are there by viewing them in File Explorer.  This dialog pops up repeatedly!

## Version

* GitHub Desktop:  1.4.0

* Operating system:  Microsoft Windows [Version 10.0.16299.611]

## Steps to Reproduce

1. Open Github Desktop
2. Error pops up repeatedly
### Expected Behavior

Never

**Comment by tierninho** [comment]
@michael-coffey please attach your logs if possible. 

Note, we had a similar error resolved here:
https://github.com/desktop/desktop/issues/2963

**Comment by michael-coffey** [comment]
[2018-09-13.desktop.production.log](https://github.com/desktop/desktop/files/2380007/2018-09-13.desktop.production.log)
Hi. thanks for the response.  Log attached.

**Comment by shiftkey** [comment]
```
2018-09-13T15:07:24.094Z - warn: [ui] Error refreshing pull requests for 'Revit.Signage'
Error: spawn UNKNOWN
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:514:9)
    at Object.exports.execFile (child_process.js:224:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:199:20)
    at C:\ProgramData\17888\GitHubDesktop\app-1.4.0\webpack:\app\node_modules\dugite\build\lib\git-process.js:66:1
    at new Promise (<anonymous>)
    at Function.exec (C:\ProgramData\17888\GitHubDesktop\app-1.4.0\webpack:\app\node_modules\dugite\build\lib\git-process.js:49:1)
    at a.measure (C:\ProgramData\17888\GitHubDesktop\app-1.4.0\webpack:\app\src\lib\git\core.ts:119:3)
    at Object.n [as measure] (C:\ProgramData\17888\GitHubDesktop\app-1.4.0\webpack:\app\src\ui\lib\git-perf.ts:27:4)
```

My gut feeling is that the Git installation at `C:\ProgramData\17888\GitHubDesktop\app-1.4.0\resources\app\git\` is missing or corrupt. This also isn't where I expected Desktop to be installed to, but we can figure that out later.

@michael-coffey could you open a shell and run this command?

```
C:\ProgramData\17888\GitHubDesktop\app-1.4.0\resources\app\git\cmd\git.exe --version
```

This is just a sanity check to see if you can spawn our embedded Git. I was also hoping the directory structure in here looked like this:

<img width="451" alt="screen shot 2018-09-13 at 1 08 08 pm" src="https://user-images.githubusercontent.com/359239/45500874-1ad46e00-b756-11e8-922e-1fc4b49dcefd.png">

If yours is different, let me know how it differs. It might just require a fresh install of Desktop.

**Comment by michael-coffey** [comment]
A colleague at my firm believes its because of the Applocker program.  I got this message from the shell "This program is blocked by group policy. For more information, contact your system administrator."  So we are investigating if this program needs to be re-whitelisted.  Thanks.

**Comment by shiftkey** [comment]
@michael-coffey thanks for the update. I'm going to close this out as an external issue to Desktop.

**Comment by sugabubba7** [comment]
I'm getting the same 'Git: spawn UNKNOWN' error please help me out everything is confusing!!!!
