### ISSUE TITLE
"unable to find app" after updating to latest version

### ISSUE THREAD

**Issue by NicStarzi** [desktop/desktop#6486]
## Description
While I was writing a commit report GitHub Desktop crashed. I can not remember what the error message was. Attempting to start GitHub Desktop again after that crash fails. Instead, an error dialog is  shown saying: "A JavaScript error occurred in the main process".
I was unable to start GitHub Desktop since.

## Version
* GitHub Desktop: 1.5.1
* Operating system: Microsoft Windows [Version 6.1.7601] (Windows 7)

## Steps to Reproduce
I don't have any

### Expected Behavior
The application should be starting up regularily.

### Actual Behavior
The application does not start at all. It shows a fatal error and thats it.

## Additional Information
Screenshot of error dialog:
![image001](https://user-images.githubusercontent.com/9675240/50386876-5e912900-06f0-11e9-8fe9-d38dd701a3b8.png)

### Logs
Log:
[2018-12-23.desktop.production.log](https://github.com/desktop/desktop/files/2706236/2018-12-23.desktop.production.log)

Thank you for the help.

**Comment by msftrncs** [comment]
@NicStarzi, it kind of looks like the updater had some problems.  Were you previously running 1.5.1, or was it 1.4.1?

It would appear that you started 1.4.1, then it updated, and you reloaded, and then the updater tried to update again, it appears to have deleted the GIT client, and that is what led to the crash.

If you haven't done anything else yet, you should be able to find previous version copies in the folder c:\Users\ds\AppData\Local\GitHubDesktop.  You will probably find 1.4.1 still there, and if you execute the GitHubDesktop.exe in that folder you can get back up and running, but it will try to update again, though it might go better the second time.

**Comment by NicStarzi** [comment]
To be honest, I am not sure if I was running 1.5.1 or not. I did not download a newer version for weeks now. Does the application download a newer version by itself? Perhaps in the background?

Anyways, I deleted the 1.5.1 folder and successfully ran the 1.4.1 version. I will try to update to 1.5.1 again now.

**Comment by shiftkey** [comment]
@NicStarzi thanks for the report!

This error seems to be related to Electron not being able to find the installed app after the update is applied. Are you able to grab the latest Squirrel installer log as that might have some interesting clues about whether the application had some issue applying the update?

The file should be located at `%LOCALAPPDATA%\GitHubDesktop\SquirrelSetup.log`

**Comment by NicStarzi** [comment]
Here is the Log:
[SquirrelSetup.log](https://github.com/desktop/desktop/files/2707761/SquirrelSetup.log)

By he way: after having manually deleted the 1.5.1 version of the Application and doing a fresh update from 1.4.1 everything works fine now.

**Comment by msftrncs** [comment]
FYI, #5800, was the same starting version, maybe there was something wrong with the original 1.4.1 install process.

**Comment by shiftkey** [comment]
@NicStarzi thanks for the log. Here's my understanding of what happened:

On the 23rd of December, the delta packages between 1.4.1 and 1.5.1 were downloaded (to save bytes):

```
2018-12-23 19:19:06> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-1.4.2-delta.nupkg
2018-12-23 19:19:06> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-1.4.3-delta.nupkg
2018-12-23 19:19:06> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-1.5.0-delta.nupkg
2018-12-23 19:19:06> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-1.5.1-delta.nupkg
```

Then we had an error with accessing the destination directory to install the new version:

```
2018-12-23 19:28:57> IEnableLogger: Failed to install package to app dir: System.UnauthorizedAccessException: Access to the path 'C:\Users\ds\AppData\Local\GitHubDesktop\app-1.5.1\api-ms-win-core-processthreads-l1-1-1.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   ...
```

The updater logic then tried again but used the full package (just in case there was something wrong with the delta packages):

```
2018-12-23 19:28:04> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-1.5.1-full.nupkg
```

The same error occurred

```
2018-12-23 19:28:57> Program: Really couldn't apply updates!: System.UnauthorizedAccessException: Access to the path 'C:\Users\ds\AppData\Local\GitHubDesktop\app-1.5.1\api-ms-win-core-processthreads-l1-1-1.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   ...
```

On the 24th, it tried again with the delta packages:

```
2018-12-24 14:35:07> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-1.5.0-delta.nupkg
2018-12-24 14:35:07> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-1.4.2-delta.nupkg
2018-12-24 14:35:07> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-1.5.1-delta.nupkg
2018-12-24 14:35:07> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-1.4.3-delta.nupkg
```

It was able to install the files in the expected location:

```
2018-12-24 14:41:55> ApplyReleasesImpl: Writing files to app directory: C:\Users\ds\AppData\Local\GitHubDesktop\app-1.5.1
2018-12-24 14:41:55> LogHost: Rigging execution stub for lib/net45/GitHubDesktop_ExecutionStub.exe to C:\Users\ds\AppData\Local\GitHubDesktop\GitHubDesktop.exe
```

The only interesting error after that was this (some operation about updating the registry):

```
2018-12-24 14:42:40> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2018-12-24 14:42:40> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
```

This is inside the same `ApplyReleasesImpl` function, and maybe this unhandled error resulted in the updated version on-disk being in a broken state, but I'm not 100% sure right now. I have #5197 open to track upgrading our Electron Windows installer dependency (which might have already fixed this) and given we figured out a workaround I think I'm going to move this into #5197 to dig into this code and suggest a patch upstream.

**Comment by shiftkey** [comment]
As the install/upgrade process is not easy for us to patch, and we were able to workaround this issue, I'm going to close this out for now and track the upgrade error in #5197 which is the dependency we use to install and update the app.

The last comment from @NicStarzi also fits this theory:

> By the way: after having manually deleted the 1.5.1 version of the Application and doing a fresh update from 1.4.1 everything works fine now.

What happened here is that the Electron runtime was looking for the application's `package.json` file in a given location on launch:

```js
let packagePath = null
let packageJson = null
const searchPaths = ['app', 'app.asar', 'default_app.asar']
for (packagePath of searchPaths) {
  try {
    packagePath = path.join(process.resourcesPath, packagePath)
    packageJson = require(path.join(packagePath, 'package.json'))
    break
  } catch (error) {
    continue
  }
}
```

My theory here is that the upgrade process didn't apply correctly, and it couldn't find the `package.json`, triggering this error:

```js
if (packageJson == null) {
  process.nextTick(function () {
    return process.exit(1)
  })
  throw new Error('Unable to find a valid app')
}
```

**Comment by msftrncs** [comment]
@shiftkey, I just want to add a detail I think may have been missed.  The install of 1.5.1 did seem to complete (though maybe not correctly), and the user did successfully launch 1.5.1, and then it appears the updater started again and tried to update the app again, while it was running from the same folder it was trying to update.  This comes from the production log.  At 18:19Z, 1.5.1 was successfully started, then at 18:28Z it ran updater, and then the crash occurred.

**Comment by danniely** [comment]
After I redownloaded GitHubDesktopSetUp.exe and launched, it automatically fixed the issue. You guys should try.

**Comment by reginareynolds** [comment]
I just experienced the same issue. I attempted to push to origin, and an error message popped up, but I didn't screenshot it because I didn't think anything of it. I closed the application, and now when I try to restart it, the following appears:
![image](https://user-images.githubusercontent.com/14677252/59431211-48684980-8db2-11e9-8553-0f05cbf4af44.png)

The error code I got traces the problem back to a different line than @NicStarzi

**Comment by tierninho** [comment]
@reginareynolds Please see the latest comment from one of our engineers on this issue: https://github.com/desktop/desktop/issues/6486#issuecomment-450160955

Another user had success with: 

> After I redownloaded GitHubDesktopSetUp.exe and launched, it automatically fixed the issue. You guys should try.

**Comment by reginareynolds** [comment]
Hey, I went ahead and did as you suggested. The program opens now, but it immediately shows a new error message on opening
![image](https://user-images.githubusercontent.com/14677252/60282895-f9540580-98d5-11e9-9853-e567f8627bde.png)

Other than that inconvenience, it works fine once I dismiss the message

**Comment by tierninho** [comment]
@reginareynolds Looks like your gitconfig needs to be updated.

Do you see your username and email when you run `git config --global -l`?

**Comment by reginareynolds** [comment]
@tierninho Pretty sure I figured out the problem. I installed git separately before installing GitHub Desktop. The standalone version of git that I installed is configured, but since it's in a different installation directory, when GitHub Desktop searches for git configuration in its _own_ installation directory, it can't find anything.

**Comment by tierninho** [comment]
@reginareynolds Thank you for the update. Glad you figured it out!!

**Comment by stefanpejcic** [comment]
Having the same problem but the solution from @msftrncs worked for me. Thanks mate!

**Comment by bwack** [comment]
I'm having the same issue, but with app-2.1.3. I deleted that folder and then it started up fine with app-2.1.2. Then looking at the logs, it fails to update to 2.1.3.
[SquirrelSetup.log..zip](https://github.com/desktop/desktop/files/3721907/SquirrelSetup.log.zip)

**Comment by tierninho** [comment]
@bwack I see an error in your logs:

```
2019-10-13 17:15:23> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\hada\AppData\Local\GitHubDesktop\app-2.2.1\GitHubDesktop.exe: System.OperationCanceledException: Operasjonen ble avbrutt.
```

It sounds like you are ok now at 2.2.1?

If no, the first thing I would recommend trying would be a fresh installation of GitHub Desktop 2.1.3.

Here's how to do that:

- Close any running GitHub Desktop processes
- Open File Explorer
- Go to `%LocalAppData%` and delete the GitHubDesktop directory
- Go to` %AppData%` and delete the GitHub Desktop directory
- Reinstall GitHub Desktop

Let us know how that goes.

**Comment by bwack** [comment]
@tierninho I followed your instructions, except i installed Github desktop from desktop.github.com and got 2.2.1  right away. The log file is now new and has no errors.
