### ISSUE TITLE
Can't clone my repository to local pc

### ISSUE THREAD

**Issue by bluetata** [desktop/desktop#6512]
When I try to clone a repository , I can find any repo. list in the GitHub desktop. and the message: "Sorry ,I can't find that repository." will be shown.

Environment:
GitHub Desktop: 1.5.1
Windows 7 Pro (x64)

![image](https://user-images.githubusercontent.com/25427352/50545176-e4a7f500-0c45-11e9-817b-0f06db64c9ef.png)

**Comment by shiftkey** [comment]
@bluetata thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by bluetata** [comment]
@shiftkey thanks for your help.   
I had pasted the log, it's seems like there's no token for me. but I can still pull and push code to remote repo.

```log
2019-01-04T03:47:13.392Z - info: [ui] [AppStore] loading 5 repositories from store
2019-01-04T03:47:13.395Z - info: [ui] [AppStore] found account: bluetata (Sekito Lv)
2019-01-04T03:47:14.141Z - warn: [ui] Error refreshing account 'bluetata'
Error: Cannot update an account which doesn't have a token: bluetata
    at Object.n [as fatalError] (C:\Users\IBM_ADMIN\AppData\Local\GitHubDesktop\app-1.5.1\webpack:\app\src\ui\lib\button.tsx:139:4)
    at o (C:\Users\IBM_ADMIN\AppData\Local\GitHubDesktop\app-1.5.1\webpack:\app\src\lib\stores\accounts-store.ts:216:7)
    at l.tryUpdateAccount (C:\Users\IBM_ADMIN\AppData\Local\GitHubDesktop\app-1.5.1\webpack:\app\src\lib\stores\accounts-store.ts:138:6)
    at accounts.Promise.all.accounts.map (C:\Users\IBM_ADMIN\AppData\Local\GitHubDesktop\app-1.5.1\webpack:\app\src\lib\stores\accounts-store.ts:120:5)
    at Array.map (<anonymous>)
    at l.refresh (C:\Users\IBM_ADMIN\AppData\Local\GitHubDesktop\app-1.5.1\webpack:\app\src\lib\stores\accounts-store.ts:117:21)
    at Ce.loadInitialState (C:\Users\IBM_ADMIN\AppData\Local\GitHubDesktop\app-1.5.1\webpack:\app\src\lib\stores\app-store.ts:1396:4)
    at <anonymous>
2019-01-04T03:47:14.651Z - info: [ui] Executing getRemotes: git remote -v (took 1.244s)
2019-01-04T03:47:16.439Z - info: [ui] launching: 1.5.1 (Windows 6.1.7601)
2019-01-04T03:47:16.440Z - info: [ui] execPath: 'C:\Users\IBM_ADMIN\AppData\Local\GitHubDesktop\app-1.5.1\GitHubDesktop.exe'
2019-01-04T03:47:16.441Z - info: [ui] Executing getCommits: git log 05768db41b90b6a10c50a27f803cd358ed74682f --date=raw --max-count=1 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-show-signature --no-color -- (took 1.346s)
2019-01-04T03:47:16.638Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 1.057s)
2019-01-04T03:47:17.651Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 1.007s)
2019-01-04T03:47:18.395Z - info: [ui] Stats reported.
2019-01-04T03:47:19.260Z - info: [ui] Executing getRemotes: git remote -v (took 1.071s)
2019-01-04T03:47:19.620Z - info: [ui] Executing getCommits: git log origin/dev-writing..dev-writing --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-show-signature --no-color -- (took 1.225s)
2019-01-04T03:47:19.635Z - info: [ui] Executing getRemotes: git remote -v (took 1.153s)
2019-01-04T03:47:19.637Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.008s)
2019-01-04T03:47:20.184Z - info: [ui] Executing getCommits: git log origin/dev-writing..dev-writing --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-show-signature --no-color -- (took 1.366s)
2019-01-04T03:47:20.193Z - info: [ui] Executing getRemotes: git remote -v (took 1.186s)
2019-01-04T03:47:20.373Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.323s)
2019-01-04T03:47:20.504Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.029s)
2019-01-04T03:47:20.889Z - info: [ui] Executing getAheadBehind: git rev-list --left-right --count master...origin/master -- (took 1.106s)
2019-01-04T03:47:20.890Z - info: [ui] Executing getRemotes: git remote -v (took 1.247s)
2019-01-04T03:47:21.637Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 5.662s)
2019-01-04T03:47:22.009Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: concise-excel-vba - bluetata (empty token)
2019-01-04T03:47:22.011Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: concise-excel-vba - bluetata (empty token)
2019-01-04T03:47:22.043Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: concise-excel-vba - bluetata (empty token)
2019-01-04T03:47:26.756Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 4.434s)
2019-01-04T03:47:26.886Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 4.735s)
2019-01-04T03:47:28.415Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 6.191s)
2019-01-04T03:47:29.423Z - warn: [ui] fetchRepositories: Error: Requires authentication
2019-01-04T03:47:29.843Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune upstream (took 2.943s)
2019-01-04T03:47:29.899Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune upstream (took 3.126s)
2019-01-04T03:47:31.276Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune upstream (took 2.819s)

```

**Comment by shiftkey** [comment]
> I had pasted the log, it's seems like there's no token for me. but I can still pull and push code to remote repo.

@bluetata I suspect a `push` would fail - could you try logging out and in again to see if it addresses the issue?

**Comment by bluetata** [comment]
> 
> 
> > I had pasted the log, it's seems like there's no token for me. but I can still pull and push code to remote repo.
> 
> @bluetata I suspect a `push` would fail - could you try logging out and in again to see if it addresses the issue?

hi @shiftkey ,It worked as your said, when I retry sign out and login again. thanks a lot
