### ISSUE TITLE
Github launches, does not show repository and none of the menus work

### ISSUE THREAD

**Issue by seanjmcm** [desktop/desktop#6530]
## Description

Github for desktop launches.

Appears as here: https://imgur.com/a/rNufVa9

- Shows current repository but cannot click on anything and no files showing.

## Version

* GitHub Desktop:

Cannot get this data but updated it yesterday 2/1/19:  This is the appdata folder which may provide a clue: 

AppData/Local/GitHubDesktop
$ ls
 app.ico      **app-1.5.1/**             GitHubDesktop.exe*   Update.exe*
 **app-1.4.3/**   bin/                   packages/
 **app-1.5.0/**  'GitHub Desktop.exe'*   SquirrelSetup.log

**edit : Version 1.5.1**

* Operating system:

Windows 10 pro

## Steps to Reproduce

1. Commit a repository
2. Github for desktop says: github refreshing repository hang on
3. After a considerable wait, kill github for desktop.
4. Restart github for desktop

### Expected Behavior

Github to mwork as normal

### Actual Behavior

Github for Desktop is completely unresponsive after launch

## Additional Information

![github desktop](https://user-images.githubusercontent.com/9802201/50635084-b0d01680-0f48-11e9-92c8-4474ca9ad10f.png)

### Logs

Log file not present, folder a follows:

$ ls -l
total 10764
-rw-r--r-- 1 mcsean 197609  129000 Jun  7  2017  app.ico
drwxr-xr-x 1 mcsean 197609       0 Jan  2 09:56  app-1.4.3/
drwxr-xr-x 1 mcsean 197609       0 Dec  6 12:00  app-1.5.0/
drwxr-xr-x 1 mcsean 197609       0 Jan  2 09:56  app-1.5.1/
drwxr-xr-x 1 mcsean 197609       0 Sep 22  2017  bin/
-rwxr-xr-x 1 mcsean 197609  382424 Jul 20  2017 'GitHub Desktop.exe'*
-rwxr-xr-x 1 mcsean 197609  382424 Jan  2 09:56  GitHubDesktop.exe*
drwxr-xr-x 1 mcsean 197609       0 Jan  2 09:56  packages/
-rw-r--r-- 1 mcsean 197609 8361298 Jan  3 11:01  SquirrelSetup.log
-rwxr-xr-x 1 mcsean 197609 1659352 Jan  2 09:56  Update.exe*

**Comment by shiftkey** [comment]
@seanjmcm thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot what might be the underlying cause for the app becoming unresponsive.

**Comment by seanjmcm** [comment]
Hi Brendan,

I couldn't find the log files, I listed the directory contents, do any of those files/folders help?

In order to get around the issue, I did a `git reset --hard a1bXXXXX` to my last commit via commandline.   There were two more recent commits on the repository with which it seemed to have merge issues.  I branched and added my commit and working fine now.

It might be helpful if github desktop said something to that effect instead of freezing, imho.

**Comment by shiftkey** [comment]
> I couldn't find the log files, I listed the directory contents, do any of those files/folders help?

The log files are located at `%APPDATA%\GitHub Desktop\logs`, not under `%LOCALAPPDATA%`

**Comment by seanjmcm** [comment]
There's a choice of roaming or local. 

mcsean@mcsean MINGW64 ~/AppData
$ pwd
/c/Users/mcsean/AppData

mcsean@mcsean MINGW64 ~/AppData
$ ls -l
total 36
drwxr-xr-x 1 mcsean 197609 0 Jan  3 11:20 Local/
drwxr-xr-x 1 mcsean 197609 0 Nov 15  2017 LocalLow/
drwxr-xr-x 1 mcsean 197609 0 Dec  6 11:20 Roaming/

I just tried roaming  and it is there, (I've had to edit some of it as it is a work project).

`2019-01-03T10:53:54.841Z - info: [ui] Executing createCommit: git commit -F - (took 4.537s)
2019-01-03T10:54:16.774Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: LXXXX- seanjmcm (has token)
2019-01-03T10:54:26.898Z - info: [ui] Executing pull: git -c credential.helper= pull --no-rebase --progress origin (took 10.074s)
2019-01-03T10:54:26.900Z - error: [ui] `git -c credential.helper= pull --no-rebase --progress origin` exited with an unexpected code: 1.
Auto-merging XXX/YYY/Write XXXYYY.vi
CONFLICT (content): Merge conflict in XXX/YYY/Write XXXYYY.vi
Auto-merging Writer/subVIs/Database/Database Read PMAD Entry.vi
.......
.......
Automatic merge failed; fix conflicts and then commit the result.

warning: Cannot merge binary files:  XXX/YYY/Write XXXYYY.vi (HEAD vs. YYYYZZZ66adcf2ea5781fdbdc3c6641aXXXXXXXX)
.......
.......
(The error was parsed as 7: We found some conflicts while trying to merge. Please resolve the conflicts and commit the changes.)
2019-01-03T10:56:30.067Z - info: [ui] [AppStore] loading 7 repositories from store
2019-01-03T10:56:30.068Z - info: [ui] [AppStore] found account: seanjmcm (Sean McMahon)
2019-01-03T10:56:30.391Z - info: [ui] launching: 1.5.1 (Windows 10.0.17134)
2019-01-03T10:56:30.391Z - info: [ui] execPath: 'C:\Users\mcsean\AppData\Local\GitHubDesktop\app-1.5.1\GitHubDesktop.exe'
2019-01-03T10:57:18.982Z - info: [ui] [AppStore] loading 7 repositories from store
2019-01-03T10:57:18.983Z - info: [ui] [AppStore] found account: seanjmcm (Sean McMahon)
2019-01-03T10:57:19.313Z - info: [ui] launching: 1.5.1 (Windows 10.0.17134)
2019-01-03T10:57:19.313Z - info: [ui] execPath: 'C:\Users\mcsean\AppData\Local\GitHubDesktop\app-1.5.1\GitHubDesktop.exe'
2019-01-03T11:01:23.660Z - info: [ui] [AppStore] loading 7 repositories from store
2019-01-03T11:01:23.661Z - info: [ui] [AppStore] found account: seanjmcm (Sean McMahon)
2019-01-03T11:01:24.035Z - info: [ui] launching: 1.5.1 (Windows 10.0.17134)
2019-01-03T11:01:24.036Z - info: [ui] execPath: 'C:\Users\mcsean\AppData\Local\GitHubDesktop\app-1.5.1\GitHubDesktop.exe'
2019-01-03T11:18:25.661Z - info: [ui] [AppStore] loading 7 repositories from store
2019-01-03T11:18:25.661Z - info: [ui] [AppStore] found account: seanjmcm (Sean McMahon)
2019-01-03T11:18:25.836Z - warn: [ui] fetchMentionables: failed for seanjmcm/LXXXX
TypeError: Failed to fetch
2019-01-03T11:18:25.838Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2019-01-03T11:18:25.838Z - warn: [ui] fetchUser: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2019-01-03T11:18:25.839Z - warn: [ui] Error refreshing account 'seanjmcm'
TypeError: Failed to fetch
2019-01-03T11:18:26.000Z - warn: [ui] fetchIssues: failed for repository seanjmcm/LXXXX
TypeError: Failed to fetch
2019-01-03T11:18:26.006Z - warn: [ui] Unable to fetch issues for seanjmcm/LXXXX
TypeError: Failed to fetch
2019-01-03T11:18:26.006Z - warn: [ui] fetchPullRequests: failed for repository seanjmcm/LXXXX
TypeError: Failed to fetch
2019-01-03T11:18:26.007Z - warn: [ui] Error refreshing pull requests for 'LXXXX'
TypeError: Failed to fetch
2019-01-03T11:18:26.178Z - info: [ui] launching: 1.5.1 (Windows 10.0.17134)
2019-01-03T11:18:26.178Z - info: [ui] execPath: 'C:\Users\mcsean\AppData\Local\GitHubDesktop\app-1.5.1\GitHubDesktop.exe'
2019-01-03T11:18:27.731Z - error: [ui] Error checking for updates
Error: GitHub Desktop was not able to contact the update server. Ensure you have internet connectivity and try again.
    at Object.t.parseError (file:///C:/Users/mcsean/AppData/Local/GitHubDesktop/app-1.5.1/resources/app/renderer.js:16:97894)
    at onAutoUpdaterError (file:///C:/Users/mcsean/AppData/Local/GitHubDesktop/app-1.5.1/resources/app/renderer.js:10:24765)
    at CallbacksRegistry.apply (C:\Users\mcsean\AppData\Local\GitHubDesktop\app-1.5.1\resources\electron.asar\common\api\callbacks-registry.js:47:25)
    at EventEmitter.ipcRenderer.on (C:\Users\mcsean\AppData\Local\GitHubDesktop\app-1.5.1\resources\electron.asar\renderer\api\remote.js:277:21)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
2019-01-03T11:18:27.768Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.741s)
2019-01-03T11:18:49.685Z - info: [ui] [AppStore] loading 7 repositories from store
2019-01-03T11:18:49.686Z - info: [ui] [AppStore] found account: seanjmcm (Sean McMahon)
2019-01-03T11:18:49.838Z - info: [ui] launching: 1.5.1 (Windows 10.0.17134)
2019-01-03T11:18:49.838Z - info: [ui] execPath: 'C:\Users\mcsean\AppData\Local\GitHubDesktop\app-1.5.1\GitHubDesktop.exe'
2019-01-03T11:18:51.619Z - warn: [ui] fetchEmails: failed with endpoint https://api.github.com
Error: Server Error
    at Object.t.parsedResponse (C:\Users\mcsean\AppData\Local\GitHubDesktop\app-1.5.1\webpack:\app\src\lib\http.ts:161:4)
    at <anonymous>
2019-01-03T11:19:02.761Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 12.942s)
2019-01-03T11:19:05.757Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 7.363s)
2019-01-03T11:19:05.763Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 7.375s)
2019-01-03T11:19:06.851Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-show-signature --no-color -- (took 2.038s)
2019-01-03T11:19:11.494Z - info: [ui] Executing getFilesWithConflictMarkers: git diff --check (took 3.991s)
2019-01-03T11:25:26.165Z - info: [ui] [AppStore] loading 7 repositories from store
2019-01-03T11:25:26.166Z - info: [ui] [AppStore] found account: seanjmcm (Sean McMahon)
2019-01-03T11:25:26.333Z - info: [ui] launching: 1.5.1 (Windows 10.0.17134)
2019-01-03T11:25:26.333Z - info: [ui] execPath: 'C:\Users\mcsean\AppData\Local\GitHubDesktop\app-1.5.1\GitHubDesktop.exe'
2019-01-03T11:25:31.873Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.376s)
2019-01-03T11:27:29.399Z - info: [ui] Background fetch for 7 repositories took 3.193sec
2019-01-03T11:31:19.977Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: LXXXX- seanjmcm (has token)
2019-01-03T11:31:21.465Z - info: [ui] Executing checkoutBranch: git -c credential.helper= checkout --progress 2017 -- (took 1.484s)
2019-01-03T11:32:12.160Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: LXXXX- seanjmcm (has token)
2019-01-03T11:32:18.552Z - info: [ui] Executing push: git -c credential.helper= push origin 2017 --set-upstream --progress (took 6.372s)
2019-01-03T11:32:19.661Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.107s)
2019-01-03T11:32:38.519Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: LXXXX- seanjmcm (has token)
2019-01-03T11:32:39.654Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.121s)
2019-01-03T11:42:31.873Z - info: [ui] Background fetch for 7 repositories took 1.747sec
2019-01-03T11:57:32.357Z - info: [ui] Background fetch for 7 repositories took 2.231sec
2019-01-03T12:06:13.460Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.329s)`

**Comment by steveward** [comment]
@seanjmcm thanks for sharing the log file.  I'm glad to hear you were able to work around this.

Did this issue happen immediately when you opened GitHub Desktop for the first time that day, or did it happen after you attempted the pull referenced here? 

```
2019-01-03T10:54:26.900Z - error: [ui] `git -c credential.helper= pull --no-rebase --progress origin` exited with an unexpected code: 1.
Auto-merging XXX/YYY/Write XXXYYY.vi
CONFLICT (content): Merge conflict in XXX/YYY/Write XXXYYY.vi
Auto-merging Writer/subVIs/Database/Database Read PMAD Entry.vi
.......
.......
Automatic merge failed; fix conflicts and then commit the result.

warning: Cannot merge binary files:  XXX/YYY/Write XXXYYY.vi (HEAD vs. YYYYZZZ66adcf2ea5781fdbdc3c6641aXXXXXXXX)
.......
.......
```

Also, is the `XXX/YYY/Write XXXYYY.vi` binary file a fairly large file?

**Comment by steveward** [comment]
@seanjmcm thanks for the clarification. GitHub Desktop's error messaging is something that we definitely know can be improved. We'd love to see the community contribute PRs to improve this if you are ever interested.

Since I have not seen any other reports of this freezing behavior you encountered I am going to close this issue out for the time being. Let me know if you continue to run into this issue and we can keep investigating further.
