### ISSUE TITLE
Can't sign in to my Enterprise account using Desktop App after last update

### ISSUE THREAD

**Issue by imonteroq** [desktop/desktop#7434]
## Description
It seems that after the last update, Enterprise sign-in on the Desktop App has stopped working. After following the standard process and successfully authenticating in the browser, the app gives an error: "Unable to fetch authenticated user. I have tried authenticating with Safari and Chrome and neither will work. Other colleagues have experienced the same issue.

It would be great to get some help on this and also access to older versions while the issue is being fixed.

Thanks a mil.

* Github Desktop Version
1.6.5

* GitHub Enterprise Version:
2.15.5

* Operating system:
MacOS Mojave

## Steps to Reproduce
1. Open Desktop App
2. Go to Github Desktop > Preferences > Accounts > Enterprise > Sign in
3. Type in the repository url.
4. Click on Continue with Browser.
5. Authenticate.
6. App gives "Unable to fetch authenticated user" error

### Expected Behavior
I should be able to interact with repositories under my Enterprise account in the Desktop app.

### Actual Behavior
App gives "Unable to fetch authenticated user" error after browser-based authentication.

## Additional Information
One of my colleagues has found an older version and it is able to sign in without any problems.

**Comment by billygriffin** [comment]
Hi @imonteroq, thanks for the report and sorry you're having problems! We've seen this pop up for a few folks, but it's difficult to diagnose your issue without understanding more about your configuration. Would you mind uploading a log file from `Help` -> `Show Logs in Finder` to help us further investigate?

**Comment by imonteroq** [comment]
Hi @billygriffin , thanks for prompt response. Is there anything in the logs that I should mask so that it does not compromise any security features of my company?

**Comment by steveward** [comment]
@imonteroq the main things that would be visible would be your GitHub Enterprise URL, repository names, and your account name. If you spot the error message related to the authentication issue you can cut and paste that into an issue reply and mask any private information.

**Comment by imonteroq** [comment]
```
2019-04-30T08:57:14.285Z - info: [ui] [SignInStore] initializing OAuth flow
2019-04-30T08:57:14.304Z - info: [main] opening in browser: https://github.xxxxxx.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user&state=a99163f2-666f-495f-b069-300174bd5163
2019-04-30T08:57:14.304Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-04-30T08:57:14.311Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-04-30T08:57:17.320Z - info: [main] Processing protocol url
2019-04-30T08:57:17.320Z - info: [ui] [Dispatcher] requesting authenticated user
2019-04-30T08:57:17.322Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-04-30T08:57:17.809Z - warn: [ui] deserialize: invalid JSON found at 'https://github.groupondev.com/login/oauth/access_token' - status: 401, length: '(missing)' id: '(missing)'
SyntaxError: Unexpected token < in JSON at position 0
    at o (/webpack:/app/src/lib/http.ts:63:5)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:156:6)
    at Object.t.requestOAuthToken (/webpack:/app/src/lib/api.ts:885:5)
2019-04-30T08:57:17.809Z - warn: [ui] requestOAuthToken: failed with endpoint https://github.xxxxxx.com/api/v3
Error: API error https://github.xxxxxx.com/login/oauth/access_token: Unauthorized (401)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:157:26)
2019-04-30T08:57:17.812Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at t.Dispatcher.dispatchURLAction (/webpack:/app/src/ui/dispatcher/dispatcher.ts:953:32)
```

**Comment by imonteroq** [comment]
Hi, I believe this is the error part in the log file. Please let me know if you need further details. Thanks a mil!

```
2019-04-30T08:57:14.285Z - info: [ui] [SignInStore] initializing OAuth flow
2019-04-30T08:57:14.304Z - info: [main] opening in browser: https://github.xxxxxx.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user&state=a99163f2-666f-495f-b069-300174bd5163
2019-04-30T08:57:14.304Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-04-30T08:57:14.311Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-04-30T08:57:17.320Z - info: [main] Processing protocol url
2019-04-30T08:57:17.320Z - info: [ui] [Dispatcher] requesting authenticated user
2019-04-30T08:57:17.322Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-04-30T08:57:17.809Z - warn: [ui] deserialize: invalid JSON found at 'https://github.xxxxxx.com/login/oauth/access_token' - status: 401, length: '(missing)' id: '(missing)'
SyntaxError: Unexpected token < in JSON at position 0
    at o (/webpack:/app/src/lib/http.ts:63:5)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:156:6)
    at Object.t.requestOAuthToken (/webpack:/app/src/lib/api.ts:885:5)
2019-04-30T08:57:17.809Z - warn: [ui] requestOAuthToken: failed with endpoint https://github.xxxxxx.com/api/v3
Error: API error https://github.xxxxxx.com/login/oauth/access_token: Unauthorized (401)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:157:26)
2019-04-30T08:57:17.812Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at t.Dispatcher.dispatchURLAction (/webpack:/app/src/ui/dispatcher/dispatcher.ts:953:32)
```

**Comment by steveward** [comment]
@imonteroq can you try resetting GitHub Desktop to see if that helps with this issue?

1. Close GitHub Desktop
2. Delete all of the files under `~/Library/Application Support/GitHub Desktop/`
3. Restart GitHub Desktop and try logging in again

**Comment by imonteroq** [comment]
@steveward I have just tried and the issue persists.
Thanks. Find below the full log output:

```
2019-05-01T09:36:14.433Z - info: [ui] [AppStore] loading 0 repositories from store
2019-05-01T09:36:14.597Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-05-01T09:36:14.597Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-05-01T09:36:14.597Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-05-01T09:36:14.597Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-05-01T09:36:14.598Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-05-01T09:36:14.754Z - info: [ui] launching: 1.6.5 (Mac OS 10.14.4)
2019-05-01T09:36:14.755Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
2019-05-01T09:36:14.756Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-05-01T09:36:14.762Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-05-01T09:36:14.780Z - info: [ui] Opt in reported.
2019-05-01T09:36:14.780Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-05-01T09:36:15.994Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-05-01T09:36:21.893Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-05-01T09:36:22.873Z - info: [ui] [Welcome] advancing to step: SignInToEnterprise
2019-05-01T09:36:22.875Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2019-05-01T09:36:31.530Z - info: [ui] [Welcome] kind EndpointEntry is the same as EndpointEntry. ignoring...
2019-05-01T09:36:34.672Z - info: [ui] [SignInStore] initializing OAuth flow
2019-05-01T09:36:34.692Z - info: [main] opening in browser: https://github.xxxxxx.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user&state=3b92df95-a099-4389-949b-342281fb0418
2019-05-01T09:36:34.692Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-05-01T09:36:34.713Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-05-01T09:36:41.917Z - info: [main] Processing protocol url
2019-05-01T09:36:41.921Z - info: [ui] [Dispatcher] requesting authenticated user
2019-05-01T09:36:41.922Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-05-01T09:36:42.385Z - warn: [ui] deserialize: invalid JSON found at 'https://github.xxxxxx.com/login/oauth/access_token' - status: 401, length: '(missing)' id: '(missing)'
SyntaxError: Unexpected token < in JSON at position 0
    at o (/webpack:/app/src/lib/http.ts:63:5)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:156:6)
    at Object.t.requestOAuthToken (/webpack:/app/src/lib/api.ts:885:5)
2019-05-01T09:36:42.385Z - warn: [ui] requestOAuthToken: failed with endpoint https://github.xxxxxx.com/api/v3
Error: API error https://github.xxxxxx.com/login/oauth/access_token: Unauthorized (401)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:157:26)
2019-05-01T09:36:42.387Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at t.Dispatcher.dispatchURLAction (/webpack:/app/src/ui/dispatcher/dispatcher.ts:953:32)
2019-05-01T09:36:42.388Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-05-01T09:36:45.046Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-05-01T09:36:50.288Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-05-01T09:37:04.299Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...

```

**Comment by steveward** [comment]
@imonteroq thanks for trying that. Can you verify that there is no longer an application password stored for your GitHub Enterprise account in `Keychain Access.app`? It should look like `GitHub - https://<your_enterprise_url>/api/v3`.

Also, is there anything in your network that could be interfering with the authentication request to your GitHub Enterprise server? 

We can also try investigating the request by using the Developer Tools. Here's how to do that:

 - launch the app, then click **View | Toggle Developer Tools**
 - switch to the **Network** tab
 - trigger the issue by attempting to log in
 - select the problem request and inspect the **Headers** and **Response**  to see if there is any useful information

Let me know if that shows anything interesting.

**Comment by imonteroq** [comment]
Hi @stew],

All my team mates are having the same issue and we've all had to downgrade to the older version. We are actually based in different places, some working from the office and others from home. We are connected through the company's VPN but we've been doing this since we joined and never had an issue. I don't think it has to do with set-up.

Regarding the Headers and Response, what should I look for? Find below a couple of attributes:
**Status**: 304 Not Modified
"verifiable_password_authentication": false

Thanks once again.

**Comment by steveward** [comment]
@imonteroq what specific version of GitHub Desktop did you downgrade to that is working without issue?

**Comment by imonteroq** [comment]
@steveward , I couldn't find any earlier version so I downloaded the old app from here: https://central.github.com/mac/latest

**Comment by steveward** [comment]
@imonteroq that's an older version of GitHub Desktop that is no longer being updated (the last release was a couple of years ago). At this time it's not possible to roll back to previous versions of GitHub Desktop.

@desktop/engineering anyone have any ideas about what could be causing this auth issue? I'm out of ideas. https://github.com/desktop/desktop/issues/4866 and https://github.com/desktop/desktop/issues/3399 look similar.

**Comment by imonteroq** [comment]
@steveward thanks for that! We are aware of that, we just needed a simple way to keep pushing our code to our repo.

**Comment by imonteroq** [comment]
Hi,

Has anybody been able to look at this so far?

Thanks.

**Comment by tierninho** [comment]
@imonteroq Based on you logs:
 
> 2019-05-01T09:36:42.385Z - warn: [ui] deserialize: invalid JSON found at 'https://github.xxxxxx.com/login/oauth/access_token' - status: 401, length: '(missing)' id: '(missing)'
SyntaxError: Unexpected token < in JSON at position 0

There is a similar [issue](https://github.com/desktop/desktop/issues/3399) and I'd love to see what the response body is for these requests - maybe something is intercepting the request and serving up different, non-JSON content? 

Here's what I'd like to try:

 - launch the app, then click **View | Toggle Developer Tools**
 - switch to the **Network** tab
 - trigger the issue (by switching repository or whatever)
 - select a problem request and inspect the **Headers** and **Response** 

If you find something interesting, could you attach that here?

**Comment by tierninho** [comment]
@imonteroq  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
