### ISSUE TITLE
Cannot open Github Desktop

### ISSUE THREAD

**Issue by jtrinh21** [desktop/desktop#7701]
This is what I have repeatedly got when running Github Desktop

Error: spawn C:\Users\trinh\AppData\Local\GitHubDesktop\Update.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Version: 2.0.2
OS: Windows 10.0.17134

**Comment by shiftkey** [comment]
@jtrinh21 did this get resolved?

**Comment by jtrinh21** [comment]
@shiftkey

**Comment by shiftkey** [comment]
@jtrinh21 are you able to elaborate on the steps you ran before encountering this issue?

`EACCESS` is a generic permissions issue reported by Node while it tries to launch the file, and I wonder if there's some way to get this back to a good state...

**Comment by jtrinh21** [comment]
@shiftkey the laptop was shut down completely before I turned it on and then double-clicked at the Github Desktop to run it as usual. I did not modify or change any folder at all..

**Comment by jtrinh21** [comment]
I just uninstalled and reinstalled the application. The problem is solved now. Thank you so much for helping me. Much appreciated!

**Comment by shiftkey** [comment]
@jtrinh21 I'm glad you were able to get back to a good place!

**Comment by krishnadubagunta** [comment]
@shiftkey I have the same problem and this is the error that I could find on the console, 

```json
{
  "message": "Transaction committed too early. See http://bit.ly/2kdckMn",
  "name": "PrematureCommitErrror",
  "_e": {
    "stack": "Error
    at k (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:10:179048)
    at new n (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:10:226448)
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:10:199938
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:10:186060
    at Y (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:10:183139)
    at J (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:10:183798)
    at $ (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:10:183652)"
  }
}
```

**Comment by shiftkey** [comment]
@krishnadubagunta this is a different error to what was reported earlier.

Please open a fresh issue and fill out the **Bug report** template so we can investigate it.
