### ISSUE TITLE
process spawn failure when cmd.exe is inaccessible

### ISSUE THREAD

**Issue by tsymiar** [desktop/desktop#7716]
```
Error: spawn C:\WINDOWS\system32\cmd.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Version: 2.0.3
OS: Windows 10.0.18362

the alert poped out when click “Repository -> Open in Commond Prompt” menu.

**Comment by shiftkey** [comment]
@tsymiar thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by tsymiar** [comment]
Here is the log of the day, the .log file can not upload.
> 2019-06-06T11:27:10.185Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 13.407s)
2019-06-06T11:27:16.015Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MyAutomatic - tsymiar (has token)
2019-06-06T11:27:16.532Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 6.538s)
2019-06-06T11:27:20.901Z - info: [ui] Executing getAheadBehind: git rev-list --left-right --count gh-pages...origin/gh-pages -- (took 2.840s)
2019-06-06T11:27:35.461Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 19.350s)
2019-06-06T11:27:39.837Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 3.876s)
2019-06-06T11:27:40.167Z - info: [ui] Background fetch for 5 repositories took 43.420sec
2019-06-06T11:27:41.665Z - info: [ui] Executing getStashSize: git log -g -z --pretty=%gd%x1F%H%x1F%gs refs/stash (took 1.480s)
2019-06-06T11:27:41.687Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%h%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-show-signature --no-color -- (took 1.526s)
2019-06-06T11:27:41.695Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.522s)
2019-06-06T11:27:44.239Z - info: [ui] Executing getCommitDiff: git log b26d9dd3dcfa27b223beda26d2101b6fe2722791 -m -1 --first-parent --patch-with-raw -z --no-color -- js/main.js (took 2.302s)
2019-06-06T11:27:50.127Z - info: [ui] [AppStore] loading 5 repositories from store
2019-06-06T11:27:50.128Z - info: [ui] [AppStore] found account: tsymiar (tsymiar)
2019-06-06T11:27:50.593Z - info: [ui] launching: 2.0.0 (Windows 10.0.18362)
2019-06-06T11:27:50.594Z - info: [ui] execPath: 'C:\Users\dell-pc\AppData\Local\GitHubDesktop\app-2.0.0\GitHubDesktop.exe'
2019-06-06T11:27:52.009Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.439s)
2019-06-06T11:29:55.793Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: 4AxisFlying - tsymiar (has token)
2019-06-06T11:30:05.380Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 9.479s)
2019-06-06T11:30:07.664Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.895s)
2019-06-06T11:30:07.709Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- MDK-ARM/4axisflying.uvguix.dell-pc (took 1.965s)
2019-06-06T11:30:11.671Z - info: [ui] Executing getChangedFiles: git log 1db32ae8223c2d26b2f5c715949a1485391cf1cb -C -M -m -1 --no-show-signature --first-parent --name-status --format=format: -z -- (took 2.955s)
2019-06-06T11:30:12.080Z - info: [ui] Background fetch for 5 repositories took 21.878sec
2019-06-06T15:18:49.312Z - info: [ui] [AppStore] loading 5 repositories from store
2019-06-06T15:18:49.314Z - info: [ui] [AppStore] found account: tsymiar (tsymiar)
2019-06-06T15:18:50.246Z - info: [ui] launching: 2.0.3 (Windows 10.0.18362)
2019-06-06T15:18:50.247Z - info: [ui] execPath: 'C:\Users\dell-pc\AppData\Local\GitHubDesktop\app-2.0.3\GitHubDesktop.exe'
2019-06-06T15:18:51.177Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.408s)
2019-06-06T15:18:53.846Z - info: [ui] Stats reported.
2019-06-06T15:18:54.655Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 4.007s)
2019-06-06T15:18:55.976Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%h%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-show-signature --no-color -- (took 1.019s)
2019-06-06T15:19:04.866Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 7.517s)
2019-06-06T15:21:08.203Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 3.127s)
2019-06-06T15:21:08.555Z - info: [ui] Background fetch for 5 repositories took 18.557sec
2019-06-06T15:36:15.446Z - info: [ui] Background fetch for 5 repositories took 6.449sec
2019-06-06T15:39:16.094Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 2.747s)
2019-06-06T15:48:19.125Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.655s)
2019-06-06T15:48:23.191Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- WinNTKline/MfcUtil/opencv/CvimgMat.cc (took 4.063s)
2019-06-06T15:50:03.055Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 5.903s)
2019-06-06T15:51:13.214Z - info: [ui] Background fetch for 5 repositories took 4.218sec
2019-06-06T16:06:12.791Z - info: [ui] Background fetch for 5 repositories took 3.794sec
2019-06-06T16:21:01.925Z - info: [ui] Executing getConfigValueInPath: git config -z protocol.version (took 3.884s)
2019-06-06T16:21:08.177Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 6.252s)
2019-06-06T16:21:10.340Z - info: [ui] Executing getAheadBehind: git rev-list --left-right --count gh-pages...origin/gh-pages -- (took 1.050s)
2019-06-06T16:21:14.446Z - info: [ui] Background fetch for 5 repositories took 5.450sec
2019-06-06T16:36:12.787Z - info: [ui] Background fetch for 5 repositories took 3.790sec
2019-06-06T16:51:14.289Z - info: [ui] Background fetch for 5 repositories took 5.293sec
2019-06-06T16:52:10.663Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 6.532s)
2019-06-06T17:06:13.115Z - info: [ui] Background fetch for 5 repositories took 4.119sec
2019-06-06T17:21:13.526Z - info: [ui] Background fetch for 5 repositories took 4.529sec
2019-06-06T17:23:10.978Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 5.874s)
2019-06-06T17:36:13.237Z - info: [ui] Background fetch for 5 repositories took 4.241sec
2019-06-06T17:51:16.355Z - info: [ui] Background fetch for 5 repositories took 7.359sec
2019-06-06T17:54:10.191Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 5.091s)
2019-06-06T18:06:13.114Z - info: [ui] Background fetch for 5 repositories took 4.117sec
2019-06-06T18:21:14.003Z - info: [ui] Background fetch for 5 repositories took 5.008sec
2019-06-06T18:25:10.162Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 5.955s)
2019-06-06T18:36:12.321Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 3.323s)
2019-06-06T18:36:15.883Z - info: [ui] Background fetch for 5 repositories took 6.887sec
2019-06-06T18:51:14.235Z - info: [ui] Background fetch for 5 repositories took 5.238sec
2019-06-06T18:56:08.314Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 5.194s)
2019-06-06T19:00:27.033Z - info: [ui] Executing createCommit: git commit -F - (took 1.990s)
2019-06-06T19:00:28.674Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MyAutomatic - tsymiar (has token)
2019-06-06T19:01:05.784Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin auto-dev:auto-dev --progress (took 36.900s)
2019-06-06T19:01:13.256Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MyAutomatic - tsymiar (has token)
2019-06-06T19:01:22.810Z - error: [main] Error: spawn C:\WINDOWS\system32\cmd.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2019-06-06T19:01:23.498Z - info: [main] Error report submitted
2019-06-06T19:01:30.885Z - info: [ui] [AppStore] loading 5 repositories from store
2019-06-06T19:01:30.886Z - info: [ui] [AppStore] found account: tsymiar (tsymiar)
2019-06-06T19:01:31.827Z - info: [ui] launching: 2.0.3 (Windows 10.0.18362)
2019-06-06T19:01:31.828Z - info: [ui] execPath: 'C:\Users\dell-pc\AppData\Local\GitHubDesktop\app-2.0.3\GitHubDesktop.exe'
2019-06-06T19:01:32.728Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.479s)
2019-06-06T19:01:34.850Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MyAutomatic - tsymiar (has token)
2019-06-06T19:01:40.301Z - error: [main] Error: spawn C:\WINDOWS\system32\cmd.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2019-06-06T19:01:40.946Z - info: [main] Error report submitted
2019-06-06T19:01:44.574Z - info: [ui] [AppStore] loading 5 repositories from store
2019-06-06T19:01:44.575Z - info: [ui] [AppStore] found account: tsymiar (tsymiar)
2019-06-06T19:01:45.327Z - info: [ui] launching: 2.0.3 (Windows 10.0.18362)
2019-06-06T19:01:45.328Z - info: [ui] execPath: 'C:\Users\dell-pc\AppData\Local\GitHubDesktop\app-2.0.3\GitHubDesktop.exe'
2019-06-06T19:02:21.453Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MyAutomatic - tsymiar (has token)
2019-06-06T19:02:26.444Z - info: [ui] Executing pull: git -c credential.helper= -c protocol.version=2 pull --progress origin (took 4.701s)
2019-06-06T19:02:29.923Z - error: [main] Error: spawn C:\WINDOWS\system32\cmd.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2019-06-06T19:02:30.549Z - info: [main] Error report submitted
2019-06-06T19:02:37.111Z - info: [main] opening in browser: https://github.com/desktop/desktop/issues
2019-06-06T19:04:03.792Z - info: [ui] [AppStore] loading 5 repositories from store
2019-06-06T19:04:03.794Z - info: [ui] [AppStore] found account: tsymiar (tsymiar)
2019-06-06T19:04:04.415Z - info: [ui] launching: 2.0.3 (Windows 10.0.18362)
2019-06-06T19:04:04.415Z - info: [ui] execPath: 'C:\Users\dell-pc\AppData\Local\GitHubDesktop\app-2.0.3\GitHubDesktop.exe'
2019-06-06T19:04:06.460Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MyAutomatic - tsymiar (has token)
2019-06-06T19:06:10.754Z - info: [ui] Background fetch for 5 repositories took 6.883sec
2019-06-06T19:08:49.261Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin auto-dev:auto-dev --progress (took 282.650s)
2019-06-06T19:13:58.686Z - error: [main] Error: spawn C:\WINDOWS\system32\cmd.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2019-06-06T19:13:59.359Z - info: [main] Error report submitted
2019-06-06T19:14:11.717Z - info: [ui] [AppStore] loading 5 repositories from store
2019-06-06T19:14:11.718Z - info: [ui] [AppStore] found account: tsymiar (tsymiar)
2019-06-06T19:14:12.468Z - info: [ui] launching: 2.0.3 (Windows 10.0.18362)
2019-06-06T19:14:12.469Z - info: [ui] execPath: 'C:\Users\dell-pc\AppData\Local\GitHubDesktop\app-2.0.3\GitHubDesktop.exe'
2019-06-06T19:14:28.302Z - error: [main] Error: spawn C:\WINDOWS\system32\cmd.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2019-06-06T19:14:28.814Z - info: [main] Error report submitted
2019-06-06T19:14:32.999Z - info: [ui] [AppStore] loading 5 repositories from store
2019-06-06T19:14:33.000Z - info: [ui] [AppStore] found account: tsymiar (tsymiar)
2019-06-06T19:14:33.805Z - info: [ui] launching: 2.0.3 (Windows 10.0.18362)
2019-06-06T19:14:33.805Z - info: [ui] execPath: 'C:\Users\dell-pc\AppData\Local\GitHubDesktop\app-2.0.3\GitHubDesktop.exe'
2019-06-06T19:16:38.846Z - info: [ui] Background fetch for 5 repositories took 4.847sec
2019-06-06T19:19:02.855Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MyAutomatic - tsymiar (has token)
2019-06-06T19:19:09.892Z - error: [main] Error: spawn C:\WINDOWS\system32\cmd.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2019-06-06T19:19:10.534Z - info: [main] Error report submitted
2019-06-06T19:19:14.928Z - info: [ui] [AppStore] loading 5 repositories from store
2019-06-06T19:19:14.929Z - info: [ui] [AppStore] found account: tsymiar (tsymiar)
2019-06-06T19:19:15.661Z - info: [ui] launching: 2.0.3 (Windows 10.0.18362)
2019-06-06T19:19:15.662Z - info: [ui] execPath: 'C:\Users\dell-pc\AppData\Local\GitHubDesktop\app-2.0.3\GitHubDesktop.exe'

**Comment by shiftkey** [comment]
@tsymiar thanks for the log files.

While I don't have a full answer for what's happening I want to call out two theories that I have, based on the log file output:

1. It looks like this `EACCESS` error is occurring as part of a Git hook to the repository, running immediately after some Git operations. Do you have Git hooks enabled for this repository? Can you share an example of what the Git hook is trying to do here?

```
2019-06-06T19:08:49.261Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin auto-dev:auto-dev --progress (took 282.650s)
2019-06-06T19:13:58.686Z - error: [main] Error: spawn C:\WINDOWS\system32\cmd.exe EACCES
at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
at onErrorNT (internal/child_process.js:406:16)
at process._tickCallback (internal/process/next_tick.js:63:19)
```

2. The `EACCESS` error is beign raised for `C:\WINDOWS\system32\cmd.exe`, which should be accessible to all users unless there's been a permissions change. Are you able to run **Command Prompt** outside Desktop and see that work?

**Comment by tsymiar** [comment]
@shiftkey I can run git commands with the **Windows Command Line**, but sometimes can not open it by the **Command Prompt** menu item, it seems not must appear. I can commit success inside Desktop, but got failure when try to push to remote, whatever by the menu item or the sync button.

**Comment by shiftkey** [comment]
> I can commit success inside Desktop, but got failure when try to push to remote, whatever by the menu item or the sync button.

I believe there are some hooks enable in your repository. Can you share the names of the files in your `.git/hooks/` directory?

**Comment by tsymiar** [comment]
@shiftkey here are the files in the `.git/hooks/` directory:
```
-rwxrwxrwx 1 wsl wsl  478 Dec 16  2017 applypatch-msg.sample*
-rwxrwxrwx 1 wsl wsl  896 Dec 16  2017 commit-msg.sample*
-rwxrwxrwx 1 wsl wsl  189 Dec 16  2017 post-update.sample*
-rwxrwxrwx 1 wsl wsl  424 Dec 16  2017 pre-applypatch.sample*
-rwxrwxrwx 1 wsl wsl 1642 Dec 16  2017 pre-commit.sample*
-rwxrwxrwx 1 wsl wsl 1492 Dec 16  2017 prepare-commit-msg.sample*
-rwxrwxrwx 1 wsl wsl 1348 Dec 16  2017 pre-push.sample*
-rwxrwxrwx 1 wsl wsl 4898 Dec 16  2017 pre-rebase.sample*
-rwxrwxrwx 1 wsl wsl  544 Dec 16  2017 pre-receive.sample*
-rwxrwxrwx 1 wsl wsl 3610 Dec 16  2017 update.sample*
```

**Comment by shiftkey** [comment]
@tsymiar thanks for that. As all of the files end in `.sample`, these are not active hooks in the repository so I'm going to put that aside for now.

Coming back to this comment:

> I can run git commands with the **Windows Command Line**, but sometimes can not open it by the **Command Prompt** menu item, it seems not must appear.

The **Command Prompt** menu item not working here feels like it's the same thing as this error, just manifesting differently:

> ` Error: spawn C:\WINDOWS\system32\cmd.exe EACCES`

I don't know specifically how this might be triggered, but maybe the current user doesn't have permissions to launch this. What happens if you go to this path in Explorer and double-click to run it?

> I can commit success inside Desktop, but got failure when try to push to remote, whatever by the menu item or the sync button.

My previous theory here was that a Git hook was running after the push, but given there's no active hooks I think something else is running here that is trying to launch `cmd.exe`. Do you have Git LFS enabled for this repository?

**Comment by shiftkey** [comment]
cc @desktop/support for any extra ideas to investigate here

**Comment by tsymiar** [comment]
@shiftkey current user could run the `cmd.exe` in the `C:\WINDOWS\system32` directory, because the user was logged as administrator. I had enabled Git LFS to upload binary files to this repository before, does it affect?

**Comment by shiftkey** [comment]
>  I had enabled Git LFS to upload binary files to this repository before, does it affect?

It might. I'm hazy on how Git LFS could be using `cmd.exe`, but it does fit with everything else we're seeing.

**Comment by tsymiar** [comment]
@shiftkey the newest version 2.1.0 seems case this issue repeatedly, at first time when I opened **Repository | Open in Command Prompt** menu item,  the Desktop alerted an error message below, then I clicked the **Exit and restart** button and open the menu item again, the Desktop would alert the message again. Restart again, the Desktop will alert over again.

```
Error: spawn C:\WINDOWS\system32\cmd.exe EACCES

    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Version: 2.1.0
OS: Windows 10.0.18362
```

**Comment by tierninho** [comment]
@tsymiar This is a hard one to track down. Based on some research, it seems like one of the hook(s) doesn't have execute permissions, but I can't say for certain.

@steveward any thoughts?

**Comment by billygriffin** [comment]
I'd love to find an answer to this one, but it seems like it's particularly vexing and I don't know that we're going to be able to track it down. I'm really sorry @tsymiar - sometimes with _just the right configuration_ it's just too complex for us to be able to get to the bottom of what might be causing something like this. If you have any more clues that might help, let us know, but for now I'm going to close this issue. Apologies again.
