### ISSUE TITLE
Failed to execute "clone" and "Push origin"

### ISSUE THREAD

**Issue by xueqing** [desktop/desktop#7774]
## Description

I have succeed to sign in and connect to my github, but I cannot find my repositories. Besides, after commiting my changes locally, I failed to execute "Push origin". BTW, I can choose repositories cloned before and execute "Fetch origin".

## Version
2.0.3
* GitHub Desktop:
Microsoft Windows [Version 10.0.17763.503]
* Operating system:
Windows

## Steps to Reproduce
1. `commit`
2. `Push origin`

### Expected Behavior

Push to my remote github repository.

### Actual Behavior

Error happened:
Authentication failed. You may not have permissson to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permisson to accesss this repository.

## Additional Information

I didn't update my app before, and I didn't meet these problems in the past time. These problems seem to start to happen about two weeks ago. And I fail to look through and clone my remote repository today. I also update my app to v2.0.3 today.
BTW, I can clone and push with git bash tools.
I find `2019-06-12T02:20:50.051Z - warn: [ui] searchForUserWithEmail: not found 'hj.chen@bmi-win'` in your specific log file. But I don't know how to modify the email account.

### Logs

[2019-06-12.desktop.production.log](https://github.com/desktop/desktop/files/3279331/2019-06-12.desktop.production.log)

**Comment by shiftkey** [comment]
@xueqing thanks for the report! It looks like the underlying token that Desktop needs has gone missing from the Credential store on Windows:

```
2019-06-12T02:18:38.757Z - warn: [ui] Error refreshing account 'xueqing'
Error: Cannot update an account which doesn't have a token: xueqing
    at Object.n [as fatalError] (C:\Users\kiki\AppData\Local\GitHubDesktop\app-2.0.3\webpack:\external "path":1:1)
    at o (C:\Users\kiki\AppData\Local\GitHubDesktop\app-2.0.3\webpack:\app\src\lib\stores\accounts-store.ts:217:7)
    at l.tryUpdateAccount (C:\Users\kiki\AppData\Local\GitHubDesktop\app-2.0.3\webpack:\app\src\lib\stores\accounts-store.ts:139:6)
    at accounts.Promise.all.accounts.map (C:\Users\kiki\AppData\Local\GitHubDesktop\app-2.0.3\webpack:\app\src\lib\stores\accounts-store.ts:121:5)
    at Array.map (<anonymous>)
    at l.refresh (C:\Users\kiki\AppData\Local\GitHubDesktop\app-2.0.3\webpack:\app\src\lib\stores\accounts-store.ts:118:21)
    at ze.loadInitialState (C:\Users\kiki\AppData\Local\GitHubDesktop\app-2.0.3\webpack:\app\src\lib\stores\app-store.ts:1650:4)
```

Could you try signing out and in again to restore that token? I think that should get you back to a good place!

**Comment by xueqing** [comment]
Thanks. It works for me. Should I close this bug?

**Comment by tierninho** [comment]
Great, glad it works for you now! I took the liberty and closed this issue out for you.
