### ISSUE TITLE
Botched 2.0.4 Update

### ISSUE THREAD

**Issue by the-avid-engineer** [desktop/desktop#7778]
## Description
I checked for the 2.0.4 update as soon as I saw it was available. I was on 2.0.3 when this happened.

In the **Help** -> **About GitHub Desktop** modal, I tapped on "Check for Updates" or whatever it says.

Usually this finishes pretty quickly.. but it didn't this time. It just stuck on "Downloading" or "Checking" or something. So I closed the application to try again.

As soon as I open GitHub Desktop, I get an error (text copied from logs):
```
`git lfs install --skip-repo` exited with an unexpected code: 128.
stderr:
fatal: 'lfs' appears to be a git command, but we were not
able to execute it. Maybe git-lfs is broken?
```

I closed that alert, and went back to the **About GitHub Desktop** modal. It still says "Downloading" or "Checking" or something. But now it says "2.0.4" is installed. So I repeat a few times, same thing happens every time.

I waited a bit longer to retry, and NOW when I open, I get this lovely message:

![image](https://user-images.githubusercontent.com/36554739/59366770-a8e28280-8cef-11e9-8697-d86b8871b58f.png)

I supposed I botched the update by closing while it was "downloading"? Not sure..

## Version
* GitHub Desktop: 2.0.3 upgrading to 2.0.4
* Operating system: Microsoft Windows [Version 10.0.17134.765]

## Steps to Reproduce
See description..

### Expected Behavior
Update downloads in the background and installs once it's ready.

### Actual Behavior
Botched update.

## Additional Information
None

### Logs
[2019-06-12.desktop.production.log](https://github.com/desktop/desktop/files/3282208/2019-06-12.desktop.production.log)

**Comment by the-avid-engineer** [comment]
I just downloaded the installer and it seems to have fixed whatever was botched

**Comment by shiftkey** [comment]
@the-avid-engineer thanks for the report! It looks like something interfered with the update, as a file was locked that prevented the update from working:

```
---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\theav\AppData\Local\GitHubDesktop\app-2.0.4\content_resources_200_percent.pak' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()<---


    at AutoUpdater.emitError (C:\Users\theav\AppData\Local\GitHubDesktop\app-2.0.4\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:70:24)
    at squirrelUpdate.update (C:\Users\theav\AppData\Local\GitHubDesktop\app-2.0.4\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:55:23)
    at ChildProcess.<anonymous> (C:\Users\theav\AppData\Local\GitHubDesktop\app-2.0.4\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:71:14)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

> I just downloaded the installer and it seems to have fixed whatever was botched

Cool, that's what I was going to recommend after ensuring there were no leftover `GitHubDesktop.exe` processes running...

**Comment by shiftkey** [comment]
> I supposed I botched the update by closing while it was "downloading"? Not sure..

Yeah, the updater will download and apply the update in the background, so all that is left to do is restart the app. I can see how that might break if it's closed during this. 

We're tracking this and other installer-related feedback for Windows in #7055, so I'm fine with closing this out for now...
