### ISSUE TITLE
Can't find the local repository

### ISSUE THREAD

**Issue by kambizmbi** [desktop/desktop#7855]
Hi

I've been dealing with a problem lately ( I think after I updated my github desktop)

Since three days ago each time I try to open my local repository an error shows up and says can't find "zbook" ( zbook is the name of my folder)

![image](https://user-images.githubusercontent.com/31544905/59992094-3cf10a00-965f-11e9-82fe-0a6d367742ff.png)

At first I thought maybe it's my pc so I tried on other PCs too but nothing changed.

I have windows 10 and 7

Here's my logs (on windows 7) :

```
2019-06-24T03:39:16.053Z - info: [main] Received possible protocol arguments: 2
2019-06-24T03:39:17.889Z - error: [ui] Error reporting opt in:
TypeError: Failed to fetch
2019-06-24T03:39:19.567Z - info: [ui] [AppStore] loading 0 repositories from store
2019-06-24T03:39:19.607Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-06-24T03:39:19.610Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-06-24T03:39:19.612Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-06-24T03:39:19.613Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-06-24T03:39:19.615Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-06-24T03:39:20.077Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-06-24T03:39:20.125Z - info: [ui] launching: 2.0.4 (Windows 6.1.7601)
2019-06-24T03:39:20.125Z - info: [ui] execPath: 'C:\Users\Kambiz_MBI\AppData\Local\GitHubDesktop\app-2.0.4\GitHubDesktop.exe'
2019-06-24T03:39:20.199Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-06-24T03:39:21.491Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.388s)
2019-06-24T03:39:25.756Z - info: [ui] [Welcome] advancing to step: SignInToDotCom
2019-06-24T03:39:25.764Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2019-06-24T03:39:27.676Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-06-24T03:39:31.441Z - error: [ui] Error checking for updates
Error: GitHub Desktop was not able to contact the update server. Ensure you have internet connectivity and try again.
    at Object.t.parseError (file:///C:/Users/Kambiz_MBI/AppData/Local/GitHubDesktop/app-2.0.4/resources/app/renderer.js:12:117588)
    at onAutoUpdaterError (file:///C:/Users/Kambiz_MBI/AppData/Local/GitHubDesktop/app-2.0.4/resources/app/renderer.js:6:97598)
    at CallbacksRegistry.apply (C:\Users\Kambiz_MBI\AppData\Local\GitHubDesktop\app-2.0.4\resources\electron.asar\common\api\callbacks-registry.js:47:25)
    at EventEmitter.ipcRenderer.on (C:\Users\Kambiz_MBI\AppData\Local\GitHubDesktop\app-2.0.4\resources\electron.asar\renderer\api\remote.js:285:21)
    at EventEmitter.emit (events.js:182:13)
2019-06-24T03:39:39.469Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-06-24T03:39:40.929Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-06-24T03:39:58.107Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-06-24T03:39:59.906Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-06-24T03:41:19.605Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-06-24T03:49:37.494Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-06-24T03:49:39.250Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-06-24T03:50:19.770Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-06-24T03:50:34.954Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2019-06-24T03:50:36.829Z - info: [ui] [AppStore] adding account kambizmbi (kambizmbi) to store
2019-06-24T03:50:36.836Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2019-06-24T03:50:37.010Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-06-24T03:50:37.129Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-06-24T03:50:37.425Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-06-24T03:50:39.718Z - info: [ui] [Welcome] advancing to step: UsageOptOut
2019-06-24T03:50:43.687Z - info: [ui] Opt in reported.
2019-06-24T03:50:58.010Z - info: [ui] [AppStore] adding repository at D:\Work\Site\zbook to store
2019-06-24T03:52:12.614Z - info: [ui] Executing isUsingLFS: git lfs track (took 74.032s)
2019-06-24T03:52:13.387Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 21.583s)
2019-06-24T03:52:13.409Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 33.815s)
2019-06-24T03:52:13.485Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 75.104s)
2019-06-24T03:52:21.828Z - info: [ui] Executing installLFSHooks: git lfs install --force (took 3.447s)
2019-06-24T03:52:31.013Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 18.368s)
2019-06-24T03:52:31.448Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 17.361s)
2019-06-24T03:52:32.491Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 13.964s)
2019-06-24T03:53:49.968Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 13.630s)
2019-06-24T03:53:55.513Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 12.067s)
2019-06-24T03:53:55.556Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 12.122s)
2019-06-24T03:54:04.573Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 8.728s)
2019-06-24T04:00:11.188Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.214s)
2019-06-24T04:03:49.575Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.128s)
2019-06-24T04:04:45.130Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.034s)
2019-06-24T04:05:17.640Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.371s)
2019-06-24T04:09:32.961Z - info: [main] Received possible protocol arguments: 2
2019-06-24T04:09:35.037Z - info: [ui] [AppStore] loading 1 repositories from store
2019-06-24T04:09:35.038Z - info: [ui] [AppStore] found account: kambizmbi (kambizmbi)
2019-06-24T04:09:35.510Z - info: [ui] launching: 2.0.4 (Windows 6.1.7601)
2019-06-24T04:09:35.510Z - info: [ui] execPath: 'C:\Users\Kambiz_MBI\AppData\Local\GitHubDesktop\app-2.0.4\GitHubDesktop.exe'
2019-06-24T04:09:36.726Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.358s)
2019-06-24T04:09:36.742Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.426s)
2019-06-24T04:09:37.420Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.972s)
2019-06-24T04:09:38.122Z - info: [ui] Stats reported.
2019-06-24T04:09:38.465Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.739s)
2019-06-24T04:09:38.465Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.723s)
2019-06-24T04:09:54.081Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.757s)
2019-06-24T04:09:54.081Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.539s)
```

**Comment by niik** [comment]
Hey @kambizmbi, it would appear as if Git is having problems getting the status of your repository, this could be caused by any number of problems so in order to be able to provide any helpful tips here we need to understand what's stopping Git from loading the repository status.

Do you have access to Git on the command line? Try clicking on the `Repository` menu in GitHub Desktop and then `Open in Command Prompt`. If you don't have the command line utilities installed GitHub Desktop should help guide you to install them.

Once you have them installed open the command prompt again and navigate to the repository directory. Should look something like this

```
> Z:
> cd Work\Site\zbook
```

Once you're there try running git status

```
> git status
```

Have a look at the output and see if you see any errors that would explain what's happening and if there's an error please copy and paste it into this issue.

Although it shouldn't be the cause of your problems I noticed that the commands were taking a very long time to run. Is it possible that Z: is a network drive? Is there any chance you could move it to a local disk instead?

**Comment by tierninho** [comment]
@kambizmbi  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by sannya256** [comment]
HI, am experiencing the same issue and this is what i get after running git status - error: bad signature 0x00000000
fatal: index file corrupt - please help
