### ISSUE TITLE
Cannot start rebase due to bad revision error

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7871]
When attempting to initiate a rebase, the `Start rebase` button failed to work, ending in two console errors without notifying the user. I was playing around with LFS files in this repo as seen in the logs below, but I do not see any commits.

### Error 1:
```
install.ts:23 `git rev-list c8fb8d4517e993455b727b3dc25b272c08f6b680..origin/dsdsdffds --reverse --oneline --no-abbrev-commit --` exited with an unexpected code: 128.
stderr:
fatal: bad revision 'c8fb8d4517e993455b727b3dc25b272c08f6b680..origin/dsdsdffds'

(The error was parsed as 27: Bad revision.)
```

### Error 2:
```
Uncaught (in promise) p: Bad revision.
    at Object.t.git (file:///Applications/Beta%20Desktop.app/Contents/Resources/app/renderer.js:11:6105)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Result of `git show c8fb8d4517e993455b727b3dc25b272c08f6b680` is:
```
commit c8fb8d4517e993455b727b3dc25b272c08f6b680 (asassaaasdas)
Author: TL <tierninho@github.com>
Date:   Mon Jun 24 08:04:47 2019 -1000

    ;';'

diff --git a/100MB copy 3.zip b/100MB copy 3.zip
new file mode 100644
index 0000000..07704c3
Binary files /dev/null and b/100MB copy 3.zip differ
diff --git a/100MB copy 4.zip b/100MB copy 4.zip
new file mode 100644
index 0000000..07704c3
Binary files /dev/null and b/100MB copy 4.zip differ
(END)
```

and result of `git show origin/dsdsdffds` is:
```
➜  SM git:(dsdsdffds) git show origin/dsdsdffds
fatal: ambiguous argument 'origin/dsdsdffds': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

![Screen Shot 2019-06-25 at 8 43 32 AM](https://user-images.githubusercontent.com/14828183/60125268-27dfae00-9727-11e9-8d3a-47448cbbd405.png)

2.1.0-beta1, mac

**Comment by shiftkey** [comment]
`(The error was parsed as 27: Bad revision.)`

I'm going to put together a PR to ensure we handle this error and provide a generic message about "not being able to start the rebase".
