### ISSUE TITLE
error spawn EACCES

### ISSUE THREAD

**Issue by deraldinho** [desktop/desktop#7885]
Error: spawn C:\Users\deral\AppData\Local\GitHubDesktop\Update.exe EACCES
at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
at onErrorNT (internal/child_process.js:406:16)
at process._tickCallback (internal/process/next_tick.js:63:19)

Version: 2.0.4
OS: Windows 10.0.17763
## Version

* GitHub Desktop:

* Operating system:

**Comment by deraldinho** [comment]
Error: spawn C:\Users\deral\AppData\Local\GitHubDesktop\Update.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Version: 2.0.4
OS: Windows 10.0.17763

**Comment by steveward** [comment]
Thanks for the report @deraldinho. Could you fill out the template with a few more details about the issue you are experiencing? Is this happening when you attempt to launch GitHub Desktop?

**Comment by tierninho** [comment]
@deraldinho  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
