### ISSUE TITLE
A JavaScript error occoured in the main process

### ISSUE THREAD

**Issue by laukstein** [desktop/desktop#8139]
Latest GitHub recently stop working and shows (maybe is caused by recent Windows 10 updates)
![grabilla p12600](https://user-images.githubusercontent.com/183966/63441152-a449f100-c439-11e9-9462-56b1ef33df2f.png)

Same issue was reported earlier https://github.com/desktop/desktop/issues/6486

**Comment by niik** [comment]
Hey @laukstein, sorry to hear you're having problems!

This error is usually the result of something going wrong while the app is updating (we shipped 2.1.2 very recently). We'd appreciate it if you could grab the latest Squirrel installer log and post that here as that might have some interesting clues about whether the application had some issue applying the update.

The file should be located at `%LOCALAPPDATA%\GitHubDesktop\SquirrelSetup.log`

Regardless of that though I think the easiest and fastest solution for your would be to uninstall GitHub Desktop and then reinstall it using the installer from https://desktop.github.com. Reinstalling should not affect any of your settings or the list of repositories you've got tracked in the app.

Please let us know if reinstalling did not solve your problem.

**Comment by laukstein** [comment]
I just reinstall Github Desktop and it seems working now for now.

**Comment by gothate** [comment]
There is no SquirrelSetup.log but in the desktop.production.log there is this:
`2019-08-21T15:33:58.262Z - info: [ui] skipping fast-forward for all branches as there are 58 local branches - this will run again when there are less than 20 local branches tracking remotes
2019-08-21T15:34:06.932Z - info: [main] opening in browser: https://desktop.github.com/release-notes/
2019-08-21T15:37:09.392Z - info: [ui] [AppStore] loading 1 repositories from store
2019-08-21T15:37:09.634Z - info: [ui] launching: 2.1.2 (Windows 10.0.14393)
2019-08-21T15:37:09.636Z - info: [ui] execPath: 'C:\Users\jrogers\AppData\Local\GitHubDesktop\app-2.1.2\GitHubDesktop.exe'
2019-08-21T15:38:50.998Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\jrogers\AppData\Local\GitHubDesktop\app-2.1.2\chrome_100_percent.pak' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\jrogers\AppData\Local\GitHubDesktop\app-2.1.2\chrome_100_percent.pak' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()<---


    at AutoUpdater.emitError (C:\Users\jrogers\AppData\Local\GitHubDesktop\app-2.1.2\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:70:24)
    at C:\Users\jrogers\AppData\Local\GitHubDesktop\app-2.1.2\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:55:23
    at ChildProcess.<anonymous> (C:\Users\jrogers\AppData\Local\GitHubDesktop\app-2.1.2\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:73:14)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
`

**Comment by gothate** [comment]
Update check was manually initiated if that helps.
It definitely murdered the app though requiring a reinstall.

**Comment by tierninho** [comment]
@gothate If you were having the same problem with installing Desktop, please open a new issue as the original issue is now resolved and so we can address your issue independently. Thanks!
