### ISSUE TITLE
GitHub desktop keeps automatically pulling remote repositories?

### ISSUE THREAD

**Issue by Cristy94** [desktop/desktop#8167]
## Description

As mentioned in the title: random remote changes appear in my local repository without me fetching or pulling. Not only the changes appear locally, they appear as uncommitted changes, like I was the one who wrote those changes?

## Version

* GitHub Desktop: 2.1.2

* Operating system: Windows 10

## Steps to Reproduce

1) I have no incoming changes
2) I start editing my files, have local changes
3) Meanwhile someone pushes some changes
4) I check the repo in GitHub desktop and suddenly I not only have my local changes, but also the remote changes that I never pulled. It's even worse because the remote changes appear as uncommitted, so now there's a mess of my local (actual) uncommitted changes and some other remote uncommitted changes?

### Expected Behavior

Don't automatically pull remote changes.

### Actual Behavior

Remote changes are pulled as uncommitted changes.

### Logs

Some errors from logs, probably not related:
```
2019-08-26T09:32:35.003Z - warn: [ui] fetchAll: 'REPO/issues?state=open' returned a 401
2019-08-26T09:32:41.842Z - info: [ui] [Timing] Action 'create commit' for 'REPO' took 1.320s
2019-08-26T09:32:41.893Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: REPO - Username(has token)
2019-08-26T09:32:45.923Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin feature/teams:feature/teams --progress (took 3.891s)
2019-08-26T09:32:47.477Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.495s)
2019-08-26T09:32:47.608Z - info: [ui] [fetchProtectedBranches] unable to list protected branches

Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\Cristian\AppData\Local\GitHubDesktop\app-2.1.2\webpack:\app\src\lib\http.ts:171:4)
    at _.fetchRepository (C:\Users\Cristian\AppData\Local\GitHubDesktop\app-2.1.2\webpack:\app\src\lib\api.ts:451:14)
    at Ue.repositoryWithRefreshedGitHubRepository (C:\Users\Cristian\AppData\Local\GitHubDesktop\app-2.1.2\webpack:\app\src\lib\stores\app-store.ts:3113:21)
2019-08-26T09:37:32.355Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2019-08-26T09:37:32.416Z - warn: [ui] fetchRepository: an error occurred for 'REPO'
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\Cristian\AppData\Local\GitHubDesktop\app-2.1.2\webpack:\app\src\lib\http.ts:171:4)
    at _.fetchRepository (C:\Users\Cristian\AppData\Local\GitHubDesktop\app-2.1.2\webpack:\app\src\lib\api.ts:451:14)
    at Ue.repositoryWithRefreshedGitHubRepository (C:\Users\Cristian\AppData\Local\GitHubDesktop\app-2.1.2\webpack:\app\src\lib\stores\app-store.ts:3113:21)
```

**Comment by Cristy94** [comment]
I think it is pretty similar, the difference being that I never press the Fetch button (but I guess it auto-fetches in background anyway). 

Another difference from that issue seems to be that the uncomitted changes are the actual changes from remote, not the reversed/reverted changes (this is what I remember, not at office atm, can check that tomorrow).

**Comment by LoeizD** [comment]
We are having exactly the same issue with up to date github today on a new install.

We can't even delete the changes for one file (that match the "they appear as uncommitted changes, like I was the one who wrote those changes"), preventing form pulling, and from working. We have to delete it manually in windows explorer.

It is troublesome as it happens on team members who are less technical.

**Comment by billygriffin** [comment]
Hi @LoeizD, would you mind opening a new "Bug report" issue and laying out the reproduction steps, and preferably screenshots and logs? The issue as described here was resolved in a previous update, so I'd love to dig into it further with you. Thanks!
