### ISSUE TITLE
fatal: unable to access

### ISSUE THREAD

**Issue by akinuri** [desktop/desktop#8210]
## Description
Can't clone/publish/push repository. Having connection problems. I've tried connecting with two different connections; the one in the office, and using my phone as a hotspot. Problem persists.

I know there are already similar issues, but none that I could apply.

## Version
* GitHub Desktop: 2.1.3
* Operating system: Microsoft Windows [Version 10.0.17763.107] (64-bit)

## Steps to Reproduce

1. Launch GitHub Desktop
2. "Clone a repository from the Internet..."
3. Select "GitHub.com" from the tabs
4. Select a repository from the list
5. Click "Clone"

### Expected Behavior
Repository should be cloned to "GitHub" folder in "Documents".

### Actual Behavior
Getting various errors.

When cloning:

> Cloning into 'C:\Users\...'
fatal: unable to access 'https://github.com/.../...git': Failed to connect to github.com port 443: Timed out

When publishing:

> Unable to publish repository. Please check if you have an internet connection and try again.

When pushing:

> fatal: unable to access 'https://github.com/.../...git': Failed to connect to github.com port 443: Timed out

## Additional Information

I'm not that familiar with Git. I'm relatively familiar with GitHub Desktop. I've found mentions of similar issues. They talk about running git commands, modifying proxy settings, etc. I don't know anything about them. I do not use proxy. I'm not on a corporate network, or anything. I've never had this problem before. So I expect a solution that can be applied to my situation (GitHub Desktop on Windows 10).

I thought reinstalling GitHub Desktop might help, but it didn't. Sometimes it really messes up and I can't even list my repositories on GitHub.com. So I had to reinstall twice.

![screenshot of the clone error](https://cdn3.imggmi.com/uploads/2019/9/5/0ce26ba5bf58ffcbb0329bed7225a957-full.png)

### Logs

These logs are from a fresh (second) install. So if they're not long/enough, I can update it later (after few more attempts).

```
2019-09-05T09:36:51.209Z - info: [main] Received possible protocol arguments: 2
2019-09-05T09:36:51.211Z - error: [main] Malformed launch arguments received: C:\Users\Noreh\AppData\Local\GitHubDesktop\app-2.1.3\GitHubDesktop.exe,--squirrel-firstrun
2019-09-05T09:36:52.309Z - info: [ui] [AppStore] loading 0 repositories from store
2019-09-05T09:36:52.342Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-09-05T09:36:52.517Z - info: [ui] launching: 2.1.3 (Windows 10.0.17763)
2019-09-05T09:36:52.517Z - info: [ui] execPath: 'C:\Users\Noreh\AppData\Local\GitHubDesktop\app-2.1.3\GitHubDesktop.exe'
2019-09-05T09:36:52.522Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-09-05T09:36:52.841Z - info: [ui] [Welcome] no sign in step found. ignoring...
2019-09-05T09:36:54.801Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---


    at AutoUpdater.emitError (C:\Users\Noreh\AppData\Local\GitHubDesktop\app-2.1.3\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:70:24)
    at C:\Users\Noreh\AppData\Local\GitHubDesktop\app-2.1.3\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:46:21
    at C:\Users\Noreh\AppData\Local\GitHubDesktop\app-2.1.3\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:91:14
    at ChildProcess.<anonymous> (C:\Users\Noreh\AppData\Local\GitHubDesktop\app-2.1.3\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:73:14)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
2019-09-05T09:37:04.235Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2019-09-05T09:37:13.541Z - info: [ui] [Welcome] advancing to step: UsageOptOut
2019-09-05T09:37:18.422Z - info: [ui] Opt in reported.
2019-09-05T09:37:18.433Z - info: [ui] Opt out reported.
2019-09-05T09:37:31.856Z - info: [ui] [AppStore] adding account akinuri (Noreh AD) to store
2019-09-05T09:37:44.277Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/akinuri/element.js.git - akinuri (has token)
2019-09-05T09:38:05.718Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/akinuri/element.js.git C:\Users\Noreh\Documents\GitHub\element.js (took 21.349s)
2019-09-05T09:38:05.724Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/akinuri/element.js.git C:\Users\Noreh\Documents\GitHub\element.js` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\Noreh\Documents\GitHub\element.js'...
fatal: unable to access 'https://github.com/akinuri/element.js.git/': Failed to connect to github.com port 443: Timed out
```

**Comment by steveward** [comment]
@akinuri thanks for the report. Normally the `Failed to connect to github.com port 443: Timed out` is related to being behind a proxy, but it could be caused by a firewall or antivirus software blocking GitHub Desktop from connecting. Could either of those be a possibility here?

**Comment by akinuri** [comment]
Nope. Currently, I'm not using any firewall/antivirus program. I used to some months ago. The latest one was Panda.

Here's the current list of programs installed:

```
3D Viewer                                                       Microsoft Corporation           
7-Zip 18.05 (x64)                                               Igor Pavlov                     
Adobe Acrobat DC                                                Adobe Systems Incorporated      
Adobe Acrobat Reader DC                                         Adobe Systems Incorporated      
Adobe Illustrator CC 2019                                       Adobe Systems Incorporated      
Adobe Photoshop CC 2019                                         Adobe Systems Incorporated      
Adobe Premiere Pro CC 2018                                      Adobe Systems Incorporated      
Adobe Shockwave Player 12.3                                     Adobe Systems, Inc.             
Adobe XD                                                        Adobe Systems Incorporated      
Agent Ransack x64                                               Mythicsoft Ltd                  
Alarms & Clock                                                  Microsoft Corporation           
Any Video Converter 6.3.3                                       Anvsoft 7.07.2019               
App Installer                                                   Microsoft Corporation           
Audacity 2.2.2                                                  Audacity Team                   
Audio By Harman                                                 Harman                          
AudioShell 2.3.6                                                Softpointer Inc                 
Autodesk 3ds Max 2018                                           Autodesk                        
Autodesk Advanced Material Library Image Library 2018           Autodesk                        
Autodesk Certificate Package  (x64) - 5.1.4                     Autodesk                        
Autodesk Desktop App                                            Autodesk                        
Autodesk License Service (x64) - 5.1.4                          Autodesk                        
Autodesk Material Library 2018                                  Autodesk                        
Autodesk Material Library Base Resolution Image Library 2018    Autodesk                        
Autodesk Material Library Medium Resolution Image Library 2018  Autodesk                        
Bandwidth Monitor v3.4 build 757                                BWMONITOR.COM                   
Bulk Rename Utility 3.0.0.1 (64-bit)                            TGRMN Software                  
CCleaner                                                        Piriform                        
Calculator                                                      Microsoft Corporation           
Camera                                                          Microsoft Corporation           
Canon MF633C/635C                                               CANON INC.                      
FFmpeg (Windows) for Audacity version 2.2.2                                                     
Feedback Hub                                                    Microsoft Corporation           
FileZilla Client 3.44.2                                         Tim Kosse                       
Get Help                                                        Microsoft Corporation           
GitHub Desktop                                                  GitHub, Inc.                    
Google Chrome                                                   Google LLC                      
Groove Music                                                    Microsoft Corporation           
HEIF Image Extensions                                           Microsoft Corporation           
HP DeskJet 2130 series Basic Device Software                    Hewlett-Packard Co.             
HP DeskJet 2130 series Help                                     Hewlett Packard                 
Intel(R) Management Engine Components                           Intel Corporation               
Intel(R) Processor Graphics                                     Intel Corporation               
Internet Download Manager                                       Tonec Inc.                      
K-Lite Mega Codec Pack 14.1.5                                   KLCP                            
KMSpico                                                                                         
LAME v3.99.3 (for Windows)                                                                      
MAXtoA for 3ds Max 2018                                         Solid Angle                     
Mail and Calendar                                               Microsoft Corporation           
Maps                                                            Microsoft Corporation           
Messaging                                                       Microsoft Corporation           
Microsoft Office Professional Plus 2016 - en-us                 Microsoft Corporation           
Microsoft OneDrive                                              Microsoft Corporation           
Microsoft Pay                                                   Microsoft Corporation           
Microsoft Solitaire Collection                                  Microsoft Studios               
Microsoft Sticky Notes                                          Microsoft Corporation           
Microsoft Store                                                 Microsoft Corporation           
Microsoft System CLR Types for SQL Server 2017 CTP2.1           Microsoft Corporation           
Microsoft Visual C++ 2005 Redistributable - x64 8.0.61000       Microsoft Corporation           
Microsoft Visual C++ 2005 Redistributable - x86 8.0.61001       Microsoft Corporation           
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161  Microsoft Corporation           
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161  Microsoft Corporation           
Microsoft Visual C++ 2010 Redistributable - x64 10.0.40219      Microsoft Corporation           
Microsoft Visual C++ 2010 Redistributable - x86 10.0.40219      Microsoft Corporation           
Microsoft Visual C++ 2012 Redistributable (x64) - 11.0.61030    Корпорация Майкрософт           
Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.61030    Корпорация Майкрософт           
Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40664    Корпорация Майкрософт           
Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.40664    Корпорация Майкрософт           
Microsoft Visual C++ 2017 Redistributable (x64) - 14.15.26706   Microsoft Corporation           
Microsoft Visual C++ 2017 Redistributable (x86) - 14.15.26706   Microsoft Corporation           
Microsoft Visual Studio 2010 Tools for Office Runtime (x64)     Microsoft Corporation           
Microsoft Visual Studio 2017                                    Microsoft Corporation           
Microsoft Visual Studio Code (User)                             Microsoft Corporation           
Mixed Reality Portal                                            Microsoft Corporation           
Mobile Plans                                                    Microsoft Corporation           
Movies & TV                                                     Microsoft Corporation           
Mozilla Firefox 68.0.1 (x64 en-US)                              Mozilla                         
Mozilla Maintenance Service                                     Mozilla                         
Mp3tag v2.94                                                    Florian Heidenreich             
NVIDIA GeForce Experience 3.7.0.81                              NVIDIA Corporation              
NVIDIA Graphics Driver 382.64                                   NVIDIA Corporation              
NVIDIA PhysX System Software 9.17.0524                          NVIDIA Corporation              
NVIDIA mental ray and IRay feature plugins for 3ds Max 2018     Autodesk                        
Notepad++ (32-bit x86)                                          Notepad++ Team                  
Office                                                          Microsoft Corporation           
OneNote                                                         Microsoft Corporation           
Paint 3D                                                        Microsoft Corporation           
People                                                          Microsoft Corporation           
Photos                                                          Microsoft Corporation           
Pictureflect Photo Viewer                                       Pictureflect                    
Poedit                                                          Vaclav Slavik                   
PowerISO                                                        Power Software Ltd              
Print 3D                                                        Microsoft Corporation           
Python 3.7.2 (64-bit)                                           Python Software Foundation      
Python Launcher                                                 Python Software Foundation      
ShareX                                                          ShareX Team                     
SketchUp 2018                                                   Trimble, Inc.                   
Skype                                                           Skype                           
Snip & Sketch                                                   Microsoft Corporation           
Store Experience Host                                           Microsoft Corporation           
Subtitle Workshop 6.0b                                                                          
TeamViewer 14                                                   TeamViewer                      
Tips                                                            Microsoft Corporation           
TreeSize Free V4.1.2                                            JAM Software                    
USB Disk Security                                               Zbshareware Lab                 
V-Ray Online License Server                                     Chaos Software Ltd              
V-Ray for 3dsmax 2018 for x64                                   Chaos Software Ltd              
VLC media player                                                VideoLAN                        
VP9 Video Extensions                                            Microsoft Corporation           
VideoPad Video Editor                                           NCH Software                    
Voice Recorder                                                  Microsoft Corporation           
Vulkan Run Time Libraries 1.0.42.1                              LunarG, Inc.                    
Weather                                                         Microsoft Corporation           
Web Media Extensions                                            Microsoft Corporation           
Webp Image Extensions                                           Microsoft Corporation           
WhatsApp                                                        WhatsApp                        
WinRAR 5.50 (64-bit)                                            win.rar GmbH                    
XAMPP                                                           Bitnami                         
Xbox Console Companion                                          Microsoft Corporation           
Xbox Game Bar                                                   Microsoft Corporation           
Xbox Game Speech                                                Window  Microsoft Corporation   
Xbox Game bar                                                   Microsoft Corporation           
Xbox Identity Provider                                          Microsoft Corporation           
Xbox Live                                                       Microsoft Corporation           
Your Phone                                                      Microsoft Corporation           
icofx 3.1                                                       IcoFX Software S.R.L.           
µTorrent                                                        BitTorrent Inc.                 
```

**Comment by steveward** [comment]
@akinuri thanks for sharing that. Can you follow these steps and let me know the output of the command in step 3?

1. Open a repository in GitHub Desktop
2. Go to the menu and select `Repository` > `Open in <command_line>`
3. Run the command `git config --list --show-origin`

**Comment by akinuri** [comment]
Currently my Github folder is empty. I've moved the contents to somewhere else when I was experimenting. So to test your steps, I created a new repository. Can't publish it for the reasons I've already mentioned. Went to the `Repository` > Open in `<command_line>` and I got a warning:

> Unable to locate Git <br>
> We were unable to locate Git on your system. This means you won't be able to execute any Git commands in the command prompt.<br>
> To help you get Git installed and configured for your operation system, we have some external resources available.<br>
> [Open without Git] [Install Git]

Now, I'm not sure if this warning was always there. I've reinstalled GitHub Desktop twice, and installed and uninstalled Git once. So this warning might be due to my tinkering. In any case, what should I do? I think/thought that GitHub Desktop doesn't require an extarnal Git installation o.O

**Comment by steveward** [comment]
@akinuri GitHub Desktop has its own bundled Git, but in order to run specific Git commands you will need to install Git for Windows:

https://git-scm.com/download/win

Once you install that you can open Git Bash and run the command.

**Comment by akinuri** [comment]
Oh. Done.

```
Microsoft Windows [Version 10.0.17763.107]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Noreh\Documents\GitHub\test>git config --list --show-origin
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/mingw64/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.smudge=git-lfs smudge --skip -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.process=git-lfs filter-process --skip
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/mingw64/etc/gitconfig credential.helper=manager
file:C:/Program Files/Git/mingw64/etc/gitconfig core.editor="C:\\Program Files (x86)\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
file:C:/Users/Noreh/.gitconfig  filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/Noreh/.gitconfig  filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/Noreh/.gitconfig  filter.lfs.process=git-lfs filter-process
file:C:/Users/Noreh/.gitconfig  filter.lfs.required=true
file:C:/Users/Noreh/.gitconfig  user.name=Noreh AD
file:C:/Users/Noreh/.gitconfig  user.email=__EMAIL__OMITTED__
file:C:/Users/Noreh/.gitconfig  http.proxy=
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
:

file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/mingw64/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.smudge=git-lfs smudge --skip -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.process=git-lfs filter-process --skip
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/mingw64/etc/gitconfig credential.helper=manager
file:C:/Program Files/Git/mingw64/etc/gitconfig core.editor="C:\\Program Files (x86)\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
file:C:/Users/Noreh/.gitconfig  filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/Noreh/.gitconfig  filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/Noreh/.gitconfig  filter.lfs.process=git-lfs filter-process
file:C:/Users/Noreh/.gitconfig  filter.lfs.required=true
file:C:/Users/Noreh/.gitconfig  user.name=Noreh AD
file:C:/Users/Noreh/.gitconfig  user.email=__EMAIL__OMITTED__
file:C:/Users/Noreh/.gitconfig  http.proxy=
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
:...skipping...
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/mingw64/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.smudge=git-lfs smudge --skip -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.process=git-lfs filter-process --skip
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/mingw64/etc/gitconfig credential.helper=manager
file:C:/Program Files/Git/mingw64/etc/gitconfig core.editor="C:\\Program Files (x86)\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
file:C:/Users/Noreh/.gitconfig  filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/Noreh/.gitconfig  filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/Noreh/.gitconfig  filter.lfs.process=git-lfs filter-process
file:C:/Users/Noreh/.gitconfig  filter.lfs.required=true
file:C:/Users/Noreh/.gitconfig  user.name=Noreh AD
file:C:/Users/Noreh/.gitconfig  user.email=__EMAIL__OMITTED__
file:C:/Users/Noreh/.gitconfig  http.proxy=
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
~
~

C:\Users\Noreh\Documents\GitHub\test>
```

**Comment by steveward** [comment]
@akinuri thanks! There's the issue:

`file:C:/Users/Noreh/.gitconfig  http.proxy=`

There is an empty line for your proxy, which is causing Git to attempt to connect to a proxy that doesn't exist. You can run this command to remove this line:

`git config --global --unset http.proxy`

That should get things working for you.
