### ISSUE TITLE
Behind company Proxy error

### ISSUE THREAD

**Issue by Bitexirtz** [desktop/desktop#8296]
Environment: Windows 10 64 Bit
GitHub Desktop version: 2.1.3

Problem: When I check for updates the following exception is thrown.

```
Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---
```

**Comment by steveward** [comment]
@Bitexirtz thanks for the report.  Have you configured a system proxy on you machine? There's a helpful [guide here](https://www.howtogeek.com/tips/how-to-set-your-proxy-settings-in-windows-8.1/) for how to do that.

**Comment by tierninho** [comment]
@Bitexirtz  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by Bitexirtz** [comment]
Sorry for late response. Yes I configured the system proxy. In fact, I can be able to update Visual Studio Code after inputting the proxy credentials. But GitHub Desktop doesn't prompt to input credentials and just display the exception mentioned above.

**Comment by steveward** [comment]
@Bitexirtz Have you looked into something like [CNTLM](http://cntlm.sourceforge.net/)? Configuring CNTLM with your proxy may get things working.

**Comment by Bitexirtz** [comment]
>>Have you looked into something like CNTLM?
As described above, I am using Windows 10. Is this applicable? I researched about CNTLM and I think it is not for Windows.

One thing to point is my system proxy works fine. I can update Visual Studio Code without problem after entering the proxy credentials.

**Comment by steveward** [comment]
@Bitexirtz are you seeing a prompt in Visual Studio Code? It looks like they have some [specific options for handling authenticated system proxies](https://code.visualstudio.com/docs/setup/network#_proxy-server-support). GitHub Desktop doesn't have that type of built-in proxy support at this time (see https://github.com/desktop/desktop/issues/966 for some historical discussion). 

Do you know what kind of authentication method you are using?

**Comment by Bitexirtz** [comment]
>are you seeing a prompt in Visual Studio Code?
Yes. A prompt is displayed in VS Code.

>Do you know what kind of authentication method you are using?
You mean ldap? (Sorry but I may not understood your question.)

**Comment by steveward** [comment]
@Bitexirtz this is what I would be referring to:

https://code.visualstudio.com/docs/setup/network#_authenticated-proxies

**Comment by Bitexirtz** [comment]
Yes. That dialog is displayed in Visual Studio Code.

**Comment by steveward** [comment]
@Bitexirtz apologies for the delay. Could you open up PowerShell and run the following command?

`[System.Net.WebProxy]::GetDefaultProxy().GetProxy('https://github.com').ToString()`

That should print either https://github.com if the system level proxy setting isn't automatically configured or something like https://proxy.yourcompany.com:8888/ if it is automatically configured. That should give us some more information about your setup.

**Comment by Bitexirtz** [comment]
![GetProxy](https://user-images.githubusercontent.com/7827862/73219751-cd646f80-4197-11ea-94d1-520ff958ee69.png)

This is what displayed. I think system proxy was configured correctly.

**Comment by steveward** [comment]
@Bitexirtz we're shipping better support for proxies in GitHub Desktop -- if you are interested you can download the beta version to see if that helps with the issues you were experiencing:

https://github.com/desktop/desktop#beta-channel

**Comment by steveward** [comment]
@Bitexirtz I'm going to close this issue out -- let us know if you are having any problems.

**Comment by Bitexirtz** [comment]
Sorry I can't try it out. We are currently on lockdown due to covid19 so we have no office. I will just inform again if there are still problems using the beta version. Thanks a lot.
