### ISSUE TITLE
Create branch dialog provides no feedback when creation fails

### ISSUE THREAD

**Issue by TrueCP6** [desktop/desktop#8306]
## Description

When trying to create a branch from an upstream branch (not master) it loads endlessly (or just takes very long) without creating the branch.

## Version

* GitHub Desktop: Version 2.1.3

* Operating system: Microsoft Windows [Version 10.0.17134.885]

## Steps to Reproduce

1. Switch to an upstream branch
2. Create a new branch using the upstream branch

### Expected Behavior

The branch should be created within a few seconds.

### Actual Behavior

It instead loads for a long time without using much CPU, disk or network. The branch doesn't seem to ever get created.

## Additional Information

![My Results](https://i.imgur.com/LT7T7Xo.png)

### Logs

[Log](https://github.com/desktop/desktop/files/3639529/2019-09-22.desktop.production.log)

**Comment by niik** [comment]
Hey @TrueCP6, thanks so much for opening this. I've been able to reproduce the problem on my machine. Looking at your log file (thanks so much for including that by the way!) there's an underlying error that we're failing to present to you:

```
fatal: A branch named 'Animation' already exists.

(The error was parsed as 26: A branch with that name already exists.)
2019-09-22T08:40:50.231Z - error: [ui] createBranch failed
GitError: A branch with that name already exists.
    at Object.t.git (C:\Users\minec\AppData\Local\GitHubDesktop\app-2.1.3\webpack:\app\src\lib\git\core.ts:175:2)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
    at Object.t.createBranch (C:\Users\minec\AppData\Local\GitHubDesktop\app-2.1.3\webpack:\app\src\lib\git\branch.ts:27:5)
    at T.performFailableOperation (C:\Users\minec\AppData\Local\GitHubDesktop\app-2.1.3\webpack:\app\src\lib\stores\git-store.ts:733:22)
    at ze._createBranch (C:\Users\minec\AppData\Local\GitHubDesktop\app-2.1.3\webpack:\app\src\lib\stores\app-store.ts:2816:20)
    at Object.createBranch [as onSubmit] (C:\Users\minec\AppData\Local\GitHubDesktop\app-2.1.3\webpack:\app\src\ui\create-branch\create-branch-dialog.tsx:
```

So what's happening is that you're trying to create a branch called `animation`, but there's already a branch called `Animation` in your repository. Git itself has no problems with branch names which only differs in case but Windows (and typically macOS) use a case-insensitive file system which doesn't allow for two files to only differ in case.

This is absolutely a bug on our end and I'll label it as such but for now you should be able to continue working by choosing a different branch name. If another branch name doesn't resolve your issue please let us know.
