### ISSUE TITLE
Github Desktop 2.2.3: Opening Repository with external editor results in crash

### ISSUE THREAD

**Issue by googolflops** [desktop/desktop#8695]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Open Github desktop on Windows 7 Pro Latest patches 
2. Fork something in your repository , go to 'Open your repository in your external editor (Atom)'
3. Click on 'Open in Atom'

### Expected behavior

Atom to open the repository 
### Actual behavior

An error with: 
Error: spawn C:\Windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

Version: 2.2.3
OS: Windows 6.1.7601

### Logs

2019-11-24T21:16:02.986Z - info: [main] Received possible protocol arguments: 2
2019-11-24T21:16:02.987Z - error: [main] Malformed launch arguments received: C:\Users\EEI\AppData\Local\GitHubDesktop\app-2.2.3\GitHubDesktop.exe,--squirrel-firstrun
2019-11-24T21:16:03.055Z - info: [main] Received possible protocol arguments: 2
2019-11-24T21:16:03.056Z - error: [main] Malformed launch arguments received: C:\ProgramData\A11\GitHubDesktop\app-2.2.3\GitHubDesktop.exe,--squirrel-firstrun
2019-11-24T21:16:03.056Z - info: [main] Received possible protocol arguments: 4
2019-11-24T21:16:03.056Z - error: [main] Malformed launch arguments received: C:\Users\EEI\AppData\Local\GitHubDesktop\app-2.2.3\GitHubDesktop.exe,--squirrel-firstrun,--allow-file-access-from-files,--original-process-start-time=13219103762411121
2019-11-24T21:16:05.018Z - info: [ui] [AppStore] loading 0 repositories from store
2019-11-24T21:16:05.034Z - info: [ui] [Welcome] no sign in step found. ignoring...

**Comment by billygriffin** [comment]
Thanks for the issue! We’ve seen this come up a couple times before and usually stems from something that went wrong during installation. Would you mind following the steps here and letting us know if that fixes it? Happy to look into it further if not. https://github.com/desktop/desktop/issues/8447#issuecomment-541147243

**Comment by googolflops** [comment]
Thanks, I'll give it a try.
