### ISSUE TITLE
After a pull, GitHub still says, there are changes to pull

### ISSUE THREAD

**Issue by sdiedrichsen** [desktop/desktop#9054]
### Describe the bug

After a pull, the window top bar refreshes but instead of "Fetch origin", it says "Pull" with the same number fo changes. 
Clicking on the tabs "Changes" and "History" resolves the issue eventually. 

 

### Version & OS

2.3.1 on macOS 10.15.3.

### Expected behavior

After  a pull. there should be a feedback, that the pull was successful and the right most button in the top bar should display "Fetch origin"

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @sdiedrichsen. Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by sdiedrichsen** [comment]
Here's the log:
>>>>>

2020-02-06T07:08:23.288Z - info: [ui] [AppStore] loading 1 repositories from store
2020-02-06T07:08:23.290Z - info: [ui] [AppStore] found account: sdiedric (Steffan Diedrichsen)
2020-02-06T07:08:23.290Z - info: [ui] [AppStore] found account: sdiedrichsen (sdiedrichsen)
2020-02-06T07:08:23.394Z - info: [ui] [BranchPruner] Last prune took place in 2 hours - skipping
2020-02-06T07:08:23.936Z - info: [ui] launching: 2.3.1 (Mac OS 10.15.3)
2020-02-06T07:08:23.937Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
2020-02-06T07:08:25.604Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.670s)
2020-02-06T07:08:25.605Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 2.252s)
2020-02-06T07:08:26.034Z - info: [ui] Current tutorial step is NotApplicable
2020-02-06T07:08:26.058Z - info: [ui] Current tutorial step is NotApplicable
2020-02-06T07:08:43.452Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 7.155s)
2020-02-06T07:08:44.310Z - error: [ui] Error performing periodic fetch for 'musicapps/MusicApps'
TypeError: Cannot read property 'length' of undefined
    at Object.t.isBranchPushable (/webpack:/app/src/lib/helpers/push-control.ts:37:28)
    at Ve.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:887:9)
    at /webpack:/app/src/lib/stores/app-store.ts:4012:9
    at Ve.withPushPullFetch (/webpack:/app/src/lib/stores/app-store.ts:3609:7)
    at Ve.performFetch (/webpack:/app/src/lib/stores/app-store.ts:3974:5)
    at t.BackgroundFetcher.performAndScheduleFetch (/webpack:/app/src/lib/stores/helpers/background-fetcher.ts:97:9)
2020-02-06T07:08:44.478Z - info: [ui] Current tutorial step is NotApplicable
2020-02-06T07:08:48.167Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MusicApps - sdiedric (has token)
2020-02-06T07:08:52.377Z - info: [ui] Executing pull: git -c credential.helper= pull --progress origin (took 4.178s)

--->> Now, I toggle between History and Changes:

2020-02-06T07:09:07.206Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 2.276s)


<<<<<

**Comment by joeharrison714** [comment]
I am experiencing this as well

**Comment by aaronshekey** [comment]
Here's a video of this. It happens to me all day every day on Windows. Restarting GitHub Desktop resolves it.

https://www.dropbox.com/s/066ut6rfuu7n450/pull-origin-restart.mov?dl=0

**Comment by tierninho** [comment]
I spotted one error in the logs:

```
Error performing periodic fetch for 'musicapps/MusicApps'
TypeError: Cannot read property 'length' of undefined
```

@niik Any thoughts?

**Comment by niik** [comment]
Thanks @sdiedrichsen, that log is super helpful and should hopefully let us resolve https://github.com/desktop/desktop/issues/9053 as well. While we can certainly guard against this specific condition easily enough it would be lovely if we could fully understand what's being returned from the API here.

Could either one of you open up DevTools (`View -> Toggle Developer Tools`) go to the Network tab, type `push_control` into the filter requests text box and select a request from the list and finally click on the `Preview` tab to see the actual response sent back from the server. Something like 👇 

<img width="958" alt="image" src="https://user-images.githubusercontent.com/634063/74431850-f86ce580-4e5e-11ea-93d2-ed24d2533b99.png">

If you could get us a snapshot of just the response part (feel free to blur or obscure branch names and such) that would be fantastic.

**Comment by sdiedrichsen** [comment]
Markus, 

I see this push_control entries. But if I click on Preview, the window says "Failed to load response data" or "Nothing to preview”.

Best,

Steffan

**Comment by steveward** [comment]
Closing as stale. If this is still an issue, let us know and we can reopen to investigate further.
