### ISSUE TITLE
After pushing a branch and creating a PR, GitHub desktop still thinks, I can create  a pull request.

### ISSUE THREAD

**Issue by sdiedrichsen** [desktop/desktop#9081]
### Describe the bug

After pushing a branch and creating a PR, GitHub desktop still thinks, I can create  a pull request and doesn't display the current PR state.

### Version & OS
Version 2.3.1
macOS 10.15.3

### Steps to reproduce the behavior

1. Create a branch from master
2. Commit a change
3. publish the branch
4. create a pull request

### Expected behavior

After the creation of the pull request, GitHub desktop should track the PR state. And it should say something "No local changes, push further commits to the PR."

### Actual behavior

GitHub desktop remains in the state, that the branch has been pushed, but no PR has been created. It doesn't track the PR. 

### Logs

That's a clip of the log: 
```
2020-02-10T12:57:27.628Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.841s)
2020-02-10T12:57:27.885Z - info: [ui] Current tutorial step is NotApplicable
2020-02-10T12:57:27.898Z - info: [ui] skipping fast-forward for all branches as there are 20 eligible branches (Threshold is 20 eligible branches).
2020-02-10T13:04:56.811Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.364s)
2020-02-10T13:08:39.459Z - info: [ui] Current tutorial step is NotApplicable
2020-02-10T13:09:05.838Z - info: [ui] Current tutorial step is NotApplicable
2020-02-10T13:09:06.782Z - info: [ui] [Timing] Action 'create commit' for 'musicapps/MusicApps' took 3.027s
2020-02-10T13:09:12.653Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MusicApps - sdiedric (has token)
2020-02-10T13:09:19.324Z - info: [ui] Executing push: git -c credential.helper= push origin Issue-#509-CGenData.cpp-CFPropertyListCreateFromXMLData-deprecated --set-upstream --progress (took 6.670s)
2020-02-10T13:09:23.370Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 4.044s)
2020-02-10T13:09:23.943Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Branch not found
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:175:4)
    at x.fetchPushControl (/webpack:/app/src/lib/api.ts:826:14)
    at Ve.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:883:29)
    at m.performFailableOperation.retryAction (/webpack:/app/src/lib/stores/app-store.ts:3536:13)
    at x.performFailableOperation (/webpack:/app/src/lib/stores/git-store.ts:733:22)
    at /webpack:/app/src/lib/stores/app-store.ts:3493:9
    at Ve.withPushPullFetch (/webpack:/app/src/lib/stores/app-store.ts:3609:7)
2020-02-10T13:09:24.927Z - info: [ui] Current tutorial step is NotApplicable
2020-02-10T13:09:24.936Z - info: [ui] skipping fast-forward for all branches as there are 20 eligible branches (Threshold is 20 eligible branches).
2020-02-10T13:09:27.746Z - info: [main] opening in browser: https://github.aso.apple.com/MusicApps/MusicApps/pull/new/Issue-%23509-CGenData.cpp-CFPropertyListCreateFromXMLData-deprecated
2020-02-10T13:10:32.610Z - info: [ui] Current tutorial step is NotApplicable
```

**Comment by niik** [comment]
Hi @sdiedrichsen, thanks for opening this! It can sometimes take up to two minutes from you creating the PR until Desktop is able to pick it up and understand that there's no point in suggesting you create a PR. If more than two minutes has passed and you still don't see the PR then there's something else amiss.

Could you open the branches dropdown and look in the pull requests tab and see if you can find your PR in there?

<img width="364" alt="image" src="https://user-images.githubusercontent.com/634063/74172049-de00f500-4c2f-11ea-8c2e-3a9193c92b2d.png">

Additionally, are you working within a fork or do you have contributor access to the repository?

**Comment by sdiedrichsen** [comment]
Hello Markus, 


thanks for getting back on this.

I have to relaunch GitHub Desktop a few times before I see this Pull request state indicator. I didn’t check the pull request tab now. I’ll provide on the later. 

Here’s the log of the last  re-launches. The least launch was successful:

020-02-11T10:38:20.461Z - info: [ui] Current tutorial step is NotApplicable
2020-02-11T10:38:20.471Z - info: [ui] skipping fast-forward for all branches as there are 23 eligible branches (Threshold is 20 eligible branches).
2020-02-11T10:38:24.448Z - info: [main] opening in browser: https://github.aso.apple.com/MusicApps/MusicApps/pull/new/sdiedrichsen%2FStatic-Analyzer-Potential-Leak-
2020-02-11T10:38:45.770Z - info: [ui] Current tutorial step is NotApplicable
2020-02-11T10:38:58.782Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MusicApps - sdiedric (has token)
2020-02-11T10:39:02.087Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.302s)
2020-02-11T10:39:02.665Z - warn: [ui] deserialize: invalid JSON found at 'https://github.aso.apple.com/api/v3/repos/musicapps/MusicApps/branches/sdiedrichsen/Static-Analyzer-Potential-Leak-/push_control' - status: 500, length: '(missing)' id: '(missing)'
SyntaxError: Unexpected end of JSON input
    at o (/webpack:/app/src/lib/http.ts:68:5)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:170:6)
    at x.fetchPushControl (/webpack:/app/src/lib/api.ts:827:6)
    at Ve.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:883:29)
    at /webpack:/app/src/lib/stores/app-store.ts:4012:9
    at Ve.withPushPullFetch (/webpack:/app/src/lib/stores/app-store.ts:3609:7)
    at Ve.performFetch (/webpack:/app/src/lib/stores/app-store.ts:3974:5)
2020-02-11T10:39:02.666Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: API error https://github.aso.apple.com/api/v3/repos/musicapps/MusicApps/branches/sdiedrichsen/Static-Analyzer-Potential-Leak-/push_control: Internal Server Error (500)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:171:26)
2020-02-11T10:39:03.693Z - info: [ui] Current tutorial step is NotApplicable
2020-02-11T10:39:03.703Z - info: [ui] skipping fast-forward for all branches as there are 23 eligible branches (Threshold is 20 eligible branches).
2020-02-11T10:39:12.886Z - info: [ui] [AppStore] loading 1 repositories from store
2020-02-11T10:39:12.887Z - info: [ui] [AppStore] found account: sdiedric (Steffan Diedrichsen)
2020-02-11T10:39:12.887Z - info: [ui] [AppStore] found account: sdiedrichsen (sdiedrichsen)
2020-02-11T10:39:13.140Z - info: [ui] [BranchPruner] Last prune took place in 21 hours - skipping
2020-02-11T10:39:13.438Z - info: [ui] launching: 2.3.1 (Mac OS 10.15.3)
2020-02-11T10:39:13.439Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
2020-02-11T10:39:14.129Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.158s)
2020-02-11T10:39:14.303Z - info: [ui] Current tutorial step is NotApplicable
2020-02-11T10:39:14.511Z - info: [ui] Current tutorial step is NotApplicable
2020-02-11T10:39:22.931Z - info: [ui] [AppStore] loading 1 repositories from store
2020-02-11T10:39:22.932Z - info: [ui] [AppStore] found account: sdiedric (Steffan Diedrichsen)
2020-02-11T10:39:22.932Z - info: [ui] [AppStore] found account: sdiedrichsen (sdiedrichsen)
2020-02-11T10:39:23.186Z - info: [ui] [BranchPruner] Last prune took place in 21 hours - skipping
2020-02-11T10:39:23.697Z - info: [ui] launching: 2.3.1 (Mac OS 10.15.3)
2020-02-11T10:39:23.697Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
2020-02-11T10:39:24.281Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.268s)
2020-02-11T10:39:24.467Z - info: [ui] Current tutorial step is NotApplicable
2020-02-11T10:39:24.508Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.014s)
2020-02-11T10:39:24.657Z - info: [ui] Current tutorial step is NotApplicable


Best,

Steffan

**Comment by sdiedrichsen** [comment]
Here’s the additional Information I promised you:

No, I don’t see the pull request in the tab.

Best,

Steffan

**Comment by tierninho** [comment]
I spotted two errors in the logs:

```
2020-02-11T10:39:02.666Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: API error https://github.aso.apple.com/api/v3/repos/musicapps/MusicApps/branches/sdiedrichsen/Static-Analyzer-Potential-Leak-/push_control: Internal Server Error (500)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:171:26)
```

and 

```
2020-02-11T10:39:02.665Z - warn: [ui] deserialize: invalid JSON found at 'https://github.aso.apple.com/api/v3/repos/musicapps/MusicApps/branches/sdiedrichsen/Static-Analyzer-Potential-Leak-/push_control' - status: 500, length: '(missing)' id: '(missing)'
SyntaxError: Unexpected end of JSON input
```

@niik Any thoughts?

**Comment by niik** [comment]
Hey @sdiedrichsen, we're going through a bunch of issues that haven't seen any activity in a while. Are you still experiencing problems with PRs not updating?

**Comment by lini** [comment]
I am still experiencing this issue - macOS 10.15.7, Github Desktop 2.5.6, working with a private Github repository. The PR tab in the branches dropdown does not update with the currently open PRs in the repository. I have to manually find the branch of the PR in the branches tab and switch to it.
