### ISSUE TITLE
"Failed to execute installGlobalLFSFilter: UNKNOWN" error running GitHub Desktop as non-admin user

### ISSUE THREAD

**Issue by lopuj** [desktop/desktop#9223]
### Describe the bug

I am having issues using GitHub Desktop as a non-admin user. WhenI first launch it, I get a pop up saying: "Failed to execute installGlobalLFSFilter: UNKNOWN". Then if I click out of the pop up and try to clone a repository, I get the following: "Failed to execute clone: UNKNOWN". These issues go away if using an admin account.

### Version & OS
Version: 2.3.1
OS: Microsoft Windows 10 Enterprise 10.0.17763 Build 17763

### Steps to reproduce the behavior
1. Open Desktop as a non-admin
2. See error
3. Try to clone repository

### Screenshots
![image](https://user-images.githubusercontent.com/8886432/75933936-101d0580-5e30-11ea-8790-4c3e5ff31181.png)

![image](https://user-images.githubusercontent.com/8886432/75933970-1e6b2180-5e30-11ea-91fb-33bdcb30c759.png)

### Logs
[2020-03-03.desktop.production.log](https://github.com/desktop/desktop/files/4290178/2020-03-03.desktop.production.log)

**Comment by steveward** [comment]
@lopuj thanks for the report. One question about this point:

>These issues go away if using an admin account.

Is this a separate Windows user account, or are you launching GitHub Desktop as an admin?

**Comment by lopuj** [comment]
It’s a separate windows user account with higher admin privileges than my regular account. I have temporary access it to right now to install software on my new work desktop. I have to run Github Desktop as an administrator, which prompts me to enter admin credentials for that account. My regular account doesn’t have permission to run it as admin

**Comment by steveward** [comment]
Are you able to install and perform Git operations using [Git for Windows]( https://git-scm.com/download/win) on the non-admin machine?

The only error in the log file that I am seeing is related to the Squirrel installer we use with GitHub Desktop -- it may be worth taking a look at that log file to see if there is any information. You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

**Comment by lopuj** [comment]
I was able to install both Github Desktop and Git for Windows without using an admin account. I'm also able to perform Git operations with my non admin account. 

I looked into both of those squirrel logs, and I'm not seeing anything useful that's sticking out to me.
[SquirrelSetup.log](https://github.com/desktop/desktop/files/4300041/SquirrelSetup.log)
[SquirrelSetup.log](https://github.com/desktop/desktop/files/4300042/SquirrelSetup.log)

**Comment by tierninho** [comment]
So I spotted two errors in the logs.

```
2020-03-05 11:58:50> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\dolson\AppData\Local\Microsoft\Teams\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2020-03-05 11:58:50> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\dolson\AppData\Local\Microsoft\Teams\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
```

```
2020-03-03 15:08:20> ApplyReleasesImpl: Examining Pin: Snipping Tool.lnk
2020-03-03 15:08:20> ApplyReleasesImpl: File 'C:\Users\dolson\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Snipping Tool.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
```

@steveward Do these mean anything to you?

**Comment by steveward** [comment]
@lopuj are there any specific Group Policy settings in your environment that could be causing this? Unfortunately this seems very specific to your setup -- would it be possible to whitelist GitHub Desktop?

**Comment by tierninho** [comment]
@lopuj  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
