### ISSUE TITLE
Issue reading property of undefined

### ISSUE THREAD

**Issue by diligamer** [desktop/desktop#9264]
```
TypeError: Cannot read property 'find' of undefined
    at a (file:///app/renderer.js:18:107280)
    at file:///app/renderer.js:18:106383
    at To (file:///app/renderer.js:11:95039)
    at oa.operation (file:///app/renderer.js:11:208241)
    at t (file:///app/renderer.js:18:106362)
    at _t (file:///app/renderer.js:11:64707)
    at Tt (file:///app/renderer.js:11:64785)
    at bo (file:///app/renderer.js:11:92565)
    at HTMLDocument.<anonymous> (file:///app/renderer.js:11:95199)

Version: 2.3.1
OS: Windows 10.0.19577
```

As Someone Who Just Wants A Clean GUI For Committing, I Have No Idea What This Means.

**Comment by niik** [comment]
H @diligamer, thanks for reporting this. This sounds similar to https://github.com/desktop/desktop/issues/5790. Were you by chance selecting text using your mouse when this happened?

Are you able to reproduce the crash?

**Comment by diligamer** [comment]
forgot what i did to crash it
