### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by hritikbhandari** [desktop/desktop#9369]
### Describe the feature or problem you’d like to solve

I am unable to login to my GitHub account from GitHub desktop despite having an active internet connection. It says Unable to fetch. Please sort it .

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by tierninho** [comment]
@hritikbhandari Please share your logs so we can have more information. See the Help menu in Desktop. Thanks.

**Comment by hritikbhandari** [comment]
2020-03-26T20:05:33.225Z - info: [ui] [AppStore] loading 0 repositories from store
2020-03-26T20:05:33.226Z - info: [ui] [AppStore] found account: hritikbhandari (Hritik Bhandari)
2020-03-26T20:05:33.456Z - info: [ui] launching: 2.2.4 (Windows 10.0.18362)
2020-03-26T20:05:33.456Z - info: [ui] execPath: 'C:\Users\bhand\AppData\Local\GitHubDesktop\app-2.2.4\GitHubDesktop.exe'
2020-03-26T20:06:03.471Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-03-26T20:06:03.472Z - warn: [ui] fetchUser: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-03-26T20:06:03.472Z - warn: [ui] Error refreshing account 'hritikbhandari'
TypeError: Failed to fetch
2020-03-26T20:06:03.480Z - warn: [ui] fetchRepositories: TypeError: Failed to fetch
2020-03-26T20:06:04.184Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2020-03-26T20:13:23.755Z - warn: [ui] fetchRepositories: TypeError: Failed to fetch
2020-03-26T20:15:45.695Z - error: [ui] `git rev-parse --is-bare-repository` exited with an unexpected code: 128.
stderr:
fatal: not a git repository (or any of the parent directories): .git

(The error was parsed as 28: This is not a git repository.)
2020-03-26T20:16:57.691Z - warn: [ui] fetchRepositories: TypeError: Failed to fetch
2020-03-26T20:19:40.581Z - error: [ui] `git rev-parse --is-bare-repository` exited with an unexpected code: 128.
stderr:
fatal: not a git repository (or any of the parent directories): .git

(The error was parsed as 28: This is not a git repository.)
2020-03-26T20:21:22.250Z - info: [ui] Executing initGitRepository: git init (took 2.162s)
2020-03-26T20:21:22.306Z - info: [ui] [AppStore] adding repository at D:\Files\Professional\Projects\Portfolio Website to store
2020-03-26T20:21:22.628Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:21:34.293Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 11.336s)
2020-03-26T20:21:37.265Z - info: [ui] Executing createCommit: git commit -F - (took 2.972s)
2020-03-26T20:21:37.680Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:22:21.395Z - warn: [ui] fetchOrgs: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-03-26T20:22:33.755Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:22:53.758Z - error: [ui] createRepository: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-03-26T20:23:21.148Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:23:29.278Z - error: [ui] createRepository: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-03-26T20:23:32.746Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:23:50.986Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:24:07.587Z - warn: [ui] fetchOrgs: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-03-26T20:25:00.643Z - warn: [ui] fetchOrgs: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-03-26T20:25:03.322Z - error: [ui] createRepository: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-03-26T20:25:05.913Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:25:10.914Z - info: [ui] [AppStore] removing account hritikbhandari (Hritik Bhandari) from store
2020-03-26T20:25:23.795Z - info: [ui] [SignInStore] initializing OAuth flow
2020-03-26T20:25:23.849Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=afaff937-4beb-4c6c-9f58-760312365c19
2020-03-26T20:25:28.136Z - info: [main] Received possible protocol arguments: 5
2020-03-26T20:25:28.136Z - info: [main] Processing protocol url
2020-03-26T20:25:28.137Z - info: [ui] [Dispatcher] requesting authenticated user
2020-03-26T20:25:28.223Z - info: [main] Received possible protocol arguments: 3
2020-03-26T20:25:28.224Z - info: [main] Processing protocol url
2020-03-26T20:25:28.437Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:25:58.227Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-03-26T20:25:58.561Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at t.Dispatcher.dispatchURLAction (C:\Users\bhand\AppData\Local\GitHubDesktop\app-2.2.4\webpack:\app\src\ui\dispatcher\dispatcher.ts:1391:32)
2020-03-26T20:26:08.027Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:26:58.698Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:28:05.995Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:28:38.940Z - info: [ui] [AppStore] loading 1 repositories from store
2020-03-26T20:28:39.130Z - info: [ui] launching: 2.2.4 (Windows 10.0.18362)
2020-03-26T20:28:39.131Z - info: [ui] execPath: 'C:\Users\bhand\AppData\Local\GitHubDesktop\app-2.2.4\GitHubDesktop.exe'
2020-03-26T20:28:39.719Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:28:39.866Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:29:09.838Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2020-03-26T20:30:39.470Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:30:45.012Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T20:32:15.436Z - info: [ui] Current tutorial step is NotApplicable
2020-03-26T21:13:52.717Z - info: [main] Received possible protocol arguments: 2
2020-03-26T21:13:52.720Z - error: [main] Malformed launch arguments received: C:\Users\bhand\AppData\Local\GitHubDesktop\app-2.4.0\GitHubDesktop.exe,--squirrel-firstrun
2020-03-26T21:13:53.335Z - info: [ui] [AppStore] loading 1 repositories from store
2020-03-26T21:13:54.524Z - info: [ui] launching: 2.4.0 (Windows 10.0.18362)
2020-03-26T21:13:54.525Z - info: [ui] execPath: 'C:\Users\bhand\AppData\Local\GitHubDesktop\app-2.4.0\GitHubDesktop.exe'
2020-03-26T21:13:55.620Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.118s)
2020-03-26T21:13:56.800Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---


    at AutoUpdater.emitError (electron/js2c/browser_init.js:324:24)
    at electron/js2c/browser_init.js:300:21
    at electron/js2c/browser_init.js:431:14
    at ChildProcess.<anonymous> (electron/js2c/browser_init.js:413:14)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
2020-03-26T21:14:25.068Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2020-03-26T21:18:13.381Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.851s)
2020-03-26T21:20:46.651Z - info: [ui] [AppStore] loading 1 repositories from store
2020-03-26T21:20:47.142Z - info: [ui] launching: 2.4.0 (Windows 10.0.18362)
2020-03-26T21:20:47.143Z - info: [ui] execPath: 'C:\Users\bhand\AppData\Local\GitHubDesktop\app-2.4.0\GitHubDesktop.exe'
2020-03-26T21:20:48.452Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.290s)
2020-03-26T21:20:48.452Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.749s)
2020-03-26T21:20:48.468Z - info: [ui] Executing getRemotes: git remote -v (took 1.817s)
2020-03-26T21:21:17.764Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch

**Comment by tierninho** [comment]
Thanks for the logs. Here is the error:

```2020-03-26T20:25:58.227Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-03-26T20:25:58.561Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
```

Are you behind a proxy server of some sort? If that is the case, the latest version of desktop, v2.4, supports proxies -- just update from `Help > About` menu and let us know if you have any questions. 

Also, is there any security or firewall software running?

**Comment by tierninho** [comment]
@hritikbhandari  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
