### ISSUE TITLE
diff shows "This file is empty" for all files on one repository

### ISSUE THREAD

**Issue by gwiskur** [desktop/desktop#9386]
### Describe the bug

diff shows "This file is empty" for all files (which are non-empty) in one repository.

### Version & OS

Github Desktop Version 2.4.0
OS: Windows 10 Pro, Version 1903, OS build 18362.720

### Steps to reproduce the behavior

1. Open Github Desktop
    1.5 Click the Update to latest version link, and wait for relaunch
2. Click the dropdown to view files in one of your repositories
    2.5 Pick the repository that you most recently created or commited to

### Actual behavior

The diff shows "This file is empty" for all files in the repository

### Expected behavior

The diff should show the file contents (all in green highlight, for complete files added).

### Logs

Not sure if logs will be helpful here; attached just in case.
[2020-03-26.desktop.production.log](https://github.com/desktop/desktop/files/4396293/2020-03-26.desktop.production.log)
[2020-03-27.desktop.production.log](https://github.com/desktop/desktop/files/4396294/2020-03-27.desktop.production.log)

### Additional context

Closing and relaunching does not remedy the problem.
Removing the repository from GitHub Desktop, then adding it back again seems to resolve the problem, but it was pretty disconcerting until I figured that out.

**Comment by tierninho** [comment]
@gwiskur Apologies for the troubles with Desktop and glad you resolved the issue. I believe the diff wasn't shown because Desktop had trouble with the initial install or couldn't authenticate your repo fully.

Upon glancing at your logs, I discovered these errors:

```
2020-03-26T18:41:22.059Z - error: [main] Malformed launch arguments received: C:\Users\Glenn\AppData\Local\GitHubDesktop\app-2.4.0\GitHubDesktop.exe,--allow-file-access-from-files,--original-process-start-time=13229721680891993
```

```
stderr:
fatal: not a git repository (or any of the parent directories): .git

(The error was parsed as 28: This is not a git repository.)
```

```
Error: Failed to execute getPartialBlobContents: ENOENT
    at ChildProcess.<anonymous> (C:\Users\Glenn\AppData\Local\GitHubDesktop\app-2.3.1\webpack:\app\src\lib\git\spawn.ts:46:20)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
2020-03-27T02:13:42.249Z - error: [ui] Could not load new contents for syntax highlighting
Error: ENOENT: no such file or directory, open 'C:\Users\Glenn\Documents\GitHub\open_calcs\main\templates\organizations\organization-user-add.html'
```

The first error has popped up a few times due to a modified registry, although it could be other security software causing issues. See this section in our known issues doc if you'd like to learn more about the registry:

https://github.com/desktop/desktop/blob/development/docs/known-issues.md#authentication-errors-due-to-modified-registry-entries

In the past, `ENOENT` errors have been resolved with a fresh install. Glad you didn't have to get to that stage. I am posting the steps for anyone else who may run into this:

Here's how to do that:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Hope this helped and thanks for using Desktop.
