### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by otenporto** [desktop/desktop#9415]
**Issue**

I'm new to Github and tried to install Github Desktop's latest version on my 64bit Win 10. I keep getting an "Installation has failed" error though, along with the following log. Does anybody know what I should do? :´(

**Screenshot**

![123](https://user-images.githubusercontent.com/62725667/77979276-92d39c00-72da-11ea-8d3b-bf03d89cbe04.png)

**Error log**

2020-03-30 20:48:53> Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC
2020-03-30 20:48:53> Program: Starting install, writing to C:\Users\USUARIO\AppData\Local\SquirrelTemp
2020-03-30 20:48:53> Program: About to install to: C:\Users\USUARIO\AppData\Local\GitHubDesktop
2020-03-30 20:48:53> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\USUARIO\AppData\Local\GitHubDesktop\packages\.betaId'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2020-03-30 20:48:53> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\USUARIO\AppData\Local\GitHubDesktop\packages\RELEASES'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2020-03-30 20:48:53> CheckForUpdateImpl: Reading RELEASES file from C:\Users\USUARIO\AppData\Local\SquirrelTemp
2020-03-30 20:48:53> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2020-03-30 20:48:54> ApplyReleasesImpl: Writing files to app directory: C:\Users\USUARIO\AppData\Local\GitHubDesktop\app-2.4.0
2020-03-30 20:48:57> LogHost: Rigging execution stub for GitHubDesktop_ExecutionStub.exe to C:\Users\USUARIO\AppData\Local\GitHubDesktop\GitHubDesktop.exe

**Comment by steveward** [comment]
Thanks for the report @otenporto. Are you running any antivirus or other security software on this machine that could be blocking the installation from completing?

**Comment by otenporto** [comment]
I tried running it the 1st time while Bitdefender was on and got the error. I've disabled it, cleaned the files on LocalAppData and re-downloaded the installer, didn't help. Even tried uninstalling Bitdefender, didn't work either :/.

**Comment by steveward** [comment]
@otenporto have you been able to install any other Electron applications like Slack/Atom/Discord without issue?

Can you also check to see if there is anything in the Event Viewer that might shed some light on why the installation is failing?

1. Open `Event Viewer`
2. In the left sidebar, expand "Windows Logs" and select "Application"
3. In the right sidebar, select "Filter Current Log..." and check the "Error" event level.

Let me know if you see anything related to GitHub Desktop there.

**Comment by otenporto** [comment]
> @otenporto have you been able to install any other Electron applications like Slack/Atom/Discord without issue?

Actually, I installed Discord Desktop an hour or so before I attempted to install Github Desktop. No problems whatsoever. 

> Can you also check to see if there is anything in the Event Viewer that might shed some light on why the installation is failing?

I ran the installer again. Two errors appeared on the list along with a information. One of the errors mentions **.NET Runtime** and the other a certain **KERNELBASE.dll.** Could it be related to net framework, maybe?

![Event Properties - Errors and Information](https://user-images.githubusercontent.com/62725667/78189145-e3b4d300-7447-11ea-8e5f-1cb1114c8a6e.png)

**Comment by steveward** [comment]
Thanks for sharing those logs @otenporto. There are a couple of things you can try to verify that there are no issues with your installation of Windows:

- Open up an elevated command prompt and run `sfc \scannow`. This will scan your system for any issues that may be causing the installation to fail, such as missing DLLs.

- Run the .NET Framework Repair Tool. This will scan your system for any issues with your .NET installation and attempt to repair them. You can download that here:

http://www.microsoft.com/en-us/download/details.aspx?id=30135

Let me know if either of those steps helps.

**Comment by steveward** [comment]
@otenporto since we haven't heard back from you I am going to close this issue out. Let me know if you are still having any problems.
