### ISSUE TITLE
[win10-uwp]clone is auth failed

### ISSUE THREAD

**Issue by Michael-Lee-Wang** [desktop/desktop#9465]
### Login is ok

###no logs
reason: no permissions of %Appdata%/GitHub desktop/logs

### clone, auth failed and then input username and password retry failed.

I think it has something to do with uwp app's permissions.

**Comment by steveward** [comment]
Thanks for the report @Michael-Lee-Wang. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by Michael-Lee-Wang** [comment]
I found that in C:\Program Files\WindowsApps\**GithubDesktop**\.
``` log
2020-04-08 00:19:57> Program: Starting Squirrel Updater: --install .
2020-04-08 00:19:57> Program: Starting install, writing to C:\Users\Michael\AppData\Local\SquirrelTemp
2020-04-08 00:19:57> Program: About to install to: C:\Users\Michael\AppData\Local\GitHubDesktop
2020-04-08 00:19:57> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Michael\AppData\Local\GitHubDesktop\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2020-04-08 00:19:57> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Michael\AppData\Local\GitHubDesktop\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2020-04-08 00:19:57> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Michael\AppData\Local\SquirrelTemp
2020-04-08 00:19:57> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2020-04-08 00:19:57> ApplyReleasesImpl: Writing files to app directory: C:\Users\Michael\AppData\Local\GitHubDesktop\app-2.4.0
2020-04-08 00:19:59> LogHost: Rigging execution stub for GitHubDesktop_ExecutionStub.exe to C:\Users\Michael\AppData\Local\GitHubDesktop\GitHubDesktop.exe
2020-04-08 00:20:18> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Michael\AppData\Local\GitHubDesktop\app-2.4.0\GitHubDesktop.exe]
2020-04-08 00:20:22> ApplyReleasesImpl: Starting fixPinnedExecutables
2020-04-08 00:20:22> ApplyReleasesImpl: Fixing up tray icons
2020-04-08 00:20:22> ApplyReleasesImpl: cleanDeadVersions: for version 2.4.0
2020-04-08 00:20:22> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.4.0
```

![image](https://user-images.githubusercontent.com/23114200/78912644-6da11380-7aba-11ea-992f-fe8fde473140.png)

> So, %AppData%\Local\ has no any files about GitHubDesktop.
> I'm sure there are not enough permissions as uwp application. When I add full control permissions to the 'C:\Program Files\WindowsApps', clone work well, but it's unsafe.

**Comment by Lazer39** [comment]
OK

**Comment by steveward** [comment]
@Michael-Lee-Wang did you possibly install GitHub Desktop from the Microsoft Store? I just discovered there is an unofficial UWP app that someone published (without GitHub's permission) to the Microsoft Store. This has not been tested officially by GitHub so I would recommend not using this version. The official version of GitHub Desktop can be downloaded here:

http://desktop.github.com

**Comment by Michael-Lee-Wang** [comment]
@steveward  ok, i got it. Thanks!
