### ISSUE TITLE
Setup to contribute - yarn issue

### ISSUE THREAD

**Issue by oleg3790** [desktop/desktop#9625]
### Describe the bug
I'm preparing to contribute (after following this [outline](https://github.com/desktop/desktop/blob/development/docs/contributing/setup-windows.md)), but am getting blocked by the following error when running `yarn`, has anyone else encountered this before?

**Using:**
- Windows 10.0.18362 Build 18362
- Node 10.12.0
- Python 2.7.18
- Yarn 1.21.1

```
PS C:\Users\oleg3\Documents\Development Projects\GitHub\desktop> yarn
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.3: The platform "win32" is incompatible with this module.
info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ ts-node -P script/tsconfig.json script/post-install.ts
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
[1/4] ⠐ dugite
[2/4] ⠐ fs-admin
[3/4] ⠈ keytar
error C:\Users\oleg3\Documents\Development Projects\GitHub\desktop\app\node_modules\registry-js: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: C:\Users\oleg3\Documents\Development Projects\GitHub\desktop\app\node_modules\registry-js
Output:
C:\Users\oleg3\Documents\Development Projects\GitHub\desktop\app\node_modules\node-abi\index.js:30
  throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
  ^

Error: Could not detect abi for version 7.1.8 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at getAbi (C:\Users\oleg3\Documents\Development Projects\GitHub\desktop\app\node_modules\node-abi\index.js:30:9)
    at module.exports (C:\Users\oleg3\Documents\Development Projects\GitHub\desktop\app\node_modules\registry-js\node_modules\prebuild-install\rc.js:73:57)
    at Object.<anonymous> (C:\Users\oleg3\Documents\Development Projects\GitHub\desktop\app\node_modules\registry-js\node_modules\prebuild-install\bin.js:9:25)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)

C:\Users\oleg3\Documents\Development Projects\GitHub\desktop\app\node_modules\registry-js>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.12.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\ProgramData\\nvm\\v10.12.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2019',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\oleg3\\Documents\\Development Projects\\GitHub\\desktop\\app\\node_modules\\registry-js\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\ProgramData\\nvm\\v10.12.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\oleg3\\.node-gyp\\7.1.8\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\oleg3\\.node-gyp\\7.1.8',
gyp info spawn args   '-Dnode_gyp_dir=C:\\ProgramData\\nvm\\v10.12.0\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\oleg3\\.node-gyp\\7.1.8\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\oleg3\\Documents\\Development Projects\\GitHub\\desktop\\app\\node_modules\\registry-js',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\oleg3\\Documents\\Development Projects\\GitHub\\desktop\\app\\node_modules\\registry-js\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\ProgramData\nvm\v10.12.0\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\ProgramData\nvm\v10.12.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\ProgramData\nvm\v10.12.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\ProgramData\nvm\v10.12.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\ProgramData\nvm\v10.12.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\ProgramData\nvm\v10.12.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\ProgramData\nvm\v10.12.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2019'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\ProgramData\nvm\v10.12.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\oleg3\Documents\Development Projects\GitHub\desktop\app\node_modules\registry-js
gyp ERR! node -v v10.12.0



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Steps to reproduce the behavior

1. Clone my forked desktop repo: https://github.com/oleg3790/desktop
2. Execute `yarn`

### Additional context

I tried installing `node-abi` as it seems to be complaining about it and didn't see any transitive dependency on it, but that did nothing.

**Comment by say25** [comment]
The step around `npm config set msvs_version 2019` was missed. I work with Oleg on this offline.
