### ISSUE TITLE
S.P.S.C. = git.exe not found (While creating a repository for it)

### ISSUE THREAD

**Issue by shahoob** [desktop/desktop#9627]
### Describe the bug

The GitHub Desktop App doesn't know
where git.exe is.

When i want to create S.P.S.C. (stands for 'Super. Password. Strength. Checker.')

### Version & OS

Version: 2.4.2
OS Version: Windows 10 Pro Build 1909

### Steps to reproduce the behavior

1. Click on repository selector, then 'Add'
2. Click on option 'Create new repository'
3. Fill in some stuff (as normal)
4. Click on 'Create repository'

### Expected behavior

No errors

### Actual behavior

The GitHub Desktop App can't find it,
while something is there.

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/33746450/80305314-581b3180-87bc-11ea-8eb3-ea452fc3a904.png)
![Screenshot (2)](https://user-images.githubusercontent.com/33746450/80305316-5b162200-87bc-11ea-8931-12356301064c.png)
![Screenshot (3)](https://user-images.githubusercontent.com/33746450/80305317-5d787c00-87bc-11ea-8314-5370132b22f5.png)
![Screenshot (4)](https://user-images.githubusercontent.com/33746450/80305319-5ea9a900-87bc-11ea-9ff9-4fc7e5274620.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

```
2020-04-26T10:30:55.522Z - info: [ui] [AppStore] loading 36 repositories from store
2020-04-26T10:30:55.524Z - info: [ui] [AppStore] found account: shahoob (Shehab Tweel)
2020-04-26T10:30:56.597Z - info: [ui] launching: 2.4.2 (Windows 10.0.18363)
2020-04-26T10:30:56.598Z - info: [ui] execPath: 'C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\GitHubDesktop.exe'
2020-04-26T10:30:57.395Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.118s)
2020-04-26T10:30:57.990Z - info: [ui] Stats reported.
2020-04-26T10:32:59.654Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.890s)
2020-04-26T10:33:00.407Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: blockly - shahoob (has token)
2020-04-26T10:33:03.543Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 3.004s)
2020-04-26T10:33:38.030Z - info: [ui] Background fetch for 36 repositories took 42.377sec
2020-04-26T10:33:41.516Z - error: [ui] createRepository: unable to initialize a Git repository at C:\Users\sheha\Documents\GitHub\S.P.S.C.
Error: Git could not be found at the expected path: 'C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\resources\app\git\cmd\git.exe'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\webpack:\app\node_modules\dugite\build\lib\git-process.js:87:1
    at exithandler (child_process.js:315:5)
    at ChildProcess.errorhandler (child_process.js:327:5)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
2020-04-26T10:34:40.847Z - error: [ui] createRepository: unable to initialize a Git repository at C:\Users\sheha\Documents\GitHub\S.P.S.C.
Error: Git could not be found at the expected path: 'C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\resources\app\git\cmd\git.exe'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\webpack:\app\node_modules\dugite\build\lib\git-process.js:87:1
    at exithandler (child_process.js:315:5)
    at ChildProcess.errorhandler (child_process.js:327:5)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
2020-04-26T10:35:29.754Z - info: [ui] [AppStore] loading 36 repositories from store
2020-04-26T10:35:29.754Z - info: [ui] [AppStore] found account: shahoob (Shehab Tweel)
2020-04-26T10:35:30.622Z - info: [ui] launching: 2.4.2 (Windows 10.0.18363)
2020-04-26T10:35:30.623Z - info: [ui] execPath: 'C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\GitHubDesktop.exe'
2020-04-26T10:36:04.227Z - error: [ui] createRepository: unable to initialize a Git repository at C:\Users\sheha\Documents\GitHub\S.P.S.C.
Error: Git could not be found at the expected path: 'C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\resources\app\git\cmd\git.exe'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\webpack:\app\node_modules\dugite\build\lib\git-process.js:87:1
    at exithandler (child_process.js:315:5)
    at ChildProcess.errorhandler (child_process.js:327:5)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
2020-04-26T10:38:01.511Z - info: [ui] Background fetch for 36 repositories took 31.675sec
2020-04-26T10:43:39.257Z - error: [ui] createRepository: unable to initialize a Git repository at C:\Users\sheha\Documents\GitHub\S.P.S.C.
Error: Git could not be found at the expected path: 'C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\resources\app\git\cmd\git.exe'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\webpack:\app\node_modules\dugite\build\lib\git-process.js:87:1
    at exithandler (child_process.js:315:5)
    at ChildProcess.errorhandler (child_process.js:327:5)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
2020-04-26T10:45:05.183Z - info: [ui] [AppStore] loading 36 repositories from store
2020-04-26T10:45:05.184Z - info: [ui] [AppStore] found account: shahoob (Shehab Tweel)
2020-04-26T10:45:05.797Z - info: [ui] launching: 2.4.2 (Windows 10.0.18363)
2020-04-26T10:45:05.797Z - info: [ui] execPath: 'C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\GitHubDesktop.exe'
2020-04-26T10:45:14.750Z - info: [ui] [AppStore] adding repository at C:\Users\sheha\Documents\GitHub\te to store
2020-04-26T10:45:39.344Z - error: [ui] createRepository: unable to initialize a Git repository at C:\Users\sheha\Documents\GitHub\S.P.S.C.
Error: Git could not be found at the expected path: 'C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\resources\app\git\cmd\git.exe'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\webpack:\app\node_modules\dugite\build\lib\git-process.js:87:1
    at exithandler (child_process.js:315:5)
    at ChildProcess.errorhandler (child_process.js:327:5)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
2020-04-26T10:50:16.108Z - info: [ui] [AppStore] loading 36 repositories from store
2020-04-26T10:50:16.109Z - info: [ui] [AppStore] found account: shahoob (Shehab Tweel)
2020-04-26T10:50:16.880Z - info: [ui] launching: 2.4.2 (Windows 10.0.18363)
2020-04-26T10:50:16.880Z - info: [ui] execPath: 'C:\Users\sheha\AppData\Local\GitHubDesktop\app-2.4.2\GitHubDesktop.exe'
2020-04-26T10:50:39.842Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.680s)
```

### Additional context

I don't know what's going on.

NOTE: Other names (like 'te', just to test) may work.
as expected.

**Comment by shahoob** [comment]
nevermind.

it worked.
you can ignore this.

This issue will be closed,
any contributors and owner can
reopen if happened.

**Comment by Maxxxxz** [comment]
After some trial and error with the same problem, the error message is not very helpful. **The problem is the use of periods in the title of repo**. Remove the periods and this should work. Hopefully this helps anyone having this issue in the future.

**Comment by shahoob** [comment]
Ok, didn't know that
but I no longer use GitHub desktop anymore.
