### ISSUE TITLE
Repositories automatically got deleted on GitHub Desktop.

### ISSUE THREAD

**Issue by mk210** [desktop/desktop#9704]
### Describe the bug

While i was using the GitHub Desktop App, all my cloned repositories got deleted from the local directory. It is still available online though. I was trying to edit a file and suddenly all my files and folders in the directory got deleted.

### Version & OS

V 2.4.3

### Steps to reproduce the behavior

This is what i did,
1. Open Visual Studio Code via GitHub Desktop.
2. Selected a File to edit
3. Trying to create a new Markdown File
4. All The folders just deleted.

### Expected behavior

A New Markdown file was supposed to be created.

### Actual behavior

Instead of creating a new file, All the folders have been deleted.
### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

N/A
### Additional context

I have Checked for updates and it is said i have the latest updates, so i am not sure of the actual problem which is leading to this behaviour.

**Comment by billygriffin** [comment]
@mk210 Thanks for the issue and sorry about that - that's definitely not intended behavior and not something we've ever seen in GitHub Desktop before. Do you mind sharing your log file from when this occurred? You can find it in `Help` -> `Show Logs in Finder/Explorer`

**Comment by mk210** [comment]
@billygriffin  These are the logs for when it hapenned.

2020-05-05T07:11:13.569Z - info: [ui] [AppStore] loading 3 repositories from store
2020-05-05T07:11:13.570Z - info: [ui] [AppStore] found account: mk210 (mk210 Katta)
2020-05-05T07:11:14.190Z - info: [ui] launching: 2.4.0 (Windows 10.0.18362)
2020-05-05T07:11:14.191Z - info: [ui] execPath: 'C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.0\GitHubDesktop.exe'
2020-05-05T07:11:14.889Z - info: [ui] Stats reported.
2020-05-05T07:13:58.806Z - info: [ui] [AppStore] loading 3 repositories from store
2020-05-05T07:13:58.807Z - info: [ui] [AppStore] found account: mk210 (mk210 Katta)
2020-05-05T07:13:59.313Z - info: [ui] launching: 2.4.0 (Windows 10.0.18362)
2020-05-05T07:13:59.313Z - info: [ui] execPath: 'C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.0\GitHubDesktop.exe'
2020-05-05T07:14:01.666Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T07:14:35.510Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T07:14:35.511Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/Tech-club/Tech-Club-Blog.git - mk210 (has token)
2020-05-05T07:14:40.279Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/Tech-club/Tech-Club-Blog.git C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.3.1\Tech-Club-Blog (took 4.714s)
2020-05-05T07:14:40.321Z - info: [ui] [AppStore] adding repository at C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.3.1\Tech-Club-Blog to store
2020-05-05T07:14:40.567Z - info: [ui] [BranchPruner] No branches to prune.
2020-05-05T07:14:40.641Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T07:14:40.908Z - warn: [ui] Unable to fetch issues for Tech-club/Tech-Club-Blog
Error: Cannot get issues for a repository that hasn't been inserted into the database!
    at Object.n [as fatalError] (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.0\webpack:\external "path":1:1)
    at t.IssuesStore.getLatestUpdatedAt (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.0\webpack:\app\src\lib\stores\issues-store.ts:29:14)
    at t.IssuesStore.refreshIssues (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.0\webpack:\app\src\lib\stores\issues-store.ts:66:5)
    at Ye._refreshIssues (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.0\webpack:\app\src\lib\stores\app-store.ts:1605:6)
    at Ye._selectRepositoryRefreshTasks (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.0\webpack:\app\src\lib\stores\app-store.ts:1533:12)
    at Ye._selectRepository (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.0\webpack:\app\src\lib\stores\app-store.ts:1503:4)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.0\webpack:\app\src\ui\dispatcher\dispatcher.ts:618:6
    at Ye._completeOpenInDesktop (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.0\webpack:\app\src\lib\stores\app-store.ts:4726:20)
2020-05-05T07:14:41.267Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T07:14:43.007Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.535s)
2020-05-05T07:15:58.858Z - info: [ui] Background fetch for 3 repositories took 0.001sec
2020-05-05T07:16:43.555Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2020-05-05T07:16:48.086Z - info: [ui] [BranchPruner] No branches to prune.
2020-05-05T07:16:48.091Z - error: [ui] Error performing periodic fetch for 'mk210/DBMS-Coursework'
Error: Unable to find path to repository on disk.
    at C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.0\webpack:\app\node_modules\dugite\build\lib\git-process.js:87:1
    at exithandler (child_process.js:315:5)
    at ChildProcess.errorhandler (child_process.js:327:5)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
2020-05-05T07:18:05.775Z - info: [ui] [AppStore] loading 2 repositories from store
2020-05-05T07:18:05.777Z - info: [ui] [AppStore] found account: mk210 (mk210 Katta)
2020-05-05T07:18:06.126Z - info: [ui] launching: 2.4.3 (Windows 10.0.18362)
2020-05-05T07:18:06.126Z - info: [ui] execPath: 'C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\GitHubDesktop.exe'
2020-05-05T07:20:05.804Z - info: [ui] Background fetch for 2 repositories took 0.000sec
2020-05-05T07:26:39.853Z - info: [ui] [AppStore] loading 2 repositories from store
2020-05-05T07:26:39.854Z - info: [ui] [AppStore] found account: mk210 (mk210 Katta)
2020-05-05T07:26:40.132Z - info: [ui] launching: 2.4.3 (Windows 10.0.18362)
2020-05-05T07:26:40.132Z - info: [ui] execPath: 'C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\GitHubDesktop.exe'
2020-05-05T07:26:49.884Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T07:26:49.886Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/Tech-club/Tech-Club-Blog.git - mk210 (has token)
2020-05-05T07:26:55.273Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/Tech-club/Tech-Club-Blog.git C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.3.1\Tech-Club-Blog (took 5.322s)
2020-05-05T07:26:55.315Z - info: [ui] [AppStore] adding repository at C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.3.1\Tech-Club-Blog to store
2020-05-05T07:26:55.609Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T07:26:55.803Z - warn: [ui] Unable to fetch issues for Tech-club/Tech-Club-Blog
Error: Cannot get issues for a repository that hasn't been inserted into the database!
    at Object.n [as fatalError] (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\external "path":1:1)
    at t.IssuesStore.getLatestUpdatedAt (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\app\src\lib\stores\issues-store.ts:29:14)
    at t.IssuesStore.refreshIssues (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\app\src\lib\stores\issues-store.ts:66:5)
    at Xe._refreshIssues (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\app\src\lib\stores\app-store.ts:1626:6)
    at Xe._selectRepositoryRefreshTasks (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\app\src\lib\stores\app-store.ts:1554:12)
    at Xe._selectRepository (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\app\src\lib\stores\app-store.ts:1524:4)
    at C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\app\src\ui\dispatcher\dispatcher.ts:652:6
    at Xe._completeOpenInDesktop (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\app\src\lib\stores\app-store.ts:4778:20)
2020-05-05T07:26:56.104Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T07:26:58.481Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Tech-Club-Blog - mk210 (has token)
2020-05-05T07:27:00.436Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.899s)
2020-05-05T07:27:00.950Z - warn: [ui] Unable to fetch issues for Tech-club/Tech-Club-Blog
Error: Cannot get issues for a repository that hasn't been inserted into the database!
    at Object.n [as fatalError] (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\external "path":1:1)
    at t.IssuesStore.getLatestUpdatedAt (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\app\src\lib\stores\issues-store.ts:29:14)
    at t.IssuesStore.refreshIssues (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\app\src\lib\stores\issues-store.ts:66:5)
    at Xe._refreshIssues (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\app\src\lib\stores\app-store.ts:1626:6)
    at C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\app\src\lib\stores\app-store.ts:4155:18
    at Xe.withPushPullFetch (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\app\src\lib\stores\app-store.ts:3735:7)
    at Xe.performFetch (C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\webpack:\app\src\lib\stores\app-store.ts:4100:5)
2020-05-05T07:28:40.902Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T07:28:40.903Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Tech-Club-Blog - mk210 (has token)
2020-05-05T07:28:42.996Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.028s)
2020-05-05T07:28:43.589Z - info: [ui] Background fetch for 3 repositories took 3.706sec
2020-05-05T07:43:44.406Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T07:43:44.406Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Tech-Club-Blog - mk210 (has token)
2020-05-05T07:43:46.351Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.881s)
2020-05-05T07:43:46.863Z - info: [ui] Background fetch for 3 repositories took 3.269sec
2020-05-05T08:13:32.188Z - warn: [ui] getFetchPollInterval: failed for Tech-club/Tech-Club-Blog
TypeError: Failed to fetch
2020-05-05T08:13:32.894Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 3.931s)
2020-05-05T08:13:36.353Z - warn: [ui] fetchRepository: an error occurred for 'Tech-club/Tech-Club-Blog'
TypeError: Failed to fetch
2020-05-05T08:13:36.353Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Tech-Club-Blog - mk210 (has token)
2020-05-05T08:13:41.701Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.213s)
2020-05-05T08:13:43.161Z - info: [ui] Background fetch for 3 repositories took 14.192sec
2020-05-05T08:13:44.322Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T08:13:44.323Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Tech-Club-Blog - mk210 (has token)
2020-05-05T08:13:48.040Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 3.613s)
2020-05-05T08:13:48.627Z - info: [ui] Background fetch for 3 repositories took 5.037sec
2020-05-05T08:28:44.509Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T08:28:44.509Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Tech-Club-Blog - mk210 (has token)
2020-05-05T08:28:46.423Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.851s)
2020-05-05T08:28:47.289Z - info: [ui] Background fetch for 3 repositories took 3.701sec
2020-05-05T08:43:44.219Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T08:43:44.219Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Tech-Club-Blog - mk210 (has token)
2020-05-05T08:43:46.189Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.915s)
2020-05-05T08:43:47.188Z - info: [ui] Background fetch for 3 repositories took 3.600sec
2020-05-05T08:58:44.189Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T08:58:44.190Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Tech-Club-Blog - mk210 (has token)
2020-05-05T08:58:46.120Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.874s)
2020-05-05T08:58:46.693Z - info: [ui] Background fetch for 3 repositories took 3.107sec
2020-05-05T09:13:44.225Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T09:13:44.226Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Tech-Club-Blog - mk210 (has token)
2020-05-05T09:13:46.221Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.939s)
2020-05-05T09:13:46.844Z - info: [ui] Background fetch for 3 repositories took 3.258sec
2020-05-05T09:28:44.162Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T09:28:44.163Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Tech-Club-Blog - mk210 (has token)
2020-05-05T09:28:46.859Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.599s)
2020-05-05T09:28:47.838Z - info: [ui] Background fetch for 3 repositories took 4.252sec
2020-05-05T09:43:44.215Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T09:43:44.215Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Tech-Club-Blog - mk210 (has token)
2020-05-05T09:43:46.284Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.012s)
2020-05-05T09:43:47.134Z - info: [ui] Background fetch for 3 repositories took 3.543sec
2020-05-05T13:45:56.869Z - info: [ui] [AppStore] loading 3 repositories from store
2020-05-05T13:45:56.870Z - info: [ui] [AppStore] found account: mk210 (mk210 Katta)
2020-05-05T13:45:57.992Z - warn: [ui] fetchRepository: 'Tech-club/Tech-Club-Blog' returned a 404
2020-05-05T13:45:58.271Z - info: [ui] launching: 2.4.3 (Windows 10.0.18362)
2020-05-05T13:45:58.272Z - info: [ui] execPath: 'C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.4.3\GitHubDesktop.exe'
2020-05-05T13:45:59.417Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.353s)

But now, everything seems to be working as it should after i have re-cloned my repository back to my system.

**Comment by steveward** [comment]
Thanks for sharing the log file @mk210. 

It looks like you were storing your repositories where GitHub Desktop installs in `%LocalAppData%\GitHubDesktop\app-2.3.1`:

```
2020-05-05T07:14:40.279Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/Tech-club/Tech-Club-Blog.git C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.3.1\Tech-Club-Blog (took 4.714s)
2020-05-05T07:14:40.321Z - info: [ui] [AppStore] adding repository at C:\Users\mk210\AppData\Local\GitHubDesktop\app-2.3.1\Tech-Club-Blog to store
```

Here's what I belive happened:

1. Your repositories were stored in `%LocalAppData%\GitHubDesktop\app-2.3.1`
2. You were running version `2.4.0` of GitHub Desktop (stored in `app-2.4.0`)
3. GitHub Desktop updated to `v2.4.3`
4. GitHub Desktop cleaned up the older `app-2.3.1` directory to free up space on disk, and as a result your stored repositories were deleted.

We do not recommend storing repositories in the `%LocalAppData%\GitHubDesktop` directory since things can changes there as the application updates. By default GitHub Desktop recommends storing your repositories in the `Documents\GitHub` directory, which is where I would recommend you move your existing repositories to if they are still stored in `%LocalAppData%`.

Let me know if you have any further questions about this.
