### ISSUE TITLE
Failed to fetch when I try to login the Github Desktop, prompt "Failed to fetch"

### ISSUE THREAD

**Issue by eric91w** [desktop/desktop#9736]
### Describe the bug
Failed to fetch when I try to login the Github Desktop
prompt "Failed to fetch"

### Version & OS
Version: app-2.4.3
OS: Windows 10.0.18363

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to 'file->option'
2. Click on 'Sign in (Github.com)'
3. Input my username/email and password
4. Click on 'Sign in' 
5. See error "Failed to fetch"

### Expected behavior
sign in github desktop

### Actual behavior
failed to sign in github desktop
A clear and concise description of what actually happened.

### Screenshots
![image](https://user-images.githubusercontent.com/26499298/81364556-8849c500-9118-11ea-851c-50496b87f69e.png)

Add screenshots to help explain your problem, if applicable.

### Logs
2020-05-08T02:33:22.953Z - info: [main] Received possible protocol arguments: 2
2020-05-08T02:33:22.955Z - error: [main] Malformed launch arguments received: C:\Users\mouya\AppData\Local\GitHubDesktop\app-2.4.3\GitHubDesktop.exe,--squirrel-firstrun
2020-05-08T02:33:23.328Z - info: [ui] [AppStore] loading 0 repositories from store
2020-05-08T02:33:23.343Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-05-08T02:33:23.345Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-05-08T02:33:23.411Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-05-08T02:33:23.449Z - info: [ui] launching: 2.4.3 (Windows 10.0.18363)
2020-05-08T02:33:23.449Z - info: [ui] execPath: 'C:\Users\mouya\AppData\Local\GitHubDesktop\app-2.4.3\GitHubDesktop.exe'
2020-05-08T02:33:23.471Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-05-08T02:33:24.368Z - info: [ui] Opt in reported.
2020-05-08T02:33:25.557Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---

    at AutoUpdater.emitError (electron/js2c/browser_init.js:324:24)
    at electron/js2c/browser_init.js:300:21
    at electron/js2c/browser_init.js:431:14
    at ChildProcess.<anonymous> (electron/js2c/browser_init.js:413:14)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
2020-05-08T02:33:30.093Z - info: [ui] [Welcome] advancing to step: SignInToDotCom
2020-05-08T02:33:30.094Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2020-05-08T02:33:32.987Z - info: [ui] [SignInStore] initializing OAuth flow
2020-05-08T02:33:32.987Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=d58b2d87-c4c4-40d5-96d4-68ca97d02964
2020-05-08T02:33:32.988Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-05-08T02:33:33.062Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-05-08T02:33:35.013Z - info: [main] Received possible protocol arguments: 5
2020-05-08T02:33:35.013Z - info: [main] Processing protocol url
2020-05-08T02:33:35.015Z - info: [ui] [Dispatcher] requesting authenticated user
2020-05-08T02:33:35.028Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-05-08T02:33:35.110Z - info: [main] Received possible protocol arguments: 3
2020-05-08T02:33:35.110Z - info: [main] Processing protocol url
2020-05-08T02:33:36.480Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-05-08T02:33:36.480Z - warn: [ui] fetchUser: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-05-08T02:33:36.480Z - info: [ui] [SignInStore] error with OAuth flow
TypeError: Failed to fetch
2020-05-08T02:33:36.494Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-05-08T02:33:41.727Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-05-08T02:33:42.490Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-05-08T02:33:42.494Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-05-08T02:33:43.061Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-05-08T02:33:45.662Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-05-08T02:33:49.001Z - info: [ui] [Welcome] advancing to step: Start
2020-05-08T02:33:51.612Z - info: [ui] [Welcome] advancing to step: SignInToEnterprise
2020-05-08T02:33:55.197Z - info: [ui] [Welcome] advancing to step: Start
2020-05-08T02:33:57.129Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2020-05-08T02:34:00.329Z - info: [ui] [Welcome] advancing to step: UsageOptOut
2020-05-08T02:34:04.161Z - info: [ui] Opt in reported.
2020-05-08T02:34:23.253Z - info: [ui] [SignInStore] initializing OAuth flow
2020-05-08T02:34:23.253Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=fda9d83d-e3ea-4654-ab66-4ecfec345cef
2020-05-08T02:34:24.984Z - info: [main] Received possible protocol arguments: 5
2020-05-08T02:34:24.984Z - info: [main] Processing protocol url
2020-05-08T02:34:24.985Z - info: [ui] [Dispatcher] requesting authenticated user
2020-05-08T02:34:25.083Z - info: [main] Received possible protocol arguments: 3
2020-05-08T02:34:25.084Z - info: [main] Processing protocol url
2020-05-08T02:34:26.191Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-05-08T02:34:26.191Z - warn: [ui] fetchUser: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-05-08T02:34:26.192Z - info: [ui] [SignInStore] error with OAuth flow
TypeError: Failed to fetch

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by eric91w** [comment]
I don't know why it works well again itself.

**Comment by billygriffin** [comment]
Sorry for the confusion @eric91w, glad it's fixed. Please let us know if you're seeing this again.
