### ISSUE TITLE
All repositories that were added to GithubDesktop are missing

### ISSUE THREAD

**Issue by MostHated** [desktop/desktop#9954]
### Describe the bug
I had a long list of dozens of repos that were added to Github desktop and I used the app to keep them up to date, view their changes, etc, but I opened it today and they are all missing. It might not have been so bad if the window that said "Drag repos here to add them" was still there, but as soon as you add one, that goes away, so I would have to go to file, add repo, etc, etc for each one. 

I have backups of my system, I just need to know what the name of the file is that has the list of all my added repos so I can restore it, and want to bring it to your attention that this happened for some reason, so as to hopefully figure out why, and how to avoid it.

Thanks,
-MH

**Comment by rafeca** [comment]
Hi @MostHated ! I'm sorry you experienced this issue.

The repository-related data is stored in the IndexedDB database of Electron (located in `/Users/<username>/Library/Application Support/GitHub Desktop/IndexedDB` on OSX and ` C:\Users\<username>\AppData\Local\GitHub Desktop\IndexedDB`), but you may want to restore its parent repository to restore other data like preferences/etc.

I don't recall seeing a similar issue happening, so it would be good to get more information to be able to debug it. A few things that would help:

- Can you post your logs so we can investigate what could have triggered this problem? (you can find them via the Help menu and selecting `Show Logs...`). If they also got deleted you can find them in the `Logs` folder on  `C:\Users\<username>\AppData\Local\GitHub Desktop` inside your backup.
- Do you remember what were you doing before/once this happened?
- What operating system are you using? What GitHub Desktop version are you using?

Thanks!

**Comment by MostHated** [comment]
Thanks for the info.

As for what I was doing, I had just got on the PC that morning, gave it a restart, as I do most mornings because I have an RTX2070 video card that has some issues for some reason and causes the display driver to lag out for a few minutes, it recovers, then I restart. I just got in the habit of restarting each morning. I have been dealing with that part of it for 1.5 years or so.  

Once I logged in, I went to open the Github desktop app and was greeted by the "fresh install" window as if I never had the app installed before. 

PC: OS: Windows 10 Pro x86_64 Kernel: 10.0.19041

I will get you the logs here in a little bit and will post them up.

**Comment by MostHated** [comment]
[2020-06-08.desktop.production.zip](https://github.com/desktop/desktop/files/4748823/2020-06-08.desktop.production.zip)

**Comment by rafeca** [comment]
Thanks for the context @MostHated !

By looking at the logs I've found the exact point where your repositories disappeared:

```
2020-06-07T16:05:49.557Z - info: [ui] Background fetch for 198 repositories took 89.201sec
2020-06-07T18:39:59.203Z - info: [ui] [AppStore] loading 0 repositories from store
2020-06-07T18:39:59.204Z - info: [ui] [AppStore] found account: MostHated (MostHated)
2020-06-07T18:39:59.461Z - info: [ui] launching: 2.5.2 (Windows 10.0.19041)
2020-06-07T18:39:59.461Z - info: [ui] execPath: 'C:\Users\<redacted>\AppData\Local\GitHubDesktop\app-2.5.2\GitHubDesktop.exe'
2020-06-07T18:40:50.183Z - info: [ui] [AppStore] loading 0 repositories from store
```

(this is on L3924 of `2020-06-07.desktop.production.log`)

I see also a lot of errors that have been happening since way before that event, related to non-existant repositories, like the following one:

```
2020-06-07T16:04:41.998Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/<redacted>/<redacted>.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2020-06-07T16:04:45.184Z - warn: [ui] deserialize: invalid JSON found at 'https://api.github.com/repos/<redacted>/<redacted>' - status: 200, length: '(missing)' id: '(missing)'
TypeError: Failed to fetch
    at Response.json (<anonymous>)
    at o (C:\WINDOWS\system32\webpack:\app\src\lib\http.ts:68:5)
    at Object.t.parsedResponse (C:\WINDOWS\system32\webpack:\app\src\lib\http.ts:164:4)
    at x.fetchRepository (C:\WINDOWS\system32\webpack:\app\src\lib\api.ts:526:6)
    at Object.t.inferLastPushForRepository (C:\WINDOWS\system32\webpack:\app\src\lib\infer-last-push-for-repository.ts:41:20)
    at Xe.refreshIndicatorForRepository (C:\WINDOWS\system32\webpack:\app\src\lib\stores\app-store.ts:2869:22)
    at Xe.refreshAllSidebarIndicators (C:\WINDOWS\system32\webpack:\app\src\lib\stores\app-store.ts:2829:7)
```

I don't recall seeing similar issues before, @steveward have you ever seen something like this?

**Comment by MostHated** [comment]
That is indeed interesting. I suppose perhaps a notification is a repo is no longer longer accessible and then a "Would you like to remove from github desktop?" (but with the option to keep the files locally), would help keep them from piling up?

**Comment by MostHated** [comment]
Hmm... I have been going through and searching for ones that have the "The repository does not seem to exist anymore" messages, and so far, all of them I have checked do still exist and I do still have access to them. I am not sure what is up with that?

**Comment by MostHated** [comment]
It also seems my "Open in Desktop" button is missing. I redownloaded and installed Github Desktop, my repos are still there, but the button is missing from my browser. I am not sure if this is related?

Firefox 77.0.1 (64-bit)

**Comment by updatesvc** [comment]
Hi @rafeca 
Got the same issue how do you restore the indexDB on windows
In my indexDB folder all my files are new,.
Here is a snippet of my logs

```
2020-06-22T08:40:17.219Z - info: [ui] [AppStore] loading 0 repositories from store
2020-06-22T08:40:17.221Z - info: [ui] [AppStore] found account: updatesvc (Bob)
2020-06-22T08:40:17.929Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-06-22T08:40:17.930Z - warn: [ui] fetchUser: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2020-06-22T08:40:17.930Z - warn: [ui] Error refreshing account 'updatesvc'
TypeError: Failed to fetch
2020-06-22T08:40:17.930Z - warn: [ui] fetchRepositories: TypeError: Failed to fetch
2020-06-22T08:40:18.455Z - info: [ui] launching: 2.5.2 (Windows 10.0.18363)
2020-06-22T08:40:18.455Z - info: [ui] execPath: 'C:\Users\bob\AppData\Local\GitHubDesktop\app-2.5.2\GitHubDesktop.exe'
2020-06-22T08:40:44.231Z - info: [ui] [AppStore] loading 0 repositories from store
2020-06-22T08:40:44.233Z - info: [ui] [AppStore] found account: updatesvc (Bob)
2020-06-22T08:40:44.965Z - info: [ui] launching: 2.5.2 (Windows 10.0.18363)
2020-06-22T08:40:44.965Z - info: [ui] execPath: 'C:\Users\bob\AppData\Local\GitHubDesktop\app-2.5.2\GitHubDesktop.exe'
2020-06-22T08:42:43.407Z - info: [ui] Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup (took 1.169s)
```

**Comment by MostHated** [comment]
I back my PC up every night to my NAS. Unfortunately, without a backup, I don't think you will be able to.

**Comment by updatesvc** [comment]
> I back my PC up every night to my NAS. Unfortunately, without a backup, I don't think you will be able to.
Ooh, I guess I have to add them one by one - good thing it wasn't a lot of repos :)

**Comment by tablatronix** [comment]
#10087 

I just opened this issue, might be the same one. Just now found this. i will read it and provide any info needed also

**Comment by tierninho** [comment]
I wonder if this comment about fetching repositories via the api is helpful here? 🤔 

https://github.com/desktop/desktop/issues/7924#issuecomment-508883236

Dug through a bunch of past issues and didn't spot much else to go on.

**Comment by MostHated** [comment]
I am still not sure if this particular issue is what caused the "Open in Desktop" button in my browser to disappear, but it happened on the same day, and am still missing the button after a reinstall of Github Desktop, a reinstall of the browser, and even a second copy of the browser (The newer Dev version).

**Comment by tablatronix** [comment]
I have had an update waiting I am afraid to click it

**Comment by Luis-Fernando-Molina** [comment]
> The repository-related data is stored in the IndexedDB database of Electron (located in /Users/<username>/Library/Application Support/GitHub Desktop/IndexedDB on OSX and C:\Users\<username>\AppData\Local\GitHub Desktop\IndexedDB), but you may want to restore its parent repository to restore other data like preferences/etc.

Something similar happened to me.

> /Users/<username>/Library/Application Support/GitHub Desktop/IndexedDB

In my case the folder Library does not exists

> C:\Users\<username>\AppData\Local\GitHub Desktop\IndexedDB

And IndexedDB does not exist. 

I just shut down the app because I wanted it to refresh the branches list since I deleted one at the github.com and when I launched again, a new, never seen before screen appear, where I can only start from scratch it seems.

**Comment by darkrevenger** [comment]
Same here... I had more than 40 repos and to be honest I don't even know where they are on my PC but thats my fault for trusting a program of keeping an eye of where my proyects are.

Can't github desktop at least add a backup once every day of where they are stored?

**Comment by JonatanPlesko** [comment]
Hi,

The same issue happened to me just now. I was doing some work in Github Desktop, then I went into the terminal and executed "git branch --merged | grep -v \* | xargs git branch -D" to remove all local branches, then as I returned to Github Desktop I tried to open it by Cmd+Space, however that somehow opened another instance which seemed to be a different version or empty. I closed both instances and reopened the one I have saved in my dock, however the repositories were now completely empty (I was still logged in!). I tried to open the "other" instance again but I was unable to, and I could only really find one instance on my machine.

I also tried updating to the latest version as this happened, but the data was still lost. I'm using macOS Monterey 12.1 on a 2020 13" MBP. The logs of my actions from before this happened all the way until I tried to close and reopen the app a few times (and ended up re-adding two repositories, or more accurately, a repository and its submodule as a separate repository).

[2022-03-31T07:27:07.188Z.log](https://github.com/desktop/desktop/files/8391141/2022-03-31T07.27.07.188Z.log)

**Comment by tablatronix** [comment]
ohhhhh ssssssshhhhh not this again
![Screen Shot 2022-06-28 at 8 39 25 PM](https://user-images.githubusercontent.com/807787/176333075-17ad6029-baee-424a-ac54-13de676b0438.png)

Looks like maybe I ran out of space or application memory at some point? I rebooted just now and now this again, gone.

**Comment by Cdddo** [comment]
Just happened to me on Windows and GitHubDesktop 3.0.7. Restarted the computer and boom suddenly all the repos have disappeared from the App.
It would be very simple to add a little backup list to be able to restore the repos, while this issue gets sorted out...

**Comment by fedscornell** [comment]
same here. Restarted my computer this morning, and all repo disappeared in my git desktop. Any solutions?

**Comment by steveward** [comment]
@fedscornell @Cdddo did you notice if the app updated when this occurred?

**Comment by fedscornell** [comment]
@steveward I think so. Do you know where to check when it's updated? I have the github log files, but I didn't see "update" in the log.

**Comment by fedscornell** [comment]
@steveward Just confirmed that it's updated today and then my local repos all disappeared. My yesterday's log was 3.0.6, and today's log is 3.0.7. It says "launching: 3.0.7 (Windows 10.0.xxxxx)"

**Comment by Jump-Suit** [comment]
Can confirm mine just got wiped on `3.1.2`

**Comment by Johnjohnnyjingles** [comment]
U too cuzo

**Comment by MACHacker2** [comment]
Joe Martin has hacked me to the point of no return. I see people are getting answers on this thread, so I thought I would try to post this here even though it may not be correct. I am just trying to stop this maniac.  Anybody hello. is there a jen e?   He asked her to call him, but he is in my computer and in this phone my new iPhone 13 right as we speak.

**Comment by steveward** [comment]
Another instance in https://github.com/desktop/desktop/issues/17711

**Comment by StuartReid81** [comment]
Just did it for me too

**Comment by tidy-dev** [comment]
[Another report for 3.4.13](https://github.com/desktop/desktop/issues/19838)

Note some characteristics  the setup from the logs in case we find can similarities with others:
- macOS (Usually a windows problem)
- 100+ Repositories. (Usually people who report do have a good number because it is a larger bother to add back.. but this seems like an extraordinary case)
- There were some auth errors and repository remotes not found errors.
- Mention of multiple hosts in logs (gitlab and github)
- Use of hooks. 
- Error in fetching protected branches. 

Other notes:
- 3.4.13 only had Dugite update with git upgrades.

**Comment by fkeyzuwu** [comment]
still happens. any fix?

**Comment by jbright47** [comment]
just happened to me today

**Comment by oliviathevampire** [comment]
> just happened to me today

Same!

**Comment by zharkoristikj-rldatix** [comment]
Experienced the same after an update.

**Comment by babakks** [comment]
There's another one in #21937, 9 repos in total on Windows 10.
@tidy-dev @niik

**Comment by cachi01** [comment]
Happened to me today. Also a repo is no longer being recognized as one.

**Comment by zephyris** [comment]
And me today...

**Comment by manoadamro** [comment]
Yep. every now and then an update comes along and just wipes everything.  This has been happening from time to time since 2020 (maybe even earlier) so I doubt it's ever going to be fixed.

**Comment by tablatronix** [comment]
I am fairly sure this has to do with temporary storage getting wiped, either incomplete save or corrupt save, or host OS just wipes it (OSX does this sometimes, usually on crashes, unsafe shutdowns)

If someone could actually support this issue and provide basic info like how to backup app configuration files at the least...

Another thought is schema changes and some update script is failing to migrate the config

**Comment by AdolfoDomingues** [comment]
Just happened with me too. I made a big change in one of my repositories, so when I opened Git, it took a while to open, and it froze; I had to end the process. When I reopened git, all the repositories I had registered there were gone. Not gone from my PC, but now I have to re-add them, which will be excruciating since I have dozens of repositories across 4 or more hard drives.
