### ISSUE TITLE
Mutiple git.exe running and getting 100% in CPU

### ISSUE THREAD

**Issue by joseaugusto0** [desktop/desktop#9969]
### Describe the bug

After I update Git for Desktop (version 2.5.2), when I start the app, the main screen was running 
endlessly "Refreshing Repository", and when I open Task Manager, my CPU is getting 100% with 6,7 git.exe instances running.

### Logs

```
2020-06-09T00:23:20.304Z - info: [main] Received possible protocol arguments: 2
2020-06-09T00:23:20.309Z - error: [main] Malformed launch arguments received: C:\Users\josea\AppData\Local\GitHubDesktop\app-2.5.2\GitHubDesktop.exe,--squirrel-firstrun
2020-06-09T00:23:25.463Z - info: [ui] [AppStore] loading 0 repositories from store
2020-06-09T00:23:25.485Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-06-09T00:23:25.489Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-06-09T00:23:26.905Z - error: [ui] Error reporting opt in:
TypeError: Failed to fetch
2020-06-09T00:23:28.269Z - info: [ui] launching: 2.5.2 (Windows 10.0.19041)
2020-06-09T00:23:28.270Z - info: [ui] execPath: 'C:\Users\josea\AppData\Local\GitHubDesktop\app-2.5.2\GitHubDesktop.exe'
2020-06-09T00:23:28.274Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-06-09T00:23:29.740Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: Um ou mais erros. ---> System.Net.WebException: O nome remoto n�o p�de ser resolvido: 'central.github.com'
   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   em System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   em System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fim do rastreamento de pilha do local anterior onde a exce��o foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exce��o foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exce��o foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exce��o foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exce��o foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- Fim do rastreamento de pilha de exce��es internas ---
   em System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   em System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   em System.Threading.Tasks.Task`1.get_Result()
   em Squirrel.Update.Program.executeCommandLine(String[] args)
   em Squirrel.Update.Program.main(String[] args)
   em Squirrel.Update.Program.Main(String[] args)
---> (Exce��o Interna N� 0) System.Net.WebException: O nome remoto n�o p�de ser resolvido: 'central.github.com'
   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   em System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   em System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fim do rastreamento de pilha do local anterior onde a exce��o foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exce��o foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exce��o foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exce��o foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exce��o foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---
 at AutoUpdater.emitError (electron/js2c/browser_init.js:324:24)
    at electron/js2c/browser_init.js:300:21
    at electron/js2c/browser_init.js:431:14
    at ChildProcess.<anonymous> (electron/js2c/browser_init.js:413:14)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
2020-06-09T00:23:29.844Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.677s)
2020-06-09T00:23:31.182Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-06-09T00:23:35.156Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
2020-06-09T00:23:35.157Z - info: [ui] [SignInStore] initializing OAuth flow
2020-06-09T00:23:35.158Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=83c1cad0-f641-42b9-9682-c1ac45252bd8
2020-06-09T00:23:41.493Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2020-06-09T00:23:46.367Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-06-09T00:24:12.011Z - info: [main] Received possible protocol arguments: 5
2020-06-09T00:24:12.011Z - info: [main] Processing protocol url
2020-06-09T00:24:12.024Z - info: [ui] [Dispatcher] requesting authenticated user
2020-06-09T00:24:12.028Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-06-09T00:24:12.102Z - info: [main] Received possible protocol arguments: 3
2020-06-09T00:24:12.103Z - info: [main] Processing protocol url
2020-06-09T00:24:13.046Z - info: [ui] [SignInStore] account resolved
2020-06-09T00:24:13.046Z - info: [ui] [AppStore] adding account joseaugusto0 (joseaugusto0) to store
2020-06-09T00:24:13.050Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2020-06-09T00:24:13.086Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-06-09T00:24:13.159Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-06-09T00:24:13.567Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-06-09T00:24:24.508Z - info: [ui] [Welcome] advancing to step: UsageOptOut
2020-06-09T00:24:31.092Z - info: [ui] Opt out reported.
2020-06-09T00:24:52.727Z - info: [ui] [AppStore] adding repository at D:\Github\Estudos to store
2020-06-09T00:25:51.766Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 6.243s)
2020-06-09T00:26:25.932Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 1.224s)
```

**Comment by tierninho** [comment]
@joseaugusto0 Thank you for filing the issue and apologies for the troubles.

It looks like you had an install error when you updated Desktop:

```
2020-06-09T00:23:29.740Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: Um ou mais erros. ---> System.Net.WebException: O nome remoto nao pode ser resolvido: 'central.github.com'
```

I'd suggest a fresh copy of Desktop. Note, this will mean adding in your repositories again -- you can drag/drop them from your local to make it easier and faster.

Here are the steps to reinstall:

- Close GitHub Desktop
- Delete the `%AppData%\GitHub Desktop\` directory
- Delete the `%LocalAppData%\GitHubDesktop\` directory
- Reinstall GitHub Desktop from desktop.github.com

Hope this helps! Let us know.

**Comment by tierninho** [comment]
@joseaugusto0  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
